// Большие справочные страницы раздела /ii-modeli/ (лицензии, дообучение).
// Только смысл своими словами, без цитирования текстов лицензий и без юридических заключений.
module.exports = {
  licenzii: {
    slug: "licenzii",
    title: "Лицензии открытых ИИ-моделей простыми словами",
    description: "Что разрешают Apache 2.0, MIT, лицензия Llama, условия Gemma, некоммерческие лицензии и AGPL. Разбор для бизнеса обычным языком, без юридических формулировок.",
    h1: "Лицензии открытых моделей простыми словами",
    intro: "Лицензия открытой модели это условия, на которых правообладатель разрешает скачать файлы модели, запускать их и встраивать в свой продукт. Слово «открытая» здесь не означает «делай что хочешь»: у одних моделей условия почти такие же свободные, как у открытого софта, у других есть пороги по числу пользователей, запреты и региональные оговорки. Ниже основные типы условий обычным языком. Это объяснение для ориентирования, а не правовое заключение: вашу версию модели и ваш сценарий смотрит юрист.",
    sections: [
      {
        h2: "Открытые веса и открытый исходный код это разные вещи",
        html: "<p>Когда говорят про открытую модель, чаще всего имеют в виду открытые веса. Веса это большой файл с числами, который получился в результате обучения. Скачав его, вы можете запустить модель на своём сервере, получать от неё ответы и встраивать её в рабочие процессы, не обращаясь к чужому облаку.</p><p>Открытый исходный код в привычном смысле означает нечто большее: опубликован код, которым модель обучали, описан состав обучающих данных, и любой может воспроизвести результат с нуля. У подавляющего большинства известных моделей это не так. Публикуют готовый файл весов и техническую карточку, а кухню оставляют за кадром.</p><p>Практический вывод простой: не переносите привычки из мира обычного открытого софта на модели автоматически. Перед запуском стоит посмотреть, что именно выложили и на каких условиях.</p><ul><li>Веса модели, то есть сам файл, который вы скачиваете и запускаете.</li><li>Код запуска и вспомогательные утилиты, у них может быть своя лицензия.</li><li>Обучающие данные, которые публикуют редко и обычно на других условиях.</li><li>Отчёт или карточка модели с описанием ограничений и известных слабых мест.</li></ul>"
      },
      {
        h2: "Apache 2.0 и MIT: самые спокойные варианты",
        html: "<p>Это две классические свободные лицензии, пришедшие из мира программного обеспечения. В общих чертах они разрешают использовать материал в коммерческих продуктах, изменять его, распространять изменённые версии и не требуют открывать ваш собственный код. Для бизнеса это самый предсказуемый вариант из всех встречающихся.</p><p>Главное требование у обеих одинаковое по духу: сохранять указание авторства и текст лицензии там, где вы распространяете производный материал. Если вы просто запускаете модель внутри компании и никому не передаёте файлы, обязанностей заметно меньше, но привычка хранить исходные файлы лицензии рядом с моделью всё равно полезна.</p><p>Отличие Apache 2.0 от MIT, которое обычно называют первым, это патентная оговорка. Apache 2.0 прямо говорит о передаче прав на патенты, связанные с материалом, и одновременно предусматривает, что права прекращаются, если получатель сам начнёт патентную войну против авторов. MIT такой конструкции не содержит, она короче и проще. Юристы часто считают Apache 2.0 более защищённым вариантом именно из-за этого пункта.</p><p>Обе лицензии не дают никаких гарантий качества и снимают с авторов ответственность за последствия использования. Это не формальность, а важный момент, к которому мы вернёмся отдельно.</p>"
      },
      {
        h2: "Лицензия сообщества Llama: свободно, но с условиями",
        html: "<p>Модели семейства Llama выпускаются не под классической свободной лицензией, а под собственным документом с условиями использования. Коммерческое применение разрешено, и для подавляющего большинства компаний это работает без проблем, но набор обязанностей заметно шире, чем у Apache 2.0.</p><p>Первое, что обычно обсуждают, это порог по числу пользователей. Условия устроены так, что очень крупные сервисы, у которых аудитория продукта на момент выхода модели превышает установленный в документе порог, должны запрашивать отдельное разрешение у правообладателя. Малый и средний бизнес в этот порог не упирается никогда, но если вы планируете массовый потребительский продукт, пункт стоит прочитать внимательно.</p><p>Второе требование касается названий. Если вы распространяете производную модель или продукт на её основе, вас просят указывать происхождение и включать название семейства в имя вашей модели, а также сохранять заметное упоминание того, что продукт построен на этой модели. Это не запрет, а обязанность по оформлению, о которой легко забыть.</p><p>Третье это политика допустимого использования, отдельный документ со списком запрещённых сценариев. Он про вред людям, обход закона, введение в заблуждение и подобные вещи. Ещё один пункт, о котором часто забывают: результаты работы модели нельзя использовать для обучения посторонних моделей, кроме случаев, прямо разрешённых условиями.</p>"
      },
      {
        h2: "Условия использования вместо лицензии: случай Gemma и похожие",
        html: "<p>Часть моделей выходит не под лицензией в привычном понимании, а под документом с названием вроде условий использования. Разница не только словесная. Такой документ обычно устроен как соглашение между вами и правообладателем, и в нём чаще встречаются пункты, которых в классических лицензиях нет вовсе.</p><p>Типичный набор выглядит так: коммерческое использование разрешено, дообучение и распространение производных версий разрешены, но вы обязаны передавать те же ограничения дальше всем, кому передаёте модель, соблюдать политику запрещённых сценариев и принимать, что правообладатель оставляет за собой право потребовать прекратить использование конкретной версии, если она нарушает правила.</p><p>Для бизнеса важно понимать: это живой документ. Его могут обновить к следующему выпуску модели, и условия для новой версии окажутся не такими, как для той, что вы скачали год назад. Поэтому версия имеет значение, а дата скачивания имеет значение вдвойне.</p><p>Есть и обратная сторона. Такие условия обычно писались под широкий круг сценариев и читаются проще, чем кажется. Проблема не в жёсткости, а в том, что их почти никто не открывает.</p>"
      },
      {
        h2: "Некоммерческие лицензии и research-only",
        html: "<p>Отдельная категория, где ошибка обходится дороже всего. Лицензии вида CC BY-NC и пометки research-only, non-commercial или for research purposes only означают, что модель выложена для исследований, обучения и личных экспериментов, но не для зарабатывания денег.</p><p>Что именно считается коммерческим использованием, в таких лицензиях описано довольно широко. Под запрет попадает не только продажа доступа к модели, но и применение её внутри компании ради коммерческой выгоды: обработка клиентских обращений, генерация коммерческих текстов, помощь сотрудникам в выполнении оплачиваемой работы. Формулировки различаются, и трактовки тоже, поэтому здесь особенно нужен взгляд юриста.</p><p>Важный нюанс: некоммерческая модель не становится коммерчески пригодной после дообучения. Производная модель наследует ограничения. Точно так же ограничение не снимается тем, что вы не берёте денег именно за ответы модели, а зарабатываете на подписке, в которой она лишь одна из функций.</p><p>Практика простая. Если продукт хоть как-то связан с деньгами, некоммерческие модели годятся только для прототипа и проверки гипотезы, а на боевой контур ставят модель с подходящей лицензией. Это часто вторая модель, и переезд стоит закладывать заранее.</p>"
      },
      {
        h2: "AGPL и почему её опасается бизнес",
        html: "<p>AGPL это копилефт-лицензия. Её идея в том, что свобода должна передаваться дальше: если вы взяли материал под AGPL, изменили его и дали людям пользоваться результатом, вы обязаны открыть исходный код своей версии на тех же условиях.</p><p>Ключевое отличие от старой GPL в слове «сетевое». В классической GPL обязанность открыть код возникала при распространении программы. AGPL закрывает эту лазейку: если пользователи работают с вашей системой по сети, через сайт или через интерфейс сервиса, это приравнивается к передаче, и обязанность раскрыть код возникает всё равно.</p><p>Для компании, у которой вокруг модели построен собственный продукт, это звучит как требование отдать свои наработки. В реальности всё зависит от того, что именно попало под лицензию и где проходит граница производного произведения, а это как раз тот вопрос, на который без юриста отвечать не стоит.</p><p>В мире моделей AGPL встречается не столько у самих весов, сколько у инструментов вокруг: серверов запуска, библиотек, интерфейсов. Проверять надо весь набор, а не только файл модели.</p>"
      },
      {
        h2: "Региональные исключения: где модель нельзя использовать",
        html: "<p>Отдельная особенность последних лет: часть моделей выходит с географическими ограничениями. Встречаются формулировки, по которым лицензия не предоставляется пользователям и компаниям, находящимся в определённых регионах, чаще всего называют Европейский союз, Великобританию, Швейцарию или Южную Корею. Причина обычно регуляторная, а не техническая.</p><p>Смотреть надо не только на то, где зарегистрирована ваша компания, но и на то, где находятся пользователи продукта и где стоят серверы. Компания в ОАЭ с клиентами в Европе и сервером в Германии это уже три разные юрисдикции в одном проекте.</p><p>Ещё одно ограничение приходит с другой стороны: экспортные правила и санкционные режимы страны происхождения модели. Они не записаны в тексте лицензии, но обычно упоминаются отсылкой, и работают независимо от желания сторон.</p><p>Вывод для планирования: география проекта это часть технического задания, а не мелочь для финального этапа. Если вы работаете сразу в России и ОАЭ, проверять список доступных моделей нужно для каждого контура отдельно.</p>"
      },
      {
        h2: "Лицензия на веса и лицензия на обучающие данные",
        html: "<p>Частая путаница. Разрешение на использование весов не говорит ничего о том, на каких правах собирались тексты, картинки и записи, на которых модель обучалась. Это два разных слоя, и вопросы к ним разные.</p><p>Правообладатель модели разрешает вам её запускать, но не выдаёт гарантий, что в обучающей выборке не было материалов с чужими правами. Судебная практика вокруг этого вопроса в разных странах пока складывается, единого ответа нет, и по состоянию на сегодня осторожная позиция состоит в том, чтобы считать вопрос открытым.</p><p>Практические следствия видны там, где модель генерирует то, что потом становится вашим активом: тексты для сайта, изображения для рекламы, код в продукте. Здесь имеет смысл заранее договориться внутри компании, что именно вы публикуете от своего имени и какую проверку эти материалы проходят.</p><p>Если вы сами дообучаете модель, появляется третий слой: права на ваши собственные данные. Об этом подробнее в материале про дообучение.</p>"
      },
      {
        h2: "Что проверить бизнесу перед запуском",
        html: "<p>Практический порядок действий, который занимает немного времени и снимает большую часть будущих неприятных открытий.</p><ol><li>Проверяйте конкретную версию, а не семейство. Условия для разных выпусков одной линейки могут отличаться, и предыдущая проверка не переносится на новую модель автоматически.</li><li>Сохраняйте копию текста лицензии и карточки модели на дату скачивания, вместе с точным названием версии. Документ на сайте правообладателя может измениться, ваша копия останется доказательством того, на что вы соглашались.</li><li>Проверяйте лицензии всего набора: веса, сервер запуска, библиотеки, интерфейс, дополнительные модели вроде переводчика или распознавания речи.</li><li>Опишите свой сценарий одним абзацем и покажите его юристу вместе с сохранёнными документами. Вопрос формулируется не как «можно ли Llama», а как «можно ли нам вот это, вот так, для вот этих пользователей».</li><li>Заведите простой реестр: какая модель, какая версия, какая лицензия, где стоит, кто отвечает. При смене модели запись обновляется.</li></ol><p>Этот список не заменяет юридическую консультацию, он делает её быстрой и дешёвой, потому что юрист получает конкретику, а не просьбу разобраться в теме.</p>"
      },
      {
        h2: "Лицензия не отвечает за то, что модель сгенерирует",
        html: "<p>Момент, который упускают чаще всего. Лицензия отвечает на вопрос, имеете ли вы право запускать модель. Она не отвечает на вопрос, кто виноват, если модель выдала неверную цену, придуманный факт, некорректный медицинский или юридический совет либо оскорбительный текст.</p><p>Практически все лицензии на модели содержат отказ от гарантий и ограничение ответственности автора. То есть по умолчанию последствия ложатся на того, кто поставил модель перед клиентом, то есть на вас.</p><p>Отсюда набор мер, который относится уже не к праву, а к устройству системы: отделять справочные ответы от фактов, которые модель берёт из вашей базы, показывать источник, не давать модели самостоятельно называть цены и сроки, ставить человека на подтверждение в чувствительных сценариях, вести журнал ответов.</p><p>Чем выше цена ошибки в вашей сфере, тем раньше в проекте появляется регламент проверки. Это не бюрократия, а единственный способ спокойно отвечать на вопрос, что произойдёт, если модель ошибётся.</p>"
      },
      {
        h2: "Как это выглядит на практике при установке на свой сервер",
        html: "<p>Когда модель ставят в контур компании, лицензионная часть обычно превращается в несколько понятных артефактов. Появляется список того, что установлено, с версиями и ссылками на сохранённые документы. Появляется описание того, где хранятся данные и что именно уходит в модель. Появляется решение по географии: в каком дата-центре стоит сервер и кто из этого следует.</p><p>Дальше идут технические решения, которые вытекают из лицензионных. Некоммерческая модель уезжает на стенд, боевой контур получает модель с подходящими условиями. Инструмент под копилефт-лицензией либо заменяется, либо ставится так, чтобы вопрос производного произведения не возникал вовсе.</p><p>Отдельно фиксируется, что будет при обновлении. Новая версия модели это новая проверка условий, а не просто замена файла. Обычно это занимает полчаса и делается один раз перед обновлением, а не после того, как продукт уже работает на новых весах.</p>"
      }
    ],
    faq: [
      [
        "Что вообще означает «открытая модель»?",
        "Чаще всего это означает, что опубликованы веса, то есть файл модели, который можно скачать и запустить у себя. Код обучения и состав обучающих данных при этом обычно не раскрывают. Условия использования задаются отдельным документом, и они бывают как совсем свободными, так и довольно ограничивающими."
      ],
      [
        "Можно ли использовать открытую модель в коммерческом продукте?",
        "Зависит от конкретной лицензии и конкретной версии. Модели под Apache 2.0 и MIT обычно рассчитаны на коммерческое применение, модели с пометкой non-commercial или research-only нет. Формулировка ответа для вашего случая остаётся за юристом, который посмотрит документ и ваш сценарий."
      ],
      [
        "Наследует ли дообученная модель лицензию исходной?",
        "В общих чертах да: производная модель обычно остаётся связанной условиями исходной, включая запреты и обязанности по указанию происхождения. Считать, что дообучение снимает ограничения, опасно. Если вы планируете распространять свою версию, это отдельный вопрос к юристу."
      ],
      [
        "Почему AGPL пугает компании?",
        "Потому что эта лицензия требует открыть исходный код вашей версии, если пользователи работают с системой по сети, а не только при передаче программы. Где именно проходит граница производного произведения, зависит от архитектуры решения, и это как раз тот вопрос, который решается не самостоятельно."
      ],
      [
        "Что делать, если лицензия не действует в нашем регионе?",
        "Проверять три вещи: где зарегистрирована компания, где находятся пользователи и где физически стоит сервер. Если хотя бы один из пунктов попадает под исключение, обычно подбирают другую модель с подходящими условиями. Решение о допустимости принимает юрист, техническая часть просто даёт альтернативы."
      ],
      [
        "Кто отвечает, если модель выдаст неверный ответ клиенту?",
        "Лицензии на модели почти всегда снимают ответственность с автора модели, поэтому последствия ложатся на компанию, которая поставила её перед клиентом. Снижают риск устройством системы: ответы по своей базе знаний, показ источника, запрет называть цены и сроки самостоятельно, проверка человеком в чувствительных сценариях."
      ]
    ],
    _en: {
      title: "Open-model licenses explained in plain language",
      description: "What Apache 2.0, MIT, the Llama license, Gemma terms, non-commercial licenses and AGPL actually allow. A plain-language guide for business owners, not lawyers.",
      h1: "Open-model licenses in plain language",
      intro: "An open-model license is the set of terms under which the rights holder lets you download the model files, run them and build them into your product. In the AI world the word open does not mean do whatever you want. Some models carry terms almost as permissive as ordinary open-source software, others add user thresholds, prohibitions and regional carve-outs. What follows maps the main types in plain language. It is orientation, not legal advice: your version and your use case need a lawyer.",
      sections: [
        {
          h2: "Open weights and open source are not the same thing",
          html: "<p>When people call a model open, they usually mean open weights. Weights are a large file of numbers produced by training. Once you have that file, you can run the model on your own server, get answers from it and wire it into your business processes without calling anyone else's cloud.</p><p>Open source in the traditional sense means considerably more: the training code is published, the composition of the training data is described, and anyone can reproduce the result from scratch. For the vast majority of well-known models that is not the case. What gets published is the finished weights file and a technical model card, while the kitchen stays behind closed doors.</p><p>The practical takeaway is simple. Do not carry habits from ordinary open-source software over to models automatically. Before deployment, look at what was actually released and on what terms.</p><ul><li>The model weights, meaning the file you download and run.</li><li>The serving code and helper tools, which may carry their own separate license.</li><li>The training data, rarely published and usually under different terms.</li><li>The model card or report describing limitations and known weak spots.</li></ul>"
        },
        {
          h2: "Apache 2.0 and MIT: the calmest options",
          html: "<p>These are two classic permissive licenses inherited from the software world. Broadly speaking, both allow commercial use, modification and distribution of modified versions, and neither requires you to open your own source code. For a business this is the most predictable arrangement you will encounter.</p><p>The main obligation is similar in spirit for both: preserve the attribution and the license text wherever you distribute derived material. If you simply run the model inside your own company and never hand the files to anyone, the obligations are noticeably lighter, but keeping the original license files next to the model is still a good habit.</p><p>The difference usually mentioned first is the patent clause. Apache 2.0 explicitly addresses the grant of patent rights related to the material, and it also terminates those rights if the recipient starts patent litigation against the authors. MIT contains no such construction and is shorter and simpler. Lawyers often treat Apache 2.0 as the better protected option precisely because of that clause.</p><p>Neither license offers any warranty of quality, and both disclaim the authors' liability for consequences of use. That is not a formality, and we return to it below.</p>"
        },
        {
          h2: "The Llama community license: commercial, but with strings",
          html: "<p>The Llama family ships not under a classic permissive license but under its own terms-of-use document. Commercial use is allowed, and for the overwhelming majority of companies it works without friction, yet the set of obligations is noticeably wider than under Apache 2.0.</p><p>The point discussed most often is the user threshold. The terms are written so that very large services, whose product audience at the time the model was released exceeds the threshold stated in the document, must request separate permission from the rights holder. Small and mid-sized businesses never come close to that line, but if you are planning a mass consumer product, read the clause carefully.</p><p>The second obligation concerns naming. If you distribute a derived model or a product built on it, you are asked to state the origin, include the family name in your model's name and keep a visible notice that the product is built on this model. That is not a prohibition but a packaging duty, and it is easy to forget.</p><p>The third is the acceptable use policy, a separate document listing prohibited scenarios: harm to people, circumventing the law, deception and similar categories. One more clause people miss: model outputs may not be used to train unrelated models except where the terms explicitly allow it.</p>"
        },
        {
          h2: "Terms of use instead of a license: the Gemma pattern",
          html: "<p>Some models ship not under a license in the familiar sense but under a document called something like terms of use. The difference is more than wording. Such a document is usually structured as an agreement between you and the rights holder, and it tends to include clauses that classic licenses simply do not have.</p><p>The typical package looks like this: commercial use is allowed, fine-tuning and distributing derived versions are allowed, but you must pass the same restrictions on to anyone you hand the model to, comply with the prohibited-use policy, and accept that the rights holder reserves the right to demand that use of a specific version stops if it breaks the rules.</p><p>For a business the important part is that this is a living document. It can be updated for the next model release, and the terms for the new version may differ from the ones attached to the file you downloaded a year ago. So the version matters, and the download date matters twice as much.</p><p>There is an upside too. Such terms are usually drafted by a large company's legal team for a broad range of scenarios, and they read more clearly than people expect. The problem is not their strictness but the fact that almost nobody reads them to the end.</p>"
        },
        {
          h2: "Non-commercial and research-only licenses",
          html: "<p>This is the category where a mistake costs the most. Licenses such as CC BY-NC, or labels like research-only, non-commercial and for research purposes only, mean the model was released for research, learning and personal experiments, not for making money.</p><p>What counts as commercial use is described broadly in such licenses. It covers not only selling access to the model but also using it inside a company for commercial benefit: handling customer requests, generating commercial copy, helping employees do paid work. Wordings and interpretations differ, which is exactly why a lawyer's reading matters here.</p><p>An important nuance: a non-commercial model does not become commercially usable after fine-tuning. The derived model inherits the restrictions. Nor does the restriction disappear because you charge for a subscription rather than for the model's answers, with the model being only one feature among many.</p><p>The practical rule is simple. If the product touches money in any way, non-commercial models belong in prototypes and hypothesis testing, while production runs a model with suitable terms. That is often a second model, and the migration is worth planning from the start.</p>"
        },
        {
          h2: "AGPL and why businesses are wary of it",
          html: "<p>AGPL is a copyleft license. Its idea is that freedom should travel onward: if you take AGPL material, modify it and let people use the result, you must release the source of your version on the same terms.</p><p>The key difference from the older GPL is the network clause. Under classic GPL the obligation to publish source arose when you distributed the program. AGPL closes that gap: if users interact with your system over a network, through a website or a service interface, that counts as distribution and the obligation applies anyway.</p><p>For a company that has built a proprietary product around a model, this sounds like a demand to hand over its own work. In reality everything depends on what exactly falls under the license and where the boundary of a derived work runs, and that is precisely the question you should not answer without a lawyer.</p><p>In the model world AGPL appears less often on the weights themselves than on the surrounding tooling: serving stacks, libraries, interfaces. The whole set needs checking, not just the model file.</p>"
        },
        {
          h2: "Regional carve-outs: where a model may not be used",
          html: "<p>A notable feature of recent years: some models ship with geographic restrictions. You will find wordings under which the license is not granted to users and companies located in certain regions, most often the European Union, the United Kingdom, Switzerland or South Korea. The reason is usually regulatory rather than technical.</p><p>What matters is not only where your company is registered but also where your product's users are and where your servers physically sit. A company in the UAE with customers in Europe and a server in Germany already spans three jurisdictions in one project.</p><p>Another restriction arrives from a different direction: export rules and sanctions regimes of the model's country of origin. They are not written into the license text, though they are usually referenced, and they apply regardless of what the parties want.</p><p>The planning takeaway is that geography belongs in the technical brief, not in the final checklist. If you operate in both Russia and the UAE, the list of usable models has to be checked separately for each environment.</p>"
        },
        {
          h2: "The license on the weights and the rights to the training data",
          html: "<p>A common confusion. Permission to use the weights says nothing about the terms on which the texts, images and recordings used for training were collected. These are two separate layers with different questions attached.</p><p>The rights holder allows you to run the model but gives no guarantee that the training set contained no third-party protected material. Case law around this question is still forming in different countries, there is no single answer, and as of today the careful position is to treat the question as open.</p><p>The practical consequences show up wherever the model generates something that becomes your asset: website copy, advertising images, code inside your product. It is worth agreeing internally, in advance, what you publish under your own name and what review those materials go through.</p><p>If you fine-tune the model yourself, a third layer appears: the rights to your own data. That is covered in the guide on fine-tuning.</p>"
        },
        {
          h2: "What a business should check before deployment",
          html: "<p>A practical sequence that takes little time and removes most of the unpleasant discoveries later.</p><ol><li>Check the specific version, not the family. Terms can differ between releases in the same line, and a previous check does not carry over to a new model automatically.</li><li>Keep a copy of the license text and the model card as of the download date, together with the exact version name. The document on the vendor's site can change; your copy is the record of what you agreed to.</li><li>Check the licenses of the whole stack: weights, serving software, libraries, interface and any extra models such as translation or speech recognition.</li><li>Write your scenario down in one paragraph and show it to a lawyer along with the saved documents. The question is not whether Llama is allowed, but whether this specific use, in this specific way, for these specific users, is allowed for you.</li><li>Keep a simple register: which model, which version, which license, where it runs, who owns it. Update the entry whenever the model changes.</li></ol><p>This list does not replace legal advice. It makes that advice fast and inexpensive, because the lawyer receives specifics instead of a request to research the field.</p>"
        },
        {
          h2: "A license does not answer for what the model generates",
          html: "<p>The point people miss most often. A license answers whether you have the right to run the model. It does not answer who is responsible when the model quotes a wrong price, invents a fact, gives an incorrect medical or legal suggestion, or produces offensive text.</p><p>Almost every model license disclaims warranties and limits the author's liability. By default, therefore, the consequences land on whoever put the model in front of the customer, which is you.</p><p>From that follows a set of measures that belong to system design rather than law: separate general answers from facts the model pulls out of your own knowledge base, show the source, never let the model quote prices and deadlines on its own, put a human in the loop for sensitive scenarios, and keep a log of answers.</p><p>The higher the cost of an error in your field, the earlier a review procedure appears in the project. That is not bureaucracy; it is the only way to answer calmly what happens when the model gets something wrong.</p>"
        },
        {
          h2: "What this looks like in practice on your own server",
          html: "<p>When a model is deployed inside a company, the licensing side usually turns into a few concrete artifacts. There is a list of what is installed, with versions and links to the saved documents. There is a description of where data lives and what exactly reaches the model. There is a decision about geography: which data center hosts the server and what follows from that.</p><p>Technical decisions then follow from the licensing ones. A non-commercial model moves to the test bench, while production gets a model with suitable terms. A tool under a copyleft license is either replaced or deployed in a way that keeps the derived-work question from arising at all.</p><p>Upgrades are handled explicitly. A new model version means a fresh terms check, not just a file swap. In practice that takes half an hour and happens once, before the upgrade, rather than after the product is already running on new weights.</p>"
        }
      ],
      faq: [
        [
          "What does open model actually mean?",
          "Usually it means the weights are published, that is, a model file you can download and run yourself. The training code and the composition of the training data are normally not released. Usage terms come in a separate document, and they range from fully permissive to fairly restrictive."
        ],
        [
          "Can an open model be used in a commercial product?",
          "It depends on the specific license and the specific version. Models under Apache 2.0 and MIT are generally intended for commercial use; models labeled non-commercial or research-only are not. The answer for your particular case belongs to a lawyer who reads the document alongside your scenario."
        ],
        [
          "Does a fine-tuned model inherit the original license?",
          "Broadly yes: a derived model normally stays bound by the original terms, including prohibitions and attribution duties. Assuming that fine-tuning removes restrictions is risky. If you plan to distribute your own version, that is a separate question for a lawyer."
        ],
        [
          "Why does AGPL worry companies?",
          "Because it requires you to release the source of your version when users interact with the system over a network, not only when you distribute the program. Where the boundary of a derived work sits depends on the architecture, which is exactly the kind of question not to decide on your own."
        ],
        [
          "What if the license does not apply in our region?",
          "Check three things: where the company is registered, where the users are, and where the server physically runs. If any of them falls under a carve-out, the usual answer is to pick a different model with suitable terms. A lawyer decides admissibility; the technical side simply supplies alternatives."
        ],
        [
          "Who is liable if the model gives a customer a wrong answer?",
          "Model licenses almost always disclaim the author's liability, so consequences land on the company that put the model in front of the customer. The risk is reduced by design: answers grounded in your own knowledge base, visible sources, no self-invented prices or deadlines, and human review in sensitive scenarios."
        ]
      ]
    }
  },

  doobuchenie: {
    slug: "doobuchenie",
    title: "Как дообучить открытую модель под свой бизнес",
    description: "Чем отличаются промпт, поиск по своим документам и настоящее дообучение, что такое LoRA, сколько нужно данных и как проверить, что модель стала отвечать лучше.",
    h1: "Как дообучить открытую модель под свой бизнес",
    intro: "Дообучение это изменение самой модели на ваших примерах, чтобы она отвечала так, как принято у вас: в вашем стиле, по вашим правилам, в вашем формате. Это не единственный и часто не первый способ получить нужный результат. Гораздо чаще задача решается точной инструкцией или поиском по своим документам, а дообучение подключают тогда, когда первые два способа упёрлись в потолок. Ниже разбор всех трёх подходов, требований к данным и железу и способов честно проверить, что стало лучше.",
    sections: [
      {
        h2: "Три разные вещи, которые постоянно путают",
        html: "<p>Когда говорят «обучите модель под нас», обычно имеют в виду одну из трёх совершенно разных работ. Разница в цене и сроках между ними кратная, поэтому её стоит проговорить до начала проекта.</p><p>Первое это промпт, системная инструкция. Вы объясняете модели, кто она, как отвечать, чего не делать и в каком формате выдавать результат. Меняется мгновенно, стоит дёшево, и удивительно большая часть задач закрывается именно здесь.</p><p>Второе это поиск по своим документам, его обычно называют RAG. Модель не запоминает ваши материалы, а получает нужные куски из вашей базы прямо в момент ответа: регламенты, прайс, инструкции, историю клиента. Модель при этом остаётся обычной, меняется только то, что ей подсовывают под руку.</p><p>Третье это собственно дообучение, когда вы берёте примеры правильных ответов и меняете саму модель. Она начинает отвечать в нужном стиле и формате без длинных инструкций, но ценой обучающего цикла, отдельной версии модели и обязанности всё это поддерживать.</p>"
      },
      {
        h2: "Почему в большинстве случаев сначала RAG",
        html: "<p>Главная причина простая: дообучение плохо подходит для знаний, которые меняются. Если прайс, условия доставки или регламент обновляются раз в месяц, вшивать их в веса модели означает переобучать её каждый раз. Поиск по документам обновляется заменой файла в базе.</p><p>Вторая причина это проверяемость. При работе через базу знаний видно, из какого документа взят ответ. Можно показать источник пользователю, можно разобрать ошибку и найти, какой именно кусок текста ввёл модель в заблуждение. Дообученная модель отвечает изнутри, и понять происхождение ошибки заметно сложнее.</p><p>Третья причина это цена входа. Настроить поиск по документам обычно быстрее, чем собрать качественную обучающую выборку. А заодно этот этап показывает, каких материалов у компании нет и какие написаны так, что их не понимает даже человек.</p><p>Разумный порядок выглядит так: сначала инструкция, потом база знаний, и только потом дообучение, если осталось то, что первые два способа не закрыли. Обычно остаётся стиль, формат, узкая терминология и специфические правила поведения.</p>"
      },
      {
        h2: "LoRA и QLoRA простыми словами",
        html: "<p>Полное дообучение означает изменение всех чисел внутри модели, а их миллиарды. Это долго и дорого. LoRA решает задачу иначе: сама модель остаётся нетронутой, а рядом обучается небольшая добавка, тонкий слой поправок, который подключается к модели при запуске.</p><p>Такая добавка занимает несравнимо меньше места, чем сама модель, и обучается кратно быстрее. Её можно хранить отдельно, подключать и отключать, держать несколько штук под разные задачи и подменять без замены основной модели. Для бизнеса это удобно тем, что откат к прежнему поведению не требует ничего сложного.</p><p>QLoRA это та же идея плюс сжатие основной модели на время обучения, чтобы она помещалась в меньший объём видеопамяти. Качество при этом немного просаживается по сравнению с обучением без сжатия, но зато обучение становится доступным на одной видеокарте вместо кластера.</p><p>В подавляющем большинстве бизнес-проектов используется именно этот путь. Он дешевле, обратимее и проще в поддержке, а разница в качестве на типичных задачах вроде стиля ответов и формата обычно не решающая.</p>"
      },
      {
        h2: "Полное дообучение: когда оно оправдано",
        html: "<p>Полное дообучение имеет смысл, когда задача не сводится к стилю и формату, а требует по сути другой модели. Например, узкая предметная область с собственным языком, где обычная модель плохо понимает даже постановку вопроса. Или редкий язык и диалект, представленный в исходной модели слабо. Или переход в другую модальность, когда модель учат работать с непривычным для неё типом данных.</p><p>Второй случай это очень большой объём собственных данных. Когда речь идёт о миллионах качественных примеров, лёгкая добавка перестаёт вмещать в себя всё, что вы хотите передать модели.</p><p>Цена вопроса другая: нужен кластер видеокарт или аренда мощностей, нужны люди, которые умеют вести такие обучения, и нужен бюджет на несколько неудачных подходов, потому что с первого раза не получается почти никогда.</p><p>Для большинства компаний честный ответ звучит так: полное дообучение не нужно. Если кажется, что нужно, сначала стоит проверить, действительно ли исчерпаны инструкция, база знаний и лёгкая добавка.</p>"
      },
      {
        h2: "Сколько нужно данных",
        html: "<p>Ожидание обычно такое: чтобы дообучить модель, нужны десятки тысяч примеров. На практике для типичных задач вроде стиля ответов, формата и соблюдения правил бывает достаточно нескольких сотен хорошо подобранных примеров.</p><p>Работает это так: модель уже умеет говорить, рассуждать и понимать вопросы. Вы не учите её языку, вы показываете, как именно надо отвечать в вашей ситуации. Для этого нужны не объёмы, а точность.</p><p>Отсюда главное правило: тысяча плохих примеров хуже, чем сто хороших. Плохой пример это ответ с ошибкой по сути, ответ не в том формате, ответ, который в вашей компании считается неправильным, или просто неудачная формулировка, попавшая в выборку из реальной переписки. Модель не отличает хорошее от плохого, она воспроизводит то, что видит, и уверенно повторяет ваши ошибки.</p><p>Поэтому сбор данных это работа не техническая, а содержательная. Примеры должен отбирать человек, который понимает, какой ответ правильный, и умеет объяснить почему. Обычно это руководитель отдела или самый сильный сотрудник, а не подрядчик.</p>"
      },
      {
        h2: "Как выглядят данные на практике",
        html: "<p>Формат обучающей выборки проще, чем кажется. В основе лежат пары: вход и правильный ответ. Вход это вопрос клиента, задача, документ или их сочетание. Ответ это то, что вы считаете образцовым.</p><p>Источники, откуда такие пары обычно берут:</p><ul><li>Реальная переписка с клиентами, из которой отобраны удачные ответы, а неудачные вычищены.</li><li>База типовых вопросов и утверждённых ответов, если она уже велась в отделе.</li><li>Размеченные документы, когда задача состоит в извлечении полей: договор и таблица с тем, что из него надо вытащить.</li><li>Примеры, написанные специально под редкие, но важные ситуации, которых в переписке почти не встречается.</li><li>Примеры того, как отвечать не надо, если модель учат отказываться и переводить разговор на человека.</li></ul><p>Отдельно стоит потратить время на разнообразие. Если девять примеров из десяти про одну и ту же тему, модель решит, что это и есть её работа, и начнёт тянуть все разговоры в эту сторону.</p><p>И ещё одно: данные надо чистить от персональной информации до того, как они попадут в обучение, а не после.</p>"
      },
      {
        h2: "Железо и время",
        html: "<p>Для ориентира: лёгкое дообучение методом LoRA для модели размером примерно до восьми миллиардов параметров реально выполняется на одной видеокарте с достаточным объёмом памяти. Это укладывается в аренду на короткий срок или в собственную машину, если она уже есть.</p><p>Модели среднего размера требуют более серьёзной карты или сжатия в духе QLoRA. Крупные модели, которые считаются тяжёлыми даже для запуска, требуют нескольких карт или арендованного кластера, и там разговор идёт уже о другом бюджете.</p><p>Время самого обучения на небольшой выборке обычно измеряется часами, а не неделями. Основное время проекта уходит не на обучение, а на подготовку данных и на проверку результата. Это стоит закладывать в план, потому что ожидание «обучим за выходные» разбивается именно о сбор примеров.</p><p>Для запуска готовой модели требования отдельные и обычно скромнее, чем для обучения. Сжатая модель нужного размера спокойно работает на одной карте, и именно это делает установку на свой сервер реалистичной для обычной компании.</p>"
      },
      {
        h2: "Как понять, что стало лучше",
        html: "<p>Самая частая ошибка проекта звучит так: посмотрели десяток ответов, они понравились, признали успех. Человек, который делал модель, видит в ответах то, что хотел увидеть, и это относится ко всем без исключения.</p><p>Минимальная честная проверка состоит из трёх вещей. Первая это отложенная выборка: примеры, которые модель не видела при обучении, отложены заранее и используются только для проверки. Если данные для проверки участвовали в обучении, результат ничего не значит.</p><p>Вторая это слепое сравнение. Ответы старой и новой версии показывают эксперту вперемешку, без пометок, какая версия где. Человек выбирает лучший ответ, и только потом раскрывается, какой модели он принадлежал. Этот приём убирает эффект ожидания и часто даёт неприятные, но полезные результаты.</p><p>Третья это проверка человеком, который отвечает за содержание, а не за технику. Метрика может расти, а ответы при этом станут формально правильными и бесполезными для клиента.</p><p>Отдельно проверяют, не сломалось ли то, что раньше работало. Для этого держат небольшой постоянный набор обычных вопросов и прогоняют его при каждом обновлении.</p>"
      },
      {
        h2: "Частые ошибки",
        html: "<p>Список того, что встречается в проектах чаще всего, независимо от отрасли.</p><ul><li>Дообучение вместо инструкции. Задачу, которая решается одним абзацем в системном промпте, пытаются решить обучающим циклом. Проверьте промпт до того, как собирать данные.</li><li>Знания, вшитые в модель. Прайс и регламенты меняются, а модель продолжает уверенно называть прошлогодние условия. Меняющиеся факты место в базе знаний, а не в весах.</li><li>Персональные данные в обучающей выборке. Из переписки в обучение уезжают телефоны, адреса и суммы. Убрать их потом из модели гораздо сложнее, чем вычистить заранее.</li><li>Забывание общих навыков. Модель, обученную только на коротких шаблонных ответах, часто перестаёт справляться с обычными вопросами. Лечится разнообразием выборки и аккуратными настройками обучения.</li><li>Отсутствие версионирования. Никто не помнит, какая версия сейчас работает, на каких данных обучалась и как откатиться. Каждая версия должна иметь номер, описание данных и возможность вернуться к предыдущей.</li><li>Обучение без цели. Если заранее не сформулировано, что именно должно измениться, оценить результат невозможно, и проект заканчивается спором о вкусах.</li></ul>"
      },
      {
        h2: "Юридическая сторона в общих словах",
        html: "<p>Обучающая выборка это данные компании, и к ним применимы те же правила, что и к любым другим данным. Если в примерах есть переписка с клиентами, там почти наверняка есть персональные данные, и вопрос о допустимости их использования для обучения решается не технической командой.</p><p>В общих чертах ситуация выглядит так: обезличивание снимает часть вопросов, но не все, а формулировки о целях обработки и согласиях у каждой компании свои. В России и в ОАЭ регулирование разное, и проект, работающий в обоих контурах, обычно требует двух отдельных решений.</p><p>Практический подход, который экономит время: до сбора данных описать, откуда берутся примеры, какие поля в них есть и что именно из них вычищается, и показать это описание юристу и ответственному за политику компании. Это короткий документ, но именно он потом отвечает на неудобные вопросы.</p><p>Сюда же относится вопрос прав на исходную модель: дообученная версия обычно остаётся связанной условиями исходной лицензии, включая ограничения на распространение. Это разбирается в отдельном материале про лицензии.</p>"
      },
      {
        h2: "Чем это заканчивается на практике",
        html: "<p>Рабочая конфигурация, к которой приходит большинство проектов, выглядит не как одна дообученная модель, а как небольшая система из нескольких частей.</p><p>Модель стоит на своём сервере или на арендованном сервере компании, и данные не уходят во внешние сервисы. Рядом находится база знаний, которую обновляют без переобучения: положили новый регламент, и ответы изменились. Поверх лежит системная инструкция, которая задаёт правила поведения и границы. И, если это понадобилось, подключена лёгкая добавка после дообучения, отвечающая за стиль, формат и узкую терминологию.</p><p>К этому прилагается регламент: кто отвечает за содержание базы знаний, как часто проверяются ответы, что делать с ошибкой, кто утверждает обновление модели и как откатиться назад. Без этой части система деградирует незаметно: материалы устаревают, ответы съезжают, и однажды это замечает клиент.</p><p>Такой набор скучнее, чем идея «обучим нейросеть под нас», но он обновляется силами самой компании и переживает смену подрядчика, а это обычно и есть настоящая цель проекта.</p>"
      }
    ],
    faq: [
      [
        "Чем дообучение отличается от базы знаний?",
        "База знаний подставляет модели нужные документы в момент ответа, и её можно обновить заменой файла. Дообучение меняет саму модель на примерах и отвечает за стиль, формат и правила поведения. Меняющиеся факты держат в базе, устойчивую манеру отвечать закрепляют дообучением."
      ],
      [
        "Сколько примеров нужно, чтобы начать?",
        "Для задач стиля и формата часто хватает нескольких сотен тщательно отобранных пар вопрос-ответ. Объём здесь менее важен, чем качество: тысяча случайных примеров из переписки обычно даёт худший результат, чем сотня выверенных. Отбирать их должен человек, понимающий предметную область."
      ],
      [
        "Можно ли дообучить модель на одной видеокарте?",
        "Для моделей размером примерно до восьми миллиардов параметров лёгкое дообучение методом LoRA или QLoRA реально выполняется на одной карте с достаточной памятью. Для более крупных моделей нужен кластер или аренда мощностей. Запуск уже готовой модели требует заметно меньше, чем обучение."
      ],
      [
        "Как проверить, что модель действительно стала лучше?",
        "Нужны примеры, которые модель не видела при обучении, слепое сравнение ответов старой и новой версии без пометок и оценка человеком, отвечающим за содержание. Отдельно прогоняют постоянный набор обычных вопросов, чтобы убедиться, что прежние умения не сломались."
      ],
      [
        "Что делать с персональными данными в примерах?",
        "Вычищать их до обучения, а не после: из готовой модели убрать попавшую туда информацию гораздо сложнее. Описание того, откуда берутся данные и что именно из них удаляется, стоит согласовать с юристом и с ответственным за политику компании до начала сбора."
      ],
      [
        "Придётся ли переобучать модель при каждом изменении в компании?",
        "Нет, если система построена правильно. Меняющиеся сведения вроде прайса, условий и регламентов живут в базе знаний и обновляются заменой документа. К дообучению возвращаются редко, когда меняется сама манера общения или появляется новый тип задач."
      ]
    ],
    _en: {
      title: "Fine-tuning an open model for your business",
      description: "Prompting, search over your own documents and real fine-tuning compared: what LoRA is, how much data you need and how to check the model actually improved.",
      h1: "How to fine-tune an open model for your business",
      intro: "Fine-tuning means changing the model itself on your own examples so that it answers the way your company does: in your tone, by your rules, in your format. It is neither the only nor usually the first way to get the result you want. Far more often the job is solved by a precise instruction or by search over your own documents, and fine-tuning enters once those two hit a ceiling. What follows covers all three approaches, the data and hardware they need, and how to check honestly whether anything improved.",
      sections: [
        {
          h2: "Three different things people keep confusing",
          html: "<p>When someone says train the model for us, they usually mean one of three quite different jobs. The cost and timeline differ by multiples, so it is worth settling which one before the project starts.</p><p>The first is the prompt, the system instruction. You tell the model who it is, how to answer, what to avoid and what format to produce. It changes instantly, costs little, and a surprisingly large share of tasks is solved right here.</p><p>The second is search over your own documents, commonly called RAG. The model does not memorize your materials; it receives the relevant fragments from your knowledge base at the moment of answering: policies, price lists, instructions, customer history. The model stays ordinary, only what is handed to it changes.</p><p>The third is fine-tuning proper, where you take examples of correct answers and change the model itself. It starts answering in the required tone and format without lengthy instructions, at the price of a training cycle, a separate model version and the duty to maintain all of it.</p>"
        },
        {
          h2: "Why a knowledge base usually comes first",
          html: "<p>The main reason is simple: fine-tuning is a poor fit for knowledge that changes. If prices, delivery terms or internal policies are updated monthly, baking them into the weights means retraining every time. Document search is updated by replacing a file.</p><p>The second reason is verifiability. When answers come from a knowledge base, you can see which document they came from. You can show the source to the user, investigate an error and find exactly which passage misled the model. A fine-tuned model answers from the inside, and tracing an error is considerably harder.</p><p>The third reason is the cost of entry. Setting up document search is usually faster than assembling a good training set. It also reveals which materials the company does not have and which are written so badly that even a human cannot follow them.</p><p>A sensible order looks like this: instruction first, knowledge base second, fine-tuning only for whatever the first two did not cover. What remains is usually tone, format, narrow terminology and specific behavioral rules.</p>"
        },
        {
          h2: "LoRA and QLoRA in plain language",
          html: "<p>Full fine-tuning means changing every number inside the model, and there are billions of them. That is slow and expensive. LoRA solves the problem differently: the model itself stays untouched while a small add-on is trained alongside it, a thin layer of corrections attached to the model at run time.</p><p>That add-on takes vastly less space than the model and trains many times faster. It can be stored separately, switched on and off, kept in several variants for different tasks and swapped without replacing the base model. For a business the appeal is that rolling back to the previous behavior takes nothing complicated.</p><p>QLoRA is the same idea plus compression of the base model during training, so it fits into less GPU memory. Quality drops slightly compared with uncompressed training, but training becomes feasible on a single card instead of a cluster.</p><p>The overwhelming majority of business projects take this route. It is cheaper, more reversible and easier to maintain, and on typical tasks such as tone and format the quality gap is rarely decisive.</p>"
        },
        {
          h2: "Full fine-tuning: when it is justified",
          html: "<p>Full fine-tuning makes sense when the task is not about tone and format but effectively requires a different model. For instance, a narrow domain with its own language where a general model struggles even to parse the question. Or a rare language or dialect barely represented in the base model. Or a shift in modality, where the model is taught to work with a data type it was not built for.</p><p>The second case is a very large volume of proprietary data. Once you are dealing with millions of quality examples, a lightweight add-on stops holding everything you want to convey.</p><p>The price tag is different: a GPU cluster or rented capacity, people who have run such training before, and budget for several failed attempts, because it almost never works on the first pass.</p><p>For most companies the honest answer is that full fine-tuning is not needed. If it feels necessary, first confirm that the instruction, the knowledge base and the lightweight add-on are genuinely exhausted.</p>"
        },
        {
          h2: "How much data you actually need",
          html: "<p>The usual expectation is that fine-tuning requires tens of thousands of examples. In practice, for typical tasks such as answer style, format and rule compliance, several hundred well-chosen examples are often enough.</p><p>The reason is that the model already knows how to speak, reason and understand questions. You are not teaching it language; you are showing how answers should look in your specific situation. That calls for precision rather than volume.</p><p>Hence the main rule: a thousand bad examples are worse than a hundred good ones. A bad example is an answer that is substantively wrong, an answer in the wrong format, an answer your company considers incorrect, or simply an awkward phrasing that slipped in from real correspondence. The model cannot tell good from bad; it reproduces what it sees and repeats your mistakes with confidence.</p><p>Data collection is therefore editorial work, not technical work. Examples should be selected by someone who knows which answer is right and can explain why. Usually that is a department head or your strongest specialist, not a contractor.</p>"
        },
        {
          h2: "What the data looks like in practice",
          html: "<p>The format of a training set is simpler than people expect. At its core are pairs: an input and the correct answer. The input is a customer question, a task, a document or some combination. The answer is what you consider exemplary.</p><p>The usual sources for such pairs:</p><ul><li>Real customer correspondence, with the good answers selected and the poor ones removed.</li><li>An existing library of standard questions and approved answers, if the team already kept one.</li><li>Annotated documents, when the task is field extraction: a contract plus a table of what must be pulled out of it.</li><li>Examples written specifically for rare but important situations that barely appear in correspondence.</li><li>Examples of how not to answer, if the model is being taught to decline and hand the conversation to a human.</li></ul><p>Spend separate effort on variety. If nine examples out of ten cover the same topic, the model will conclude that this is the job and start steering every conversation in that direction.</p><p>One more thing: personal information should be stripped from the data before training, not afterwards.</p>"
        },
        {
          h2: "Hardware and time",
          html: "<p>As a rough guide, a lightweight LoRA fine-tune for a model of roughly up to eight billion parameters is genuinely doable on a single GPU with enough memory. That fits a short rental or a machine you already own.</p><p>Mid-sized models require a stronger card or QLoRA-style compression. Large models, heavy even to run, require several cards or a rented cluster, and that is a different budget conversation.</p><p>Training time on a small set is usually measured in hours, not weeks. Most of the project goes into preparing data and evaluating results, not into training. Plan accordingly, because the idea of training over a weekend breaks precisely on example collection.</p><p>Running a finished model has its own, generally lighter requirements. A compressed model of the right size runs comfortably on a single card, and that is what makes on-premise deployment realistic for an ordinary company.</p>"
        },
        {
          h2: "How to tell whether it actually improved",
          html: "<p>The most common project mistake sounds like this: we looked at a dozen answers, liked them, and called it a success. The person who built the model sees in the answers what they hoped to see, and that applies to everyone without exception.</p><p>An honest minimum check has three parts. The first is a held-out set: examples the model never saw during training, set aside in advance and used only for evaluation. If the evaluation data took part in training, the result means nothing.</p><p>The second is blind comparison. Answers from the old and new versions are shown to an expert shuffled together, with no labels. The person picks the better answer, and only then is the source revealed. This removes the expectation effect and often produces unpleasant but useful results.</p><p>The third is review by the person responsible for substance rather than for the technology. A metric can rise while the answers become formally correct and useless to the customer.</p><p>Separately, check that nothing that used to work is now broken. Keep a small fixed set of ordinary questions and run it on every update.</p>"
        },
        {
          h2: "Common mistakes",
          html: "<p>What shows up most often in projects, regardless of industry.</p><ul><li>Fine-tuning instead of instructing. A task solvable with one paragraph in the system prompt is attacked with a training cycle. Test the prompt before collecting data.</li><li>Knowledge baked into the weights. Prices and policies change while the model keeps confidently quoting last year's terms. Changing facts belong in the knowledge base, not in the model.</li><li>Personal data in the training set. Phone numbers, addresses and amounts travel from correspondence into training. Removing them from a trained model is far harder than cleaning them beforehand.</li><li>Forgetting general skills. A model trained only on short templated replies often stops handling ordinary questions. The cure is a varied data set and careful training settings.</li><li>No versioning. Nobody remembers which version is live, what data it was trained on or how to roll back. Every version needs a number, a description of its data and a way back.</li><li>Training without a goal. If nobody stated in advance what should change, the result cannot be assessed and the project ends in an argument about taste.</li></ul>"
        },
        {
          h2: "The legal side in general terms",
          html: "<p>A training set is company data, and the same rules apply to it as to any other data. If the examples include customer correspondence, they almost certainly contain personal data, and whether it may be used for training is not a decision for the technical team.</p><p>Broadly, the picture is this: anonymization removes part of the problem but not all of it, and each company has its own wording on processing purposes and consent. Regulation in Russia and in the UAE differs, and a project operating in both usually needs two separate answers.</p><p>A practical approach that saves time: before collecting data, write down where the examples come from, what fields they contain and what exactly gets stripped out, then show that description to a lawyer and to whoever owns company policy. It is a short document, but it is the one that answers the awkward questions later.</p><p>The rights to the base model belong here too: a fine-tuned version generally stays bound by the original license, including distribution limits. That is covered in the separate guide on licenses.</p>"
        },
        {
          h2: "What this ends up looking like",
          html: "<p>The working setup most projects arrive at is not a single fine-tuned model but a small system of several parts.</p><p>The model runs on your own server or on a server rented by the company, so data never leaves for external services. Next to it sits a knowledge base updated without retraining: drop in a new policy document and the answers change. Above that lies the system instruction that defines behavior and boundaries. And, if it turned out to be necessary, a lightweight fine-tuned add-on handles tone, format and narrow terminology.</p><p>All of it comes with a written routine: who owns the content of the knowledge base, how often answers are reviewed, what happens when an error is found, who approves a model update and how to roll back. Without that part the system degrades invisibly: materials go stale, answers drift, and one day a customer notices first.</p><p>This arrangement is duller than the idea of training a neural network just for us, but the company can maintain it in house and it survives a change of contractor, which is usually the real goal of the project.</p>"
        }
      ],
      faq: [
        [
          "How is fine-tuning different from a knowledge base?",
          "A knowledge base feeds the model the right documents at the moment of answering, and it is updated by replacing a file. Fine-tuning changes the model itself on examples and governs tone, format and behavioral rules. Changing facts belong in the base; a consistent way of answering is what fine-tuning locks in."
        ],
        [
          "How many examples are needed to start?",
          "For tone and format tasks a few hundred carefully selected question-answer pairs are often enough. Volume matters less than quality here: a thousand random samples pulled from correspondence usually perform worse than a hundred vetted ones. Selection belongs to someone who knows the domain."
        ],
        [
          "Can a model be fine-tuned on a single GPU?",
          "For models of roughly up to eight billion parameters, a lightweight LoRA or QLoRA fine-tune is genuinely feasible on one card with enough memory. Larger models need a cluster or rented capacity. Running a finished model takes noticeably less than training one."
        ],
        [
          "How do we verify the model really got better?",
          "You need examples the model never saw during training, a blind comparison of old and new answers without labels, and review by the person accountable for content. Separately, run a fixed set of ordinary questions to confirm that previous abilities did not break."
        ],
        [
          "What about personal data in the examples?",
          "Strip it before training rather than after: removing information from a trained model is far harder. A short description of where the data comes from and what is removed from it is worth agreeing with a lawyer and with whoever owns company policy before collection begins."
        ],
        [
          "Will the model need retraining every time something changes?",
          "Not if the system is built properly. Changing details such as prices, terms and policies live in the knowledge base and are updated by replacing a document. Fine-tuning is revisited rarely, when the way of communicating itself changes or a new type of task appears."
        ]
      ]
    }
  }
};
