// Модели для программирования: автодополнение, генерация кода, агенты для разработки. Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'starcoder',
    name: 'StarCoder',
    developer: 'BigCode (Hugging Face и ServiceNow)', country: 'США / Франция',
    modality: ['code'],
    first: '2023-05', latest: '2024-04',
    sizes: '1B – 15B',
    license: 'BigCode OpenRAIL-M (коммерция разрешена, но есть список запрещённых применений)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Одна из первых открытых моделей для кода, обучена на открытом наборе исходников с возможностью исключить свой репозиторий. Сегодня скорее база для дообучения, чем лидер.',
    tasks: ['Автодополнение кода в редакторе', 'Дообучение на внутреннем коде компании', 'Генерация шаблонного кода и тестов'],
    where: ['ИТ-отделы', 'Разработка внутренних систем'],
    versions: [['StarCoder / StarCoderBase', '2023-05'], ['StarCoder2 (3B, 7B, 15B)', '2024-02'], ['StarCoder2-15B-Instruct', '2024-04']],
    hf: 'https://huggingface.co/bigcode',
    github: 'https://github.com/bigcode-project/starcoder2',
    alternatives: ['qwen-coder', 'deepseek-coder', 'mellum'],
    source: 'https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1',
    verified: true,
  },
  {
    id: 'code-llama',
    name: 'Code Llama',
    developer: 'Meta', country: 'США',
    modality: ['code'],
    first: '2023-08', latest: '2024-01',
    sizes: '7B – 70B',
    license: 'Llama 2 Community License (коммерция разрешена с ограничениями)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Версия Llama 2, доученная на коде; есть варианты для Python и для диалога. Устарела, но много готовых дообученных версий и инструментов.',
    tasks: ['Автодополнение и объяснение кода', 'Генерация скриптов на Python', 'Базовая модель для дообучения под свой стек'],
    where: ['ИТ-отделы', 'Обучение разработчиков'],
    versions: [['Code Llama 7B / 13B / 34B', '2023-08'], ['Code Llama 70B', '2024-01']],
    hf: 'https://huggingface.co/codellama',
    github: 'https://github.com/meta-llama/codellama',
    alternatives: ['llama', 'qwen-coder', 'deepseek-coder'],
    source: 'https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf',
    verified: true,
  },
  {
    id: 'deepseek-coder',
    name: 'DeepSeek-Coder',
    developer: 'DeepSeek', country: 'Китай',
    modality: ['code'],
    first: '2023-11', latest: '2024-09',
    sizes: '1.3B – 236B-A21B',
    license: 'DeepSeek License (коммерция разрешена, есть запреты на отдельные применения); код — MIT',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Линейка моделей для кода от DeepSeek: от маленьких для автодополнения до большой MoE V2, которая в 2024 году была на уровне закрытых моделей. Позже код ушёл в общие модели DeepSeek.',
    tasks: ['Автодополнение и генерация кода', 'Перевод кода между языками', 'Поиск ошибок и объяснение чужого кода'],
    where: ['ИТ-отделы', 'Разработка продуктов', 'Поддержка старых систем'],
    versions: [['DeepSeek-Coder 1.3B / 6.7B / 33B', '2023-11'], ['DeepSeek-Coder 7B v1.5', '2024-01'], ['DeepSeek-Coder-V2 и V2-Lite', '2024-06'], ['DeepSeek-Coder-V2-Instruct-0724', '2024-09']],
    hf: 'https://huggingface.co/deepseek-ai',
    github: 'https://github.com/deepseek-ai/DeepSeek-Coder-V2',
    alternatives: ['qwen-coder', 'deepseek', 'code-llama'],
    source: 'https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct-0724',
    verified: true,
  },
  {
    id: 'qwen-coder',
    name: 'Qwen Coder',
    developer: 'Alibaba (команда Qwen)', country: 'Китай',
    modality: ['code'],
    first: '2024-04', latest: '2026-02',
    sizes: '0.5B – 480B-A35B',
    license: 'Apache 2.0 (у CodeQwen1.5 и Qwen2.5-Coder-3B — собственная лицензия Qwen)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Самая широкая открытая линейка для кода: от 0.5B для автодополнения до 480B для агентов. Qwen3-Coder-Next (80B, активны 3B) работает как агент-разработчик на одной видеокарте.',
    tasks: ['Автодополнение кода в редакторе', 'Агент, который сам правит код в репозитории', 'Генерация и доработка скриптов, SQL, интеграций', 'Ревью кода внутри компании без выхода данных наружу'],
    where: ['ИТ-отделы', 'Разработка продуктов', 'Аналитика данных'],
    versions: [['CodeQwen1.5-7B', '2024-04'], ['Qwen2.5-Coder 1.5B / 7B', '2024-09'], ['Qwen2.5-Coder 0.5B – 32B', '2024-11'], ['Qwen3-Coder 480B-A35B и 30B-A3B', '2025-07'], ['Qwen3-Coder-Next 80B-A3B', '2026-02']],
    hf: 'https://huggingface.co/Qwen/Qwen3-Coder-Next',
    github: 'https://github.com/QwenLM/Qwen3-Coder',
    alternatives: ['qwen', 'devstral', 'deepseek-coder'],
    source: 'https://huggingface.co/Qwen/Qwen3-Coder-Next',
    verified: true,
  },
  {
    id: 'codestral',
    name: 'Codestral',
    developer: 'Mistral AI', country: 'Франция',
    modality: ['code'],
    first: '2024-05', latest: '2024-07',
    sizes: '7B – 22B',
    license: 'Codestral 22B — Mistral Non-Production License (только исследования и тесты); побочная Mamba-Codestral 7B — Apache 2.0',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    summary: 'Модель Mistral для кода на 80+ языках программирования. Открытые веса основной версии нельзя использовать в работе без платной лицензии; новые версии Codestral только по API.',
    tasks: ['Оценка и тесты перед покупкой лицензии', 'Автодополнение кода (при коммерческой лицензии)', 'Исследование качества моделей для кода'],
    where: ['ИТ-отделы', 'Исследовательские команды'],
    versions: [['Codestral-22B-v0.1', '2024-05'], ['Mamba-Codestral-7B', '2024-07']],
    hf: 'https://huggingface.co/mistralai/Codestral-22B-v0.1',
    github: null,
    alternatives: ['devstral', 'qwen-coder', 'mistral'],
    source: 'https://huggingface.co/mistralai/Codestral-22B-v0.1',
    verified: true,
  },
  {
    id: 'devstral',
    name: 'Devstral',
    developer: 'Mistral AI (с All Hands AI)', country: 'Франция',
    modality: ['code'],
    first: '2025-05', latest: '2025-12',
    sizes: '24B – 123B',
    license: 'Small-версии 24B — Apache 2.0; Devstral 2 123B — модифицированная MIT (нельзя компаниям с выручкой выше 20 млн долларов в месяц)',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    summary: 'Модели Mistral для агентной разработки: сами читают репозиторий, правят файлы и запускают команды. Версия 24B помещается на одну видеокарту.',
    tasks: ['Агент-разработчик для исправления задач из трекера', 'Доработка внутренних систем по описанию', 'Автоматизация рутинных правок в коде'],
    where: ['ИТ-отделы', 'Разработка продуктов', 'Внедрение и интеграции'],
    versions: [['Devstral Small 2505', '2025-05'], ['Devstral Small 2507', '2025-07'], ['Devstral 2 123B и Devstral Small 2 24B', '2025-12']],
    hf: 'https://huggingface.co/mistralai/Devstral-2-123B-Instruct-2512',
    github: null,
    alternatives: ['qwen-coder', 'kat-coder', 'sera'],
    source: 'https://huggingface.co/mistralai/Devstral-2-123B-Instruct-2512',
    verified: true,
  },
  {
    id: 'mellum',
    name: 'Mellum',
    developer: 'JetBrains', country: 'Чехия',
    modality: ['code'],
    first: '2025-04', latest: '2026-06',
    sizes: '4B – 12B-A2.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модели JetBrains для быстрого автодополнения кода. Mellum2 (12B, активны 2.5B) уже полноценный помощник: пишет и правит код, вызывает инструменты, рассуждает.',
    tasks: ['Быстрое автодополнение кода на своём сервере', 'Помощник разработчика без отправки кода в облако', 'Дообучение на коде компании'],
    where: ['ИТ-отделы', 'Разработка продуктов'],
    versions: [['Mellum-4b-base', '2025-04'], ['Mellum-4b SFT для Python и Kotlin', '2025-05'], ['Mellum-4b DPO', '2025-09'], ['Mellum2 12B-A2.5B Instruct и Thinking', '2026-06']],
    hf: 'https://huggingface.co/JetBrains',
    github: null,
    alternatives: ['qwen-coder', 'starcoder', 'seed-coder'],
    source: 'https://blog.jetbrains.com/ai/2026/06/mellum2-goes-open-source-a-fast-model-for-ai-workflows/',
    verified: true,
  },
  {
    id: 'kat-coder',
    name: 'KAT-Coder / KAT-Dev',
    developer: 'Kwaipilot (Kuaishou)', country: 'Китай',
    modality: ['code'],
    first: '2025-09', latest: '2026-07',
    sizes: '32B – 72B, 35B-A3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    summary: 'Модели Kuaishou для агентной разработки, обученные решать реальные задачи в репозиториях. KAT-Coder-V2.5-Dev (35B, активны 3B) — открытая версия их закрытого флагмана.',
    tasks: ['Агент, исправляющий задачи в репозитории', 'Генерация и рефакторинг кода', 'Автоматизация рутинных задач разработки'],
    where: ['ИТ-отделы', 'Разработка продуктов'],
    versions: [['KAT-Dev 32B', '2025-09'], ['KAT-Dev-72B-Exp', '2025-10'], ['KAT-Coder-V2.5-Dev 35B-A3B', '2026-07']],
    hf: 'https://huggingface.co/Kwaipilot/KAT-Coder-V2.5-Dev',
    github: null,
    alternatives: ['qwen-coder', 'devstral', 'iquest-coder'],
    source: 'https://huggingface.co/Kwaipilot/KAT-Coder-V2.5-Dev',
    verified: true,
  },
  {
    id: 'iquest-coder',
    name: 'IQuest-Coder',
    developer: 'IQuest Research', country: 'Китай',
    modality: ['code'],
    first: '2026-01', latest: '2026-02',
    sizes: '7B – 40B',
    license: 'Модифицированная MIT: при коммерческом использовании нужно показывать надпись IQuest Coder в интерфейсе продукта',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Семейство моделей для кода с обычными и рассуждающими версиями, в том числе вариант Loop с повторным проходом по слоям. Размеры от 7B до 40B.',
    tasks: ['Генерация и доработка кода', 'Решение задач с пошаговыми рассуждениями', 'Агентная работа с репозиторием'],
    where: ['ИТ-отделы', 'Разработка продуктов'],
    versions: [['IQuest-Coder-V1 7B / 40B и 40B-Loop', '2026-01'], ['IQuest-Coder-V1 14B', '2026-02']],
    hf: 'https://huggingface.co/IQuestLab',
    github: null,
    alternatives: ['qwen-coder', 'kat-coder', 'seed-coder'],
    source: 'https://huggingface.co/IQuestLab/IQuest-Coder-V1-40B-Instruct',
    verified: true,
  },
  {
    id: 'sera',
    name: 'SERA (Ai2 Open Coding Agents)',
    developer: 'Ai2 (Allen Institute for AI)', country: 'США',
    modality: ['code'],
    first: '2026-01', latest: '2026-02',
    sizes: '8B – 32B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Полностью открытые агенты-разработчики от Ai2: открыты веса, данные и рецепт обучения. Задуманы так, чтобы компания могла дешево доучить агента на своём репозитории.',
    tasks: ['Агент для исправления задач в коде', 'Дообучение агента под внутренний репозиторий', 'Автоматизация мелких правок и тестов'],
    where: ['ИТ-отделы', 'Разработка продуктов'],
    versions: [['SERA-8B и SERA-32B', '2026-01'], ['SERA-14B', '2026-02']],
    hf: 'https://huggingface.co/allenai/SERA-32B',
    github: null,
    alternatives: ['devstral', 'qwen-coder', 'olmo'],
    source: 'https://huggingface.co/allenai/SERA-14B',
    verified: true,
  },
  {
    id: 'seed-coder',
    name: 'Seed-Coder',
    developer: 'ByteDance Seed', country: 'Китай',
    modality: ['code'],
    first: '2025-05', latest: '2025-05',
    sizes: '8B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Компактная модель для кода 8B от ByteDance: базовая, инструктивная и рассуждающая версии. Данные для обучения отбирала сама модель, почти без ручных правил.',
    tasks: ['Автодополнение и генерация кода', 'Решение алгоритмических задач', 'Основа для дообучения под свой стек'],
    where: ['ИТ-отделы', 'Обучение разработчиков'],
    versions: [['Seed-Coder-8B Base / Instruct / Reasoning', '2025-05']],
    hf: 'https://huggingface.co/ByteDance-Seed/Seed-Coder-8B-Instruct',
    github: 'https://github.com/ByteDance-Seed/Seed-Coder',
    alternatives: ['qwen-coder', 'mellum', 'seed-oss'],
    source: 'https://huggingface.co/ByteDance-Seed/Seed-Coder-8B-Reasoning',
    verified: true,
  },
];
