// Генерация картинок, видео и говорящих аватаров. Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- Картинки ----------
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    developer: 'Stability AI', country: 'Великобритания',
    modality: ['image'],
    first: '2022-08', latest: '2024-10',
    sizes: '0.9B – 8B',
    license: 'SD 1.x — CreativeML OpenRAIL-M, SDXL — OpenRAIL++, SD3 и SD3.5 — Stability AI Community License (бесплатно при выручке до $1 млн в год); Stable Cascade — некоммерческая исследовательская лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['marketing', 'media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Модель, с которой началась открытая генерация картинок. Огромная экосистема дообучений, стилей и плагинов, работает даже на домашнем ПК. Популярные ускорители SDXL-Lightning и Hyper-SD сделала ByteDance.',
    tasks: ['Иллюстрации и баннеры для рекламы', 'Фоны и сцены для карточек товаров', 'Дообучение под фирменный стиль', 'Черновые визуалы для дизайнеров'],
    where: ['Маркетинг и реклама', 'Интернет-магазины', 'Дизайн-студии', 'Издательства'],
    versions: [['SD 1.4', '2022-08'], ['SD 1.5', '2022-10'], ['SD 2.0', '2022-11'], ['SDXL 1.0', '2023-07'], ['SDXL Turbo', '2023-11'], ['Stable Cascade', '2024-02'], ['SD3 Medium', '2024-06'], ['SD3.5 Large / Medium', '2024-10']],
    hf: 'https://huggingface.co/stabilityai',
    github: 'https://github.com/Stability-AI/sd3.5',
    alternatives: ['flux', 'sana', 'z-image'],
    source: 'https://huggingface.co/stabilityai/stable-diffusion-3.5-large',
    verified: true,
    en: {
      summary: 'The model that started open image generation. A huge ecosystem of fine-tunes, styles and plugins; runs even on a home PC. The popular SDXL-Lightning and Hyper-SD accelerators were made by ByteDance.',
      tasks: ['Illustrations and banners for advertising', 'Backgrounds and scenes for product cards', 'Fine-tuning to a brand style', 'Draft visuals for designers'],
      where: ['Marketing and advertising', 'Online stores', 'Design studios', 'Publishers'],
      license: 'SD 1.x — CreativeML OpenRAIL-M, SDXL — OpenRAIL++, SD3 and SD3.5 — Stability AI Community License (free for revenue under $1M per year); Stable Cascade — non-commercial research license',
      country: 'UK',
    },
  },
  {
    id: 'kandinsky',
    name: 'Kandinsky',
    developer: 'Сбер (Kandinsky Lab)', country: 'Россия',
    modality: ['image', 'video'],
    first: '2022-11', latest: '2026-07',
    sizes: '2B – 19B',
    license: 'Apache 2.0 (версии 2.x–4), MIT (Kandinsky 5 и WM 1.0)',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'yes',
    industries: ['marketing', 'media', 'education', 'gov'],
    ollama: false,
    cpu: false,
    summary: 'Российское семейство генерации картинок и видео от Сбера. Хорошо понимает запросы на русском и российский культурный контекст, открыто под MIT.',
    tasks: ['Картинки по описанию на русском', 'Короткие рекламные ролики из текста или фото', 'Редактирование изображений по инструкции', 'Визуалы для соцсетей'],
    where: ['Маркетинг и SMM', 'Медиа и издательства', 'Образование', 'Госсектор и компании с требованиями к российскому ПО'],
    versions: [['Kandinsky 2.0', '2022-11'], ['Kandinsky 2.1', '2023-04'], ['Kandinsky 2.2', '2023-07'], ['Kandinsky 3.0', '2023-11'], ['Kandinsky 4.0 Video Flash', '2024-12'], ['Kandinsky 5.0 Video Lite', '2025-09'], ['Kandinsky 5.0 Image Lite / Video Pro', '2025-11'], ['Kandinsky WM 1.0', '2026-07']],
    hf: 'https://huggingface.co/kandinskylab',
    github: 'https://github.com/kandinskylab/kandinsky-5',
    alternatives: ['flux', 'wan', 'z-image'],
    source: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-T2I-Lite',
    verified: true,
    en: {
      summary: 'Sber\'s Russian family of image and video generation models. Understands Russian-language prompts and Russian cultural context well; released under MIT.',
      tasks: ['Images from Russian-language descriptions', 'Short promo videos from text or a photo', 'Instruction-based image editing', 'Visuals for social media'],
      where: ['Marketing and social media', 'Media and publishing', 'Education', 'Public sector and companies required to use Russian software'],
      license: 'Apache 2.0 (versions 2.x–4), MIT (Kandinsky 5 and WM 1.0)',
      developer: 'Sber (Kandinsky Lab)',
      country: 'Russia',
    },
  },
  {
    id: 'deepfloyd-if',
    name: 'DeepFloyd IF',
    developer: 'DeepFloyd (Stability AI)', country: 'Великобритания',
    modality: ['image'],
    first: '2023-04', latest: '2023-04',
    sizes: '0.4B – 4.3B',
    license: 'DeepFloyd IF License — только исследования, коммерция запрещена',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['science'],
    ollama: false,
    cpu: false,
    summary: 'Ранняя модель, которая одной из первых научилась аккуратно писать текст на картинках. Сейчас интересна скорее как история, развитие остановлено.',
    tasks: ['Исследовательские эксперименты', 'Прототипы картинок с надписями'],
    where: ['R&D-отделы', 'Университеты'],
    versions: [['IF-I-M / IF-I-L', '2023-03'], ['IF-I-XL v1.0', '2023-04']],
    hf: 'https://huggingface.co/DeepFloyd/IF-I-XL-v1.0',
    github: 'https://github.com/deep-floyd/IF',
    alternatives: ['stable-diffusion', 'pixart'],
    source: 'https://huggingface.co/DeepFloyd/IF-I-XL-v1.0',
    verified: true,
    en: {
      summary: 'An early model that was among the first to render text on images accurately. Today it is mostly of historical interest; development has stopped.',
      tasks: ['Research experiments', 'Prototype images with captions'],
      where: ['R&D departments', 'Universities'],
      license: 'DeepFloyd IF License — research only, commercial use prohibited',
      country: 'UK',
    },
  },
  {
    id: 'pixart',
    name: 'PixArt',
    developer: 'Huawei Noah\'s Ark Lab и партнёры', country: 'Китай',
    modality: ['image'],
    first: '2023-11', latest: '2024-04',
    sizes: '0.6B',
    license: 'OpenRAIL++ (разрешает коммерцию с запретом вредного использования)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Компактная модель картинок на 0.6B с качеством уровня крупных. Умеет 4K в версии Sigma, подходит для скромного железа.',
    tasks: ['Иллюстрации для статей и соцсетей', 'Фоны для карточек товаров', 'Быстрые черновики визуалов'],
    where: ['Маркетинг', 'Малый бизнес', 'Медиа'],
    versions: [['PixArt-alpha', '2023-11'], ['PixArt-LCM', '2023-11'], ['PixArt-Sigma', '2024-04']],
    hf: 'https://huggingface.co/PixArt-alpha',
    github: 'https://github.com/PixArt-alpha/PixArt-sigma',
    alternatives: ['sana', 'stable-diffusion'],
    source: 'https://huggingface.co/PixArt-alpha/PixArt-Sigma-XL-2-1024-MS',
    verified: true,
    en: {
      summary: 'A compact 0.6B image model with quality on par with much larger ones. The Sigma version does 4K; suits modest hardware.',
      tasks: ['Illustrations for articles and social media', 'Backgrounds for product cards', 'Quick visual drafts'],
      where: ['Marketing', 'Small business', 'Media'],
      license: 'OpenRAIL++ (allows commercial use, prohibits harmful use)',
      developer: 'Huawei Noah\'s Ark Lab and partners',
      country: 'China',
    },
  },
  {
    id: 'playground',
    name: 'Playground',
    developer: 'Playground AI', country: 'США',
    modality: ['image'],
    first: '2023-11', latest: '2024-02',
    sizes: 'около 2.6B',
    license: 'Playground v2.5 Community License — бесплатно, но если генерация картинок — основной продукт и у сервиса больше 1 млн пользователей в месяц, нужна отдельная лицензия',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Модель на архитектуре SDXL с упором на эстетику: яркие цвета, контраст, портреты. Совместима с инструментами экосистемы SDXL.',
    tasks: ['Эстетичные рекламные визуалы', 'Портреты и лайфстайл-картинки', 'Обложки для постов'],
    where: ['Маркетинг и SMM', 'Дизайн-студии', 'E-commerce'],
    versions: [['Playground v1', '2023-11'], ['Playground v2', '2023-12'], ['Playground v2.5', '2024-02']],
    hf: 'https://huggingface.co/playgroundai',
    github: null,
    alternatives: ['stable-diffusion', 'flux'],
    source: 'https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic',
    verified: true,
    en: {
      summary: 'An SDXL-based model focused on aesthetics: vivid colors, contrast, portraits. Compatible with SDXL ecosystem tools.',
      tasks: ['Aesthetic ad visuals', 'Portraits and lifestyle images', 'Post covers'],
      where: ['Marketing and social media', 'Design studios', 'E-commerce'],
      license: 'Playground v2.5 Community License — free, but if image generation is your core product and the service has over 1M monthly users, a separate license is required',
      country: 'USA',
      sizes: 'about 2.6B',
    },
  },
  {
    id: 'sana',
    name: 'SANA',
    developer: 'NVIDIA', country: 'США',
    modality: ['image'],
    first: '2024-11', latest: '2025-03',
    sizes: '0.6B – 4.8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['retail', 'marketing', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Быстрая модель картинок от NVIDIA: 4K-изображения за секунды и работа даже на ноутбучной видеокарте. Версия Sprint генерирует в 1–2 шага.',
    tasks: ['Массовая генерация картинок', 'Визуалы высокого разрешения', 'Генерация в реальном времени в приложениях'],
    where: ['E-commerce', 'Маркетинг', 'Продуктовые команды'],
    versions: [['SANA 0.6B / 1.6B', '2024-11'], ['SANA 1.5 (4.8B)', '2025-03'], ['SANA-Sprint', '2025-03']],
    hf: 'https://huggingface.co/Efficient-Large-Model',
    github: 'https://github.com/NVlabs/Sana',
    alternatives: ['pixart', 'z-image', 'flux'],
    source: 'https://huggingface.co/Efficient-Large-Model/SANA1.5_4.8B_1024px',
    verified: true,
    en: {
      summary: 'NVIDIA\'s fast image model: 4K images in seconds, runs even on a laptop GPU. The Sprint version generates in 1–2 steps.',
      tasks: ['Bulk image generation', 'High-resolution visuals', 'Real-time generation inside apps'],
      where: ['E-commerce', 'Marketing', 'Product teams'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'hunyuan-image',
    name: 'Hunyuan Image',
    developer: 'Tencent', country: 'Китай',
    modality: ['image'],
    first: '2024-05', latest: '2026-01',
    sizes: '1.5B – 80B-A13B',
    license: 'Tencent Hunyuan Community License — коммерция разрешена, но не действует в ЕС, Великобритании и Южной Корее, для крупных сервисов нужна отдельная лицензия',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Модели картинок Tencent. HunyuanImage 3.0 — крупнейшая открытая MoE-модель генерации на 80B, умеет рассуждать над запросом и редактировать по инструкции.',
    tasks: ['Сложные сцены по длинному описанию', 'Картинки с текстом на китайском и английском', 'Редактирование изображений по инструкции', 'Рекламные постеры'],
    where: ['Маркетинг', 'Медиа', 'Геймдев'],
    versions: [['Hunyuan-DiT', '2024-05'], ['HunyuanImage 2.1', '2025-09'], ['HunyuanImage 3.0', '2025-09'], ['HunyuanImage 3.0-Instruct', '2026-01']],
    hf: 'https://huggingface.co/tencent/HunyuanImage-3.0',
    github: 'https://github.com/Tencent-Hunyuan/HunyuanImage-3.0',
    alternatives: ['qwen-image', 'flux', 'hidream'],
    source: 'https://huggingface.co/tencent/HunyuanImage-3.0-Instruct',
    verified: true,
    en: {
      summary: 'Tencent\'s image models. HunyuanImage 3.0 is the largest open MoE generation model at 80B; it can reason about the prompt and edit by instruction.',
      tasks: ['Complex scenes from long descriptions', 'Images with Chinese and English text', 'Instruction-based image editing', 'Advertising posters'],
      where: ['Marketing', 'Media', 'Game development'],
      license: 'Tencent Hunyuan Community License — commercial use allowed, but not valid in the EU, UK and South Korea; large services need a separate license',
      country: 'China',
    },
  },
  {
    id: 'hidream',
    name: 'HiDream',
    developer: 'HiDream.ai', country: 'Китай',
    modality: ['image'],
    first: '2025-04', latest: '2026-05',
    sizes: 'около 9B – 17B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Открытые модели картинок под MIT: генерация (I1), редактирование по инструкции (E1) и единая модель O1-Image, которая делает и то и другое.',
    tasks: ['Генерация картинок по описанию', 'Правка изображений словами', 'Вариации продуктовых фото'],
    where: ['E-commerce', 'Маркетинг', 'Дизайн-студии'],
    versions: [['HiDream-I1', '2025-04'], ['HiDream-E1', '2025-04'], ['HiDream-E1.1', '2025-07'], ['HiDream-O1-Image', '2026-05']],
    hf: 'https://huggingface.co/HiDream-ai',
    github: 'https://github.com/HiDream-ai/HiDream-I1',
    alternatives: ['flux', 'qwen-image', 'z-image'],
    source: 'https://huggingface.co/HiDream-ai/HiDream-O1-Image',
    verified: true,
    en: {
      summary: 'Open MIT-licensed image models: generation (I1), instruction-based editing (E1) and the unified O1-Image model that does both.',
      tasks: ['Image generation from descriptions', 'Editing images with words', 'Variations of product photos'],
      where: ['E-commerce', 'Marketing', 'Design studios'],
      license: 'MIT',
      country: 'China',
      sizes: 'about 9B – 17B',
    },
  },
  {
    id: 'omnigen',
    name: 'OmniGen',
    developer: 'BAAI (Пекинская академия ИИ)', country: 'Китай',
    modality: ['image'],
    first: '2024-10', latest: '2025-06',
    sizes: 'около 4B',
    license: 'MIT (v1), Apache 2.0 (OmniGen2)',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Универсальная модель: генерирует, редактирует, переносит объект или человека с фото в новую сцену без отдельных плагинов.',
    tasks: ['Перенос товара или человека в новую сцену', 'Редактирование фото по инструкции', 'Генерация по нескольким референсам'],
    where: ['E-commerce', 'Фотостудии', 'Маркетинг'],
    versions: [['OmniGen v1', '2024-10'], ['OmniGen2', '2025-06']],
    hf: 'https://huggingface.co/OmniGen2/OmniGen2',
    github: 'https://github.com/VectorSpaceLab/OmniGen2',
    alternatives: ['bagel', 'qwen-image', 'hidream'],
    source: 'https://huggingface.co/OmniGen2/OmniGen2',
    verified: true,
    en: {
      summary: 'An all-in-one model: generates, edits and moves an object or person from a photo into a new scene without separate plugins.',
      tasks: ['Placing a product or person into a new scene', 'Instruction-based photo editing', 'Generation from multiple references'],
      where: ['E-commerce', 'Photo studios', 'Marketing'],
      license: 'MIT (v1), Apache 2.0 (OmniGen2)',
      developer: 'BAAI (Beijing Academy of Artificial Intelligence)',
      country: 'China',
      sizes: 'about 4B',
    },
  },
  {
    id: 'z-image',
    name: 'Z-Image',
    developer: 'Alibaba (Tongyi-MAI)', country: 'Китай',
    modality: ['image'],
    first: '2025-11', latest: '2026-01',
    sizes: '6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Компактная модель на 6B с фотореализмом уровня крупных моделей. Turbo-версия выдаёт картинку за несколько шагов на обычной игровой видеокарте.',
    tasks: ['Фотореалистичные рекламные картинки', 'Картинки с текстом на английском и китайском', 'Массовая генерация визуалов'],
    where: ['E-commerce', 'Маркетинг и SMM', 'Медиа'],
    versions: [['Z-Image-Turbo', '2025-11'], ['Z-Image', '2026-01']],
    hf: 'https://huggingface.co/Tongyi-MAI/Z-Image',
    github: 'https://github.com/Tongyi-MAI/Z-Image',
    alternatives: ['flux', 'qwen-image', 'sana'],
    source: 'https://huggingface.co/Tongyi-MAI/Z-Image',
    verified: true,
    en: {
      summary: 'A compact 6B model with photorealism on par with large models. The Turbo version produces an image in a few steps on a regular gaming GPU.',
      tasks: ['Photorealistic ad images', 'Images with English and Chinese text', 'Bulk visual generation'],
      where: ['E-commerce', 'Marketing and social media', 'Media'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'glm-image',
    name: 'GLM-Image',
    developer: 'Zhipu AI (Z.ai)', country: 'Китай',
    modality: ['image'],
    first: '2026-01', latest: '2026-01',
    sizes: '9B + 7B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Гибрид языковой модели на 9B и декодера на 7B. Сильна в картинках с большим количеством текста: постеры, инфографика, слайды.',
    tasks: ['Постеры и баннеры с текстом', 'Инфографика', 'Иллюстрации к презентациям'],
    where: ['Маркетинг', 'Образование', 'Внутренние коммуникации'],
    versions: [['GLM-Image', '2026-01']],
    hf: 'https://huggingface.co/zai-org/GLM-Image',
    github: 'https://github.com/zai-org/GLM-Image',
    alternatives: ['qwen-image', 'hunyuan-image'],
    source: 'https://huggingface.co/zai-org/GLM-Image',
    verified: true,
    en: {
      summary: 'A hybrid of a 9B language model and a 7B decoder. Strong at text-heavy images: posters, infographics, slides.',
      tasks: ['Posters and banners with text', 'Infographics', 'Illustrations for presentations'],
      where: ['Marketing', 'Education', 'Internal communications'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'longcat-image',
    name: 'LongCat-Image',
    developer: 'Meituan', country: 'Китай',
    modality: ['image'],
    first: '2025-12', latest: '2026-02',
    sizes: '6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Модель генерации и редактирования картинок на 6B от Meituan. Хорошо пишет китайский текст, есть быстрая версия для правок.',
    tasks: ['Генерация картинок по описанию', 'Правка фото по инструкции', 'Визуалы для карточек товаров'],
    where: ['E-commerce', 'Доставка и ритейл', 'Маркетинг'],
    versions: [['LongCat-Image / Image-Edit', '2025-12'], ['LongCat-Image-Edit-Turbo', '2026-02']],
    hf: 'https://huggingface.co/meituan-longcat/LongCat-Image',
    github: 'https://github.com/meituan-longcat/LongCat-Image',
    alternatives: ['z-image', 'qwen-image'],
    source: 'https://huggingface.co/meituan-longcat/LongCat-Image-Edit-Turbo',
    verified: true,
    en: {
      summary: 'Meituan\'s 6B image generation and editing model. Renders Chinese text well; has a fast version for edits.',
      tasks: ['Image generation from descriptions', 'Instruction-based photo editing', 'Visuals for product cards'],
      where: ['E-commerce', 'Delivery and retail', 'Marketing'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'krea',
    name: 'Krea 2',
    developer: 'Krea', country: 'США',
    modality: ['image'],
    first: '2026-06', latest: '2026-06',
    sizes: '12B',
    license: 'Krea 2 Community License — бесплатно для команд до 50 мест, крупным компаниям нужен платный тариф, обязательна фильтрация контента',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Модель картинок на 12B с упором на реализм без глянцевого «ИИ-вида». Turbo-версия выдаёт 2K-картинку за пару секунд.',
    tasks: ['Реалистичные фото для рекламы', 'Картинки высокого разрешения', 'Дообучение стилей'],
    where: ['Маркетинг', 'Дизайн-студии', 'E-commerce'],
    versions: [['Krea 2 Raw / Turbo', '2026-06']],
    hf: 'https://huggingface.co/krea/Krea-2-Turbo',
    github: null,
    alternatives: ['flux', 'chroma', 'z-image'],
    source: 'https://huggingface.co/krea/Krea-2-Raw',
    verified: true,
    en: {
      summary: 'A 12B image model focused on realism without the glossy "AI look". The Turbo version produces a 2K image in a couple of seconds.',
      tasks: ['Realistic photos for advertising', 'High-resolution images', 'Style fine-tuning'],
      where: ['Marketing', 'Design studios', 'E-commerce'],
      license: 'Krea 2 Community License — free for teams up to 50 seats, large companies need a paid plan, content filtering is mandatory',
      country: 'USA',
    },
  },
  {
    id: 'ideogram',
    name: 'Ideogram 4',
    developer: 'Ideogram', country: 'Канада',
    modality: ['image'],
    first: '2026-05', latest: '2026-06',
    sizes: 'около 9B',
    license: 'Ideogram 4 Non-Commercial — только некоммерческое использование',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['science', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Открытые веса модели Ideogram, известной точной типографикой. Под некоммерческой лицензией: для бизнеса подходит только для тестов.',
    tasks: ['Тестирование генерации с текстом', 'Исследования и прототипы'],
    where: ['R&D-отделы', 'Дизайн-студии (эксперименты)'],
    versions: [['Ideogram 4 (fp8 / nf4)', '2026-05'], ['Ideogram 4 для diffusers', '2026-06']],
    hf: 'https://huggingface.co/ideogram-ai/ideogram-4-fp8',
    github: null,
    alternatives: ['glm-image', 'qwen-image'],
    source: 'https://huggingface.co/ideogram-ai/ideogram-4-fp8',
    verified: true,
    en: {
      summary: 'Open weights of the Ideogram model, known for precise typography. Under a non-commercial license: for business, suitable only for testing.',
      tasks: ['Testing text-in-image generation', 'Research and prototypes'],
      where: ['R&D departments', 'Design studios (experiments)'],
      license: 'Ideogram 4 Non-Commercial — non-commercial use only',
      country: 'Canada',
      sizes: 'about 9B',
    },
  },
  {
    id: 'chroma',
    name: 'Chroma',
    developer: 'lodestones (независимый разработчик)', country: 'нет данных',
    modality: ['image'],
    first: '2025-01', latest: '2026-07',
    sizes: '4B – 8.9B',
    license: 'Apache 2.0 у Chroma и Chroma2, у Kroma — Krea 2 Community License',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['media'],
    ollama: false,
    cpu: false,
    summary: 'Общественная модель, переобученная из FLUX.1-schnell с упрощённой архитектурой. Без цензуры стилей, популярна как база для дообучения.',
    tasks: ['База для дообучения своих стилей', 'Художественные иллюстрации', 'Картинки для игр'],
    where: ['Дизайн-студии', 'Геймдев', 'Энтузиасты и R&D'],
    versions: [['Chroma (превью)', '2025-01'], ['Chroma1-Base', '2025-07'], ['Chroma1-HD / Flash', '2025-08'], ['Chroma2-Kaleidoscope', '2026-01'], ['Kroma', '2026-07']],
    hf: 'https://huggingface.co/lodestones/Chroma1-HD',
    github: null,
    alternatives: ['flux', 'krea'],
    source: 'https://huggingface.co/lodestones/Kroma',
    verified: true,
    en: {
      summary: 'A community model retrained from FLUX.1-schnell with a simplified architecture. No style censorship; popular as a base for fine-tuning.',
      tasks: ['Base for fine-tuning your own styles', 'Artistic illustrations', 'Images for games'],
      where: ['Design studios', 'Game development', 'Enthusiasts and R&D'],
      license: 'Apache 2.0 for Chroma and Chroma2, Krea 2 Community License for Kroma',
      developer: 'lodestones (independent developer)',
      country: 'not disclosed',
    },
  },
  {
    id: 'bagel',
    name: 'BAGEL',
    developer: 'ByteDance Seed', country: 'Китай',
    modality: ['image', 'vlm'],
    first: '2025-05', latest: '2025-05',
    sizes: '14B-A7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['retail', 'dev', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Единая модель, которая и понимает картинки, и генерирует, и редактирует их по диалогу. Похожа на то, как работают картинки в ChatGPT.',
    tasks: ['Редактирование фото в диалоге', 'Ответы на вопросы по изображению', 'Генерация картинок с пояснениями'],
    where: ['Продуктовые команды', 'E-commerce', 'R&D'],
    versions: [['BAGEL-7B-MoT', '2025-05']],
    hf: 'https://huggingface.co/ByteDance-Seed/BAGEL-7B-MoT',
    github: 'https://github.com/ByteDance-Seed/Bagel',
    alternatives: ['omnigen', 'janus', 'qwen-image'],
    source: 'https://huggingface.co/ByteDance-Seed/BAGEL-7B-MoT',
    verified: true,
    en: {
      summary: 'A unified model that understands images, generates them and edits them in a conversation. Similar to how images work in ChatGPT.',
      tasks: ['Photo editing in a conversation', 'Answering questions about an image', 'Image generation with explanations'],
      where: ['Product teams', 'E-commerce', 'R&D'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'controlnet',
    name: 'ControlNet',
    developer: 'Лвминь Чжан (Стэнфорд) и сообщество', country: 'США',
    modality: ['image'],
    first: '2023-02', latest: '2024-07',
    sizes: '0.4B – 1.3B',
    license: 'OpenRAIL (оригинал), Apache 2.0 у популярных версий под SDXL',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Надстройка над моделями картинок: задаёт позу, контуры, глубину или планировку, чтобы результат точно повторял нужную композицию.',
    tasks: ['Картинка по эскизу или контуру', 'Сохранение позы и композиции', 'Визуализация интерьеров по планировке', 'Серии в едином ракурсе'],
    where: ['Дизайн интерьеров и архитектура', 'Реклама', 'Мода и одежда'],
    versions: [['ControlNet 1.0', '2023-02'], ['ControlNet 1.1', '2023-04'], ['ControlNet Union SDXL', '2024-07']],
    hf: 'https://huggingface.co/lllyasviel/ControlNet',
    github: 'https://github.com/lllyasviel/ControlNet',
    alternatives: ['stable-diffusion', 'flux'],
    source: 'https://huggingface.co/xinsir/controlnet-union-sdxl-1.0',
    verified: true,
    en: {
      summary: 'An add-on for image models: sets pose, outlines, depth or floor plan so the result follows the required composition exactly.',
      tasks: ['Image from a sketch or outline', 'Keeping pose and composition', 'Interior visualization from a floor plan', 'Series with a consistent angle'],
      where: ['Interior design and architecture', 'Advertising', 'Fashion and apparel'],
      license: 'OpenRAIL (original), Apache 2.0 for popular SDXL versions',
      developer: 'Lvmin Zhang (Stanford) and the community',
      country: 'USA',
    },
  },

  // ---------- Видео ----------
  {
    id: 'animatediff',
    name: 'AnimateDiff',
    developer: 'Shanghai AI Lab и CUHK', country: 'Китай',
    modality: ['video'],
    first: '2023-07', latest: '2024-07',
    sizes: 'модуль движения поверх SD 1.5 / SDXL',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Модуль, который оживляет модели картинок Stable Diffusion и превращает их в короткую анимацию. Одна из первых открытых видеотехнологий.',
    tasks: ['Короткие анимации в фирменном стиле', 'Живые обложки и баннеры', 'Анимированные стикеры'],
    where: ['SMM', 'Дизайн-студии', 'Реклама'],
    versions: [['AnimateDiff v1', '2023-07'], ['AnimateDiff v3', '2023-12'], ['SparseCtrl', '2024-07']],
    hf: 'https://huggingface.co/guoyww/animatediff',
    github: 'https://github.com/guoyww/AnimateDiff',
    alternatives: ['stable-video-diffusion', 'ltx-video'],
    source: 'https://huggingface.co/guoyww/animatediff-sparsectrl-rgb',
    verified: true,
    en: {
      summary: 'A module that brings Stable Diffusion image models to life, turning them into short animations. One of the first open video technologies.',
      tasks: ['Short animations in brand style', 'Animated covers and banners', 'Animated stickers'],
      where: ['Social media', 'Design studios', 'Advertising'],
      license: 'Apache 2.0',
      developer: 'Shanghai AI Lab and CUHK',
      country: 'China',
      sizes: 'motion module on top of SD 1.5 / SDXL',
    },
  },
  {
    id: 'stable-video-diffusion',
    name: 'Stable Video Diffusion',
    developer: 'Stability AI', country: 'Великобритания',
    modality: ['video'],
    first: '2023-11', latest: '2023-11',
    sizes: 'около 1.5B',
    license: 'Stability AI Community License — бесплатно при выручке до $1 млн в год',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Первая открытая модель Stability AI для видео: оживляет фото в ролик на 2–4 секунды. Сейчас уступает новым моделям по качеству.',
    tasks: ['Оживление фото товара', 'Короткие видеозаставки', 'Анимация иллюстраций'],
    where: ['E-commerce', 'SMM'],
    versions: [['SVD / SVD-XT', '2023-11']],
    hf: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt',
    github: 'https://github.com/Stability-AI/generative-models',
    alternatives: ['ltx-video', 'wan', 'cogvideox'],
    source: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt',
    verified: true,
    en: {
      summary: 'Stability AI\'s first open video model: turns a photo into a 2–4 second clip. Now behind newer models in quality.',
      tasks: ['Animating product photos', 'Short video intros', 'Animating illustrations'],
      where: ['E-commerce', 'Social media'],
      license: 'Stability AI Community License — free for revenue under $1M per year',
      country: 'UK',
      sizes: 'about 1.5B',
    },
  },
  {
    id: 'open-sora',
    name: 'Open-Sora',
    developer: 'HPC-AI Tech', country: 'Сингапур',
    modality: ['video'],
    first: '2024-03', latest: '2025-03',
    sizes: 'до 11B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'na',
    industries: ['science', 'media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Полностью открытый проект видеогенерации: веса, код и рецепт обучения. Версия 2.0 на 11B делает видео из текста и из картинки.',
    tasks: ['Видео по текстовому описанию', 'Оживление картинок', 'Обучение своей видеомодели'],
    where: ['R&D', 'Медиа', 'Реклама'],
    versions: [['Open-Sora 1.0', '2024-03'], ['Open-Sora 1.2', '2024-06'], ['Open-Sora 2.0', '2025-03']],
    hf: 'https://huggingface.co/hpcai-tech/Open-Sora-v2',
    github: 'https://github.com/hpcaitech/Open-Sora',
    alternatives: ['wan', 'hunyuan-video', 'cogvideox'],
    source: 'https://huggingface.co/hpcai-tech/Open-Sora-v2',
    verified: true,
    en: {
      summary: 'A fully open video generation project: weights, code and training recipe. Version 2.0 at 11B makes video from text and from an image.',
      tasks: ['Video from a text description', 'Animating images', 'Training your own video model'],
      where: ['R&D', 'Media', 'Advertising'],
      license: 'Apache 2.0',
      country: 'Singapore',
      sizes: 'up to 11B',
    },
  },
  {
    id: 'cogvideox',
    name: 'CogVideoX',
    developer: 'Zhipu AI (Z.ai) и Университет Цинхуа', country: 'Китай',
    modality: ['video'],
    first: '2024-08', latest: '2024-11',
    sizes: '2B – 5B',
    license: '2B — Apache 2.0, 5B — CogVideoX License (коммерция после регистрации и с ограничениями)',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'science', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Модель видео на 2–5B, которая запускается на одной игровой видеокарте. Популярная база для исследований и надстроек.',
    tasks: ['Короткие ролики из текста', 'Оживление изображений', 'Эксперименты с дообучением видео'],
    where: ['Маркетинг', 'R&D', 'Образование'],
    versions: [['CogVideoX-2B / 5B', '2024-08'], ['CogVideoX 1.5-5B', '2024-11']],
    hf: 'https://huggingface.co/zai-org/CogVideoX1.5-5B',
    github: 'https://github.com/zai-org/CogVideo',
    alternatives: ['wan', 'ltx-video', 'hunyuan-video'],
    source: 'https://huggingface.co/zai-org/CogVideoX1.5-5B',
    verified: true,
    en: {
      summary: 'A 2–5B video model that runs on a single gaming GPU. A popular base for research and add-ons.',
      tasks: ['Short clips from text', 'Animating images', 'Video fine-tuning experiments'],
      where: ['Marketing', 'R&D', 'Education'],
      license: '2B — Apache 2.0, 5B — CogVideoX License (commercial use after registration and with restrictions)',
      developer: 'Zhipu AI (Z.ai) and Tsinghua University',
      country: 'China',
    },
  },
  {
    id: 'mochi',
    name: 'Mochi',
    developer: 'Genmo', country: 'США',
    modality: ['video'],
    first: '2024-10', latest: '2024-10',
    sizes: '10B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Открытая видеомодель на 10B с реалистичным движением. На момент выхода была одной из сильнейших открытых, сейчас обновлений нет.',
    tasks: ['Видео по описанию', 'Короткие рекламные сцены'],
    where: ['Реклама', 'Медиа'],
    versions: [['Mochi 1 preview', '2024-10']],
    hf: 'https://huggingface.co/genmo/mochi-1-preview',
    github: 'https://github.com/genmoai/mochi',
    alternatives: ['wan', 'hunyuan-video', 'ltx-video'],
    source: 'https://huggingface.co/genmo/mochi-1-preview',
    verified: true,
    en: {
      summary: 'An open 10B video model with realistic motion. At release it was among the strongest open models; no updates now.',
      tasks: ['Video from a description', 'Short ad scenes'],
      where: ['Advertising', 'Media'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'ltx-video',
    name: 'LTX-Video / LTX-2',
    developer: 'Lightricks', country: 'Израиль',
    modality: ['video', 'audio'],
    first: '2024-10', latest: '2026-07',
    sizes: '2B – 22B',
    license: 'LTX-Video 0.9 — Apache 2.0; LTX-2 и новее — LTX-2 Community License (бесплатно при выручке до $10 млн в год)',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['marketing', 'media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Быстрая видеомодель, которая с LTX-2 генерирует видео сразу со звуком и речью. Можно управлять камерой и позой, есть облегчённые версии.',
    tasks: ['Рекламные ролики со звуком', 'Видео из фото товара', 'Озвученные сцены для соцсетей', 'Управление камерой и движением'],
    where: ['Маркетинг и SMM', 'Продакшн-студии', 'E-commerce'],
    versions: [['LTX-Video 0.9', '2024-10'], ['LTX-2', '2026-01'], ['LTX-2.3', '2026-03'], ['LTX-2.5', '2026-07']],
    hf: 'https://huggingface.co/Lightricks/LTX-2.5',
    github: 'https://github.com/Lightricks/LTX-2',
    alternatives: ['wan', 'hunyuan-video', 'magi'],
    source: 'https://huggingface.co/Lightricks/LTX-2.5',
    verified: true,
    en: {
      summary: 'A fast video model; with LTX-2 it generates video with sound and speech in one go. Camera and pose control, lightweight versions available.',
      tasks: ['Ad videos with sound', 'Video from a product photo', 'Voiced scenes for social media', 'Camera and motion control'],
      where: ['Marketing and social media', 'Production studios', 'E-commerce'],
      license: 'LTX-Video 0.9 — Apache 2.0; LTX-2 and newer — LTX-2 Community License (free for revenue under $10M per year)',
      country: 'Israel',
    },
  },
  {
    id: 'hunyuan-video',
    name: 'HunyuanVideo',
    developer: 'Tencent', country: 'Китай',
    modality: ['video'],
    first: '2024-12', latest: '2025-11',
    sizes: '8.3B – 13B',
    license: 'Tencent Hunyuan Community License — не действует в ЕС, Великобритании и Южной Корее',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Видеомодель Tencent, одна из первых открытых на уровне закрытых сервисов. Версия 1.5 стала легче (8.3B) и идёт на потребительских картах.',
    tasks: ['Видео по текстовому сценарию', 'Оживление изображений', 'База для дообучения своих видеомоделей'],
    where: ['Реклама', 'Медиа', 'Геймдев'],
    versions: [['HunyuanVideo', '2024-12'], ['HunyuanVideo-I2V', '2025-03'], ['HunyuanVideo 1.5', '2025-11']],
    hf: 'https://huggingface.co/tencent/HunyuanVideo-1.5',
    github: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-1.5',
    alternatives: ['wan', 'ltx-video', 'skyreels'],
    source: 'https://huggingface.co/tencent/HunyuanVideo-1.5',
    verified: true,
    en: {
      summary: 'Tencent\'s video model, one of the first open ones on par with closed services. Version 1.5 is lighter (8.3B) and runs on consumer GPUs.',
      tasks: ['Video from a text script', 'Animating images', 'Base for fine-tuning your own video models'],
      where: ['Advertising', 'Media', 'Game development'],
      license: 'Tencent Hunyuan Community License — not valid in the EU, UK and South Korea',
      country: 'China',
    },
  },
  {
    id: 'skyreels',
    name: 'SkyReels',
    developer: 'Skywork AI (Kunlun Tech)', country: 'Китай',
    modality: ['video', 'avatar'],
    first: '2025-02', latest: '2026-01',
    sizes: '1.3B – 19B',
    license: 'V1 — Apache 2.0, V2 и V3 — Skywork License (коммерция разрешена с условиями)',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Видеомодели для кинематографичных сцен с людьми. Умеют ролики неограниченной длины, продление видео и говорящих персонажей по аудио.',
    tasks: ['Длинные ролики с продолжением', 'Видео с одним персонажем по референсу', 'Говорящий аватар по голосу'],
    where: ['Продакшн-студии', 'Реклама', 'Сериалы и короткие драмы'],
    versions: [['SkyReels V1', '2025-02'], ['SkyReels V2', '2025-04'], ['SkyReels V3', '2026-01']],
    hf: 'https://huggingface.co/Skywork',
    github: 'https://github.com/SkyworkAI/SkyReels-V3',
    alternatives: ['wan', 'hunyuan-video', 'infinitetalk'],
    source: 'https://huggingface.co/Skywork/SkyReels-V3-A2V-19B',
    verified: true,
    en: {
      summary: 'Video models for cinematic scenes with people. Can make videos of unlimited length, extend videos and create talking characters from audio.',
      tasks: ['Long videos with continuation', 'Video with one character from a reference', 'Talking avatar from a voice'],
      where: ['Production studios', 'Advertising', 'Series and short dramas'],
      license: 'V1 — Apache 2.0, V2 and V3 — Skywork License (commercial use allowed with conditions)',
      country: 'China',
    },
  },
  {
    id: 'step-video',
    name: 'Step-Video',
    developer: 'StepFun', country: 'Китай',
    modality: ['video'],
    first: '2025-02', latest: '2025-03',
    sizes: '30B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['multi'],
    ru: 'na',
    industries: ['media', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Крупная видеомодель на 30B с роликами до 204 кадров. Требует серверного железа, зато открыта под MIT.',
    tasks: ['Видео по описанию', 'Оживление изображений'],
    where: ['Медиа', 'R&D', 'Продакшн'],
    versions: [['Step-Video-T2V', '2025-02'], ['Step-Video-TI2V', '2025-03']],
    hf: 'https://huggingface.co/stepfun-ai/stepvideo-t2v',
    github: 'https://github.com/stepfun-ai/Step-Video-T2V',
    alternatives: ['wan', 'hunyuan-video'],
    source: 'https://huggingface.co/stepfun-ai/stepvideo-ti2v',
    verified: true,
    en: {
      summary: 'A large 30B video model producing clips of up to 204 frames. Needs server hardware, but is open under MIT.',
      tasks: ['Video from a description', 'Animating images'],
      where: ['Media', 'R&D', 'Production'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'magi',
    name: 'MAGI',
    developer: 'Sand AI', country: 'Китай',
    modality: ['video', 'audio'],
    first: '2025-04', latest: '2026-08',
    sizes: '4.5B – 114B-A6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Видео, которое генерируется по кускам друг за другом, поэтому ролик можно продлевать бесконечно. MAGI-2 делает видео сразу со звуком.',
    tasks: ['Длинные ролики с продолжением', 'Видео со звуком', 'Оживление изображений'],
    where: ['Продакшн-студии', 'Медиа', 'Реклама'],
    versions: [['MAGI-1 24B / 4.5B', '2025-04'], ['MAGI-1 distill', '2025-05'], ['MAGI-2-preview', '2026-08']],
    hf: 'https://huggingface.co/sand-ai/MAGI-2-preview',
    github: 'https://github.com/SandAI-org/MAGI-1',
    alternatives: ['ltx-video', 'wan', 'skyreels'],
    source: 'https://huggingface.co/sand-ai/MAGI-2-preview',
    verified: true,
    en: {
      summary: 'Video generated chunk by chunk in sequence, so a clip can be extended indefinitely. MAGI-2 produces video with sound.',
      tasks: ['Long videos with continuation', 'Video with sound', 'Animating images'],
      where: ['Production studios', 'Media', 'Advertising'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'sana-video',
    name: 'SANA-Video',
    developer: 'NVIDIA', country: 'США',
    modality: ['video'],
    first: '2025-10', latest: '2026-08',
    sizes: '2B – 5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Лёгкая и быстрая видеомодель NVIDIA. Выдаёт 720p-ролики на одной видеокарте, есть версия на 4 шага для быстрой генерации.',
    tasks: ['Быстрые ролики для соцсетей', 'Массовая генерация видео', 'Видео из картинки'],
    where: ['SMM', 'E-commerce', 'Продуктовые команды'],
    versions: [['SANA-Video 2B 480p', '2025-10'], ['SANA-Video 2B 720p', '2026-03'], ['SANA-Video 2.0 5B', '2026-08']],
    hf: 'https://huggingface.co/Efficient-Large-Model/SANA-Video_2.0_5B_720p',
    github: 'https://github.com/NVlabs/Sana',
    alternatives: ['ltx-video', 'wan', 'cogvideox'],
    source: 'https://huggingface.co/Efficient-Large-Model/SANA-Video_2.0_5B_720p',
    verified: true,
    en: {
      summary: 'NVIDIA\'s lightweight, fast video model. Produces 720p clips on a single GPU; a 4-step version enables quick generation.',
      tasks: ['Quick clips for social media', 'Bulk video generation', 'Video from an image'],
      where: ['Social media', 'E-commerce', 'Product teams'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'longcat-video',
    name: 'LongCat-Video',
    developer: 'Meituan', country: 'Китай',
    modality: ['video'],
    first: '2025-10', latest: '2025-10',
    sizes: '13.6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Видеомодель на 13.6B: из текста, из картинки и продолжение видео. Держит качество на роликах в несколько минут.',
    tasks: ['Длинные ролики', 'Видео из фото', 'Продолжение готового видео'],
    where: ['Маркетинг', 'Медиа', 'E-commerce'],
    versions: [['LongCat-Video', '2025-10']],
    hf: 'https://huggingface.co/meituan-longcat/LongCat-Video',
    github: 'https://github.com/meituan-longcat/LongCat-Video',
    alternatives: ['wan', 'hunyuan-video', 'magi'],
    source: 'https://huggingface.co/meituan-longcat/LongCat-Video',
    verified: true,
    en: {
      summary: 'A 13.6B video model: from text, from an image and video continuation. Keeps quality on clips several minutes long.',
      tasks: ['Long videos', 'Video from a photo', 'Continuing an existing video'],
      where: ['Marketing', 'Media', 'E-commerce'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'minimax-h3',
    name: 'MiniMax H3 (Hailuo)',
    developer: 'MiniMax', country: 'Китай',
    modality: ['video'],
    first: '2026-07', latest: '2026-07',
    sizes: '33B + кодировщик 32B',
    license: 'MiniMax H3 Community License — собственная лицензия с условиями',
    commercial: 'conditional',
    hardware: ['multi'],
    ru: 'na',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Открытые веса видеомодели Hailuo от MiniMax. Крупная модель на 33B, делает видео по тексту и картинке, но требует нескольких серверных видеокарт.',
    tasks: ['Кинематографичные рекламные ролики', 'Видео по тексту и картинке', 'Сложные сцены с движением'],
    where: ['Продакшн-студии', 'Реклама', 'Медиа'],
    versions: [['MiniMax-H3', '2026-07']],
    hf: 'https://huggingface.co/MiniMaxAI/MiniMax-H3',
    github: null,
    alternatives: ['wan', 'ltx-video', 'magi'],
    source: 'https://huggingface.co/MiniMaxAI/MiniMax-H3',
    verified: true,
    en: {
      summary: 'Open weights of MiniMax\'s Hailuo video model. A large 33B model that makes video from text and images, but needs several server GPUs.',
      tasks: ['Cinematic ad videos', 'Video from text and images', 'Complex scenes with motion'],
      where: ['Production studios', 'Advertising', 'Media'],
      license: 'MiniMax H3 Community License — own license with conditions',
      country: 'China',
      sizes: '33B + 32B encoder',
    },
  },

  // ---------- Аватары ----------
  {
    id: 'sadtalker',
    name: 'SadTalker',
    developer: 'Сианьский университет Цзяотун и Tencent AI Lab', country: 'Китай',
    modality: ['avatar'],
    first: '2023-04', latest: '2023-07',
    sizes: 'меньше 1B',
    license: 'Apache 2.0 (код), MIT на карточке HF',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['education', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Старая лёгкая модель говорящей головы: одно фото и аудио превращаются в видео. Работает на слабом железе, но качество заметно ниже новых.',
    tasks: ['Говорящее фото для приветствия', 'Простые озвученные аватары'],
    where: ['Образование', 'SMM'],
    versions: [['SadTalker', '2023-04'], ['SadTalker V0.0.2', '2023-07']],
    hf: 'https://huggingface.co/vinthony/SadTalker',
    github: 'https://github.com/OpenTalker/SadTalker',
    alternatives: ['liveportrait', 'musetalk'],
    source: 'https://huggingface.co/vinthony/SadTalker-V002rc',
    verified: true,
    en: {
      summary: 'An older lightweight talking-head model: one photo plus audio becomes a video. Runs on weak hardware, but quality is noticeably below newer models.',
      tasks: ['Talking photo for greetings', 'Simple voiced avatars'],
      where: ['Education', 'Social media'],
      license: 'Apache 2.0 (code), MIT on the HF card',
      developer: 'Xi\'an Jiaotong University and Tencent AI Lab',
      country: 'China',
      sizes: 'under 1B',
    },
  },
  {
    id: 'liveportrait',
    name: 'LivePortrait',
    developer: 'Kuaishou (Kling)', country: 'Китай',
    modality: ['avatar'],
    first: '2024-07', latest: '2024-07',
    sizes: 'меньше 1B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['marketing', 'media', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Оживляет портрет по видео-образцу: мимика и повороты головы переносятся с актёра на фото. Быстро работает даже на слабой видеокарте.',
    tasks: ['Оживление портретов', 'Перенос мимики актёра на персонажа', 'Анимация маскотов'],
    where: ['SMM', 'Реклама', 'Музеи и образование'],
    versions: [['LivePortrait', '2024-07']],
    hf: 'https://huggingface.co/KwaiVGI/LivePortrait',
    github: 'https://github.com/KwaiVGI/LivePortrait',
    alternatives: ['sadtalker', 'echomimic'],
    source: 'https://huggingface.co/KwaiVGI/LivePortrait',
    verified: true,
    en: {
      summary: 'Animates a portrait from a reference video: an actor\'s facial expressions and head turns are transferred to the photo. Runs fast even on a weak GPU.',
      tasks: ['Animating portraits', 'Transferring an actor\'s expressions to a character', 'Mascot animation'],
      where: ['Social media', 'Advertising', 'Museums and education'],
      license: 'MIT',
      country: 'China',
      sizes: 'under 1B',
    },
  },
  {
    id: 'musetalk',
    name: 'MuseTalk',
    developer: 'Tencent Music (Lyra Lab)', country: 'Китай',
    modality: ['avatar'],
    first: '2024-04', latest: '2025-03',
    sizes: 'меньше 1B',
    license: 'MIT (код), веса разрешены для любых целей, включая коммерцию',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['education', 'media', 'support'],
    ollama: false,
    cpu: false,
    summary: 'Синхронизация губ в реальном времени: подгоняет рот на видео под новое аудио. Подходит для перевода видео и живых аватаров.',
    tasks: ['Дубляж видео на другой язык', 'Живой аватар в видеочате', 'Правка речи в готовом ролике'],
    where: ['Образование', 'Медиа', 'Поддержка клиентов'],
    versions: [['MuseTalk 1.0', '2024-04'], ['MuseTalk 1.5', '2025-03']],
    hf: 'https://huggingface.co/TMElyralab/MuseTalk',
    github: 'https://github.com/TMElyralab/MuseTalk',
    alternatives: ['liveportrait', 'infinitetalk', 'sadtalker'],
    source: 'https://github.com/TMElyralab/MuseTalk',
    verified: true,
    en: {
      summary: 'Real-time lip sync: matches the mouth in a video to new audio. Suits video translation and live avatars.',
      tasks: ['Dubbing video into another language', 'Live avatar in a video chat', 'Editing speech in a finished video'],
      where: ['Education', 'Media', 'Customer support'],
      license: 'MIT (code), weights allowed for any purpose including commercial',
      country: 'China',
      sizes: 'under 1B',
    },
  },
  {
    id: 'hallo',
    name: 'Hallo',
    developer: 'Фуданьский университет', country: 'Китай',
    modality: ['avatar'],
    first: '2024-06', latest: '2026-04',
    sizes: 'около 1B – 5B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['education', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Серия говорящих портретов по аудио: от коротких клипов до часовых видео в 4K. Hallo-Live рассчитана на работу в реальном времени.',
    tasks: ['Видео с ведущим по фото и аудио', 'Длинные обучающие ролики', 'Живой аватар'],
    where: ['Образование', 'Медиа', 'Корпоративное обучение'],
    versions: [['Hallo', '2024-06'], ['Hallo2', '2024-10'], ['Hallo3', '2024-11'], ['Hallo4', '2025-11'], ['Hallo-Live', '2026-04']],
    hf: 'https://huggingface.co/fudan-generative-ai/Hallo-Live',
    github: 'https://github.com/fudan-generative-vision/hallo',
    alternatives: ['echomimic', 'infinitetalk', 'musetalk'],
    source: 'https://huggingface.co/fudan-generative-ai/Hallo-Live',
    verified: true,
    en: {
      summary: 'A series of audio-driven talking portraits: from short clips to hour-long 4K videos. Hallo-Live is built for real-time use.',
      tasks: ['Presenter video from a photo and audio', 'Long training videos', 'Live avatar'],
      where: ['Education', 'Media', 'Corporate training'],
      license: 'MIT',
      developer: 'Fudan University',
      country: 'China',
      sizes: 'about 1B – 5B',
    },
  },
  {
    id: 'echomimic',
    name: 'EchoMimic',
    developer: 'Ant Group', country: 'Китай',
    modality: ['avatar'],
    first: '2024-07', latest: '2026-01',
    sizes: 'до 1.3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['education', 'finance', 'support', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Говорящие аватары от Ant Group: лицо, а с V2 и жесты рук. V3-Flash выдаёт видео за 8 шагов и укладывается в 12 ГБ видеопамяти.',
    tasks: ['Видео с ведущим по фото и голосу', 'Аватар с жестами для презентаций', 'Озвученные персонажи'],
    where: ['Образование', 'Финансы и поддержка', 'SMM'],
    versions: [['EchoMimic', '2024-07'], ['EchoMimic V2', '2024-11'], ['EchoMimic V3', '2025-08'], ['EchoMimic V3-Flash', '2026-01']],
    hf: 'https://huggingface.co/BadToBest/EchoMimicV3',
    github: 'https://github.com/antgroup/echomimic_v3',
    alternatives: ['hallo', 'infinitetalk', 'liveportrait'],
    source: 'https://github.com/antgroup/echomimic_v3',
    verified: true,
    en: {
      summary: 'Ant Group\'s talking avatars: the face and, from V2, hand gestures. V3-Flash produces video in 8 steps and fits into 12 GB of GPU memory.',
      tasks: ['Presenter video from a photo and voice', 'Avatar with gestures for presentations', 'Voiced characters'],
      where: ['Education', 'Finance and support', 'Social media'],
      license: 'Apache 2.0',
      country: 'China',
      sizes: 'up to 1.3B',
    },
  },
  {
    id: 'infinitetalk',
    name: 'MultiTalk / InfiniteTalk',
    developer: 'Meituan', country: 'Китай',
    modality: ['avatar'],
    first: '2025-06', latest: '2025-08',
    sizes: '14B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['media', 'education', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Дубляж и говорящие персонажи на базе Wan: MultiTalk ведёт диалог нескольких людей, InfiniteTalk переозвучивает видео любой длины с мимикой и телом.',
    tasks: ['Дубляж видео с подгонкой мимики', 'Диалог двух персонажей по аудио', 'Длинные ролики с ведущим'],
    where: ['Медиа и продакшн', 'Образование', 'Реклама'],
    versions: [['MultiTalk', '2025-06'], ['InfiniteTalk', '2025-08']],
    hf: 'https://huggingface.co/MeiGen-AI/InfiniteTalk',
    github: 'https://github.com/MeiGen-AI/InfiniteTalk',
    alternatives: ['hallo', 'longcat-video-avatar', 'musetalk'],
    source: 'https://huggingface.co/MeiGen-AI/InfiniteTalk',
    verified: true,
    en: {
      summary: 'Dubbing and talking characters built on Wan: MultiTalk handles dialogue between several people, InfiniteTalk re-dubs videos of any length with facial and body motion.',
      tasks: ['Video dubbing with matched facial expressions', 'Dialogue between two characters from audio', 'Long videos with a presenter'],
      where: ['Media and production', 'Education', 'Advertising'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'hunyuan-video-avatar',
    name: 'HunyuanVideo-Avatar',
    developer: 'Tencent', country: 'Китай',
    modality: ['avatar'],
    first: '2025-05', latest: '2025-05',
    sizes: 'около 13B',
    license: 'Tencent Hunyuan Community License — не действует в ЕС, Великобритании и Южной Корее',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['marketing', 'media', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Говорящие персонажи на базе HunyuanVideo: передаёт эмоции голоса, работает с несколькими персонажами и разными стилями.',
    tasks: ['Видео с ведущим по фото и аудио', 'Сцены с несколькими говорящими', 'Мультяшные персонажи'],
    where: ['Реклама', 'Медиа', 'Образование'],
    versions: [['HunyuanVideo-Avatar', '2025-05']],
    hf: 'https://huggingface.co/tencent/HunyuanVideo-Avatar',
    github: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-Avatar',
    alternatives: ['infinitetalk', 'hallo', 'echomimic'],
    source: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-Avatar',
    verified: true,
    en: {
      summary: 'Talking characters built on HunyuanVideo: conveys emotions from the voice, handles several characters and different styles.',
      tasks: ['Presenter video from a photo and audio', 'Scenes with several speakers', 'Cartoon characters'],
      where: ['Advertising', 'Media', 'Education'],
      license: 'Tencent Hunyuan Community License — not valid in the EU, UK and South Korea',
      country: 'China',
      sizes: 'about 13B',
    },
  },
  {
    id: 'liveavatar',
    name: 'Live Avatar',
    developer: 'Alibaba (Quark)', country: 'Китай',
    modality: ['avatar'],
    first: '2025-12', latest: '2026-01',
    sizes: '14B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['support', 'retail', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Потоковый аватар в реальном времени неограниченной длины. Подходит для живых эфиров и диалога, но требует мощного серверного железа.',
    tasks: ['Живой аватар для диалога с клиентом', 'Бесконечные трансляции с ведущим', 'Интерактивные персонажи'],
    where: ['Поддержка клиентов', 'Стриминг и e-commerce', 'Образование'],
    versions: [['Live Avatar', '2025-12'], ['Live Avatar v1.1 (FP8)', '2026-01']],
    hf: 'https://huggingface.co/Quark-Vision/Live-Avatar',
    github: 'https://github.com/Alibaba-Quark/LiveAvatar',
    alternatives: ['hallo', 'infinitetalk', 'musetalk'],
    source: 'https://github.com/Alibaba-Quark/LiveAvatar',
    verified: true,
    en: {
      summary: 'A real-time streaming avatar of unlimited length. Suits live broadcasts and dialogue, but needs powerful server hardware.',
      tasks: ['Live avatar for customer dialogue', 'Endless broadcasts with a presenter', 'Interactive characters'],
      where: ['Customer support', 'Streaming and e-commerce', 'Education'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'longcat-video-avatar',
    name: 'LongCat-Video-Avatar',
    developer: 'Meituan', country: 'Китай',
    modality: ['avatar'],
    first: '2025-12', latest: '2026-05',
    sizes: 'на базе LongCat-Video 13.6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['media', 'education', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Говорящие люди по аудио на базе LongCat-Video. Версия 1.5 доведена до продакшна: стабильные длинные ролики на китайском и английском.',
    tasks: ['Видео с ведущим новостей или курса', 'Промо-ролики с говорящим персонажем', 'Пение и озвучка'],
    where: ['Медиа', 'Образование', 'Реклама'],
    versions: [['LongCat-Video-Avatar', '2025-12'], ['LongCat-Video-Avatar 1.5', '2026-05']],
    hf: 'https://huggingface.co/meituan-longcat/LongCat-Video-Avatar-1.5',
    github: 'https://github.com/meituan-longcat/LongCat-Video',
    alternatives: ['infinitetalk', 'hallo', 'liveavatar'],
    source: 'https://huggingface.co/meituan-longcat/LongCat-Video-Avatar-1.5',
    verified: true,
    en: {
      summary: 'Audio-driven talking people built on LongCat-Video. Version 1.5 is production-ready: stable long videos in Chinese and English.',
      tasks: ['News or course presenter videos', 'Promo videos with a talking character', 'Singing and voice-over'],
      where: ['Media', 'Education', 'Advertising'],
      license: 'MIT',
      country: 'China',
      sizes: 'based on LongCat-Video 13.6B',
    },
  },
];
