// 3D, компьютерное зрение, эмбеддинги для поиска и RAG, прогнозы временных рядов, роботы.
// Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- 3D ----------
  {
    id: 'point-e',
    name: 'Point-E / Shap-E',
    developer: 'OpenAI', country: 'США',
    modality: ['3d'],
    first: '2022-12', latest: '2023-05',
    sizes: '40M – 1B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Ранние открытые модели OpenAI, которые делают 3D-объект по тексту или картинке за секунды. Качество простое, зато быстро и легко запускается.',
    tasks: ['Черновые 3D-макеты по описанию', 'Быстрые прототипы объектов для игр и AR', 'Учебные и исследовательские пилоты по 3D'],
    where: ['Геймдев', 'Дизайн и прототипирование', 'Образование'],
    versions: [['Point-E', '2022-12'], ['Shap-E', '2023-05']],
    hf: 'https://huggingface.co/openai/shap-e',
    github: 'https://github.com/openai/shap-e',
    alternatives: ['triposr', 'trellis'],
    source: 'https://huggingface.co/openai/shap-e',
    verified: true,
  },
  {
    id: 'triposr',
    name: 'TripoSR / TripoSG',
    developer: 'VAST (TripoSR — вместе со Stability AI)', country: 'Китай',
    modality: ['3d'],
    first: '2024-03', latest: '2026-05',
    sizes: 'до 1.5B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Семейство VAST: 3D-модель по одной фотографии. TripoSR работает меньше секунды, TripoSG даёт более чистую геометрию, TripoSplat строит сцену из гауссовых точек.',
    tasks: ['3D-модель товара по фото', 'Заготовки объектов для игр и AR', 'Быстрый 3D-прототип для печати'],
    where: ['Онлайн-торговля', 'Геймдев', '3D-печать и дизайн'],
    versions: [['TripoSR', '2024-03'], ['TripoSG', '2025-03'], ['TripoSF', '2025-03'], ['TripoSplat', '2026-05']],
    hf: 'https://huggingface.co/VAST-AI/TripoSG',
    github: 'https://github.com/VAST-AI-Research/TripoSG',
    alternatives: ['stable-fast-3d', 'trellis', 'hunyuan3d'],
    source: 'https://huggingface.co/VAST-AI/TripoSplat',
    verified: true,
  },
  {
    id: 'stable-fast-3d',
    name: 'Stable Fast 3D / SPAR3D',
    developer: 'Stability AI', country: 'Великобритания',
    modality: ['3d'],
    first: '2024-08', latest: '2025-01',
    sizes: '1B – 2B',
    license: 'Stability AI Community License: бесплатно при выручке до 1 млн долларов в год, дальше нужна платная лицензия',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Модели Stability AI, которые за секунду превращают одну фотографию в 3D-модель с текстурой. SPAR3D позволяет поправить форму через облако точек.',
    tasks: ['3D-карточки товаров по фото', 'Ассеты для игр и AR', 'Быстрые макеты для дизайна'],
    where: ['Онлайн-торговля', 'Геймдев', 'Маркетинг и реклама'],
    versions: [['Stable Fast 3D (SF3D)', '2024-08'], ['SPAR3D', '2025-01']],
    hf: 'https://huggingface.co/stabilityai/stable-point-aware-3d',
    github: 'https://github.com/Stability-AI/stable-point-aware-3d',
    alternatives: ['triposr', 'trellis'],
    source: 'https://huggingface.co/stabilityai/stable-point-aware-3d',
    verified: true,
  },
  {
    id: 'instantmesh',
    name: 'InstantMesh',
    developer: 'Tencent ARC', country: 'Китай',
    modality: ['3d'],
    first: '2024-04', latest: '2024-04',
    sizes: 'н/д',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Делает 3D-сетку по одной картинке примерно за 10 секунд: сначала рисует объект с нескольких ракурсов, потом собирает из них модель.',
    tasks: ['3D-модель объекта по фото', 'Заготовки для игр и визуализаций', 'Прототипы для 3D-печати'],
    where: ['Геймдев', 'Дизайн', 'Онлайн-торговля'],
    versions: [['InstantMesh', '2024-04']],
    hf: 'https://huggingface.co/TencentARC/InstantMesh',
    github: 'https://github.com/TencentARC/InstantMesh',
    alternatives: ['triposr', 'stable-fast-3d'],
    source: 'https://huggingface.co/TencentARC/InstantMesh',
    verified: true,
  },
  {
    id: 'trellis',
    name: 'TRELLIS',
    developer: 'Microsoft', country: 'США',
    modality: ['3d'],
    first: '2024-12', latest: '2025-12',
    sizes: 'до 4B (TRELLIS.2)',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Одна из сильнейших открытых 3D-моделей: по картинке или тексту выдаёт сетку с текстурой или гауссову сцену. TRELLIS.2 заметно детальнее первой версии.',
    tasks: ['3D-модели товаров и интерьера по фото', 'Ассеты для игр и AR/VR', 'Прототипы для 3D-печати'],
    where: ['Геймдев', 'Онлайн-торговля', 'Архитектура и интерьер'],
    versions: [['TRELLIS (по картинке)', '2024-12'], ['TRELLIS (по тексту)', '2025-03'], ['TRELLIS.2', '2025-12']],
    hf: 'https://huggingface.co/microsoft/TRELLIS.2-4B',
    github: 'https://github.com/microsoft/TRELLIS.2',
    alternatives: ['hunyuan3d', 'triposr'],
    source: 'https://huggingface.co/microsoft/TRELLIS.2-4B',
    verified: true,
  },
  {
    id: 'hunyuan3d',
    name: 'Hunyuan3D',
    developer: 'Tencent', country: 'Китай',
    modality: ['3d'],
    first: '2024-11', latest: '2025-09',
    sizes: 'набор моделей: форма и текстуры',
    license: 'Tencent Hunyuan Community License: коммерция разрешена, но лицензия не действует в ЕС, Великобритании и Южной Корее; версии 2.5 и новее только через API',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Открытая 3D-линейка Tencent: форма и текстура по картинке, качество на уровне платных сервисов. Omni добавляет управление позой и формой, Part делит модель на детали.',
    tasks: ['3D-модели товаров с текстурой', 'Персонажи и предметы для игр', 'Разделение модели на детали для печати'],
    where: ['Геймдев', 'Онлайн-торговля', 'Промышленный дизайн'],
    versions: [['Hunyuan3D 1.0', '2024-11'], ['Hunyuan3D 2.0', '2025-01'], ['Hunyuan3D 2mini / 2mv', '2025-03'], ['Hunyuan3D 2.1', '2025-06'], ['Hunyuan3D-Omni и Part', '2025-09']],
    hf: 'https://huggingface.co/tencent/Hunyuan3D-2.1',
    github: 'https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1',
    alternatives: ['trellis', 'triposr'],
    source: 'https://huggingface.co/tencent/Hunyuan3D-Omni',
    verified: true,
  },
  {
    id: 'hy-world',
    name: 'HY-World (HunyuanWorld)',
    developer: 'Tencent', country: 'Китай',
    modality: ['3d', 'video'],
    first: '2025-07', latest: '2026-04',
    sizes: 'набор из нескольких моделей',
    license: 'Собственная лицензия Tencent: коммерция разрешена, но не действует в ЕС, Великобритании и Южной Корее',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Генерация целых 3D-миров и сцен по тексту или картинке, по которым можно ходить. Вторая версия собирает сцену из видео и фото.',
    tasks: ['3D-сцены для игр и виртуальных туров', 'Фоны и окружение для видеопродакшна', 'Черновики локаций для симуляций'],
    where: ['Геймдев', 'Кино и реклама', 'Недвижимость и туризм'],
    versions: [['HunyuanWorld 1.0', '2025-07'], ['HunyuanWorld-Voyager', '2025-08'], ['HunyuanWorld-Mirror', '2025-10'], ['HY-WorldPlay', '2025-12'], ['HY-World 2.0', '2026-04']],
    hf: 'https://huggingface.co/tencent/HY-World-2.0',
    github: 'https://github.com/Tencent-Hunyuan/HY-World-2.0',
    alternatives: ['hunyuan3d', 'cosmos'],
    source: 'https://huggingface.co/tencent/HY-World-2.0',
    verified: true,
  },
  {
    id: 'sam-3d',
    name: 'SAM 3D',
    developer: 'Meta', country: 'США',
    modality: ['3d', 'vision'],
    first: '2025-11', latest: '2025-11',
    sizes: 'н/д',
    license: 'SAM License (собственная лицензия Meta, коммерция разрешена с условиями); доступ по запросу на HF',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Восстанавливает 3D-форму предмета или тела человека по одной обычной фотографии, даже если объект частично закрыт. Две модели: Objects и Body.',
    tasks: ['3D-модель предмета с фото из каталога', 'Оценка позы и формы тела по фото', 'Примерка и AR-сценарии'],
    where: ['Онлайн-торговля', 'Фитнес и спорт', 'AR и виртуальная примерка'],
    versions: [['SAM 3D Objects', '2025-11'], ['SAM 3D Body', '2025-11']],
    hf: 'https://huggingface.co/facebook/sam-3d-objects',
    github: 'https://github.com/facebookresearch/sam-3d-objects',
    alternatives: ['sam', 'trellis', 'hunyuan3d'],
    source: 'https://huggingface.co/facebook/sam-3d-body-dinov3',
    verified: true,
  },

  // ---------- Компьютерное зрение ----------
  {
    id: 'yolo',
    name: 'YOLO (Ultralytics)',
    developer: 'Ultralytics', country: 'США',
    modality: ['vision'],
    first: '2023-01', latest: '2026-01',
    sizes: '2.4M – 68M',
    license: 'AGPL-3.0 (код продукта придётся открыть) или платная корпоративная лицензия Ultralytics',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Самый распространённый детектор объектов в реальном времени: находит и выделяет предметы на видео даже на слабом железе. YOLOv5 вышел ещё в 2020, в каталоге отсчёт от YOLOv8.',
    tasks: ['Подсчёт людей, машин, товаров на видео', 'Контроль касок и спецодежды', 'Поиск брака на конвейере', 'Выкладка на полках'],
    where: ['Производство', 'Ритейл и склады', 'Безопасность и видеонаблюдение', 'Транспорт'],
    versions: [['YOLOv8', '2023-01'], ['YOLO11', '2024-09'], ['YOLO26', '2026-01']],
    hf: 'https://huggingface.co/Ultralytics/YOLO26',
    github: 'https://github.com/ultralytics/ultralytics',
    alternatives: ['rf-detr', 'grounding-dino'],
    source: 'https://huggingface.co/Ultralytics/YOLO26',
    verified: true,
  },
  {
    id: 'rf-detr',
    name: 'RF-DETR',
    developer: 'Roboflow', country: 'США',
    modality: ['vision'],
    first: '2025-03', latest: '2026-06',
    sizes: 'Nano – 2XL',
    license: 'Apache 2.0 для размеров Nano–Large; XL и 2XL под собственной лицензией Roboflow',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Детектор объектов в реальном времени, открытая замена YOLO без AGPL. Умеет сегментацию (контуры объектов), с 2026 года — ключевые точки.',
    tasks: ['Детекция объектов на видео и фото', 'Точные контуры деталей и дефектов', 'Дообучение под свои классы объектов'],
    where: ['Производство', 'Склады и логистика', 'Сельское хозяйство', 'Видеоаналитика'],
    versions: [['RF-DETR Base/Large', '2025-03'], ['RF-DETR Nano/Small/Medium', '2025-07'], ['RF-DETR Seg (превью)', '2025-10'], ['RF-DETR 1.4: сегментация и XL', '2026-01'], ['Ключевые точки (превью)', '2026-06']],
    hf: null,
    github: 'https://github.com/roboflow/rf-detr',
    alternatives: ['yolo', 'grounding-dino'],
    source: 'https://github.com/roboflow/rf-detr/releases',
    verified: true,
  },
  {
    id: 'grounding-dino',
    name: 'Grounding DINO / Rex-Omni',
    developer: 'IDEA Research', country: 'Китай',
    modality: ['vision'],
    first: '2023-03', latest: '2025-10',
    sizes: '172M – 3B',
    license: 'Grounding DINO — Apache 2.0; Rex-Omni — собственная IDEA License на базе Qwen Research License',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Находит на картинке любые объекты по текстовому описанию, без обучения на своих данных: «красная коробка», «человек без каски». Rex-Omni — новое поколение на базе VLM.',
    tasks: ['Поиск объектов по описанию без разметки', 'Автоматическая разметка данных для обучения', 'Проверка фото на соответствие требованиям'],
    where: ['Видеоаналитика', 'Ритейл', 'Подготовка данных для ИИ'],
    versions: [['Grounding DINO', '2023-03'], ['Rex-Omni', '2025-10']],
    hf: 'https://huggingface.co/IDEA-Research/grounding-dino-base',
    github: 'https://github.com/IDEA-Research/GroundingDINO',
    alternatives: ['yolo', 'rf-detr', 'sam'],
    source: 'https://huggingface.co/IDEA-Research/Rex-Omni',
    verified: true,
  },
  {
    id: 'dino',
    name: 'DINOv2 / DINOv3',
    developer: 'Meta', country: 'США',
    modality: ['vision'],
    first: '2023-04', latest: '2025-08',
    sizes: '21M – 7B',
    license: 'DINOv2 — Apache 2.0; DINOv3 — собственная DINOv3 License, коммерция разрешена, доступ по запросу',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Базовые модели, которые превращают картинку в числовой «отпечаток». На них строят поиск похожих изображений, классификацию и сегментацию без большой разметки.',
    tasks: ['Поиск похожих товаров и фото', 'Классификация изображений на малых данных', 'Основа для своих моделей контроля качества'],
    where: ['Ритейл и маркетплейсы', 'Производство', 'Спутниковые снимки и агро'],
    versions: [['DINOv2', '2023-04'], ['DINOv3', '2025-08']],
    hf: 'https://huggingface.co/facebook/dinov3-vitl16-pretrain-lvd1689m',
    github: 'https://github.com/facebookresearch/dinov3',
    alternatives: ['clip-siglip', 'sam'],
    source: 'https://huggingface.co/facebook/dinov3-vit7b16-pretrain-lvd1689m',
    verified: true,
  },
  {
    id: 'depth-anything',
    name: 'Depth Anything',
    developer: 'ByteDance и Гонконгский университет', country: 'Китай',
    modality: ['vision'],
    first: '2024-01', latest: '2025-12',
    sizes: '25M – 1.4B',
    license: 'Малые версии — Apache 2.0; крупные (Large/Giant) часто CC-BY-NC, только некоммерческое использование',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Определяет глубину — расстояние до каждой точки — по одной обычной фотографии или видео. DA3 восстанавливает геометрию сцены с нескольких кадров.',
    tasks: ['Оценка расстояний и объёмов по камере', 'Эффекты глубины для фото и видео', 'Навигация роботов и дронов'],
    where: ['Робототехника', 'Строительство и недвижимость', 'Видеопродакшн'],
    versions: [['Depth Anything', '2024-01'], ['Depth Anything V2', '2024-06'], ['Video Depth Anything', '2025-01'], ['Depth Anything 3', '2025-11'], ['DA3 1.1', '2025-12']],
    hf: 'https://huggingface.co/depth-anything/DA3-LARGE-1.1',
    github: 'https://github.com/ByteDance-Seed/Depth-Anything-3',
    alternatives: ['moge', 'dino'],
    source: 'https://huggingface.co/depth-anything/DA3-LARGE-1.1',
    verified: true,
  },
  {
    id: 'moge',
    name: 'MoGe',
    developer: 'Microsoft Research', country: 'США',
    modality: ['vision', '3d'],
    first: '2024-10', latest: '2026-08',
    sizes: 'ViT-S – ViT-G',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Восстанавливает 3D-геометрию сцены по одной фотографии: глубину в метрах, облако точек и нормали поверхностей.',
    tasks: ['Замеры помещений и объектов по фото', '3D-облако точек из снимка', 'Подготовка данных для роботов и AR'],
    where: ['Строительство и ремонт', 'Робототехника', 'AR и дизайн интерьера'],
    versions: [['MoGe', '2024-10'], ['MoGe-2', '2025-07'], ['MoGe-3', '2026-08']],
    hf: 'https://huggingface.co/Ruicheng/moge-3-vitl',
    github: 'https://github.com/microsoft/MoGe',
    alternatives: ['depth-anything'],
    source: 'https://huggingface.co/Ruicheng/moge-3-vitg',
    verified: true,
  },
  {
    id: 'clip-siglip',
    name: 'SigLIP (наследник CLIP)',
    developer: 'Google', country: 'США',
    modality: ['vision', 'embed'],
    first: '2023-09', latest: '2025-02',
    sizes: 'около 0.2B – 2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модели, которые переводят картинки и текст в общее пространство: можно искать фото по словам и классифицировать изображения без обучения. CLIP от OpenAI (2021) — предшественник.',
    tasks: ['Поиск картинок по текстовому запросу', 'Автоматическая разметка и теги каталога', 'Фильтрация недопустимого контента'],
    where: ['Маркетплейсы и ритейл', 'Медиа и фотобанки', 'Модерация контента'],
    versions: [['SigLIP', '2023-09'], ['SigLIP 2', '2025-02']],
    hf: 'https://huggingface.co/google/siglip2-so400m-patch14-384',
    github: 'https://github.com/google-research/big_vision',
    alternatives: ['dino', 'jina-embeddings'],
    source: 'https://huggingface.co/google/siglip2-giant-opt-patch16-384',
    verified: true,
  },

  // ---------- Поиск и RAG ----------
  {
    id: 'e5',
    name: 'E5 / multilingual-e5',
    developer: 'Microsoft', country: 'США',
    modality: ['embed'],
    first: '2022-12', latest: '2024-02',
    sizes: '33M – 7B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Проверенные модели для смыслового поиска. Многоязычные версии хорошо работают с русским и до сих пор служат надёжной основой для RAG.',
    tasks: ['Поиск по базе знаний и документам', 'Подбор ответов для чат-бота (RAG)', 'Поиск похожих обращений и дублей'],
    where: ['Поддержка клиентов', 'Юристы и документооборот', 'Внутренние базы знаний'],
    versions: [['E5', '2022-12'], ['E5 v2', '2023-05'], ['multilingual-e5', '2023-06'], ['e5-mistral-7b-instruct', '2023-12'], ['multilingual-e5-large-instruct', '2024-02']],
    hf: 'https://huggingface.co/intfloat/multilingual-e5-large-instruct',
    github: 'https://github.com/microsoft/unilm/tree/master/e5',
    alternatives: ['bge-m3', 'gte', 'giga-embeddings'],
    source: 'https://huggingface.co/intfloat/multilingual-e5-large-instruct',
    verified: true,
  },
  {
    id: 'gte',
    name: 'GTE',
    developer: 'Alibaba', country: 'Китай',
    modality: ['embed'],
    first: '2023-07', latest: '2025-01',
    sizes: '33M – 7B',
    license: 'Apache 2.0 (первые версии — MIT)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Эмбеддинги и реранкеры Alibaba для поиска: от крошечных до 7B на базе Qwen2. Есть многоязычная версия mGTE с длинным контекстом.',
    tasks: ['Смысловой поиск по документам', 'Переранжирование результатов поиска', 'Кластеризация и классификация текстов'],
    where: ['Поддержка клиентов', 'Онлайн-торговля (поиск по каталогу)', 'Базы знаний'],
    versions: [['GTE', '2023-07'], ['GTE v1.5', '2024-04'], ['gte-Qwen2', '2024-06'], ['mGTE (многоязычная)', '2024-07'], ['gte-modernbert и реранкер', '2025-01']],
    hf: 'https://huggingface.co/Alibaba-NLP/gte-multilingual-base',
    github: null,
    alternatives: ['bge-m3', 'e5', 'qwen-embedding'],
    source: 'https://huggingface.co/Alibaba-NLP/gte-modernbert-base',
    verified: true,
  },
  {
    id: 'nomic-embed',
    name: 'Nomic Embed',
    developer: 'Nomic AI', country: 'США',
    modality: ['embed'],
    first: '2024-01', latest: '2025-03',
    sizes: '137M – 7B',
    license: 'Apache 2.0 (у части мультимодальных версий условия базовой модели)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Полностью открытые эмбеддинги — с весами, данными и кодом обучения. v2 многоязычная на MoE, есть версии для кода и для поиска по PDF-страницам.',
    tasks: ['Поиск по документам и базе знаний', 'Поиск по коду', 'Поиск по сканам и PDF без распознавания'],
    where: ['IT-отделы', 'Поддержка клиентов', 'Документооборот'],
    versions: [['nomic-embed-text v1', '2024-01'], ['v1.5', '2024-02'], ['nomic-embed-vision', '2024-06'], ['nomic-embed-text v2 (MoE)', '2025-02'], ['nomic-embed-code и multimodal', '2025-03']],
    hf: 'https://huggingface.co/nomic-ai/nomic-embed-text-v2-moe',
    github: 'https://github.com/nomic-ai/contrastors',
    alternatives: ['bge-m3', 'gte', 'jina-embeddings'],
    source: 'https://huggingface.co/nomic-ai/nomic-embed-code',
    verified: true,
  },
  {
    id: 'jina-embeddings',
    name: 'Jina Embeddings',
    developer: 'Jina AI', country: 'Германия',
    modality: ['embed'],
    first: '2023-09', latest: '2026-05',
    sizes: '33M – 3.8B',
    license: 'v2 — Apache 2.0; v3 и v5 — CC-BY-NC (только некоммерческое, для бизнеса нужна платная лицензия); v4 — Qwen Research License',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Сильные многоязычные эмбеддинги с длинным контекстом, v5-omni понимает текст, картинки и аудио. Свежие версии открыты только для некоммерческого использования.',
    tasks: ['Поиск по документам на многих языках', 'Поиск по картинкам и сканам', 'Классификация и кластеризация'],
    where: ['Базы знаний', 'Медиа', 'Онлайн-торговля'],
    versions: [['v2', '2023-09'], ['v3', '2024-09'], ['v4', '2025-06'], ['v5-text', '2026-02'], ['v5-omni', '2026-05']],
    hf: 'https://huggingface.co/jinaai/jina-embeddings-v5-omni-small',
    github: null,
    alternatives: ['bge-m3', 'qwen-embedding', 'nomic-embed'],
    source: 'https://huggingface.co/jinaai/jina-embeddings-v5-omni-small',
    verified: true,
  },
  {
    id: 'qwen-embedding',
    name: 'Qwen3 Embedding / Reranker',
    developer: 'Alibaba (Qwen)', country: 'Китай',
    modality: ['embed'],
    first: '2025-06', latest: '2026-01',
    sizes: '0.6B – 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Эмбеддинги и реранкеры на базе Qwen3, в числе лучших открытых для многоязычного поиска, включая русский. VL-версии ищут по картинкам, скриншотам и видео.',
    tasks: ['Поиск по базе знаний для RAG', 'Переранжирование найденного перед ответом', 'Поиск по сканам, слайдам и скриншотам'],
    where: ['Поддержка клиентов', 'Юристы и документооборот', 'Онлайн-торговля'],
    versions: [['Qwen3-Embedding и Reranker', '2025-06'], ['Qwen3-VL-Embedding и VL-Reranker', '2026-01']],
    hf: 'https://huggingface.co/Qwen/Qwen3-Embedding-8B',
    github: 'https://github.com/QwenLM/Qwen3-Embedding',
    alternatives: ['bge-m3', 'gte', 'giga-embeddings'],
    source: 'https://huggingface.co/Qwen/Qwen3-VL-Embedding-8B',
    verified: true,
  },
  {
    id: 'nemotron-embed',
    name: 'NVIDIA Nemotron Embed',
    developer: 'NVIDIA', country: 'США',
    modality: ['embed'],
    first: '2025-10', latest: '2026-07',
    sizes: '1B – 8B',
    license: 'Nemotron-3-Embed — OpenMDW 1.1; llama-nemotron-embed-1b-v2 — NVIDIA Open Model License; llama-embed-nemotron-8b — только некоммерческое',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Эмбеддинги NVIDIA для поиска и RAG. Nemotron-3-Embed 2026 года вышли под свободной лицензией OpenMDW и работают на многих языках.',
    tasks: ['Поиск по корпоративным документам', 'RAG для чат-ботов и ассистентов', 'Поиск по картинкам и страницам (VL-версии)'],
    where: ['Крупные компании', 'Поддержка клиентов', 'Документооборот'],
    versions: [['llama-embed-nemotron-8b', '2025-10'], ['llama-nemotron-embed-1b-v2', '2025-10'], ['llama-nemotron-embed-vl-1b-v2', '2025-12'], ['Nemotron-3-Embed', '2026-07']],
    hf: 'https://huggingface.co/nvidia/Nemotron-3-Embed-8B-BF16',
    github: null,
    alternatives: ['qwen-embedding', 'bge-m3'],
    source: 'https://huggingface.co/nvidia/Nemotron-3-Embed-1B-BF16',
    verified: true,
  },
  {
    id: 'giga-embeddings',
    name: 'FRIDA / Giga-Embeddings',
    developer: 'Сбер (SberDevices)', country: 'Россия',
    modality: ['embed'],
    first: '2024-12', latest: '2026-08',
    sizes: '480M – 10B-A1.8B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Эмбеддинги Сбера, заточенные под русский язык: по данным разработчиков, в числе лучших на русскоязычных тестах поиска. FRIDA компактная, Giga-Embeddings мощнее.',
    tasks: ['Поиск по русскоязычным документам', 'RAG для чат-ботов на русском', 'Классификация обращений и отзывов'],
    where: ['Банки и финансы', 'Госсектор и юристы', 'Поддержка клиентов'],
    versions: [['FRIDA', '2024-12'], ['Giga-Embeddings-instruct', '2024-12'], ['Giga-Embeddings-instruct 0826 (3B)', '2026-07'], ['Giga-Embeddings-instruct 0826 (480M, 10B-A1.8B)', '2026-08']],
    hf: 'https://huggingface.co/ai-sage/Giga-Embeddings-instruct-3B-0826',
    github: null,
    alternatives: ['bge-m3', 'e5', 'qwen-embedding'],
    source: 'https://huggingface.co/ai-sage/Giga-Embeddings-instruct-480M-0826',
    verified: true,
  },
  {
    id: 'embeddinggemma',
    name: 'EmbeddingGemma',
    developer: 'Google', country: 'США',
    modality: ['embed'],
    first: '2025-09', latest: '2025-09',
    sizes: '300M',
    license: 'Gemma Terms of Use (собственная лицензия Google, коммерция разрешена с правилами использования)',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Маленькая многоязычная модель эмбеддингов на базе Gemma 3, работает даже на телефоне и ноутбуке без интернета.',
    tasks: ['Поиск по документам на устройстве', 'RAG без отправки данных наружу', 'Классификация текстов'],
    where: ['Мобильные приложения', 'Работа с чувствительными данными', 'Малый бизнес'],
    versions: [['EmbeddingGemma 300M', '2025-09']],
    hf: 'https://huggingface.co/google/embeddinggemma-300m',
    github: null,
    alternatives: ['gemma', 'e5', 'granite-embedding'],
    source: 'https://huggingface.co/google/embeddinggemma-300m',
    verified: true,
  },
  {
    id: 'pplx-embed',
    name: 'pplx-embed',
    developer: 'Perplexity', country: 'США',
    modality: ['embed'],
    first: '2026-02', latest: '2026-03',
    sizes: '0.6B – 4B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Эмбеддинги поискового сервиса Perplexity. Есть версии, которые учитывают контекст всего документа, а не только отдельного фрагмента.',
    tasks: ['Поиск по большим массивам документов', 'RAG с учётом контекста документа', 'Поиск по сайту и каталогу'],
    where: ['Медиа и издательства', 'Базы знаний', 'Онлайн-сервисы'],
    versions: [['pplx-embed v1 и context-v1', '2026-02'], ['pplx-embed-v1-late-0.6b', '2026-03']],
    hf: 'https://huggingface.co/perplexity-ai/pplx-embed-v1-4b',
    github: null,
    alternatives: ['qwen-embedding', 'voyage-4-nano'],
    source: 'https://huggingface.co/perplexity-ai/pplx-embed-v1-late-0.6b',
    verified: true,
  },
  {
    id: 'voyage-4-nano',
    name: 'Voyage 4 nano',
    developer: 'Voyage AI (MongoDB)', country: 'США',
    modality: ['embed'],
    first: '2026-01', latest: '2026-01',
    sizes: 'около 340M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Единственная открытая модель линейки Voyage 4: её векторы совместимы с платными старшими версиями, можно начать локально и позже перейти на API.',
    tasks: ['Поиск по документам на своём сервере', 'RAG для небольших баз знаний', 'Поиск похожих текстов'],
    where: ['Малый и средний бизнес', 'Базы знаний', 'Поддержка клиентов'],
    versions: [['voyage-4-nano', '2026-01']],
    hf: 'https://huggingface.co/voyageai/voyage-4-nano',
    github: null,
    alternatives: ['pplx-embed', 'granite-embedding'],
    source: 'https://huggingface.co/voyageai/voyage-4-nano',
    verified: true,
  },
  {
    id: 'granite-embedding',
    name: 'Granite Embedding',
    developer: 'IBM', country: 'США',
    modality: ['embed'],
    first: '2024-12', latest: '2026-04',
    sizes: '30M – 311M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Лёгкие эмбеддинги IBM для корпоративного поиска, обученные на данных с понятными правами. R2 2026 года стали многоязычными.',
    tasks: ['Поиск по корпоративным документам', 'RAG на обычном сервере без видеокарты', 'Переранжирование результатов'],
    where: ['Крупные компании', 'Финансы и страхование', 'Базы знаний'],
    versions: [['Granite Embedding', '2024-12'], ['Granite Embedding R2 (английский)', '2025-07'], ['R2 реранкер', '2025-08'], ['R2 многоязычная', '2026-04']],
    hf: 'https://huggingface.co/ibm-granite/granite-embedding-311m-multilingual-r2',
    github: 'https://github.com/ibm-granite/granite-embedding-models',
    alternatives: ['granite', 'e5', 'bge-m3'],
    source: 'https://huggingface.co/ibm-granite/granite-embedding-311m-multilingual-r2',
    verified: true,
  },

  // ---------- Прогнозы ----------
  {
    id: 'timesfm',
    name: 'TimesFM',
    developer: 'Google', country: 'США',
    modality: ['timeseries'],
    first: '2024-05', latest: '2026-08',
    sizes: '200M – 500M',
    license: 'Версии 1.0–2.5 — Apache 2.0; TimesFM 3.0 — некоммерческая лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Готовая модель прогнозов Google: строит прогноз по любому временному ряду без обучения на ваших данных.',
    tasks: ['Прогноз продаж и спроса', 'Планирование закупок и запасов', 'Прогноз нагрузки и трафика'],
    where: ['Ритейл', 'Логистика и склады', 'Энергетика'],
    versions: [['TimesFM 1.0', '2024-05'], ['TimesFM 2.0', '2024-12'], ['TimesFM 2.5', '2025-09'], ['TimesFM 3.0', '2026-08']],
    hf: 'https://huggingface.co/google/timesfm-2.5-200m-pytorch',
    github: 'https://github.com/google-research/timesfm',
    alternatives: ['chronos', 'toto', 'tirex'],
    source: 'https://huggingface.co/google/timesfm-3.0-pytorch',
    verified: true,
  },
  {
    id: 'chronos',
    name: 'Chronos',
    developer: 'Amazon', country: 'США',
    modality: ['timeseries'],
    first: '2024-03', latest: '2025-10',
    sizes: '8M – 710M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Модели прогнозов Amazon, одни из самых скачиваемых. Chronos-2 учитывает внешние факторы: цены, акции, погоду.',
    tasks: ['Прогноз спроса с учётом акций и цен', 'Планирование запасов', 'Прогноз выручки и потоков клиентов'],
    where: ['Ритейл и онлайн-торговля', 'Производство', 'Финансы'],
    versions: [['Chronos (T5)', '2024-03'], ['Chronos-Bolt', '2024-11'], ['Chronos-2', '2025-10']],
    hf: 'https://huggingface.co/amazon/chronos-2',
    github: 'https://github.com/amazon-science/chronos-forecasting',
    alternatives: ['timesfm', 'toto', 'tirex'],
    source: 'https://huggingface.co/amazon/chronos-2',
    verified: true,
  },
  {
    id: 'moirai',
    name: 'Moirai',
    developer: 'Salesforce', country: 'США',
    modality: ['timeseries'],
    first: '2024-03', latest: '2025-08',
    sizes: '11M – 311M',
    license: 'CC-BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min'],
    summary: 'Универсальная модель прогнозов Salesforce для рядов с разной частотой и многими переменными. Веса открыты только для исследований.',
    tasks: ['Исследовательские пилоты прогнозов', 'Сравнение с другими моделями прогнозов', 'Прогнозы по многим связанным рядам'],
    where: ['Аналитика и исследования', 'Ритейл', 'Энергетика'],
    versions: [['Moirai 1.0', '2024-03'], ['Moirai 1.1', '2024-06'], ['Moirai-MoE', '2024-11'], ['Moirai 2.0', '2025-08']],
    hf: 'https://huggingface.co/Salesforce/moirai-2.0-R-small',
    github: 'https://github.com/SalesforceAIResearch/uni2ts',
    alternatives: ['chronos', 'timesfm'],
    source: 'https://huggingface.co/Salesforce/moirai-2.0-R-small',
    verified: true,
  },
  {
    id: 'lag-llama',
    name: 'Lag-Llama',
    developer: 'ServiceNow, Mila и партнёры', country: 'Канада',
    modality: ['timeseries'],
    first: '2024-02', latest: '2024-02',
    sizes: '2.4M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Одна из первых открытых моделей прогнозов «из коробки». Крошечная, даёт вероятностный прогноз, сейчас уступает Chronos и TimesFM.',
    tasks: ['Вероятностный прогноз продаж', 'Быстрые пилоты прогнозирования', 'Базовая модель для сравнения'],
    where: ['Аналитика', 'Ритейл', 'Финансы'],
    versions: [['Lag-Llama', '2024-02']],
    hf: 'https://huggingface.co/time-series-foundation-models/Lag-Llama',
    github: 'https://github.com/time-series-foundation-models/lag-llama',
    alternatives: ['chronos', 'timesfm'],
    source: 'https://huggingface.co/time-series-foundation-models/Lag-Llama',
    verified: true,
  },
  {
    id: 'toto',
    name: 'Toto',
    developer: 'Datadog', country: 'США',
    modality: ['timeseries'],
    first: '2025-05', latest: '2026-04',
    sizes: '4M – 2.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модель прогнозов от Datadog, обученная на метриках серверов и приложений. Особенно сильна для IT-мониторинга: нагрузка, задержки, ошибки.',
    tasks: ['Прогноз нагрузки на серверы', 'Поиск аномалий в метриках', 'Планирование мощностей'],
    where: ['IT и DevOps', 'Онлайн-сервисы', 'Телеком'],
    versions: [['Toto 1.0', '2025-05'], ['Toto 2.0', '2026-04']],
    hf: 'https://huggingface.co/Datadog/Toto-2.0-2.5B',
    github: 'https://github.com/DataDog/toto',
    alternatives: ['chronos', 'timesfm', 'tirex'],
    source: 'https://huggingface.co/Datadog/Toto-2.0-2.5B',
    verified: true,
  },
  {
    id: 'tirex',
    name: 'TiRex',
    developer: 'NXAI', country: 'Австрия',
    modality: ['timeseries'],
    first: '2025-05', latest: '2026-06',
    sizes: 'около 35M – 82M',
    license: 'TiRex-2 — Apache 2.0; первая версия — NXAI Community License',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Компактная модель прогнозов на архитектуре xLSTM, лидер открытых тестов при малом размере. Быстро работает на обычном процессоре.',
    tasks: ['Прогноз спроса и продаж', 'Прогноз потребления энергии', 'Прогнозы на слабом железе и на месте'],
    where: ['Производство', 'Энергетика', 'Ритейл'],
    versions: [['TiRex', '2025-05'], ['TiRex 1.1', '2025-10'], ['TiRex-2', '2026-06']],
    hf: 'https://huggingface.co/NX-AI/TiRex-2',
    github: 'https://github.com/NX-AI/tirex',
    alternatives: ['chronos', 'timesfm', 'toto'],
    source: 'https://huggingface.co/NX-AI/TiRex-2',
    verified: true,
  },

  // ---------- Роботы ----------
  {
    id: 'openvla',
    name: 'OpenVLA',
    developer: 'Стэнфорд, Беркли и партнёры', country: 'США',
    modality: ['robotics'],
    first: '2024-06', latest: '2025-02',
    sizes: '7B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Первая крупная открытая модель «зрение-язык-действие»: робот-манипулятор выполняет команды вроде «положи яблоко в миску». OFT ускоряет её в разы.',
    tasks: ['Управление манипулятором по текстовой команде', 'Пилоты по роботизации простых операций', 'Основа для дообучения под свой робот'],
    where: ['Производство', 'Склады и логистика', 'Исследовательские лаборатории'],
    versions: [['OpenVLA', '2024-06'], ['OpenVLA-OFT', '2025-02']],
    hf: 'https://huggingface.co/openvla/openvla-7b',
    github: 'https://github.com/openvla/openvla',
    alternatives: ['openpi', 'smolvla'],
    source: 'https://huggingface.co/moojink/openvla-7b-oft-finetuned-libero-spatial',
    verified: true,
  },
  {
    id: 'openpi',
    name: 'π0 / π0.5 (openpi)',
    developer: 'Physical Intelligence', country: 'США',
    modality: ['robotics'],
    first: '2025-02', latest: '2025-09',
    sizes: 'около 3B',
    license: 'Код и веса выложены под Apache 2.0, но модель построена на PaliGemma от Google — копии в LeRobot помечены условиями Gemma',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Модели управления роботами от Physical Intelligence: складывание белья, уборка, работа с предметами. π0.5 лучше справляется в незнакомой обстановке.',
    tasks: ['Управление манипуляторами и двуруким роботом', 'Дообучение под свои операции', 'Пилоты по автоматизации ручного труда'],
    where: ['Производство', 'Склады', 'Сервисная робототехника'],
    versions: [['π0 и π0-FAST', '2025-02'], ['π0.5', '2025-09']],
    hf: 'https://huggingface.co/lerobot/pi05_base',
    github: 'https://github.com/Physical-Intelligence/openpi',
    alternatives: ['gr00t', 'openvla', 'smolvla'],
    source: 'https://github.com/Physical-Intelligence/openpi',
    verified: true,
  },
  {
    id: 'gr00t',
    name: 'NVIDIA Isaac GR00T',
    developer: 'NVIDIA', country: 'США',
    modality: ['robotics'],
    first: '2025-03', latest: '2026-03',
    sizes: '2B – 3B',
    license: 'NVIDIA Open Model License (коммерция разрешена на условиях NVIDIA)',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Базовая модель NVIDIA для человекоподобных роботов и манипуляторов: видит, понимает команду и выдаёт движения. Встроена в экосистему Isaac.',
    tasks: ['Управление человекоподобными роботами', 'Дообучение под свою роботизированную ячейку', 'Обучение в симуляции с переносом на реального робота'],
    where: ['Производство', 'Склады и логистика', 'Робототехнические стартапы'],
    versions: [['GR00T N1', '2025-03'], ['GR00T N1.5', '2025-06'], ['GR00T N1.6', '2025-12'], ['GR00T N1.7', '2026-03']],
    hf: 'https://huggingface.co/nvidia/GR00T-N1.7-3B',
    github: 'https://github.com/NVIDIA/Isaac-GR00T',
    alternatives: ['openpi', 'cosmos', 'lingbot-vla'],
    source: 'https://huggingface.co/nvidia/GR00T-N1.7-3B',
    verified: true,
  },
  {
    id: 'cosmos',
    name: 'NVIDIA Cosmos',
    developer: 'NVIDIA', country: 'США',
    modality: ['robotics', 'video'],
    first: '2025-01', latest: '2026-07',
    sizes: '2B – 65B',
    license: 'Cosmos 3 — OpenMDW 1.1 (свободная, коммерция разрешена); ранние версии — NVIDIA Open Model License, коммерция тоже разрешена',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    summary: 'Модели «мира» для роботов и беспилотников: генерируют реалистичное видео физических сцен и предсказывают действия. Cosmos 3 объединяет понимание, генерацию и управление.',
    tasks: ['Синтетические видео для обучения роботов и беспилотников', 'Проверка сценариев в симуляции', 'Управление роботом (Policy-версии)'],
    where: ['Робототехника', 'Беспилотный транспорт', 'Производство и склады'],
    versions: [['Cosmos 1.0', '2025-01'], ['Cosmos-Predict2', '2025-06'], ['Cosmos-Predict2.5', '2025-10'], ['Cosmos 3 (Nano, Super)', '2026-06'], ['Cosmos 3 Edge', '2026-07']],
    hf: 'https://huggingface.co/nvidia/Cosmos3-Nano',
    github: 'https://github.com/nvidia-cosmos',
    alternatives: ['gr00t', 'wan', 'hy-world'],
    source: 'https://nvidianews.nvidia.com/news/nvidia-launches-cosmos-3-the-open-frontier-foundation-model-for-physical-ai',
    verified: true,
  },
  {
    id: 'smolvla',
    name: 'SmolVLA',
    developer: 'Hugging Face', country: 'США',
    modality: ['robotics'],
    first: '2025-06', latest: '2025-06',
    sizes: '450M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Маленькая модель управления роботом, которая работает на обычном ноутбуке. Обучена на открытых данных сообщества LeRobot, подходит для недорогих манипуляторов.',
    tasks: ['Управление недорогим манипулятором', 'Быстрые пилоты и демо роботизации', 'Обучение персонала и студентов'],
    where: ['Малое производство', 'Образование', 'Робототехнические стартапы'],
    versions: [['SmolVLA', '2025-06']],
    hf: 'https://huggingface.co/lerobot/smolvla_base',
    github: 'https://github.com/huggingface/lerobot',
    alternatives: ['openvla', 'openpi'],
    source: 'https://huggingface.co/lerobot/smolvla_base',
    verified: true,
  },
  {
    id: 'molmoact',
    name: 'MolmoAct',
    developer: 'Ai2 (Allen Institute for AI)', country: 'США',
    modality: ['robotics'],
    first: '2025-08', latest: '2026-05',
    sizes: '5B – 8B',
    license: 'Apache 2.0 (код и первая версия; у базового чекпойнта MolmoAct2 лицензия на карточке не указана)',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Полностью открытая модель управления роботом, которая сначала «рассуждает» о пространстве и траектории, а потом действует. Ход рассуждений можно проверить.',
    tasks: ['Управление манипулятором с объяснимыми шагами', 'Дообучение под свой робот', 'Исследовательские пилоты'],
    where: ['Производство', 'Исследовательские лаборатории', 'Склады'],
    versions: [['MolmoAct', '2025-08'], ['MolmoAct 2', '2026-05']],
    hf: 'https://huggingface.co/allenai/MolmoAct2',
    github: 'https://github.com/allenai/molmoact2',
    alternatives: ['openvla', 'openpi', 'molmo'],
    source: 'https://huggingface.co/allenai/MolmoAct2',
    verified: true,
  },
  {
    id: 'lingbot-vla',
    name: 'LingBot-VLA',
    developer: 'Ant Group (Robbyant)', country: 'Китай',
    modality: ['robotics'],
    first: '2026-01', latest: '2026-07',
    sizes: '4B – 6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Модель управления роботами от Ant Group, обученная на большом объёме данных с реальных роботов. Версия 2.0 работает с разными типами манипуляторов.',
    tasks: ['Управление двуруким манипулятором', 'Дообучение под свою операцию', 'Пилоты сборки и сортировки'],
    where: ['Производство', 'Склады и логистика', 'Робототехнические стартапы'],
    versions: [['LingBot-VLA (4B)', '2026-01'], ['LingBot-VLA 2.0 (6B)', '2026-07']],
    hf: 'https://huggingface.co/robbyant/lingbot-vla-v2-6b',
    github: null,
    alternatives: ['gr00t', 'openpi', 'xiaomi-robotics'],
    source: 'https://huggingface.co/robbyant/lingbot-vla-v2-6b',
    verified: true,
  },
  {
    id: 'xiaomi-robotics',
    name: 'Xiaomi Robotics',
    developer: 'Xiaomi', country: 'Китай',
    modality: ['robotics'],
    first: '2026-02', latest: '2026-07',
    sizes: '4B – 5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Открытые модели управления роботами от Xiaomi. Robotics-1 рассчитана на бытовые и кухонные задачи, U0 объединяет понимание сцены и действия.',
    tasks: ['Управление манипулятором по команде', 'Бытовые и сервисные сценарии', 'Основа для дообучения'],
    where: ['Сервисная робототехника', 'Производство', 'Исследования'],
    versions: [['Xiaomi-Robotics-0', '2026-02'], ['Xiaomi-Robotics-1', '2026-07'], ['Xiaomi-Robotics-U0', '2026-07']],
    hf: 'https://huggingface.co/XiaomiRobotics/Xiaomi-Robotics-0-Pretrain',
    github: null,
    alternatives: ['lingbot-vla', 'openpi', 'gr00t'],
    source: 'https://huggingface.co/XiaomiRobotics/Xiaomi-Robotics-1-5B',
    verified: true,
  },
  {
    id: 'gigabrain',
    name: 'GigaBrain',
    developer: 'GigaAI', country: 'Китай',
    modality: ['robotics'],
    first: '2025-11', latest: '2026-08',
    sizes: '3.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Модель управления роботами, обученная в основном на синтетических данных из модели мира. Позволяет меньше тратить на сбор данных с реальных роботов.',
    tasks: ['Управление манипулятором', 'Дообучение на малом объёме своих данных', 'Пилоты сортировки и сборки'],
    where: ['Производство', 'Склады', 'Робототехнические стартапы'],
    versions: [['GigaBrain-0', '2025-11'], ['GigaBrain-0.1', '2026-02'], ['GigaBrain-0.7', '2026-08']],
    hf: 'https://huggingface.co/open-gigaai/GigaBrain-0.7-3.5B-Base',
    github: null,
    alternatives: ['openpi', 'lingbot-vla', 'cosmos'],
    source: 'https://huggingface.co/open-gigaai/GigaBrain-0.7-3.5B-Base',
    verified: true,
  },
];
