// Речь и звук: распознавание (asr), синтез (tts), голосовые ассистенты и перевод (omni), музыка и звуки (audio).
// Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- Распознавание речи (asr) ----------
  {
    id: 'parakeet',
    name: 'NVIDIA Parakeet / Canary / Nemotron Speech',
    developer: 'NVIDIA', country: 'США',
    modality: ['asr'],
    first: '2023-12', latest: '2026-05',
    sizes: '110M – 2.5B',
    license: 'Смешанная: Parakeet и Canary в основном CC-BY-4.0 (Canary-1B первой версии некоммерческая), Parakeet Unified и Nemotron Speech Streaming под NVIDIA Open Model License, Nemotron 3.5 ASR под OpenMDW',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Быстрые модели распознавания речи от NVIDIA, в том числе потоковые для работы в реальном времени. Parakeet TDT v3 и Nemotron 3.5 ASR понимают русский.',
    tasks: ['Расшифровка звонков и совещаний', 'Субтитры к видео', 'Голосовой ввод в реальном времени', 'Разметка аудиоархивов'],
    where: ['Колл-центры', 'Медиа', 'Голосовые боты', 'Внутренние сервисы компаний'],
    versions: [
      ['Parakeet CTC 0.6B', '2023-12'],
      ['Canary-1B', '2024-02'],
      ['Parakeet TDT 0.6B v2', '2025-04'],
      ['Canary-Qwen-2.5B', '2025-06'],
      ['Parakeet TDT 0.6B v3 и Canary-1B v2', '2025-08'],
      ['Nemotron Speech Streaming 0.6B', '2025-12'],
      ['Parakeet Unified 0.6B', '2026-04'],
      ['Nemotron 3.5 ASR Streaming 0.6B', '2026-05'],
    ],
    hf: 'https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3',
    github: 'https://github.com/NVIDIA-NeMo/Speech',
    alternatives: ['whisper', 'gigaam', 'qwen-asr'],
    source: 'https://huggingface.co/nvidia/nemotron-3.5-asr-streaming-0.6b',
    verified: true,
  },
  {
    id: 'gigaam',
    name: 'GigaAM',
    developer: 'Сбер', country: 'Россия',
    modality: ['asr'],
    first: '2024-04', latest: '2026-07',
    sizes: '220M – 600M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Модели Сбера для распознавания русской речи, одни из самых точных для русского языка. Есть распознавание эмоций, версия v3 с пунктуацией и многоязычная версия (русский, казахский, киргизский, узбекский).',
    tasks: ['Расшифровка звонков на русском', 'Протоколы совещаний', 'Голосовое управление сервисами', 'Анализ эмоций в разговоре'],
    where: ['Колл-центры', 'Банки и страхование', 'Госсектор', 'Ритейл'],
    versions: [
      ['GigaAM (CTC, Emo)', '2024-04'],
      ['GigaAM-RNNT', '2024-05'],
      ['GigaAM-v2', '2024-12'],
      ['GigaAM-v3 и v3-e2e', '2025-11'],
      ['GigaAM Multilingual', '2026-07'],
    ],
    hf: 'https://huggingface.co/ai-sage/GigaAM-v3',
    github: 'https://github.com/salute-developers/GigaAM',
    alternatives: ['t-one', 'whisper', 'parakeet'],
    source: 'https://huggingface.co/ai-sage/GigaAM-Multilingual',
    verified: true,
  },
  {
    id: 't-one',
    name: 'T-one',
    developer: 'Т-Банк', country: 'Россия',
    modality: ['asr'],
    first: '2025-07', latest: '2025-07',
    sizes: '72M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Компактная потоковая модель Т-Банка для распознавания русской речи в телефонных разговорах. Работает в реальном времени даже без видеокарты.',
    tasks: ['Расшифровка телефонных звонков', 'Голосовые роботы на линии', 'Контроль качества разговоров', 'Поиск по записям звонков'],
    where: ['Колл-центры', 'Банки', 'Службы доставки', 'Телеком'],
    versions: [['T-one', '2025-07']],
    hf: 'https://huggingface.co/t-tech/T-one',
    github: 'https://github.com/voicekit-team/T-one',
    alternatives: ['gigaam', 'parakeet'],
    source: 'https://huggingface.co/t-tech/T-one',
    verified: true,
  },
  {
    id: 'moonshine',
    name: 'Moonshine',
    developer: 'Moonshine AI (Useful Sensors)', country: 'США',
    modality: ['asr'],
    first: '2024-10', latest: '2026-08',
    sizes: '27M – 245M',
    license: 'MIT; исключение — старые непотоковые модели для языков кроме английского (некоммерческая Moonshine Community License)',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Очень маленькие и быстрые модели распознавания речи для телефонов, планшетов и встраиваемых устройств. Вторая версия работает потоково и выдаёт текст, пока человек ещё говорит.',
    tasks: ['Голосовое управление устройствами', 'Распознавание на телефоне без интернета', 'Живые субтитры', 'Голосовые интерфейсы в приложениях'],
    where: ['Производители устройств', 'Мобильные приложения', 'Умный дом', 'Киоски и терминалы'],
    versions: [
      ['Moonshine Tiny / Base', '2024-10'],
      ['Moonshine v2 (потоковая)', '2026-02'],
      ['Потоковые модели для других языков', '2026-08'],
    ],
    hf: 'https://huggingface.co/moonshine-ai/moonshine-streaming-medium',
    github: 'https://github.com/moonshine-ai/moonshine',
    alternatives: ['whisper', 'parakeet'],
    source: 'https://arxiv.org/abs/2602.12241',
    verified: true,
  },
  {
    id: 'voxtral',
    name: 'Voxtral',
    developer: 'Mistral AI', country: 'Франция',
    modality: ['asr', 'tts'],
    first: '2025-07', latest: '2026-03',
    sizes: '3B – 24B',
    license: 'Модели распознавания (Mini 3B, Small 24B, Mini 4B Realtime) — Apache 2.0; Voxtral-4B-TTS — CC BY-NC 4.0, только некоммерческое',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Речевые модели Mistral: понимают аудио, расшифровывают и отвечают на вопросы по записи. Realtime-версия распознаёт в реальном времени и поддерживает русский; есть синтез речи.',
    tasks: ['Расшифровка и краткое содержание записей', 'Вопросы к аудио', 'Распознавание в реальном времени', 'Озвучка текстов (некоммерческая)'],
    where: ['Колл-центры', 'Медиа', 'Юристы и консалтинг', 'Голосовые ассистенты'],
    versions: [
      ['Voxtral Mini 3B и Small 24B', '2025-07'],
      ['Voxtral Mini 4B Realtime', '2026-02'],
      ['Voxtral 4B TTS', '2026-03'],
    ],
    hf: 'https://huggingface.co/mistralai/Voxtral-Mini-4B-Realtime-2602',
    github: null,
    alternatives: ['whisper', 'qwen-asr', 'mistral'],
    source: 'https://huggingface.co/mistralai/Voxtral-4B-TTS-2603',
    verified: true,
  },
  {
    id: 'qwen-asr',
    name: 'Qwen3-ASR',
    developer: 'Alibaba (Qwen)', country: 'Китай',
    modality: ['asr'],
    first: '2026-01', latest: '2026-06',
    sizes: '0.6B – 1.7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Модели распознавания речи от команды Qwen на 50+ языков, включая русский. Хорошо справляются с шумом, пением и акцентами.',
    tasks: ['Расшифровка звонков и встреч', 'Субтитры к видео', 'Распознавание на нескольких языках', 'Голосовой ввод в приложениях'],
    where: ['Колл-центры', 'Медиа и онлайн-обучение', 'Международные компании', 'Голосовые боты'],
    versions: [
      ['Qwen3-ASR 0.6B и 1.7B', '2026-01'],
      ['Версии для Transformers (-hf)', '2026-06'],
    ],
    hf: 'https://huggingface.co/Qwen/Qwen3-ASR-1.7B',
    github: 'https://github.com/QwenLM/Qwen3-ASR',
    alternatives: ['whisper', 'parakeet', 'sensevoice'],
    source: 'https://huggingface.co/Qwen/Qwen3-ASR-1.7B',
    verified: true,
  },
  {
    id: 'cohere-transcribe',
    name: 'Cohere Transcribe',
    developer: 'Cohere', country: 'Канада',
    modality: ['asr'],
    first: '2026-03', latest: '2026-06',
    sizes: '2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модель распознавания речи от Cohere на 14 языков (русского в списке нет), отдельная версия для арабского. Рассчитана на точную расшифровку деловых записей.',
    tasks: ['Расшифровка встреч и интервью', 'Субтитры', 'Поиск по аудиоархиву', 'Подготовка текстов для анализа'],
    where: ['Международные компании', 'Медиа', 'Консалтинг', 'Колл-центры'],
    versions: [
      ['Cohere Transcribe 03-2026', '2026-03'],
      ['Cohere Transcribe Arabic', '2026-06'],
    ],
    hf: 'https://huggingface.co/CohereLabs/cohere-transcribe-03-2026',
    github: null,
    alternatives: ['whisper', 'parakeet', 'qwen-asr'],
    source: 'https://huggingface.co/CohereLabs/cohere-transcribe-arabic-07-2026',
    verified: true,
  },
  {
    id: 'omnilingual-asr',
    name: 'Omnilingual ASR',
    developer: 'Meta', country: 'США',
    modality: ['asr'],
    first: '2025-11', latest: '2025-12',
    sizes: '300M – 7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Распознавание речи на 1600+ языках, включая русский и редкие языки, которые раньше не поддерживала ни одна система. Новый язык можно добавить по нескольким примерам.',
    tasks: ['Расшифровка на редких и местных языках', 'Оцифровка устных архивов', 'Субтитры на многих языках', 'Голосовые сервисы для малых языков'],
    where: ['Госсектор и регионы', 'Музеи и архивы', 'Медиа', 'Образование'],
    versions: [
      ['Omnilingual ASR (CTC, LLM, W2V)', '2025-11'],
      ['Omnilingual ASR v2 и Unlimited', '2025-12'],
    ],
    hf: 'https://huggingface.co/facebook/omniASR-LLM-7B',
    github: 'https://github.com/facebookresearch/omnilingual-asr',
    alternatives: ['whisper', 'seamless', 'qwen-asr'],
    source: 'https://github.com/facebookresearch/omnilingual-asr',
    verified: true,
  },
  {
    id: 'granite-speech',
    name: 'Granite Speech',
    developer: 'IBM', country: 'США',
    modality: ['asr'],
    first: '2025-03', latest: '2026-08',
    sizes: '470M – 8B',
    license: 'Apache 2.0 (вариант granite-speech-5.0-470m-turboctc-nc — некоммерческий)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Речевые модели IBM для распознавания и перевода речи на английском и нескольких европейских языках и японском. Рассчитаны на корпоративное использование.',
    tasks: ['Расшифровка деловых встреч', 'Перевод речи в текст на другом языке', 'Голосовые ассистенты', 'Обработка записей звонков'],
    where: ['Крупные компании', 'Колл-центры', 'Финансы', 'Международные команды'],
    versions: [
      ['Granite Speech 3.2 8B', '2025-03'],
      ['Granite Speech 3.3 2B и 8B', '2025-04'],
      ['Granite 4.0 1B Speech', '2026-02'],
      ['Granite Speech 4.1 2B', '2026-04'],
      ['Granite Speech 5.0 470M', '2026-08'],
    ],
    hf: 'https://huggingface.co/ibm-granite/granite-speech-4.1-2b',
    github: null,
    alternatives: ['whisper', 'parakeet', 'granite'],
    source: 'https://huggingface.co/ibm-granite/granite-speech-5.0-470m-turboctc',
    verified: true,
  },
  {
    id: 'sensevoice',
    name: 'SenseVoice / Paraformer / Fun-ASR',
    developer: 'Alibaba (Tongyi, FunAudioLLM)', country: 'Китай',
    modality: ['asr'],
    first: '2024-07', latest: '2025-12',
    sizes: 'около 230M – 800M',
    license: 'SenseVoice Small — собственная лицензия FunASR; Fun-ASR-Nano — Apache 2.0',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Набор моделей Alibaba для быстрого распознавания речи, в первую очередь китайской и азиатских языков. SenseVoice дополнительно определяет эмоции и звуковые события.',
    tasks: ['Расшифровка звонков', 'Определение эмоций в голосе', 'Распознавание смеха, музыки и других звуков', 'Голосовые боты'],
    where: ['Колл-центры', 'Работа с азиатскими рынками', 'Медиа', 'Голосовые интерфейсы'],
    versions: [
      ['SenseVoice Small', '2024-07'],
      ['Fun-ASR-Nano и Fun-ASR-MLT-Nano', '2025-12'],
    ],
    hf: 'https://huggingface.co/FunAudioLLM/Fun-ASR-Nano-2512',
    github: 'https://github.com/QwenAudio/SenseVoice',
    alternatives: ['whisper', 'qwen-asr', 'parakeet'],
    source: 'https://huggingface.co/FunAudioLLM/Fun-ASR-Nano-2512',
    verified: true,
  },
  {
    id: 'vibevoice',
    name: 'VibeVoice',
    developer: 'Microsoft', country: 'США',
    modality: ['asr', 'tts'],
    first: '2025-08', latest: '2026-09',
    sizes: '0.5B – 9B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Речевые модели Microsoft: синтез длинных диалогов на несколько голосов, быстрый синтез для живого общения и распознавание длинных записей с разделением по говорящим, в том числе на русском.',
    tasks: ['Расшифровка длинных встреч с разметкой говорящих', 'Озвучка подкастов и диалогов', 'Голос для ассистентов в реальном времени', 'Разбор записей звонков'],
    where: ['Медиа и подкасты', 'Колл-центры', 'Корпоративные встречи', 'Голосовые ассистенты'],
    versions: [
      ['VibeVoice 1.5B (синтез)', '2025-08'],
      ['VibeVoice Realtime 0.5B (синтез)', '2025-12'],
      ['VibeVoice ASR 9B', '2026-01'],
      ['VibeVoice ASR Streaming 1.5B и 7B', '2026-09'],
    ],
    hf: 'https://huggingface.co/microsoft/VibeVoice-ASR',
    github: 'https://github.com/microsoft/VibeVoice',
    alternatives: ['whisper', 'dia', 'higgs-audio'],
    source: 'https://huggingface.co/microsoft/VibeVoice-ASR-Streaming-7B',
    verified: true,
  },

  // ---------- Синтез речи (tts) ----------
  {
    id: 'bark',
    name: 'Bark',
    developer: 'Suno', country: 'США',
    modality: ['tts'],
    first: '2023-04', latest: '2023-07',
    sizes: 'около 300M – 1B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Одна из первых открытых моделей, которая озвучивает текст с интонациями, смехом и паузами. Поддерживает около десятка языков, включая русский. Сейчас устарела.',
    tasks: ['Черновая озвучка роликов', 'Прототипы голосовых сервисов', 'Звуковые эффекты в речи'],
    where: ['Медиа', 'Маркетинг', 'Разработка прототипов'],
    versions: [
      ['Bark', '2023-04'],
      ['Bark Small', '2023-07'],
    ],
    hf: 'https://huggingface.co/suno/bark',
    github: 'https://github.com/suno-ai/bark',
    alternatives: ['xtts', 'f5-tts', 'chatterbox'],
    source: 'https://huggingface.co/suno/bark-small',
    verified: true,
  },
  {
    id: 'xtts',
    name: 'Coqui XTTS',
    developer: 'Coqui', country: 'Германия',
    modality: ['tts'],
    first: '2023-09', latest: '2023-10',
    sizes: 'около 470M',
    license: 'Coqui Public Model License — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min'],
    summary: 'Популярная модель клонирования голоса по короткому образцу на 17 языках, включая русский. Компания Coqui закрылась, развитие остановлено.',
    tasks: ['Клонирование голоса по образцу', 'Озвучка на нескольких языках', 'Исследования и прототипы'],
    where: ['Исследования', 'Образование', 'Некоммерческие проекты'],
    versions: [
      ['XTTS v1', '2023-09'],
      ['XTTS v2', '2023-10'],
    ],
    hf: 'https://huggingface.co/coqui/XTTS-v2',
    github: 'https://github.com/coqui-ai/TTS',
    alternatives: ['f5-tts', 'chatterbox', 'cosyvoice'],
    source: 'https://huggingface.co/coqui/XTTS-v2',
    verified: true,
  },
  {
    id: 'styletts',
    name: 'StyleTTS 2',
    developer: 'Колумбийский университет', country: 'США',
    modality: ['tts'],
    first: '2023-11', latest: '2023-11',
    sizes: 'около 150M',
    license: 'Код MIT; у готовых весов условие — сообщать слушателям, что голос синтезирован',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Лёгкая модель синтеза английской речи с естественной интонацией. На её основе построены многие другие модели, например Kokoro.',
    tasks: ['Озвучка текстов на английском', 'Основа для дообучения своего голоса', 'Прототипы голосовых сервисов'],
    where: ['Разработка продуктов', 'Образование', 'Медиа'],
    versions: [['StyleTTS 2 (LJSpeech, LibriTTS)', '2023-11']],
    hf: 'https://huggingface.co/yl4579/StyleTTS2-LibriTTS',
    github: 'https://github.com/yl4579/StyleTTS2',
    alternatives: ['kokoro', 'piper', 'f5-tts'],
    source: 'https://github.com/yl4579/StyleTTS2',
    verified: true,
  },
  {
    id: 'piper',
    name: 'Piper',
    developer: 'Rhasspy / Open Home Foundation', country: 'США',
    modality: ['tts'],
    first: '2023-06', latest: '2025-03',
    sizes: 'около 5M – 30M',
    license: 'Старый движок MIT, новый piper1-gpl — GPL-3.0; у каждого голоса своя лицензия (есть свободные и некоммерческие)',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Очень быстрый синтез речи, который работает даже на Raspberry Pi. Готовые голоса на 35+ языках, есть несколько русских.',
    tasks: ['Озвучка уведомлений и ответов бота', 'Голос для устройств без интернета', 'Голосовые меню', 'Чтение текста вслух'],
    where: ['Умный дом', 'Встраиваемые устройства', 'Голосовые боты', 'Терминалы и киоски'],
    versions: [
      ['Piper и первые голоса', '2023-06'],
      ['piper1-gpl (новая ветка движка)', '2025-03'],
    ],
    hf: 'https://huggingface.co/rhasspy/piper-voices',
    github: 'https://github.com/OHF-Voice/piper1-gpl',
    alternatives: ['silero', 'kokoro'],
    source: 'https://github.com/OHF-Voice/piper1-gpl',
    verified: true,
  },
  {
    id: 'silero',
    name: 'Silero TTS',
    developer: 'Silero', country: 'Россия',
    modality: ['tts'],
    first: '2022-02', latest: '2025-11',
    sizes: 'десятки мегабайт',
    license: 'Основные модели CC BY-NC (некоммерческие); базовые модели для языков СНГ v5_cis_base — MIT',
    commercial: 'conditional',
    hardware: ['min'],
    summary: 'Лёгкий синтез русской речи, работает на обычном процессоре. Версия v5 добавила языки СНГ и народов России: татарский, башкирский, якутский, казахский и другие.',
    tasks: ['Озвучка ответов голосового бота', 'Чтение текстов на русском', 'Голоса на языках народов России', 'Озвучка уведомлений'],
    where: ['Голосовые боты', 'Госсектор и регионы', 'Образование', 'Доступность для слабовидящих'],
    versions: [
      ['Silero TTS в pip-пакете (v3)', '2022-02'],
      ['Silero TTS v5 (русский)', '2025-10'],
      ['v5 для языков СНГ', '2025-11'],
    ],
    hf: null,
    github: 'https://github.com/snakers4/silero-models',
    alternatives: ['piper', 'qwen-tts', 'cosyvoice'],
    source: 'https://github.com/snakers4/silero-models',
    verified: true,
  },
  {
    id: 'f5-tts',
    name: 'F5-TTS',
    developer: 'Шанхайский университет Цзяотун и партнёры', country: 'Китай',
    modality: ['tts'],
    first: '2024-10', latest: '2025-03',
    sizes: 'около 340M',
    license: 'Код MIT, официальные веса CC BY-NC 4.0 — некоммерческие',
    commercial: 'no',
    hardware: ['min'],
    summary: 'Модель клонирования голоса по нескольким секундам образца, английский и китайский. Сообщество выпустило много дообученных версий под другие языки, в том числе русский.',
    tasks: ['Клонирование голоса', 'Озвучка аудиокниг и роликов', 'Исследования и прототипы'],
    where: ['Исследования', 'Медиа (некоммерческие проекты)', 'Образование'],
    versions: [
      ['F5-TTS', '2024-10'],
      ['F5-TTS v1', '2025-03'],
    ],
    hf: 'https://huggingface.co/SWivid/F5-TTS',
    github: 'https://github.com/SWivid/F5-TTS',
    alternatives: ['cosyvoice', 'chatterbox', 'voxcpm'],
    source: 'https://huggingface.co/SWivid/F5-TTS',
    verified: true,
  },
  {
    id: 'fish-speech',
    name: 'Fish Speech / OpenAudio',
    developer: 'Fish Audio', country: 'США / Китай',
    modality: ['tts'],
    first: '2024-04', latest: '2026-03',
    sizes: '0.5B – около 4.5B',
    license: 'Ранние версии CC BY-NC-SA 4.0, S2-Pro — Fish Audio Research License; коммерция только по отдельному договору',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    summary: 'Синтез речи с клонированием голоса и управлением эмоциями на 80+ языках, включая русский. Качество близко к платным сервисам, но веса только для исследований.',
    tasks: ['Клонирование голоса', 'Эмоциональная озвучка', 'Озвучка на многих языках'],
    where: ['Исследования', 'Медиа', 'Разработка прототипов'],
    versions: [
      ['Fish Speech 1.0', '2024-04'],
      ['Fish Speech 1.5', '2024-11'],
      ['OpenAudio S1-mini', '2025-05'],
      ['Fish Audio S2-Pro', '2026-03'],
    ],
    hf: 'https://huggingface.co/fishaudio/s2-pro',
    github: 'https://github.com/fishaudio/fish-speech',
    alternatives: ['cosyvoice', 'indextts', 'qwen-tts'],
    source: 'https://huggingface.co/fishaudio/s2-pro',
    verified: true,
  },
  {
    id: 'cosyvoice',
    name: 'CosyVoice / Fun-CosyVoice',
    developer: 'Alibaba (Tongyi, FunAudioLLM)', country: 'Китай',
    modality: ['tts'],
    first: '2024-07', latest: '2025-12',
    sizes: '300M – 0.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи с клонированием голоса по короткому образцу и потоковой выдачей для живого диалога. Третья версия поддерживает 9 языков, включая русский.',
    tasks: ['Голос для бота и ассистента', 'Клонирование фирменного голоса', 'Озвучка роликов', 'Многоязычная озвучка'],
    where: ['Колл-центры', 'Медиа и маркетинг', 'Онлайн-обучение', 'Голосовые боты'],
    versions: [
      ['CosyVoice 300M', '2024-07'],
      ['CosyVoice 2 0.5B', '2024-12'],
      ['Fun-CosyVoice 3 0.5B', '2025-12'],
    ],
    hf: 'https://huggingface.co/FunAudioLLM/Fun-CosyVoice3-0.5B-2512',
    github: 'https://github.com/QwenAudio/CosyVoice',
    alternatives: ['qwen-tts', 'voxcpm', 'fish-speech'],
    source: 'https://huggingface.co/FunAudioLLM/Fun-CosyVoice3-0.5B-2512',
    verified: true,
  },
  {
    id: 'kokoro',
    name: 'Kokoro',
    developer: 'hexgrad (независимый разработчик)', country: 'не указана',
    modality: ['tts'],
    first: '2024-12', latest: '2025-02',
    sizes: '82M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Крошечная модель синтеза речи (82M), которая звучит на уровне крупных. Работает на обычном процессоре; английский и ещё несколько языков, русского нет.',
    tasks: ['Озвучка статей и уведомлений', 'Голос для приложений без видеокарты', 'Массовая озвучка текстов'],
    where: ['Мобильные и веб-приложения', 'Медиа', 'Онлайн-обучение'],
    versions: [
      ['Kokoro v0.19', '2024-12'],
      ['Kokoro v1.0', '2025-01'],
      ['Kokoro v1.1-zh', '2025-02'],
    ],
    hf: 'https://huggingface.co/hexgrad/Kokoro-82M',
    github: 'https://github.com/hexgrad/kokoro',
    alternatives: ['piper', 'styletts', 'chatterbox'],
    source: 'https://huggingface.co/hexgrad/Kokoro-82M',
    verified: true,
  },
  {
    id: 'parler-tts',
    name: 'Parler-TTS',
    developer: 'Hugging Face', country: 'США',
    modality: ['tts'],
    first: '2024-04', latest: '2024-11',
    sizes: '880M – 2.2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи, где голос задаётся текстовым описанием («спокойный женский голос, чистая запись»). Английский и 8 европейских языков, русского нет.',
    tasks: ['Подбор голоса по описанию', 'Озвучка роликов', 'Прототипы голосовых сервисов'],
    where: ['Медиа', 'Маркетинг', 'Онлайн-обучение'],
    versions: [
      ['Parler-TTS Mini v0.1', '2024-04'],
      ['Parler-TTS Mini и Large v1', '2024-08'],
      ['Parler-TTS Mini Multilingual v1.1', '2024-11'],
    ],
    hf: 'https://huggingface.co/parler-tts/parler-tts-large-v1',
    github: 'https://github.com/huggingface/parler-tts',
    alternatives: ['qwen-tts', 'kokoro', 'dia'],
    source: 'https://huggingface.co/parler-tts/parler-tts-mini-multilingual-v1.1',
    verified: true,
  },
  {
    id: 'dia',
    name: 'Dia',
    developer: 'Nari Labs', country: 'Южная Корея',
    modality: ['tts'],
    first: '2025-04', latest: '2025-11',
    sizes: '1B – 2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Модель, которая озвучивает целые диалоги на два голоса со смехом, вздохами и паузами. Только английский.',
    tasks: ['Озвучка диалогов и подкастов', 'Рекламные ролики с живой речью', 'Сценки для обучения'],
    where: ['Медиа и подкасты', 'Маркетинг', 'Онлайн-обучение'],
    versions: [
      ['Dia 1.6B', '2025-04'],
      ['Dia2 1B и 2B', '2025-11'],
    ],
    hf: 'https://huggingface.co/nari-labs/Dia2-2B',
    github: 'https://github.com/nari-labs/dia',
    alternatives: ['vibevoice', 'higgs-audio', 'moss-tts'],
    source: 'https://huggingface.co/nari-labs/Dia2-2B',
    verified: true,
  },
  {
    id: 'orpheus',
    name: 'Orpheus TTS',
    developer: 'Canopy Labs', country: 'США',
    modality: ['tts'],
    first: '2025-03', latest: '2025-03',
    sizes: '3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Синтез речи на основе языковой модели с живыми интонациями и эмоциональными вставками. Быстро отвечает, подходит для голосовых ассистентов. В основном английский.',
    tasks: ['Голос для ассистента в реальном времени', 'Эмоциональная озвучка', 'Клонирование голоса'],
    where: ['Голосовые боты', 'Медиа', 'Разработка продуктов'],
    versions: [['Orpheus 3B 0.1', '2025-03']],
    hf: 'https://huggingface.co/canopylabs/orpheus-3b-0.1-ft',
    github: 'https://github.com/canopyai/Orpheus-TTS',
    alternatives: ['csm', 'chatterbox', 'qwen-tts'],
    source: 'https://huggingface.co/canopylabs/orpheus-3b-0.1-ft',
    verified: true,
  },
  {
    id: 'csm',
    name: 'Sesame CSM',
    developer: 'Sesame', country: 'США',
    modality: ['tts'],
    first: '2025-03', latest: '2025-03',
    sizes: '1B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Модель разговорной речи, которая учитывает контекст беседы и звучит как живой собеседник. Только английский.',
    tasks: ['Голос для разговорного ассистента', 'Озвучка диалогов', 'Прототипы голосовых продуктов'],
    where: ['Голосовые боты', 'Разработка продуктов', 'Медиа'],
    versions: [['CSM-1B', '2025-03']],
    hf: 'https://huggingface.co/sesame/csm-1b',
    github: 'https://github.com/SesameAILabs/csm',
    alternatives: ['orpheus', 'moshi', 'dia'],
    source: 'https://huggingface.co/sesame/csm-1b',
    verified: true,
  },
  {
    id: 'chatterbox',
    name: 'Chatterbox',
    developer: 'Resemble AI', country: 'США',
    modality: ['tts'],
    first: '2025-04', latest: '2026-05',
    sizes: 'около 350M – 500M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи с клонированием голоса и настройкой эмоциональности. Многоязычная версия поддерживает 23 языка, включая русский; Turbo и Flash ускорены для живого диалога.',
    tasks: ['Голос для бота и ассистента', 'Клонирование фирменного голоса', 'Озвучка роликов', 'Многоязычная озвучка'],
    where: ['Колл-центры', 'Медиа и маркетинг', 'Игры', 'Голосовые боты'],
    versions: [
      ['Chatterbox', '2025-04'],
      ['Chatterbox Turbo', '2025-12'],
      ['Chatterbox Flash', '2026-05'],
    ],
    hf: 'https://huggingface.co/ResembleAI/chatterbox',
    github: 'https://github.com/resemble-ai/chatterbox',
    alternatives: ['cosyvoice', 'f5-tts', 'kokoro'],
    source: 'https://huggingface.co/ResembleAI/chatterbox-flash',
    verified: true,
  },
  {
    id: 'indextts',
    name: 'IndexTTS',
    developer: 'bilibili', country: 'Китай',
    modality: ['tts'],
    first: '2025-03', latest: '2026-08',
    sizes: 'около 1B – 2B',
    license: 'IndexTTS и 1.5 — Apache 2.0; IndexTTS2 и 2.5 — bilibili Model License (бесплатно, но с ограничениями для очень крупных компаний)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Синтез речи с клонированием голоса и точным контролем длительности, удобен для дубляжа видео. Управляет эмоциями отдельно от тембра.',
    tasks: ['Дубляж видео с попаданием в тайминг', 'Клонирование голоса', 'Эмоциональная озвучка'],
    where: ['Медиа и видеопродакшн', 'Игры', 'Маркетинг'],
    versions: [
      ['IndexTTS', '2025-03'],
      ['IndexTTS 1.5', '2025-05'],
      ['IndexTTS2', '2025-09'],
      ['IndexTTS 2.5', '2026-08'],
    ],
    hf: 'https://huggingface.co/IndexTeam/IndexTTS-2.5',
    github: 'https://github.com/index-tts/index-tts',
    alternatives: ['cosyvoice', 'fish-speech', 'qwen-tts'],
    source: 'https://huggingface.co/IndexTeam/IndexTTS-2.5',
    verified: true,
  },
  {
    id: 'moss-tts',
    name: 'MOSS-TTS / MOSS-TTSD',
    developer: 'OpenMOSS (Фуданьский университет)', country: 'Китай',
    modality: ['tts'],
    first: '2025-06', latest: '2026-05',
    sizes: '100M – 8.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Семейство синтеза речи: озвучка диалогов на несколько голосов (TTSD), быстрый синтез для живого общения и крошечная Nano. Версия 1.5 поддерживает 30+ языков, включая русский.',
    tasks: ['Озвучка подкастов и диалогов', 'Голос для ассистента', 'Клонирование голоса', 'Многоязычная озвучка'],
    where: ['Медиа и подкасты', 'Онлайн-обучение', 'Голосовые боты'],
    versions: [
      ['MOSS-TTSD v0', '2025-06'],
      ['MOSS-TTSD v0.7', '2025-10'],
      ['MOSS-TTS, TTSD v1.0 и Realtime', '2026-02'],
      ['MOSS-TTS Nano 100M', '2026-04'],
      ['MOSS-TTS v1.5', '2026-05'],
    ],
    hf: 'https://huggingface.co/OpenMOSS-Team/MOSS-TTS-v1.5',
    github: 'https://github.com/OpenMOSS/MOSS-TTSD',
    alternatives: ['dia', 'vibevoice', 'higgs-audio'],
    source: 'https://huggingface.co/OpenMOSS-Team/MOSS-TTS-v1.5',
    verified: true,
  },
  {
    id: 'higgs-audio',
    name: 'Higgs Audio',
    developer: 'Boson AI', country: 'США',
    modality: ['tts', 'asr'],
    first: '2025-07', latest: '2026-06',
    sizes: 'около 3B – 8B',
    license: 'Higgs Audio v2 — Boson Community License на основе лицензии Llama 3 (свыше 100 тыс. пользователей в год нужна отдельная лицензия); модели распознавания v3 — Apache 2.0; higgs-tts-3 — только некоммерческое',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Выразительный синтез речи и диалогов с клонированием голоса, плюс модели распознавания. Третья версия синтеза поддерживает около 100 языков, включая русский, но некоммерческая.',
    tasks: ['Выразительная озвучка роликов', 'Озвучка диалогов', 'Клонирование голоса', 'Расшифровка речи'],
    where: ['Медиа', 'Игры', 'Маркетинг'],
    versions: [
      ['Higgs Audio v2 (3B)', '2025-07'],
      ['Higgs Audio v3 STT', '2026-03'],
      ['Higgs Audio v3 8B STT v2', '2026-04'],
      ['Higgs TTS 3 (4B)', '2026-06'],
    ],
    hf: 'https://huggingface.co/bosonai/higgs-audio-v2-generation-3B-base',
    github: 'https://github.com/boson-ai/higgs-audio',
    alternatives: ['moss-tts', 'vibevoice', 'fish-speech'],
    source: 'https://huggingface.co/bosonai/higgs-tts-3-4b',
    verified: true,
  },
  {
    id: 'qwen-tts',
    name: 'Qwen3-TTS',
    developer: 'Alibaba (Qwen)', country: 'Китай',
    modality: ['tts'],
    first: '2026-01', latest: '2026-01',
    sizes: '0.6B – 1.7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи на 10 языках, включая русский: клонирование голоса по 3 секундам, готовые голоса и создание голоса по текстовому описанию.',
    tasks: ['Голос для бота и ассистента', 'Клонирование фирменного голоса', 'Подбор голоса по описанию', 'Озвучка роликов'],
    where: ['Колл-центры', 'Медиа и маркетинг', 'Онлайн-обучение', 'Голосовые боты'],
    versions: [['Qwen3-TTS 0.6B и 1.7B (Base, CustomVoice, VoiceDesign)', '2026-01']],
    hf: 'https://huggingface.co/Qwen/Qwen3-TTS-12Hz-1.7B-Base',
    github: 'https://github.com/QwenLM/Qwen3-TTS',
    alternatives: ['cosyvoice', 'voxcpm', 'chatterbox'],
    source: 'https://huggingface.co/Qwen/Qwen3-TTS-12Hz-1.7B-Base',
    verified: true,
  },
  {
    id: 'voxcpm',
    name: 'VoxCPM',
    developer: 'OpenBMB (ModelBest, Университет Цинхуа)', country: 'Китай',
    modality: ['tts'],
    first: '2025-09', latest: '2026-04',
    sizes: '0.5B – 2.3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи с клонированием голоса и естественной интонацией. VoxCPM2 поддерживает 30 языков, включая русский.',
    tasks: ['Клонирование голоса', 'Озвучка роликов и аудиокниг', 'Голос для ассистента', 'Многоязычная озвучка'],
    where: ['Медиа', 'Онлайн-обучение', 'Голосовые боты'],
    versions: [
      ['VoxCPM 0.5B', '2025-09'],
      ['VoxCPM 1.5', '2025-12'],
      ['VoxCPM2', '2026-04'],
    ],
    hf: 'https://huggingface.co/openbmb/VoxCPM2',
    github: 'https://github.com/OpenBMB/VoxCPM',
    alternatives: ['cosyvoice', 'qwen-tts', 'f5-tts'],
    source: 'https://huggingface.co/openbmb/VoxCPM2',
    verified: true,
  },
  {
    id: 'zonos',
    name: 'Zonos',
    developer: 'Zyphra', country: 'США',
    modality: ['tts'],
    first: '2025-02', latest: '2026-06',
    sizes: 'около 1.6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Синтез речи с клонированием голоса и тонкой настройкой эмоций, скорости и высоты голоса.',
    tasks: ['Клонирование голоса', 'Эмоциональная озвучка', 'Озвучка роликов'],
    where: ['Медиа', 'Маркетинг', 'Игры'],
    versions: [
      ['Zonos v0.1 (transformer, hybrid)', '2025-02'],
      ['ZONOS2', '2026-06'],
    ],
    hf: 'https://huggingface.co/Zyphra/ZONOS2',
    github: 'https://github.com/Zyphra/Zonos',
    alternatives: ['chatterbox', 'f5-tts', 'orpheus'],
    source: 'https://huggingface.co/Zyphra/ZONOS2',
    verified: true,
  },

  // ---------- Голосовые ассистенты и перевод (omni) ----------
  {
    id: 'moshi',
    name: 'Moshi / Hibiki',
    developer: 'Kyutai', country: 'Франция',
    modality: ['omni'],
    first: '2024-09', latest: '2026-02',
    sizes: '2B – 7B',
    license: 'Moshi и Hibiki — CC-BY-4.0; Hibiki-Zero и часть новых дообученных версий — некоммерческие (CC BY-NC)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Голосовой ассистент, который слушает и говорит одновременно, без задержки на распознавание и синтез. Hibiki — синхронный перевод речи в речь между несколькими европейскими языками.',
    tasks: ['Голосовой собеседник в реальном времени', 'Синхронный перевод речи', 'Голосовые интерфейсы без задержки'],
    where: ['Голосовые боты', 'Международные встречи', 'Разработка продуктов'],
    versions: [
      ['Moshi (Moshiko, Moshika)', '2024-09'],
      ['Hibiki 2B', '2025-02'],
      ['Hibiki-Zero 3B', '2026-02'],
    ],
    hf: 'https://huggingface.co/kyutai/moshiko-pytorch-bf16',
    github: 'https://github.com/kyutai-labs/moshi',
    alternatives: ['qwen-omni', 'minicpm-o', 'seamless'],
    source: 'https://huggingface.co/kyutai/hibiki-zero-3b-pytorch-bf16',
    verified: true,
  },
  {
    id: 'qwen-omni',
    name: 'Qwen Omni',
    developer: 'Alibaba (Qwen)', country: 'Китай',
    modality: ['omni', 'vlm'],
    first: '2025-03', latest: '2025-09',
    sizes: '3B – 30B-A3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модели, которые понимают текст, картинки, аудио и видео и отвечают голосом в реальном времени. Qwen3-Omni говорит на 10 языках, включая русский.',
    tasks: ['Голосовой ассистент для клиентов', 'Разбор звонков и видео', 'Ответы голосом по документам и картинкам', 'Описание аудиозаписей'],
    where: ['Колл-центры', 'Ритейл и сервис', 'Медиа', 'Внутренние помощники'],
    versions: [
      ['Qwen2.5-Omni 7B', '2025-03'],
      ['Qwen2.5-Omni 3B', '2025-04'],
      ['Qwen3-Omni 30B-A3B (Instruct, Thinking, Captioner)', '2025-09'],
    ],
    hf: 'https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct',
    github: 'https://github.com/QwenLM/Qwen3-Omni',
    alternatives: ['minicpm-o', 'moshi', 'qwen'],
    source: 'https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct',
    verified: true,
  },
  {
    id: 'seamless',
    name: 'SeamlessM4T / Seamless',
    developer: 'Meta', country: 'США',
    modality: ['omni', 'asr'],
    first: '2023-08', latest: '2023-11',
    sizes: '281M – 2.3B',
    license: 'CC BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    summary: 'Перевод речи и текста примерно между сотней языков, включая русский: речь в текст, речь в речь, потоковый перевод с сохранением интонации.',
    tasks: ['Перевод речи в речь', 'Перевод и расшифровка записей', 'Потоковый перевод'],
    where: ['Исследования', 'Образование', 'Некоммерческие проекты'],
    versions: [
      ['SeamlessM4T (medium, large)', '2023-08'],
      ['SeamlessM4T v2, Seamless Expressive и Streaming', '2023-11'],
    ],
    hf: 'https://huggingface.co/facebook/seamless-m4t-v2-large',
    github: 'https://github.com/facebookresearch/seamless_communication',
    alternatives: ['moshi', 'whisper', 'omnilingual-asr'],
    source: 'https://huggingface.co/facebook/seamless-m4t-v2-large',
    verified: true,
  },
  {
    id: 'minicpm-o',
    name: 'MiniCPM-o',
    developer: 'OpenBMB (ModelBest, Университет Цинхуа)', country: 'Китай',
    modality: ['omni', 'vlm'],
    first: '2025-01', latest: '2026-02',
    sizes: '8B – 9B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Небольшая модель, которая видит, слышит и отвечает голосом в реальном времени, может клонировать голос. Голосовой диалог на английском и китайском, текст — на 30+ языках.',
    tasks: ['Голосовой ассистент на своём сервере', 'Разбор видео и документов', 'Ответы голосом по картинке с камеры'],
    where: ['Ритейл и сервис', 'Производство', 'Разработка продуктов'],
    versions: [
      ['MiniCPM-o 2.6', '2025-01'],
      ['MiniCPM-o 4.5', '2026-02'],
    ],
    hf: 'https://huggingface.co/openbmb/MiniCPM-o-4_5',
    github: 'https://github.com/OpenBMB/MiniCPM-V',
    alternatives: ['qwen-omni', 'minicpm-v', 'moshi'],
    source: 'https://huggingface.co/openbmb/MiniCPM-o-4_5',
    verified: true,
  },

  // ---------- Музыка и звук (audio) ----------
  {
    id: 'musicgen',
    name: 'MusicGen (AudioCraft)',
    developer: 'Meta', country: 'США',
    modality: ['audio'],
    first: '2023-06', latest: '2024-11',
    sizes: '300M – 3.3B',
    license: 'Код MIT, веса CC BY-NC 4.0 — некоммерческие',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    summary: 'Генерация инструментальной музыки по текстовому описанию или по мелодии-образцу. Одна из первых открытых моделей такого рода.',
    tasks: ['Черновые музыкальные наброски', 'Музыка для прототипов роликов', 'Исследования'],
    where: ['Исследования', 'Образование', 'Некоммерческие проекты'],
    versions: [
      ['MusicGen small, medium, large', '2023-06'],
      ['MusicGen Stereo и Melody', '2023-10'],
      ['MusicGen Style и Stem', '2024-10'],
    ],
    hf: 'https://huggingface.co/facebook/musicgen-large',
    github: 'https://github.com/facebookresearch/audiocraft',
    alternatives: ['stable-audio', 'ace-step'],
    source: 'https://huggingface.co/facebook/musicgen-stem-7cb',
    verified: true,
  },
  {
    id: 'stable-audio',
    name: 'Stable Audio',
    developer: 'Stability AI', country: 'Великобритания',
    modality: ['audio'],
    first: '2024-05', latest: '2026-05',
    sizes: 'около 0.5B – 2.3B',
    license: 'Stability AI Community License: бесплатно для компаний с выручкой до 1 млн долларов в год, выше — платная лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Генерация коротких музыкальных фрагментов и звуковых эффектов по описанию. Третья версия разделена на модели для музыки и для звуков.',
    tasks: ['Звуковые эффекты для роликов и игр', 'Фоновая музыка и джинглы', 'Звуки для интерфейсов'],
    where: ['Видеопродакшн', 'Игры', 'Маркетинг'],
    versions: [
      ['Stable Audio Open 1.0', '2024-05'],
      ['Stable Audio Open Small', '2025-05'],
      ['Stable Audio 3 (small, medium)', '2026-05'],
    ],
    hf: 'https://huggingface.co/stabilityai/stable-audio-3-medium',
    github: 'https://github.com/Stability-AI/stable-audio-tools',
    alternatives: ['ace-step', 'musicgen'],
    source: 'https://huggingface.co/stabilityai/stable-audio-3-medium',
    verified: true,
  },
  {
    id: 'yue',
    name: 'YuE',
    developer: 'M-A-P и HKUST', country: 'Китай',
    modality: ['audio'],
    first: '2025-01', latest: '2026-09',
    sizes: '0.5B – 7B',
    license: 'YuE (первая версия) — Apache 2.0; YuE2 — CC BY-NC 4.0, некоммерческая',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Генерация полноценных песен с вокалом и аккомпанементом по тексту и описанию стиля: английский, китайский, японский, корейский.',
    tasks: ['Песни и джинглы по тексту', 'Демо-версии композиций', 'Музыка для роликов'],
    where: ['Маркетинг', 'Медиа', 'Музыкальные студии'],
    versions: [
      ['YuE 7B (s1) и 1B (s2)', '2025-01'],
      ['YuE s1 0.5B', '2025-03'],
      ['YuE2 3B', '2026-09'],
    ],
    hf: 'https://huggingface.co/m-a-p/YuE2-3B',
    github: 'https://github.com/multimodal-art-projection/YuE',
    alternatives: ['ace-step', 'diffrhythm', 'songgeneration'],
    source: 'https://huggingface.co/m-a-p/YuE2-3B',
    verified: true,
  },
  {
    id: 'ace-step',
    name: 'ACE-Step',
    developer: 'ACE Studio и StepFun', country: 'Китай',
    modality: ['audio'],
    first: '2025-04', latest: '2026-06',
    sizes: 'около 2B – 4B',
    license: 'v1 — Apache 2.0; v1.5 и XL — MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Быстрая генерация песен с вокалом на 19 языках, включая русский: полная песня за секунды, правка отдельных фрагментов и смена стиля.',
    tasks: ['Песни и джинглы для рекламы', 'Фоновая музыка для роликов', 'Демо-версии композиций', 'Переделка трека в другой стиль'],
    where: ['Маркетинг', 'Медиа и блогеры', 'Музыкальные студии', 'Игры'],
    versions: [
      ['ACE-Step v1 3.5B', '2025-04'],
      ['ACE-Step v1.5', '2026-01'],
      ['ACE-Step v1.5 XL', '2026-04'],
      ['v1.5 XL для Diffusers', '2026-06'],
    ],
    hf: 'https://huggingface.co/ACE-Step/acestep-v15-xl-turbo',
    github: 'https://github.com/ace-step/ACE-Step-1.5',
    alternatives: ['yue', 'diffrhythm', 'heartmula'],
    source: 'https://huggingface.co/ACE-Step/acestep-v15-xl-sft-diffusers',
    verified: true,
  },
  {
    id: 'diffrhythm',
    name: 'DiffRhythm',
    developer: 'ASLP-lab (Северо-Западный политехнический университет)', country: 'Китай',
    modality: ['audio'],
    first: '2025-03', latest: '2025-10',
    sizes: 'около 1.1B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Быстрая генерация полной песни с вокалом по тексту и образцу стиля, до нескольких минут звучания.',
    tasks: ['Песни и джинглы по тексту', 'Музыка для роликов', 'Демо-версии композиций'],
    where: ['Маркетинг', 'Медиа', 'Музыкальные студии'],
    versions: [
      ['DiffRhythm base и full', '2025-03'],
      ['DiffRhythm 1.2', '2025-05'],
      ['DiffRhythm 2', '2025-10'],
    ],
    hf: 'https://huggingface.co/ASLP-lab/DiffRhythm2',
    github: 'https://github.com/ASLP-lab/DiffRhythm',
    alternatives: ['ace-step', 'yue', 'heartmula'],
    source: 'https://huggingface.co/ASLP-lab/DiffRhythm2',
    verified: true,
  },
  {
    id: 'songgeneration',
    name: 'SongGeneration (LeVo)',
    developer: 'Tencent AI Lab', country: 'Китай',
    modality: ['audio'],
    first: '2025-06', latest: '2026-03',
    sizes: 'около 4B',
    license: 'Собственная лицензия Tencent: только исследования и обучение, коммерческое использование запрещено',
    commercial: 'no',
    hardware: ['gpu'],
    summary: 'Генерация песен с вокалом и аккомпанементом высокого качества, вторая версия близка к платным сервисам. Веса только для исследований.',
    tasks: ['Исследования генерации музыки', 'Демо-версии песен', 'Сравнение с коммерческими сервисами'],
    where: ['Исследования', 'Образование'],
    versions: [
      ['SongGeneration (LeVo)', '2025-06'],
      ['SongGeneration 2 large', '2026-03'],
    ],
    hf: 'https://huggingface.co/lglg666/SongGeneration-v2-large',
    github: null,
    alternatives: ['ace-step', 'yue', 'heartmula'],
    source: 'https://huggingface.co/lglg666/SongGeneration-v2-large',
    verified: false, // официальные репозитории недоступны, лицензия не подтверждена
  },
  {
    id: 'heartmula',
    name: 'HeartMuLa',
    developer: 'HeartMuLa Team', country: 'не указана',
    modality: ['audio'],
    first: '2026-01', latest: '2026-09',
    sizes: '3B',
    license: 'Apache 2.0; модель каверов MuLaCover — CC BY-NC 4.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Открытая модель генерации песен с вокалом на китайском, английском, японском, корейском и испанском, плюс кодек и модель расшифровки текста песен.',
    tasks: ['Песни и джинглы по тексту', 'Музыка для роликов', 'Расшифровка текста песен'],
    where: ['Маркетинг', 'Медиа', 'Музыкальные студии'],
    versions: [
      ['HeartMuLa-oss 3B, HeartCodec, HeartTranscriptor', '2026-01'],
      ['MuLaCover', '2026-09'],
    ],
    hf: 'https://huggingface.co/HeartMuLa/HeartMuLa-oss-3B',
    github: 'https://github.com/HeartMuLa/heartlib',
    alternatives: ['ace-step', 'yue', 'diffrhythm'],
    source: 'https://huggingface.co/HeartMuLa/MuLaCover',
    verified: true,
  },
];
