// Языковые модели США, Европы, Ближнего Востока и Индии (text-west). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'bloom',
    name: 'BLOOM',
    developer: 'BigScience (Hugging Face и сообщество)', country: 'Франция',
    modality: ['text'],
    first: '2022-07', latest: '2022-11',
    sizes: '560M – 176B',
    license: 'BigScience RAIL 1.0: коммерция разрешена, но с запретами на отдельные виды использования',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'education'],
    ollama: false,
    cpu: true,
    summary: 'Одна из первых больших открытых моделей, обученная сообществом из сотен исследователей на 46 языках. Сегодня интересна скорее как историческая веха.',
    tasks: ['Генерация и перевод текстов на многих языках', 'Эксперименты и обучение команды', 'Базовая модель для дообучения под узкую задачу'],
    where: ['Исследовательские группы', 'Образование'],
    versions: [['BLOOM', '2022-07'], ['BLOOMZ (дообучена на инструкциях)', '2022-11']],
    hf: 'https://huggingface.co/bigscience/bloom',
    github: null,
    alternatives: ['falcon', 'olmo', 'pythia'],
    source: 'https://huggingface.co/bigscience/bloomz',
    verified: true,
    en: {
      summary: 'One of the first large open models, trained by a community of hundreds of researchers in 46 languages. Today it is interesting mostly as a historical milestone.',
      tasks: ['Text generation and translation in many languages', 'Experiments and team training', 'Base model for fine-tuning on a narrow task'],
      where: ['Research groups', 'Education'],
      license: 'BigScience RAIL 1.0: commercial use allowed, but certain uses are prohibited',
      developer: 'BigScience (Hugging Face and the community)',
      country: 'France',
    },
  },
  {
    id: 'opt',
    name: 'OPT',
    developer: 'Meta', country: 'США',
    modality: ['text'],
    first: '2022-05', latest: '2022-12',
    sizes: '125M – 66B (175B по запросу)',
    license: 'OPT License: только некоммерческое и исследовательское использование',
    commercial: 'no',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'education'],
    ollama: false,
    cpu: true,
    summary: 'Ранняя открытая серия Meta, повторяющая по размерам GPT-3. Устарела, полезна для исследований и сравнения.',
    tasks: ['Исследовательские эксперименты', 'Обучение специалистов', 'Сравнение с современными моделями'],
    where: ['Исследовательские группы', 'Вузы'],
    versions: [['OPT', '2022-05'], ['OPT-IML', '2022-12']],
    hf: 'https://huggingface.co/facebook/opt-66b',
    github: 'https://github.com/facebookresearch/metaseq',
    alternatives: ['pythia', 'bloom', 'llama'],
    source: 'https://huggingface.co/facebook/opt-66b',
    verified: true,
    en: {
      summary: 'An early open Meta series matching GPT-3 in size. Outdated; useful for research and comparison.',
      tasks: ['Research experiments', 'Training specialists', 'Comparison with modern models'],
      where: ['Research groups', 'Universities'],
      license: 'OPT License: non-commercial and research use only',
      country: 'USA',
      sizes: '125M – 66B (175B on request)',
    },
  },
  {
    id: 'pythia',
    name: 'Pythia и GPT-NeoX',
    developer: 'EleutherAI', country: 'США',
    modality: ['text'],
    first: '2022-02', latest: '2023-02',
    sizes: '70M – 20B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['science', 'education'],
    ollama: false,
    cpu: true,
    summary: 'Полностью открытые модели некоммерческой лаборатории EleutherAI: GPT-NeoX-20B и серия Pythia с опубликованными промежуточными снимками обучения.',
    tasks: ['Базовая модель для дообучения', 'Исследование поведения моделей', 'Простая генерация и дополнение текста'],
    where: ['Исследовательские группы', 'Вузы', 'R&D-отделы'],
    versions: [['GPT-NeoX-20B', '2022-02'], ['Pythia (70M – 12B)', '2023-02']],
    hf: 'https://huggingface.co/EleutherAI',
    github: 'https://github.com/EleutherAI/pythia',
    alternatives: ['olmo', 'opt', 'bloom'],
    source: 'https://huggingface.co/EleutherAI/pythia-12b',
    verified: true,
    en: {
      summary: 'Fully open models from the non-profit lab EleutherAI: GPT-NeoX-20B and the Pythia series with published intermediate training checkpoints.',
      tasks: ['Base model for fine-tuning', 'Research into model behavior', 'Simple text generation and completion'],
      where: ['Research groups', 'Universities', 'R&D departments'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'flan-t5',
    name: 'Flan-T5 и Flan-UL2',
    developer: 'Google', country: 'США',
    modality: ['text'],
    first: '2022-10', latest: '2023-03',
    sizes: '80M – 20B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['support', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Компактные модели «вход-выход», обученные выполнять инструкции. До сих пор используются как дешёвая основа для классификации, извлечения и коротких ответов.',
    tasks: ['Классификация обращений и документов', 'Извлечение полей из текста', 'Короткие ответы и пересказ', 'Дообучение под узкую задачу'],
    where: ['Поддержка клиентов', 'Документооборот', 'Аналитика'],
    versions: [['Flan-T5', '2022-10'], ['Flan-UL2', '2023-03']],
    hf: 'https://huggingface.co/google/flan-t5-xxl',
    github: 'https://github.com/google-research/t5x',
    alternatives: ['smollm', 'phi', 'granite'],
    source: 'https://huggingface.co/google/flan-ul2',
    verified: true,
    en: {
      summary: 'Compact input-output models trained to follow instructions. Still used as a cheap base for classification, extraction and short answers.',
      tasks: ['Classification of requests and documents', 'Extracting fields from text', 'Short answers and summaries', 'Fine-tuning for a narrow task'],
      where: ['Customer support', 'Document management', 'Analytics'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'falcon',
    name: 'Falcon',
    developer: 'Technology Innovation Institute (TII)', country: 'ОАЭ',
    modality: ['text'],
    first: '2023-05', latest: '2026-01',
    sizes: '90M – 180B',
    license: 'Falcon 7B/40B: Apache 2.0; Falcon 180B и начиная с Falcon 2: TII Falcon License (на базе Apache, с политикой допустимого использования)',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes',
    industries: ['support', 'gov', 'manufacturing'],
    ollama: true,
    cpu: true,
    summary: 'Семейство из Абу-Даби: от ранних Falcon 40B и 180B до гибридных Falcon-H1 и сверхмалых Falcon-H1-Tiny на 90–600M параметров для устройств.',
    tasks: ['Ассистент и ответы по документам', 'Работа на слабом железе и в устройствах', 'Вызов инструментов в простых агентах', 'Тексты на арабском и европейских языках'],
    where: ['Поддержка клиентов', 'Встраиваемые устройства', 'Госсектор и крупные компании'],
    versions: [['Falcon 7B / 40B', '2023-05'], ['Falcon 180B', '2023-09'], ['Falcon 2 11B', '2024-05'], ['Falcon 3', '2024-12'], ['Falcon-H1', '2025-05'], ['Falcon-H1R 7B', '2025-10'], ['Falcon-H1-Tiny', '2026-01']],
    hf: 'https://huggingface.co/tiiuae',
    github: null,
    alternatives: ['jamba', 'lfm', 'granite'],
    source: 'https://huggingface.co/tiiuae/Falcon-H1-Tiny-90M-Instruct',
    verified: true,
    en: {
      summary: 'A family from Abu Dhabi: from the early Falcon 40B and 180B to hybrid Falcon-H1 and tiny Falcon-H1-Tiny models of 90–600M parameters for devices.',
      tasks: ['Assistant and answers based on documents', 'Running on low-end hardware and devices', 'Tool calling in simple agents', 'Texts in Arabic and European languages'],
      where: ['Customer support', 'Embedded devices', 'Government and large companies'],
      license: 'Falcon 7B/40B: Apache 2.0; Falcon 180B and from Falcon 2 onward: TII Falcon License (based on Apache, with an acceptable use policy)',
      country: 'UAE',
    },
  },
  {
    id: 'mpt',
    name: 'MPT',
    developer: 'MosaicML (Databricks)', country: 'США',
    modality: ['text'],
    first: '2023-05', latest: '2023-06',
    sizes: '7B – 30B',
    license: 'Базовые версии Apache 2.0, чат-версии CC-BY-NC; официальные репозитории на Hugging Face сейчас закрыты',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['science', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Одна из первых открытых моделей с разрешением на коммерцию и длинным контекстом. Официальные веса больше не раздаются, остались копии сообщества.',
    tasks: ['Генерация текстов', 'Длинные тексты (версия StoryWriter)', 'Исследования'],
    where: ['Исследовательские группы'],
    versions: [['MPT-7B', '2023-05'], ['MPT-30B', '2023-06']],
    hf: null,
    github: 'https://github.com/mosaicml/llm-foundry',
    alternatives: ['falcon', 'pythia', 'dbrx'],
    source: 'https://huggingface.co/mosaicml',
    verified: false,
    en: {
      summary: 'One of the first open models licensed for commercial use and with a long context. Official weights are no longer distributed; community copies remain.',
      tasks: ['Text generation', 'Long texts (StoryWriter version)', 'Research'],
      where: ['Research groups'],
      license: 'Base versions Apache 2.0, chat versions CC-BY-NC; the official Hugging Face repositories are currently closed',
      country: 'USA',
    },
  },
  {
    id: 'phi',
    name: 'Phi',
    developer: 'Microsoft', country: 'США',
    modality: ['text', 'vlm'],
    first: '2023-09', latest: '2026-01',
    sizes: '1.3B – 42B-A6.6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['education', 'finance', 'dev'],
    ollama: true,
    cpu: true,
    summary: 'Малые модели Microsoft, обученные на тщательно отобранных данных: сильны в логике и математике при скромном размере. Есть версии с картинками и речью.',
    tasks: ['Ассистент на ноутбуке или своём сервере', 'Задачи с рассуждением и расчётами', 'Разбор изображений и схем (vision-версии)', 'Классификация и извлечение данных'],
    where: ['Внутренние сервисы компании', 'Образование', 'Аналитика'],
    versions: [['Phi-1 / Phi-1.5', '2023-09'], ['Phi-2', '2023-12'], ['Phi-3', '2024-04'], ['Phi-3.5 (включая MoE и Vision)', '2024-08'], ['Phi-4', '2024-12'], ['Phi-4-mini и multimodal', '2025-02'], ['Phi-4-reasoning', '2025-04'], ['Phi-4-reasoning-vision-15B', '2026-01']],
    hf: 'https://huggingface.co/microsoft/Phi-4-reasoning-vision-15B',
    github: 'https://github.com/microsoft/PhiCookBook',
    alternatives: ['gemma', 'smollm', 'granite'],
    source: 'https://huggingface.co/microsoft/Phi-4-reasoning-vision-15B',
    verified: true,
    en: {
      summary: 'Small Microsoft models trained on carefully selected data: strong at logic and math for their modest size. Versions with images and speech are available.',
      tasks: ['Assistant on a laptop or your own server', 'Reasoning and calculation tasks', 'Analysis of images and diagrams (vision versions)', 'Classification and data extraction'],
      where: ['Internal company services', 'Education', 'Analytics'],
      license: 'MIT',
      country: 'USA',
    },
  },
  {
    id: 'olmo',
    name: 'OLMo',
    developer: 'Allen Institute for AI (Ai2)', country: 'США',
    modality: ['text'],
    first: '2024-02', latest: '2026-01',
    sizes: '1B – 32B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['science', 'education', 'gov'],
    ollama: true,
    cpu: true,
    summary: 'Полностью открытые модели: опубликованы не только веса, но и данные, код обучения и промежуточные снимки. Удобно, когда важна прозрачность происхождения.',
    tasks: ['Ассистент и ответы по документам', 'Задачи с рассуждением (версии Think)', 'Дообучение под свои данные с понятной историей модели'],
    where: ['Госсектор и регулируемые отрасли', 'Исследовательские группы', 'Образование'],
    versions: [['OLMo 7B', '2024-02'], ['OLMoE 1B-7B', '2024-09'], ['OLMo 2', '2024-11'], ['OLMo 2 32B', '2025-03'], ['Olmo 3', '2025-11'], ['Olmo 3.1', '2025-12'], ['Olmo-Hybrid 7B', '2026-01']],
    hf: 'https://huggingface.co/allenai/Olmo-3.1-32B-Think',
    github: 'https://github.com/allenai/OLMo',
    alternatives: ['apertus', 'pythia', 'smollm'],
    source: 'https://huggingface.co/allenai/Olmo-Hybrid-7B',
    verified: true,
    en: {
      summary: 'Fully open models: not only the weights but also the data, training code and intermediate checkpoints are published. Useful when transparent provenance matters.',
      tasks: ['Assistant and answers based on documents', 'Reasoning tasks (Think versions)', 'Fine-tuning on your data with a clear model history'],
      where: ['Government and regulated industries', 'Research groups', 'Education'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'dbrx',
    name: 'DBRX',
    developer: 'Databricks', country: 'США',
    modality: ['text'],
    first: '2024-03', latest: '2024-03',
    sizes: '132B-A36B',
    license: 'Databricks Open Model License (с ограничениями); официальные веса на Hugging Face сейчас закрыты',
    commercial: 'conditional',
    hardware: ['multi'],
    ru: 'unknown',
    industries: ['finance', 'dev'],
    ollama: true,
    cpu: false,
    summary: 'Большая MoE-модель Databricks 2024 года. Официальные репозитории закрыты, поэтому для новых внедрений не подходит.',
    tasks: ['Ответы по корпоративным данным', 'Генерация SQL и кода', 'Анализ текстов'],
    where: ['Аналитика данных', 'ИТ-отделы'],
    versions: [['DBRX Base / Instruct', '2024-03']],
    hf: null,
    github: 'https://github.com/databricks/dbrx',
    alternatives: ['mpt', 'jamba', 'command'],
    source: 'https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm',
    verified: false,
    en: {
      summary: 'A large MoE model from Databricks (2024). The official repositories are closed, so it is not suitable for new deployments.',
      tasks: ['Answers based on corporate data', 'SQL and code generation', 'Text analysis'],
      where: ['Data analytics', 'IT departments'],
      license: 'Databricks Open Model License (with restrictions); official weights on Hugging Face are currently closed',
      country: 'USA',
    },
  },
  {
    id: 'grok',
    name: 'Grok (открытые веса)',
    developer: 'xAI', country: 'США',
    modality: ['text'],
    first: '2024-03', latest: '2025-08',
    sizes: '314B (Grok-1), Grok-2 крупнее',
    license: 'Grok-1: Apache 2.0; Grok-2: Grok 2 Community License (коммерция при соблюдении правил xAI, нельзя обучать на ней другие большие модели)',
    commercial: 'conditional',
    hardware: ['multi'],
    ru: 'unknown',
    industries: ['science', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'xAI выкладывает веса прошлых поколений Grok. Модели очень большие и требуют кластера видеокарт, поэтому на практике их запускают редко.',
    tasks: ['Исследования больших моделей', 'Ассистент на собственной инфраструктуре', 'Генерация и анализ текстов'],
    where: ['Крупные ИТ-компании', 'Исследовательские группы'],
    versions: [['Grok-1', '2024-03'], ['Grok-2', '2025-08']],
    hf: 'https://huggingface.co/xai-org/grok-2',
    github: 'https://github.com/xai-org/grok-1',
    alternatives: ['inkling', 'nemotron', 'llama'],
    source: 'https://huggingface.co/xai-org/grok-2',
    verified: true,
    en: {
      summary: 'xAI publishes the weights of previous Grok generations. The models are very large and need a GPU cluster, so in practice they are rarely run.',
      tasks: ['Research on large models', 'Assistant on your own infrastructure', 'Text generation and analysis'],
      where: ['Large IT companies', 'Research groups'],
      license: 'Grok-1: Apache 2.0; Grok-2: Grok 2 Community License (commercial use if xAI rules are followed; it may not be used to train other large models)',
      country: 'USA',
      sizes: '314B (Grok-1), Grok-2 is larger',
    },
  },
  {
    id: 'jamba',
    name: 'Jamba',
    developer: 'AI21 Labs', country: 'Израиль',
    modality: ['text'],
    first: '2024-03', latest: '2026-01',
    sizes: '3B – 398B-A94B',
    license: 'Jamba v0.1, Reasoning 3B и Jamba2: Apache 2.0; Jamba 1.5–1.7: Jamba Open Model License с ограничением по выручке',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['legal', 'support', 'finance', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Гибрид трансформера и Mamba с окном до 256K токенов: держит длинные документы быстрее обычных моделей. Jamba2 ориентирована на точные ответы по источникам.',
    tasks: ['Ответы по длинным регламентам и договорам', 'Поиск по базе знаний (RAG)', 'Пересказ больших документов', 'Следование строгим инструкциям'],
    where: ['Юридические отделы', 'Поддержка клиентов', 'Финансы'],
    versions: [['Jamba v0.1', '2024-03'], ['Jamba 1.5 Mini / Large', '2024-08'], ['Jamba 1.6', '2025-02'], ['Jamba 1.7', '2025-07'], ['Jamba Reasoning 3B', '2025-10'], ['Jamba2 3B / Mini', '2026-01']],
    hf: 'https://huggingface.co/ai21labs/AI21-Jamba2-Mini',
    github: null,
    alternatives: ['falcon', 'granite', 'command'],
    source: 'https://huggingface.co/ai21labs/AI21-Jamba2-Mini',
    verified: true,
    en: {
      summary: 'A hybrid of Transformer and Mamba with a window of up to 256K tokens: handles long documents faster than conventional models. Jamba2 focuses on accurate, source-based answers.',
      tasks: ['Answers based on long policies and contracts', 'Knowledge-base search (RAG)', 'Summaries of large documents', 'Following strict instructions'],
      where: ['Legal departments', 'Customer support', 'Finance'],
      license: 'Jamba v0.1, Reasoning 3B and Jamba2: Apache 2.0; Jamba 1.5–1.7: Jamba Open Model License with a revenue limit',
      country: 'Israel',
    },
  },
  {
    id: 'command',
    name: 'Cohere Command',
    developer: 'Cohere', country: 'Канада',
    modality: ['text', 'vlm', 'code', 'translate'],
    first: '2024-03', latest: '2026-08',
    sizes: '2.5B – 218B-A25B',
    license: 'Command R, R+, R7B, Command A (2024–2025) и North Small Translate: CC-BY-NC, только некоммерческое; Command A+ (05-2026), North Mini Code и North Micro Vision: Apache 2.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes',
    industries: ['support', 'legal', 'finance', 'docs'],
    ollama: true,
    cpu: true,
    summary: 'Модели для бизнеса: поиск по документам со ссылками на источники, вызов инструментов, много языков. Command A+ 2026 года впервые вышла под Apache 2.0, за ней — линейка North: код, перевод и компактное зрение.',
    tasks: ['Ответы по базе знаний со ссылками на источники', 'Агенты, работающие с внутренними системами', 'Перевод и переписка на разных языках', 'Разбор документов с картинками (A+)'],
    where: ['Крупные компании', 'Поддержка клиентов', 'Юридические и финансовые отделы'],
    versions: [['Command R', '2024-03'], ['Command R+', '2024-04'], ['Command R7B', '2024-12'], ['Command A', '2025-03'], ['Command A Vision / Reasoning / Translate', '2025-08'], ['Command A+', '2026-05'], ['North Mini Code 30B-A3B', '2026-06'], ['North Micro Vision 2.5B / Small Translate', '2026-08']],
    hf: 'https://huggingface.co/CohereLabs/command-a-plus-05-2026-bf16',
    github: null,
    alternatives: ['aya', 'jamba', 'granite'],
    source: 'https://huggingface.co/CohereLabs/command-a-plus-05-2026-bf16',
    verified: true,
    en: {
      summary: 'Business models: document search with source citations, tool calling, many languages. Command A+ (2026) was the first under Apache 2.0, followed by the North line: code, translation and compact vision.',
      tasks: ['Knowledge-base answers with source citations', 'Agents that work with internal systems', 'Translation and correspondence in different languages', 'Analysis of documents with images (A+)'],
      where: ['Large companies', 'Customer support', 'Legal and finance departments'],
      license: 'Command R, R+, R7B, Command A (2024–2025) and North Small Translate: CC-BY-NC, non-commercial only; Command A+ (05-2026), North Mini Code and North Micro Vision: Apache 2.0',
      country: 'Canada',
    },
  },
  {
    id: 'aya',
    name: 'Aya',
    developer: 'Cohere Labs', country: 'Канада',
    modality: ['text', 'vlm'],
    first: '2024-02', latest: '2026-09',
    sizes: '3.3B – 35B',
    license: 'Aya 101: Apache 2.0; Aya 23, Expanse, Vision и Tiny Aya: CC-BY-NC, только некоммерческое',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['education', 'support', 'marketing'],
    ollama: true,
    cpu: true,
    summary: 'Многоязычные модели исследовательского крыла Cohere, от 23 до 100+ языков. Tiny Aya 2026 года на 3.3B работает на обычном ПК, но только некоммерчески.',
    tasks: ['Перевод и переписка на редких языках', 'Многоязычный чат-ассистент', 'Разбор изображений с текстом (Vision)'],
    where: ['Образование', 'Некоммерческие проекты', 'Исследования'],
    versions: [['Aya 101', '2024-02'], ['Aya 23', '2024-05'], ['Aya Expanse', '2024-10'], ['Aya Vision', '2025-03'], ['Tiny Aya', '2026-02'], ['Tiny Aya Thinker', '2026-09']],
    hf: 'https://huggingface.co/CohereLabs/tiny-aya-global',
    github: null,
    alternatives: ['command', 'apertus', 'sarvam'],
    source: 'https://huggingface.co/CohereLabs/tiny-aya-global',
    verified: true,
    en: {
      summary: 'Multilingual models from Cohere\'s research arm, covering 23 to 100+ languages. Tiny Aya (2026, 3.3B) runs on a regular PC, but for non-commercial use only.',
      tasks: ['Translation and correspondence in less common languages', 'Multilingual chat assistant', 'Analysis of images with text (Vision)'],
      where: ['Education', 'Non-profit projects', 'Research'],
      license: 'Aya 101: Apache 2.0; Aya 23, Expanse, Vision and Tiny Aya: CC-BY-NC, non-commercial only',
      country: 'Canada',
    },
  },
  {
    id: 'nemotron',
    name: 'NVIDIA Nemotron',
    developer: 'NVIDIA', country: 'США',
    modality: ['text', 'vlm', 'omni'],
    first: '2024-06', latest: '2026-08',
    sizes: '4B – 550B-A55B',
    license: 'Nemotron-4, Llama-Nemotron, Nemotron 3 Nano, Nano Omni, Cascade 2 и Super: лицензии NVIDIA Open Model License / Open Model Agreement (коммерция разрешена с условиями; у Llama-версий добавляются условия Llama); Nemotron 3 Ultra и 3.5 Lightning: OpenMDW-1.1',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['dev', 'manufacturing', 'science'],
    ollama: true,
    cpu: true,
    summary: 'Модели NVIDIA для агентов и рассуждений, заточенные под быстрый запуск на её видеокартах. Nemotron 3 это гибрид Mamba и MoE от 4B до 550B; Nano Omni разбирает видео, аудио и картинки (только английский).',
    tasks: ['Агенты с вызовом инструментов', 'Задачи с рассуждением и расчётами', 'Ответы по длинным документам', 'Генерация синтетических данных для обучения'],
    where: ['ИТ-отделы и разработка', 'Промышленность', 'Крупные компании с собственным GPU-кластером'],
    versions: [['Nemotron-4 340B', '2024-06'], ['Llama-3.1-Nemotron-70B', '2024-10'], ['Llama-Nemotron Ultra 253B', '2025-04'], ['Nemotron Nano 2 (9B, 12B)', '2025-08'], ['Nemotron 3 Nano 30B-A3B', '2025-12'], ['Nemotron 3 Super 120B-A12B / Nano 4B / Cascade 2 30B-A3B', '2026-03'], ['Nemotron 3 Nano Omni 30B-A3B', '2026-04'], ['Nemotron 3 Ultra 550B-A55B', '2026-06'], ['Nemotron 3.5 Lightning 30B-A3B', '2026-08']],
    hf: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16',
    github: null,
    alternatives: ['llama', 'qwen', 'granite'],
    source: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16',
    verified: true,
    en: {
      summary: 'NVIDIA models for agents and reasoning, optimized to run fast on its GPUs. Nemotron 3 is a Mamba and MoE hybrid from 4B to 550B; Nano Omni handles video, audio and images (English only).',
      tasks: ['Agents with tool calling', 'Reasoning and calculation tasks', 'Answers based on long documents', 'Synthetic training data generation'],
      where: ['IT and development', 'Industry', 'Large companies with their own GPU cluster'],
      license: 'Nemotron-4, Llama-Nemotron, Nemotron 3 Nano, Nano Omni, Cascade 2 and Super: NVIDIA Open Model License / Open Model Agreement (commercial use allowed with conditions; Llama-based versions add Llama terms); Nemotron 3 Ultra and 3.5 Lightning: OpenMDW-1.1',
      country: 'USA',
    },
  },
  {
    id: 'granite',
    name: 'IBM Granite',
    developer: 'IBM', country: 'США',
    modality: ['text'],
    first: '2024-05', latest: '2026-08',
    sizes: '350M – 34B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['finance', 'gov', 'dev', 'docs'],
    ollama: true,
    cpu: true,
    summary: 'Корпоративные модели IBM с прозрачными данными обучения и сертификацией ISO 42001. Granite 4 это гибрид Mamba и трансформера, экономный по памяти.',
    tasks: ['Ответы по внутренним документам (RAG)', 'Вызов инструментов и работа в агентах', 'Извлечение данных и классификация', 'Помощь в коде'],
    where: ['Банки и страхование', 'Госсектор', 'ИТ-отделы крупных компаний'],
    versions: [['Granite Code', '2024-05'], ['Granite 3.0', '2024-10'], ['Granite 3.1', '2024-12'], ['Granite 3.3', '2025-04'], ['Granite 4.0', '2025-10'], ['Granite 4.1', '2026-04'], ['Granite 4.2', '2026-08']],
    hf: 'https://huggingface.co/ibm-granite/granite-4.2-30b',
    github: null,
    alternatives: ['phi', 'command', 'nemotron'],
    source: 'https://huggingface.co/ibm-granite/granite-4.2-30b',
    verified: true,
    en: {
      summary: 'IBM enterprise models with transparent training data and ISO 42001 certification. Granite 4 is a memory-efficient Mamba and Transformer hybrid.',
      tasks: ['Answers based on internal documents (RAG)', 'Tool calling and agent work', 'Data extraction and classification', 'Coding help'],
      where: ['Banking and insurance', 'Government', 'IT departments of large companies'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'smollm',
    name: 'SmolLM',
    developer: 'Hugging Face', country: 'США',
    modality: ['text'],
    first: '2024-07', latest: '2025-07',
    sizes: '135M – 3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['support', 'education'],
    ollama: true,
    cpu: true,
    summary: 'Крошечные открытые модели Hugging Face для телефонов и ноутбуков. SmolLM3 на 3B умеет рассуждать и держит длинный контекст, весь рецепт обучения открыт.',
    tasks: ['Простой ассистент прямо на устройстве', 'Классификация и маршрутизация обращений', 'Основа для дообучения под узкую задачу'],
    where: ['Мобильные приложения', 'Встраиваемые устройства', 'Образование'],
    versions: [['SmolLM', '2024-07'], ['SmolLM2', '2024-10'], ['SmolLM3 3B', '2025-07']],
    hf: 'https://huggingface.co/HuggingFaceTB/SmolLM3-3B',
    github: 'https://github.com/huggingface/smollm',
    alternatives: ['lfm', 'phi', 'gemma'],
    source: 'https://huggingface.co/HuggingFaceTB/SmolLM3-3B',
    verified: true,
    en: {
      summary: 'Tiny open Hugging Face models for phones and laptops. SmolLM3 (3B) can reason and handle long context; the full training recipe is open.',
      tasks: ['Simple on-device assistant', 'Classification and routing of requests', 'Base for fine-tuning on a narrow task'],
      where: ['Mobile apps', 'Embedded devices', 'Education'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'lfm',
    name: 'Liquid LFM',
    developer: 'Liquid AI', country: 'США',
    modality: ['text', 'vlm', 'omni'],
    first: '2025-07', latest: '2026-08',
    sizes: '230M – 24B-A2B',
    license: 'LFM Open License v1.0: бесплатно для компаний с выручкой до 10 млн долларов в год, выше нужна отдельная лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['docs', 'support', 'retail'],
    ollama: true,
    cpu: true,
    summary: 'Модели новой архитектуры для работы прямо на устройстве: быстрые на обычном процессоре и в телефоне. Есть версии для извлечения данных, RAG и инструментов, а также LFM2.5-VL для картинок и голосовая LFM2.5-Audio.',
    tasks: ['Ассистент на ноутбуке или телефоне без интернета', 'Извлечение данных из документов', 'Вызов инструментов в приложениях', 'Поиск по базе знаний (RAG)'],
    where: ['Мобильные приложения', 'Автомобильная и бытовая электроника', 'Малый бизнес'],
    versions: [['LFM2', '2025-07'], ['LFM2-8B-A1B', '2025-10'], ['LFM2.5-1.2B / VL-1.6B / Audio-1.5B', '2026-01'], ['LFM2-24B-A2B', '2026-02'], ['LFM2.5-8B-A1B', '2026-05'], ['LFM2.5-2.6B', '2026-07'], ['LFM2.5-VL-3B', '2026-08']],
    hf: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B',
    github: null,
    alternatives: ['smollm', 'phi', 'falcon'],
    source: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B',
    verified: true,
    en: {
      summary: 'Models with a new architecture for on-device use: fast on a regular CPU and on phones. Versions for data extraction, RAG and tools, plus LFM2.5-VL for images and voice LFM2.5-Audio.',
      tasks: ['Offline assistant on a laptop or phone', 'Data extraction from documents', 'Tool calling in apps', 'Knowledge-base search (RAG)'],
      where: ['Mobile apps', 'Automotive and consumer electronics', 'Small business'],
      license: 'LFM Open License v1.0: free for companies with revenue up to 10 million dollars a year; above that, a separate license is required',
      country: 'USA',
    },
  },
  {
    id: 'apertus',
    name: 'Apertus',
    developer: 'Swiss AI (ETH Zurich, EPFL, CSCS)', country: 'Швейцария',
    modality: ['text', 'vlm'],
    first: '2025-09', latest: '2026-07',
    sizes: '0.5B – 70B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['gov', 'education', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Государственная открытая модель Швейцарии: открыты веса, данные и рецепт, более 1000 языков в обучении. Версия 1.5 понимает изображения.',
    tasks: ['Многоязычный ассистент', 'Ответы по документам', 'Разбор изображений и сканов (v1.5)', 'Дообучение с понятным происхождением данных'],
    where: ['Госсектор', 'Образование и наука', 'Регулируемые отрасли'],
    versions: [['Apertus 8B / 70B', '2025-09'], ['Apertus v1.1 (0.5B – 4B)', '2026-02'], ['Apertus v1.5 8B / 70B', '2026-07']],
    hf: 'https://huggingface.co/swiss-ai/Apertus-v1.5-70B',
    github: null,
    alternatives: ['olmo', 'aya', 'mistral'],
    source: 'https://huggingface.co/swiss-ai/Apertus-v1.5-70B',
    verified: true,
    en: {
      summary: 'Switzerland\'s public open model: weights, data and recipe are open, with more than 1000 languages in training. Version 1.5 understands images.',
      tasks: ['Multilingual assistant', 'Answers based on documents', 'Analysis of images and scans (v1.5)', 'Fine-tuning with clear data provenance'],
      where: ['Government', 'Education and science', 'Regulated industries'],
      license: 'Apache 2.0',
      country: 'Switzerland',
    },
  },
  {
    id: 'muse-glimmer',
    name: 'Muse Glimmer',
    developer: 'Meta Superintelligence Labs', country: 'США',
    modality: ['text', 'vlm'],
    first: '2026-08', latest: '2026-08',
    sizes: '30B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['support', 'dev', 'docs'],
    ollama: true,
    cpu: false,
    summary: 'Открытая модель Meta для агентов на доступном железе: дистиллирована из закрытой Muse Spark, понимает текст и картинки, обучена на 100+ языках.',
    tasks: ['Агенты с вызовом инструментов', 'Разбор скриншотов, графиков и документов', 'Многоязычный ассистент'],
    where: ['Автоматизация офисных процессов', 'Поддержка клиентов', 'ИТ-отделы'],
    versions: [['Muse Glimmer 30B', '2026-08']],
    hf: 'https://huggingface.co/meta-models/Muse-Glimmer-30B',
    github: null,
    alternatives: ['llama', 'gemma', 'qwen'],
    source: 'https://huggingface.co/meta-models/Muse-Glimmer-30B',
    verified: true,
    en: {
      summary: 'An open Meta model for agents on affordable hardware: distilled from the closed Muse Spark, understands text and images, trained on 100+ languages.',
      tasks: ['Agents with tool calling', 'Analysis of screenshots, charts and documents', 'Multilingual assistant'],
      where: ['Office process automation', 'Customer support', 'IT departments'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'inkling',
    name: 'Inkling',
    developer: 'Thinking Machines Lab', country: 'США',
    modality: ['text', 'vlm'],
    first: '2026-07', latest: '2026-07',
    sizes: '276B-A12B, 975B-A41B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['multi'],
    ru: 'unknown',
    industries: ['dev', 'finance', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Флагманские открытые модели лаборатории Миры Мурати: принимают текст, изображения и аудио. Большие MoE, требуют нескольких видеокарт.',
    tasks: ['Корпоративный ассистент уровня флагмана', 'Разбор документов, изображений и аудио', 'Помощь в программировании', 'Агенты для сложных многошаговых задач'],
    where: ['Крупные компании', 'ИТ и разработка', 'Аналитика'],
    versions: [['Inkling', '2026-07'], ['Inkling-Small', '2026-07']],
    hf: 'https://huggingface.co/thinkingmachines/Inkling',
    github: null,
    alternatives: ['command', 'nemotron', 'deepseek'],
    source: 'https://huggingface.co/thinkingmachines/Inkling-Small',
    verified: true,
    en: {
      summary: 'Flagship open models from Mira Murati\'s lab: they take text, images and audio. Large MoE models that need several GPUs.',
      tasks: ['Flagship-level corporate assistant', 'Analysis of documents, images and audio', 'Programming help', 'Agents for complex multi-step tasks'],
      where: ['Large companies', 'IT and development', 'Analytics'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'laguna',
    name: 'Laguna',
    developer: 'Poolside', country: 'США',
    modality: ['code', 'text'],
    first: '2026-04', latest: '2026-07',
    sizes: '33B-A3B – 225B-A23B',
    license: 'Laguna XS.2 и M.1: Apache 2.0; Laguna XS 2.1 и S 2.1: OpenMDW-1.1 (свободное коммерческое использование)',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['dev'],
    ollama: false,
    cpu: false,
    summary: 'Модели для агентного программирования: самостоятельно правят код в репозитории. Младшая XS запускается на Mac с 36 ГБ памяти, у S 2.1 контекст 1M токенов.',
    tasks: ['Агент-программист для внутренней разработки', 'Исправление ошибок и доработка кода', 'Работа с большими кодовыми базами'],
    where: ['ИТ-отделы', 'Разработка ПО', 'Интеграторы'],
    versions: [['Laguna XS.2', '2026-04'], ['Laguna M.1', '2026-06'], ['Laguna XS 2.1', '2026-06'], ['Laguna S 2.1', '2026-07']],
    hf: 'https://huggingface.co/poolside/Laguna-S-2.1',
    github: null,
    alternatives: ['qwen-coder', 'devstral', 'kat-coder'],
    source: 'https://huggingface.co/poolside/Laguna-S-2.1',
    verified: true,
    en: {
      summary: 'Models for agentic programming: they edit code in a repository on their own. The small XS runs on a Mac with 36 GB of memory; S 2.1 has a 1M-token context.',
      tasks: ['Coding agent for in-house development', 'Bug fixing and code improvements', 'Working with large codebases'],
      where: ['IT departments', 'Software development', 'System integrators'],
      license: 'Laguna XS.2 and M.1: Apache 2.0; Laguna XS 2.1 and S 2.1: OpenMDW-1.1 (free commercial use)',
      country: 'USA',
    },
  },
  {
    id: 'trinity',
    name: 'Arcee Trinity',
    developer: 'Arcee AI', country: 'США',
    modality: ['text'],
    first: '2025-12', latest: '2026-04',
    sizes: '6B – 398B-A13B',
    license: 'OpenMDW-1.1 (свободное коммерческое использование)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes',
    industries: ['dev', 'finance'],
    ollama: false,
    cpu: true,
    summary: 'Американское семейство MoE-моделей, обученных с нуля: Nano, Mini и Large. Trinity-Large-Thinking на 398B рассуждает перед ответом.',
    tasks: ['Агенты с вызовом инструментов', 'Задачи с рассуждением', 'Корпоративный ассистент на своих серверах'],
    where: ['ИТ-отделы', 'Крупные компании', 'Аналитика'],
    versions: [['Trinity Nano / Mini', '2025-12'], ['Trinity-Large-Preview', '2026-01'], ['Trinity-Large-Thinking', '2026-04']],
    hf: 'https://huggingface.co/arcee-ai/Trinity-Large-Thinking',
    github: null,
    alternatives: ['olmo', 'nemotron', 'gpt-oss'],
    source: 'https://huggingface.co/arcee-ai/Trinity-Large-Thinking',
    verified: true,
    en: {
      summary: 'An American family of MoE models trained from scratch: Nano, Mini and Large. Trinity-Large-Thinking (398B) reasons before answering.',
      tasks: ['Agents with tool calling', 'Reasoning tasks', 'Corporate assistant on your own servers'],
      where: ['IT departments', 'Large companies', 'Analytics'],
      license: 'OpenMDW-1.1 (free commercial use)',
      country: 'USA',
    },
  },
  {
    id: 'sarvam',
    name: 'Sarvam',
    developer: 'Sarvam AI', country: 'Индия',
    modality: ['text'],
    first: '2024-10', latest: '2026-03',
    sizes: '2B – 105B-A10B',
    license: 'Основные версии Apache 2.0 (Sarvam-M, Sarvam 30B и 105B)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['support', 'gov'],
    ollama: false,
    cpu: true,
    summary: 'Индийские модели с упором на 22 языка Индии. Sarvam 30B и 105B 2026 года это MoE-модели с сильными навыками рассуждения и работы в агентах.',
    tasks: ['Многоязычная поддержка клиентов', 'Задачи с рассуждением и расчётами', 'Агенты с вызовом инструментов'],
    where: ['Компании с клиентами в Индии', 'Госсектор', 'Колл-центры'],
    versions: [['Sarvam-1 2B', '2024-10'], ['Sarvam-M 24B', '2025-05'], ['Sarvam 30B / 105B', '2026-03']],
    hf: 'https://huggingface.co/sarvamai/sarvam-105b',
    github: null,
    alternatives: ['aya', 'apertus', 'qwen'],
    source: 'https://huggingface.co/sarvamai/sarvam-105b',
    verified: true,
    en: {
      summary: 'Indian models focused on 22 languages of India. Sarvam 30B and 105B (2026) are MoE models with strong reasoning and agent skills.',
      tasks: ['Multilingual customer support', 'Reasoning and calculation tasks', 'Agents with tool calling'],
      where: ['Companies with customers in India', 'Government', 'Call centers'],
      license: 'Main versions Apache 2.0 (Sarvam-M, Sarvam 30B and 105B)',
      country: 'India',
    },
  },
  {
    id: 'intellect',
    name: 'INTELLECT',
    developer: 'Prime Intellect', country: 'США',
    modality: ['text'],
    first: '2024-11', latest: '2026-01',
    sizes: '10B – 106B-A12B',
    license: 'INTELLECT-1 и 2: Apache 2.0; INTELLECT-3 и 3.1: MIT',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Модели, обученные распределённо на видеокартах со всего мира. INTELLECT-3 на 106B дообучена с подкреплением для математики, кода и агентов.',
    tasks: ['Задачи с рассуждением и математикой', 'Помощь в программировании', 'Агенты с вызовом инструментов'],
    where: ['ИТ и разработка', 'Исследовательские группы'],
    versions: [['INTELLECT-1 10B', '2024-11'], ['INTELLECT-2 32B', '2025-05'], ['INTELLECT-3', '2025-11'], ['INTELLECT-3.1', '2026-01']],
    hf: 'https://huggingface.co/PrimeIntellect/INTELLECT-3.1',
    github: null,
    alternatives: ['trinity', 'olmo', 'glm'],
    source: 'https://huggingface.co/PrimeIntellect/INTELLECT-3.1',
    verified: true,
    en: {
      summary: 'Models trained in a distributed way on GPUs from around the world. INTELLECT-3 (106B) is further trained with reinforcement learning for math, code and agents.',
      tasks: ['Reasoning and math tasks', 'Programming help', 'Agents with tool calling'],
      where: ['IT and development', 'Research groups'],
      license: 'INTELLECT-1 and 2: Apache 2.0; INTELLECT-3 and 3.1: MIT',
      country: 'USA',
    },
  },
  {
    id: 'reka',
    name: 'Reka Flash и Reka Edge',
    developer: 'Reka AI', country: 'США',
    modality: ['text', 'vlm'],
    first: '2025-03', latest: '2026-03',
    sizes: '7B – 21B',
    license: 'Reka Flash 3 и 3.1: Apache 2.0; Reka Edge: своя лицензия, коммерция бесплатна при выручке до 1 млн долларов в год',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['media', 'retail', 'manufacturing'],
    ollama: false,
    cpu: false,
    summary: 'Компактные модели Reka: Flash 3 на 21B для рассуждений и Reka Edge на 7B, которая быстро разбирает изображения и видео на устройстве.',
    tasks: ['Разбор фото и видео (Edge)', 'Поиск объектов на изображениях', 'Задачи с рассуждением (Flash)'],
    where: ['Видеоаналитика', 'Встраиваемые устройства', 'Розница'],
    versions: [['Reka Flash 3', '2025-03'], ['Reka Flash 3.1', '2025-05'], ['Reka Edge 2603', '2026-03']],
    hf: 'https://huggingface.co/RekaAI/reka-edge-2603',
    github: null,
    alternatives: ['phi', 'muse-glimmer', 'lfm'],
    source: 'https://huggingface.co/RekaAI/reka-edge-2603',
    verified: true,
    en: {
      summary: 'Compact Reka models: Flash 3 (21B) for reasoning and Reka Edge (7B), which quickly analyzes images and video on-device.',
      tasks: ['Photo and video analysis (Edge)', 'Object detection in images', 'Reasoning tasks (Flash)'],
      where: ['Video analytics', 'Embedded devices', 'Retail'],
      license: 'Reka Flash 3 and 3.1: Apache 2.0; Reka Edge: own license, commercial use free with revenue up to 1 million dollars a year',
      country: 'USA',
    },
  },
];
