// Языковые модели Китая, Кореи и России (text-east). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    developer: 'DeepSeek', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-11', latest: '2026-09',
    sizes: '7B – 1.6T-A49B',
    license: 'MIT (V2 и ранние версии — собственная лицензия DeepSeek с запретами на вредное использование)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Флагманская линия DeepSeek: от первых 7B/67B до V4-Pro на 1,6 трлн параметров. Уровень закрытых моделей при открытой MIT-лицензии; V4.1-Flash понимает картинки и держит контекст до 1 млн токенов.',
    tasks: ['Ассистент для сотрудников на своём сервере', 'Разбор длинных договоров и отчётов', 'Агенты, которые работают с инструментами и API', 'Помощь программистам'],
    where: ['Юристы и финансы', 'Поддержка клиентов', 'ИТ-отдел', 'Аналитика'],
    versions: [['DeepSeek LLM 7B / 67B', '2023-11'], ['DeepSeek-MoE 16B', '2024-01'], ['DeepSeek-V2', '2024-04'], ['DeepSeek-V2.5', '2024-09'], ['DeepSeek-V3', '2024-12'], ['DeepSeek-V3.1', '2025-08'], ['DeepSeek-V3.2', '2025-12'], ['DeepSeek-V4-Pro / V4-Flash', '2026-04'], ['DeepSeek-V4.1-Flash', '2026-09']],
    hf: 'https://huggingface.co/deepseek-ai',
    github: 'https://github.com/deepseek-ai',
    alternatives: ['deepseek-r1', 'kimi', 'glm'],
    source: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash',
    verified: true,
  },
  {
    id: 'kimi',
    name: 'Kimi',
    developer: 'Moonshot AI', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2025-02', latest: '2026-07',
    sizes: '16B-A3B – 2.8T-A104B',
    license: 'K2–K2.6 — модифицированная MIT (при 100 млн пользователей или 20 млн $ выручки в месяц нужно указать Kimi в интерфейсе); K3 — собственная Kimi K3 License: API-бизнесу с выручкой от 20 млн $ в год нужен отдельный договор',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    summary: 'Сверхкрупные MoE-модели Moonshot для агентной работы. K3 на 2,8 трлн параметров — самая большая открытая модель на момент выхода, с контекстом до 1 млн токенов и пониманием картинок.',
    tasks: ['Многошаговые агенты: поиск, сбор данных, отчёты', 'Глубокий анализ документов', 'Помощь программистам', 'Разбор скриншотов и таблиц'],
    where: ['Аналитические отделы', 'ИТ-разработка', 'Консалтинг', 'Маркетинг-исследования'],
    versions: [['Moonlight 16B-A3B', '2025-02'], ['Kimi K2', '2025-07'], ['Kimi Linear 48B-A3B', '2025-10'], ['Kimi K2 Thinking', '2025-11'], ['Kimi K2.5', '2026-01'], ['Kimi K2.6', '2026-04'], ['Kimi K3', '2026-07']],
    hf: 'https://huggingface.co/moonshotai',
    github: 'https://github.com/MoonshotAI',
    alternatives: ['deepseek', 'glm', 'kimi-vl'],
    source: 'https://huggingface.co/moonshotai/Kimi-K3',
    verified: true,
  },
  {
    id: 'glm',
    name: 'GLM (ChatGLM)',
    developer: 'Zhipu AI (Z.ai)', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-03', latest: '2026-08',
    sizes: '1.5B – 744B-A40B',
    license: 'GLM-4.5 – GLM-5.2 и GLM-5.3-Flash — MIT; GLM-5.3 — собственная лицензия (API-провайдерам с выручкой от 10 млрд $ нужна проверка Z.ai); ранние ChatGLM и GLM-4-9B — своя лицензия с регистрацией',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Одна из старейших китайских открытых линий: от ChatGLM-6B до GLM-5.3. Сильна в агентных задачах и программировании; GLM-5.3-Flash понимает картинки и выходит под MIT.',
    tasks: ['Корпоративный чат-ассистент', 'Агенты для рутинных офисных задач', 'Помощь программистам', 'Работа с длинными документами'],
    where: ['ИТ-отдел', 'Поддержка клиентов', 'Документооборот', 'Образование'],
    versions: [['ChatGLM-6B', '2023-03'], ['ChatGLM3-6B', '2023-10'], ['GLM-4-9B', '2024-06'], ['GLM-4-32B-0414', '2025-04'], ['GLM-4.5 / 4.5-Air', '2025-07'], ['GLM-4.7', '2025-12'], ['GLM-5', '2026-02'], ['GLM-5.3 / 5.3-Flash', '2026-08']],
    hf: 'https://huggingface.co/zai-org',
    github: 'https://github.com/zai-org',
    alternatives: ['deepseek', 'kimi', 'minimax'],
    source: 'https://huggingface.co/zai-org/GLM-5.3',
    verified: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    developer: 'MiniMax', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2025-01', latest: '2026-06',
    sizes: '230B-A10B – 456B-A46B',
    license: 'Смешанная: M1 — Apache 2.0; M2 и M2.5 — модифицированная MIT; M2.7 — только некоммерческая; M3 — MiniMax Community License (при коммерции уведомить MiniMax, от 20 млн $ выручки в год — отдельное разрешение)',
    commercial: 'conditional',
    hardware: ['multi'],
    summary: 'Крупные MoE-модели с очень длинным контекстом (до 1 млн токенов у Text-01 и M3). M3 — мультимодальная, понимает картинки. Лицензии сильно различаются от версии к версии.',
    tasks: ['Анализ больших архивов документов за один запрос', 'Агенты с инструментами', 'Помощь программистам', 'Диалоговые персонажи и сценарии'],
    where: ['Юристы', 'Аналитика', 'ИТ-разработка', 'Контент и развлечения'],
    versions: [['MiniMax-Text-01', '2025-01'], ['MiniMax-M1', '2025-06'], ['MiniMax-M2', '2025-10'], ['MiniMax-M2.1', '2025-12'], ['MiniMax-M2.5', '2026-02'], ['MiniMax-M2.7', '2026-04'], ['MiniMax-M3', '2026-06']],
    hf: 'https://huggingface.co/MiniMaxAI',
    github: 'https://github.com/MiniMax-AI',
    alternatives: ['glm', 'kimi', 'deepseek'],
    source: 'https://huggingface.co/MiniMaxAI/MiniMax-M3',
    verified: true,
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan / Hy',
    developer: 'Tencent', country: 'Китай',
    modality: ['text'],
    first: '2024-11', latest: '2026-08',
    sizes: '0.5B – 770B-A49B',
    license: 'Hy3 и Hy4-preview — Apache 2.0; Hunyuan-Large, A13B и малые модели 2025 года — Tencent Hunyuan Community License, не действует в ЕС, Великобритании и Южной Корее',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Языковые модели Tencent: от малых 0.5B–7B до Hy4-preview на 770 млрд параметров. С 2026 года линия переименована в Hy, а новые версии вышли под Apache 2.0.',
    tasks: ['Корпоративный ассистент', 'Перевод и работа с многоязычными текстами', 'Агенты с инструментами', 'Малые модели для работы на ноутбуке'],
    where: ['Поддержка клиентов', 'Внешнеэкономическая деятельность', 'ИТ-отдел', 'Медиа'],
    versions: [['Hunyuan-Large', '2024-11'], ['Hunyuan-7B', '2025-01'], ['Hunyuan-A13B', '2025-06'], ['Hunyuan 0.5B–7B', '2025-07'], ['Hy3-preview', '2026-04'], ['Hy3', '2026-07'], ['Hy4-preview', '2026-08']],
    hf: 'https://huggingface.co/tencent',
    github: 'https://github.com/Tencent-Hunyuan',
    alternatives: ['qwen', 'deepseek', 'ernie'],
    source: 'https://huggingface.co/tencent/Hy4-preview',
    verified: true,
  },
  {
    id: 'yi',
    name: 'Yi',
    developer: '01.AI', country: 'Китай',
    modality: ['text'],
    first: '2023-11', latest: '2024-05',
    sizes: '6B – 34B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Двуязычные (английский и китайский) модели 01.AI на 6–34B с версиями на контекст до 200 тыс. токенов. Новых открытых выпусков с 2024 года нет.',
    tasks: ['Чат-ассистент на одной видеокарте', 'Разбор длинных документов', 'Классификация и извлечение данных из текста'],
    where: ['Поддержка клиентов', 'Документооборот', 'Исследования'],
    versions: [['Yi-6B / 34B', '2023-11'], ['Yi-9B', '2024-03'], ['Yi-1.5', '2024-05']],
    hf: 'https://huggingface.co/01-ai',
    github: 'https://github.com/01-ai/Yi',
    alternatives: ['qwen', 'internlm', 'baichuan'],
    source: 'https://huggingface.co/01-ai/Yi-1.5-34B-Chat',
    verified: true,
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    developer: 'Baichuan Intelligence', country: 'Китай',
    modality: ['text'],
    first: '2023-06', latest: '2026-01',
    sizes: '7B – 235B-A22B',
    license: 'Baichuan-M2 и M3 — Apache 2.0; Baichuan 1/2 — собственная лицензия (коммерция по заявке)',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Сначала универсальные китайские модели, с 2025 года — медицинская линия. Baichuan-M3 (на основе Qwen3-235B) обучена моделировать ход клинического рассуждения врача.',
    tasks: ['Справочный помощник врача', 'Предварительный опрос пациента', 'Разбор медицинских документов', 'Обучение медперсонала'],
    where: ['Клиники', 'Телемедицина', 'Фарма', 'Медицинское страхование'],
    versions: [['Baichuan-7B', '2023-06'], ['Baichuan-13B', '2023-07'], ['Baichuan 2', '2023-08'], ['Baichuan-M1-14B', '2025-01'], ['Baichuan-M2-32B', '2025-08'], ['Baichuan-M3-235B', '2026-01']],
    hf: 'https://huggingface.co/baichuan-inc',
    github: 'https://github.com/baichuan-inc',
    alternatives: ['qwen', 'yi', 'internlm'],
    source: 'https://huggingface.co/baichuan-inc/Baichuan-M3-235B',
    verified: true,
  },
  {
    id: 'internlm',
    name: 'InternLM / Intern-S',
    developer: 'Shanghai AI Laboratory', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-07', latest: '2026-09',
    sizes: '1.8B – около 1T',
    license: 'InternLM3 и Intern-S1/S2 — Apache 2.0; InternLM2 и 2.5 — собственная лицензия, коммерция по бесплатной заявке',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Модели Шанхайской лаборатории ИИ. Ранняя линия InternLM — универсальная, новая Intern-S1/S2 — научная: понимает формулы, молекулы, графики и картинки.',
    tasks: ['Помощник исследователя: статьи, формулы, данные', 'Разбор научных и технических документов', 'Корпоративный чат на малых моделях'],
    where: ['НИИ и R&D', 'Химия и фарма', 'Инженерные отделы', 'Образование'],
    versions: [['InternLM-7B', '2023-07'], ['InternLM-20B', '2023-09'], ['InternLM2', '2024-01'], ['InternLM2.5', '2024-06'], ['InternLM3-8B', '2025-01'], ['Intern-S1', '2025-07'], ['Intern-S1-Pro', '2026-02'], ['Intern-S2-397B', '2026-09']],
    hf: 'https://huggingface.co/internlm',
    github: 'https://github.com/InternLM/InternLM',
    alternatives: ['qwen', 'internvl', 'deepseek'],
    source: 'https://huggingface.co/internlm/Intern-S2-397B',
    verified: true,
  },
  {
    id: 'step',
    name: 'Step',
    developer: 'StepFun', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2025-07', latest: '2026-05',
    sizes: '196B-A11B – 321B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['multi'],
    summary: 'MoE-модели StepFun, рассчитанные на быструю и дешёвую работу: при 196 млрд параметров Step-3.5/3.7-Flash задействуют около 11 млрд на токен. Step-3.7-Flash понимает картинки.',
    tasks: ['Агенты с высокой нагрузкой', 'Разбор документов со схемами и скриншотами', 'Помощь программистам'],
    where: ['ИТ-разработка', 'Поддержка клиентов', 'Операционные отделы'],
    versions: [['Step3', '2025-07'], ['Step-3.5-Flash', '2026-02'], ['Step-3.7-Flash', '2026-05']],
    hf: 'https://huggingface.co/stepfun-ai',
    github: 'https://github.com/stepfun-ai',
    alternatives: ['minimax', 'mimo', 'longcat'],
    source: 'https://huggingface.co/stepfun-ai/Step-3.7-Flash',
    verified: true,
  },
  {
    id: 'ling',
    name: 'Ling / Ring',
    developer: 'Ant Group (inclusionAI)', country: 'Китай',
    modality: ['text'],
    first: '2025-02', latest: '2026-08',
    sizes: '7.9B-A1.3B – 1T',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Семейство Ant Group: Ling — обычные модели, Ring — рассуждающие. Есть и триллионные флагманы, и экономичная Ling-3.0-tiny, которой хватает 1,3 млрд активных параметров.',
    tasks: ['Корпоративный ассистент', 'Агенты для офисных процессов', 'Финансовая аналитика (есть версия Fin)', 'Лёгкая модель для ноутбука'],
    where: ['Финансы и банки', 'Поддержка клиентов', 'ИТ-отдел'],
    versions: [['Ling-lite / Ling-plus', '2025-02'], ['Ling 2.0 (mini, flash)', '2025-09'], ['Ling-1T / Ring-1T', '2025-10'], ['Ling-2.5-1T', '2026-02'], ['Ling-2.6', '2026-04'], ['Ling-3.0-flash / tiny', '2026-08']],
    hf: 'https://huggingface.co/inclusionAI',
    github: 'https://github.com/inclusionAI/Ling-V2',
    alternatives: ['qwen', 'deepseek', 'longcat'],
    source: 'https://huggingface.co/inclusionAI/Ling-3.0-flash',
    verified: true,
  },
  {
    id: 'longcat',
    name: 'LongCat',
    developer: 'Meituan', country: 'Китай',
    modality: ['text'],
    first: '2025-08', latest: '2026-07',
    sizes: '69B – 1.6T-A48B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    summary: 'Модели Meituan (крупнейший сервис доставки Китая). LongCat-Flash динамически меняет объём вычислений под сложность запроса; LongCat-2.0 — 1,6 трлн параметров под MIT.',
    tasks: ['Агенты для заказов и сервисных процессов', 'Корпоративный ассистент', 'Разбор длинных документов'],
    where: ['Ритейл и доставка', 'Поддержка клиентов', 'Логистика'],
    versions: [['LongCat-Flash-Chat', '2025-08'], ['LongCat-Flash-Thinking', '2025-09'], ['LongCat-Flash-Lite', '2026-01'], ['LongCat-2.0', '2026-07']],
    hf: 'https://huggingface.co/meituan-longcat',
    github: 'https://github.com/meituan-longcat',
    alternatives: ['deepseek', 'ling', 'mimo'],
    source: 'https://huggingface.co/meituan-longcat/LongCat-2.0',
    verified: true,
  },
  {
    id: 'mimo',
    name: 'MiMo',
    developer: 'Xiaomi', country: 'Китай',
    modality: ['text'],
    first: '2025-04', latest: '2026-09',
    sizes: '7B – 1T-A42B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'multi'],
    summary: 'Модели Xiaomi для рассуждений и агентов: от компактной MiMo-7B до MiMo-V2.6-Pro на 1 трлн параметров. Flash-версии задействуют всего 15 млрд параметров на токен.',
    tasks: ['Логические и расчётные задачи', 'Агенты с инструментами', 'Помощь программистам'],
    where: ['ИТ-разработка', 'Аналитика', 'Производство электроники'],
    versions: [['MiMo-7B', '2025-04'], ['MiMo-V2-Flash', '2025-12'], ['MiMo-V2.5 / V2.5-Pro', '2026-04'], ['MiMo-V2.6-Flash / Pro', '2026-09']],
    hf: 'https://huggingface.co/XiaomiMiMo',
    github: 'https://github.com/XiaomiMiMo',
    alternatives: ['step', 'longcat', 'deepseek'],
    source: 'https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Pro-RL',
    verified: true,
  },
  {
    id: 'ernie',
    name: 'ERNIE 4.5',
    developer: 'Baidu', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2025-06', latest: '2025-09',
    sizes: '0.3B – 300B-A47B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Первая открытая линия Baidu: от крошечной 0.3B до MoE на 300 млрд параметров, есть версии с пониманием картинок. Средняя 21B-A3B помещается на одну видеокарту.',
    tasks: ['Корпоративный ассистент', 'Разбор документов и изображений', 'Классификация обращений'],
    where: ['Поддержка клиентов', 'Документооборот', 'Электронная коммерция'],
    versions: [['ERNIE 4.5 (0.3B, 21B-A3B, 300B-A47B)', '2025-06'], ['ERNIE-4.5-21B-A3B-Thinking', '2025-09']],
    hf: 'https://huggingface.co/baidu',
    github: 'https://github.com/PaddlePaddle/ERNIE',
    alternatives: ['qwen', 'hunyuan', 'glm'],
    source: 'https://huggingface.co/baidu/ERNIE-4.5-21B-A3B-Thinking',
    verified: true,
  },
  {
    id: 'seed-oss',
    name: 'Seed-OSS',
    developer: 'ByteDance', country: 'Китай',
    modality: ['text'],
    first: '2025-08', latest: '2025-08',
    sizes: '36B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Открытая модель ByteDance на 36B с контекстом до 512 тыс. токенов и настраиваемым «бюджетом размышлений». Помещается на одну мощную видеокарту.',
    tasks: ['Разбор длинных документов', 'Агенты с инструментами', 'Корпоративный ассистент'],
    where: ['Юристы', 'Аналитика', 'ИТ-отдел'],
    versions: [['Seed-OSS-36B', '2025-08']],
    hf: 'https://huggingface.co/ByteDance-Seed/Seed-OSS-36B-Instruct',
    github: 'https://github.com/ByteDance-Seed/seed-oss',
    alternatives: ['qwen', 'glm', 'gemma'],
    source: 'https://huggingface.co/ByteDance-Seed/Seed-OSS-36B-Instruct',
    verified: true,
  },
  {
    id: 'exaone',
    name: 'EXAONE',
    developer: 'LG AI Research', country: 'Южная Корея',
    modality: ['text', 'vlm'],
    first: '2024-07', latest: '2026-07',
    sizes: '1.2B – 750B-A37B',
    license: 'Смешанная: EXAONE 3.0–4.5 — только некоммерческая; K-EXAONE 236B — своя лицензия (коммерция разрешена, распространение третьим лицам по договору); K-EXAONE 2.0 — Apache 2.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Корейско-английские модели LG. Большая часть линии некоммерческая, но флагман K-EXAONE 2.0 на 750 млрд параметров вышел под Apache 2.0.',
    tasks: ['Корпоративный ассистент', 'Работа с корейскими и английскими текстами', 'Разбор документов и картинок (4.5)'],
    where: ['Производство', 'Работа с корейскими партнёрами', 'Исследования'],
    versions: [['EXAONE 3.0', '2024-07'], ['EXAONE 3.5', '2024-12'], ['EXAONE Deep', '2025-03'], ['EXAONE 4.0', '2025-07'], ['K-EXAONE 236B', '2025-12'], ['EXAONE 4.5', '2026-04'], ['K-EXAONE 2.0', '2026-07']],
    hf: 'https://huggingface.co/LGAI-EXAONE',
    github: 'https://github.com/LG-AI-EXAONE',
    alternatives: ['solar', 'kanana', 'hyperclova'],
    source: 'https://huggingface.co/LGAI-EXAONE/K-EXAONE-2.0-750B-A37B',
    verified: true,
  },
  {
    id: 'solar',
    name: 'Solar',
    developer: 'Upstage', country: 'Южная Корея',
    modality: ['text'],
    first: '2023-12', latest: '2026-07',
    sizes: '10.7B – 250B-A15B',
    license: 'SOLAR-10.7B — Apache 2.0; Solar Open и Open 2 — Upstage Solar License (на основе Apache 2.0: коммерция разрешена, но название дообученной модели должно начинаться с Solar, плюс пометка Built with Solar)',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    summary: 'Модели корейской Upstage. Solar Open 2 рассчитана на офисную работу с документами: 250 млрд параметров, из них активны 15 млрд, языки — английский, корейский, японский.',
    tasks: ['Работа с офисными документами', 'Агенты для рутинных задач', 'Помощь программистам'],
    where: ['Документооборот', 'Бэк-офис', 'Работа с корейскими и японскими партнёрами'],
    versions: [['SOLAR-10.7B', '2023-12'], ['Solar Pro Preview', '2024-09'], ['Solar Open 100B', '2025-12'], ['Solar Open 2 250B', '2026-07']],
    hf: 'https://huggingface.co/upstage',
    github: null,
    alternatives: ['exaone', 'kanana', 'mistral'],
    source: 'https://huggingface.co/upstage/Solar-Open2-250B',
    verified: true,
  },
  {
    id: 'kanana',
    name: 'Kanana',
    developer: 'Kakao', country: 'Южная Корея',
    modality: ['text'],
    first: '2025-02', latest: '2026-07',
    sizes: '1.3B – 30B-A3B',
    license: 'Kanana 1.5 — Apache 2.0; Kanana 2 — собственная лицензия Kakao (компаниям с аудиторией свыше 10 млн пользователей в месяц нужна отдельная лицензия); Kanana Nano — CC-BY-NC',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Компактные корейско-английские модели Kakao. Kanana 2 30B-A3B работает быстро за счёт MoE, малые версии на 1–3B подходят для обычного ПК.',
    tasks: ['Чат-бот поддержки', 'Классификация обращений', 'Лёгкий ассистент на своём ПК'],
    where: ['Поддержка клиентов', 'Мессенджеры и сервисы', 'Работа с корейскими партнёрами'],
    versions: [['Kanana Nano 2.1B', '2025-02'], ['Kanana 1.5 (2.1B, 8B)', '2025-04'], ['Kanana 1.5 15.7B-A3B', '2025-07'], ['Kanana 2 30B-A3B', '2025-12'], ['Kanana 2 1.3B / 3B', '2026-07']],
    hf: 'https://huggingface.co/kakaocorp',
    github: 'https://github.com/kakao/kanana',
    alternatives: ['exaone', 'hyperclova', 'solar'],
    source: 'https://huggingface.co/kakaocorp/kanana-2-3b-instruct',
    verified: true,
  },
  {
    id: 'hyperclova',
    name: 'HyperCLOVA X SEED',
    developer: 'Naver', country: 'Южная Корея',
    modality: ['text', 'vlm'],
    first: '2025-04', latest: '2025-12',
    sizes: '0.5B – 32B',
    license: 'Собственная лицензия HyperCLOVA X SEED с дополнительными коммерческими условиями',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Открытые младшие модели корейского Naver: от 0.5B до 32B, включая рассуждающие Think и мультимодальные версии с пониманием картинок.',
    tasks: ['Лёгкий корейско-английский ассистент', 'Разбор картинок и документов', 'Классификация текстов'],
    where: ['Работа с корейскими партнёрами', 'Поддержка клиентов', 'Медиа'],
    versions: [['SEED 0.5B / 1.5B / Vision 3B', '2025-04'], ['SEED Think 14B', '2025-07'], ['SEED Think 32B / Omni 8B', '2025-12']],
    hf: 'https://huggingface.co/naver-hyperclovax',
    github: null,
    alternatives: ['exaone', 'kanana', 'solar'],
    source: 'https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-32B',
    verified: true,
  },
  {
    id: 'gigachat',
    name: 'GigaChat',
    developer: 'Сбер', country: 'Россия',
    modality: ['text'],
    first: '2024-12', latest: '2026-09',
    sizes: '10B-A1.8B – 702B-A36B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Открытые модели Сбера, обученные с упором на русский язык: хорошо пишут и понимают по-русски, знают местные реалии. Есть лёгкая 10B-A1.8B и флагманы до 702B, всё под MIT.',
    tasks: ['Русскоязычный ассистент для сотрудников на своём сервере', 'Ответы клиентам и разбор обращений на русском', 'Работа с договорами и внутренними регламентами', 'Составление писем и отчётов'],
    where: ['Банки и финансы', 'Госсектор и компании с требованиями к хранению данных в РФ', 'Поддержка клиентов', 'Юристы и HR'],
    versions: [['GigaChat 20B-A3B', '2024-12'], ['GigaChat3 10B-A1.8B', '2025-11'], ['GigaChat3.1 (10B, 702B)', '2026-03'], ['GigaChat3.5 432B-A28B', '2026-07'], ['GigaChat3.5 Reasoning', '2026-09']],
    hf: 'https://huggingface.co/ai-sage',
    github: 'https://github.com/salute-developers/gigachat3',
    alternatives: ['yandexgpt', 't-pro', 'giga-embeddings'],
    source: 'https://huggingface.co/ai-sage/GigaChat3.5-432B-A28B-Reasoning',
    verified: true,
  },
  {
    id: 'yandexgpt',
    name: 'YandexGPT / AliceAI',
    developer: 'Яндекс', country: 'Россия',
    modality: ['text'],
    first: '2022-06', latest: '2026-09',
    sizes: '8B – 100B',
    license: 'YaLM-100B и AliceAI-Foundation — Apache 2.0; YandexGPT-5-Lite — собственное лицензионное соглашение Яндекса, коммерция на его условиях',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Модели Яндекса, обученные с нуля с упором на русский язык и российские реалии. Новая AliceAI-Foundation 80B-A3B — базовая модель под Apache 2.0, её дообучают под свои задачи.',
    tasks: ['Русскоязычный ассистент и чат-бот', 'Ответы на вопросы по базе знаний компании', 'Основа для дообучения под свою отрасль', 'Тексты и письма на русском'],
    where: ['Поддержка клиентов', 'Ритейл и сервисы', 'Компании с требованием хранить данные в РФ', 'Медиа'],
    versions: [['YaLM-100B', '2022-06'], ['YandexGPT-5-Lite-8B', '2025-02'], ['AliceAI-Foundation-80B-A3B-Base', '2026-09']],
    hf: 'https://huggingface.co/yandex',
    github: null,
    alternatives: ['gigachat', 't-pro', 'vikhr'],
    source: 'https://huggingface.co/yandex/AliceAI-Foundation-80B-A3B-Base',
    verified: true,
  },
  {
    id: 't-pro',
    name: 'T-Pro / T-Lite',
    developer: 'Т-Банк', country: 'Россия',
    modality: ['text'],
    first: '2024-12', latest: '2025-12',
    sizes: '7B – 32B',
    license: 'Apache 2.0 (версии 2.0 и 2.1; основа — Qwen)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Модели Т-Банка, дообученные на основе Qwen специально для русского языка: заметно лучше исходной модели пишут и рассуждают по-русски. T-Lite — 8B, T-Pro — 32B на одну видеокарту.',
    tasks: ['Русскоязычный чат-бот поддержки', 'Разбор обращений и документов на русском', 'Ответы по базе знаний компании', 'Черновики писем и отчётов'],
    where: ['Банки и финтех', 'Поддержка клиентов', 'Юристы и HR', 'Ритейл'],
    versions: [['T-Lite / T-Pro 1.0', '2024-12'], ['T-Pro 2.0', '2025-07'], ['T-Lite / T-Pro 2.1', '2025-12']],
    hf: 'https://huggingface.co/t-tech',
    github: null,
    alternatives: ['gigachat', 'yandexgpt', 'qwen'],
    source: 'https://huggingface.co/t-tech/T-pro-it-2.1',
    verified: true,
  },
  {
    id: 'vikhr',
    name: 'Vikhr',
    developer: 'Vikhr Models', country: 'Россия',
    modality: ['text'],
    first: '2024-01', latest: '2025-09',
    sizes: '0.5B – 24B',
    license: 'Основные версии — Apache 2.0; отдельные дообучения наследуют лицензию базы (Llama, YandexGPT)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Русскоязычные дообучения открытых моделей (Mistral, Qwen, Llama) от независимой команды Vikhr: улучшают русский язык, есть компактные версии для обычного ПК.',
    tasks: ['Русскоязычный ассистент на своём ПК или сервере', 'Ответы по базе знаний (RAG)', 'Тексты и письма на русском'],
    where: ['Малый бизнес', 'Поддержка клиентов', 'Образование'],
    versions: [['Vikhr-7B', '2024-01'], ['Vikhr-Nemo-12B / Llama3.1-8B', '2024-09'], ['QVikhr-2.5-1.5B', '2025-01'], ['QVikhr-3 (1.7B–8B)', '2025-05'], ['Vistral-24B', '2025-09']],
    hf: 'https://huggingface.co/Vikhrmodels',
    github: 'https://github.com/VikhrModels',
    alternatives: ['t-pro', 'gigachat', 'yandexgpt'],
    source: 'https://huggingface.co/Vikhrmodels/Vistral-24B-Instruct',
    verified: true,
  },
];
