// Языковые модели Китая, Кореи и России (text-east). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    developer: 'DeepSeek', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-11', latest: '2026-09',
    sizes: '7B – 1.6T-A49B',
    license: 'MIT (V2 и ранние версии — собственная лицензия DeepSeek с запретами на вредное использование)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown', industries: ['legal', 'finance', 'support', 'dev'], ollama: true, cpu: false,
    summary: 'Флагманская линия DeepSeek: от первых 7B/67B до V4-Pro на 1,6 трлн параметров. Уровень закрытых моделей при открытой MIT-лицензии; картинки понимают V4-Flash-Vision-Exp и V4.1-Flash, контекст до 1 млн токенов.',
    tasks: ['Ассистент для сотрудников на своём сервере', 'Разбор длинных договоров и отчётов', 'Агенты, которые работают с инструментами и API', 'Помощь программистам'],
    where: ['Юристы и финансы', 'Поддержка клиентов', 'ИТ-отдел', 'Аналитика'],
    versions: [['DeepSeek LLM 7B / 67B', '2023-11'], ['DeepSeek-MoE 16B', '2024-01'], ['DeepSeek-V2', '2024-04'], ['DeepSeek-V2.5', '2024-09'], ['DeepSeek-V3', '2024-12'], ['DeepSeek-V3.1', '2025-08'], ['DeepSeek-V3.2', '2025-12'], ['DeepSeek-V4-Pro / V4-Flash', '2026-04'], ['DeepSeek-V4-Flash-0731', '2026-07'], ['DeepSeek-V4-Pro-0813 / V4-Flash-Vision-Exp', '2026-08'], ['DeepSeek-V4.1-Flash', '2026-09']],
    hf: 'https://huggingface.co/deepseek-ai',
    github: 'https://github.com/deepseek-ai',
    alternatives: ['deepseek-r1', 'kimi', 'glm'],
    source: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash',
    verified: true,
    en: {
      summary: 'DeepSeek\'s flagship line: from the first 7B/67B to V4-Pro with 1.6 trillion parameters. Closed-model quality under an open MIT license; V4-Flash-Vision-Exp and V4.1-Flash understand images, context up to 1M tokens.',
      tasks: ['Employee assistant on your own server', 'Analysis of long contracts and reports', 'Agents that work with tools and APIs', 'Help for developers'],
      where: ['Legal and finance', 'Customer support', 'IT department', 'Analytics'],
      license: 'MIT (V2 and earlier versions: DeepSeek\'s own license prohibiting harmful use)',
      country: 'China',
    },
  },
  {
    id: 'kimi',
    name: 'Kimi',
    developer: 'Moonshot AI', country: 'Китай',
    modality: ['text', 'vlm', 'code'],
    first: '2025-02', latest: '2026-07',
    sizes: '16B-A3B – 2.8T-A104B',
    license: 'K2–K2.7-Code — модифицированная MIT (при 100 млн пользователей или 20 млн $ выручки в месяц нужно указать Kimi в интерфейсе); K3 — собственная Kimi K3 License: API-бизнесу с выручкой от 20 млн $ в год нужен отдельный договор',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    ru: 'unknown', industries: ['dev', 'science', 'finance'], ollama: false, cpu: false,
    summary: 'Сверхкрупные MoE-модели Moonshot для агентной работы. K3 на 2,8 трлн параметров — самая большая открытая модель на момент выхода, с контекстом до 1 млн токенов и пониманием картинок; K2.7-Code заточена под программирование.',
    tasks: ['Многошаговые агенты: поиск, сбор данных, отчёты', 'Глубокий анализ документов', 'Помощь программистам', 'Разбор скриншотов и таблиц'],
    where: ['Аналитические отделы', 'ИТ-разработка', 'Консалтинг', 'Маркетинг-исследования'],
    versions: [['Moonlight 16B-A3B', '2025-02'], ['Kimi K2', '2025-07'], ['Kimi Linear 48B-A3B', '2025-10'], ['Kimi K2 Thinking', '2025-11'], ['Kimi K2.5', '2026-01'], ['Kimi K2.6', '2026-04'], ['Kimi K2.7-Code 1T-A32B', '2026-06'], ['Kimi K3', '2026-07']],
    hf: 'https://huggingface.co/moonshotai',
    github: 'https://github.com/MoonshotAI',
    alternatives: ['deepseek', 'glm', 'kimi-vl'],
    source: 'https://huggingface.co/moonshotai/Kimi-K3',
    verified: true,
    en: {
      summary: 'Very large Moonshot MoE models for agentic work. K3 (2.8 trillion parameters) was the largest open model at release, with up to 1M tokens of context and image understanding; K2.7-Code is built for programming.',
      tasks: ['Multi-step agents: search, data collection, reports', 'In-depth document analysis', 'Help for developers', 'Analysis of screenshots and spreadsheets'],
      where: ['Analytics departments', 'Software development', 'Consulting', 'Market research'],
      license: 'K2–K2.7-Code: modified MIT (at 100 million users or $20 million monthly revenue, Kimi must be credited in the interface); K3: own Kimi K3 License, API businesses with revenue from $20 million a year need a separate agreement',
      country: 'China',
    },
  },
  {
    id: 'glm',
    name: 'GLM (ChatGLM)',
    developer: 'Zhipu AI (Z.ai)', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-03', latest: '2026-08',
    sizes: '1.5B – 744B-A40B',
    license: 'GLM-4.5 – GLM-5.2 и GLM-5.3-Flash — MIT; GLM-5.3 — собственная лицензия (API-провайдерам с выручкой от 10 млрд $ нужна проверка Z.ai); ранние ChatGLM и GLM-4-9B — своя лицензия с регистрацией',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no', industries: ['dev', 'support', 'docs', 'education'], ollama: true, cpu: true,
    summary: 'Одна из старейших китайских открытых линий: от ChatGLM-6B до GLM-5.3. Сильна в агентных задачах и программировании; GLM-5.3-Flash понимает картинки и выходит под MIT.',
    tasks: ['Корпоративный чат-ассистент', 'Агенты для рутинных офисных задач', 'Помощь программистам', 'Работа с длинными документами'],
    where: ['ИТ-отдел', 'Поддержка клиентов', 'Документооборот', 'Образование'],
    versions: [['ChatGLM-6B', '2023-03'], ['ChatGLM3-6B', '2023-10'], ['GLM-4-9B', '2024-06'], ['GLM-4-32B-0414', '2025-04'], ['GLM-4.5 / 4.5-Air', '2025-07'], ['GLM-4.7', '2025-12'], ['GLM-4.7-Flash 30B-A3B', '2026-01'], ['GLM-5', '2026-02'], ['GLM-5.1', '2026-04'], ['GLM-5.2', '2026-06'], ['GLM-5.3 / 5.3-Flash', '2026-08']],
    hf: 'https://huggingface.co/zai-org',
    github: 'https://github.com/zai-org',
    alternatives: ['deepseek', 'kimi', 'minimax'],
    source: 'https://huggingface.co/zai-org/GLM-5.3',
    verified: true,
    en: {
      summary: 'One of the oldest Chinese open lines: from ChatGLM-6B to GLM-5.3. Strong at agentic tasks and programming; GLM-5.3-Flash understands images and is released under MIT.',
      tasks: ['Corporate chat assistant', 'Agents for routine office tasks', 'Help for developers', 'Working with long documents'],
      where: ['IT department', 'Customer support', 'Document management', 'Education'],
      license: 'GLM-4.5 – GLM-5.2 and GLM-5.3-Flash: MIT; GLM-5.3: own license (API providers with revenue from $10 billion need a review by Z.ai); early ChatGLM and GLM-4-9B: own license with registration',
      country: 'China',
    },
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    developer: 'MiniMax', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2025-01', latest: '2026-06',
    sizes: '230B-A10B – 456B-A46B',
    license: 'Смешанная: M1 — Apache 2.0; M2 и M2.5 — модифицированная MIT; M2.7 — только некоммерческая; M3 — MiniMax Community License (при коммерции уведомить MiniMax, от 20 млн $ выручки в год — отдельное разрешение)',
    commercial: 'conditional',
    hardware: ['multi'],
    ru: 'unknown', industries: ['legal', 'dev', 'finance', 'media'], ollama: false, cpu: false,
    summary: 'Крупные MoE-модели с очень длинным контекстом (до 1 млн токенов у Text-01 и M3). M3 — мультимодальная, понимает картинки. Лицензии сильно различаются от версии к версии.',
    tasks: ['Анализ больших архивов документов за один запрос', 'Агенты с инструментами', 'Помощь программистам', 'Диалоговые персонажи и сценарии'],
    where: ['Юристы', 'Аналитика', 'ИТ-разработка', 'Контент и развлечения'],
    versions: [['MiniMax-Text-01', '2025-01'], ['MiniMax-M1', '2025-06'], ['MiniMax-M2', '2025-10'], ['MiniMax-M2.1', '2025-12'], ['MiniMax-M2.5', '2026-02'], ['MiniMax-M2.7', '2026-04'], ['MiniMax-M3', '2026-06']],
    hf: 'https://huggingface.co/MiniMaxAI',
    github: 'https://github.com/MiniMax-AI',
    alternatives: ['glm', 'kimi', 'deepseek'],
    source: 'https://huggingface.co/MiniMaxAI/MiniMax-M3',
    verified: true,
    en: {
      summary: 'Large MoE models with very long context (up to 1M tokens for Text-01 and M3). M3 is multimodal and understands images. Licenses differ greatly from version to version.',
      tasks: ['Analysis of large document archives in a single request', 'Agents with tools', 'Help for developers', 'Conversational characters and scenarios'],
      where: ['Lawyers', 'Analytics', 'Software development', 'Content and entertainment'],
      license: 'Mixed: M1: Apache 2.0; M2 and M2.5: modified MIT; M2.7: non-commercial only; M3: MiniMax Community License (notify MiniMax for commercial use; from $20 million annual revenue, separate permission is required)',
      country: 'China',
    },
  },
  {
    id: 'hunyuan',
    name: 'Hunyuan / Hy',
    developer: 'Tencent', country: 'Китай',
    modality: ['text'],
    first: '2024-11', latest: '2026-08',
    sizes: '0.5B – 770B-A49B',
    license: 'Hy3 и Hy4-preview — Apache 2.0; Hunyuan-Large, A13B и малые модели 2025 года — Tencent Hunyuan Community License, не действует в ЕС, Великобритании и Южной Корее',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown', industries: ['support', 'dev', 'media'], ollama: false, cpu: true,
    summary: 'Языковые модели Tencent: от малых 0.5B–7B до Hy4-preview на 770 млрд параметров. С 2026 года линия переименована в Hy, а новые версии вышли под Apache 2.0.',
    tasks: ['Корпоративный ассистент', 'Перевод и работа с многоязычными текстами', 'Агенты с инструментами', 'Малые модели для работы на ноутбуке'],
    where: ['Поддержка клиентов', 'Внешнеэкономическая деятельность', 'ИТ-отдел', 'Медиа'],
    versions: [['Hunyuan-Large', '2024-11'], ['Hunyuan-7B', '2025-01'], ['Hunyuan-A13B', '2025-06'], ['Hunyuan 0.5B–7B', '2025-07'], ['Hy3-preview', '2026-04'], ['Hy3', '2026-07'], ['Hy4-preview', '2026-08']],
    hf: 'https://huggingface.co/tencent',
    github: 'https://github.com/Tencent-Hunyuan',
    alternatives: ['qwen', 'deepseek', 'ernie'],
    source: 'https://huggingface.co/tencent/Hy4-preview',
    verified: true,
    en: {
      summary: 'Tencent language models: from small 0.5B–7B to Hy4-preview with 770 billion parameters. Since 2026 the line has been renamed Hy, and new versions are released under Apache 2.0.',
      tasks: ['Corporate assistant', 'Translation and multilingual texts', 'Agents with tools', 'Small models for a laptop'],
      where: ['Customer support', 'International trade', 'IT department', 'Media'],
      license: 'Hy3 and Hy4-preview: Apache 2.0; Hunyuan-Large, A13B and the 2025 small models: Tencent Hunyuan Community License, not valid in the EU, UK and South Korea',
      country: 'China',
    },
  },
  {
    id: 'yi',
    name: 'Yi',
    developer: '01.AI', country: 'Китай',
    modality: ['text'],
    first: '2023-11', latest: '2024-05',
    sizes: '6B – 34B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no', industries: ['support', 'docs', 'science'], ollama: true, cpu: false,
    summary: 'Двуязычные (английский и китайский) модели 01.AI на 6–34B с версиями на контекст до 200 тыс. токенов. Новых открытых выпусков с 2024 года нет.',
    tasks: ['Чат-ассистент на одной видеокарте', 'Разбор длинных документов', 'Классификация и извлечение данных из текста'],
    where: ['Поддержка клиентов', 'Документооборот', 'Исследования'],
    versions: [['Yi-6B / 34B', '2023-11'], ['Yi-9B', '2024-03'], ['Yi-1.5', '2024-05']],
    hf: 'https://huggingface.co/01-ai',
    github: 'https://github.com/01-ai/Yi',
    alternatives: ['qwen', 'internlm', 'baichuan'],
    source: 'https://huggingface.co/01-ai/Yi-1.5-34B-Chat',
    verified: true,
    en: {
      summary: 'Bilingual (English and Chinese) 01.AI models of 6–34B, with versions supporting up to 200K tokens of context. No new open releases since 2024.',
      tasks: ['Chat assistant on a single GPU', 'Analysis of long documents', 'Classification and data extraction from text'],
      where: ['Customer support', 'Document management', 'Research'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    developer: 'Baichuan Intelligence', country: 'Китай',
    modality: ['text'],
    first: '2023-06', latest: '2026-01',
    sizes: '7B – 235B-A22B',
    license: 'Baichuan-M2 и M3 — Apache 2.0; Baichuan 1/2 — собственная лицензия (коммерция по заявке)',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no', industries: ['medical'], ollama: false, cpu: false,
    summary: 'Сначала универсальные китайские модели, с 2025 года — медицинская линия. Baichuan-M3 (на основе Qwen3-235B) обучена моделировать ход клинического рассуждения врача.',
    tasks: ['Справочный помощник врача', 'Предварительный опрос пациента', 'Разбор медицинских документов', 'Обучение медперсонала'],
    where: ['Клиники', 'Телемедицина', 'Фарма', 'Медицинское страхование'],
    versions: [['Baichuan-7B', '2023-06'], ['Baichuan-13B', '2023-07'], ['Baichuan 2', '2023-08'], ['Baichuan-M1-14B', '2025-01'], ['Baichuan-M2-32B', '2025-08'], ['Baichuan-M3-235B', '2026-01']],
    hf: 'https://huggingface.co/baichuan-inc',
    github: 'https://github.com/baichuan-inc',
    alternatives: ['qwen', 'yi', 'internlm'],
    source: 'https://huggingface.co/baichuan-inc/Baichuan-M3-235B',
    verified: true,
    en: {
      summary: 'First general-purpose Chinese models, then a medical line from 2025. Baichuan-M3 (based on Qwen3-235B) is trained to model a doctor\'s clinical reasoning.',
      tasks: ['Reference assistant for doctors', 'Preliminary patient intake questions', 'Analysis of medical documents', 'Training medical staff'],
      where: ['Clinics', 'Telemedicine', 'Pharma', 'Health insurance'],
      license: 'Baichuan-M2 and M3: Apache 2.0; Baichuan 1/2: own license (commercial use on application)',
      country: 'China',
    },
  },
  {
    id: 'internlm',
    name: 'InternLM / Intern-S',
    developer: 'Shanghai AI Laboratory', country: 'Китай',
    modality: ['text', 'vlm'],
    first: '2023-07', latest: '2026-09',
    sizes: '1.8B – около 1T',
    license: 'InternLM3 и Intern-S1/S2 — Apache 2.0; InternLM2 и 2.5 — собственная лицензия, коммерция по бесплатной заявке',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown', industries: ['science', 'education', 'dev'], ollama: true, cpu: true,
    summary: 'Модели Шанхайской лаборатории ИИ. Ранняя линия InternLM — универсальная, новая Intern-S1/S2 — научная: понимает формулы, молекулы, графики и картинки.',
    tasks: ['Помощник исследователя: статьи, формулы, данные', 'Разбор научных и технических документов', 'Корпоративный чат на малых моделях'],
    where: ['НИИ и R&D', 'Химия и фарма', 'Инженерные отделы', 'Образование'],
    versions: [['InternLM-7B', '2023-07'], ['InternLM-20B', '2023-09'], ['InternLM2', '2024-01'], ['InternLM2.5', '2024-06'], ['InternLM3-8B', '2025-01'], ['Intern-S1', '2025-07'], ['Intern-S1-Pro', '2026-02'], ['Intern-S2-397B', '2026-09']],
    hf: 'https://huggingface.co/internlm',
    github: 'https://github.com/InternLM/InternLM',
    alternatives: ['qwen', 'internvl', 'deepseek'],
    source: 'https://huggingface.co/internlm/Intern-S2-397B',
    verified: true,
    en: {
      summary: 'Models from Shanghai AI Laboratory. The early InternLM line is general-purpose; the new Intern-S1/S2 is scientific: it understands formulas, molecules, charts and images.',
      tasks: ['Research assistant: papers, formulas, data', 'Analysis of scientific and technical documents', 'Corporate chat on small models'],
      where: ['Research institutes and R&D', 'Chemistry and pharma', 'Engineering departments', 'Education'],
      license: 'InternLM3 and Intern-S1/S2: Apache 2.0; InternLM2 and 2.5: own license, commercial use via a free application',
      country: 'China',
      sizes: '1.8B – about 1T',
    },
  },
  {
    id: 'step',
    name: 'Step',
    developer: 'StepFun', country: 'Китай',
    modality: ['text', 'vlm', 'omni'],
    first: '2025-07', latest: '2026-05',
    sizes: '8B – 321B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'no', industries: ['dev', 'support', 'docs'], ollama: false, cpu: false,
    summary: 'MoE-модели StepFun, рассчитанные на быструю и дешёвую работу: при 196 млрд параметров Step-3.5/3.7-Flash задействуют около 11 млрд на токен. Есть компактные Step3-VL-10B для картинок и голосовая Step-Audio 2 mini.',
    tasks: ['Агенты с высокой нагрузкой', 'Разбор документов со схемами и скриншотами', 'Помощь программистам'],
    where: ['ИТ-разработка', 'Поддержка клиентов', 'Операционные отделы'],
    versions: [['Step3', '2025-07'], ['Step-Audio 2 mini 8B', '2025-08'], ['Step3-VL-10B', '2026-01'], ['Step-3.5-Flash', '2026-02'], ['Step-3.7-Flash', '2026-05']],
    hf: 'https://huggingface.co/stepfun-ai',
    github: 'https://github.com/stepfun-ai',
    alternatives: ['minimax', 'mimo', 'longcat'],
    source: 'https://huggingface.co/stepfun-ai/Step-3.7-Flash',
    verified: true,
    en: {
      summary: 'StepFun MoE models built for fast, low-cost work: with 196 billion parameters, Step-3.5/3.7-Flash use about 11 billion per token. Compact Step3-VL-10B for images and voice Step-Audio 2 mini are available.',
      tasks: ['High-load agents', 'Analysis of documents with diagrams and screenshots', 'Help for developers'],
      where: ['Software development', 'Customer support', 'Operations departments'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'ling',
    name: 'Ling / Ring',
    developer: 'Ant Group (inclusionAI)', country: 'Китай',
    modality: ['text'],
    first: '2025-02', latest: '2026-08',
    sizes: '7.9B-A1.3B – 1T',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown', industries: ['finance', 'support', 'dev'], ollama: false, cpu: true,
    summary: 'Семейство Ant Group: Ling — обычные модели, Ring — рассуждающие. Есть и триллионные флагманы, и экономичная Ling-3.0-tiny, которой хватает 1,3 млрд активных параметров.',
    tasks: ['Корпоративный ассистент', 'Агенты для офисных процессов', 'Финансовая аналитика (есть версия Fin)', 'Лёгкая модель для ноутбука'],
    where: ['Финансы и банки', 'Поддержка клиентов', 'ИТ-отдел'],
    versions: [['Ling-lite / Ling-plus', '2025-02'], ['Ling 2.0 (mini, flash)', '2025-09'], ['Ling-1T / Ring-1T', '2025-10'], ['Ling-2.5-1T', '2026-02'], ['Ling-2.6', '2026-04'], ['Ling-3.0-flash / tiny', '2026-08']],
    hf: 'https://huggingface.co/inclusionAI',
    github: 'https://github.com/inclusionAI/Ling-V2',
    alternatives: ['qwen', 'deepseek', 'longcat'],
    source: 'https://huggingface.co/inclusionAI/Ling-3.0-flash',
    verified: true,
    en: {
      summary: 'An Ant Group family: Ling for standard models, Ring for reasoning ones. There are trillion-parameter flagships and the efficient Ling-3.0-tiny, which needs only 1.3 billion active parameters.',
      tasks: ['Corporate assistant', 'Agents for office processes', 'Financial analytics (Fin version available)', 'Lightweight model for a laptop'],
      where: ['Finance and banking', 'Customer support', 'IT department'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'longcat',
    name: 'LongCat',
    developer: 'Meituan', country: 'Китай',
    modality: ['text', 'omni', 'tts'],
    first: '2025-08', latest: '2026-07',
    sizes: '1B – 1.6T-A48B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown', industries: ['retail', 'support', 'manufacturing'], ollama: false, cpu: false,
    summary: 'Модели Meituan (крупнейший сервис доставки Китая). LongCat-Flash динамически меняет объём вычислений под сложность запроса; LongCat-2.0 — 1,6 трлн параметров под MIT. Есть омни-модели (Flash-Omni, Next) и синтез речи AudioDiT.',
    tasks: ['Агенты для заказов и сервисных процессов', 'Корпоративный ассистент', 'Разбор длинных документов'],
    where: ['Ритейл и доставка', 'Поддержка клиентов', 'Логистика'],
    versions: [['LongCat-Flash-Chat', '2025-08'], ['LongCat-Flash-Thinking', '2025-09'], ['LongCat-Flash-Omni 560B-A27B', '2025-10'], ['LongCat-Flash-Lite', '2026-01'], ['LongCat-Next 74B-A3B / AudioDiT (1B, 3.5B)', '2026-03'], ['LongCat-2.0', '2026-07']],
    hf: 'https://huggingface.co/meituan-longcat',
    github: 'https://github.com/meituan-longcat',
    alternatives: ['deepseek', 'ling', 'mimo'],
    source: 'https://huggingface.co/meituan-longcat/LongCat-2.0',
    verified: true,
    en: {
      summary: 'Models from Meituan, China\'s largest delivery service. LongCat-Flash adjusts compute to query complexity; LongCat-2.0 has 1.6 trillion parameters under MIT. Omni models (Flash-Omni, Next) and AudioDiT speech synthesis too.',
      tasks: ['Agents for orders and service processes', 'Corporate assistant', 'Analysis of long documents'],
      where: ['Retail and delivery', 'Customer support', 'Logistics'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'mimo',
    name: 'MiMo',
    developer: 'Xiaomi', country: 'Китай',
    modality: ['text', 'vlm', 'omni', 'asr'],
    first: '2025-04', latest: '2026-09',
    sizes: '7B – 1T-A42B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'multi'],
    ru: 'no', industries: ['dev', 'science', 'finance'], ollama: false, cpu: false,
    summary: 'Модели Xiaomi для рассуждений и агентов: от компактной MiMo-7B до MiMo-V2.6-Pro на 1 трлн параметров. Есть MiMo-VL для картинок, голосовая MiMo-Audio и распознавание речи MiMo-V2.5-ASR (китайский и английский).',
    tasks: ['Логические и расчётные задачи', 'Агенты с инструментами', 'Помощь программистам'],
    where: ['ИТ-разработка', 'Аналитика', 'Производство электроники'],
    versions: [['MiMo-7B', '2025-04'], ['MiMo-VL-7B', '2025-05'], ['MiMo-Audio-7B', '2025-09'], ['MiMo-V2-Flash', '2025-12'], ['MiMo-V2.5 / V2.5-Pro / V2.5-ASR', '2026-04'], ['MiMo-V2.6-Flash / Pro', '2026-09']],
    hf: 'https://huggingface.co/XiaomiMiMo',
    github: 'https://github.com/XiaomiMiMo',
    alternatives: ['step', 'longcat', 'deepseek'],
    source: 'https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Pro-RL',
    verified: true,
    en: {
      summary: 'Xiaomi models for reasoning and agents: from the compact MiMo-7B to MiMo-V2.6-Pro with 1 trillion parameters. Also MiMo-VL for images, voice MiMo-Audio and MiMo-V2.5-ASR speech recognition (Chinese and English).',
      tasks: ['Logic and calculation tasks', 'Agents with tools', 'Help for developers'],
      where: ['Software development', 'Analytics', 'Electronics manufacturing'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'ernie',
    name: 'ERNIE 4.5',
    developer: 'Baidu', country: 'Китай',
    modality: ['text', 'vlm', 'image'],
    first: '2025-06', latest: '2026-04',
    sizes: '0.3B – 424B-A47B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no', industries: ['support', 'docs', 'retail'], ollama: false, cpu: true,
    summary: 'Первая открытая линия Baidu: от крошечной 0.3B до MoE на 424 млрд параметров, есть версии с пониманием картинок. Средняя 21B-A3B помещается на одну видеокарту; ERNIE-Image 8B рисует картинки с текстом.',
    tasks: ['Корпоративный ассистент', 'Разбор документов и изображений', 'Классификация обращений'],
    where: ['Поддержка клиентов', 'Документооборот', 'Электронная коммерция'],
    versions: [['ERNIE 4.5 (0.3B, 21B-A3B, 300B-A47B, VL до 424B-A47B)', '2025-06'], ['ERNIE-4.5-21B-A3B-Thinking', '2025-09'], ['ERNIE-4.5-VL-28B-A3B-Thinking', '2025-11'], ['ERNIE-Image / Image-Turbo 8B', '2026-04']],
    hf: 'https://huggingface.co/baidu',
    github: 'https://github.com/PaddlePaddle/ERNIE',
    alternatives: ['qwen', 'hunyuan', 'glm'],
    source: 'https://huggingface.co/baidu/ERNIE-4.5-21B-A3B-Thinking',
    verified: true,
    en: {
      summary: 'Baidu\'s first open line: from a tiny 0.3B to MoE with 424 billion parameters, including versions that understand images. The mid-size 21B-A3B fits on one GPU; ERNIE-Image 8B draws images with text.',
      tasks: ['Corporate assistant', 'Analysis of documents and images', 'Customer request classification'],
      where: ['Customer support', 'Document management', 'E-commerce'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'seed-oss',
    name: 'Seed-OSS',
    developer: 'ByteDance', country: 'Китай',
    modality: ['text'],
    first: '2025-08', latest: '2025-08',
    sizes: '36B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown', industries: ['legal', 'finance', 'dev'], ollama: false, cpu: false,
    summary: 'Открытая модель ByteDance на 36B с контекстом до 512 тыс. токенов и настраиваемым «бюджетом размышлений». Помещается на одну мощную видеокарту.',
    tasks: ['Разбор длинных документов', 'Агенты с инструментами', 'Корпоративный ассистент'],
    where: ['Юристы', 'Аналитика', 'ИТ-отдел'],
    versions: [['Seed-OSS-36B', '2025-08']],
    hf: 'https://huggingface.co/ByteDance-Seed/Seed-OSS-36B-Instruct',
    github: 'https://github.com/ByteDance-Seed/seed-oss',
    alternatives: ['qwen', 'glm', 'gemma'],
    source: 'https://huggingface.co/ByteDance-Seed/Seed-OSS-36B-Instruct',
    verified: true,
    en: {
      summary: 'An open ByteDance 36B model with up to 512K tokens of context and an adjustable thinking budget. Fits on a single powerful GPU.',
      tasks: ['Analysis of long documents', 'Agents with tools', 'Corporate assistant'],
      where: ['Lawyers', 'Analytics', 'IT department'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'exaone',
    name: 'EXAONE',
    developer: 'LG AI Research', country: 'Южная Корея',
    modality: ['text', 'vlm'],
    first: '2024-07', latest: '2026-07',
    sizes: '1.2B – 750B-A37B',
    license: 'Смешанная: EXAONE 3.0–4.5 — только некоммерческая; K-EXAONE 236B — своя лицензия (коммерция разрешена, распространение третьим лицам по договору); K-EXAONE 2.0 — Apache 2.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no', industries: ['manufacturing', 'science', 'dev'], ollama: true, cpu: true,
    summary: 'Корейско-английские модели LG. Большая часть линии некоммерческая, но флагман K-EXAONE 2.0 на 750 млрд параметров вышел под Apache 2.0.',
    tasks: ['Корпоративный ассистент', 'Работа с корейскими и английскими текстами', 'Разбор документов и картинок (4.5)'],
    where: ['Производство', 'Работа с корейскими партнёрами', 'Исследования'],
    versions: [['EXAONE 3.0', '2024-07'], ['EXAONE 3.5', '2024-12'], ['EXAONE Deep', '2025-03'], ['EXAONE 4.0', '2025-07'], ['K-EXAONE 236B', '2025-12'], ['EXAONE 4.5', '2026-04'], ['K-EXAONE 2.0', '2026-07']],
    hf: 'https://huggingface.co/LGAI-EXAONE',
    github: 'https://github.com/LG-AI-EXAONE',
    alternatives: ['solar', 'kanana', 'hyperclova'],
    source: 'https://huggingface.co/LGAI-EXAONE/K-EXAONE-2.0-750B-A37B',
    verified: true,
    en: {
      summary: 'Korean-English models from LG. Most of the line is non-commercial, but the flagship K-EXAONE 2.0 with 750 billion parameters is released under Apache 2.0.',
      tasks: ['Corporate assistant', 'Working with Korean and English texts', 'Analysis of documents and images (4.5)'],
      where: ['Manufacturing', 'Work with Korean partners', 'Research'],
      license: 'Mixed: EXAONE 3.0–4.5: non-commercial only; K-EXAONE 236B: own license (commercial use allowed, distribution to third parties by agreement); K-EXAONE 2.0: Apache 2.0',
      country: 'South Korea',
    },
  },
  {
    id: 'solar',
    name: 'Solar',
    developer: 'Upstage', country: 'Южная Корея',
    modality: ['text'],
    first: '2023-12', latest: '2026-07',
    sizes: '10.7B – 250B-A15B',
    license: 'SOLAR-10.7B — Apache 2.0; Solar Open и Open 2 — Upstage Solar License (на основе Apache 2.0: коммерция разрешена, но название дообученной модели должно начинаться с Solar, плюс пометка Built with Solar)',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    ru: 'no', industries: ['docs', 'dev'], ollama: true, cpu: false,
    summary: 'Модели корейской Upstage. Solar Open 2 рассчитана на офисную работу с документами: 250 млрд параметров, из них активны 15 млрд, языки — английский, корейский, японский.',
    tasks: ['Работа с офисными документами', 'Агенты для рутинных задач', 'Помощь программистам'],
    where: ['Документооборот', 'Бэк-офис', 'Работа с корейскими и японскими партнёрами'],
    versions: [['SOLAR-10.7B', '2023-12'], ['Solar Pro Preview', '2024-09'], ['Solar Open 100B', '2025-12'], ['Solar Open 2 250B', '2026-07']],
    hf: 'https://huggingface.co/upstage',
    github: null,
    alternatives: ['exaone', 'kanana', 'mistral'],
    source: 'https://huggingface.co/upstage/Solar-Open2-250B',
    verified: true,
    en: {
      summary: 'Models from Korea\'s Upstage. Solar Open 2 is built for office document work: 250 billion parameters, 15 billion active; languages are English, Korean and Japanese.',
      tasks: ['Working with office documents', 'Agents for routine tasks', 'Help for developers'],
      where: ['Document management', 'Back office', 'Work with Korean and Japanese partners'],
      license: 'SOLAR-10.7B: Apache 2.0; Solar Open and Open 2: Upstage Solar License (based on Apache 2.0: commercial use allowed, but a fine-tuned model\'s name must start with Solar, plus a Built with Solar notice)',
      country: 'South Korea',
    },
  },
  {
    id: 'kanana',
    name: 'Kanana',
    developer: 'Kakao', country: 'Южная Корея',
    modality: ['text'],
    first: '2025-02', latest: '2026-07',
    sizes: '1.3B – 30B-A3B',
    license: 'Kanana 1.5 — Apache 2.0; Kanana 2 — собственная лицензия Kakao (компаниям с аудиторией свыше 10 млн пользователей в месяц нужна отдельная лицензия); Kanana Nano — CC-BY-NC',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no', industries: ['support'], ollama: false, cpu: true,
    summary: 'Компактные корейско-английские модели Kakao. Kanana 2 30B-A3B работает быстро за счёт MoE, малые версии на 1–3B подходят для обычного ПК.',
    tasks: ['Чат-бот поддержки', 'Классификация обращений', 'Лёгкий ассистент на своём ПК'],
    where: ['Поддержка клиентов', 'Мессенджеры и сервисы', 'Работа с корейскими партнёрами'],
    versions: [['Kanana Nano 2.1B', '2025-02'], ['Kanana 1.5 (2.1B, 8B)', '2025-04'], ['Kanana 1.5 15.7B-A3B', '2025-07'], ['Kanana 2 30B-A3B', '2025-12'], ['Kanana 2 1.3B / 3B', '2026-07']],
    hf: 'https://huggingface.co/kakaocorp',
    github: 'https://github.com/kakao/kanana',
    alternatives: ['exaone', 'hyperclova', 'solar'],
    source: 'https://huggingface.co/kakaocorp/kanana-2-3b-instruct',
    verified: true,
    en: {
      summary: 'Compact Korean-English models from Kakao. Kanana 2 30B-A3B is fast thanks to MoE; small 1–3B versions suit a regular PC.',
      tasks: ['Support chatbot', 'Customer request classification', 'Lightweight assistant on your own PC'],
      where: ['Customer support', 'Messengers and services', 'Work with Korean partners'],
      license: 'Kanana 1.5: Apache 2.0; Kanana 2: Kakao\'s own license (companies with more than 10 million monthly users need a separate license); Kanana Nano: CC-BY-NC',
      country: 'South Korea',
    },
  },
  {
    id: 'hyperclova',
    name: 'HyperCLOVA X SEED',
    developer: 'Naver', country: 'Южная Корея',
    modality: ['text', 'vlm'],
    first: '2025-04', latest: '2025-12',
    sizes: '0.5B – 32B',
    license: 'Собственная лицензия HyperCLOVA X SEED с дополнительными коммерческими условиями',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'unknown', industries: ['support', 'media', 'docs'], ollama: false, cpu: true,
    summary: 'Открытые младшие модели корейского Naver: от 0.5B до 32B, включая рассуждающие Think и мультимодальные версии с пониманием картинок.',
    tasks: ['Лёгкий корейско-английский ассистент', 'Разбор картинок и документов', 'Классификация текстов'],
    where: ['Работа с корейскими партнёрами', 'Поддержка клиентов', 'Медиа'],
    versions: [['SEED 0.5B / 1.5B / Vision 3B', '2025-04'], ['SEED Think 14B', '2025-07'], ['SEED Think 32B / Omni 8B', '2025-12']],
    hf: 'https://huggingface.co/naver-hyperclovax',
    github: null,
    alternatives: ['exaone', 'kanana', 'solar'],
    source: 'https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-32B',
    verified: true,
    en: {
      summary: 'Open smaller models from Korea\'s Naver: from 0.5B to 32B, including reasoning Think versions and multimodal versions that understand images.',
      tasks: ['Lightweight Korean-English assistant', 'Analysis of images and documents', 'Text classification'],
      where: ['Work with Korean partners', 'Customer support', 'Media'],
      license: 'Own HyperCLOVA X SEED license with additional commercial terms',
      country: 'South Korea',
    },
  },
  {
    id: 'gigachat',
    name: 'GigaChat',
    developer: 'Сбер', country: 'Россия',
    modality: ['text', 'omni'],
    first: '2024-12', latest: '2026-09',
    sizes: '10B-A1.8B – 702B-A36B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes', industries: ['finance', 'gov', 'support', 'legal'], ollama: false, cpu: true,
    summary: 'Открытые модели Сбера, обученные с упором на русский язык: хорошо пишут и понимают по-русски, знают местные реалии. Есть лёгкая 10B-A1.8B и флагманы до 702B, всё под MIT. GigaChat3.1-Audio понимает звук и записи до двух часов, GFusion — быстрая диффузионная версия для текста.',
    tasks: ['Русскоязычный ассистент для сотрудников на своём сервере', 'Ответы клиентам и разбор обращений на русском', 'Работа с договорами и внутренними регламентами', 'Составление писем и отчётов'],
    where: ['Банки и финансы', 'Госсектор и компании с требованиями к хранению данных в РФ', 'Поддержка клиентов', 'Юристы и HR'],
    versions: [['GigaChat 20B-A3B', '2024-12'], ['GigaChat3 10B-A1.8B', '2025-11'], ['GigaChat3.1 (10B, 702B)', '2026-03'], ['GigaChat3.5 432B-A28B', '2026-07'], ['GFusion / GigaChat3.1-Audio 10B-A1.8B', '2026-07'], ['GigaChat3.5 Reasoning', '2026-09']],
    hf: 'https://huggingface.co/ai-sage',
    github: 'https://github.com/salute-developers/gigachat3',
    alternatives: ['yandexgpt', 't-pro', 'giga-embeddings'],
    source: 'https://huggingface.co/ai-sage/GigaChat3.5-432B-A28B-Reasoning',
    verified: true,
    en: {
      summary: 'Sber open models with strong Russian language support and local context, from 10B-A1.8B to 702B, all MIT. GigaChat3.1-Audio handles recordings up to two hours; GFusion is a fast diffusion text version.',
      tasks: ['Russian-language employee assistant on your own server', 'Customer replies and request handling in Russian', 'Working with contracts and internal policies', 'Drafting emails and reports'],
      where: ['Banking and finance', 'Government and companies required to store data in Russia', 'Customer support', 'Legal and HR'],
      license: 'MIT',
      developer: 'Sber',
      country: 'Russia',
    },
  },
  {
    id: 'yandexgpt',
    name: 'YandexGPT / AliceAI',
    developer: 'Яндекс', country: 'Россия',
    modality: ['text'],
    first: '2022-06', latest: '2026-09',
    sizes: '8B – 100B',
    license: 'YaLM-100B, AliceAI-T5 и AliceAI-Foundation — Apache 2.0; YandexGPT-5-Lite — собственное лицензионное соглашение Яндекса, коммерция на его условиях',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes', industries: ['support', 'retail', 'media'], ollama: false, cpu: false,
    summary: 'Модели Яндекса, обученные с нуля с упором на русский язык и российские реалии. Новые AliceAI-Foundation 80B-A3B и экономичная AliceAI-T5 35B-A0.6B — базовые модели под Apache 2.0, их дообучают под свои задачи.',
    tasks: ['Русскоязычный ассистент и чат-бот', 'Ответы на вопросы по базе знаний компании', 'Основа для дообучения под свою отрасль', 'Тексты и письма на русском'],
    where: ['Поддержка клиентов', 'Ритейл и сервисы', 'Компании с требованием хранить данные в РФ', 'Медиа'],
    versions: [['YaLM-100B', '2022-06'], ['YandexGPT-5-Lite-8B', '2025-02'], ['AliceAI-T5-35B-A0.6B', '2026-09'], ['AliceAI-Foundation-80B-A3B-Base', '2026-09']],
    hf: 'https://huggingface.co/yandex',
    github: null,
    alternatives: ['gigachat', 't-pro', 'vikhr'],
    source: 'https://huggingface.co/yandex/AliceAI-Foundation-80B-A3B-Base',
    verified: true,
    en: {
      summary: 'Yandex models trained from scratch with a focus on the Russian language and Russian context. The new AliceAI-Foundation 80B-A3B and efficient AliceAI-T5 35B-A0.6B are Apache 2.0 base models for fine-tuning.',
      tasks: ['Russian-language assistant and chatbot', 'Answers based on the company knowledge base', 'Base for industry-specific fine-tuning', 'Texts and emails in Russian'],
      where: ['Customer support', 'Retail and services', 'Companies required to store data in Russia', 'Media'],
      license: 'YaLM-100B, AliceAI-T5 and AliceAI-Foundation: Apache 2.0; YandexGPT-5-Lite: Yandex\'s own license agreement, commercial use on its terms',
      developer: 'Yandex',
      country: 'Russia',
    },
  },
  {
    id: 't-pro',
    name: 'T-Pro / T-Lite',
    developer: 'Т-Банк', country: 'Россия',
    modality: ['text'],
    first: '2024-12', latest: '2026-07',
    sizes: '7B – 36B-A3B',
    license: 'Apache 2.0 (версии 2.0, 2.1 и T-Search; основа — Qwen)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes', industries: ['finance', 'support', 'legal', 'hr'], ollama: false, cpu: false,
    summary: 'Модели Т-Банка, дообученные на основе Qwen специально для русского языка: заметно лучше исходной модели пишут и рассуждают по-русски. T-Lite — 8B, T-Pro — 32B на одну видеокарту; T-Search — агент для многошагового поиска на русском и английском.',
    tasks: ['Русскоязычный чат-бот поддержки', 'Разбор обращений и документов на русском', 'Ответы по базе знаний компании', 'Черновики писем и отчётов'],
    where: ['Банки и финтех', 'Поддержка клиентов', 'Юристы и HR', 'Ритейл'],
    versions: [['T-Lite / T-Pro 1.0', '2024-12'], ['T-Pro 2.0', '2025-07'], ['T-Lite / T-Pro 2.1', '2025-12'], ['T-Search 36B-A3B', '2026-07']],
    hf: 'https://huggingface.co/t-tech',
    github: null,
    alternatives: ['gigachat', 'yandexgpt', 'qwen'],
    source: 'https://huggingface.co/t-tech/T-pro-it-2.1',
    verified: true,
    en: {
      summary: 'T-Bank models fine-tuned from Qwen for Russian: they write and reason in Russian noticeably better than the original. T-Lite is 8B, T-Pro 32B on one GPU; T-Search is a multi-step search agent in Russian and English.',
      tasks: ['Russian-language support chatbot', 'Analysis of requests and documents in Russian', 'Answers based on the company knowledge base', 'Drafts of emails and reports'],
      where: ['Banking and fintech', 'Customer support', 'Legal and HR', 'Retail'],
      license: 'Apache 2.0 (versions 2.0, 2.1 and T-Search; based on Qwen)',
      developer: 'T-Bank',
      country: 'Russia',
    },
  },
  {
    id: 'vikhr',
    name: 'Vikhr',
    developer: 'Vikhr Models', country: 'Россия',
    modality: ['text', 'asr', 'omni'],
    first: '2024-01', latest: '2025-12',
    sizes: '0.5B – 24B',
    license: 'Основные версии — Apache 2.0; отдельные дообучения наследуют лицензию базы (Llama, YandexGPT)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes', industries: ['support', 'education', 'marketing'], ollama: false, cpu: true,
    summary: 'Русскоязычные дообучения открытых моделей (Mistral, Qwen, Llama) от независимой команды Vikhr: улучшают русский язык, есть компактные версии для обычного ПК. Borealis — аудио-модель для распознавания и понимания русской речи.',
    tasks: ['Русскоязычный ассистент на своём ПК или сервере', 'Ответы по базе знаний (RAG)', 'Тексты и письма на русском'],
    where: ['Малый бизнес', 'Поддержка клиентов', 'Образование'],
    versions: [['Vikhr-7B', '2024-01'], ['Vikhr-Nemo-12B / Llama3.1-8B', '2024-09'], ['QVikhr-2.5-1.5B', '2025-01'], ['QVikhr-3 (1.7B–8B)', '2025-05'], ['Vistral-24B / Borealis (речь в текст)', '2025-09'], ['Borealis-5B-it', '2025-12']],
    hf: 'https://huggingface.co/Vikhrmodels',
    github: 'https://github.com/VikhrModels',
    alternatives: ['t-pro', 'gigachat', 'yandexgpt'],
    source: 'https://huggingface.co/Vikhrmodels/Vistral-24B-Instruct',
    verified: true,
    en: {
      summary: 'Russian-language fine-tunes of open models (Mistral, Qwen, Llama) by the independent Vikhr team, with compact versions for a regular PC. Borealis is an audio model for recognizing and understanding Russian speech.',
      tasks: ['Russian-language assistant on your own PC or server', 'Knowledge-base answers (RAG)', 'Texts and emails in Russian'],
      where: ['Small business', 'Customer support', 'Education'],
      license: 'Main versions: Apache 2.0; some fine-tunes inherit the base model license (Llama, YandexGPT)',
      country: 'Russia',
    },
  },
];
