// Языковые модели США, Европы, Ближнего Востока и Индии (text-west). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'bloom',
    name: 'BLOOM',
    developer: 'BigScience (Hugging Face и сообщество)', country: 'Франция',
    modality: ['text'],
    first: '2022-07', latest: '2022-11',
    sizes: '560M – 176B',
    license: 'BigScience RAIL 1.0: коммерция разрешена, но с запретами на отдельные виды использования',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Одна из первых больших открытых моделей, обученная сообществом из сотен исследователей на 46 языках. Сегодня интересна скорее как историческая веха.',
    tasks: ['Генерация и перевод текстов на многих языках', 'Эксперименты и обучение команды', 'Базовая модель для дообучения под узкую задачу'],
    where: ['Исследовательские группы', 'Образование'],
    versions: [['BLOOM', '2022-07'], ['BLOOMZ (дообучена на инструкциях)', '2022-11']],
    hf: 'https://huggingface.co/bigscience/bloom',
    github: null,
    alternatives: ['falcon', 'olmo', 'pythia'],
    source: 'https://huggingface.co/bigscience/bloomz',
    verified: true,
  },
  {
    id: 'opt',
    name: 'OPT',
    developer: 'Meta', country: 'США',
    modality: ['text'],
    first: '2022-05', latest: '2022-12',
    sizes: '125M – 66B (175B по запросу)',
    license: 'OPT License: только некоммерческое и исследовательское использование',
    commercial: 'no',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Ранняя открытая серия Meta, повторяющая по размерам GPT-3. Устарела, полезна для исследований и сравнения.',
    tasks: ['Исследовательские эксперименты', 'Обучение специалистов', 'Сравнение с современными моделями'],
    where: ['Исследовательские группы', 'Вузы'],
    versions: [['OPT', '2022-05'], ['OPT-IML', '2022-12']],
    hf: 'https://huggingface.co/facebook/opt-66b',
    github: 'https://github.com/facebookresearch/metaseq',
    alternatives: ['pythia', 'bloom', 'llama'],
    source: 'https://huggingface.co/facebook/opt-66b',
    verified: true,
  },
  {
    id: 'pythia',
    name: 'Pythia и GPT-NeoX',
    developer: 'EleutherAI', country: 'США',
    modality: ['text'],
    first: '2022-02', latest: '2023-02',
    sizes: '70M – 20B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Полностью открытые модели некоммерческой лаборатории EleutherAI: GPT-NeoX-20B и серия Pythia с опубликованными промежуточными снимками обучения.',
    tasks: ['Базовая модель для дообучения', 'Исследование поведения моделей', 'Простая генерация и дополнение текста'],
    where: ['Исследовательские группы', 'Вузы', 'R&D-отделы'],
    versions: [['GPT-NeoX-20B', '2022-02'], ['Pythia (70M – 12B)', '2023-02']],
    hf: 'https://huggingface.co/EleutherAI',
    github: 'https://github.com/EleutherAI/pythia',
    alternatives: ['olmo', 'opt', 'bloom'],
    source: 'https://huggingface.co/EleutherAI/pythia-12b',
    verified: true,
  },
  {
    id: 'flan-t5',
    name: 'Flan-T5 и Flan-UL2',
    developer: 'Google', country: 'США',
    modality: ['text'],
    first: '2022-10', latest: '2023-03',
    sizes: '80M – 20B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Компактные модели «вход-выход», обученные выполнять инструкции. До сих пор используются как дешёвая основа для классификации, извлечения и коротких ответов.',
    tasks: ['Классификация обращений и документов', 'Извлечение полей из текста', 'Короткие ответы и пересказ', 'Дообучение под узкую задачу'],
    where: ['Поддержка клиентов', 'Документооборот', 'Аналитика'],
    versions: [['Flan-T5', '2022-10'], ['Flan-UL2', '2023-03']],
    hf: 'https://huggingface.co/google/flan-t5-xxl',
    github: 'https://github.com/google-research/t5x',
    alternatives: ['smollm', 'phi', 'granite'],
    source: 'https://huggingface.co/google/flan-ul2',
    verified: true,
  },
  {
    id: 'falcon',
    name: 'Falcon',
    developer: 'Technology Innovation Institute (TII)', country: 'ОАЭ',
    modality: ['text'],
    first: '2023-05', latest: '2026-01',
    sizes: '90M – 180B',
    license: 'Falcon 7B/40B: Apache 2.0; Falcon 180B и начиная с Falcon 2: TII Falcon License (на базе Apache, с политикой допустимого использования)',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Семейство из Абу-Даби: от ранних Falcon 40B и 180B до гибридных Falcon-H1 и сверхмалых Falcon-H1-Tiny на 90–600M параметров для устройств.',
    tasks: ['Ассистент и ответы по документам', 'Работа на слабом железе и в устройствах', 'Вызов инструментов в простых агентах', 'Тексты на арабском и европейских языках'],
    where: ['Поддержка клиентов', 'Встраиваемые устройства', 'Госсектор и крупные компании'],
    versions: [['Falcon 7B / 40B', '2023-05'], ['Falcon 180B', '2023-09'], ['Falcon 2 11B', '2024-05'], ['Falcon 3', '2024-12'], ['Falcon-H1', '2025-05'], ['Falcon-H1R 7B', '2025-10'], ['Falcon-H1-Tiny', '2026-01']],
    hf: 'https://huggingface.co/tiiuae',
    github: null,
    alternatives: ['jamba', 'lfm', 'granite'],
    source: 'https://huggingface.co/tiiuae/Falcon-H1-Tiny-90M-Instruct',
    verified: true,
  },
  {
    id: 'mpt',
    name: 'MPT',
    developer: 'MosaicML (Databricks)', country: 'США',
    modality: ['text'],
    first: '2023-05', latest: '2023-06',
    sizes: '7B – 30B',
    license: 'Базовые версии Apache 2.0, чат-версии CC-BY-NC; официальные репозитории на Hugging Face сейчас закрыты',
    commercial: 'conditional',
    hardware: ['gpu'],
    summary: 'Одна из первых открытых моделей с разрешением на коммерцию и длинным контекстом. Официальные веса больше не раздаются, остались копии сообщества.',
    tasks: ['Генерация текстов', 'Длинные тексты (версия StoryWriter)', 'Исследования'],
    where: ['Исследовательские группы'],
    versions: [['MPT-7B', '2023-05'], ['MPT-30B', '2023-06']],
    hf: null,
    github: 'https://github.com/mosaicml/llm-foundry',
    alternatives: ['falcon', 'pythia', 'dbrx'],
    source: 'https://huggingface.co/mosaicml',
    verified: false,
  },
  {
    id: 'phi',
    name: 'Phi',
    developer: 'Microsoft', country: 'США',
    modality: ['text', 'vlm'],
    first: '2023-09', latest: '2026-01',
    sizes: '1.3B – 42B-A6.6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Малые модели Microsoft, обученные на тщательно отобранных данных: сильны в логике и математике при скромном размере. Есть версии с картинками и речью.',
    tasks: ['Ассистент на ноутбуке или своём сервере', 'Задачи с рассуждением и расчётами', 'Разбор изображений и схем (vision-версии)', 'Классификация и извлечение данных'],
    where: ['Внутренние сервисы компании', 'Образование', 'Аналитика'],
    versions: [['Phi-1 / Phi-1.5', '2023-09'], ['Phi-2', '2023-12'], ['Phi-3', '2024-04'], ['Phi-3.5 (включая MoE и Vision)', '2024-08'], ['Phi-4', '2024-12'], ['Phi-4-mini и multimodal', '2025-02'], ['Phi-4-reasoning', '2025-04'], ['Phi-4-reasoning-vision-15B', '2026-01']],
    hf: 'https://huggingface.co/microsoft/Phi-4-reasoning-vision-15B',
    github: 'https://github.com/microsoft/PhiCookBook',
    alternatives: ['gemma', 'smollm', 'granite'],
    source: 'https://huggingface.co/microsoft/Phi-4-reasoning-vision-15B',
    verified: true,
  },
  {
    id: 'olmo',
    name: 'OLMo',
    developer: 'Allen Institute for AI (Ai2)', country: 'США',
    modality: ['text'],
    first: '2024-02', latest: '2026-01',
    sizes: '1B – 32B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Полностью открытые модели: опубликованы не только веса, но и данные, код обучения и промежуточные снимки. Удобно, когда важна прозрачность происхождения.',
    tasks: ['Ассистент и ответы по документам', 'Задачи с рассуждением (версии Think)', 'Дообучение под свои данные с понятной историей модели'],
    where: ['Госсектор и регулируемые отрасли', 'Исследовательские группы', 'Образование'],
    versions: [['OLMo 7B', '2024-02'], ['OLMoE 1B-7B', '2024-09'], ['OLMo 2', '2024-11'], ['OLMo 2 32B', '2025-03'], ['Olmo 3', '2025-11'], ['Olmo 3.1', '2025-12'], ['Olmo-Hybrid 7B', '2026-01']],
    hf: 'https://huggingface.co/allenai/Olmo-3.1-32B-Think',
    github: 'https://github.com/allenai/OLMo',
    alternatives: ['apertus', 'pythia', 'smollm'],
    source: 'https://huggingface.co/allenai/Olmo-Hybrid-7B',
    verified: true,
  },
  {
    id: 'dbrx',
    name: 'DBRX',
    developer: 'Databricks', country: 'США',
    modality: ['text'],
    first: '2024-03', latest: '2024-03',
    sizes: '132B-A36B',
    license: 'Databricks Open Model License (с ограничениями); официальные веса на Hugging Face сейчас закрыты',
    commercial: 'conditional',
    hardware: ['multi'],
    summary: 'Большая MoE-модель Databricks 2024 года. Официальные репозитории закрыты, поэтому для новых внедрений не подходит.',
    tasks: ['Ответы по корпоративным данным', 'Генерация SQL и кода', 'Анализ текстов'],
    where: ['Аналитика данных', 'ИТ-отделы'],
    versions: [['DBRX Base / Instruct', '2024-03']],
    hf: null,
    github: 'https://github.com/databricks/dbrx',
    alternatives: ['mpt', 'jamba', 'command'],
    source: 'https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm',
    verified: false,
  },
  {
    id: 'grok',
    name: 'Grok (открытые веса)',
    developer: 'xAI', country: 'США',
    modality: ['text'],
    first: '2024-03', latest: '2025-08',
    sizes: '314B (Grok-1), Grok-2 крупнее',
    license: 'Grok-1: Apache 2.0; Grok-2: Grok 2 Community License (коммерция при соблюдении правил xAI, нельзя обучать на ней другие большие модели)',
    commercial: 'conditional',
    hardware: ['multi'],
    summary: 'xAI выкладывает веса прошлых поколений Grok. Модели очень большие и требуют кластера видеокарт, поэтому на практике их запускают редко.',
    tasks: ['Исследования больших моделей', 'Ассистент на собственной инфраструктуре', 'Генерация и анализ текстов'],
    where: ['Крупные ИТ-компании', 'Исследовательские группы'],
    versions: [['Grok-1', '2024-03'], ['Grok-2', '2025-08']],
    hf: 'https://huggingface.co/xai-org/grok-2',
    github: 'https://github.com/xai-org/grok-1',
    alternatives: ['inkling', 'nemotron', 'llama'],
    source: 'https://huggingface.co/xai-org/grok-2',
    verified: true,
  },
  {
    id: 'jamba',
    name: 'Jamba',
    developer: 'AI21 Labs', country: 'Израиль',
    modality: ['text'],
    first: '2024-03', latest: '2026-01',
    sizes: '3B – 398B-A94B',
    license: 'Jamba v0.1, Reasoning 3B и Jamba2: Apache 2.0; Jamba 1.5–1.7: Jamba Open Model License с ограничением по выручке',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Гибрид трансформера и Mamba с окном до 256K токенов: держит длинные документы быстрее обычных моделей. Jamba2 ориентирована на точные ответы по источникам.',
    tasks: ['Ответы по длинным регламентам и договорам', 'Поиск по базе знаний (RAG)', 'Пересказ больших документов', 'Следование строгим инструкциям'],
    where: ['Юридические отделы', 'Поддержка клиентов', 'Финансы'],
    versions: [['Jamba v0.1', '2024-03'], ['Jamba 1.5 Mini / Large', '2024-08'], ['Jamba 1.6', '2025-02'], ['Jamba 1.7', '2025-07'], ['Jamba Reasoning 3B', '2025-10'], ['Jamba2 3B / Mini', '2026-01']],
    hf: 'https://huggingface.co/ai21labs/AI21-Jamba2-Mini',
    github: null,
    alternatives: ['falcon', 'granite', 'command'],
    source: 'https://huggingface.co/ai21labs/AI21-Jamba2-Mini',
    verified: true,
  },
  {
    id: 'command',
    name: 'Cohere Command',
    developer: 'Cohere', country: 'Канада',
    modality: ['text', 'vlm'],
    first: '2024-03', latest: '2026-05',
    sizes: '7B – 218B-A25B',
    license: 'Command R, R+, R7B, Command A (2024–2025): CC-BY-NC, только некоммерческое; Command A+ (05-2026): Apache 2.0',
    commercial: 'conditional',
    hardware: ['gpu', 'multi'],
    summary: 'Модели для бизнеса: поиск по документам со ссылками на источники, вызов инструментов, много языков. Command A+ 2026 года впервые вышла под Apache 2.0.',
    tasks: ['Ответы по базе знаний со ссылками на источники', 'Агенты, работающие с внутренними системами', 'Перевод и переписка на разных языках', 'Разбор документов с картинками (A+)'],
    where: ['Крупные компании', 'Поддержка клиентов', 'Юридические и финансовые отделы'],
    versions: [['Command R', '2024-03'], ['Command R+', '2024-04'], ['Command R7B', '2024-12'], ['Command A', '2025-03'], ['Command A Vision / Reasoning / Translate', '2025-08'], ['Command A+', '2026-05']],
    hf: 'https://huggingface.co/CohereLabs/command-a-plus-05-2026-bf16',
    github: null,
    alternatives: ['aya', 'jamba', 'granite'],
    source: 'https://huggingface.co/CohereLabs/command-a-plus-05-2026-bf16',
    verified: true,
  },
  {
    id: 'aya',
    name: 'Aya',
    developer: 'Cohere Labs', country: 'Канада',
    modality: ['text', 'vlm'],
    first: '2024-02', latest: '2026-09',
    sizes: '3.3B – 35B',
    license: 'Aya 101: Apache 2.0; Aya 23, Expanse, Vision и Tiny Aya: CC-BY-NC, только некоммерческое',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Многоязычные модели исследовательского крыла Cohere, от 23 до 100+ языков. Tiny Aya 2026 года на 3.3B работает на обычном ПК, но только некоммерчески.',
    tasks: ['Перевод и переписка на редких языках', 'Многоязычный чат-ассистент', 'Разбор изображений с текстом (Vision)'],
    where: ['Образование', 'Некоммерческие проекты', 'Исследования'],
    versions: [['Aya 101', '2024-02'], ['Aya 23', '2024-05'], ['Aya Expanse', '2024-10'], ['Aya Vision', '2025-03'], ['Tiny Aya', '2026-02'], ['Tiny Aya Thinker', '2026-09']],
    hf: 'https://huggingface.co/CohereLabs/tiny-aya-global',
    github: null,
    alternatives: ['command', 'apertus', 'sarvam'],
    source: 'https://huggingface.co/CohereLabs/tiny-aya-global',
    verified: true,
  },
  {
    id: 'nemotron',
    name: 'NVIDIA Nemotron',
    developer: 'NVIDIA', country: 'США',
    modality: ['text'],
    first: '2024-06', latest: '2026-08',
    sizes: '4B – 550B-A55B',
    license: 'Nemotron-4, Llama-Nemotron, Nemotron 3 Nano и Super: лицензии NVIDIA Open Model License (коммерция разрешена с условиями; у Llama-версий добавляются условия Llama); Nemotron 3 Ultra и 3.5 Lightning: OpenMDW-1.1',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Модели NVIDIA для агентов и рассуждений, заточенные под быстрый запуск на её видеокартах. Nemotron 3 это гибрид Mamba и MoE от 4B до 550B.',
    tasks: ['Агенты с вызовом инструментов', 'Задачи с рассуждением и расчётами', 'Ответы по длинным документам', 'Генерация синтетических данных для обучения'],
    where: ['ИТ-отделы и разработка', 'Промышленность', 'Крупные компании с собственным GPU-кластером'],
    versions: [['Nemotron-4 340B', '2024-06'], ['Llama-3.1-Nemotron-70B', '2024-10'], ['Llama-Nemotron Ultra 253B', '2025-04'], ['Nemotron Nano 2 (9B, 12B)', '2025-08'], ['Nemotron 3 Nano 30B-A3B', '2025-12'], ['Nemotron 3 Super 120B-A12B', '2026-03'], ['Nemotron 3 Ultra 550B-A55B', '2026-06'], ['Nemotron 3.5 Lightning 30B-A3B', '2026-08']],
    hf: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16',
    github: null,
    alternatives: ['llama', 'qwen', 'granite'],
    source: 'https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16',
    verified: true,
  },
  {
    id: 'granite',
    name: 'IBM Granite',
    developer: 'IBM', country: 'США',
    modality: ['text'],
    first: '2024-05', latest: '2026-08',
    sizes: '350M – 34B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Корпоративные модели IBM с прозрачными данными обучения и сертификацией ISO 42001. Granite 4 это гибрид Mamba и трансформера, экономный по памяти.',
    tasks: ['Ответы по внутренним документам (RAG)', 'Вызов инструментов и работа в агентах', 'Извлечение данных и классификация', 'Помощь в коде'],
    where: ['Банки и страхование', 'Госсектор', 'ИТ-отделы крупных компаний'],
    versions: [['Granite Code', '2024-05'], ['Granite 3.0', '2024-10'], ['Granite 3.1', '2024-12'], ['Granite 3.3', '2025-04'], ['Granite 4.0', '2025-10'], ['Granite 4.1', '2026-04'], ['Granite 4.2', '2026-08']],
    hf: 'https://huggingface.co/ibm-granite/granite-4.2-30b',
    github: null,
    alternatives: ['phi', 'command', 'nemotron'],
    source: 'https://huggingface.co/ibm-granite/granite-4.2-30b',
    verified: true,
  },
  {
    id: 'smollm',
    name: 'SmolLM',
    developer: 'Hugging Face', country: 'США',
    modality: ['text'],
    first: '2024-07', latest: '2025-07',
    sizes: '135M – 3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    summary: 'Крошечные открытые модели Hugging Face для телефонов и ноутбуков. SmolLM3 на 3B умеет рассуждать и держит длинный контекст, весь рецепт обучения открыт.',
    tasks: ['Простой ассистент прямо на устройстве', 'Классификация и маршрутизация обращений', 'Основа для дообучения под узкую задачу'],
    where: ['Мобильные приложения', 'Встраиваемые устройства', 'Образование'],
    versions: [['SmolLM', '2024-07'], ['SmolLM2', '2024-10'], ['SmolLM3 3B', '2025-07']],
    hf: 'https://huggingface.co/HuggingFaceTB/SmolLM3-3B',
    github: 'https://github.com/huggingface/smollm',
    alternatives: ['lfm', 'phi', 'gemma'],
    source: 'https://huggingface.co/HuggingFaceTB/SmolLM3-3B',
    verified: true,
  },
  {
    id: 'lfm',
    name: 'Liquid LFM',
    developer: 'Liquid AI', country: 'США',
    modality: ['text'],
    first: '2025-07', latest: '2026-08',
    sizes: '230M – 24B-A2B',
    license: 'LFM Open License v1.0: бесплатно для компаний с выручкой до 10 млн долларов в год, выше нужна отдельная лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Модели новой архитектуры для работы прямо на устройстве: быстрые на обычном процессоре и в телефоне. Есть версии для извлечения данных, RAG и инструментов.',
    tasks: ['Ассистент на ноутбуке или телефоне без интернета', 'Извлечение данных из документов', 'Вызов инструментов в приложениях', 'Поиск по базе знаний (RAG)'],
    where: ['Мобильные приложения', 'Автомобильная и бытовая электроника', 'Малый бизнес'],
    versions: [['LFM2', '2025-07'], ['LFM2-8B-A1B', '2025-10'], ['LFM2.5-1.2B', '2026-01'], ['LFM2-24B-A2B', '2026-02'], ['LFM2.5-8B-A1B', '2026-05'], ['LFM2.5-2.6B', '2026-07']],
    hf: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B',
    github: null,
    alternatives: ['smollm', 'phi', 'falcon'],
    source: 'https://huggingface.co/LiquidAI/LFM2.5-2.6B',
    verified: true,
  },
  {
    id: 'apertus',
    name: 'Apertus',
    developer: 'Swiss AI (ETH Zurich, EPFL, CSCS)', country: 'Швейцария',
    modality: ['text', 'vlm'],
    first: '2025-09', latest: '2026-07',
    sizes: '0.5B – 70B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    summary: 'Государственная открытая модель Швейцарии: открыты веса, данные и рецепт, более 1000 языков в обучении. Версия 1.5 понимает изображения.',
    tasks: ['Многоязычный ассистент', 'Ответы по документам', 'Разбор изображений и сканов (v1.5)', 'Дообучение с понятным происхождением данных'],
    where: ['Госсектор', 'Образование и наука', 'Регулируемые отрасли'],
    versions: [['Apertus 8B / 70B', '2025-09'], ['Apertus v1.1 (0.5B – 4B)', '2026-02'], ['Apertus v1.5 8B / 70B', '2026-07']],
    hf: 'https://huggingface.co/swiss-ai/Apertus-v1.5-70B',
    github: null,
    alternatives: ['olmo', 'aya', 'mistral'],
    source: 'https://huggingface.co/swiss-ai/Apertus-v1.5-70B',
    verified: true,
  },
  {
    id: 'muse-glimmer',
    name: 'Muse Glimmer',
    developer: 'Meta Superintelligence Labs', country: 'США',
    modality: ['text', 'vlm'],
    first: '2026-08', latest: '2026-08',
    sizes: '30B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    summary: 'Открытая модель Meta для агентов на доступном железе: дистиллирована из закрытой Muse Spark, понимает текст и картинки, обучена на 100+ языках.',
    tasks: ['Агенты с вызовом инструментов', 'Разбор скриншотов, графиков и документов', 'Многоязычный ассистент'],
    where: ['Автоматизация офисных процессов', 'Поддержка клиентов', 'ИТ-отделы'],
    versions: [['Muse Glimmer 30B', '2026-08']],
    hf: 'https://huggingface.co/meta-models/Muse-Glimmer-30B',
    github: null,
    alternatives: ['llama', 'gemma', 'qwen'],
    source: 'https://huggingface.co/meta-models/Muse-Glimmer-30B',
    verified: true,
  },
  {
    id: 'inkling',
    name: 'Inkling',
    developer: 'Thinking Machines Lab', country: 'США',
    modality: ['text', 'vlm'],
    first: '2026-07', latest: '2026-07',
    sizes: '276B-A12B, 975B-A41B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['multi'],
    summary: 'Флагманские открытые модели лаборатории Миры Мурати: принимают текст, изображения и аудио. Большие MoE, требуют нескольких видеокарт.',
    tasks: ['Корпоративный ассистент уровня флагмана', 'Разбор документов, изображений и аудио', 'Помощь в программировании', 'Агенты для сложных многошаговых задач'],
    where: ['Крупные компании', 'ИТ и разработка', 'Аналитика'],
    versions: [['Inkling', '2026-07'], ['Inkling-Small', '2026-07']],
    hf: 'https://huggingface.co/thinkingmachines/Inkling',
    github: null,
    alternatives: ['command', 'nemotron', 'deepseek'],
    source: 'https://huggingface.co/thinkingmachines/Inkling-Small',
    verified: true,
  },
  {
    id: 'laguna',
    name: 'Laguna',
    developer: 'Poolside', country: 'США',
    modality: ['code', 'text'],
    first: '2026-04', latest: '2026-07',
    sizes: '33B-A3B – 225B-A23B',
    license: 'Laguna XS.2 и M.1: Apache 2.0; Laguna XS 2.1 и S 2.1: OpenMDW-1.1 (свободное коммерческое использование)',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    summary: 'Модели для агентного программирования: самостоятельно правят код в репозитории. Младшая XS запускается на Mac с 36 ГБ памяти, у S 2.1 контекст 1M токенов.',
    tasks: ['Агент-программист для внутренней разработки', 'Исправление ошибок и доработка кода', 'Работа с большими кодовыми базами'],
    where: ['ИТ-отделы', 'Разработка ПО', 'Интеграторы'],
    versions: [['Laguna XS.2', '2026-04'], ['Laguna M.1', '2026-06'], ['Laguna XS 2.1', '2026-06'], ['Laguna S 2.1', '2026-07']],
    hf: 'https://huggingface.co/poolside/Laguna-S-2.1',
    github: null,
    alternatives: ['qwen-coder', 'devstral', 'kat-coder'],
    source: 'https://huggingface.co/poolside/Laguna-S-2.1',
    verified: true,
  },
  {
    id: 'trinity',
    name: 'Arcee Trinity',
    developer: 'Arcee AI', country: 'США',
    modality: ['text'],
    first: '2025-12', latest: '2026-04',
    sizes: '6B – 398B-A13B',
    license: 'OpenMDW-1.1 (свободное коммерческое использование)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Американское семейство MoE-моделей, обученных с нуля: Nano, Mini и Large. Trinity-Large-Thinking на 398B рассуждает перед ответом.',
    tasks: ['Агенты с вызовом инструментов', 'Задачи с рассуждением', 'Корпоративный ассистент на своих серверах'],
    where: ['ИТ-отделы', 'Крупные компании', 'Аналитика'],
    versions: [['Trinity Nano / Mini', '2025-12'], ['Trinity-Large-Preview', '2026-01'], ['Trinity-Large-Thinking', '2026-04']],
    hf: 'https://huggingface.co/arcee-ai/Trinity-Large-Thinking',
    github: null,
    alternatives: ['olmo', 'nemotron', 'gpt-oss'],
    source: 'https://huggingface.co/arcee-ai/Trinity-Large-Thinking',
    verified: true,
  },
  {
    id: 'sarvam',
    name: 'Sarvam',
    developer: 'Sarvam AI', country: 'Индия',
    modality: ['text'],
    first: '2024-10', latest: '2026-03',
    sizes: '2B – 105B-A10B',
    license: 'Основные версии Apache 2.0 (Sarvam-M, Sarvam 30B и 105B)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    summary: 'Индийские модели с упором на 22 языка Индии. Sarvam 30B и 105B 2026 года это MoE-модели с сильными навыками рассуждения и работы в агентах.',
    tasks: ['Многоязычная поддержка клиентов', 'Задачи с рассуждением и расчётами', 'Агенты с вызовом инструментов'],
    where: ['Компании с клиентами в Индии', 'Госсектор', 'Колл-центры'],
    versions: [['Sarvam-1 2B', '2024-10'], ['Sarvam-M 24B', '2025-05'], ['Sarvam 30B / 105B', '2026-03']],
    hf: 'https://huggingface.co/sarvamai/sarvam-105b',
    github: null,
    alternatives: ['aya', 'apertus', 'qwen'],
    source: 'https://huggingface.co/sarvamai/sarvam-105b',
    verified: true,
  },
  {
    id: 'intellect',
    name: 'INTELLECT',
    developer: 'Prime Intellect', country: 'США',
    modality: ['text'],
    first: '2024-11', latest: '2026-01',
    sizes: '10B – 106B-A12B',
    license: 'INTELLECT-1 и 2: Apache 2.0; INTELLECT-3 и 3.1: MIT',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    summary: 'Модели, обученные распределённо на видеокартах со всего мира. INTELLECT-3 на 106B дообучена с подкреплением для математики, кода и агентов.',
    tasks: ['Задачи с рассуждением и математикой', 'Помощь в программировании', 'Агенты с вызовом инструментов'],
    where: ['ИТ и разработка', 'Исследовательские группы'],
    versions: [['INTELLECT-1 10B', '2024-11'], ['INTELLECT-2 32B', '2025-05'], ['INTELLECT-3', '2025-11'], ['INTELLECT-3.1', '2026-01']],
    hf: 'https://huggingface.co/PrimeIntellect/INTELLECT-3.1',
    github: null,
    alternatives: ['trinity', 'olmo', 'glm'],
    source: 'https://huggingface.co/PrimeIntellect/INTELLECT-3.1',
    verified: true,
  },
  {
    id: 'reka',
    name: 'Reka Flash и Reka Edge',
    developer: 'Reka AI', country: 'США',
    modality: ['text', 'vlm'],
    first: '2025-03', latest: '2026-03',
    sizes: '7B – 21B',
    license: 'Reka Flash 3 и 3.1: Apache 2.0; Reka Edge: своя лицензия, коммерция бесплатна при выручке до 1 млн долларов в год',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    summary: 'Компактные модели Reka: Flash 3 на 21B для рассуждений и Reka Edge на 7B, которая быстро разбирает изображения и видео на устройстве.',
    tasks: ['Разбор фото и видео (Edge)', 'Поиск объектов на изображениях', 'Задачи с рассуждением (Flash)'],
    where: ['Видеоаналитика', 'Встраиваемые устройства', 'Розница'],
    versions: [['Reka Flash 3', '2025-03'], ['Reka Flash 3.1', '2025-05'], ['Reka Edge 2603', '2026-03']],
    hf: 'https://huggingface.co/RekaAI/reka-edge-2603',
    github: null,
    alternatives: ['phi', 'muse-glimmer', 'lfm'],
    source: 'https://huggingface.co/RekaAI/reka-edge-2603',
    verified: true,
  },
];
