// Виртуальная примерка одежды и обработка фото: удаление фона, апскейл, реставрация лиц, удаление объектов, свет, окрашивание.
// Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- Виртуальная примерка ----------
  {
    id: 'idm-vton',
    name: 'IDM-VTON',
    developer: 'KAIST и OMNIOUS.AI', country: 'Южная Корея',
    modality: ['tryon'],
    first: '2024-03', latest: '2024-04',
    sizes: 'на базе SDXL',
    license: 'CC BY-NC-SA 4.0 (только некоммерческое использование)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Одна из самых известных открытых примерок: переносит вещь с фото товара на фото человека, хорошо держит принты и логотипы. Лицензия некоммерческая.',
    tasks: ['Пилот примерочной на сайте магазина', 'Прототип карточек товара на модели без фотосессии', 'Сравнение с коммерческими сервисами примерки'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Исследовательские отделы ритейла'],
    versions: [['IDM-VTON (VITON-HD)', '2024-03'], ['IDM-VTON-DC (DressCode)', '2024-04']],
    hf: 'https://huggingface.co/yisol/IDM-VTON',
    github: 'https://github.com/yisol/IDM-VTON',
    alternatives: ['catvton', 'leffa', 'fashn-vton'],
    source: 'https://huggingface.co/api/models/yisol/IDM-VTON',
    verified: true,
    en: {
      summary: 'One of the best-known open virtual try-on models: moves a garment from a product photo onto a photo of a person, keeping prints and logos well. Non-commercial license.',
      tasks: ['Pilot of a fitting room on a store website', 'Prototype product cards on a model without a photo shoot', 'Comparison with commercial try-on services'],
      where: ['Online apparel retail', 'Marketplaces', 'Retail research departments'],
      license: 'CC BY-NC-SA 4.0 (non-commercial use only)',
      developer: 'KAIST and OMNIOUS.AI',
      country: 'South Korea',
      sizes: 'based on SDXL',
    },
  },
  {
    id: 'catvton',
    name: 'CatVTON / CatV2TON',
    developer: 'Университет Сунь Ятсена и Pixocial', country: 'Китай',
    modality: ['tryon', 'video'],
    first: '2024-07', latest: '2025-04',
    sizes: '899M',
    license: 'CC BY-NC-SA 4.0 (CatVTON), CC BY-NC-ND 4.0 (CatV2TON) — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['retail'],
    ollama: false,
    cpu: false,
    summary: 'Лёгкая модель примерки, запускается на обычной видеокарте. Есть версия без маски и CatV2TON, который примеряет одежду и на видео.',
    tasks: ['Примерка вещи на фото покупателя', 'Черновые карточки товара на модели', 'Примерка на коротком видео'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Фэшн-стартапы'],
    versions: [['CatVTON', '2024-07'], ['CatVTON без маски', '2024-09'], ['CatV2TON (фото и видео)', '2025-02'], ['CatV2TON V2', '2025-04']],
    hf: 'https://huggingface.co/zhengchong/CatVTON',
    github: 'https://github.com/Zheng-Chong/CatVTON',
    alternatives: ['fastfit', 'idm-vton', 'ootdiffusion'],
    source: 'https://huggingface.co/api/models?author=zhengchong',
    verified: true,
    en: {
      summary: 'A lightweight try-on model that runs on a regular GPU. There is a mask-free version and CatV2TON, which also tries clothes on in video.',
      tasks: ['Trying a garment on a customer\'s photo', 'Draft product cards on a model', 'Try-on in a short video'],
      where: ['Online apparel retail', 'Marketplaces', 'Fashion startups'],
      license: 'CC BY-NC-SA 4.0 (CatVTON), CC BY-NC-ND 4.0 (CatV2TON) — non-commercial use only',
      developer: 'Sun Yat-sen University and Pixocial',
      country: 'China',
    },
  },
  {
    id: 'fastfit',
    name: 'FastFit',
    developer: 'LavieAI и Университет Сунь Ятсена', country: 'Китай',
    modality: ['tryon'],
    first: '2025-07', latest: '2025-07',
    sizes: 'на базе SD 1.5 inpainting',
    license: 'FastFit Non-Commercial License (коммерция — по договору с LavieAI)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail'],
    ollama: false,
    cpu: false,
    summary: 'Примерка сразу нескольких вещей за раз: верх, низ, обувь, сумка. Быстрее прежних моделей за счёт кэширования. Лицензия некоммерческая.',
    tasks: ['Сборка образа из нескольких товаров на одной модели', 'Пилот «собери лук» на сайте', 'Прототипы лукбуков без съёмки'],
    where: ['Онлайн-торговля одеждой и обувью', 'Маркетплейсы', 'Фэшн-бренды'],
    versions: [['FastFit-SR и FastFit-MR (1024)', '2025-07']],
    hf: 'https://huggingface.co/zhengchong/FastFit-MR-1024',
    github: 'https://github.com/Zheng-Chong/FastFit',
    alternatives: ['catvton', 'omnitry', 'any2anytryon'],
    source: 'https://github.com/Zheng-Chong/FastFit',
    verified: true,
    en: {
      summary: 'Tries on several items at once: top, bottom, shoes, bag. Faster than earlier models thanks to caching. Non-commercial license.',
      tasks: ['Building an outfit from several products on one model', '"Build a look" pilot on a website', 'Lookbook prototypes without a shoot'],
      where: ['Online apparel and footwear retail', 'Marketplaces', 'Fashion brands'],
      license: 'FastFit Non-Commercial License (commercial use under agreement with LavieAI)',
      developer: 'LavieAI and Sun Yat-sen University',
      country: 'China',
      sizes: 'based on SD 1.5 inpainting',
    },
  },
  {
    id: 'ootdiffusion',
    name: 'OOTDiffusion',
    developer: 'Xiao-i Research', country: 'Китай',
    modality: ['tryon'],
    first: '2024-02', latest: '2024-03',
    sizes: 'на базе Stable Diffusion',
    license: 'CC BY-NC-SA 4.0 (только некоммерческое использование)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Ранняя популярная открытая примерка: одна версия для верхней одежды по пояс, другая для образа в полный рост. Лицензия некоммерческая.',
    tasks: ['Примерка верха на фото модели', 'Примерка в полный рост: верх, низ, платья', 'Прототип примерочной для тестов'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Исследовательские отделы ритейла'],
    versions: [['OOTDiffusion HD (по пояс)', '2024-02'], ['OOTDiffusion DC (в полный рост)', '2024-03']],
    hf: 'https://huggingface.co/levihsu/OOTDiffusion',
    github: 'https://github.com/levihsu/OOTDiffusion',
    alternatives: ['idm-vton', 'catvton', 'stableviton'],
    source: 'https://huggingface.co/api/models/levihsu/OOTDiffusion/commits/main',
    verified: true,
    en: {
      summary: 'An early popular open try-on model: one version for upper-body garments, another for full-length outfits. Non-commercial license.',
      tasks: ['Trying tops on a model photo', 'Full-length try-on: tops, bottoms, dresses', 'Fitting room prototype for testing'],
      where: ['Online apparel retail', 'Marketplaces', 'Retail research departments'],
      license: 'CC BY-NC-SA 4.0 (non-commercial use only)',
      country: 'China',
      sizes: 'based on Stable Diffusion',
    },
  },
  {
    id: 'leffa',
    name: 'Leffa',
    developer: 'Meta AI (вместе с King\'s College London)', country: 'США',
    modality: ['tryon'],
    first: '2024-12', latest: '2024-12',
    sizes: 'на базе Stable Diffusion',
    license: 'MIT для кода и весов, но веса обучены на наборах VITON-HD и DressCode с некоммерческими условиями — для бизнеса нужна юридическая проверка',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Модель Meta для примерки и смены позы человека на фото. Бережно переносит мелкие детали ткани и надписи. Лицензия MIT, но обучающие данные некоммерческие.',
    tasks: ['Примерка одежды на фото модели', 'Смена позы модели на уже снятом кадре', 'Добор ракурсов для карточки товара'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Фото-студии и контент-отделы'],
    versions: [['Leffa: примерка (VITON-HD) и смена позы', '2024-12'], ['Leffa: примерка (DressCode)', '2024-12']],
    hf: 'https://huggingface.co/franciszzj/Leffa',
    github: 'https://github.com/franciszzj/Leffa',
    alternatives: ['idm-vton', 'fashn-vton', 'catvton'],
    source: 'https://github.com/franciszzj/Leffa',
    verified: true,
    en: {
      summary: 'Meta\'s model for virtual try-on and changing a person\'s pose in a photo. Carefully transfers fine fabric details and lettering. MIT license, but the training data is non-commercial.',
      tasks: ['Trying clothes on a model photo', 'Changing the model pose in an existing shot', 'Adding extra angles for a product card'],
      where: ['Online apparel retail', 'Marketplaces', 'Photo studios and content teams'],
      license: 'MIT for code and weights, but the weights were trained on the VITON-HD and DressCode datasets with non-commercial terms — for business use, check with a lawyer',
      developer: 'Meta AI (with King\'s College London)',
      country: 'USA',
      sizes: 'based on Stable Diffusion',
    },
  },
  {
    id: 'stableviton',
    name: 'StableVITON',
    developer: 'KAIST', country: 'Южная Корея',
    modality: ['tryon'],
    first: '2024-02', latest: '2024-02',
    sizes: 'на базе Stable Diffusion',
    license: 'CC BY-NC-SA 4.0 (только некоммерческое использование)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'science', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Исследовательская модель примерки с конференции CVPR 2024, одна из первых на базе Stable Diffusion. Сейчас чаще служит точкой сравнения.',
    tasks: ['Пилот примерки верхней одежды', 'Сравнение качества разных моделей примерки', 'Обучение своей примерки на базе открытого кода'],
    where: ['Онлайн-торговля одеждой', 'Исследовательские отделы ритейла', 'Образование'],
    versions: [['StableVITON', '2024-02']],
    hf: 'https://huggingface.co/rlawjdghek/StableVITON',
    github: 'https://github.com/rlawjdghek/StableVITON',
    alternatives: ['idm-vton', 'ootdiffusion'],
    source: 'https://github.com/rlawjdghek/StableVITON',
    verified: true,
    en: {
      summary: 'A research try-on model from CVPR 2024, one of the first built on Stable Diffusion. Now mostly used as a comparison baseline.',
      tasks: ['Pilot of upper-body garment try-on', 'Comparing quality of different try-on models', 'Training your own try-on on the open code'],
      where: ['Online apparel retail', 'Retail research departments', 'Education'],
      license: 'CC BY-NC-SA 4.0 (non-commercial use only)',
      country: 'South Korea',
      sizes: 'based on Stable Diffusion',
    },
  },
  {
    id: 'fitdit',
    name: 'FitDiT',
    developer: 'Tencent и Фуданьский университет', country: 'Китай',
    modality: ['tryon'],
    first: '2024-12', latest: '2024-12',
    sizes: 'на базе SD3',
    license: 'CC BY-NC-SA 4.0 (только некоммерческое использование)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail'],
    ollama: false,
    cpu: false,
    summary: 'Примерка на трансформере от Tencent: точнее передаёт фактуру ткани, мелкий принт и длину вещи. Лицензия некоммерческая.',
    tasks: ['Примерка вещей со сложным принтом и фактурой', 'Карточки товара на модели для тестов', 'Подбор длины и посадки на фото'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Фэшн-бренды'],
    versions: [['FitDiT', '2024-12']],
    hf: 'https://huggingface.co/BoyuanJiang/FitDiT',
    github: 'https://github.com/BoyuanJiang/FitDiT',
    alternatives: ['idm-vton', 'leffa', 'fashn-vton'],
    source: 'https://github.com/BoyuanJiang/FitDiT',
    verified: true,
    en: {
      summary: 'Tencent\'s transformer-based try-on: more accurately reproduces fabric texture, fine prints and garment length. Non-commercial license.',
      tasks: ['Try-on of items with complex prints and textures', 'Test product cards on a model', 'Checking length and fit on a photo'],
      where: ['Online apparel retail', 'Marketplaces', 'Fashion brands'],
      license: 'CC BY-NC-SA 4.0 (non-commercial use only)',
      developer: 'Tencent and Fudan University',
      country: 'China',
      sizes: 'based on SD3',
    },
  },
  {
    id: 'any2anytryon',
    name: 'Any2AnyTryon',
    developer: 'Пекинский университет почты и связи и др.', country: 'Китай',
    modality: ['tryon'],
    first: '2025-02', latest: '2025-02',
    sizes: 'дополнения (LoRA) к FLUX.1 dev 12B',
    license: 'Лицензия не указана; работает поверх FLUX.1 [dev] с некоммерческой лицензией',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Универсальный набор для одежды на базе FLUX: примерка, генерация модели в заданной вещи и «снятие» вещи с человека в отдельное фото товара.',
    tasks: ['Примерка по фото товара', 'Фото модели в вещи по текстовому описанию', 'Чистое фото вещи со снимка человека'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Контент-отделы'],
    versions: [['Any2AnyTryon (набор LoRA)', '2025-02']],
    hf: 'https://huggingface.co/loooooong/Any2anyTryon',
    github: 'https://github.com/logn-2024/Any2anyTryon',
    alternatives: ['omnitry', 'fastfit', 'flux'],
    source: 'https://huggingface.co/api/models/loooooong/Any2anyTryon',
    verified: true,
    en: {
      summary: 'An all-round FLUX-based apparel toolkit: try-on, generating a model wearing a given item, and "taking off" an item from a person into a separate product photo.',
      tasks: ['Try-on from a product photo', 'Photo of a model wearing an item from a text description', 'Clean product photo extracted from a shot of a person'],
      where: ['Online apparel retail', 'Marketplaces', 'Content teams'],
      license: 'License not stated; runs on top of FLUX.1 [dev] with a non-commercial license',
      developer: 'Beijing University of Posts and Telecommunications and others',
      country: 'China',
      sizes: 'add-ons (LoRA) for FLUX.1 dev 12B',
    },
  },
  {
    id: 'omnitry',
    name: 'OmniTry',
    developer: 'Kunbyte AI', country: 'Китай',
    modality: ['tryon'],
    first: '2025-08', latest: '2025-08',
    sizes: 'дополнение к FLUX.1 Fill dev 12B',
    license: 'Apache 2.0 для самой модели, но нужна базовая FLUX.1 Fill [dev] с некоммерческой лицензией (для бизнеса — лицензия Black Forest Labs)',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail'],
    ollama: false,
    cpu: false,
    summary: 'Примерка не только одежды: очки, серьги, сумки, шляпы, часы и другие аксессуары. Работает без маски. Требует видеокарту от 28 ГБ.',
    tasks: ['Примерка аксессуаров и украшений на фото', 'Карточки товара с аксессуаром на модели', 'Примерочная очков и бижутерии на сайте'],
    where: ['Ювелирные и оптика', 'Онлайн-торговля аксессуарами', 'Маркетплейсы'],
    versions: [['OmniTry', '2025-08']],
    hf: 'https://huggingface.co/Kunbyte/OmniTry',
    github: 'https://github.com/Kunbyte-AI/OmniTry',
    alternatives: ['any2anytryon', 'fashn-vton', 'flux'],
    source: 'https://github.com/Kunbyte-AI/OmniTry',
    verified: true,
    en: {
      summary: 'Try-on beyond clothing: glasses, earrings, bags, hats, watches and other accessories. Works without a mask. Needs a GPU with 28 GB or more.',
      tasks: ['Trying accessories and jewelry on a photo', 'Product cards with an accessory on a model', 'Online fitting room for eyewear and jewelry'],
      where: ['Jewelry and eyewear', 'Online accessory retail', 'Marketplaces'],
      license: 'Apache 2.0 for the model itself, but it requires the base FLUX.1 Fill [dev] with a non-commercial license (for business — a Black Forest Labs license)',
      country: 'China',
      sizes: 'add-on for FLUX.1 Fill dev 12B',
    },
  },
  {
    id: 'fashn-vton',
    name: 'FASHN VTON',
    developer: 'FASHN AI', country: 'Израиль',
    modality: ['tryon'],
    first: '2026-01', latest: '2026-02',
    sizes: '972M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['retail'],
    ollama: false,
    cpu: false,
    summary: 'Редкая открытая примерка с коммерческой лицензией: без маски, берёт фото вещи на модели или раскладку. Веса около 2 ГБ.',
    tasks: ['Карточки товара на модели без фотосессии', 'Примерочная на сайте магазина', 'Каталог из фото раскладки одежды'],
    where: ['Онлайн-торговля одеждой', 'Маркетплейсы', 'Фэшн-бренды'],
    versions: [['FASHN VTON v1.5', '2026-01']],
    hf: 'https://huggingface.co/fashn-ai/fashn-vton-1.5',
    github: 'https://github.com/fashn-AI/fashn-vton-1.5',
    alternatives: ['leffa', 'idm-vton', 'omnitry'],
    source: 'https://huggingface.co/fashn-ai/fashn-vton-1.5',
    verified: true,
    en: {
      summary: 'A rare open try-on model with a commercial license: mask-free, accepts a photo of the item on a model or a flat lay. Weights are about 2 GB.',
      tasks: ['Product cards on a model without a photo shoot', 'Fitting room on a store website', 'Catalog from flat-lay clothing photos'],
      where: ['Online apparel retail', 'Marketplaces', 'Fashion brands'],
      license: 'Apache 2.0',
      country: 'Israel',
    },
  },

  // ---------- Удаление фона ----------
  {
    id: 'rmbg',
    name: 'BRIA RMBG',
    developer: 'BRIA AI', country: 'Израиль',
    modality: ['photo', 'video'],
    first: '2023-12', latest: '2026-05',
    sizes: '44M – 220M',
    license: 'Некоммерческая лицензия BRIA (RMBG-2.0 — CC BY-NC 4.0); для бизнеса — платная лицензия BRIA',
    commercial: 'no',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Удаление фона от BRIA, обучено на лицензированных фото. Мягкие края, волосы, прозрачность. Есть версии для видео. Для бизнеса нужен платный договор.',
    tasks: ['Вырезка товара на белый фон', 'Фото сотрудников и экспертов без фона', 'Удаление фона на видео'],
    where: ['Онлайн-торговля и маркетплейсы', 'Реклама и дизайн', 'Фото-студии'],
    versions: [['RMBG-1.4', '2023-12'], ['RMBG-2.0', '2024-10'], ['VRMBG-2.0 (видео)', '2025-12'], ['VRMBG-3.0 (видео)', '2026-05']],
    hf: 'https://huggingface.co/briaai/RMBG-2.0',
    github: 'https://github.com/Bria-AI/RMBG-2.0',
    alternatives: ['birefnet', 'ben2', 'inspyrenet'],
    source: 'https://huggingface.co/api/models?author=briaai',
    verified: true,
    en: {
      summary: 'BRIA\'s background removal, trained on licensed photos. Soft edges, hair, transparency. Video versions available. Business use requires a paid agreement.',
      tasks: ['Cutting products out onto a white background', 'Staff and expert photos without background', 'Background removal in video'],
      where: ['Online retail and marketplaces', 'Advertising and design', 'Photo studios'],
      license: 'BRIA non-commercial license (RMBG-2.0 — CC BY-NC 4.0); for business — paid BRIA license',
      country: 'Israel',
    },
  },
  {
    id: 'birefnet',
    name: 'BiRefNet',
    developer: 'Нанькайский университет', country: 'Китай',
    modality: ['photo', 'vision'],
    first: '2024-03', latest: '2025-07',
    sizes: 'около 220M (есть облегчённые lite)',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Открытая модель точного выделения объекта и удаления фона под лицензией MIT. На ней построен RMBG-2.0. Есть версии для 2K и для волос и полупрозрачных краёв.',
    tasks: ['Удаление фона с фото товаров потоком', 'Точные маски для дизайна и печати', 'Вырезка людей с волосами для рекламы'],
    where: ['Онлайн-торговля и маркетплейсы', 'Реклама и дизайн', 'Полиграфия'],
    versions: [['BiRefNet', '2024-03'], ['BiRefNet lite', '2024-08'], ['BiRefNet matting', '2024-10'], ['BiRefNet HR (2K)', '2025-02'], ['BiRefNet dynamic', '2025-03'], ['BiRefNet dynamic matting', '2025-07']],
    hf: 'https://huggingface.co/ZhengPeng7/BiRefNet',
    github: 'https://github.com/ZhengPeng7/BiRefNet',
    alternatives: ['rmbg', 'ben2', 'inspyrenet'],
    source: 'https://huggingface.co/api/models?author=ZhengPeng7',
    verified: true,
    en: {
      summary: 'An open MIT-licensed model for precise object segmentation and background removal. RMBG-2.0 is built on it. Versions for 2K and for hair and semi-transparent edges.',
      tasks: ['Bulk background removal from product photos', 'Precise masks for design and print', 'Cutting out people with hair for advertising'],
      where: ['Online retail and marketplaces', 'Advertising and design', 'Printing'],
      license: 'MIT',
      developer: 'Nankai University',
      country: 'China',
      sizes: 'about 220M (lightweight lite versions available)',
    },
  },
  {
    id: 'ben2',
    name: 'BEN2',
    developer: 'Prama LLC', country: 'США',
    modality: ['photo', 'video'],
    first: '2024-11', latest: '2025-01',
    sizes: 'около 95M',
    license: 'BEN — Apache 2.0, BEN2 base — MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Модель удаления фона с упором на сложные края: волосы, мех, тонкие детали. Открытая версия под MIT, умеет обрабатывать видео.',
    tasks: ['Вырезка товара и людей с фото', 'Удаление фона на видео', 'Подготовка фото для каталога'],
    where: ['Онлайн-торговля', 'Реклама и SMM', 'Видеопродакшн'],
    versions: [['BEN', '2024-11'], ['BEN2 base', '2025-01']],
    hf: 'https://huggingface.co/PramaLLC/BEN2',
    github: 'https://github.com/PramaLLC/BEN2',
    alternatives: ['birefnet', 'rmbg'],
    source: 'https://huggingface.co/api/models?author=PramaLLC',
    verified: true,
    en: {
      summary: 'A background removal model focused on difficult edges: hair, fur, fine details. The open version is MIT-licensed and can process video.',
      tasks: ['Cutting out products and people from photos', 'Background removal in video', 'Preparing photos for a catalog'],
      where: ['Online retail', 'Advertising and social media', 'Video production'],
      license: 'BEN — Apache 2.0, BEN2 base — MIT',
      country: 'USA',
      sizes: 'about 95M',
    },
  },
  {
    id: 'inspyrenet',
    name: 'InSPyReNet / transparent-background',
    developer: 'Ким Тэхун (POSTECH)', country: 'Южная Корея',
    modality: ['photo', 'video'],
    first: '2022-10', latest: '2023-09',
    sizes: 'небольшая (на базе Swin-B)',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Модель выделения главного объекта и готовая программа transparent-background на её основе: убирает фон с фото, видео и веб-камеры одной командой.',
    tasks: ['Пакетное удаление фона с фото', 'Замена фона на цвет или размытие', 'Удаление фона на видео'],
    where: ['Онлайн-торговля', 'Фото-студии', 'Дизайн'],
    versions: [['InSPyReNet (DIS5K)', '2022-10'], ['transparent-background 1.0', '2022-11'], ['base-nightly', '2023-09']],
    hf: null,
    github: 'https://github.com/plemeri/transparent-background',
    alternatives: ['birefnet', 'rmbg', 'ben2'],
    source: 'https://github.com/plemeri/transparent-background',
    verified: true,
    en: {
      summary: 'A salient object detection model and the ready-made transparent-background tool built on it: removes backgrounds from photos, video and webcam with one command.',
      tasks: ['Batch background removal from photos', 'Replacing the background with a color or blur', 'Background removal in video'],
      where: ['Online retail', 'Photo studios', 'Design'],
      license: 'MIT',
      developer: 'Taehoon Kim (POSTECH)',
      country: 'South Korea',
      sizes: 'small (based on Swin-B)',
    },
  },

  // ---------- Апскейл и восстановление ----------
  {
    id: 'real-esrgan',
    name: 'Real-ESRGAN',
    developer: 'Tencent ARC Lab', country: 'Китай',
    modality: ['photo'],
    first: '2021-07', latest: '2022-04',
    sizes: 'около 17M',
    license: 'BSD-3-Clause',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Классика увеличения фото в 2–4 раза с очисткой от шума и артефактов сжатия. Лёгкая, работает даже на процессоре. Есть версии для рисунков и аниме.',
    tasks: ['Увеличение старых и мелких фото товаров', 'Очистка картинок от артефактов сжатия', 'Подготовка изображений к печати'],
    where: ['Онлайн-торговля', 'Полиграфия', 'Медиа и архивы'],
    versions: [['Real-ESRGAN x4plus', '2021-07'], ['Real-ESRGAN anime 6B', '2021-08'], ['realesr-general-x4v3 и AnimeVideo-v3', '2022-04']],
    hf: null,
    github: 'https://github.com/xinntao/Real-ESRGAN',
    alternatives: ['hat', 'seedvr', 'supir'],
    source: 'https://github.com/xinntao/Real-ESRGAN/releases',
    verified: true,
    en: {
      summary: 'The classic for upscaling photos 2–4x while cleaning noise and compression artifacts. Lightweight, runs even on a CPU. Versions for drawings and anime.',
      tasks: ['Upscaling old and small product photos', 'Cleaning images of compression artifacts', 'Preparing images for print'],
      where: ['Online retail', 'Printing', 'Media and archives'],
      license: 'BSD-3-Clause',
      country: 'China',
      sizes: 'about 17M',
    },
  },
  {
    id: 'swinir',
    name: 'SwinIR',
    developer: 'ETH Zurich', country: 'Швейцария',
    modality: ['photo'],
    first: '2021-08', latest: '2021-08',
    sizes: 'около 12M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['media', 'retail'],
    ollama: false,
    cpu: true,
    summary: 'Модель на трансформере для увеличения, шумоподавления и очистки фото от артефактов JPEG. Лёгкая и проверенная, часто стоит внутри других систем.',
    tasks: ['Увеличение фото', 'Шумоподавление снимков', 'Очистка от артефактов сжатия'],
    where: ['Медиа и архивы', 'Полиграфия', 'Онлайн-торговля'],
    versions: [['SwinIR', '2021-08']],
    hf: null,
    github: 'https://github.com/JingyunLiang/SwinIR',
    alternatives: ['hat', 'real-esrgan'],
    source: 'https://github.com/JingyunLiang/SwinIR/releases',
    verified: true,
    en: {
      summary: 'A transformer model for upscaling, denoising and removing JPEG artifacts from photos. Lightweight and proven; often embedded in other systems.',
      tasks: ['Photo upscaling', 'Image denoising', 'Removing compression artifacts'],
      where: ['Media and archives', 'Printing', 'Online retail'],
      license: 'Apache 2.0',
      country: 'Switzerland',
      sizes: 'about 12M',
    },
  },
  {
    id: 'hat',
    name: 'HAT',
    developer: 'XPixel Group (Шэньчжэньский институт передовых технологий АН Китая и др.)', country: 'Китай',
    modality: ['photo'],
    first: '2022-05', latest: '2023-08',
    sizes: '9M – 40M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['media', 'retail'],
    ollama: false,
    cpu: true,
    summary: 'Увеличение фото на трансформере, точнее SwinIR на тонких деталях. Есть версии для реальных снимков с шумом и лёгкая HAT-S.',
    tasks: ['Увеличение фото товаров и интерьеров', 'Подготовка изображений к печати', 'Повышение чёткости архивных снимков'],
    where: ['Полиграфия', 'Онлайн-торговля', 'Медиа и архивы'],
    versions: [['HAT', '2022-05'], ['Real HAT GAN', '2022-11'], ['HAT-S', '2023-04'], ['Real HAT GAN sharper', '2023-08']],
    hf: null,
    github: 'https://github.com/XPixelGroup/HAT',
    alternatives: ['swinir', 'real-esrgan', 'supir'],
    source: 'https://github.com/XPixelGroup/HAT',
    verified: true,
    en: {
      summary: 'Transformer-based photo upscaling, more accurate than SwinIR on fine details. Versions for real noisy photos and a lightweight HAT-S.',
      tasks: ['Upscaling product and interior photos', 'Preparing images for print', 'Sharpening archival photos'],
      where: ['Printing', 'Online retail', 'Media and archives'],
      license: 'Apache 2.0',
      developer: 'XPixel Group (Shenzhen Institutes of Advanced Technology, Chinese Academy of Sciences, and others)',
      country: 'China',
    },
  },
  {
    id: 'supir',
    name: 'SUPIR',
    developer: 'XPixel Group (Шэньчжэньский институт передовых технологий АН Китая, Shanghai AI Lab и др.)', country: 'Китай',
    modality: ['photo'],
    first: '2024-02', latest: '2024-02',
    sizes: 'на базе SDXL, плюс LLaVA 13B для описаний',
    license: 'Только некоммерческое использование (коммерция — по письменному разрешению авторов)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['media', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Мощное восстановление сильно испорченных фото на базе SDXL: дорисовывает детали, а не просто увеличивает. Требовательна к железу, лицензия некоммерческая.',
    tasks: ['Восстановление старых и размытых фото', 'Увеличение снимков с дорисовкой деталей', 'Пилоты реставрации архивов'],
    where: ['Медиа и архивы', 'Фото-студии', 'Музеи и библиотеки'],
    versions: [['SUPIR v0Q и v0F', '2024-02']],
    hf: null,
    github: 'https://github.com/Fanghua-Yu/SUPIR',
    alternatives: ['seedvr', 'stablesr', 'flux-upscaler'],
    source: 'https://github.com/Fanghua-Yu/SUPIR',
    verified: true,
    en: {
      summary: 'Powerful SDXL-based restoration of badly damaged photos: it recreates details rather than just upscaling. Hardware-hungry; non-commercial license.',
      tasks: ['Restoring old and blurry photos', 'Upscaling with detail reconstruction', 'Archive restoration pilots'],
      where: ['Media and archives', 'Photo studios', 'Museums and libraries'],
      license: 'Non-commercial use only (commercial use with the authors\' written permission)',
      developer: 'XPixel Group (Shenzhen Institutes of Advanced Technology, Chinese Academy of Sciences, Shanghai AI Lab and others)',
      country: 'China',
      sizes: 'based on SDXL, plus LLaVA 13B for captions',
    },
  },
  {
    id: 'stablesr',
    name: 'StableSR',
    developer: 'S-Lab, Наньянский технологический университет', country: 'Сингапур',
    modality: ['photo'],
    first: '2023-05', latest: '2023-05',
    sizes: 'на базе SD 2.1',
    license: 'NTU S-Lab License 1.0 (некоммерческая)',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['media', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Одна из первых моделей увеличения фото на базе Stable Diffusion: восстанавливает реалистичные детали. Лицензия некоммерческая.',
    tasks: ['Увеличение фото с дорисовкой деталей', 'Исследовательские пилоты реставрации', 'Сравнение с классическими апскейлерами'],
    where: ['Медиа и архивы', 'Фото-студии', 'Образование'],
    versions: [['StableSR', '2023-05']],
    hf: 'https://huggingface.co/Iceclear/StableSR',
    github: 'https://github.com/IceClear/StableSR',
    alternatives: ['supir', 'seedvr'],
    source: 'https://github.com/IceClear/StableSR',
    verified: true,
    en: {
      summary: 'One of the first Stable Diffusion-based photo upscalers: restores realistic details. Non-commercial license.',
      tasks: ['Upscaling photos with detail reconstruction', 'Research restoration pilots', 'Comparison with classic upscalers'],
      where: ['Media and archives', 'Photo studios', 'Education'],
      license: 'NTU S-Lab License 1.0 (non-commercial)',
      developer: 'S-Lab, Nanyang Technological University',
      country: 'Singapore',
      sizes: 'based on SD 2.1',
    },
  },
  {
    id: 'seedvr',
    name: 'SeedVR / SeedVR2',
    developer: 'ByteDance Seed', country: 'Китай',
    modality: ['photo', 'video'],
    first: '2025-06', latest: '2025-06',
    sizes: '3B – 7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'na',
    industries: ['media', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Восстановление и увеличение видео и фото от ByteDance. SeedVR2 делает это за один шаг, поэтому заметно быстрее похожих моделей. Коммерческая лицензия.',
    tasks: ['Увеличение фото и видео до 2K–4K', 'Восстановление старых роликов и снимков', 'Улучшение пользовательских фото перед публикацией'],
    where: ['Медиа и видеопродакшн', 'Архивы', 'Онлайн-торговля'],
    versions: [['SeedVR-7B', '2025-06'], ['SeedVR2-3B', '2025-06'], ['SeedVR2-7B', '2025-06']],
    hf: 'https://huggingface.co/ByteDance-Seed/SeedVR2-7B',
    github: 'https://github.com/ByteDance-Seed/SeedVR',
    alternatives: ['supir', 'real-esrgan', 'flux-upscaler'],
    source: 'https://huggingface.co/api/models/ByteDance-Seed/SeedVR2-7B',
    verified: true,
    en: {
      summary: 'ByteDance\'s video and photo restoration and upscaling. SeedVR2 does it in a single step, so it is noticeably faster than similar models. Commercial-friendly license.',
      tasks: ['Upscaling photos and video to 2K–4K', 'Restoring old videos and photos', 'Enhancing user photos before publishing'],
      where: ['Media and video production', 'Archives', 'Online retail'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'flux-upscaler',
    name: 'Flux.1-dev ControlNet Upscaler',
    developer: 'Jasper AI', country: 'США',
    modality: ['photo'],
    first: '2024-09', latest: '2024-09',
    sizes: 'дополнение к FLUX.1 dev 12B',
    license: 'FLUX.1 [dev] Non-Commercial License',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Дополнение к FLUX для увеличения маленьких и размытых картинок с дорисовкой деталей. Популярно, но под некоммерческой лицензией FLUX dev.',
    tasks: ['Увеличение мелких картинок с дорисовкой', 'Улучшение сгенерированных изображений', 'Пилоты апскейла для каталога'],
    where: ['Реклама и дизайн', 'Контент-отделы', 'Онлайн-торговля'],
    versions: [['Flux.1-dev ControlNet Upscaler', '2024-09']],
    hf: 'https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Upscaler',
    github: null,
    alternatives: ['seedvr', 'supir', 'flux'],
    source: 'https://huggingface.co/api/models/jasperai/Flux.1-dev-Controlnet-Upscaler',
    verified: true,
    en: {
      summary: 'A FLUX add-on for upscaling small and blurry images with detail reconstruction. Popular, but under the non-commercial FLUX dev license.',
      tasks: ['Upscaling small images with detail reconstruction', 'Enhancing generated images', 'Upscaling pilots for a catalog'],
      where: ['Advertising and design', 'Content teams', 'Online retail'],
      license: 'FLUX.1 [dev] Non-Commercial License',
      country: 'USA',
      sizes: 'add-on for FLUX.1 dev 12B',
    },
  },

  // ---------- Реставрация лиц ----------
  {
    id: 'codeformer',
    name: 'CodeFormer',
    developer: 'S-Lab, Наньянский технологический университет', country: 'Сингапур',
    modality: ['photo'],
    first: '2022-08', latest: '2023-04',
    sizes: 'небольшая, до 0.1B',
    license: 'NTU S-Lab License 1.0 (некоммерческая)',
    commercial: 'no',
    hardware: ['min'],
    ru: 'na',
    industries: ['media'],
    ollama: false,
    cpu: true,
    summary: 'Популярная реставрация лиц на старых и размытых фото, работает и с видео. Есть режимы дорисовки и окрашивания лица. Лицензия некоммерческая.',
    tasks: ['Восстановление лиц на старых фото', 'Улучшение лиц на видео низкого качества', 'Пилоты реставрации семейных архивов'],
    where: ['Фото-студии и фотосалоны', 'Медиа и архивы', 'Музеи'],
    versions: [['CodeFormer', '2022-08'], ['Модели дорисовки и окрашивания лиц', '2023-04']],
    hf: null,
    github: 'https://github.com/sczhou/CodeFormer',
    alternatives: ['gfpgan', 'supir'],
    source: 'https://github.com/sczhou/CodeFormer',
    verified: true,
    en: {
      summary: 'Popular face restoration for old and blurry photos; also works on video. Has face inpainting and colorization modes. Non-commercial license.',
      tasks: ['Restoring faces in old photos', 'Enhancing faces in low-quality video', 'Family archive restoration pilots'],
      where: ['Photo studios and photo shops', 'Media and archives', 'Museums'],
      license: 'NTU S-Lab License 1.0 (non-commercial)',
      developer: 'S-Lab, Nanyang Technological University',
      country: 'Singapore',
      sizes: 'small, up to 0.1B',
    },
  },
  {
    id: 'gfpgan',
    name: 'GFPGAN',
    developer: 'Tencent ARC Lab', country: 'Китай',
    modality: ['photo'],
    first: '2021-06', latest: '2022-02',
    sizes: 'небольшая, до 0.1B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['media'],
    ollama: false,
    cpu: true,
    summary: 'Проверенная реставрация лиц на старых и сжатых фото с коммерческой лицензией. Часто работает в паре с Real-ESRGAN, самые ходовые версии 1.3 и 1.4.',
    tasks: ['Восстановление лиц на старых фото', 'Улучшение аватаров и фото профиля', 'Реставрация в фотосалоне или онлайн-сервисе'],
    where: ['Фото-студии и фотосалоны', 'Медиа и архивы', 'Онлайн-сервисы обработки фото'],
    versions: [['GFPGAN v1', '2021-06'], ['GFPGAN v1.2', '2021-08'], ['GFPGAN v1.3', '2022-02']],
    hf: null,
    github: 'https://github.com/TencentARC/GFPGAN',
    alternatives: ['codeformer', 'real-esrgan'],
    source: 'https://github.com/TencentARC/GFPGAN/releases',
    verified: true,
    en: {
      summary: 'Proven face restoration for old and compressed photos, with a commercial-friendly license. Often paired with Real-ESRGAN; the most used versions are 1.3 and 1.4.',
      tasks: ['Restoring faces in old photos', 'Enhancing avatars and profile photos', 'Restoration in a photo shop or online service'],
      where: ['Photo studios and photo shops', 'Media and archives', 'Online photo editing services'],
      license: 'Apache 2.0',
      country: 'China',
      sizes: 'small, up to 0.1B',
    },
  },

  // ---------- Удаление объектов, свет, цвет ----------
  {
    id: 'lama',
    name: 'LaMa',
    developer: 'Samsung AI Center Москва (вместе со Сколтехом)', country: 'Россия',
    modality: ['photo'],
    first: '2021-09', latest: '2021-09',
    sizes: 'около 51M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Удаление лишних объектов, надписей и водяных знаков с фото с аккуратной дорисовкой фона. Лёгкая и быстрая, до сих пор стандарт для такой задачи.',
    tasks: ['Удаление ценников, людей и мусора с фото', 'Чистка фото интерьеров и недвижимости', 'Удаление надписей и дат с архивных снимков'],
    where: ['Недвижимость', 'Онлайн-торговля', 'Фото-студии'],
    versions: [['LaMa и Big-LaMa', '2021-09']],
    hf: null,
    github: 'https://github.com/advimman/lama',
    alternatives: ['powerpaint', 'flux'],
    source: 'https://github.com/advimman/lama',
    verified: true,
    en: {
      summary: 'Removes unwanted objects, text and watermarks from photos with clean background fill. Lightweight and fast; still the standard for this task.',
      tasks: ['Removing price tags, people and clutter from photos', 'Cleaning interior and real estate photos', 'Removing text and dates from archival photos'],
      where: ['Real estate', 'Online retail', 'Photo studios'],
      license: 'Apache 2.0',
      developer: 'Samsung AI Center Moscow (with Skoltech)',
      country: 'Russia',
      sizes: 'about 51M',
    },
  },
  {
    id: 'powerpaint',
    name: 'PowerPaint',
    developer: 'Shanghai AI Laboratory (OpenMMLab) и Университет Цинхуа', country: 'Китай',
    modality: ['photo', 'image'],
    first: '2023-12', latest: '2024-05',
    sizes: 'на базе SD 1.5',
    license: 'MIT (код), Apache 2.0 (веса v2-1)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['marketing', 'retail', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Универсальная дорисовка фото: убрать объект, вставить новый по описанию, заменить форму или расширить кадр за края.',
    tasks: ['Удаление и замена объектов на фото', 'Расширение кадра под нужный формат', 'Вставка товара или детали по текстовому описанию'],
    where: ['Реклама и дизайн', 'Онлайн-торговля', 'Недвижимость'],
    versions: [['PowerPaint v1', '2023-12'], ['PowerPaint v2', '2024-04'], ['PowerPaint v2-1', '2024-05']],
    hf: 'https://huggingface.co/JunhaoZhuang/PowerPaint-v2-1',
    github: 'https://github.com/open-mmlab/PowerPaint',
    alternatives: ['lama', 'flux', 'controlnet'],
    source: 'https://github.com/open-mmlab/PowerPaint',
    verified: true,
    en: {
      summary: 'All-round photo inpainting: remove an object, insert a new one from a description, change a shape or extend the frame beyond its edges.',
      tasks: ['Removing and replacing objects in photos', 'Extending the frame to a required format', 'Inserting a product or detail from a text description'],
      where: ['Advertising and design', 'Online retail', 'Real estate'],
      license: 'MIT (code), Apache 2.0 (v2-1 weights)',
      developer: 'Shanghai AI Laboratory (OpenMMLab) and Tsinghua University',
      country: 'China',
      sizes: 'based on SD 1.5',
    },
  },
  {
    id: 'ic-light',
    name: 'IC-Light',
    developer: 'Лвмин Чжан (автор ControlNet)', country: 'США',
    modality: ['photo', 'image'],
    first: '2024-05', latest: '2024-05',
    sizes: 'на базе SD 1.5',
    license: 'Apache 2.0 (новая версия IC-Light v2 на FLUX открытой не выложена)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Меняет освещение на фото: ставит объект или человека в новый свет по описанию или под заданный фон, чтобы вырезка смотрелась естественно.',
    tasks: ['Подгонка света товара под новый фон', 'Студийный свет для портретов без пересъёмки', 'Единый стиль освещения в каталоге'],
    where: ['Онлайн-торговля', 'Реклама и дизайн', 'Фото-студии'],
    versions: [['IC-Light (по тексту и по фону)', '2024-05']],
    hf: 'https://huggingface.co/lllyasviel/ic-light',
    github: 'https://github.com/lllyasviel/IC-Light',
    alternatives: ['controlnet', 'stable-diffusion', 'rmbg'],
    source: 'https://github.com/lllyasviel/IC-Light',
    verified: true,
    en: {
      summary: 'Changes lighting in a photo: relights an object or person from a description or to match a given background, so a cut-out looks natural.',
      tasks: ['Matching product lighting to a new background', 'Studio lighting for portraits without a reshoot', 'Consistent lighting style across a catalog'],
      where: ['Online retail', 'Advertising and design', 'Photo studios'],
      license: 'Apache 2.0 (the newer FLUX-based IC-Light v2 has not been released openly)',
      developer: 'Lvmin Zhang (author of ControlNet)',
      country: 'USA',
      sizes: 'based on SD 1.5',
    },
  },
  {
    id: 'ddcolor',
    name: 'DDColor',
    developer: 'Alibaba DAMO Academy', country: 'Китай',
    modality: ['photo'],
    first: '2023-09', latest: '2023-12',
    sizes: 'DDColor-T (tiny) и DDColor-L',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['media'],
    ollama: false,
    cpu: true,
    summary: 'Окрашивание чёрно-белых фото в естественные цвета. Лёгкая модель с коммерческой лицензией, есть компактная версия tiny.',
    tasks: ['Окрашивание архивных фото', 'Цветные версии исторических снимков для публикаций', 'Сервис оживления семейных фото'],
    where: ['Медиа и архивы', 'Музеи и библиотеки', 'Фото-студии'],
    versions: [['DDColor (три модели)', '2023-09'], ['DDColor tiny', '2023-12']],
    hf: 'https://huggingface.co/piddnad/DDColor-models',
    github: 'https://github.com/piddnad/DDColor',
    alternatives: ['codeformer', 'gfpgan'],
    source: 'https://github.com/piddnad/DDColor',
    verified: true,
    en: {
      summary: 'Colorizes black-and-white photos in natural colors. A lightweight model with a commercial-friendly license; a compact tiny version is available.',
      tasks: ['Colorizing archival photos', 'Color versions of historical photos for publications', 'Family photo restoration service'],
      where: ['Media and archives', 'Museums and libraries', 'Photo studios'],
      license: 'Apache 2.0',
      country: 'China',
      sizes: 'DDColor-T (tiny) and DDColor-L',
    },
  },
];
