// Модели зрения с текстом (VLM) и распознавание документов (OCR). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- VLM: картинка + текст ----------
  {
    id: 'llava',
    name: 'LLaVA',
    developer: 'LLaVA / LMMs-Lab (исследователи из США и Китая)', country: 'США / Китай',
    modality: ['vlm'],
    first: '2023-04', latest: '2026-05',
    sizes: '0.5B – 72B',
    license: 'Новые версии OneVision — Apache 2.0; первые LLaVA на Llama и Vicuna наследуют их лицензии',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'retail'],
    ollama: true,
    cpu: true,
    summary: 'Открытый проект, с которого пошла мода на модели «картинка + текст». Линейка OneVision понимает фото, документы и видео; открыты данные и рецепты обучения.',
    tasks: ['Ответы на вопросы по фото и скриншотам', 'Описание товаров по фотографии', 'Разбор видео по кадрам', 'Основа для дообучения своей визуальной модели'],
    where: ['Электронная коммерция', 'Исследовательские команды', 'Контроль контента'],
    versions: [['LLaVA', '2023-04'], ['LLaVA-1.5', '2023-10'], ['LLaVA-NeXT (1.6)', '2024-01'], ['LLaVA-OneVision', '2024-08'], ['LLaVA-OneVision-1.5', '2025-09'], ['LLaVA-OneVision-2-8B', '2026-05']],
    hf: 'https://huggingface.co/lmms-lab',
    github: 'https://github.com/LLaVA-VL/LLaVA-NeXT',
    alternatives: ['qwen-vl', 'internvl', 'molmo'],
    source: 'https://huggingface.co/lmms-lab-encoder/LLaVA-OneVision-2-8B-Instruct',
    verified: true,
  },
  {
    id: 'qwen-vl',
    name: 'Qwen-VL',
    developer: 'Alibaba (команда Qwen)', country: 'Китай',
    modality: ['vlm', 'ocr'],
    first: '2023-08', latest: '2025-10',
    sizes: '2B – 235B-A22B',
    license: 'Qwen3-VL — Apache 2.0; у старых Qwen-VL и части Qwen2/2.5-VL (3B, 72B) собственные лицензии Qwen',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown',
    industries: ['docs', 'retail', 'support', 'manufacturing'],
    ollama: true,
    cpu: true,
    summary: 'Одна из сильнейших открытых моделей зрения: читает документы, таблицы, графики, видео, работает с интерфейсами. С Qwen3.5 зрение встроено прямо в основную модель Qwen.',
    tasks: ['Извлечение данных из сканов счетов и накладных', 'Разбор фотографий товаров и витрин', 'Анализ видео и записей с камер', 'Агент, работающий с интерфейсом по скриншотам'],
    where: ['Бухгалтерия и документооборот', 'Розница и склад', 'Электронная коммерция', 'Службы поддержки'],
    versions: [['Qwen-VL', '2023-08'], ['Qwen2-VL', '2024-09'], ['Qwen2.5-VL', '2025-01'], ['Qwen2.5-VL-32B', '2025-03'], ['Qwen3-VL 235B-A22B и 30B-A3B', '2025-09'], ['Qwen3-VL 2B – 32B', '2025-10']],
    hf: 'https://huggingface.co/Qwen/Qwen3-VL-235B-A22B-Instruct',
    github: 'https://github.com/QwenLM/Qwen3-VL',
    alternatives: ['qwen', 'internvl', 'minicpm-v'],
    source: 'https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct',
    verified: true,
  },
  {
    id: 'internvl',
    name: 'InternVL',
    developer: 'Shanghai AI Laboratory (OpenGVLab)', country: 'Китай',
    modality: ['vlm'],
    first: '2023-12', latest: '2026-03',
    sizes: '1B – 241B-A28B',
    license: 'InternVL3.5 — Apache 2.0; InternVL-U — MIT; отдельные крупные версии наследуют лицензию базовой модели (например, Qwen)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown',
    industries: ['docs', 'science', 'manufacturing'],
    ollama: false,
    cpu: true,
    summary: 'Большая линейка китайских моделей зрения с размерами от 1B до 241B. InternVL-U (4B) объединяет понимание картинок, их генерацию и редактирование.',
    tasks: ['Понимание документов, схем и графиков', 'Ответы на вопросы по фото', 'Разбор видео', 'Генерация и правка картинок (InternVL-U)'],
    where: ['Документооборот', 'Промышленность и контроль качества', 'Электронная коммерция'],
    versions: [['InternVL', '2023-12'], ['InternVL 1.5', '2024-04'], ['InternVL2', '2024-07'], ['InternVL2.5', '2024-12'], ['InternVL3', '2025-04'], ['InternVL3.5', '2025-08'], ['InternVL-U', '2026-03']],
    hf: 'https://huggingface.co/OpenGVLab',
    github: 'https://github.com/OpenGVLab/InternVL',
    alternatives: ['qwen-vl', 'internlm', 'minicpm-v'],
    source: 'https://huggingface.co/InternVL-U/InternVL-U',
    verified: true,
  },
  {
    id: 'minicpm-v',
    name: 'MiniCPM-V',
    developer: 'OpenBMB (ModelBest и Университет Цинхуа)', country: 'Китай',
    modality: ['vlm', 'ocr'],
    first: '2024-01', latest: '2026-05',
    sizes: '1.3B – 8B',
    license: 'Apache 2.0 (у ранних версий была собственная лицензия MiniCPM с регистрацией для коммерции)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['docs', 'retail', 'support'],
    ollama: true,
    cpu: true,
    summary: 'Компактные модели зрения, которые работают даже на телефоне и ноутбуке. Хорошо читают текст на фото, понимают видео; версия 4.6 весит всего 1.3B.',
    tasks: ['Распознавание текста на фото прямо на устройстве', 'Разбор чеков и документов без отправки в облако', 'Описание фото и видео', 'Встроенный помощник в мобильное приложение'],
    where: ['Мобильные приложения', 'Розница', 'Полевые службы'],
    versions: [['MiniCPM-V', '2024-01'], ['MiniCPM-V 2.0', '2024-04'], ['MiniCPM-Llama3-V 2.5', '2024-05'], ['MiniCPM-V 2.6', '2024-08'], ['MiniCPM-V 4.0', '2025-07'], ['MiniCPM-V 4.5', '2025-08'], ['MiniCPM-V 4.6 и 4.6-Thinking', '2026-05']],
    hf: 'https://huggingface.co/openbmb/MiniCPM-V-4.6',
    github: 'https://github.com/OpenBMB/MiniCPM-V',
    alternatives: ['qwen-vl', 'smolvlm', 'minicpm-o'],
    source: 'https://huggingface.co/openbmb/MiniCPM-V-4.6',
    verified: true,
  },
  {
    id: 'cogvlm',
    name: 'CogVLM и GLM-V',
    developer: 'Zhipu AI (Z.ai) и Университет Цинхуа', country: 'Китай',
    modality: ['vlm'],
    first: '2023-11', latest: '2025-12',
    sizes: '9B – 106B-A12B',
    license: 'GLM-4.1V / 4.5V / 4.6V — MIT; CogVLM и CogVLM2 — собственные лицензии (CogVLM2 на базе Llama 3)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['docs', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Модели зрения от Zhipu: сначала CogVLM, затем линейка GLM-V. GLM-4.6V умеет вызывать инструменты по картинкам и работать как агент с интерфейсом.',
    tasks: ['Ответы на вопросы по фото и документам', 'Агент, работающий с интерфейсом по скриншотам', 'Разбор графиков и отчётов', 'Подписи к фото и видео'],
    where: ['Документооборот', 'Службы поддержки', 'Аналитика'],
    versions: [['CogVLM-17B', '2023-11'], ['CogAgent', '2023-12'], ['CogVLM2 19B', '2024-05'], ['GLM-4.1V-9B-Thinking', '2025-06'], ['GLM-4.5V 106B-A12B', '2025-08'], ['GLM-4.6V и GLM-4.6V-Flash 9B', '2025-12']],
    hf: 'https://huggingface.co/zai-org/GLM-4.6V',
    github: 'https://github.com/zai-org/GLM-V',
    alternatives: ['glm', 'qwen-vl', 'glm-ocr'],
    source: 'https://huggingface.co/zai-org/GLM-4.6V',
    verified: true,
  },
  {
    id: 'idefics',
    name: 'IDEFICS',
    developer: 'Hugging Face', country: 'Франция / США',
    modality: ['vlm'],
    first: '2023-07', latest: '2024-08',
    sizes: '8B – 80B',
    license: 'Idefics2 и Idefics3 — Apache 2.0; первая IDEFICS на LLaMA — только для исследований',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Открытые модели зрения от Hugging Face, воспроизводившие закрытую Flamingo. Idefics3 стала основой для компактной линейки SmolVLM.',
    tasks: ['Ответы на вопросы по картинкам', 'Разбор документов и скриншотов', 'Основа для дообучения'],
    where: ['Исследовательские команды', 'Электронная коммерция'],
    versions: [['IDEFICS 9B / 80B', '2023-07'], ['Idefics2-8B', '2024-04'], ['Idefics3-8B-Llama3', '2024-08']],
    hf: 'https://huggingface.co/HuggingFaceM4/Idefics3-8B-Llama3',
    github: null,
    alternatives: ['smolvlm', 'llava', 'molmo'],
    source: 'https://huggingface.co/HuggingFaceM4/Idefics3-8B-Llama3',
    verified: true,
  },
  {
    id: 'molmo',
    name: 'Molmo',
    developer: 'Ai2 (Allen Institute for AI)', country: 'США',
    modality: ['vlm'],
    first: '2024-09', latest: '2026-03',
    sizes: '1B-A7B – 72B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'manufacturing'],
    ollama: false,
    cpu: false,
    summary: 'Полностью открытые модели зрения Ai2 (веса и данные). Умеют указывать точку на картинке и считать предметы; Molmo2 понимает видео, MolmoWeb управляет браузером.',
    tasks: ['Подсчёт товаров и объектов на фото', 'Указание, где на снимке нужный предмет', 'Разбор видео', 'Агент, работающий с сайтами (MolmoWeb)'],
    where: ['Склад и розница', 'Промышленность', 'Исследовательские команды'],
    versions: [['Molmo 7B / 72B и MolmoE-1B', '2024-09'], ['Molmo2 4B / 8B', '2025-12'], ['MolmoPoint и MolmoWeb', '2026-03']],
    hf: 'https://huggingface.co/allenai/Molmo2-8B',
    github: 'https://github.com/allenai/molmo',
    alternatives: ['qwen-vl', 'moondream', 'molmoact'],
    source: 'https://huggingface.co/allenai/MolmoWeb-8B',
    verified: true,
  },
  {
    id: 'paligemma',
    name: 'PaliGemma',
    developer: 'Google', country: 'США',
    modality: ['vlm'],
    first: '2024-05', latest: '2024-11',
    sizes: '3B – 28B',
    license: 'Gemma Terms of Use (коммерция разрешена с правилами использования)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['science', 'manufacturing'],
    ollama: false,
    cpu: true,
    summary: 'Модель зрения Google на базе Gemma, задуманная как основа для дообучения под узкую задачу: подписи, поиск объектов, чтение текста.',
    tasks: ['Дообучение под свою задачу распознавания', 'Поиск объектов на фото', 'Чтение текста на изображениях', 'Подписи к фото'],
    where: ['Промышленность', 'Розница', 'Исследовательские команды'],
    versions: [['PaliGemma 3B', '2024-05'], ['PaliGemma 2 (3B, 10B, 28B)', '2024-11']],
    hf: 'https://huggingface.co/google/paligemma2-10b-mix-448',
    github: null,
    alternatives: ['gemma', 'florence-2', 'qwen-vl'],
    source: 'https://huggingface.co/google/paligemma2-28b-pt-896',
    verified: true,
  },
  {
    id: 'florence-2',
    name: 'Florence-2',
    developer: 'Microsoft', country: 'США',
    modality: ['vlm', 'vision'],
    first: '2024-06', latest: '2024-06',
    sizes: '0.23B – 0.77B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['manufacturing', 'media', 'retail'],
    ollama: false,
    cpu: true,
    summary: 'Очень маленькая модель зрения: подписи, поиск объектов, сегментация и чтение текста по одной команде. Работает даже на процессоре.',
    tasks: ['Чтение текста на фото', 'Поиск и выделение объектов', 'Автоматические подписи к фото', 'Разметка данных для обучения'],
    where: ['Промышленность', 'Розница', 'Разметка данных'],
    versions: [['Florence-2 base / large', '2024-06']],
    hf: 'https://huggingface.co/microsoft/Florence-2-large',
    github: null,
    alternatives: ['paligemma', 'moondream', 'grounding-dino'],
    source: 'https://huggingface.co/microsoft/Florence-2-large',
    verified: true,
  },
  {
    id: 'moondream',
    name: 'Moondream',
    developer: 'Moondream (M87 Labs)', country: 'США',
    modality: ['vlm'],
    first: '2024-01', latest: '2026-06',
    sizes: '2B – 9B-A2B',
    license: 'Moondream 2 — Apache 2.0; Moondream 3 — Moondream Model License (коммерция в своих продуктах разрешена, нельзя продавать доступ к самой модели как облачный сервис)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['manufacturing', 'retail', 'security'],
    ollama: true,
    cpu: true,
    summary: 'Небольшая и быстрая модель зрения для продуктовых задач: ответы на вопросы, поиск и указание объектов, подписи. Moondream 3.1 — MoE на 9B с 2B активных.',
    tasks: ['Поиск объектов и подсчёт на фото', 'Проверка фото из полевых отчётов', 'Подписи и теги для каталога', 'Обработка кадров с камер'],
    where: ['Розница и склад', 'Полевые службы', 'Электронная коммерция'],
    versions: [['moondream1', '2024-01'], ['moondream2', '2024-03'], ['Moondream 3 Preview', '2025-09'], ['Moondream 3.1 9B-A2B', '2026-06']],
    hf: 'https://huggingface.co/moondream/moondream3.1-9B-A2B',
    github: 'https://github.com/vikhyat/moondream',
    alternatives: ['florence-2', 'smolvlm', 'molmo'],
    source: 'https://huggingface.co/moondream/moondream3.1-9B-A2B',
    verified: true,
  },
  {
    id: 'smolvlm',
    name: 'SmolVLM',
    developer: 'Hugging Face', country: 'Франция / США',
    modality: ['vlm'],
    first: '2024-11', latest: '2025-04',
    sizes: '256M – 2.2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs', 'retail'],
    ollama: false,
    cpu: true,
    summary: 'Самые маленькие модели зрения Hugging Face: от 256M, работают в браузере и на телефоне. SmolVLM2 понимает и видео.',
    tasks: ['Описание фото и видео на слабом железе', 'Чтение простых документов', 'Встраивание в мобильные и офлайн-приложения'],
    where: ['Мобильные приложения', 'Встраиваемые устройства', 'Образование'],
    versions: [['SmolVLM 2B', '2024-11'], ['SmolVLM 256M / 500M', '2025-01'], ['SmolVLM2 (256M – 2.2B, видео)', '2025-02'], ['SmolVLM2-2.2B-Base', '2025-04']],
    hf: 'https://huggingface.co/HuggingFaceTB/SmolVLM2-2.2B-Instruct',
    github: null,
    alternatives: ['moondream', 'minicpm-v', 'docling'],
    source: 'https://huggingface.co/HuggingFaceTB/SmolVLM2-2.2B-Instruct',
    verified: true,
  },
  {
    id: 'kimi-vl',
    name: 'Kimi-VL',
    developer: 'Moonshot AI', country: 'Китай',
    modality: ['vlm'],
    first: '2025-04', latest: '2025-06',
    sizes: '16B-A3B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['docs', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Экономичная MoE-модель зрения (16B, активны 3B) с длинным контекстом и рассуждающей версией. Хорошо разбирает длинные документы и видео.',
    tasks: ['Разбор длинных PDF и презентаций', 'Ответы на вопросы по видео', 'Работа с интерфейсами по скриншотам'],
    where: ['Документооборот', 'Аналитика', 'Службы поддержки'],
    versions: [['Kimi-VL-A3B Instruct и Thinking', '2025-04'], ['Kimi-VL-A3B-Thinking-2506', '2025-06']],
    hf: 'https://huggingface.co/moonshotai/Kimi-VL-A3B-Thinking-2506',
    github: 'https://github.com/MoonshotAI/Kimi-VL',
    alternatives: ['kimi', 'qwen-vl', 'keye-vl'],
    source: 'https://huggingface.co/moonshotai/Kimi-VL-A3B-Thinking-2506',
    verified: true,
  },
  {
    id: 'janus',
    name: 'Janus',
    developer: 'DeepSeek', country: 'Китай',
    modality: ['vlm', 'image'],
    first: '2024-10', latest: '2025-01',
    sizes: '1B – 7B',
    license: 'Код — MIT, веса — DeepSeek Model License (коммерция разрешена, есть запреты на отдельные применения)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: true,
    summary: 'Одна модель и понимает картинки, и рисует их по описанию. Janus-Pro-7B была заметна в начале 2025 года, но по качеству картинок уступает специализированным моделям.',
    tasks: ['Ответы на вопросы по картинкам', 'Черновые иллюстрации по описанию', 'Эксперименты с единой моделью зрения и генерации'],
    where: ['Маркетинг', 'Исследовательские команды'],
    versions: [['Janus-1.3B', '2024-10'], ['JanusFlow-1.3B', '2024-11'], ['Janus-Pro 1B / 7B', '2025-01']],
    hf: 'https://huggingface.co/deepseek-ai/Janus-Pro-7B',
    github: 'https://github.com/deepseek-ai/Janus',
    alternatives: ['bagel', 'omnigen', 'qwen-vl'],
    source: 'https://huggingface.co/deepseek-ai/Janus-Pro-7B',
    verified: true,
  },
  {
    id: 'keye-vl',
    name: 'Keye-VL',
    developer: 'Kuaishou', country: 'Китай',
    modality: ['vlm'],
    first: '2025-06', latest: '2026-05',
    sizes: '8B – 671B-A37B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Модели зрения от Kuaishou с упором на короткие видео. Keye-VL-2.0 (30B, активны 3B) хорошо понимает, что и когда происходит в ролике.',
    tasks: ['Разбор и описание коротких видео', 'Проверка роликов и контента', 'Поиск нужного момента в видео', 'Ответы на вопросы по фото'],
    where: ['Медиа и соцсети', 'Маркетинг', 'Контроль контента'],
    versions: [['Keye-VL-8B-Preview', '2025-06'], ['Keye-VL-1.5-8B', '2025-08'], ['Keye-VL-671B-A37B', '2025-11'], ['Keye-VL-2.0-30B-A3B', '2026-05']],
    hf: 'https://huggingface.co/Kwai-Keye/Keye-VL-2.0-30B-A3B',
    github: 'https://github.com/Kwai-Keye/Keye',
    alternatives: ['qwen-vl', 'kimi-vl', 'internvl'],
    source: 'https://huggingface.co/Kwai-Keye/Keye-VL-2.0-30B-A3B',
    verified: true,
  },
  {
    id: 'ovis',
    name: 'Ovis',
    developer: 'Alibaba (AIDC-AI)', country: 'Китай',
    modality: ['vlm', 'ocr'],
    first: '2024-07', latest: '2026-07',
    sizes: '0.9B – 80B-A3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown',
    industries: ['docs', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Модели зрения от международного подразделения Alibaba с сильным чтением текста и таблиц. В линейке есть MoE Ovis2.6 и отдельные компактные OvisOCR для документов.',
    tasks: ['Извлечение данных из счетов, договоров и накладных', 'Распознавание таблиц', 'Ответы на вопросы по фото и графикам', 'Разбор карточек товаров'],
    where: ['Документооборот', 'Электронная коммерция', 'Бухгалтерия'],
    versions: [['Ovis1.5', '2024-07'], ['Ovis1.6', '2024-09'], ['Ovis2 (1B – 34B)', '2025-02'], ['Ovis2.5', '2025-08'], ['Ovis2.6-30B-A3B', '2026-02'], ['Ovis2.6-80B-A3B', '2026-05'], ['OvisOCR2', '2026-07']],
    hf: 'https://huggingface.co/ATH-MaaS/Ovis2.6-80B-A3B',
    github: 'https://github.com/AIDC-AI/Ovis',
    alternatives: ['qwen-vl', 'internvl', 'paddleocr-vl'],
    source: 'https://huggingface.co/ATH-MaaS/OvisOCR2',
    verified: true,
  },
  {
    id: 'granite-vision',
    name: 'Granite Vision',
    developer: 'IBM', country: 'США',
    modality: ['vlm', 'ocr'],
    first: '2025-01', latest: '2026-04',
    sizes: '2B – 4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs', 'finance'],
    ollama: true,
    cpu: true,
    summary: 'Компактные модели IBM для корпоративных документов: таблицы, графики, формы, пары «поле — значение». Карточка честно предупреждает, что лучше всего работает с английским.',
    tasks: ['Извлечение полей из форм и счетов', 'Перевод графиков и таблиц в данные', 'Ответы на вопросы по документам'],
    where: ['Документооборот', 'Бухгалтерия', 'Финансы'],
    versions: [['Granite Vision 3.1 2B Preview', '2025-01'], ['Granite Vision 3.2 2B', '2025-02'], ['Granite Vision 3.3 2B', '2025-06'], ['Granite 4.0 3B Vision', '2026-03'], ['Granite Vision 4.1 4B', '2026-04']],
    hf: 'https://huggingface.co/ibm-granite/granite-vision-4.1-4b',
    github: null,
    alternatives: ['granite', 'docling', 'qwen-vl'],
    source: 'https://huggingface.co/ibm-granite/granite-vision-4.1-4b',
    verified: true,
  },

  // ---------- OCR: распознавание документов ----------
  {
    id: 'nougat',
    name: 'Nougat',
    developer: 'Meta', country: 'США',
    modality: ['ocr'],
    first: '2023-09', latest: '2023-09',
    sizes: '250M – 350M',
    license: 'Большая версия — CC-BY-NC 4.0 (некоммерческая), малая — CC-BY 4.0',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['science', 'education', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Ранняя модель, переводящая научные PDF в текст с формулами. Сегодня устарела, её обходят почти все современные OCR-модели.',
    tasks: ['Перевод научных статей из PDF в текст с формулами', 'Оцифровка технической документации'],
    where: ['Наука и образование', 'Технические архивы'],
    versions: [['Nougat small / base', '2023-09']],
    hf: 'https://huggingface.co/facebook/nougat-base',
    github: 'https://github.com/facebookresearch/nougat',
    alternatives: ['got-ocr', 'olmocr', 'mineru'],
    source: 'https://huggingface.co/facebook/nougat-base',
    verified: true,
  },
  {
    id: 'got-ocr',
    name: 'GOT-OCR 2.0',
    developer: 'StepFun', country: 'Китай',
    modality: ['ocr'],
    first: '2024-09', latest: '2024-11',
    sizes: '580M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['docs'],
    ollama: false,
    cpu: true,
    summary: 'Одна из первых универсальных OCR-моделей нового поколения: текст, формулы, таблицы, ноты и схемы. Маленькая, работает на слабом железе, но уже уступает новинкам.',
    tasks: ['Распознавание сканов счетов и договоров', 'Перевод таблиц в редактируемый вид', 'Распознавание формул и схем'],
    where: ['Бухгалтерия', 'Документооборот', 'Архивы'],
    versions: [['GOT-OCR2.0', '2024-09'], ['GOT-OCR-2.0 для Transformers', '2024-11']],
    hf: 'https://huggingface.co/stepfun-ai/GOT-OCR2_0',
    github: 'https://github.com/Ucas-HaoranWei/GOT-OCR2.0',
    alternatives: ['paddleocr-vl', 'deepseek-ocr', 'step'],
    source: 'https://huggingface.co/stepfun-ai/GOT-OCR-2.0-hf',
    verified: true,
  },
  {
    id: 'olmocr',
    name: 'olmOCR',
    developer: 'Ai2 (Allen Institute for AI)', country: 'США',
    modality: ['ocr'],
    first: '2025-02', latest: '2025-10',
    sizes: '7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['docs', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Модель и набор инструментов для массового перевода PDF в чистый текст с сохранением порядка чтения, таблиц и формул. Рассчитана на обработку миллионов страниц.',
    tasks: ['Массовая оцифровка архива PDF', 'Распознавание договоров и отчётов в текст', 'Подготовка документов для поиска и RAG', 'Распознавание таблиц'],
    where: ['Документооборот', 'Юридические отделы', 'Архивы и библиотеки'],
    versions: [['olmOCR-7B-0225-preview', '2025-02'], ['olmOCR-7B-0725', '2025-07'], ['olmOCR-7B-0825', '2025-08'], ['olmOCR-2-7B-1025', '2025-10']],
    hf: 'https://huggingface.co/allenai/olmOCR-2-7B-1025',
    github: 'https://github.com/allenai/olmocr',
    alternatives: ['mineru', 'chandra-ocr', 'dots-ocr'],
    source: 'https://huggingface.co/allenai/olmOCR-2-7B-1025',
    verified: true,
  },
  {
    id: 'docling',
    name: 'SmolDocling и Granite-Docling',
    developer: 'IBM и Hugging Face', country: 'США',
    modality: ['ocr'],
    first: '2025-03', latest: '2025-09',
    sizes: '256M – 258M',
    license: 'Granite-Docling — Apache 2.0; SmolDocling — CDLA-Permissive 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Крошечные модели для открытого конвертера документов Docling: переводят страницу в разметку с таблицами, формулами и кодом. Работают на обычном ноутбуке.',
    tasks: ['Перевод PDF и сканов в Markdown для поиска и RAG', 'Распознавание таблиц из отчётов', 'Разбор счетов и договоров на обычном ПК'],
    where: ['Документооборот', 'Юридические отделы', 'Внутренние базы знаний'],
    versions: [['SmolDocling-256M-preview', '2025-03'], ['Granite-Docling-258M', '2025-09']],
    hf: 'https://huggingface.co/ibm-granite/granite-docling-258M',
    github: 'https://github.com/docling-project/docling',
    alternatives: ['granite-vision', 'mineru', 'paddleocr-vl'],
    source: 'https://huggingface.co/ibm-granite/granite-docling-258M',
    verified: true,
  },
  {
    id: 'dots-ocr',
    name: 'dots.ocr',
    developer: 'rednote hilab (Xiaohongshu)', country: 'Китай',
    modality: ['ocr'],
    first: '2025-07', latest: '2026-03',
    sizes: 'около 3B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['docs', 'finance'],
    ollama: false,
    cpu: false,
    summary: 'Многоязычная модель для разбора документов: текст, таблицы, формулы и порядок чтения за один проход. dots.mocr ещё переводит графики и схемы в векторный SVG.',
    tasks: ['Распознавание счетов, договоров и накладных', 'Перевод таблиц в редактируемый вид', 'Перевод графиков и схем в векторный формат', 'Подготовка документов для RAG'],
    where: ['Документооборот', 'Бухгалтерия', 'Аналитика'],
    versions: [['dots.ocr', '2025-07'], ['dots.mocr и dots.mocr-svg', '2026-03']],
    hf: 'https://huggingface.co/dots-studio/dots.mocr',
    github: 'https://github.com/rednote-hilab/dots.mocr',
    alternatives: ['paddleocr-vl', 'mineru', 'deepseek-ocr'],
    source: 'https://huggingface.co/dots-studio/dots.mocr',
    verified: true,
  },
  {
    id: 'deepseek-ocr',
    name: 'DeepSeek-OCR',
    developer: 'DeepSeek', country: 'Китай',
    modality: ['ocr'],
    first: '2025-10', latest: '2026-01',
    sizes: 'около 3B',
    license: 'DeepSeek-OCR — MIT; DeepSeek-OCR 2 — Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['docs', 'finance'],
    ollama: true,
    cpu: false,
    summary: 'OCR-модель, которая сильно сжимает страницу в небольшое число визуальных токенов, поэтому быстро обрабатывает большие объёмы. Версия 2 лучше понимает порядок чтения.',
    tasks: ['Массовое распознавание сканов счетов и договоров', 'Распознавание таблиц', 'Перевод PDF в Markdown для поиска и RAG'],
    where: ['Документооборот', 'Бухгалтерия', 'Архивы'],
    versions: [['DeepSeek-OCR', '2025-10'], ['DeepSeek-OCR 2', '2026-01']],
    hf: 'https://huggingface.co/deepseek-ai/DeepSeek-OCR-2',
    github: 'https://github.com/deepseek-ai/DeepSeek-OCR-2',
    alternatives: ['paddleocr-vl', 'dots-ocr', 'glm-ocr'],
    source: 'https://huggingface.co/deepseek-ai/DeepSeek-OCR-2',
    verified: true,
  },
  {
    id: 'paddleocr-vl',
    name: 'PaddleOCR-VL',
    developer: 'Baidu (PaddlePaddle)', country: 'Китай',
    modality: ['ocr'],
    first: '2025-10', latest: '2026-05',
    sizes: '0.9B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'finance', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Компактная модель для разбора документов из популярного набора PaddleOCR. По карточке поддерживает 109 языков, в том числе русский; версия 1.6 лидирует на тесте OmniDocBench.',
    tasks: ['Распознавание счетов, договоров и накладных, в том числе на русском', 'Распознавание таблиц, формул, печатей', 'Перевод сканов в Markdown и JSON', 'Работа на обычном ПК без мощной видеокарты'],
    where: ['Бухгалтерия', 'Документооборот', 'Логистика', 'Архивы'],
    versions: [['PaddleOCR-VL', '2025-10'], ['PaddleOCR-VL-1.5', '2026-01'], ['PaddleOCR-VL-1.6', '2026-05']],
    hf: 'https://huggingface.co/PaddlePaddle/PaddleOCR-VL-1.6',
    github: 'https://github.com/PaddlePaddle/PaddleOCR',
    alternatives: ['glm-ocr', 'mineru', 'qianfan-ocr'],
    source: 'https://huggingface.co/PaddlePaddle/PaddleOCR-VL-1.6',
    verified: true,
  },
  {
    id: 'glm-ocr',
    name: 'GLM-OCR',
    developer: 'Zhipu AI (Z.ai)', country: 'Китай',
    modality: ['ocr'],
    first: '2026-01', latest: '2026-01',
    sizes: '0.9B',
    license: 'MIT (модуль разметки страницы PP-DocLayoutV3 — Apache 2.0)',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'finance'],
    ollama: true,
    cpu: true,
    summary: 'Лёгкая OCR-модель Zhipu для разбора документов. В карточке русский указан среди поддерживаемых языков; рассчитана на высокую нагрузку и слабое железо.',
    tasks: ['Распознавание счетов, договоров и накладных, в том числе на русском', 'Распознавание таблиц и формул', 'Извлечение полей в JSON', 'Поток документов с высокой нагрузкой'],
    where: ['Бухгалтерия', 'Документооборот', 'Логистика'],
    versions: [['GLM-OCR', '2026-01']],
    hf: 'https://huggingface.co/zai-org/GLM-OCR',
    github: 'https://github.com/zai-org/GLM-OCR',
    alternatives: ['paddleocr-vl', 'cogvlm', 'lighton-ocr'],
    source: 'https://huggingface.co/zai-org/GLM-OCR',
    verified: true,
  },
  {
    id: 'mineru',
    name: 'MinerU',
    developer: 'Shanghai AI Laboratory (OpenDataLab)', country: 'Китай',
    modality: ['ocr'],
    first: '2025-06', latest: '2026-05',
    sizes: '0.9B – 1.2B',
    license: 'MinerU2.5-Pro — Apache 2.0; первая MinerU2.5 — AGPL 3.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs', 'science', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Популярный открытый инструмент перевода PDF в Markdown со своей небольшой моделью. MinerU2.5-Pro улучшили только за счёт данных, без роста размера. Языки в карточке — китайский и английский.',
    tasks: ['Перевод PDF-отчётов и договоров в Markdown', 'Распознавание таблиц и формул', 'Подготовка документов для RAG и поиска'],
    where: ['Документооборот', 'Внутренние базы знаний', 'Аналитика'],
    versions: [['MinerU2.0-2505-0.9B', '2025-06'], ['MinerU2.5-2509-1.2B', '2025-09'], ['MinerU2.5-Pro-2604', '2026-04'], ['MinerU2.5-Pro-2605', '2026-05']],
    hf: 'https://huggingface.co/opendatalab/MinerU2.5-Pro-2605-1.2B',
    github: 'https://github.com/opendatalab/MinerU',
    alternatives: ['paddleocr-vl', 'docling', 'olmocr'],
    source: 'https://huggingface.co/opendatalab/MinerU2.5-Pro-2605-1.2B',
    verified: true,
  },
  {
    id: 'chandra-ocr',
    name: 'Chandra OCR',
    developer: 'Datalab', country: 'США',
    modality: ['ocr'],
    first: '2025-10', latest: '2026-03',
    sizes: '5B – 9B',
    license: 'Модифицированная OpenRAIL-M: бесплатно для исследований и компаний с выручкой и инвестициями до 2 млн долларов, нельзя конкурировать с их API; остальным — платная лицензия',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['docs', 'finance', 'legal'],
    ollama: false,
    cpu: false,
    summary: 'Сильная OCR-модель от авторов Marker и Surya: рукописный текст, формы, таблицы. По карточке поддерживает 90+ языков, русский есть среди примеров.',
    tasks: ['Распознавание счетов, договоров и накладных, в том числе на русском', 'Распознавание рукописных форм и анкет', 'Распознавание сложных таблиц'],
    where: ['Документооборот', 'Бухгалтерия', 'Страхование и банки'],
    versions: [['Chandra', '2025-10'], ['Chandra OCR 2', '2026-03']],
    hf: 'https://huggingface.co/datalab-to/chandra-ocr-2',
    github: 'https://github.com/datalab-to/chandra',
    alternatives: ['olmocr', 'dots-ocr', 'paddleocr-vl'],
    source: 'https://huggingface.co/datalab-to/chandra-ocr-2',
    verified: true,
  },
  {
    id: 'hunyuan-ocr',
    name: 'HunyuanOCR',
    developer: 'Tencent', country: 'Китай',
    modality: ['ocr'],
    first: '2025-11', latest: '2026-07',
    sizes: '1B',
    license: 'Tencent Hunyuan Community License (коммерция разрешена, но не действует в ЕС, Великобритании и Южной Корее)',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'finance'],
    ollama: false,
    cpu: false,
    summary: 'Лёгкая OCR-модель Tencent: разбор документов, поиск текста на фото, извлечение полей и перевод текста с картинок. Версия 1.5 быстрее и запускается на обычном ПК.',
    tasks: ['Извлечение полей из счетов и накладных', 'Распознавание таблиц и формул', 'Перевод текста на фотографиях и сканах', 'Чтение текста на фото и в видео'],
    where: ['Документооборот', 'Логистика', 'Бухгалтерия'],
    versions: [['HunyuanOCR 1.0', '2025-11'], ['HunyuanOCR-1.5', '2026-07']],
    hf: 'https://huggingface.co/tencent/HunyuanOCR',
    github: 'https://github.com/Tencent-Hunyuan/HunyuanOCR',
    alternatives: ['paddleocr-vl', 'glm-ocr', 'hunyuan'],
    source: 'https://github.com/Tencent-Hunyuan/HunyuanOCR',
    verified: true,
  },
  {
    id: 'lighton-ocr',
    name: 'LightOnOCR',
    developer: 'LightOn', country: 'Франция',
    modality: ['ocr'],
    first: '2025-10', latest: '2026-01',
    sizes: '0.9B – 1B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs'],
    ollama: false,
    cpu: true,
    summary: 'Французская OCR-модель на 1B, которая переводит страницу в текст за один проход и быстро работает на потоке. Языки в карточке — европейские, китайский и японский, русского нет.',
    tasks: ['Распознавание счетов и договоров на европейских языках', 'Распознавание таблиц', 'Перевод PDF в текст для поиска и RAG', 'Поиск координат элементов на странице (версии bbox)'],
    where: ['Документооборот', 'Юридические отделы', 'Архивы'],
    versions: [['LightOnOCR-1B-1025', '2025-10'], ['LightOnOCR-2-1B и bbox-версии', '2026-01']],
    hf: 'https://huggingface.co/lightonai/LightOnOCR-2-1B',
    github: null,
    alternatives: ['glm-ocr', 'paddleocr-vl', 'docling'],
    source: 'https://huggingface.co/lightonai/LightOnOCR-2-1B',
    verified: true,
  },
  {
    id: 'nanonets-ocr',
    name: 'Nanonets-OCR',
    developer: 'Nanonets', country: 'США / Индия',
    modality: ['ocr'],
    first: '2025-06', latest: '2025-10',
    sizes: '1.5B – 3B',
    license: 'Nanonets-OCR2-1.5B-exp — Apache 2.0; у 3B-версий лицензия на карточке не указана, основа — Qwen2.5-VL-3B со своей лицензией',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'finance', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Модель для перевода документов в Markdown с таблицами, печатями, подписями, галочками и водяными знаками. В карточке OCR2 русский указан среди языков.',
    tasks: ['Распознавание счетов, договоров и накладных, в том числе на русском', 'Распознавание печатей, подписей и отметок', 'Распознавание рукописного текста', 'Распознавание таблиц'],
    where: ['Документооборот', 'Бухгалтерия', 'Юридические отделы'],
    versions: [['Nanonets-OCR-s', '2025-06'], ['Nanonets-OCR2 1.5B и 3B', '2025-10']],
    hf: 'https://huggingface.co/nanonets/Nanonets-OCR2-3B',
    github: null,
    alternatives: ['qwen-vl', 'olmocr', 'chandra-ocr'],
    source: 'https://huggingface.co/nanonets/Nanonets-OCR2-3B',
    verified: true,
  },
  {
    id: 'teleocr',
    name: 'TeleOCR',
    developer: 'TeleAI (China Telecom)', country: 'Китай',
    modality: ['ocr'],
    first: '2026-08', latest: '2026-08',
    sizes: 'около 1.2B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs'],
    ollama: false,
    cpu: true,
    summary: 'Новая лёгкая модель для разбора документов, на момент выхода лидер теста OmniDocBench v1.6. Хорошо справляется со снятыми на телефон и помятыми страницами. Языки в карточке — китайский, английский, японский.',
    tasks: ['Распознавание счетов и накладных, снятых на телефон', 'Распознавание таблиц и формул', 'Перевод документов в Markdown для RAG'],
    where: ['Документооборот', 'Логистика', 'Бухгалтерия'],
    versions: [['TeleOCR', '2026-08']],
    hf: 'https://huggingface.co/StarDoc-AI/TeleOCR',
    github: 'https://github.com/caipeng328/TeleOCR',
    alternatives: ['paddleocr-vl', 'qianfan-ocr', 'mineru'],
    source: 'https://huggingface.co/StarDoc-AI/TeleOCR',
    verified: true,
  },
  {
    id: 'qianfan-ocr',
    name: 'Qianfan-OCR',
    developer: 'Baidu (Qianfan)', country: 'Китай',
    modality: ['ocr'],
    first: '2026-03', latest: '2026-03',
    sizes: '4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['docs', 'finance'],
    ollama: false,
    cpu: false,
    summary: 'Модель Baidu, которая не только распознаёт документ, но и отвечает на вопросы по нему. По карточке поддерживает 192 языка, включая кириллицу.',
    tasks: ['Распознавание счетов, договоров и накладных, в том числе на русском', 'Разметка страницы и распознавание таблиц', 'Ответы на вопросы по документу', 'Извлечение ключевых полей'],
    where: ['Бухгалтерия', 'Документооборот', 'Банки и страхование'],
    versions: [['Qianfan-OCR', '2026-03']],
    hf: 'https://huggingface.co/baidu/Qianfan-OCR',
    github: null,
    alternatives: ['paddleocr-vl', 'ernie', 'glm-ocr'],
    source: 'https://huggingface.co/baidu/Qianfan-OCR',
    verified: true,
  },
];
