// Волна 4: эмбеддинги, реранкеры, поиск по документам-картинкам и CLIP-подобные модели для RAG.
// Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'sentence-transformers',
    name: 'Sentence Transformers (all-MiniLM, paraphrase-multilingual)',
    developer: 'UKP Lab (ТУ Дармштадт), затем Hugging Face', country: 'Германия',
    modality: ['embed'],
    first: '2019-08', latest: '2025-01',
    sizes: 'около 20M – 470M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['dev', 'support', 'docs', 'retail'],
    ollama: true,
    cpu: true,
    summary: 'Классика смыслового поиска: маленькие быстрые модели, которые работают даже на слабом сервере без видеокарты. Многоязычные версии понимают русский.',
    tasks: ['Поиск по базе знаний и FAQ', 'Поиск похожих обращений и дублей', 'Группировка отзывов и заявок по темам'],
    where: ['Поддержка клиентов', 'Внутренние базы знаний', 'Онлайн-торговля'],
    versions: [
      ['SBERT (первые NLI-модели)', '2019-08'],
      ['Многоязычные paraphrase и distiluse', '2020-04'],
      ['paraphrase-multilingual-MiniLM-L12-v2', '2021-06'],
      ['all-MiniLM-L6-v2 и all-mpnet-base-v2', '2021-08'],
      ['Static Embeddings (en и многоязычная)', '2025-01'],
    ],
    hf: 'https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    github: 'https://github.com/huggingface/sentence-transformers',
    alternatives: ['e5', 'bge-m3', 'rubert-tiny'],
    source: 'https://huggingface.co/sentence-transformers/static-similarity-mrl-multilingual-v1',
    verified: true,
    en: {
      summary: 'The classic for meaning-based search: small, fast models that run even on a modest server without a GPU. The multilingual versions understand Russian.',
      tasks: ['Search across a knowledge base and FAQ', 'Finding similar tickets and duplicates', 'Grouping reviews and requests by topic'],
      where: ['Customer support', 'Internal knowledge bases', 'E-commerce'],
      license: 'Apache 2.0',
      developer: 'UKP Lab (TU Darmstadt), later Hugging Face',
      country: 'Germany',
      sizes: 'about 20M – 470M',
    },
  },
  {
    id: 'bge',
    name: 'BGE (BAAI General Embedding)',
    developer: 'BAAI (Пекинская академия ИИ)', country: 'Китай',
    modality: ['embed'],
    first: '2023-08', latest: '2025-09',
    sizes: '24M – 9B',
    license: 'MIT (v1, v1.5); Apache 2.0 (bge-en-icl, bge-code, bge-reasoner); bge-multilingual-gemma2 — по лицензии Gemma',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['dev', 'support', 'docs'],
    ollama: true,
    cpu: true,
    summary: 'Одни из самых популярных эмбеддингов для поиска и RAG. Основные версии v1.5 рассчитаны на английский и китайский; для русского у BAAI есть отдельная bge-m3.',
    tasks: ['Поиск по документам на английском', 'Подбор фрагментов для ответа чат-бота (RAG)', 'Поиск по коду (bge-code)'],
    where: ['IT и разработка', 'Внутренние базы знаний', 'Поддержка клиентов'],
    versions: [
      ['BGE v1 (en, zh)', '2023-08'],
      ['BGE v1.5 small, base, large', '2023-09'],
      ['bge-en-icl и bge-multilingual-gemma2', '2024-07'],
      ['bge-code-v1', '2025-05'],
      ['bge-reasoner-embed', '2025-09'],
    ],
    hf: 'https://huggingface.co/BAAI/bge-large-en-v1.5',
    github: 'https://github.com/FlagOpen/FlagEmbedding',
    alternatives: ['bge-m3', 'e5', 'gte'],
    source: 'https://huggingface.co/BAAI/bge-reasoner-embed-qwen3-8b-0923',
    verified: true,
    en: {
      summary: 'Some of the most popular embeddings for search and RAG. The main v1.5 versions target English and Chinese; for Russian, BAAI has a separate model, bge-m3.',
      tasks: ['Search across English-language documents', 'Picking passages for chatbot answers (RAG)', 'Code search (bge-code)'],
      where: ['IT and software development', 'Internal knowledge bases', 'Customer support'],
      license: 'MIT (v1, v1.5); Apache 2.0 (bge-en-icl, bge-code, bge-reasoner); bge-multilingual-gemma2 — under the Gemma license',
      developer: 'BAAI (Beijing Academy of Artificial Intelligence)',
      country: 'China',
    },
  },
  {
    id: 'bge-reranker',
    name: 'BGE Reranker',
    developer: 'BAAI (Пекинская академия ИИ)', country: 'Китай',
    modality: ['rerank'],
    first: '2023-09', latest: '2024-07',
    sizes: '278M – 9B',
    license: 'MIT (base, large); Apache 2.0 (v2-m3, v2-gemma, v2-minicpm); v2.5-gemma2 — по лицензии Gemma',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['dev', 'support', 'docs', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Реранкеры: берут найденные поиском фрагменты и переставляют их по реальной близости к вопросу. Версия v2-m3 многоязычная и лёгкая, её часто ставят в пару к bge-m3.',
    tasks: ['Уточнение выдачи перед ответом чат-бота', 'Сортировка результатов поиска по базе знаний', 'Отбор самых подходящих пунктов договоров и регламентов'],
    where: ['Поддержка клиентов', 'Юристы и документооборот', 'Внутренние базы знаний'],
    versions: [
      ['bge-reranker-base и large', '2023-09'],
      ['bge-reranker-v2-m3, v2-gemma, v2-minicpm-layerwise', '2024-03'],
      ['bge-reranker-v2.5-gemma2-lightweight', '2024-07'],
    ],
    hf: 'https://huggingface.co/BAAI/bge-reranker-v2-m3',
    github: 'https://github.com/FlagOpen/FlagEmbedding',
    alternatives: ['bge-m3', 'qwen-embedding', 'jina-reranker'],
    source: 'https://huggingface.co/BAAI/bge-reranker-v2.5-gemma2-lightweight',
    verified: true,
    en: {
      summary: 'Rerankers: they take passages found by search and reorder them by how well they actually match the question. v2-m3 is multilingual and lightweight, often paired with bge-m3.',
      tasks: ['Refining search results before a chatbot answers', 'Sorting knowledge base search results', 'Selecting the most relevant clauses of contracts and policies'],
      where: ['Customer support', 'Legal and document management', 'Internal knowledge bases'],
      license: 'MIT (base, large); Apache 2.0 (v2-m3, v2-gemma, v2-minicpm); v2.5-gemma2 — under the Gemma license',
      developer: 'BAAI (Beijing Academy of Artificial Intelligence)',
      country: 'China',
    },
  },
  {
    id: 'mxbai',
    name: 'mxbai (Mixedbread Embed и Rerank)',
    developer: 'Mixedbread', country: 'Германия',
    modality: ['embed', 'rerank'],
    first: '2024-02', latest: '2025-10',
    sizes: '17M – 1.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['dev', 'support', 'retail', 'docs'],
    ollama: true,
    cpu: true,
    summary: 'Эмбеддинги и реранкеры немецкой Mixedbread. mxbai-embed-large — одна из самых скачиваемых английских моделей для поиска, реранкеры v2 работают на 100+ языках, включая русский.',
    tasks: ['Поиск по базе знаний', 'Переранжирование результатов перед ответом бота', 'Поиск по каталогу товаров'],
    where: ['Поддержка клиентов', 'Онлайн-торговля', 'IT и разработка'],
    versions: [
      ['mxbai-rerank v1 (xsmall, base, large)', '2024-02'],
      ['mxbai-embed-large-v1', '2024-03'],
      ['mxbai-embed-xsmall-v1', '2024-09'],
      ['mxbai-rerank v2 (base, large)', '2025-03'],
      ['mxbai-edge-colbert v0 (17M, 32M)', '2025-10'],
    ],
    hf: 'https://huggingface.co/mixedbread-ai/mxbai-rerank-large-v2',
    github: 'https://github.com/mixedbread-ai/mxbai-rerank',
    alternatives: ['bge-reranker', 'nomic-embed', 'bge-m3'],
    source: 'https://huggingface.co/mixedbread-ai/mxbai-edge-colbert-v0-32m',
    verified: true,
    en: {
      summary: 'Embeddings and rerankers from Germany\'s Mixedbread. mxbai-embed-large is one of the most downloaded English search models; the v2 rerankers cover 100+ languages, including Russian.',
      tasks: ['Search across a knowledge base', 'Reranking results before a bot answers', 'Product catalog search'],
      where: ['Customer support', 'E-commerce', 'IT and software development'],
      license: 'Apache 2.0',
      country: 'Germany',
    },
  },
  {
    id: 'arctic-embed',
    name: 'Snowflake Arctic Embed',
    developer: 'Snowflake', country: 'США',
    modality: ['embed'],
    first: '2024-04', latest: '2024-12',
    sizes: '22M – 568M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['dev', 'docs', 'support', 'finance'],
    ollama: true,
    cpu: true,
    summary: 'Эмбеддинги от Snowflake, заточенные именно под поиск. Версия 2.0 многоязычная (русский в списке языков), держит длинные тексты до 8 тыс. токенов и умеет сжимать векторы.',
    tasks: ['Поиск по документам и базе знаний', 'Подбор фрагментов для RAG', 'Поиск по отчётам и внутренним данным'],
    where: ['Внутренние базы знаний', 'Финансы и аналитика', 'Поддержка клиентов'],
    versions: [
      ['Arctic Embed xs, s, m, l', '2024-04'],
      ['Arctic Embed m v1.5', '2024-07'],
      ['Arctic Embed 2.0 m и l (многоязычные)', '2024-12'],
    ],
    hf: 'https://huggingface.co/Snowflake/snowflake-arctic-embed-l-v2.0',
    github: 'https://github.com/Snowflake-Labs/arctic-embed',
    alternatives: ['bge-m3', 'e5', 'gte'],
    source: 'https://www.snowflake.com/en/blog/engineering/snowflake-arctic-embed-2-multilingual/',
    verified: true,
    en: {
      summary: 'Snowflake embeddings built specifically for search. Version 2.0 is multilingual (Russian is on the language list), handles long texts up to 8K tokens and can compress vectors.',
      tasks: ['Search across documents and knowledge bases', 'Picking passages for RAG', 'Search across reports and internal data'],
      where: ['Internal knowledge bases', 'Finance and analytics', 'Customer support'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'harrier',
    name: 'Harrier (harrier-oss)',
    developer: 'Microsoft', country: 'США',
    modality: ['embed'],
    first: '2026-03', latest: '2026-03',
    sizes: '270M – 27B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['dev', 'support', 'docs', 'legal'],
    ollama: false,
    cpu: true,
    summary: 'Многоязычные эмбеддинги Microsoft 2026 года с контекстом до 32 тыс. токенов, русский в списке языков. Версии 270M и 0.6B идут на обычном сервере, 27B — самая точная.',
    tasks: ['Поиск по базе знаний на разных языках', 'Подбор фрагментов для RAG', 'Поиск по длинным документам'],
    where: ['Поддержка клиентов', 'Юристы и документооборот', 'Внутренние базы знаний'],
    versions: [
      ['harrier-oss-v1 (270M, 0.6B, 27B)', '2026-03'],
    ],
    hf: 'https://huggingface.co/microsoft/harrier-oss-v1-0.6b',
    github: null,
    alternatives: ['qwen-embedding', 'e5', 'embeddinggemma'],
    source: 'https://huggingface.co/microsoft/harrier-oss-v1-27b',
    verified: true,
    en: {
      summary: 'Microsoft\'s 2026 multilingual embeddings with context up to 32K tokens; Russian is on the language list. The 270M and 0.6B versions run on a regular server, 27B is the most accurate.',
      tasks: ['Multilingual knowledge base search', 'Picking passages for RAG', 'Search across long documents'],
      where: ['Customer support', 'Legal and document management', 'Internal knowledge bases'],
      license: 'MIT',
      country: 'USA',
    },
  },
  {
    id: 'octen-embedding',
    name: 'Octen Embedding',
    developer: 'Octen', country: 'США / Сингапур',
    modality: ['embed'],
    first: '2025-12', latest: '2026-04',
    sizes: '0.6B – 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['legal', 'finance', 'medical', 'dev'],
    ollama: false,
    cpu: true,
    summary: 'Дообученные Qwen3-Embedding от стартапа Octen под поиск в юридических, финансовых и медицинских текстах. Версия 8B на январь 2026 возглавляла рейтинг RTEB.',
    tasks: ['Поиск по договорам и судебной практике', 'Поиск по финансовым отчётам', 'Поиск по длинным документам до 32 тыс. токенов'],
    where: ['Юристы', 'Банки и финансы', 'Клиники (справочные базы)'],
    versions: [
      ['Octen-Embedding-8B', '2025-12'],
      ['Octen-Embedding-4B', '2025-12'],
      ['Octen-Embedding-0.6B и 8B-INT8', '2026-01'],
      ['Octen-Embedding-4B-INT8', '2026-04'],
    ],
    hf: 'https://huggingface.co/Octen/Octen-Embedding-8B',
    github: null,
    alternatives: ['qwen-embedding', 'bge-m3', 'harrier'],
    source: 'https://huggingface.co/Octen/Octen-Embedding-4B-INT8',
    verified: true,
    en: {
      summary: 'Qwen3-Embedding models fine-tuned by the startup Octen for search in legal, financial and medical texts. As of January 2026 the 8B version topped the RTEB leaderboard.',
      tasks: ['Search across contracts and case law', 'Search across financial reports', 'Search across long documents up to 32K tokens'],
      where: ['Law firms', 'Banking and finance', 'Clinics (reference databases)'],
      license: 'Apache 2.0',
      country: 'USA / Singapore',
    },
  },
  {
    id: 'jina-reranker',
    name: 'Jina Reranker',
    developer: 'Jina AI', country: 'Германия',
    modality: ['rerank', 'docsearch'],
    first: '2024-04', latest: '2026-07',
    sizes: '33M – 2.4B',
    license: 'v1 — Apache 2.0; v2, v3, v3.5 и m0 — CC-BY-NC 4.0 (для бизнеса — через API или договор с Jina)',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['dev', 'support', 'docs', 'retail'],
    ollama: false,
    cpu: true,
    summary: 'Сильные многоязычные реранкеры; m0 сортирует и страницы-картинки (сканы, слайды). Свежие версии открыты только для некоммерческого использования.',
    tasks: ['Уточнение выдачи перед ответом чат-бота', 'Сортировка найденных страниц PDF и слайдов', 'Поиск по каталогу и базе знаний'],
    where: ['Поддержка клиентов', 'Документооборот', 'Онлайн-торговля'],
    versions: [
      ['v1 turbo и tiny (англ.)', '2024-04'],
      ['v2-base-multilingual', '2024-06'],
      ['m0 (текст и картинки)', '2025-03'],
      ['v3 (0.6B)', '2025-09'],
      ['v3.5', '2026-07'],
    ],
    hf: 'https://huggingface.co/jinaai/jina-reranker-v3.5',
    github: null,
    alternatives: ['bge-reranker', 'qwen-embedding', 'jina-embeddings'],
    source: 'https://huggingface.co/jinaai/jina-reranker-v3.5',
    verified: true,
    en: {
      summary: 'Strong multilingual rerankers; m0 also ranks pages as images (scans, slides). The latest versions are open for non-commercial use only.',
      tasks: ['Refining search results before a chatbot answers', 'Sorting retrieved PDF pages and slides', 'Catalog and knowledge base search'],
      where: ['Customer support', 'Document management', 'E-commerce'],
      license: 'v1 — Apache 2.0; v2, v3, v3.5 and m0 — CC-BY-NC 4.0 (for business use — via the API or an agreement with Jina)',
      country: 'Germany',
    },
  },
  {
    id: 'reader-lm',
    name: 'ReaderLM (Jina)',
    developer: 'Jina AI', country: 'Германия',
    modality: ['nlp'],
    first: '2024-09', latest: '2025-01',
    sizes: '0.5B – 1.5B',
    license: 'CC-BY-NC 4.0',
    commercial: 'no',
    hardware: ['min'],
    ru: 'yes',
    industries: ['dev', 'docs', 'marketing'],
    ollama: true,
    cpu: true,
    summary: 'Маленькие модели, которые превращают сырой HTML веб-страниц в чистый Markdown или JSON. Удобно готовить сайты для базы знаний. Лицензия только некоммерческая.',
    tasks: ['Очистка страниц сайтов для базы знаний', 'Извлечение данных со страниц в JSON', 'Подготовка текстов для RAG'],
    where: ['IT и разработка', 'Маркетинг и аналитика конкурентов', 'Внутренние базы знаний'],
    versions: [
      ['reader-lm 0.5b и 1.5b', '2024-09'],
      ['ReaderLM-v2 (1.5B, 29 языков)', '2025-01'],
    ],
    hf: 'https://huggingface.co/jinaai/ReaderLM-v2',
    github: null,
    alternatives: ['docling', 'jina-embeddings', 'gliner'],
    source: 'https://huggingface.co/jinaai/ReaderLM-v2',
    verified: true,
    en: {
      summary: 'Small models that turn raw web page HTML into clean Markdown or JSON. Handy for preparing websites for a knowledge base. Non-commercial license only.',
      tasks: ['Cleaning website pages for a knowledge base', 'Extracting data from pages into JSON', 'Preparing texts for RAG'],
      where: ['IT and software development', 'Marketing and competitor analysis', 'Internal knowledge bases'],
      license: 'CC-BY-NC 4.0',
      country: 'Germany',
    },
  },
  {
    id: 'r3-rerank',
    name: 'R3 (R3-Embedding и R3-Rerank)',
    developer: 'Tencent', country: 'Китай',
    modality: ['rerank', 'agent'],
    first: '2026-07', latest: '2026-07',
    sizes: '0.6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['dev'],
    ollama: false,
    cpu: true,
    summary: 'Пара небольших моделей Tencent на базе Qwen3 для подбора ИИ-агенту нужного навыка (skill) под запрос: эмбеддинг находит кандидатов, реранкер выбирает лучший.',
    tasks: ['Выбор инструмента или навыка для ИИ-агента', 'Маршрутизация запросов между сценариями бота', 'Поиск по каталогу внутренних инструментов'],
    where: ['IT и разработка', 'Команды, строящие ИИ-агентов'],
    versions: [
      ['R3-Embedding-0.6B и R3-Rerank-0.6B', '2026-07'],
    ],
    hf: 'https://huggingface.co/tencent/R3-rerank-0.6b',
    github: null,
    alternatives: ['qwen-embedding', 'bge-reranker'],
    source: 'https://huggingface.co/tencent/R3-embedding-0.6b',
    verified: true,
    en: {
      summary: 'A pair of small Tencent models based on Qwen3 that pick the right skill for an AI agent for a given request: the embedding model finds candidates, the reranker chooses the best one.',
      tasks: ['Choosing a tool or skill for an AI agent', 'Routing requests between bot scenarios', 'Search across a catalog of internal tools'],
      where: ['IT and software development', 'Teams building AI agents'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'colpali',
    name: 'ColPali / ColQwen',
    developer: 'Illuin Technology (команда ViDoRe)', country: 'Франция',
    modality: ['docsearch', 'embed'],
    first: '2024-06', latest: '2025-07',
    sizes: '256M – 3B',
    license: 'Адаптеры MIT или Apache 2.0, но у базовых моделей свои лицензии: PaliGemma — Gemma, Qwen2.5-VL-3B — исследовательская лицензия Qwen (ColQwen2 на Qwen2-VL — Apache 2.0)',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['docs', 'legal', 'finance', 'dev'],
    ollama: false,
    cpu: true,
    summary: 'Поиск по PDF и сканам как по картинкам: страницу не нужно распознавать, модель сразу находит нужную по вопросу, включая таблицы и схемы. Обучены на английском.',
    tasks: ['Поиск по сканам, презентациям и PDF', 'RAG по документам с таблицами и графиками', 'Поиск по технической документации'],
    where: ['Документооборот', 'Юристы', 'Банки и страхование'],
    versions: [
      ['ColPali', '2024-06'],
      ['ColPali v1.2', '2024-08'],
      ['ColQwen2', '2024-09'],
      ['ColPali v1.3 и ColQwen2 v1.0', '2024-11'],
      ['ColSmol 256M и 500M, ColQwen2.5', '2025-01'],
      ['ColQwen-Omni', '2025-07'],
    ],
    hf: 'https://huggingface.co/vidore/colqwen2-v1.0',
    github: 'https://github.com/illuin-tech/colpali',
    alternatives: ['qwen-embedding', 'jina-embeddings', 'nomic-embed'],
    source: 'https://huggingface.co/vidore/colqwen-omni-v0.1',
    verified: true,
    en: {
      summary: 'Searches PDFs and scans as images: pages do not need to be OCR\'d first, the model finds the right one for a question directly, including tables and charts. Trained on English.',
      tasks: ['Search across scans, presentations and PDFs', 'RAG over documents with tables and charts', 'Search across technical documentation'],
      where: ['Document management', 'Law firms', 'Banking and insurance'],
      license: 'Adapters are MIT or Apache 2.0, but the base models have their own licenses: PaliGemma — Gemma, Qwen2.5-VL-3B — Qwen research license (ColQwen2 on Qwen2-VL — Apache 2.0)',
      developer: 'Illuin Technology (ViDoRe team)',
      country: 'France',
    },
  },
  {
    id: 'evie',
    name: 'EVIE',
    developer: 'Tencent', country: 'Китай',
    modality: ['docsearch', 'embed'],
    first: '2026-08', latest: '2026-09',
    sizes: '4.5B – 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['docs', 'legal', 'finance'],
    ollama: false,
    cpu: false,
    summary: 'Модели Tencent на базе Qwen3.5 для поиска по сканам и PDF как по картинкам. По данным карточки, на момент выхода — среди лучших в рейтинге ViDoRe.',
    tasks: ['Поиск по сканам и PDF без распознавания', 'RAG по отчётам с таблицами и графиками', 'Поиск по архивам документов'],
    where: ['Документооборот', 'Банки и финансы', 'Юристы'],
    versions: [
      ['EVIE-Preview-4.5B', '2026-08'],
      ['EVIE-4.5B и EVIE-8B', '2026-09'],
    ],
    hf: 'https://huggingface.co/tencent/EVIE-8B',
    github: 'https://github.com/Tencent/EVIE',
    alternatives: ['colpali', 'qwen-embedding', 'jina-embeddings'],
    source: 'https://huggingface.co/tencent/EVIE-4.5B',
    verified: true,
    en: {
      summary: 'Tencent models based on Qwen3.5 for searching scans and PDFs as images. According to the model card, among the top of the ViDoRe leaderboard at release.',
      tasks: ['Search across scans and PDFs without OCR', 'RAG over reports with tables and charts', 'Search across document archives'],
      where: ['Document management', 'Banking and finance', 'Law firms'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'modernvbert',
    name: 'ModernVBERT / ColModernVBERT',
    developer: 'Illuin Technology, EPFL, CentraleSupélec', country: 'Франция',
    modality: ['docsearch', 'embed'],
    first: '2025-10', latest: '2025-10',
    sizes: '250M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['docs', 'dev'],
    ollama: false,
    cpu: true,
    summary: 'Компактная (250M) модель для поиска по страницам документов как по картинкам. По данным авторов, не уступает моделям в 10 раз крупнее и работает без видеокарты.',
    tasks: ['Поиск по сканам и PDF на слабом сервере', 'Индексация архивов документов', 'Поиск по слайдам и инструкциям'],
    where: ['Документооборот', 'Внутренние базы знаний'],
    versions: [
      ['ModernVBERT, ColModernVBERT, BiModernVBERT', '2025-10'],
    ],
    hf: 'https://huggingface.co/ModernVBERT/colmodernvbert',
    github: null,
    alternatives: ['colpali', 'evie'],
    source: 'https://arxiv.org/abs/2510.01149',
    verified: true,
    en: {
      summary: 'A compact (250M) model for searching document pages as images. According to the authors, it matches models 10 times larger and runs without a GPU.',
      tasks: ['Search across scans and PDFs on a modest server', 'Indexing document archives', 'Search across slides and manuals'],
      where: ['Document management', 'Internal knowledge bases'],
      license: 'MIT',
      country: 'France',
    },
  },
  {
    id: 'clip',
    name: 'CLIP (OpenAI)',
    developer: 'OpenAI', country: 'США',
    modality: ['vision', 'embed'],
    first: '2021-01', latest: '2022-04',
    sizes: 'около 0.15B – 0.6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'media', 'security'],
    ollama: false,
    cpu: true,
    summary: 'Модель 2021 года, которая первой связала картинки и текст: поиск фото по словам и классификация без обучения. Понимает только английский, сейчас чаще берут SigLIP 2 или PE.',
    tasks: ['Поиск картинок по текстовому запросу', 'Автоматические теги для каталога', 'Поиск похожих изображений'],
    where: ['Онлайн-торговля', 'Фотобанки и медиа', 'Модерация контента'],
    versions: [
      ['CLIP ResNet-50 и ViT-B/32', '2021-01'],
      ['RN101 и RN50x4', '2021-03'],
      ['ViT-B/16 и RN50x16', '2021-07'],
      ['ViT-L/14 и RN50x64', '2022-01'],
      ['ViT-L/14@336px', '2022-04'],
    ],
    hf: 'https://huggingface.co/openai/clip-vit-large-patch14',
    github: 'https://github.com/openai/CLIP',
    alternatives: ['clip-siglip', 'perception-encoder', 'ruclip'],
    source: 'https://github.com/openai/CLIP',
    verified: true,
    en: {
      summary: 'The 2021 model that first linked images and text: search photos by words and classify them without training. English only; SigLIP 2 or PE are usually chosen today.',
      tasks: ['Image search by text query', 'Automatic tags for a catalog', 'Finding similar images'],
      where: ['E-commerce', 'Stock photo libraries and media', 'Content moderation'],
      license: 'MIT',
      country: 'USA',
      sizes: 'about 0.15B – 0.6B',
    },
  },
  {
    id: 'perception-encoder',
    name: 'Perception Encoder (PE)',
    developer: 'Meta', country: 'США',
    modality: ['vision', 'embed', 'audio'],
    first: '2025-04', latest: '2025-12',
    sizes: 'размер на карточке не указан',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['retail', 'media', 'security', 'manufacturing'],
    ollama: false,
    cpu: true,
    summary: 'Семейство энкодеров Meta для картинок и видео, а с версией PE-AV — и для звука. PE-Core ищет по тексту точнее SigLIP 2 (по данным Meta), есть малые версии.',
    tasks: ['Поиск фото и видео по описанию', 'Разметка и теги каталога', 'Поиск по звуку и видео (PE-AV)'],
    where: ['Онлайн-торговля', 'Медиа и видеоархивы', 'Видеонаблюдение и безопасность'],
    versions: [
      ['PE-Core, PE-Lang, PE-Spatial (B, L, G)', '2025-04'],
      ['Малые PE-Core T и S, PE-Spatial', '2025-07'],
      ['PE-AV и PE-A-Frame (звук и видео)', '2025-12'],
    ],
    hf: 'https://huggingface.co/facebook/PE-Core-L14-336',
    github: 'https://github.com/facebookresearch/perception_models',
    alternatives: ['clip-siglip', 'dino', 'metaclip'],
    source: 'https://github.com/facebookresearch/perception_models',
    verified: true,
    en: {
      summary: 'Meta\'s family of encoders for images and video, and with PE-AV also for audio. PE-Core searches by text more accurately than SigLIP 2 (per Meta); small versions are available.',
      tasks: ['Search photos and videos by description', 'Catalog labeling and tagging', 'Search across audio and video (PE-AV)'],
      where: ['E-commerce', 'Media and video archives', 'Video surveillance and security'],
      license: 'Apache 2.0',
      country: 'USA',
      sizes: 'size not stated on the model card',
    },
  },
  {
    id: 'metaclip',
    name: 'MetaCLIP / MetaCLIP 2',
    developer: 'Meta', country: 'США',
    modality: ['vision', 'embed'],
    first: '2023-10', latest: '2025-11',
    sizes: '0.15B – 3.6B',
    license: 'CC-BY-NC 4.0',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['retail', 'media', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Открытый повтор CLIP от Meta с прозрачным рецептом сбора данных. MetaCLIP 2 обучен на многоязычных данных со всего мира. Только некоммерческая лицензия.',
    tasks: ['Поиск картинок по тексту', 'Классификация изображений без обучения', 'Исследования и прототипы поиска'],
    where: ['Медиа и фотобанки', 'Онлайн-торговля (прототипы)', 'Наука'],
    versions: [
      ['MetaCLIP (B/32 – H/14)', '2023-10'],
      ['MetaCLIP 2 worldwide (H/14)', '2025-07'],
      ['MetaCLIP 2 giant', '2025-08'],
      ['MetaCLIP 2 B/16 и L/14', '2025-11'],
    ],
    hf: 'https://huggingface.co/facebook/metaclip-2-worldwide-huge-quickgelu',
    github: 'https://github.com/facebookresearch/MetaCLIP',
    alternatives: ['clip-siglip', 'perception-encoder', 'clip'],
    source: 'https://huggingface.co/facebook/metaclip-2-worldwide-b16',
    verified: true,
    en: {
      summary: 'Meta\'s open reproduction of CLIP with a transparent data collection recipe. MetaCLIP 2 is trained on multilingual data from around the world. Non-commercial license only.',
      tasks: ['Image search by text', 'Image classification without training', 'Search research and prototypes'],
      where: ['Media and stock photo libraries', 'E-commerce (prototypes)', 'Science'],
      license: 'CC-BY-NC 4.0',
      country: 'USA',
    },
  },
  {
    id: 'clap',
    name: 'CLAP (LAION)',
    developer: 'LAION', country: 'Германия',
    modality: ['audio', 'embed'],
    first: '2023-02', latest: '2023-10',
    sizes: 'размер на карточке не указан',
    license: 'Apache 2.0 (веса на HF); код и исходные чекпойнты — CC0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['media', 'marketing', 'security'],
    ollama: false,
    cpu: true,
    summary: 'Аналог CLIP для звука: переводит аудио и текст в общее пространство. Можно искать звуки и музыку по описанию и классифицировать их без обучения. Текст — английский.',
    tasks: ['Поиск звуков и музыки по описанию', 'Автоматические теги для аудиотеки', 'Распознавание типа звука (сирена, стекло, голос)'],
    where: ['Медиа и аудиопродакшн', 'Маркетинг и реклама', 'Системы безопасности'],
    versions: [
      ['LAION-CLAP (HTSAT, LAION-Audio-630K)', '2023-02'],
      ['Larger CLAP: музыка и речь', '2023-04'],
      ['larger_clap в Transformers', '2023-10'],
    ],
    hf: 'https://huggingface.co/laion/larger_clap_general',
    github: 'https://github.com/LAION-AI/CLAP',
    alternatives: ['perception-encoder', 'clip'],
    source: 'https://huggingface.co/laion/larger_clap_music_and_speech',
    verified: true,
    en: {
      summary: 'CLIP for audio: maps audio and text into a shared space. Lets you search sounds and music by description and classify them without training. Text must be in English.',
      tasks: ['Search sounds and music by description', 'Automatic tags for an audio library', 'Recognizing sound types (siren, breaking glass, voice)'],
      where: ['Media and audio production', 'Marketing and advertising', 'Security systems'],
      license: 'Apache 2.0 (weights on HF); code and original checkpoints — CC0',
      country: 'Germany',
      sizes: 'size not stated on the model card',
    },
  },
];
