// Волна 6 (сентябрь 2026): новые семейства из новостей 22.09.2026.
// Факты сверены по Hugging Face / GitHub / официальным блогам на 22.09.2026.
module.exports = [
  {
    id: 'jina-ocr',
    name: 'jina-ocr-v1',
    developer: 'Jina AI', country: 'Германия',
    modality: ['ocr', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '3.4B-A0.6B',
    license: 'CC BY-NC 4.0 — только некоммерческое использование; коммерческую лицензию Jina AI выдаёт по запросу',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['docs', 'finance', 'legal', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Разбор документов одной моделью: страница целиком превращается в Markdown — текст в правильном порядке чтения, таблицы и формулы в LaTeX. Построена на DeepSeek-OCR, активны только 0,6 млрд параметров из 3,4.',
    tasks: ['Перевод сканов и PDF в Markdown', 'Распознавание таблиц и формул', 'Разбор счетов, актов и отчётов', 'Подготовка архива документов к поиску и RAG'],
    where: ['Документооборот', 'Бухгалтерия и финансы', 'Юридические отделы', 'Наука и образование'],
    versions: [['jina-ocr-v1', '2026-09']],
    hf: 'https://huggingface.co/jinaai/jina-ocr-v1',
    github: null,
    alternatives: ['deepseek-ocr', 'dots-ocr', 'olmocr'],
    source: 'https://huggingface.co/jinaai/jina-ocr-v1',
    verified: true,
    en: {
      summary: 'Document parsing in a single model: a whole page becomes Markdown - text in correct reading order, tables and formulas in LaTeX. Built on DeepSeek-OCR, with only 0.6B of its 3.4B parameters active.',
      tasks: ['Converting scans and PDFs to Markdown', 'Recognizing tables and formulas', 'Parsing invoices, acts and reports', 'Preparing a document archive for search and RAG'],
      where: ['Document management', 'Accounting and finance', 'Legal departments', 'Science and education'],
      license: 'CC BY-NC 4.0 - non-commercial use only; Jina AI issues a commercial license on request',
      country: 'Germany',
    },
  },
  {
    id: 'samsone',
    name: 'Samsone',
    developer: 'Samsung', country: 'Южная Корея',
    modality: ['omni'],
    first: '2026-09', latest: '2026-09',
    sizes: '99M – 356M',
    license: 'Лицензия на веса и код в репозитории не указана — файла LICENSE нет, прав на коммерческое использование никто не давал; условия надо уточнять у Samsung (лицензия CC BY 4.0 относится только к статье на arXiv)',
    commercial: 'no',
    hardware: ['min'],
    ru: 'no',
    industries: ['media', 'manufacturing', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Крошечные модели понимания звука для смартфона: слушают речь, музыку и звуки вокруг и отвечают текстом — описывают запись и отвечают на вопросы о ней. Работают прямо на устройстве, вопросы и ответы — на английском: других языков в обучающих данных нет.',
    tasks: ['Описание аудиозаписи словами', 'Ответы на вопросы о звуке', 'Определение типа звука и обстановки', 'Обработка звука на устройстве без отправки в облако'],
    where: ['Мобильные приложения', 'Медиа и аудиопродакшн', 'Производство и мониторинг оборудования'],
    versions: [['Samsone-99M / 134M / 356M', '2026-09']],
    hf: null,
    github: 'https://github.com/SamsungLabs/samsone',
    alternatives: ['audio-flamingo', 'kimi-audio', 'qwen-omni'],
    source: 'https://github.com/SamsungLabs/samsone/releases/tag/v1.0.0',
    verified: true,
    en: {
      summary: 'Tiny audio-understanding models for smartphones: they listen to speech, music and ambient sounds and answer in text - describing a recording and answering questions about it. They run on the device itself; prompts and answers are in English - no other languages are present in the training data.',
      tasks: ['Describing an audio recording in words', 'Answering questions about a sound', 'Identifying the type of sound and the setting', 'Processing audio on the device without sending it to the cloud'],
      where: ['Mobile apps', 'Media and audio production', 'Manufacturing and equipment monitoring'],
      license: 'No license is stated for the weights or the code in the repository - there is no LICENSE file and no one has granted commercial rights; terms must be clarified with Samsung (the CC BY 4.0 license applies only to the arXiv paper)',
      country: 'South Korea',
    },
  },
];
