// Волна 7, группа «HR и подбор персонала»: разбор резюме, матчинг резюме и вакансий, извлечение навыков,
// таксономии профессий, извлечение полей из документов кандидатов.
// Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  // ---------- МАТЧИНГ ВАКАНСИЙ И ДОЛЖНОСТЕЙ ----------
  {
    id: 'jobbert',
    name: 'JobBERT (TechWolf)',
    developer: 'TechWolf', country: 'Бельгия',
    modality: ['embed', 'nlp'],
    first: '2024-12', latest: '2025-06',
    sizes: '109M – 278M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['hr'],
    ollama: false,
    cpu: true,
    quant: ['gguf'],
    summary: 'Модель бельгийской HR-компании: превращает названия должностей в векторы, чтобы находить похожие вакансии и резюме. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Сопоставление названий должностей из разных источников', 'Поиск похожих вакансий и резюме по смыслу', 'Наведение порядка в справочнике должностей компании'],
    where: ['HR и подбор персонала', 'Кадровые агентства', 'Сайты и агрегаторы вакансий'],
    versions: [['JobBERT-v2', '2024-12'], ['JobBERT-v3, многоязычная', '2025-06']],
    hf: 'https://huggingface.co/TechWolf/JobBERT-v3',
    github: null,
    alternatives: ['context-skill', 'escoxlm-r', 'bge-m3'],
    source: 'https://huggingface.co/TechWolf/JobBERT-v3',
    verified: true,
    en: {
      summary: 'A model from a Belgian HR company: it turns job titles into vectors so you can find similar vacancies and resumes. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Matching job titles coming from different sources', 'Finding similar vacancies and resumes by meaning', 'Cleaning up the company job title reference list'],
      where: ['HR and recruiting', 'Staffing agencies', 'Job boards and aggregators'],
      license: 'MIT',
      country: 'Belgium',
    },
  },
  {
    id: 'context-skill',
    name: 'ConTeXT-Skill-Extraction',
    developer: 'TechWolf', country: 'Бельгия',
    modality: ['embed', 'nlp'],
    first: '2024-12', latest: '2024-12',
    sizes: '109M',
    license: 'на карточке модели лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['hr', 'education'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Находит в тексте вакансии или резюме упоминания навыков и сопоставляет их со справочником компании. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Извлечение навыков из описания вакансии', 'Сопоставление навыков кандидата с требованиями', 'Карта компетенций по подразделениям'],
    where: ['HR и подбор персонала', 'Обучение и развитие персонала', 'Кадровые агентства'],
    versions: [['ConTeXT-Skill-Extraction-base', '2024-12']],
    hf: 'https://huggingface.co/TechWolf/ConTeXT-Skill-Extraction-base',
    github: null,
    alternatives: ['jobbert', 'escoxlm-r', 'gliner'],
    source: 'https://huggingface.co/TechWolf/ConTeXT-Skill-Extraction-base',
    verified: true,
    en: {
      summary: 'Finds mentions of skills in a vacancy or resume text and maps them to the company skill reference list. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Extracting skills from a job description', 'Matching candidate skills against requirements', 'Building a competence map across departments'],
      where: ['HR and recruiting', 'Learning and development', 'Staffing agencies'],
      license: 'no license is stated on the model card — check with the developer',
      country: 'Belgium',
    },
  },
  // ---------- НАВЫКИ И ТАКСОНОМИИ ПРОФЕССИЙ ----------
  {
    id: 'escoxlm-r',
    name: 'ESCOXLM-R и JobBERT (ITU Copenhagen)',
    developer: 'Mike Zhang, Rob van der Goot, Barbara Plank (IT University of Copenhagen и LMU Munich)', country: 'Дания',
    modality: ['nlp', 'text'],
    first: '2022-04', latest: '2023-11',
    sizes: '110M – 560M',
    license: 'Apache 2.0 у ESCOXLM-R; у ранних моделей JobBERT и JobSpanBERT лицензия на карточке не указана',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['hr', 'education', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Научная линейка моделей для текстов рынка труда: обучены на объявлениях о работе и европейском справочнике профессий ESCO, вытаскивают из вакансий навыки и требования. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Извлечение навыков и требований из текста вакансии', 'Приведение навыков к единому справочнику ESCO', 'Классификация вакансий и должностей', 'Аналитика по рынку труда'],
    where: ['HR и подбор персонала', 'Сайты вакансий', 'Исследования рынка труда'],
    versions: [['JobBERT и JobSpanBERT', '2022-04'], ['JobBERTa', '2023-03'], ['JobBERT skill и knowledge extraction', '2023-04'], ['ESCOXLM-R на базе XLM-R large', '2023-05'], ['ESCOXLM-R skill и knowledge extraction', '2023-11']],
    hf: 'https://huggingface.co/jjzha/esco-xlm-roberta-large',
    github: 'https://github.com/jjzha/escoxlmr',
    alternatives: ['jobbert', 'context-skill', 'gliner'],
    source: 'https://huggingface.co/jjzha/esco-xlm-roberta-large',
    verified: true,
    en: {
      summary: 'A research line of models for labour market texts: trained on job postings and the European ESCO occupation taxonomy, they pull skills and requirements out of vacancies. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Extracting skills and requirements from vacancy text', 'Mapping skills to the single ESCO reference list', 'Classifying vacancies and job titles', 'Labour market analytics'],
      where: ['HR and recruiting', 'Job boards', 'Labour market research'],
      license: 'Apache 2.0 for ESCOXLM-R; the early JobBERT and JobSpanBERT models state no license on their cards',
      developer: 'Mike Zhang, Rob van der Goot, Barbara Plank (IT University of Copenhagen and LMU Munich)',
      country: 'Denmark',
    },
  },
  {
    id: 'careerbert',
    name: 'CareerBERT',
    developer: 'Авторы статьи CareerBERT, немецкие университеты', country: 'Германия',
    modality: ['embed', 'nlp'],
    first: '2025-02', latest: '2025-02',
    sizes: '110M',
    license: 'на карточке модели лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['hr', 'education'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Немецкоязычная модель, которая сопоставляет резюме с профессиями из европейского справочника ESCO и подсказывает подходящие направления. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Подбор профессий под опыт кандидата', 'Сопоставление резюме и описаний вакансий', 'Подсказки по карьерным переходам внутри компании'],
    where: ['HR и подбор персонала', 'Карьерные консультации', 'Обучение и развитие персонала'],
    versions: [['CareerBERT-JG на базе jobGBERT', '2025-02'], ['CareerBERT-G на базе gbert-base', '2025-02']],
    hf: 'https://huggingface.co/lwolfrum2/careerbert-jg',
    github: null,
    alternatives: ['jobbert', 'escoxlm-r', 'occcanine'],
    source: 'https://huggingface.co/lwolfrum2/careerbert-jg',
    verified: true,
    en: {
      summary: 'A German-language model that matches a resume to occupations from the European ESCO reference list and suggests suitable directions. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Suggesting occupations that fit the candidate experience', 'Matching resumes against job descriptions', 'Hints on internal career moves'],
      where: ['HR and recruiting', 'Career counselling', 'Learning and development'],
      license: 'no license is stated on the model card — check with the developer',
      developer: 'The authors of the CareerBERT paper, German universities',
      country: 'Germany',
    },
  },
  {
    id: 'occcanine',
    name: 'OccCANINE',
    developer: 'University of Southern Denmark', country: 'Дания',
    modality: ['nlp'],
    first: '2024-02', latest: '2024-04',
    sizes: 'на базе CANINE-s, размер на карточке не указан',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['hr', 'science', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Переводит свободное описание профессии в стандартный код HISCO на 13 языках. Создана для исторических архивов, но годится и для наведения порядка в справочниках должностей. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Приведение разнородных названий профессий к единому коду', 'Разбор архивов кадровых и статистических данных', 'Подготовка данных для отчётности'],
    where: ['HR и кадровый учёт', 'Исследования и статистика', 'Госсектор'],
    versions: [['OccCANINE', '2024-02']],
    hf: 'https://huggingface.co/Christianvedel/OccCANINE',
    github: 'https://github.com/christianvedels/OccCANINE',
    alternatives: ['escoxlm-r', 'careerbert', 'xlm-roberta'],
    source: 'https://huggingface.co/Christianvedel/OccCANINE',
    verified: true,
    en: {
      summary: 'Turns a free-form occupation description into a standard HISCO code in 13 languages. Built for historical archives, but also useful for cleaning up job title reference lists. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Mapping mixed occupation names onto a single code', 'Processing archives of HR and statistical data', 'Preparing data for reporting'],
      where: ['HR and personnel records', 'Research and statistics', 'Public sector'],
      license: 'Apache 2.0',
      developer: 'University of Southern Denmark',
      country: 'Denmark',
      sizes: 'based on CANINE-s, size not stated on the model card',
    },
  },
  // ---------- РАЗБОР РЕЗЮМЕ ----------
  {
    id: 'qwen3vl-resume-parser',
    name: 'Qwen3-VL Resume Parser',
    developer: 'Sukhrob Nurali', country: 'не раскрыта',
    modality: ['vlm', 'ocr'],
    first: '2026-02', latest: '2026-02',
    sizes: '8B, дообучение Qwen3-VL-8B-Instruct',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['hr', 'docs'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Дообученная Qwen3-VL-8B читает страницы резюме как картинки и возвращает запись из 23 полей в JSON. Автор прямо пишет: для автоматических решений по кандидатам модель не предназначена, решение принимает человек.',
    tasks: ['Перенос резюме из PDF в карточку кандидата', 'Заполнение базы кандидатов без ручного ввода', 'Разбор резюме с разной вёрсткой и оформлением'],
    where: ['HR и подбор персонала', 'Кадровые агентства', 'Документооборот'],
    versions: [['qwen3vl-resume-parser на базе Qwen3-VL-8B-Instruct', '2026-02']],
    hf: 'https://huggingface.co/sukhrobnurali/qwen3vl-resume-parser',
    github: 'https://github.com/sukhrobnurali/resume-trainer',
    alternatives: ['nuextract', 'qwen-vl', 'docling'],
    source: 'https://huggingface.co/sukhrobnurali/qwen3vl-resume-parser',
    verified: true,
    en: {
      summary: 'A fine-tuned Qwen3-VL-8B reads resume pages as images and returns a 23-field JSON record. The author states plainly that the model is not meant for automated decisions about candidates; a human decides.',
      tasks: ['Moving a resume from PDF into a candidate record', 'Filling a candidate database without manual typing', 'Parsing resumes with different layouts and styling'],
      where: ['HR and recruiting', 'Staffing agencies', 'Document workflows'],
      license: 'Apache 2.0',
      country: 'not disclosed',
      sizes: '8B, a fine-tune of Qwen3-VL-8B-Instruct',
    },
  },
  // ---------- ИЗВЛЕЧЕНИЕ ПОЛЕЙ ИЗ ДОКУМЕНТОВ КАНДИДАТА ----------
  {
    id: 'donut',
    name: 'Donut',
    developer: 'NAVER CLOVA', country: 'Южная Корея',
    modality: ['ocr', 'vlm'],
    first: '2022-07', latest: '2022-07',
    sizes: 'около 200M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['docs', 'hr', 'finance'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Читает скан документа и сразу отдаёт заполненную структуру полей, без отдельного OCR. В HR её дообучают под разбор резюме и анкет. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Извлечение полей из анкет и резюме', 'Разбор сканов справок и дипломов', 'Определение типа входящего документа'],
    where: ['HR и подбор персонала', 'Документооборот', 'Бухгалтерия'],
    versions: [['donut-base', '2022-07'], ['donut-base-finetuned-cord-v2, чеки', '2022-07'], ['donut-base-finetuned-docvqa, вопросы к документу', '2022-07'], ['donut-base-finetuned-rvlcdip, типы документов', '2022-07']],
    hf: 'https://huggingface.co/naver-clova-ix/donut-base',
    github: 'https://github.com/clovaai/donut',
    alternatives: ['nuextract', 'layoutlm', 'trocr'],
    source: 'https://huggingface.co/naver-clova-ix/donut-base',
    verified: true,
    en: {
      summary: 'Reads a scanned document and returns a filled-in field structure straight away, with no separate OCR step. In HR it is fine-tuned for parsing resumes and forms. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Extracting fields from forms and resumes', 'Parsing scans of certificates and diplomas', 'Detecting the type of an incoming document'],
      where: ['HR and recruiting', 'Document workflows', 'Accounting'],
      license: 'MIT',
      country: 'South Korea',
      sizes: 'about 200M',
    },
  },
  {
    id: 'lilt',
    name: 'LiLT',
    developer: 'SCUT DLVC Lab, Южно-Китайский технологический университет', country: 'Китай',
    modality: ['ocr', 'nlp'],
    first: '2022-09', latest: '2022-10',
    sizes: 'около 130M английская и около 280M многоязычная версия',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['docs', 'hr', 'finance'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Лёгкая модель, которая учитывает и текст, и расположение блоков на странице: обучается на одном языке и переносится на другие. Подходит для разметки полей резюме и анкет. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Разметка полей в резюме и анкетах', 'Извлечение данных из форм и бланков', 'Разбор документов на нескольких языках'],
    where: ['HR и подбор персонала', 'Документооборот', 'Финансовые отделы'],
    versions: [['LiLT-RoBERTa-en-base', '2022-09'], ['LiLT-InfoXLM-base, многоязычная', '2022-10']],
    hf: 'https://huggingface.co/SCUT-DLVCLab/lilt-roberta-en-base',
    github: 'https://github.com/jpWang/LiLT',
    alternatives: ['layoutlm', 'donut', 'table-transformer'],
    source: 'https://huggingface.co/SCUT-DLVCLab/lilt-roberta-en-base',
    verified: true,
    en: {
      summary: 'A light model that takes both the text and the position of blocks on the page into account: trained in one language and transferable to others. Good for tagging fields in resumes and forms. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Tagging fields in resumes and forms', 'Extracting data from forms and templates', 'Parsing documents in several languages'],
      where: ['HR and recruiting', 'Document workflows', 'Finance departments'],
      license: 'MIT',
      developer: 'SCUT DLVC Lab, South China University of Technology',
      country: 'China',
      sizes: 'about 130M for the English version and about 280M for the multilingual one',
    },
  },
  {
    id: 'udop',
    name: 'UDOP',
    developer: 'Microsoft', country: 'США',
    modality: ['ocr', 'vlm'],
    first: '2024-02', latest: '2024-02',
    sizes: '742M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['docs', 'hr', 'finance'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Одна модель на все задачи с документом: чтение, ответы на вопросы по странице, извлечение полей, классификация. В HR применяется для разбора резюме и приложенных сканов. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Извлечение полей из резюме и приложений к нему', 'Ответы на вопросы по содержимому документа', 'Классификация входящих документов'],
    where: ['HR и подбор персонала', 'Документооборот', 'Бухгалтерия'],
    versions: [['udop-large', '2024-02'], ['udop-large-512', '2024-02'], ['udop-large-512-300k', '2024-02']],
    hf: 'https://huggingface.co/microsoft/udop-large',
    github: 'https://github.com/microsoft/i-Code/tree/main/i-Code-Doc',
    alternatives: ['layoutlm', 'donut', 'lilt'],
    source: 'https://huggingface.co/microsoft/udop-large',
    verified: true,
    en: {
      summary: 'One model for every document task: reading, answering questions about a page, extracting fields, classification. In HR it is used to parse resumes and attached scans. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Extracting fields from a resume and its attachments', 'Answering questions about document content', 'Classifying incoming documents'],
      where: ['HR and recruiting', 'Document workflows', 'Accounting'],
      license: 'MIT',
      country: 'USA',
    },
  },
  {
    id: 'pix2struct',
    name: 'Pix2Struct',
    developer: 'Google', country: 'США',
    modality: ['vlm', 'ocr'],
    first: '2023-03', latest: '2023-03',
    sizes: '282M – 1.3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['docs', 'hr', 'finance'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Читает документ или скриншот как картинку и отвечает структурой: текст, поля, ответы на вопросы. В HR её дообучают под резюме и анкеты. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Извлечение данных из резюме и анкет в виде картинок', 'Вопросы к содержимому скана', 'Разбор таблиц и схем в документах'],
    where: ['HR и подбор персонала', 'Документооборот', 'Аналитика'],
    versions: [['pix2struct-base и pix2struct-large', '2023-03'], ['pix2struct-docvqa, вопросы к документу', '2023-03'], ['pix2struct-chartqa и ai2d, графики и схемы', '2023-03']],
    hf: 'https://huggingface.co/google/pix2struct-base',
    github: 'https://github.com/google-research/pix2struct',
    alternatives: ['donut', 'udop', 'nuextract'],
    source: 'https://huggingface.co/google/pix2struct-base',
    verified: true,
    en: {
      summary: 'Reads a document or a screenshot as an image and answers with structure: text, fields, answers to questions. In HR it is fine-tuned for resumes and forms. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Extracting data from resumes and forms supplied as images', 'Questions about the content of a scan', 'Parsing tables and diagrams in documents'],
      where: ['HR and recruiting', 'Document workflows', 'Analytics'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'kosmos-2-5',
    name: 'Kosmos-2.5',
    developer: 'Microsoft', country: 'США',
    modality: ['ocr', 'vlm'],
    first: '2024-05', latest: '2024-08',
    sizes: 'около 1.4B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['docs', 'hr'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Превращает скан страницы в размеченный текст с координатами блоков или в markdown. Удобна как первый шаг перед разбором резюме. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Перевод сканов резюме в текст с сохранением структуры', 'Подготовка документов к извлечению полей', 'Оцифровка бумажных анкет'],
    where: ['HR и подбор персонала', 'Документооборот', 'Архивы'],
    versions: [['Kosmos-2.5', '2024-05'], ['Kosmos-2.5-chat', '2024-08']],
    hf: 'https://huggingface.co/microsoft/kosmos-2.5',
    github: 'https://github.com/microsoft/unilm/tree/master/kosmos-2.5',
    alternatives: ['got-ocr', 'olmocr', 'donut'],
    source: 'https://huggingface.co/microsoft/kosmos-2.5',
    verified: true,
    en: {
      summary: 'Turns a scanned page into tagged text with block coordinates, or into markdown. Handy as the first step before parsing a resume. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Converting resume scans into text that keeps its structure', 'Preparing documents for field extraction', 'Digitising paper forms'],
      where: ['HR and recruiting', 'Document workflows', 'Archives'],
      license: 'MIT',
      country: 'USA',
      sizes: 'about 1.4B',
    },
  },
  {
    id: 'dit-docs',
    name: 'DiT (Document Image Transformer)',
    developer: 'Microsoft', country: 'США',
    modality: ['vision', 'ocr'],
    first: '2022-03', latest: '2022-03',
    sizes: 'версии base и large',
    license: 'MIT по репозиторию microsoft/unilm; на карточках Hugging Face лицензия не указана',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['docs', 'hr'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'По картинке определяет, что за документ перед ней: резюме, диплом, справка, договор. Помогает раскладывать пакеты файлов от кандидатов по типам. Решение о кандидате принимает человек, автоматический отбор без проверки использовать нельзя.',
    tasks: ['Сортировка входящих документов кандидатов по типам', 'Проверка комплектности пакета документов', 'Поиск нужного скана в архиве'],
    where: ['HR и кадровый учёт', 'Документооборот', 'Архивы'],
    versions: [['DiT-base и DiT-large', '2022-03'], ['DiT, дообученная на RVL-CDIP, 16 типов документов', '2022-03']],
    hf: 'https://huggingface.co/microsoft/dit-base',
    github: 'https://github.com/microsoft/unilm/tree/master/dit',
    alternatives: ['donut', 'layoutlm', 'docling'],
    source: 'https://huggingface.co/microsoft/dit-base',
    verified: true,
    en: {
      summary: 'From an image it works out what kind of document it is: resume, diploma, certificate, contract. Helps sort candidate file bundles by type. A human makes the decision about a candidate; automatic screening without review must not be used.',
      tasks: ['Sorting incoming candidate documents by type', 'Checking that a document package is complete', 'Finding the right scan in an archive'],
      where: ['HR and personnel records', 'Document workflows', 'Archives'],
      license: 'MIT per the microsoft/unilm repository; no license is stated on the Hugging Face cards',
      country: 'USA',
      sizes: 'base and large versions',
    },
  },
];
