// Новые открытые модели, сверено по Hugging Face на 28.09.2026.
// FLUX 3 Action (управление роботом) и Ming-Image Design (дизайн-картинки со слоями).
module.exports = [
  {
    id: 'flux-action',
    name: 'FLUX.3 Action',
    developer: 'Black Forest Labs', country: 'Германия',
    modality: ['robotics'],
    first: '2026-09', latest: '2026-09',
    sizes: '7B',
    license: 'FLUX Kommunity License 1.0 (коммерческое использование только при выручке компании до $5 млн в год; текстовый энкодер под Apache 2.0)',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['manufacturing', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Открытая модель управления роботом: по кадру с камеры, положению механизма и текстовой команде выдаёт следующие движения. Первое место на бенчмарке RoboLab-120, помещается в видеокарту на 24 ГБ.',
    tasks: ['управление роботом-манипулятором', 'сортировка и упаковка на складе', 'операции взять и переставить', 'дообучение под свой робот'],
    where: ['склад и логистика', 'производство', 'робототехника'],
    versions: [['FLUX 3 Action Base', '2026-09']],
    hf: 'https://huggingface.co/black-forest-labs/flux-3-action-base',
    github: null,
    alternatives: ['openvla', 'cosmos', 'gr00t'],
    source: 'https://huggingface.co/black-forest-labs/flux-3-action-base',
    verified: true,
  },
  {
    id: 'ming-image',
    name: 'Ming-Image Design',
    developer: 'inclusionAI (Ant Group)', country: 'Китай',
    modality: ['image'],
    first: '2026-09', latest: '2026-09',
    sizes: '6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['marketing', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Открытая модель генерации картинок под дизайн: интерфейсы, инфографика, постеры, текст на изображении. Отдаёт результат слоями с прозрачным фоном, его удобно дорабатывать.',
    tasks: ['баннеры и постеры', 'инфографика', 'макеты интерфейсов', 'картинки с текстом и логотипом'],
    where: ['маркетинг', 'дизайн и медиа', 'реклама'],
    versions: [['Ming-Image-0.1-Design', '2026-09'], ['Ming-Image-0.1-Design-Layer', '2026-09']],
    hf: 'https://huggingface.co/inclusionAI/Ming-Image-0.1-Design',
    github: null,
    alternatives: ['qwen-image', 'flux', 'glm-image'],
    source: 'https://huggingface.co/inclusionAI/Ming-Image-0.1-Design',
    verified: true,
  },
];
