// Волна 8: рекомендательные системы — похожие товары, «с этим покупают», персональная лента,
// ранжирование выдачи в магазине. Факты сверены по Hugging Face / GitHub на 23.09.2026.
// Общая оговорка группы: почти все эти модели надо дообучать на истории заказов и просмотров
// конкретного магазина — готовых рекомендаций «из коробки» они не дают.
module.exports = [
  // ---------- ГЕНЕРАТИВНЫЕ РЕКОМЕНДАТЕЛИ НОВОГО ПОКОЛЕНИЯ ----------
  {
    id: 'openonerec',
    name: 'OneRec (OpenOneRec)',
    developer: 'Kuaishou', country: 'Китай',
    modality: ['recsys', 'text'],
    first: '2025-12', latest: '2026-07',
    sizes: '1.7B, 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['retail', 'media', 'marketing'],
    ollama: false,
    cpu: true,
    quant: ['gguf'],
    summary: 'Открытая базовая модель рекомендаций от сервиса коротких видео: история просмотров и покупок подаётся модели как последовательность и она предсказывает следующий товар или ролик. Нужно дообучение на своих данных.',
    tasks: ['Персональная лента товаров или контента', 'Подбор следующего товара по истории заказов', 'Рекомендации в рекламных блоках', 'Объяснение, почему показана эта карточка'],
    where: ['Интернет-магазины и маркетплейсы', 'Медиа и видеосервисы', 'Реклама и маркетинг'],
    versions: [['OneRec-1.7B и OneRec-8B', '2025-12'], ['Технический отчёт и набор задач RecIF-Bench', '2026-01'], ['OneRec-Tokenizer для своих каталогов', '2026-01'], ['OneRec-1.7B-pretrain', '2026-02'], ['OneReason-0.8B', '2026-06'], ['OneReason-8B', '2026-07']],
    hf: 'https://huggingface.co/OpenOneRec',
    github: 'https://github.com/Kuaishou-OneRec/OpenOneRec',
    alternatives: ['hllm', 'minionerec', 'recgpt'],
    source: 'https://huggingface.co/OpenOneRec/OneRec-1.7B',
    verified: true,
    en: {
      summary: 'An open foundation model for recommendations from a short-video service: browsing and purchase history is fed to the model as a sequence and it predicts the next item or clip. Fine-tuning on your own data is required.',
      tasks: ['A personal feed of products or content', 'Picking the next item from order history', 'Recommendations inside ad slots', 'Explaining why a given card is shown'],
      where: ['Online stores and marketplaces', 'Media and video services', 'Advertising and marketing'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'hllm',
    name: 'HLLM',
    developer: 'ByteDance', country: 'Китай',
    modality: ['recsys', 'text'],
    first: '2024-09', latest: '2025-08',
    sizes: '1B, 7B',
    license: 'Apache 2.0 на карточке весов; отдельные сборки обучены поверх Baichuan2 с собственной лицензией',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['retail', 'media', 'marketing'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Двухуровневая схема: одна языковая модель читает описание товара, вторая собирает из истории интерес покупателя. Выложены готовые чекпойнты на 1B и 7B, но под свой каталог их надо дообучать.',
    tasks: ['Рекомендации по истории просмотров и покупок', 'Понимание товара по названию и описанию', 'Подбор карточек для новых позиций без статистики', 'Персональные заголовки и подписи к карточкам'],
    where: ['Интернет-магазины и маркетплейсы', 'Контентные площадки', 'Реклама и продвижение'],
    versions: [['HLLM-1B и HLLM-7B (наборы Books и Pixel8M)', '2024-09'], ['HLLM-Creator: персональные тексты к карточкам', '2025-08']],
    hf: 'https://huggingface.co/ByteDance/HLLM',
    github: 'https://github.com/bytedance/HLLM',
    alternatives: ['openonerec', 'recgpt', 'minionerec'],
    source: 'https://huggingface.co/ByteDance/HLLM',
    verified: true,
    en: {
      summary: 'A two-level design: one language model reads the item description, the second builds the shopper interest from history. Ready checkpoints at 1B and 7B are published, but they need fine-tuning for your own catalogue.',
      tasks: ['Recommendations from browsing and purchase history', 'Understanding an item from its title and description', 'Suggesting cards for new items with no statistics', 'Personalised titles and captions for cards'],
      where: ['Online stores and marketplaces', 'Content platforms', 'Advertising and promotion'],
      license: 'Apache 2.0 on the weights card; some builds are trained on top of Baichuan2, which has its own licence',
      country: 'China',
    },
  },
  {
    id: 'minionerec',
    name: 'MiniOneRec',
    developer: 'Открытый проект MiniOneRec', country: 'Китай',
    modality: ['recsys', 'text'],
    first: '2025-10', latest: '2025-10',
    sizes: '1.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['retail', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Небольшой открытый генеративный рекомендатель на 1,5B с выложенными чекпойнтами и полным циклом обучения. Удобен как учебный и стартовый вариант, под реальный магазин требует дообучения на своих заказах.',
    tasks: ['Быстрый прототип рекомендаций на своих данных', 'Проверка гипотез до запуска большой модели', 'Обучение команды работе с генеративными рекомендациями', 'Рекомендации для небольшого каталога'],
    where: ['Интернет-магазины', 'ИТ-отделы и подрядчики', 'Исследования и обучение'],
    versions: [['MiniOneRec: чекпойнты Industrial и Office на базе Qwen2.5-1.5B-Instruct', '2025-10']],
    hf: 'https://huggingface.co/kkknight/MiniOneRec',
    github: 'https://github.com/AkaliKong/MiniOneRec',
    alternatives: ['openonerec', 'hllm', 'lc-rec'],
    source: 'https://huggingface.co/kkknight/MiniOneRec',
    verified: true,
    en: {
      summary: 'A small open generative recommender at 1.5B with published checkpoints and a full training pipeline. Handy as a learning and starter option; a real store needs fine-tuning on its own orders.',
      tasks: ['A quick recommendation prototype on your own data', 'Testing ideas before running a large model', 'Training a team to work with generative recommendations', 'Recommendations for a small catalogue'],
      where: ['Online stores', 'IT departments and contractors', 'Research and training'],
      license: 'Apache 2.0',
      developer: 'MiniOneRec open project',
      country: 'China',
    },
  },
  // ---------- РЕКОМЕНДАТЕЛИ НА ЯЗЫКОВЫХ МОДЕЛЯХ ----------
  {
    id: 'recgpt',
    name: 'RecGPT',
    developer: 'VinAI Research', country: 'Вьетнам',
    modality: ['recsys', 'text'],
    first: '2024-04', latest: '2024-04',
    sizes: '7B',
    license: 'CC BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['retail', 'media', 'science'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Языковая модель на 7B, дообученная на текстах отзывов и карточек товаров под задачи рекомендаций и предсказания оценки. Лицензия запрещает коммерческое использование, для магазина нужна своя история заказов.',
    tasks: ['Предсказание оценки товара пользователем', 'Подбор следующей покупки по истории', 'Исследование текстовых рекомендаций', 'Сравнение подходов на своих данных'],
    where: ['Исследовательские команды', 'Интернет-магазины (некоммерческие пилоты)', 'Медиа и контентные каталоги'],
    versions: [['RecGPT-7B', '2024-04'], ['RecGPT-7B-Instruct', '2024-04']],
    hf: 'https://huggingface.co/vinai/RecGPT-7B',
    github: 'https://github.com/VinAIResearch/RecGPT',
    alternatives: ['ecellm', 'lc-rec', 'p5'],
    source: 'https://huggingface.co/vinai/RecGPT-7B',
    verified: true,
    en: {
      summary: 'A 7B language model further trained on review and product-card text for recommendation and rating-prediction tasks. The licence forbids commercial use; a store still needs its own order history.',
      tasks: ['Predicting the rating a user would give an item', 'Suggesting the next purchase from history', 'Researching text-based recommendations', 'Comparing approaches on your own data'],
      where: ['Research teams', 'Online stores (non-commercial pilots)', 'Media and content catalogues'],
      license: 'CC BY-NC 4.0 - non-commercial use only',
      country: 'Vietnam',
    },
  },
  {
    id: 'ecellm',
    name: 'eCeLLM',
    developer: 'Ohio State University (NingLab)', country: 'США',
    modality: ['recsys', 'text'],
    first: '2024-02', latest: '2024-07',
    sizes: '2.7B – 13B',
    license: 'CC BY 4.0 на веса; базовые модели Phi-2, Mistral и Llama 2 идут со своими условиями',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['retail', 'support', 'marketing'],
    ollama: false,
    cpu: true,
    quant: ['gguf'],
    summary: 'Три языковые модели, дообученные на большом наборе торговых инструкций: подбор товара, ответы по карточке, сопоставление позиций, разбор отзывов. Под свой ассортимент всё равно нужно дообучение.',
    tasks: ['Подбор товара по запросу покупателя', 'Ответы на вопросы по карточке товара', 'Сопоставление одинаковых позиций в каталогах', 'Разбор отзывов и вопросов покупателей'],
    where: ['Интернет-магазины и маркетплейсы', 'Поддержка покупателей', 'Контент-отделы и карточки товаров'],
    versions: [['eCeLLM-S (на базе Phi-2)', '2024-02'], ['eCeLLM-M (на базе Mistral 7B Instruct)', '2024-02'], ['eCeLLM-L (13B)', '2024-02'], ['Обновление карточек и весов', '2024-07']],
    hf: 'https://huggingface.co/NingLab/eCeLLM-M',
    github: 'https://github.com/ninglab/eCeLLM',
    alternatives: ['recgpt', 'openonerec', 'easyrec'],
    source: 'https://huggingface.co/NingLab/eCeLLM-M',
    verified: true,
    en: {
      summary: 'Three language models tuned on a large set of commerce instructions: product selection, answers from the item card, matching listings, review analysis. Your own assortment still needs fine-tuning.',
      tasks: ['Finding a product from a shopper request', 'Answering questions about an item card', 'Matching identical listings across catalogues', 'Analysing reviews and customer questions'],
      where: ['Online stores and marketplaces', 'Customer support', 'Content teams and product cards'],
      license: 'CC BY 4.0 on the weights; the base models Phi-2, Mistral and Llama 2 come with their own terms',
      country: 'USA',
    },
  },
  {
    id: 'p5',
    name: 'P5',
    developer: 'Rutgers University', country: 'США',
    modality: ['recsys', 'text'],
    first: '2022-12', latest: '2022-12',
    sizes: 'версии small и base на базе T5',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'media', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Ранняя и до сих пор популярная работа, где рекомендации задаются обычным текстом: один и тот же небольшой движок отвечает на подбор, оценку и объяснение. Чекпойнты обучены на открытых наборах, для магазина нужен свой.',
    tasks: ['Подбор следующего товара по истории', 'Предсказание оценки товара', 'Текстовое объяснение рекомендации', 'База для собственных экспериментов'],
    where: ['Интернет-магазины', 'Медиа и каталоги отзывов', 'Исследования и обучение'],
    versions: [['P5 (beauty, small)', '2022-12'], ['P5 sports, toys, yelp — версии small и base', '2022-12']],
    hf: 'https://huggingface.co/makitanikaze/P5',
    github: 'https://github.com/jeykigung/P5',
    alternatives: ['recgpt', 'lc-rec', 'openonerec'],
    source: 'https://huggingface.co/makitanikaze/P5',
    verified: true,
    en: {
      summary: 'An early and still popular approach where recommendations are expressed as plain text: one small engine handles selection, rating and explanation. Checkpoints are trained on public datasets; a store needs its own.',
      tasks: ['Suggesting the next item from history', 'Predicting an item rating', 'A text explanation of a recommendation', 'A base for your own experiments'],
      where: ['Online stores', 'Media and review catalogues', 'Research and training'],
      license: 'MIT',
      country: 'USA',
      sizes: 'small and base versions built on T5',
    },
  },
  {
    id: 'lc-rec',
    name: 'LC-Rec',
    developer: 'Renmin University of China', country: 'Китай',
    modality: ['recsys', 'text'],
    first: '2023-11', latest: '2023-11',
    sizes: 'около 7B (дельта к весам LLaMA)',
    license: 'на карточках и в репозитории лицензия не указана; веса выложены как дельта к LLaMA, условия LLaMA сохраняются',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['retail', 'media', 'science'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Подход, где каждому товару выдаётся короткий код-идентификатор, понятный языковой модели, и она предсказывает этот код. Выложены дельта-веса по трём категориям, лицензия на карточке не указана.',
    tasks: ['Подбор следующего товара по истории', 'Перевод каталога в короткие коды для модели', 'Рекомендации по текстовому запросу покупателя', 'База для своих экспериментов с кодами товаров'],
    where: ['Интернет-магазины', 'Каталоги и маркетплейсы', 'Исследовательские команды'],
    versions: [['LC-Rec: дельта-веса для категорий Games, Arts, Instruments', '2023-11']],
    hf: 'https://huggingface.co/bwzheng0324/lc-rec-games-delta',
    github: 'https://github.com/RUCAIBox/LC-Rec',
    alternatives: ['p5', 'minionerec', 'openonerec'],
    source: 'https://huggingface.co/bwzheng0324/lc-rec-games-delta',
    verified: true,
    en: {
      summary: 'An approach where every item gets a short identifier code that a language model understands, and the model predicts that code. Delta weights for three categories are published; no licence is stated on the card.',
      tasks: ['Suggesting the next item from history', 'Turning a catalogue into short codes for the model', 'Recommendations from a shopper text request', 'A base for your own experiments with item codes'],
      where: ['Online stores', 'Catalogues and marketplaces', 'Research teams'],
      license: 'no licence is stated on the cards or in the repository; the weights are published as a delta to LLaMA, so LLaMA terms still apply',
      country: 'China',
      sizes: 'about 7B (a delta to LLaMA weights)',
    },
  },
  // ---------- ЭМБЕДДИНГИ ТОВАРОВ И «ПОХОЖИЕ ТОВАРЫ» ----------
  {
    id: 'blair',
    name: 'BLaIR',
    developer: 'UC San Diego (McAuley Lab)', country: 'США',
    modality: ['recsys', 'embed'],
    first: '2024-03', latest: '2024-05',
    sizes: '125M и 355M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'marketing', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Лёгкие энкодеры, обученные на парах «карточка товара — живой отзыв»: дают вектора товаров для блоков «похожее» и для поиска по описанию словами покупателя. Веса маленькие, работают на обычном сервере.',
    tasks: ['Блок «похожие товары» по описанию', 'Поиск товара по фразе покупателя', 'Подбор карточек для новых позиций', 'Группировка ассортимента по смыслу'],
    where: ['Интернет-магазины и маркетплейсы', 'Поиск по каталогу', 'Маркетинг и подборки'],
    versions: [['BLaIR-roberta-base и BLaIR-roberta-large', '2024-03'], ['BLaIR-games-roberta-base', '2024-05']],
    hf: 'https://huggingface.co/hyp1231/blair-roberta-base',
    github: 'https://github.com/hyp1231/AmazonReviews2023',
    alternatives: ['easyrec', 'beeformer', 'marqo-ecommerce'],
    source: 'https://huggingface.co/hyp1231/blair-roberta-base',
    verified: true,
    en: {
      summary: 'Light encoders trained on pairs of item card and real review: they produce item vectors for similar-item blocks and for search by a shopper description. The weights are small and run on an ordinary server.',
      tasks: ['A similar-items block based on descriptions', 'Product search from a shopper phrase', 'Suggesting cards for new listings', 'Grouping the assortment by meaning'],
      where: ['Online stores and marketplaces', 'Catalogue search', 'Marketing and curated lists'],
      license: 'MIT',
      country: 'USA',
    },
  },
  {
    id: 'easyrec',
    name: 'EasyRec (HKUDS)',
    developer: 'HKUDS, Университет Гонконга', country: 'Китай',
    modality: ['recsys', 'embed'],
    first: '2024-08', latest: '2024-08',
    sizes: 'три версии на базе RoBERTa: small, base, large',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'media', 'marketing'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Энкодеры, которые сводят в один вектор текстовый портрет покупателя и текстовое описание товара, чтобы сопоставлять их напрямую. Помогают там, где по новой позиции ещё нет статистики покупок.',
    tasks: ['Рекомендации для новых товаров без статистики', 'Подбор по текстовому портрету покупателя', 'Усиление обычных рекомендаций описаниями', 'Похожие позиции внутри каталога'],
    where: ['Интернет-магазины и маркетплейсы', 'Контентные площадки', 'Маркетинг и подборки'],
    versions: [['EasyRec-Small, EasyRec-Base, EasyRec-Large', '2024-08']],
    hf: 'https://huggingface.co/hkuds/easyrec-roberta-large',
    github: 'https://github.com/HKUDS/EasyRec',
    alternatives: ['blair', 'beeformer', 'marqo-ecommerce'],
    source: 'https://huggingface.co/hkuds/easyrec-roberta-large',
    verified: true,
    en: {
      summary: 'Encoders that put a text portrait of a shopper and a text description of an item into one vector space so they can be matched directly. They help where a new listing has no purchase statistics yet.',
      tasks: ['Recommendations for new items with no statistics', 'Matching by a text portrait of the shopper', 'Reinforcing ordinary recommendations with descriptions', 'Similar listings inside the catalogue'],
      where: ['Online stores and marketplaces', 'Content platforms', 'Marketing and curated lists'],
      license: 'Apache 2.0',
      developer: 'HKUDS, University of Hong Kong',
      country: 'China',
      sizes: 'three RoBERTa-based versions: small, base, large',
    },
  },
  {
    id: 'beeformer',
    name: 'beeFormer',
    developer: 'Recombee', country: 'Чехия',
    modality: ['recsys', 'embed'],
    first: '2024-08', latest: '2024-09',
    sizes: 'около 110M (на базе all-mpnet-base-v2)',
    license: 'Llama 3.1 Community License — обучающие тексты получены с помощью Llama 3.1; код репозитория под CC BY-SA 4.0',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'media', 'marketing'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Энкодеры описаний, дообученные так, чтобы близкими считались товары, которые люди действительно берут вместе, а не просто похожие по словам. Выложены версии, обученные на открытых каталогах.',
    tasks: ['Блок «с этим часто берут»', 'Рекомендации для позиций без истории продаж', 'Перенос модели на новый каталог', 'Похожие товары по описанию'],
    where: ['Интернет-магазины', 'Медиатеки и книжные каталоги', 'Маркетинг и подборки'],
    versions: [['Llama-movielens-mpnet, Llama-goodbooks-mpnet, Llama-amazbooks-mpnet, Llama-goodlens-mpnet', '2024-08'], ['Обновление карточек моделей', '2024-09']],
    hf: 'https://huggingface.co/beeformer',
    github: 'https://github.com/recombee/beeformer',
    alternatives: ['blair', 'easyrec', 'marqo-ecommerce'],
    source: 'https://huggingface.co/beeformer/Llama-movielens-mpnet',
    verified: true,
    en: {
      summary: 'Description encoders trained so that items people actually buy together end up close to each other, not merely items that sound alike. Versions trained on public catalogues are published.',
      tasks: ['A frequently-bought-together block', 'Recommendations for listings with no sales history', 'Moving the model to a new catalogue', 'Similar items by description'],
      where: ['Online stores', 'Media libraries and book catalogues', 'Marketing and curated lists'],
      license: 'Llama 3.1 Community License - the training texts were produced with Llama 3.1; the repository code is under CC BY-SA 4.0',
      developer: 'Recombee',
      country: 'Czechia',
      sizes: 'about 110M (built on all-mpnet-base-v2)',
    },
  },
  {
    id: 'marqo-ecommerce',
    name: 'Marqo Ecommerce Embeddings',
    developer: 'Marqo', country: 'Австралия',
    modality: ['recsys', 'embed', 'vision'],
    first: '2024-08', latest: '2024-11',
    sizes: '203M (B) и 652M (L)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: true,
    quant: ['int8', 'int4'],
    summary: 'Модели, которые переводят фото товара и его название в один вектор: подходят для блока «похожие товары», поиска картинкой и подбора по описанию. Заточены под товарные карточки магазинов.',
    tasks: ['Похожие товары по фото и названию', 'Поиск по каталогу картинкой', 'Поиск товара по фразе покупателя', 'Поиск дублей в каталоге'],
    where: ['Интернет-магазины и маркетплейсы', 'Каталоги и витрины', 'Маркетинг и подборки'],
    versions: [['Marqo-FashionCLIP', '2024-08'], ['Marqo-FashionSigLIP', '2024-08'], ['Marqo-Ecommerce-B и Marqo-Ecommerce-L', '2024-09'], ['Обновление карточек и сборок ONNX', '2024-11']],
    hf: 'https://huggingface.co/Marqo/marqo-ecommerce-embeddings-L',
    github: 'https://github.com/marqo-ai/marqo-ecommerce-embeddings',
    alternatives: ['fashion-clip', 'blair', 'easyrec'],
    source: 'https://huggingface.co/Marqo/marqo-ecommerce-embeddings-L',
    verified: true,
    en: {
      summary: 'Models that turn a product photo and its title into a single vector: suitable for a similar-items block, image search and matching by description. Built for retail product cards.',
      tasks: ['Similar items by photo and title', 'Catalogue search by image', 'Product search from a shopper phrase', 'Finding duplicates in the catalogue'],
      where: ['Online stores and marketplaces', 'Catalogues and storefronts', 'Marketing and curated lists'],
      license: 'Apache 2.0',
      country: 'Australia',
    },
  },
  {
    id: 'fashion-clip',
    name: 'FashionCLIP',
    developer: 'Исследовательский проект FashionCLIP (данные Farfetch)', country: 'не раскрыта',
    modality: ['recsys', 'embed', 'vision'],
    first: '2023-02', latest: '2023-03',
    sizes: 'на базе CLIP ViT-B/32',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['retail', 'marketing', 'media'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Проверенная временем модель для одежды и обуви: понимает фото вещи и её описание в одном пространстве, поэтому годится для похожих товаров и подбора по образу. Под свой ассортимент лучше дообучить.',
    tasks: ['Похожие вещи по фотографии', 'Подбор образа и сопутствующих позиций', 'Автоматическая разметка карточек одежды', 'Поиск по каталогу словами покупателя'],
    where: ['Магазины одежды и обуви', 'Маркетплейсы моды', 'Фото- и контент-продакшн'],
    versions: [['FashionCLIP', '2023-02'], ['FashionCLIP 2.0 (на базе Laion CLIP ViT-B/32)', '2023-03']],
    hf: 'https://huggingface.co/patrickjohncyh/fashion-clip',
    github: 'https://github.com/patrickjohncyh/fashion-clip',
    alternatives: ['marqo-ecommerce', 'blair', 'clip-siglip'],
    source: 'https://huggingface.co/patrickjohncyh/fashion-clip',
    verified: true,
    en: {
      summary: 'A time-tested model for clothing and footwear: it places an item photo and its description in one space, so it fits similar-item blocks and outfit matching. Fine-tuning for your own assortment is advisable.',
      tasks: ['Similar items by photograph', 'Building an outfit and matching add-ons', 'Automatic tagging of clothing cards', 'Catalogue search in the shopper own words'],
      where: ['Clothing and footwear stores', 'Fashion marketplaces', 'Photo and content production'],
      license: 'MIT',
      developer: 'FashionCLIP research project (Farfetch data)',
      country: 'not disclosed',
      sizes: 'built on CLIP ViT-B/32',
    },
  },
];
