// Волна 4: языковые модели второго эшелона (малые, региональные, код, диффузионные) и аудио-LLM. Факты сверены по Hugging Face / GitHub / Ollama на 22.09.2026.
module.exports = [
  {
    id: 'minicpm',
    name: 'MiniCPM',
    developer: 'OpenBMB (ModelBest и Университет Цинхуа)', country: 'Китай',
    modality: ['text'],
    first: '2024-02', latest: '2026-09',
    sizes: '0.5B – 8B',
    license: 'Apache 2.0 (у первых MiniCPM-2B и MiniCPM 2.0 была собственная лицензия MiniCPM с регистрацией для коммерции)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['support', 'docs', 'dev'],
    ollama: false,
    cpu: true,
    summary: 'Компактные текстовые модели для работы прямо на устройстве: ноутбуке, телефоне, мини-ПК. MiniCPM5 на 1B и 2B ориентированы на вызов инструментов и длинный контекст.',
    tasks: ['Локальный чат-ассистент без облака', 'Извлечение данных и классификация текстов', 'Вызов инструментов и простые агенты на слабом железе'],
    where: ['Поддержка клиентов', 'Документооборот', 'Встраиваемые устройства'],
    versions: [
      ['MiniCPM-2B', '2024-02'],
      ['MiniCPM 2.0 (1B, MoE 8x2B)', '2024-04'],
      ['MiniCPM3-4B', '2024-09'],
      ['MiniCPM4 (0.5B, 8B)', '2025-06'],
      ['MiniCPM4.1-8B', '2025-09'],
      ['MiniCPM5-1B', '2026-05'],
      ['MiniCPM5-2B', '2026-09'],
    ],
    hf: 'https://huggingface.co/openbmb/MiniCPM5-2B',
    github: 'https://github.com/OpenBMB/MiniCPM',
    alternatives: ['smollm', 'lfm', 'qwen'],
    source: 'https://huggingface.co/openbmb/MiniCPM5-2B',
    verified: true,
  },
  {
    id: 'k2',
    name: 'K2 (K2-Think, K2-V2, K2-Horizon)',
    developer: 'MBZUAI, Институт фундаментальных моделей (IFM, проект LLM360)', country: 'ОАЭ',
    modality: ['text', 'reasoning'],
    first: '2024-05', latest: '2026-09',
    sizes: '0.9B – 375B-A23B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'education', 'dev'],
    ollama: false,
    cpu: true,
    summary: 'Полностью открытые модели из ОАЭ: вместе с весами опубликованы данные, код обучения и промежуточные чекпоинты. K2-Horizon 2026 года — линейка от 0.9B до 375B с контекстом до 512 тыс. токенов.',
    tasks: ['Рассуждения, математика и технические вопросы', 'Разбор длинных документов', 'Агенты и написание кода', 'Проверяемое обучение своих моделей на открытых данных'],
    where: ['Исследовательские группы', 'IT-отделы', 'Образование'],
    versions: [
      ['K2-65B', '2024-05'],
      ['K2-Think 32B', '2025-09'],
      ['K2-V2 70B', '2025-12'],
      ['K2-Think-V2', '2026-01'],
      ['K2-Horizon (0.9B, 3.7B, 7B, 32B, MoVA 36B-A4B, 375B-A23B)', '2026-09'],
    ],
    hf: 'https://huggingface.co/IFM/K2-Horizon-7B',
    github: 'https://github.com/LLM360',
    alternatives: ['olmo', 'jais', 'falcon'],
    source: 'https://huggingface.co/IFM/K2-Horizon-375B-A23B',
    verified: true,
  },
  {
    id: 'jais',
    name: 'Jais',
    developer: 'Inception (G42), MBZUAI и Cerebras', country: 'ОАЭ',
    modality: ['text'],
    first: '2023-08', latest: '2025-12',
    sizes: '256M – 70B',
    license: 'Apache 2.0 (Jais 2 — по запросу доступа на Hugging Face)',
    commercial: 'yes',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'no',
    industries: ['support', 'gov', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Семейство моделей для арабского и английского языков, включая диалекты Персидского залива. Подходит компаниям, работающим с арабоязычными клиентами и госструктурами региона.',
    tasks: ['Чат-бот на арабском и английском', 'Перевод и пересказ документов на арабском', 'Классификация обращений клиентов'],
    where: ['Поддержка клиентов на Ближнем Востоке', 'Госсектор ОАЭ и Залива', 'Документооборот'],
    versions: [
      ['Jais-13B', '2023-08'],
      ['Jais-30B', '2023-11'],
      ['Jais-30B v3', '2024-02'],
      ['Jais Family (590M – 30B) и Jais Adapted (7B – 70B)', '2024-08'],
      ['Jais 2 (8B, 70B)', '2025-12'],
    ],
    hf: 'https://huggingface.co/inception42/Jais-2-70B-Chat',
    github: null,
    alternatives: ['allam', 'k2', 'falcon'],
    source: 'https://huggingface.co/inception42/Jais-2-8B-Chat',
    verified: true,
  },
  {
    id: 'allam',
    name: 'ALLaM',
    developer: 'HUMAIN (ранее SDAIA)', country: 'Саудовская Аравия',
    modality: ['text'],
    first: '2025-02', latest: '2025-02',
    sizes: '7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['gov', 'support', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Саудовская модель для арабского и английского языков, обученная с нуля. В открытом доступе одна версия на 7B.',
    tasks: ['Ассистент на арабском языке', 'Ответы на вопросы по документам', 'Генерация и редактирование текстов на арабском'],
    where: ['Госсектор Саудовской Аравии', 'Образование', 'Поддержка клиентов'],
    versions: [['ALLaM-7B-Instruct-preview', '2025-02']],
    hf: 'https://huggingface.co/humain-ai/ALLaM-7B-Instruct-preview',
    github: null,
    alternatives: ['jais', 'k2'],
    source: 'https://huggingface.co/humain-ai/ALLaM-7B-Instruct-preview',
    verified: true,
  },
  {
    id: 'ornith',
    name: 'Ornith',
    developer: 'DeepReinforce', country: 'не раскрыта',
    modality: ['code', 'agent'],
    first: '2026-06', latest: '2026-08',
    sizes: '9B – 397B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['dev'],
    ollama: true,
    cpu: false,
    summary: 'Модели для агентной разработки: сами строят план и обвязку под задачу и выполняют её в терминале. Дообучены на базе Qwen 3.5 и Gemma 4, работают с Claude Code, OpenHands и похожими инструментами.',
    tasks: ['Агент-разработчик в терминале', 'Исправление ошибок по описанию задачи', 'Разбор и доработка большого репозитория'],
    where: ['Команды разработки', 'IT-аутсорс', 'Внутренняя автоматизация'],
    versions: [
      ['Ornith-1.0 (9B, 35B, 397B)', '2026-06'],
      ['Ornith-1.5 (9B, 35B-A3B, 397B)', '2026-08'],
    ],
    hf: 'https://huggingface.co/ornith-ai/Ornith-1.5-35B-A3B',
    github: 'https://github.com/ornith-ai/Ornith-1',
    alternatives: ['qwen-coder', 'devstral', 'kat-coder'],
    source: 'https://huggingface.co/ornith-ai/Ornith-1.5-9B',
    verified: true,
  },
  {
    id: 'apriel',
    name: 'Apriel',
    developer: 'ServiceNow', country: 'США',
    modality: ['text', 'reasoning', 'vlm'],
    first: '2025-04', latest: '2026-04',
    sizes: '5B – 15B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['support', 'dev', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Модели ServiceNow на 15B с пошаговыми рассуждениями, которые помещаются на одну видеокарту. С версии 1.5 понимают и картинки, хорошо вызывают инструменты.',
    tasks: ['Ассистент с рассуждениями для внутренних сервисов', 'Вызов инструментов и корпоративные агенты', 'Разбор скриншотов и документов с картинками'],
    where: ['IT-службы и сервис-деск', 'Поддержка клиентов', 'Разработка'],
    versions: [
      ['Apriel-5B', '2025-04'],
      ['Apriel-Nemotron-15B-Thinker', '2025-05'],
      ['Apriel-1.5-15B-Thinker', '2025-09'],
      ['Apriel-1.6-15B-Thinker', '2025-11'],
      ['SuperApriel-15B', '2026-04'],
    ],
    hf: 'https://huggingface.co/ServiceNow-AI/Apriel-1.6-15b-Thinker',
    github: 'https://github.com/ServiceNow/Apriel',
    alternatives: ['phi', 'nemotron', 'granite'],
    source: 'https://huggingface.co/ServiceNow-AI/SuperApriel-15B-Instruct',
    verified: true,
  },
  {
    id: 'cogito',
    name: 'Cogito',
    developer: 'Deep Cogito', country: 'США',
    modality: ['text', 'reasoning'],
    first: '2025-04', latest: '2025-11',
    sizes: '3B – 671B',
    license: 'v1 и Llama-версии v2 — лицензии Llama; версии на Qwen и DeepSeek — Apache 2.0 / MIT',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'unknown',
    industries: ['support', 'dev', 'docs'],
    ollama: true,
    cpu: true,
    summary: 'Дообученные Llama, Qwen и DeepSeek с гибридным режимом: модель отвечает сразу или сначала рассуждает. Флагман v2.1 на 671B тратит на рассуждения заметно меньше токенов, чем DeepSeek R1.',
    tasks: ['Чат-ассистент с режимом рассуждений', 'Написание кода и вызов инструментов', 'Ответы на сложные вопросы по документам'],
    where: ['Поддержка клиентов', 'Разработка', 'Аналитика'],
    versions: [
      ['Cogito v1 Preview (3B – 70B)', '2025-04'],
      ['Cogito v2 Preview (70B – 671B)', '2025-07'],
      ['Cogito v2.1 671B', '2025-11'],
    ],
    hf: 'https://huggingface.co/deepcogito/cogito-671b-v2.1',
    github: null,
    alternatives: ['deepseek-r1', 'llama', 'qwen'],
    source: 'https://www.deepcogito.com/research/cogito-v2-1',
    verified: true,
  },
  {
    id: 'deepscaler',
    name: 'DeepScaleR, DeepCoder, DeepSWE',
    developer: 'Agentica (Беркли, Sky Computing Lab) и Together AI', country: 'США',
    modality: ['reasoning', 'code'],
    first: '2025-02', latest: '2025-07',
    sizes: '1.5B – 32B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['education', 'dev', 'science'],
    ollama: true,
    cpu: true,
    summary: 'Небольшие модели, дообученные обучением с подкреплением: DeepScaleR на 1.5B решает олимпиадную математику, DeepCoder пишет код, DeepSWE работает агентом-разработчиком. Рецепты и данные открыты.',
    tasks: ['Решение математических задач с пошаговым выводом', 'Генерация и проверка кода', 'Агент для исправления ошибок в репозитории'],
    where: ['Образование', 'Разработка', 'Исследования'],
    versions: [
      ['DeepScaleR-1.5B-Preview', '2025-02'],
      ['DeepCoder-14B и 1.5B', '2025-04'],
      ['DeepSWE-Preview 32B', '2025-07'],
    ],
    hf: 'https://huggingface.co/agentica-org/DeepScaleR-1.5B-Preview',
    github: 'https://github.com/agentica-project/rllm',
    alternatives: ['deepseek-r1', 'openthinker', 'sky-t1'],
    source: 'https://huggingface.co/agentica-org/DeepSWE-Preview',
    verified: true,
  },
  {
    id: 'tinyllama',
    name: 'TinyLlama',
    developer: 'TinyLlama (исследователи SUTD)', country: 'Сингапур',
    modality: ['text'],
    first: '2023-09', latest: '2024-03',
    sizes: '1.1B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['education', 'science', 'dev'],
    ollama: true,
    cpu: true,
    summary: 'Модель на 1.1B с архитектурой Llama 2, обученная на 3 трлн токенов. Сегодня уступает новым малым моделям, но остаётся популярной основой для экспериментов и дообучения.',
    tasks: ['Простые чат-боты на слабом железе', 'Эксперименты и обучение команды', 'Основа для дообучения под узкую задачу'],
    where: ['Образование', 'Исследования', 'Прототипы'],
    versions: [
      ['TinyLlama-1.1B (промежуточные чекпоинты)', '2023-09'],
      ['TinyLlama-1.1B-Chat v1.0', '2023-12'],
      ['TinyLlama v1.1 (общая, код и математика, китайская)', '2024-03'],
    ],
    hf: 'https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0',
    github: 'https://github.com/jzhang38/TinyLlama',
    alternatives: ['smollm', 'phi', 'pythia'],
    source: 'https://huggingface.co/TinyLlama/TinyLlama_v1.1',
    verified: true,
  },
  {
    id: 'orca',
    name: 'Orca 2',
    developer: 'Microsoft Research', country: 'США',
    modality: ['text', 'reasoning'],
    first: '2023-11', latest: '2023-11',
    sizes: '7B – 13B',
    license: 'Microsoft Research License: только исследования, без коммерции',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['science', 'education'],
    ollama: true,
    cpu: false,
    summary: 'Исследовательские модели Microsoft на базе Llama 2, которых учили выбирать способ рассуждения под задачу. Модель orca-mini в Ollama — другой проект, её выпускал независимый разработчик Панкадж Матхур.',
    tasks: ['Исследования методов рассуждения', 'Сравнение с современными малыми моделями', 'Обучение специалистов'],
    where: ['Исследовательские группы', 'Вузы'],
    versions: [['Orca 2 (7B, 13B)', '2023-11']],
    hf: 'https://huggingface.co/microsoft/Orca-2-13b',
    github: null,
    alternatives: ['phi', 'llama', 'wizardlm'],
    source: 'https://huggingface.co/microsoft/Orca-2-13b',
    verified: true,
  },
  {
    id: 'stablelm',
    name: 'StableLM и Stable Code',
    developer: 'Stability AI', country: 'Великобритания',
    modality: ['text', 'code'],
    first: '2023-04', latest: '2024-08',
    sizes: '1.6B – 12B',
    license: 'Ранние Alpha и StableLM-3B-4E1T — CC BY-SA 4.0; StableLM 2 1.6B, Zephyr и Stable Code — Stability AI Community License (бесплатно при выручке до 1 млн $ в год); StableLM 2 12B — некоммерческая',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['support', 'dev', 'education'],
    ollama: true,
    cpu: true,
    summary: 'Малые модели Stability AI: StableLM 2 на 1.6B знает 7 европейских языков, Stable Code на 3B дописывает код. Обновлений с 2024 года нет.',
    tasks: ['Лёгкий чат-бот на обычном ПК', 'Автодополнение кода в редакторе', 'Основа для дообучения под свою задачу'],
    where: ['Разработка', 'Поддержка клиентов', 'Образование'],
    versions: [
      ['StableLM Alpha (3B, 7B)', '2023-04'],
      ['StableLM-3B-4E1T', '2023-09'],
      ['StableLM Zephyr 3B', '2023-11'],
      ['StableLM 2 1.6B и Stable Code 3B', '2024-01'],
      ['Stable Code Instruct 3B', '2024-03'],
      ['StableLM 2 12B', '2024-04'],
      ['Arabic StableLM 2', '2024-08'],
    ],
    hf: 'https://huggingface.co/stabilityai/stablelm-2-1_6b',
    github: 'https://github.com/Stability-AI/StableLM',
    alternatives: ['smollm', 'phi', 'starcoder'],
    source: 'https://huggingface.co/stabilityai/stablelm-2-12b-chat',
    verified: true,
  },
  {
    id: 'yi-coder',
    name: 'Yi-Coder',
    developer: '01.AI', country: 'Китай',
    modality: ['code'],
    first: '2024-09', latest: '2024-09',
    sizes: '1.5B – 9B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['dev'],
    ollama: true,
    cpu: true,
    summary: 'Модели для кода от 01.AI на 1.5B и 9B с контекстом 128 тыс. токенов и поддержкой 52 языков программирования. Отдельная линейка рядом с текстовыми Yi.',
    tasks: ['Автодополнение и генерация кода', 'Объяснение и рефакторинг кода', 'Ассистент программиста без облака'],
    where: ['Разработка', 'IT-отделы'],
    versions: [['Yi-Coder 1.5B и 9B (Base, Chat)', '2024-09']],
    hf: 'https://huggingface.co/01-ai/Yi-Coder-9B-Chat',
    github: 'https://github.com/01-ai/Yi-Coder',
    alternatives: ['yi', 'qwen-coder', 'deepseek-coder'],
    source: 'https://huggingface.co/01-ai/Yi-Coder-9B-Chat',
    verified: true,
  },
  {
    id: 'codegeex',
    name: 'CodeGeeX',
    developer: 'Zhipu AI (Z.ai) и Университет Цинхуа', country: 'Китай',
    modality: ['code'],
    first: '2023-07', latest: '2024-07',
    sizes: '6B – 9B',
    license: 'Собственная лицензия CodeGeeX: исследования свободно, для коммерции нужна регистрация',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['dev'],
    ollama: true,
    cpu: false,
    summary: 'Модели для кода от создателей GLM. CodeGeeX4-ALL-9B на базе GLM-4-9B в одной модели совмещает автодополнение, чат по коду, вызов функций и поиск по репозиторию.',
    tasks: ['Автодополнение кода в IDE', 'Чат-помощник по коду', 'Ответы на вопросы по репозиторию'],
    where: ['Разработка', 'IT-отделы'],
    versions: [
      ['CodeGeeX2-6B', '2023-07'],
      ['CodeGeeX4-ALL-9B', '2024-07'],
    ],
    hf: 'https://huggingface.co/zai-org/codegeex4-all-9b',
    github: 'https://github.com/zai-org/CodeGeeX4',
    alternatives: ['glm', 'qwen-coder', 'deepseek-coder'],
    source: 'https://huggingface.co/zai-org/codegeex4-all-9b',
    verified: true,
  },
  {
    id: 'opencoder',
    name: 'OpenCoder',
    developer: 'INF Technology', country: 'Китай',
    modality: ['code'],
    first: '2024-11', latest: '2024-11',
    sizes: '1.5B – 8B',
    license: 'Собственная лицензия INF: коммерческое использование разрешено',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['dev', 'education'],
    ollama: true,
    cpu: true,
    summary: 'Полностью воспроизводимые модели для кода: вместе с весами открыты данные, конвейер их очистки и рецепт обучения. Понимают английский и китайский.',
    tasks: ['Генерация и дополнение кода', 'Обучение своей модели для кода по открытому рецепту', 'Ассистент программиста на слабом железе'],
    where: ['Разработка', 'Образование'],
    versions: [['OpenCoder 1.5B и 8B (Base, Instruct)', '2024-11']],
    hf: 'https://huggingface.co/infly/OpenCoder-8B-Instruct',
    github: 'https://github.com/OpenCoder-llm/OpenCoder-llm',
    alternatives: ['starcoder', 'qwen-coder', 'yi-coder'],
    source: 'https://huggingface.co/infly/OpenCoder-8B-Instruct',
    verified: true,
  },
  {
    id: 'athene',
    name: 'Athene',
    developer: 'Nexusflow', country: 'США',
    modality: ['text', 'agent'],
    first: '2024-07', latest: '2024-11',
    sizes: '70B – 72B',
    license: 'Nexusflow Research License: без коммерции и без размещения как сервиса',
    commercial: 'no',
    hardware: ['gpu', 'multi'],
    ru: 'no',
    industries: ['science', 'dev'],
    ollama: true,
    cpu: false,
    summary: 'Дообученные Llama 3 и Qwen 2.5 от Nexusflow. Athene-V2-Agent специально натренирован на вызов функций и агентные сценарии. Коммерческое использование запрещено.',
    tasks: ['Исследование агентов и вызова функций', 'Сравнение с коммерческими моделями', 'Эксперименты с чат-ассистентом'],
    where: ['Исследовательские группы', 'Разработка прототипов'],
    versions: [
      ['Athene-70B', '2024-07'],
      ['Athene-V2-Chat и Athene-V2-Agent 72B', '2024-11'],
    ],
    hf: 'https://huggingface.co/Nexusflow/Athene-V2-Chat',
    github: null,
    alternatives: ['qwen', 'llama', 'hermes'],
    source: 'https://huggingface.co/Nexusflow/Athene-V2-Agent',
    verified: true,
  },
  {
    id: 'rnj',
    name: 'Rnj-1',
    developer: 'Essential AI', country: 'США',
    modality: ['code', 'reasoning'],
    first: '2025-12', latest: '2026-04',
    sizes: '8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['dev', 'science'],
    ollama: true,
    cpu: false,
    summary: 'Модель на 8B, обученная с нуля компанией одного из авторов архитектуры трансформер. Сильна в коде и технических задачах, версия 1.5 держит контекст до 160 тыс. токенов.',
    tasks: ['Генерация и исправление кода', 'Агент-разработчик на одной видеокарте', 'Решение технических и научных задач'],
    where: ['Разработка', 'Инженерные отделы', 'Исследования'],
    versions: [
      ['rnj-1 и rnj-1-instruct', '2025-12'],
      ['rnj-1.5-instruct', '2026-04'],
    ],
    hf: 'https://huggingface.co/EssentialAI/rnj-1-instruct',
    github: null,
    alternatives: ['qwen-coder', 'seed-coder', 'olmo'],
    source: 'https://huggingface.co/EssentialAI/rnj-1.5-instruct',
    verified: true,
  },
  {
    id: 'neural-chat',
    name: 'NeuralChat',
    developer: 'Intel', country: 'США',
    modality: ['text'],
    first: '2023-11', latest: '2023-12',
    sizes: '7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['support', 'education'],
    ollama: true,
    cpu: false,
    summary: 'Дообученная Mistral 7B от Intel, показывавшая обучение и запуск на процессорах и ускорителях Intel. Устарела, интересна как пример оптимизации под железо Intel.',
    tasks: ['Простой чат-ассистент', 'Эксперименты с запуском на железе Intel', 'Основа для дообучения'],
    where: ['Поддержка клиентов', 'Образование'],
    versions: [
      ['neural-chat-7b-v3-1', '2023-11'],
      ['neural-chat-7b-v3-3', '2023-12'],
    ],
    hf: 'https://huggingface.co/Intel/neural-chat-7b-v3-3',
    github: 'https://github.com/intel/intel-extension-for-transformers',
    alternatives: ['mistral', 'zephyr', 'openchat'],
    source: 'https://huggingface.co/Intel/neural-chat-7b-v3-3',
    verified: true,
  },
  {
    id: 'llada',
    name: 'LLaDA',
    developer: 'Жэньминьский университет (GSAI) и Ant Group (inclusionAI)', country: 'Китай',
    modality: ['text', 'agent'],
    first: '2025-02', latest: '2026-09',
    sizes: '8B – 100B (MoE)',
    license: 'LLaDA 8B и 1.5 — MIT; LLaDA-MoE и LLaDA2.x — Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'unknown',
    industries: ['dev', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Диффузионные языковые модели: текст пишется не по одному слову, а сразу блоками с последующим уточнением, что ускоряет генерацию. LLaDA2.2 умеет править уже написанное и рассчитана на агентов. Генератор картинок LLaDA-Image — отдельный продукт.',
    tasks: ['Быстрая генерация кода и текстов', 'Агентные сценарии с длинным контекстом', 'Исследования альтернатив обычным LLM'],
    where: ['Разработка', 'Исследовательские группы'],
    versions: [
      ['LLaDA 8B', '2025-02'],
      ['LLaDA 1.5', '2025-05'],
      ['LLaDA-MoE 7B-A1B', '2025-09'],
      ['LLaDA2.0 mini (16B) и flash (100B)', '2025-11'],
      ['LLaDA2.1 mini и flash', '2026-02'],
      ['LLaDA2.2-flash', '2026-07'],
      ['LLaDA2.2-mini', '2026-09'],
    ],
    hf: 'https://huggingface.co/inclusionAI/LLaDA2.2-flash',
    github: 'https://github.com/inclusionAI/LLaDA2.X',
    alternatives: ['ling', 'qwen', 'seed-oss'],
    source: 'https://huggingface.co/inclusionAI/LLaDA2.2-mini',
    verified: true,
  },
  {
    id: 'kimi-audio',
    name: 'Kimi-Audio',
    developer: 'Moonshot AI', country: 'Китай',
    modality: ['omni', 'asr'],
    first: '2025-04', latest: '2025-04',
    sizes: '7B',
    license: 'MIT (часть кода на основе Qwen 2.5 — Apache 2.0)',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['support', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Универсальная аудиомодель: распознаёт речь, отвечает на вопросы о звуке, определяет эмоции и ведёт голосовой диалог. Обучена на 13 млн часов аудио, языки — английский и китайский.',
    tasks: ['Распознавание речи', 'Определение эмоций и звуковых событий', 'Голосовой диалог речь-в-речь'],
    where: ['Колл-центры', 'Медиа', 'Голосовые боты'],
    versions: [['Kimi-Audio-7B и 7B-Instruct', '2025-04']],
    hf: 'https://huggingface.co/moonshotai/Kimi-Audio-7B-Instruct',
    github: 'https://github.com/MoonshotAI/Kimi-Audio',
    alternatives: ['qwen-omni', 'minicpm-o', 'audio-flamingo'],
    source: 'https://huggingface.co/moonshotai/Kimi-Audio-7B-Instruct',
    verified: true,
  },
  {
    id: 'audio-flamingo',
    name: 'Audio Flamingo',
    developer: 'NVIDIA', country: 'США',
    modality: ['omni'],
    first: '2024-07', latest: '2026-04',
    sizes: '0.5B – 8B',
    license: 'Некоммерческие лицензии NVIDIA (OneWay Noncommercial), только исследования',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['media', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Модели, которые слушают речь, звуки и музыку и отвечают на вопросы о них. Audio Flamingo Next разбирает записи до 30 минут. Только для исследований.',
    tasks: ['Подробное описание аудиозаписей', 'Вопросы и ответы по длинной записи', 'Разметка музыки и звуков'],
    where: ['Медиа и продакшн', 'Исследования'],
    versions: [
      ['Audio Flamingo', '2024-07'],
      ['Audio Flamingo 2 (0.5B – 3B)', '2025-02'],
      ['Audio Flamingo 3', '2025-07'],
      ['Music Flamingo', '2025-11'],
      ['Audio Flamingo Next', '2026-04'],
    ],
    hf: 'https://huggingface.co/nvidia/audio-flamingo-next-hf',
    github: 'https://github.com/NVIDIA/audio-flamingo',
    alternatives: ['qwen-omni', 'kimi-audio', 'voxtral'],
    source: 'https://huggingface.co/nvidia/audio-flamingo-next-hf',
    verified: true,
  },
  {
    id: 'personaplex',
    name: 'PersonaPlex',
    developer: 'NVIDIA', country: 'США',
    modality: ['omni'],
    first: '2026-01', latest: '2026-01',
    sizes: '7B',
    license: 'Веса — NVIDIA Open Model License, код — MIT',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['support', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Голосовой собеседник на основе Moshi, который слушает и говорит одновременно, позволяет себя перебивать. Роль задаётся текстом, голос — образцом записи. Только английский.',
    tasks: ['Голосовой ассистент с заданной ролью', 'Тренажёр разговоров для обучения персонала', 'Голосовые интерфейсы без задержки'],
    where: ['Колл-центры', 'Обучение персонала', 'Голосовые боты'],
    versions: [['PersonaPlex-7B-v1', '2026-01']],
    hf: 'https://huggingface.co/nvidia/personaplex-7b-v1',
    github: 'https://github.com/NVIDIA/personaplex',
    alternatives: ['moshi', 'qwen-omni', 'minicpm-o'],
    source: 'https://research.nvidia.com/labs/adlr/personaplex',
    verified: true,
  },
];
