// Liquid d1, FleXray, Interfaze 1 Lite, AREX-2, Cactus Whistle. Факты сверены по Hugging Face и сайтам разработчиков на 09.10.2026.
module.exports = [
  {
    id: 'liquid-d1',
    name: 'Liquid d1',
    developer: 'Liquid AI', country: 'США',
    modality: ['nlp', 'vlm', 'omni'],
    first: '2026-10', latest: '2026-10',
    sizes: '600M и 3B',
    license: 'LFM Open License v1.0: бесплатно для компаний с выручкой до 10 млн долларов в год, выше нужна отдельная лицензия',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['support', 'retail', 'security', 'manufacturing'],
    ollama: false,
    cpu: true,
    summary: 'Маленькие модели решений: по тексту, картинке или голосовой записи отвечают «да или нет», выбирают вариант или ставят оценку за один проход, текст не пишут. d1-3B видит картинки, d1-omni-600M ещё и слышит речь до 30 секунд. Русский заявлен.',
    tasks: ['сортировка обращений и заявок по отделам', 'проверка фото на браке или нарушении по списку вопросов', 'маршрутизация голосовых команд', 'оценка ответов ИИ и защита агента от лишних действий'],
    where: ['поддержка клиентов', 'интернет-магазины', 'производство и контроль качества', 'встроенные ИИ-агенты на устройствах'],
    versions: [['d1-omni-600M (текст, картинки, речь)', '2026-10'], ['d1-3B (текст и картинки)', '2026-10']],
    hf: 'https://huggingface.co/LiquidAI/d1-3B',
    github: null,
    alternatives: ['clef', 'jev-gev', 'lfm'],
    source: 'https://huggingface.co/LiquidAI/d1-3B',
    verified: true,
    en: {
      summary: "Small decision models: from text, an image or a voice clip they answer yes or no, pick an option or give a rating in one pass, without writing text. d1-3B sees images, d1-omni-600M also hears speech up to 30 seconds. Russian is listed.",
      tasks: ['routing requests and tickets to teams', 'checking a photo for defects or violations against a list of questions', 'routing voice commands', 'scoring AI answers and guarding an agent against unwanted actions'],
      where: ['customer support', 'online stores', 'manufacturing and quality control', 'AI agents built into devices'],
      license: 'LFM Open License v1.0: free for companies with annual revenue under 10 million dollars, above that a separate license is needed',
      sizes: '600M and 3B',
      country: 'USA',
    },
  },
  {
    id: 'flexray',
    name: 'FleXray',
    developer: 'MIT CSAIL, Массачусетская больница общего профиля и Гарвардская медицинская школа', country: 'США',
    modality: ['medical', 'vision'],
    first: '2026-06', latest: '2026-10',
    sizes: 'небольшая сеть U-Net, снимки 256 на 256 пикселей',
    license: 'CC BY-NC 4.0 (только некоммерческое использование); исследовательский выпуск, не клинический продукт',
    commercial: 'no',
    hardware: ['min'],
    ru: 'na',
    industries: ['medical', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Находит на рентгеновском снимке 60 анатомических структур: рёбра, позвонки, кости таза и конечностей. По ним можно автоматически мерить, например, угол искривления позвоночника. Патологии не ищет, правую сторону от левой не отличает.',
    tasks: ['разметка анатомии на рентгеновских снимках', 'измерение угла искривления позвоночника', 'сопоставление кадров рентгеноскопии с КТ при навигации', 'подготовка данных для исследований'],
    where: ['исследовательские группы и вузы', 'разработчики медицинского ПО (для прототипов)', 'обучение рентгенологов'],
    versions: [['FleXray (одна сеть и ансамбль из пяти)', '2026-06']],
    hf: 'https://huggingface.co/VictorButoi/flexray',
    github: 'https://github.com/VictorButoi/FleXray',
    alternatives: ['sam', 'medgemma'],
    source: 'https://huggingface.co/VictorButoi/flexray',
    verified: true,
    en: {
      summary: "Finds 60 anatomical structures on an X-ray: ribs, vertebrae, pelvis and limb bones. They can be used to measure, for example, the curvature angle of the spine automatically. It does not look for pathologies and does not tell right from left.",
      tasks: ['labeling anatomy on X-ray images', 'measuring the spine curvature angle', 'matching fluoroscopy frames with CT for navigation', 'preparing data for research'],
      where: ['research groups and universities', 'medical software developers (for prototypes)', 'training radiologists'],
      developer: 'MIT CSAIL, Massachusetts General Hospital and Harvard Medical School',
      license: 'CC BY-NC 4.0 (non-commercial use only); a research release, not a clinical product',
      sizes: 'a small U-Net, 256 by 256 pixel images',
      country: 'USA',
    },
  },
  {
    id: 'interfaze',
    name: 'Interfaze 1 Lite',
    developer: 'Interfaze', country: 'не указана',
    modality: ['vlm', 'ocr', 'asr'],
    first: '2026-10', latest: '2026-10',
    sizes: 'модель на 80 ГБ видеопамяти (ядро на базе Qwen3.8-27B)',
    license: 'Apache 2.0 для самой модели; внутри компоненты с чужими лицензиями, в том числе Llama 3.2 Community и модифицированная OpenRAIL-M, их условия нужно проверить',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['docs', 'finance', 'support', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Одна модель для разработчиков: читает документы и таблицы, расшифровывает речь с разметкой спикеров, находит объекты на картинке и отвечает строго по заданной JSON-схеме. Внутри ядро для рассуждений и набор узких моделей.',
    tasks: ['разбор документов и таблиц с координатами текста', 'расшифровка записей с разметкой спикеров', 'извлечение данных из документов в заданную JSON-схему', 'поиск элементов интерфейса для агентов, работающих с компьютером'],
    where: ['документооборот и бухгалтерия', 'финансы', 'колл-центры', 'разработка ИИ-агентов'],
    versions: [['Interfaze 1 Lite', '2026-10']],
    hf: 'https://huggingface.co/interfaze-ai/interfaze-1-lite',
    github: null,
    alternatives: ['qwen', 'docling', 'granite-speech'],
    source: 'https://huggingface.co/interfaze-ai/interfaze-1-lite',
    verified: true,
    en: {
      summary: "One model for developers: reads documents and tables, transcribes speech with speaker labels, finds objects in an image and answers strictly by a JSON schema you supply. Inside is a reasoning core and a set of narrow specialist models.",
      tasks: ['parsing documents and tables with text coordinates', 'transcribing recordings with speaker labels', 'extracting data from documents into a given JSON schema', 'finding interface elements for computer-use agents'],
      where: ['document management and accounting', 'finance', 'call centers', 'AI agent development'],
      license: 'Apache 2.0 for the model itself; it includes components with third-party licenses, among them Llama 3.2 Community and a modified OpenRAIL-M, whose terms must be checked',
      sizes: 'a model that needs 80 GB of video memory (the core is based on Qwen3.8-27B)',
      country: 'not stated',
    },
  },
  {
    id: 'arex',
    name: 'AREX-2',
    developer: 'Пекинская академия искусственного интеллекта (BAAI)', country: 'Китай',
    modality: ['agent', 'reasoning', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '27B',
    license: 'Apache 2.0; следует учитывать условия базовой модели Qwen',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['science', 'dev', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Агентная модель на 27B (на базе Qwen3.8-27B) для долгих задач: предлагает решение, замеряет результат, разбирает ошибки и пересматривает решение в несколько заходов. Контекст 262 тысячи токенов. Заявлена как исследовательская.',
    tasks: ['итеративная доработка кода и алгоритмов', 'задачи машинного обучения с проверяемым результатом', 'глубокий поиск и сбор информации по теме'],
    where: ['разработка ПО и ИТ', 'исследовательские группы', 'R&D-отделы'],
    versions: [['AREX-Turbo 4B', '2026-09'], ['AREX-2 27B', '2026-09']],
    hf: 'https://huggingface.co/BAAI/AREX-2',
    github: 'https://github.com/VectorSpaceLab/AREX-2',
    alternatives: ['qwen', 'kimi', 'deepseek'],
    source: 'https://huggingface.co/BAAI/AREX-2',
    verified: true,
    en: {
      summary: "An agent model of 27B (based on Qwen3.8-27B) for long tasks: it proposes a solution, measures the result, analyzes errors and revises the solution over several rounds. A 262K-token context. Stated as a research model.",
      tasks: ['iterative improvement of code and algorithms', 'machine learning tasks with a verifiable result', 'deep search and gathering information on a topic'],
      where: ['software development and IT', 'research groups', 'R&D departments'],
      license: 'Apache 2.0; the terms of the Qwen base model must also be followed',
      developer: 'Beijing Academy of Artificial Intelligence (BAAI)',
      country: 'China',
    },
  },
  {
    id: 'cactus-whistle',
    name: 'Cactus Whistle',
    developer: 'Cactus Compute', country: 'не указана',
    modality: ['asr'],
    first: '2026-09', latest: '2026-09',
    sizes: '16,9 МБ',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['support', 'manufacturing', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Распознавание речи в одном файле на 16,9 МБ: работает на телефоне, часах, роботе и процессоре без видеокарты. Языки: английский, немецкий, французский, испанский, итальянский, нидерландский, польский. Даёт метки времени для слов.',
    tasks: ['голосовой ввод в мобильных приложениях без интернета', 'управление устройством голосом', 'подсветка слов в субтитрах по меткам времени'],
    where: ['мобильные приложения', 'умный дом и носимые устройства', 'автомобильные системы'],
    versions: [['Whistle', '2026-09']],
    hf: 'https://huggingface.co/Cactus-Compute/whistle',
    github: null,
    alternatives: ['moonshine', 'whisper', 'parakeet'],
    source: 'https://huggingface.co/Cactus-Compute/whistle',
    verified: true,
    en: {
      summary: "Speech recognition in a single 16.9 MB file: runs on a phone, watch, robot and CPU without a graphics card. Languages: English, German, French, Spanish, Italian, Dutch, Polish. Gives word timestamps.",
      tasks: ['voice input in mobile apps without internet', 'controlling a device by voice', 'highlighting words in subtitles by timestamps'],
      where: ['mobile apps', 'smart home and wearables', 'automotive systems'],
      sizes: '16.9 MB',
      country: 'not stated',
    },
  },
];
