// Clef и Clef-flash (Cloudflare). Факты сверены по Hugging Face и библиотеке Ollama на 04.10.2026.
module.exports = [
  {
    id: 'clef',
    name: 'Clef',
    developer: 'Cloudflare', country: 'США',
    modality: ['nlp', 'vlm', 'agent'],
    first: '2026-10', latest: '2026-10',
    sizes: '27B и 9B (Clef-flash)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['support', 'docs', 'security', 'dev'],
    ollama: true,
    cpu: false,
    summary: 'Модели решений: не пишут текст, а читают ситуацию (текст, JSON, картинку, кадры видео) и за один проход возвращают вероятность каждого варианта ответа на типизированные вопросы «да или нет», «выбери один» и «оцени по шкале». Вместо разбора свободного текста агент получает готовые числа.',
    tasks: ['сортировка обращений и заявок по категориям с вероятностью', 'проверка документа или фото по списку вопросов (всё ли указано, есть ли нарушение)', 'выбор следующего шага агентом без разбора текстового ответа', 'оценка риска или срочности по шкале'],
    where: ['поддержка клиентов и разбор тикетов', 'документооборот и проверка заявок', 'безопасность и модерация', 'ИИ-агенты и автоматизация процессов'],
    versions: [['Clef 27B (на базе Qwen3.8-27B)', '2026-10'], ['Clef-flash 9B (на базе Qwen3.5-9B)', '2026-10']],
    hf: 'https://huggingface.co/Cloudflare/clef',
    github: null,
    alternatives: ['qwen', 'gemma', 'nemotron-safety'],
    source: 'https://huggingface.co/Cloudflare/clef',
    verified: true,
    en: {
      summary: "Decision models: they do not write text but read a situation (text, JSON, an image, video frames) and return in one pass the probability of each answer to typed questions: yes or no, pick one, rate on a scale. The agent gets ready numbers instead of parsing free text.",
      tasks: ['sorting requests and tickets into categories with a probability', 'checking a document or photo against a list of questions (is everything stated, is there a violation)', 'choosing the next step of an agent without parsing a text answer', 'rating risk or urgency on a scale'],
      where: ['customer support and ticket handling', 'document management and request checks', 'security and moderation', 'AI agents and process automation'],
      sizes: '27B and 9B (Clef-flash)',
      country: 'USA',
    },
  },
];
