// Пропущенные за август и сентябрь: WeVisDoc, EVIE, WeMM-Embedding, Intern-Decision, FrogNano, UI-Mate, Atria Dawn, Kumo Tabular, NV-Reason-CT. Факты сверены по Hugging Face на 10.10.2026.
module.exports = [
  {
    id: 'wevisdoc',
    name: 'WeVisDoc',
    developer: 'Tencent', country: 'Китай',
    modality: ['ocr', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '2B и 4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['docs', 'finance', 'legal'],
    ollama: false,
    cpu: false,
    summary: 'Разбирает страницу документа целиком: превращает её в Markdown с формулами в LaTeX и таблицами в HTML. Версия 4B на OmniDocBench v1.6 набирает 95,38. Языки в карточке: английский и китайский.',
    tasks: ['перевод сканов и PDF в Markdown для поиска и RAG', 'распознавание таблиц и формул', 'разбор отчётов и научных статей'],
    where: ['документооборот и бухгалтерия', 'юридические отделы', 'финансы и аналитика'],
    versions: [['WeVisDoc-2B', '2026-09'], ['WeVisDoc-4B', '2026-09']],
    hf: 'https://huggingface.co/tencent/WeVisDoc-4B',
    github: null,
    alternatives: ['docling', 'lighton-ocr', 'youtu-parsing-omni'],
    source: 'https://huggingface.co/tencent/WeVisDoc-4B',
    verified: true,
    en: {
      summary: "Parses a whole document page: turns it into Markdown with LaTeX formulas and HTML tables. The 4B version scores 95.38 on OmniDocBench v1.6. Languages on the card: English and Chinese.",
      tasks: ['turning scans and PDFs into Markdown for search and RAG', 'recognizing tables and formulas', 'parsing reports and scientific papers'],
      where: ['document management and accounting', 'legal departments', 'finance and analytics'],
      country: 'China',
    },
  },
  {
    id: 'evie',
    name: 'EVIE',
    developer: 'Tencent', country: 'Китай',
    modality: ['docsearch', 'embed'],
    first: '2026-08', latest: '2026-09',
    sizes: '4.5B и 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['docs', 'legal', 'finance', 'retail'],
    ollama: false,
    cpu: false,
    summary: 'Ищет нужные страницы по документам как по картинкам, не переводя их в текст: сопоставляет запрос с визуальным видом страницы. На ViDoRe V3 набирает 66,75 у версии 8B. Индекс можно сжать до 32 векторов на страницу.',
    tasks: ['поиск по сканам, презентациям и отчётам без распознавания текста', 'RAG по документам с таблицами и графиками', 'поиск в архивах договоров и каталогов'],
    where: ['документооборот и архивы', 'юридические отделы', 'базы знаний'],
    versions: [['EVIE-Preview-4.5B', '2026-08'], ['EVIE-4.5B и EVIE-8B', '2026-09']],
    hf: 'https://huggingface.co/tencent/EVIE-4.5B',
    github: 'https://github.com/Tencent/EVIE',
    alternatives: ['colbert', 'llamaindex-vdr', 'qwen-embedding'],
    source: 'https://huggingface.co/tencent/EVIE-4.5B',
    verified: true,
    en: {
      summary: "Finds the right pages in documents as pictures, without turning them into text: matches a query against how the page looks. Version 8B scores 66.75 on ViDoRe V3. The index can be compressed to 32 vectors per page.",
      tasks: ['searching scans, slides and reports without text recognition', 'RAG over documents with tables and charts', 'searching archives of contracts and catalogs'],
      where: ['document management and archives', 'legal departments', 'knowledge bases'],
      country: 'China',
    },
  },
  {
    id: 'wemm-embedding',
    name: 'WeMM-Embedding',
    developer: 'Tencent', country: 'Китай',
    modality: ['embed', 'vision'],
    first: '2026-08', latest: '2026-08',
    sizes: '2B и 9B',
    license: 'Apache 2.0, кроме сторонних компонентов (их условия указаны в файле LICENSE)',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['retail', 'media', 'docs', 'support'],
    ollama: false,
    cpu: false,
    summary: 'Универсальные эмбеддинги на базе Qwen3.5: переводят текст, картинки, видео и визуальные документы в один вектор на 4096 чисел. Звук не поддерживается. Языки в карточке: китайский и английский.',
    tasks: ['поиск по каталогу товаров по картинке или описанию', 'поиск по видео и презентациям', 'RAG по смешанным материалам из текста и изображений'],
    where: ['интернет-магазины', 'медиа и архивы', 'базы знаний'],
    versions: [['WeMM-Embedding-2B', '2026-08'], ['WeMM-Embedding-9B', '2026-08']],
    hf: 'https://huggingface.co/tencent/WeMM-Embedding-9B',
    github: null,
    alternatives: ['embeddinggemma', 'qwen-embedding', 'gme'],
    source: 'https://huggingface.co/tencent/WeMM-Embedding-9B',
    verified: true,
    en: {
      summary: "Universal embeddings based on Qwen3.5: they turn text, images, video and visual documents into one vector of 4096 numbers. Audio is not supported. Languages on the card: Chinese and English.",
      tasks: ['searching a product catalog by picture or description', 'searching video and slide decks', 'RAG over mixed text and image materials'],
      where: ['online stores', 'media and archives', 'knowledge bases'],
      license: 'Apache 2.0 except third-party components (their terms are in the LICENSE file)',
      country: 'China',
    },
  },
  {
    id: 'intern-decision',
    name: 'Intern-Decision',
    developer: 'Шанхайская лаборатория искусственного интеллекта', country: 'Китай',
    modality: ['nlp', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['support', 'docs', 'security'],
    ollama: false,
    cpu: false,
    summary: 'Модель решений на базе Qwen3.5-4B: по тексту и картинкам отвечает вероятностями на все вопросы о ситуации за один проход, без генерации текста. Подходит для маршрутизации заявок и оценки срочности.',
    tasks: ['сортировка заявок по отделам', 'оценка приоритета и срочности обращений', 'проверка по фото, всё ли в порядке'],
    where: ['поддержка клиентов', 'документооборот', 'ИИ-агенты и автоматизация'],
    versions: [['Intern-Decision-4B', '2026-09']],
    hf: 'https://huggingface.co/internlm/Intern-Decision-4B',
    github: null,
    alternatives: ['clef', 'jev-gev', 'liquid-d1'],
    source: 'https://huggingface.co/internlm/Intern-Decision-4B',
    verified: true,
    en: {
      summary: "A decision model based on Qwen3.5-4B: from text and images it answers all questions about a situation with probabilities in one pass, without generating text. Suits routing requests and rating urgency.",
      tasks: ['routing requests to teams', 'rating priority and urgency of requests', 'checking from a photo that everything is in order'],
      where: ['customer support', 'document management', 'AI agents and automation'],
      developer: 'Shanghai Artificial Intelligence Laboratory',
      country: 'China',
    },
  },
  {
    id: 'frognano',
    name: 'FrogNano',
    developer: 'Microsoft', country: 'США',
    modality: ['code', 'agent'],
    first: '2026-09', latest: '2026-09',
    sizes: '4B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['dev'],
    ollama: false,
    cpu: false,
    summary: 'Компактный агент для работы с кодом репозитория на базе Qwen3.5-4B: ищет по проекту, правит файлы, запускает тесты и готовит патч. Обучен только с подкреплением на примерно 1500 синтетических задачах. Работает через лёгкую обвязку Leaf из пяти инструментов.',
    tasks: ['исправление ошибок в репозитории по описанию задачи', 'навигация по незнакомой кодовой базе', 'подготовка патчей с запуском тестов'],
    where: ['разработка ПО и ИТ', 'внутренние инструменты команд на своих серверах'],
    versions: [['FrogNano-4B-2609', '2026-09']],
    hf: 'https://huggingface.co/microsoft/FrogNano-4B-2609',
    github: null,
    alternatives: ['qwen-coder', 'devstral', 'sera'],
    source: 'https://huggingface.co/microsoft/FrogNano-4B-2609',
    verified: true,
    en: {
      summary: "A compact agent for working with repository code, based on Qwen3.5-4B: searches the project, edits files, runs tests and prepares a patch. Trained only with reinforcement learning on about 1500 synthetic tasks. Works through the light Leaf harness with five tools.",
      tasks: ['fixing bugs in a repository from a task description', 'navigating an unfamiliar codebase', 'preparing patches with test runs'],
      where: ['software development and IT', 'in-house team tools on your own servers'],
      country: 'USA',
    },
  },
  {
    id: 'ui-mate',
    name: 'UI-Mate',
    developer: 'Tencent', country: 'Китай',
    modality: ['agent', 'vlm'],
    first: '2026-08', latest: '2026-08',
    sizes: '27B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['dev', 'support', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Открытый агент для управления рабочим столом: смотрит на живые скриншоты, рассуждает и выдаёт клики и ввод с клавиатуры. Можно показать рабочий процесс один раз, и агент перенесёт его на новую задачу. Нужна внешняя среда, которая исполнит действия.',
    tasks: ['автоматизация работы в программах без API', 'повторение рабочего процесса по одному показанному примеру', 'тестирование интерфейсов'],
    where: ['автоматизация офисной работы', 'тестирование ПО', 'работа с 1С и закрытыми системами'],
    versions: [['UI-Mate-27B', '2026-08']],
    hf: 'https://huggingface.co/tencent/UI-Mate-27B',
    github: 'https://github.com/Tencent/UI-Mate',
    alternatives: ['ui-venus', 'gui-owl', 'fara'],
    source: 'https://huggingface.co/tencent/UI-Mate-27B',
    verified: true,
    en: {
      summary: "An open agent for operating a desktop: looks at live screenshots, reasons and outputs clicks and keyboard input. You can show a workflow once and the agent carries it over to a new task. An external environment is needed to execute the actions.",
      tasks: ['automating work in programs with no API', 'repeating a workflow from one shown example', 'testing interfaces'],
      where: ['office work automation', 'software testing', 'work with 1C and closed systems'],
      country: 'China',
    },
  },
  {
    id: 'atria-dawn',
    name: 'Atria Dawn',
    developer: 'Шанхайская лаборатория искусственного интеллекта', country: 'Китай',
    modality: ['text', 'agent', 'reasoning'],
    first: '2026-09', latest: '2026-09',
    sizes: '744B (MoE, на базе GLM-5.2)',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['multi'],
    ru: 'no',
    industries: ['science', 'dev', 'security', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Агентная модель для долгих задач: поиск и сбор доказательств, исследования, разработка, подготовка отчётов и презентаций, анализ уязвимостей в разрешённой среде. Превью на базе GLM-5.2, контекст 256 тысяч токенов, только текст. Есть версия FP8.',
    tasks: ['глубокий поиск и исследование по теме с проверяемым результатом', 'разработка программ и подготовка отчётов и презентаций', 'проверка и исправление уязвимостей в авторизованной среде'],
    where: ['исследовательские группы', 'разработка ПО', 'информационная безопасность'],
    versions: [['Atria-Dawn-Preview', '2026-09'], ['Atria-Dawn-Preview-FP8', '2026-09']],
    hf: 'https://huggingface.co/internlm/Atria-Dawn-Preview',
    github: null,
    alternatives: ['glm', 'kimi', 'deepseek'],
    source: 'https://huggingface.co/internlm/Atria-Dawn-Preview',
    verified: true,
    en: {
      summary: "An agent model for long tasks: searching and gathering evidence, research, development, preparing reports and presentations, analyzing vulnerabilities in an authorized environment. A preview based on GLM-5.2, 256K-token context, text only. An FP8 version exists.",
      tasks: ['deep search and research on a topic with a verifiable result', 'developing programs and preparing reports and presentations', 'checking and fixing vulnerabilities in an authorized environment'],
      where: ['research groups', 'software development', 'information security'],
      sizes: '744B (MoE, based on GLM-5.2)',
      developer: 'Shanghai Artificial Intelligence Laboratory',
      country: 'China',
    },
  },
  {
    id: 'kumo-tabular',
    name: 'Kumo Tabular',
    developer: 'NVIDIA', country: 'США',
    modality: ['tabular'],
    first: '2026-09', latest: '2026-09',
    sizes: 'размер на карточке не указан',
    license: 'OpenMDW 1.1',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['finance', 'retail', 'manufacturing'],
    ollama: false,
    cpu: false,
    summary: 'Предобученная модель для таблиц: классификация и регрессия по примерам в контексте, отдельно обучать под задачу не нужно. Подаёте размеченные строки и строки, для которых нужен прогноз, и получаете вероятности классов.',
    tasks: ['скоринг клиентов и заявок', 'прогноз по таблице продаж или заказов', 'выявление оттока по таблице клиентов'],
    where: ['финансы и скоринг', 'розница и продажи', 'аналитика'],
    versions: [['Kumo Tabular', '2026-09']],
    hf: 'https://huggingface.co/nvidia/Kumo-Tabular',
    github: 'https://github.com/NVIDIA/structured-data-models',
    alternatives: ['tabpfn', 'tabicl', 'xiaomi-tabldm'],
    source: 'https://huggingface.co/nvidia/Kumo-Tabular',
    verified: true,
    en: {
      summary: "A pretrained model for tables: classification and regression from in-context examples, with no task-specific training. You supply labeled rows and the rows that need a forecast and get class probabilities.",
      tasks: ['scoring customers and requests', 'forecasting from a table of sales or orders', 'detecting churn from a customer table'],
      where: ['finance and scoring', 'retail and sales', 'analytics'],
      sizes: 'size not stated on the card',
      country: 'USA',
    },
  },
  {
    id: 'nv-reason-ct',
    name: 'NV-Reason-CT',
    developer: 'NVIDIA', country: 'США',
    modality: ['medical', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '4B (на базе Qwen3.5-4B с 3D-кодировщиком)',
    license: 'OpenMDW 1.1; исследовательская модель, не клинический продукт',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['medical', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Языковая модель для компьютерной томографии: смотрит на объём КТ грудной клетки или брюшной полости целиком, а не на отдельные срезы, пишет структурированные заключения и отвечает на вопросы с рассуждением. Только английский.',
    tasks: ['черновик заключения по КТ для врача', 'ответы «да или нет» по снимку с рассуждением', 'исследования в медицинской визуализации'],
    where: ['клиники и радиология (для прототипов и исследований)', 'разработчики медицинского ПО', 'вузы'],
    versions: [['NV-Reason-CT', '2026-09']],
    hf: 'https://huggingface.co/nvidia/NV-Reason-CT',
    github: null,
    alternatives: ['medgemma', 'flexray', 'ii-medical'],
    source: 'https://huggingface.co/nvidia/NV-Reason-CT',
    verified: true,
    en: {
      summary: "A language model for computed tomography: looks at a whole chest or abdominal CT volume, not separate slices, writes structured reports and answers questions with reasoning. English only.",
      tasks: ['a draft CT report for a physician', 'yes-or-no answers about a scan with reasoning', 'research in medical imaging'],
      where: ['clinics and radiology (for prototypes and research)', 'medical software developers', 'universities'],
      license: 'OpenMDW 1.1; a research model, not a clinical product',
      sizes: '4B (based on Qwen3.5-4B with a 3D encoder)',
      country: 'USA',
    },
  },
];
