// vLLM Semantic Router Decision и Vela, Youtu-Parsing-Omni, Iris-3B. Факты сверены по Hugging Face на 10.10.2026.
module.exports = [
  {
    id: 'vllm-sr-decision',
    name: 'vLLM Semantic Router: Decision и Vela',
    developer: 'проект vLLM Semantic Router', country: 'международный проект',
    modality: ['nlp', 'safety'],
    first: '2026-09', latest: '2026-10',
    sizes: '0.3B – 27B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['security', 'support', 'dev', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Открытое семейство моделей для ИИ-шлюза: на запрос отвечают вероятностями, не генерируя текст. Определяют тему и срочность, попытку взлома, вредный запрос, персональные данные, нужен ли инструмент. Малые версии работают на процессоре, Vela понимает 17 языков, включая русский.',
    tasks: ['маршрутизация запросов между моделями и командами', 'проверка запроса на попытку взлома и вредное содержание до основной модели', 'поиск персональных данных с координатами в тексте', 'выявление утверждений в ответе ИИ без опоры на источник'],
    where: ['ИИ-шлюзы и корпоративные ассистенты', 'информационная безопасность', 'поддержка клиентов'],
    versions: [['Decision 1.0 (Kai, Eos, Lux, Route 0.6B)', '2026-09'], ['Decision 2.0 (Kai 0.6B, Eos 0.8B, Sol 2B, Nox 4B, Lux 9B, Vega 27B)', '2026-09'], ['Vela 2.0 (0.3B, 0.8B, 4B, 9B)', '2026-10']],
    hf: 'https://huggingface.co/vllm-sr/Decision-2.0-Vega-27B',
    github: 'https://github.com/vllm-project/semantic-router',
    alternatives: ['clef', 'jev-gev', 'liquid-d1'],
    source: 'https://huggingface.co/vllm-sr/Vela-2.0-0.3B',
    verified: true,
    en: {
      summary: "An open family of models for an AI gateway: they answer a request with probabilities without generating text. They detect topic and urgency, jailbreak attempts, harmful requests, personal data and whether a tool is needed. Small versions run on a CPU, Vela understands 17 languages including Russian.",
      tasks: ['routing requests between models and teams', 'checking a request for a jailbreak attempt or harmful content before the main model', 'finding personal data with positions in a text', 'spotting claims in an AI answer with no source behind them'],
      where: ['AI gateways and corporate assistants', 'information security', 'customer support'],
      developer: 'vLLM Semantic Router project',
      country: 'international project',
    },
  },
  {
    id: 'youtu-parsing-omni',
    name: 'Youtu-Parsing-Omni',
    developer: 'Tencent', country: 'Китай',
    modality: ['ocr', 'omni', 'vlm'],
    first: '2026-10', latest: '2026-10',
    sizes: '5B',
    license: 'собственная лицензия Tencent; в тексте прямо сказано, что модель не предназначена для использования в Евросоюзе',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['docs', 'finance', 'media', 'education'],
    ollama: false,
    cpu: false,
    summary: 'Одна компактная модель превращает страницу документа, график, блок-схему, геометрический чертёж, аудио или видео в структурированный JSON: с координатами блоков, таблицами, формулами, расшифровкой речи и временными метками.',
    tasks: ['разбор сканов и PDF с таблицами и формулами', 'перевод графиков и блок-схем в таблицу или диаграмму', 'расшифровка аудио и видео с временными метками', 'описание сцен в видео'],
    where: ['документооборот и бухгалтерия', 'финансы и аналитика', 'медиа', 'образование'],
    versions: [['Youtu-Parsing (2,5B)', '2026-06'], ['Youtu-Parsing-Omni 5B', '2026-10']],
    hf: 'https://huggingface.co/tencent/Youtu-Parsing-Omni',
    github: null,
    alternatives: ['docling', 'lighton-ocr', 'hunyuan-ocr'],
    source: 'https://huggingface.co/tencent/Youtu-Parsing-Omni',
    verified: true,
    en: {
      summary: "One compact model turns a document page, chart, flowchart, geometry figure, audio or video into structured JSON: with block coordinates, tables, formulas, speech transcription and timestamps.",
      tasks: ['parsing scans and PDFs with tables and formulas', 'turning charts and flowcharts into a table or diagram', 'transcribing audio and video with timestamps', 'describing scenes in video'],
      where: ['document management and accounting', 'finance and analytics', 'media', 'education'],
      license: "Tencent's own license; the text states explicitly that the model is not intended for use within the European Union",
      country: 'China',
    },
  },
  {
    id: 'iris',
    name: 'Iris-3B',
    developer: 'Sperid Labs', country: 'не указана',
    modality: ['image', 'vision'],
    first: '2026-10', latest: '2026-10',
    sizes: '3B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['media', 'marketing', 'retail', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Генерирует картинки напрямую в пикселях, без сжатого скрытого пространства. После дообучения те же веса оценивают глубину по одной фотографии, восстанавливают и увеличивают изображения в 4 раза. Промпты на английском, размер по умолчанию 1024 на 1024.',
    tasks: ['генерация изображений по описанию', 'оценка глубины сцены по одной фотографии', 'восстановление и увеличение старых или сжатых снимков'],
    where: ['маркетинг и контент', 'интернет-магазины и каталоги', 'исследования в компьютерном зрении'],
    versions: [['Iris-3B', '2026-10']],
    hf: 'https://huggingface.co/speridlabs/iris-3b',
    github: null,
    alternatives: ['qwen-image', 'flux', 'depth-anything'],
    source: 'https://huggingface.co/speridlabs/iris-3b',
    verified: true,
    en: {
      summary: "Generates images directly in pixels, without a compressed latent space. After fine-tuning, the same weights estimate depth from a single photo and restore and upscale images 4 times. Prompts are in English, the default size is 1024 by 1024.",
      tasks: ['generating images from a description', 'estimating scene depth from a single photo', 'restoring and upscaling old or compressed photos'],
      where: ['marketing and content', 'online stores and catalogs', 'computer vision research'],
      developer: 'Sperid Labs',
      country: 'not stated',
    },
  },
];
