// Волна 8: номера и транспорт — чтение государственного номера с камеры, детекция и классификация
// транспорта, подсчёт потока и трекинг машин, распознавание номеров на въездах и парковках.
// Факты сверены по Hugging Face / GitHub на 23.09.2026.
module.exports = [
  // ---------- ЧТЕНИЕ НОМЕРНОЙ ПЛАСТИНЫ ----------
  {
    id: 'fast-plate-ocr',
    name: 'FastPlateOCR',
    developer: 'ankandrew (открытый проект)', country: 'не раскрыта',
    modality: ['anpr', 'ocr', 'vision'],
    first: '2024-04', latest: '2026-03',
    sizes: 'модели XS и S на архитектуре CCT',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Лёгкие модели чтения символов с уже вырезанной номерной пластины, работают на обычном процессоре. Съёмка машин и людей и хранение таких записей — работа с персональными данными: порядок и сроки согласуйте с юристом.',
    tasks: ['Чтение номера на въезде и выезде', 'Сверка номера с белым списком пропусков', 'Разбор архива записей с камер', 'Дообучение чтения под свой формат номера'],
    where: ['Склады и логистика', 'Охрана территории и КПП', 'Парковки и автомойки', 'Автодилеры и автосервисы'],
    versions: [['Первые открытые модели (релиз arg-plates)', '2024-04'], ['v1.0.1', '2025-07'], ['v1.0.2', '2025-09'], ['v1.1.0, модели v2 global с определением региона', '2026-03']],
    hf: null,
    github: 'https://github.com/ankandrew/fast-plate-ocr',
    alternatives: ['open-image-models', 'fast-alpr', 'nomeroff-net'],
    source: 'https://github.com/ankandrew/fast-plate-ocr/releases',
    verified: true,
    en: {
      summary: 'Lightweight models that read characters from an already cropped license plate and run on an ordinary CPU. Filming vehicles and people and storing such records is personal data processing: agree the procedure and retention with a lawyer.',
      tasks: ['Reading a plate at entry and exit', 'Matching a plate against a whitelist of passes', 'Going through archived camera footage', 'Fine-tuning reading for your own plate format'],
      where: ['Warehousing and logistics', 'Site security and checkpoints', 'Parking lots and car washes', 'Car dealers and service centres'],
      license: 'MIT',
      developer: 'ankandrew (open project)',
      country: 'not disclosed',
      sizes: 'XS and S models on the CCT architecture',
    },
  },
  {
    id: 'open-image-models',
    name: 'Open Image Models',
    developer: 'ankandrew (открытый проект)', country: 'не раскрыта',
    modality: ['anpr', 'vision'],
    first: '2024-09', latest: '2026-07',
    sizes: 'детекторы YOLO-v9 на входах от 256 до 640 пикселей',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Готовые детекторы в формате ONNX: находят номерную пластину на кадре, плюс общие детекторы объектов. Съёмка машин и людей и хранение записей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Поиск номерной пластины на кадре с камеры', 'Подготовка кадра для чтения символов', 'Отбор кадров с транспортом из видеопотока', 'Запуск детекции на слабом железе'],
    where: ['Склады и логистика', 'Охрана территории и КПП', 'Парковки и шлагбаумы', 'Дорожные службы'],
    versions: [['Первые открытые веса (релиз assets)', '2024-09'], ['v0.4.0', '2025-06'], ['v0.5.1', '2025-09'], ['v0.6.0', '2026-07']],
    hf: null,
    github: 'https://github.com/ankandrew/open-image-models',
    alternatives: ['fast-plate-ocr', 'fast-alpr', 'yolo'],
    source: 'https://github.com/ankandrew/open-image-models/releases',
    verified: true,
    en: {
      summary: 'Ready-made ONNX detectors that find the license plate in a frame, plus general object detectors. Filming vehicles and people and storing the records is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Finding the plate in a camera frame', 'Preparing a crop for character reading', 'Picking frames with vehicles out of a video stream', 'Running detection on modest hardware'],
      where: ['Warehousing and logistics', 'Site security and checkpoints', 'Parking lots and barriers', 'Road services'],
      license: 'MIT',
      developer: 'ankandrew (open project)',
      country: 'not disclosed',
      sizes: 'YOLO-v9 detectors at input sizes from 256 to 640 pixels',
    },
  },
  {
    id: 'fast-alpr',
    name: 'FastALPR',
    developer: 'ankandrew (открытый проект)', country: 'не раскрыта',
    modality: ['anpr', 'ocr', 'vision'],
    first: '2024-06', latest: '2026-03',
    sizes: 'связка лёгкого детектора пластины и моделей чтения XS и S',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Готовый конвейер распознавания номера: детектор пластины и чтение символов в одном пакете, свои модели можно подставить. Съёмка машин и людей и хранение записей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Быстрый запуск распознавания номеров на объекте', 'Автоматический пропуск транспорта по списку', 'Учёт заезда и выезда машин', 'Замена отдельных моделей на свои дообученные'],
    where: ['Склады и логистика', 'Парковки и шлагбаумы', 'Охрана территории и КПП', 'Автомойки и автосервисы'],
    versions: [['Первые открытые веса (релиз assets)', '2024-06'], ['v0.2.0', '2025-07'], ['v0.3.0', '2025-08'], ['v0.4.0', '2026-03']],
    hf: null,
    github: 'https://github.com/ankandrew/fast-alpr',
    alternatives: ['fast-plate-ocr', 'open-image-models', 'nomeroff-net'],
    source: 'https://github.com/ankandrew/fast-alpr/releases',
    verified: true,
    en: {
      summary: 'A ready pipeline for plate recognition: plate detector and character reading in one package, with your own models pluggable. Filming vehicles and people and storing the records is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Getting plate recognition running quickly on site', 'Automatic vehicle access by list', 'Logging vehicle entry and exit', 'Swapping individual models for your own fine-tuned ones'],
      where: ['Warehousing and logistics', 'Parking lots and barriers', 'Site security and checkpoints', 'Car washes and service centres'],
      license: 'MIT',
      developer: 'ankandrew (open project)',
      country: 'not disclosed',
      sizes: 'a lightweight plate detector paired with XS and S reading models',
    },
  },
  {
    id: 'nomeroff-net',
    name: 'Nomeroff Net',
    developer: 'RIA.com', country: 'Украина',
    modality: ['anpr', 'ocr', 'vision'],
    first: '2022-05', latest: '2024-12',
    sizes: 'детектор на YOLOv8 плюс отдельные модули чтения символов',
    license: 'GPL-3.0 — копилефт, при встраивании в свой продукт условия лицензии надо соблюдать',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['security', 'manufacturing', 'gov', 'retail'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Система распознавания номеров с отдельными модулями чтения под Россию, Казахстан, Беларусь, Украину, Грузию, Армению и Киргизию. Съёмка машин и людей и хранение записей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Чтение российского номера с камеры', 'Определение страны и типа пластины', 'Учёт транспорта на въезде и выезде', 'Дообучение чтения на своих кадрах'],
    where: ['Охрана территории и КПП', 'Склады и логистика', 'Парковки и шлагбаумы', 'Госсектор и муниципальные службы'],
    versions: [['v3.1.0', '2022-05'], ['v3.2.0', '2022-07'], ['v3.4.0', '2023-03'], ['v4.0.0 на YOLOv8', '2024-12']],
    hf: null,
    github: 'https://github.com/ria-com/nomeroff-net',
    alternatives: ['fast-alpr', 'fast-plate-ocr', 'hyperlpr'],
    source: 'https://github.com/ria-com/nomeroff-net',
    verified: true,
    en: {
      summary: 'A plate recognition system with separate reading modules for Russia, Kazakhstan, Belarus, Ukraine, Georgia, Armenia and Kyrgyzstan. Filming vehicles and people and storing the records is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Reading a Russian plate from a camera', 'Identifying the country and plate type', 'Logging vehicles at entry and exit', 'Fine-tuning reading on your own footage'],
      where: ['Site security and checkpoints', 'Warehousing and logistics', 'Parking lots and barriers', 'Public sector and municipal services'],
      license: 'GPL-3.0 - copyleft; if you embed it in your product you must comply with the license terms',
      developer: 'RIA.com',
      country: 'Ukraine',
      sizes: 'a YOLOv8 detector plus separate character-reading modules',
    },
  },
  {
    id: 'hyperlpr',
    name: 'HyperLPR',
    developer: 'szad670401 (открытый проект)', country: 'Китай',
    modality: ['anpr', 'ocr', 'vision'],
    first: '2023-02', latest: '2025-02',
    sizes: 'компактные модели детекции и чтения, рассчитаны на работу без видеокарты',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['security', 'manufacturing', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Известная открытая система распознавания китайских номеров: одиночные синие и жёлтые пластины, электромобили, учебные машины. Под российский формат номера её надо дообучать. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Распознавание номера на въезде и выезде', 'Работа на слабом железе без видеокарты', 'Встраивание распознавания в своё приложение', 'Дообучение под номера другой страны'],
    where: ['Парковки и шлагбаумы', 'Охрана территории и КПП', 'Склады и логистика', 'Торговые центры'],
    versions: [['HyperLPR3 (v3.0)', '2023-02'], ['Обновления кода и моделей в репозитории', '2025-02']],
    hf: null,
    github: 'https://github.com/szad670401/HyperLPR',
    alternatives: ['nomeroff-net', 'fast-alpr', 'pp-vehicle'],
    source: 'https://github.com/szad670401/HyperLPR',
    verified: true,
    en: {
      summary: 'A well-known open system for Chinese plates: single-row blue and yellow plates, electric vehicles, driving-school cars. It has to be fine-tuned for the Russian plate format. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Plate recognition at entry and exit', 'Running on modest hardware without a GPU', 'Embedding recognition into your own application', 'Fine-tuning for another country plate format'],
      where: ['Parking lots and barriers', 'Site security and checkpoints', 'Warehousing and logistics', 'Shopping centres'],
      license: 'Apache 2.0',
      developer: 'szad670401 (open project)',
      country: 'China',
      sizes: 'compact detection and reading models designed to run without a GPU',
    },
  },
  {
    id: 'autolane-alpr',
    name: 'Autolane ALPR',
    developer: 'Autolane', country: 'не раскрыта',
    modality: ['anpr', 'ocr', 'vision'],
    first: '2026-01', latest: '2026-02',
    sizes: 'детекторы RF-DETR и YOLOX-S, чтение символов на CCT-S',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: ['int8'],
    summary: 'Свежий набор весов для распознавания номеров: два детектора пластины и модель чтения, обучены на американских номерах, под российский формат нужно дообучение. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Поиск пластины на кадре', 'Чтение символов номера', 'Запуск на камерах и одноплатных компьютерах', 'Дообучение на своём наборе номеров'],
    where: ['Парковки и шлагбаумы', 'Склады и логистика', 'Охрана территории и КПП', 'Автодилеры и автосервисы'],
    versions: [['RF-DETR для детекции пластины', '2026-01'], ['YOLOX-S для детекции пластины', '2026-02'], ['CCT-S для чтения символов', '2026-02']],
    hf: 'https://huggingface.co/autolane',
    github: null,
    alternatives: ['fast-alpr', 'open-image-models', 'yolov11-plate'],
    source: 'https://huggingface.co/autolane/rfdetr-alpr',
    verified: true,
    en: {
      summary: 'A recent set of plate recognition weights: two plate detectors and a reading model, trained on US plates, so the Russian format needs fine-tuning. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Finding the plate in a frame', 'Reading the plate characters', 'Running on cameras and single-board computers', 'Fine-tuning on your own set of plates'],
      where: ['Parking lots and barriers', 'Warehousing and logistics', 'Site security and checkpoints', 'Car dealers and service centres'],
      license: 'Apache 2.0',
      developer: 'Autolane',
      country: 'not disclosed',
      sizes: 'RF-DETR and YOLOX-S detectors, CCT-S for character reading',
    },
  },
  {
    id: 'yolov11-plate',
    name: 'YOLOv11 License Plate Detection',
    developer: 'MorseTechLab', country: 'не раскрыта',
    modality: ['anpr', 'vision'],
    first: '2025-05', latest: '2026-05',
    sizes: 'дообученная YOLO11, есть сборка ONNX',
    license: 'AGPL-3.0 — наследуется от Ultralytics YOLO11, для закрытого продукта нужна платная лицензия разработчика YOLO',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Самый скачиваемый на Hugging Face детектор номерных пластин: находит пластину на кадре, дальше её читает отдельная модель. Съёмка машин и людей и хранение записей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Поиск пластины на видео с камеры', 'Подготовка вырезов для чтения номера', 'Проверка идеи распознавания номеров без обучения', 'Дообучение детектора на своих кадрах'],
    where: ['Парковки и шлагбаумы', 'Склады и логистика', 'Охрана территории и КПП', 'Дорожные службы'],
    versions: [['Первая публикация весов', '2025-05'], ['Обновление карточки и сборки ONNX', '2026-05']],
    hf: 'https://huggingface.co/morsetechlab/yolov11-license-plate-detection',
    github: null,
    alternatives: ['open-image-models', 'autolane-alpr', 'yolo'],
    source: 'https://huggingface.co/morsetechlab/yolov11-license-plate-detection',
    verified: true,
    en: {
      summary: 'The most downloaded plate detector on Hugging Face: it finds the plate in a frame, and a separate model then reads it. Filming vehicles and people and storing the records is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Finding the plate in camera video', 'Preparing crops for plate reading', 'Testing a plate recognition idea without training', 'Fine-tuning the detector on your own footage'],
      where: ['Parking lots and barriers', 'Warehousing and logistics', 'Site security and checkpoints', 'Road services'],
      license: 'AGPL-3.0 - inherited from Ultralytics YOLO11; a closed product needs the paid license from the YOLO developer',
      developer: 'MorseTechLab',
      country: 'not disclosed',
      sizes: 'a fine-tuned YOLO11, with an ONNX build available',
    },
  },
  {
    id: 'hezar-plate',
    name: 'Hezar License Plate Recognition',
    developer: 'Hezar AI', country: 'Иран',
    modality: ['anpr', 'ocr'],
    first: '2023-10', latest: '2025-06',
    sizes: 'компактная модель CRNN',
    license: 'на карточке модели лицензия не указана — перед коммерческим использованием уточните у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['security', 'manufacturing', 'gov', 'retail'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Чтение символов с иранских номерных пластин, модель маленькая и работает без видеокарты. Обучена на номерах другой страны, под российский формат нужно дообучение. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Чтение номера с вырезанной пластины', 'Пример архитектуры для своего формата номера', 'Дообучение чтения на своих кадрах', 'Работа на слабом железе'],
    where: ['Охрана территории и КПП', 'Парковки и шлагбаумы', 'Склады и логистика', 'Транспортные компании'],
    versions: [['Первая версия чтения номеров', '2023-10'], ['Версия v2', '2024-06'], ['Обновление карточки и весов', '2025-06']],
    hf: 'https://huggingface.co/hezarai/crnn-fa-license-plate-recognition-v2',
    github: 'https://github.com/hezarai/hezar',
    alternatives: ['fast-plate-ocr', 'nomeroff-net', 'trocr'],
    source: 'https://huggingface.co/hezarai/crnn-fa-license-plate-recognition-v2',
    verified: true,
    en: {
      summary: 'Character reading for Iranian license plates; the model is small and runs without a GPU. It was trained on another country plates, so the Russian format needs fine-tuning. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Reading a plate from a cropped image', 'Using the architecture as an example for your own plate format', 'Fine-tuning reading on your own footage', 'Running on modest hardware'],
      where: ['Site security and checkpoints', 'Parking lots and barriers', 'Warehousing and logistics', 'Transport companies'],
      license: 'the model card states no license - check with the developer before commercial use',
      developer: 'Hezar AI',
      country: 'Iran',
      sizes: 'a compact CRNN model',
    },
  },
  {
    id: 'vehicle-paligemma',
    name: 'VehiclePaliGemma',
    developer: 'NYU Abu Dhabi (ComNets)', country: 'ОАЭ',
    modality: ['anpr', 'vlm', 'ocr'],
    first: '2024-11', latest: '2025-07',
    sizes: '3B',
    license: 'Gemma Terms of Use — собственная лицензия Google с ограничениями по применению',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['security', 'manufacturing', 'gov', 'retail'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Модель, которая смотрит на фото и словами отвечает, что написано на номере: дообучена на малайзийских номерах, под российский формат нужно дообучение. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Чтение номера на сложных кадрах', 'Ответы на вопросы по фото транспорта', 'Разбор архива фотографий с камер', 'Дообучение под свой формат номера'],
    where: ['Охрана территории и КПП', 'Парковки и шлагбаумы', 'Транспортные компании', 'Госсектор'],
    versions: [['Первая публикация весов', '2024-11'], ['Обновление карточки модели', '2025-07']],
    hf: 'https://huggingface.co/NYUAD-ComNets/VehiclePaliGemma',
    github: null,
    alternatives: ['paligemma', 'fast-plate-ocr', 'nomeroff-net'],
    source: 'https://huggingface.co/NYUAD-ComNets/VehiclePaliGemma',
    verified: true,
    en: {
      summary: 'A model that looks at a photo and answers in words what the plate says: fine-tuned on Malaysian plates, so the Russian format needs fine-tuning. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Reading plates in difficult frames', 'Answering questions about a vehicle photo', 'Going through an archive of camera photos', 'Fine-tuning for your own plate format'],
      where: ['Site security and checkpoints', 'Parking lots and barriers', 'Transport companies', 'Public sector'],
      license: 'Gemma Terms of Use - a proprietary Google license with usage restrictions',
      developer: 'NYU Abu Dhabi (ComNets)',
      country: 'UAE',
    },
  },
  // ---------- ТРАНСПОРТ: ДЕТЕКЦИЯ, АТРИБУТЫ, ПОТОК ----------
  {
    id: 'pp-vehicle',
    name: 'PP-Vehicle (PaddleDetection)',
    developer: 'PaddlePaddle (Baidu)', country: 'Китай',
    modality: ['anpr', 'vision', 'ocr'],
    first: '2022-09', latest: '2026-03',
    sizes: 'набор моделей: детектор транспорта, атрибуты, чтение номера на PP-OCR',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['manufacturing', 'security', 'gov', 'retail'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Готовый набор моделей под задачи транспорта: распознавание номера, цвет и тип машины, подсчёт въездов и выездов, поиск стоянки в неположенном месте. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Подсчёт транспортного потока', 'Определение типа и цвета машины', 'Чтение номера на въезде', 'Контроль стоянки в запрещённых зонах'],
    where: ['Склады и логистика', 'Парковки и территории предприятий', 'Дорожные службы', 'Торговые центры'],
    versions: [['PaddleDetection 2.5 с конвейером PP-Vehicle', '2022-09'], ['2.6.0', '2023-02'], ['2.7.0', '2023-10'], ['2.8.0', '2024-11'], ['2.8.1', '2025-02'], ['2.9.0', '2026-03']],
    hf: null,
    github: 'https://github.com/PaddlePaddle/PaddleDetection',
    alternatives: ['intel-vehicle', 'boxmot', 'hyperlpr'],
    source: 'https://github.com/PaddlePaddle/PaddleDetection/releases',
    verified: true,
    en: {
      summary: 'A ready set of models for vehicle tasks: plate recognition, car color and type, counting entries and exits, spotting parking where it is not allowed. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Counting traffic flow', 'Identifying car type and color', 'Reading the plate at the entrance', 'Monitoring parking in restricted zones'],
      where: ['Warehousing and logistics', 'Parking lots and company premises', 'Road services', 'Shopping centres'],
      license: 'Apache 2.0',
      developer: 'PaddlePaddle (Baidu)',
      country: 'China',
      sizes: 'a set of models: vehicle detector, attributes, plate reading on PP-OCR',
    },
  },
  {
    id: 'intel-vehicle',
    name: 'Intel Vehicle Models (OpenVINO)',
    developer: 'Intel', country: 'США',
    modality: ['anpr', 'vision'],
    first: '2026-05', latest: '2026-09',
    sizes: 'варианты YOLO26 от nano до x',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['manufacturing', 'security', 'gov', 'retail'],
    ollama: false,
    cpu: true,
    quant: ['int8'],
    summary: 'Модели Intel под видеоаналитику транспорта: легковая, грузовик, автобус, мотоцикл, а также журнал въезда и выезда и слишком долгая стоянка. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Подсчёт машин и разбивка по типам', 'Журнал въезда и выезда транспорта', 'Контроль занятости парковочных мест', 'Поиск машин, стоящих слишком долго'],
    where: ['Парковки и территории предприятий', 'Склады и логистика', 'Городская инфраструктура', 'Торговые центры'],
    versions: [['vehicle-detection на базе YOLO26', '2026-05'], ['vehicle-entry-exit-logging', '2026-08'], ['vehicle-stopped-too-long-detection', '2026-08'], ['Обновление карточек моделей', '2026-09']],
    hf: 'https://huggingface.co/Intel/vehicle-detection',
    github: null,
    alternatives: ['pp-vehicle', 'boxmot', 'yolo'],
    source: 'https://huggingface.co/Intel/vehicle-detection',
    verified: true,
    en: {
      summary: 'Intel models for vehicle video analytics: car, truck, bus, motorcycle, plus entry and exit logging and vehicles stopped too long. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Counting vehicles and splitting them by type', 'Logging vehicle entry and exit', 'Monitoring parking space occupancy', 'Spotting vehicles that stay too long'],
      where: ['Parking lots and company premises', 'Warehousing and logistics', 'City infrastructure', 'Shopping centres'],
      license: 'MIT',
      country: 'USA',
      sizes: 'YOLO26 variants from nano to x',
    },
  },
  {
    id: 'boxmot',
    name: 'BoxMOT',
    developer: 'Mikel Brostrom (открытый проект)', country: 'не раскрыта',
    modality: ['anpr', 'vision'],
    first: '2020-12', latest: '2026-09',
    sizes: 'трекеры плюс модели повторной идентификации от компактных до крупных',
    license: 'AGPL-3.0 — копилефт, для закрытого продукта условия надо проверять отдельно',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['manufacturing', 'security', 'retail', 'gov'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Набор трекеров: связывает одну и ту же машину между кадрами и камерами, отсюда считается поток и время на объекте. Съёмка машин и людей и хранение записей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Подсчёт машин, проехавших через линию', 'Сопровождение транспорта между кадрами', 'Поиск той же машины на другой камере', 'Замер времени нахождения на территории'],
    where: ['Склады и логистика', 'Парковки и территории предприятий', 'Дорожные службы', 'Охрана территории'],
    versions: [['Первый выпуск (v1.0)', '2020-12'], ['v10.0.46', '2023-11'], ['v22.0.0', '2026-07'], ['v23.0.0', '2026-08'], ['v25.0.0', '2026-09']],
    hf: null,
    github: 'https://github.com/mikel-brostrom/boxmot',
    alternatives: ['pp-vehicle', 'intel-vehicle', 'yolo'],
    source: 'https://github.com/mikel-brostrom/boxmot/releases',
    verified: true,
    en: {
      summary: 'A set of trackers: it links the same vehicle across frames and cameras, which is how flow and time on site are counted. Filming vehicles and people and storing the records is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Counting vehicles crossing a line', 'Following a vehicle across frames', 'Finding the same vehicle on another camera', 'Measuring time spent on the premises'],
      where: ['Warehousing and logistics', 'Parking lots and company premises', 'Road services', 'Site security'],
      license: 'AGPL-3.0 - copyleft; for a closed product the terms need separate review',
      developer: 'Mikel Brostrom (open project)',
      country: 'not disclosed',
      sizes: 'trackers plus re-identification models from compact to large',
    },
  },
  {
    id: 'vit-vehicle-classifiers',
    name: 'ViT Vehicle Classifiers (dima806)',
    developer: 'dima806 (открытый проект)', country: 'не раскрыта',
    modality: ['anpr', 'vision'],
    first: '2023-11', latest: '2024-10',
    sizes: 'на базе ViT-base (google/vit-base-patch16-224-in21k)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['retail', 'manufacturing', 'finance', 'security'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Два простых классификатора по фото: тип транспорта и марка автомобиля. Обучены на открытых наборах, перед применением проверяйте на своих кадрах. Съёмка машин и людей — работа с персональными данными, порядок согласуйте с юристом.',
    tasks: ['Определение типа транспорта по фото', 'Предварительная разметка марки автомобиля', 'Разбор фотографий в объявлениях и заявках', 'Пример для дообучения под свой список классов'],
    where: ['Автодилеры и площадки объявлений', 'Страхование и оценка', 'Склады и логистика', 'Охрана территории'],
    versions: [['Классификатор типов транспорта', '2023-11'], ['Классификатор марок автомобилей', '2024-10']],
    hf: 'https://huggingface.co/dima806/vehicle_10_types_image_detection',
    github: null,
    alternatives: ['vehicle-paligemma', 'intel-vehicle', 'clip-siglip'],
    source: 'https://huggingface.co/dima806/car_brands_image_detection',
    verified: true,
    en: {
      summary: 'Two simple photo classifiers: vehicle type and car brand. Trained on public datasets, so check them on your own footage before use. Filming vehicles and people is personal data processing: agree the procedure with a lawyer.',
      tasks: ['Identifying the vehicle type from a photo', 'Pre-labelling the car brand', 'Going through photos in listings and applications', 'Using as an example for fine-tuning to your own class list'],
      where: ['Car dealers and classifieds platforms', 'Insurance and appraisal', 'Warehousing and logistics', 'Site security'],
      license: 'Apache 2.0',
      developer: 'dima806 (open project)',
      country: 'not disclosed',
      sizes: 'based on ViT-base (google/vit-base-patch16-224-in21k)',
    },
  },
];
