// Волна 8: чертежи и CAD — генерация CAD-моделей по описанию, изображению и облаку точек,
// разбор инженерных чертежей и строительных планов, векторизация растровых чертежей,
// чтение схем, блок-схем и графиков. Факты сверены по Hugging Face / GitHub на 23.09.2026.
module.exports = [
  // ---------- CAD ПО ОБЛАКУ ТОЧЕК И СКАНУ ----------
  {
    id: 'cad-recode',
    name: 'CAD-Recode',
    developer: 'Университет Люксембурга (SnT) и Artec3D', country: 'Люксембург',
    modality: ['cad', '3d', 'code'],
    first: '2024-12', latest: '2025-03',
    sizes: '1.5B (Qwen2-1.5B плюс один проекционный слой)',
    license: 'CC BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['manufacturing', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Превращает облако точек детали в исполняемый код CadQuery на Python, то есть в параметрическую 3D-модель, которую можно открыть и править в CAD. Результат — черновик: проверяет и подписывает документ инженер.',
    tasks: ['Восстановление параметрической модели по 3D-скану детали', 'Перевод облака точек в редактируемый код CadQuery', 'Подготовка черновика модели для доработки конструктором', 'Оцифровка деталей без исходных чертежей'],
    where: ['Конструкторские бюро', 'Производство и обратный инжиниринг', 'Ремонт и изготовление запчастей', 'Исследования'],
    versions: [['CAD-Recode (первый выпуск)', '2024-12'], ['CAD-Recode v1.5', '2025-03']],
    hf: 'https://huggingface.co/filapro/cad-recode-v1.5',
    github: 'https://github.com/filaPro/cad-recode',
    alternatives: ['cadrille', 'cadreasoner', 'zero-to-cad'],
    source: 'https://huggingface.co/filapro/cad-recode-v1.5',
    verified: true,
    en: {
      summary: 'Turns a point cloud of a part into executable CadQuery Python code, that is, a parametric 3D model you can open and edit in CAD. The output is a draft: an engineer checks and signs off the document.',
      tasks: ['Recovering a parametric model from a 3D scan of a part', 'Converting a point cloud into editable CadQuery code', 'Preparing a draft model for a design engineer to finish', 'Digitising parts that have no original drawings'],
      where: ['Design offices', 'Manufacturing and reverse engineering', 'Repair and spare-part production', 'Research'],
      license: 'CC BY-NC 4.0 - non-commercial use only',
      developer: 'University of Luxembourg (SnT) and Artec3D',
      country: 'Luxembourg',
      sizes: '1.5B (Qwen2-1.5B plus a single projection layer)',
    },
  },
  {
    id: 'cadrille',
    name: 'cadrille',
    developer: 'AIRI, МГУ и Университет Иннополис', country: 'Россия',
    modality: ['cad', '3d', 'vlm'],
    first: '2025-05', latest: '2025-06',
    sizes: '2.2B (на основе Qwen2-VL)',
    license: 'CC BY-NC 4.0 у весов, код на GitHub под Apache 2.0 — весами пользоваться только некоммерчески',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['manufacturing', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Развитие CAD-Recode: собирает CAD-модель в виде кода CadQuery сразу из трёх видов входа — облака точек, картинки и текстового описания. Выдаёт черновик, проверяет и подписывает документ инженер.',
    tasks: ['Сборка CAD-модели по фотографии детали', 'Восстановление модели по 3D-скану', 'Черновик детали по короткому текстовому описанию', 'Единый инструмент вместо трёх узких моделей'],
    where: ['Конструкторские бюро', 'Производство и обратный инжиниринг', 'Проектные организации', 'Исследования'],
    versions: [['cadrille-rl (версия с обучением с подкреплением)', '2025-05'], ['cadrille (базовая трёхмодальная версия)', '2025-06']],
    hf: 'https://huggingface.co/maksimko123/cadrille',
    github: 'https://github.com/col14m/cadrille',
    alternatives: ['cad-recode', 'cadreasoner', 'zero-to-cad'],
    source: 'https://huggingface.co/maksimko123/cadrille',
    verified: true,
    en: {
      summary: 'A successor to CAD-Recode: it builds a CAD model as CadQuery code from three kinds of input at once - a point cloud, an image and a text description. It produces a draft; an engineer checks and signs off the document.',
      tasks: ['Building a CAD model from a photo of a part', 'Recovering a model from a 3D scan', 'A draft part from a short text description', 'One tool instead of three narrow models'],
      where: ['Design offices', 'Manufacturing and reverse engineering', 'Engineering and design firms', 'Research'],
      license: 'CC BY-NC 4.0 for the weights, Apache 2.0 for the GitHub code - the weights are for non-commercial use only',
      developer: 'AIRI, Lomonosov Moscow State University and Innopolis University',
      country: 'Russia',
      sizes: '2.2B (based on Qwen2-VL)',
    },
  },
  {
    id: 'cadreasoner',
    name: 'CADReasoner',
    developer: 'FusionBrain Lab, МГУ и Университет Иннополис', country: 'Россия',
    modality: ['cad', '3d', 'vlm'],
    first: '2026-02', latest: '2026-08',
    sizes: '2.2B',
    license: 'Apache 2.0 у основных весов, у модели CADENA — MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'na',
    industries: ['manufacturing', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Строит код CadQuery по изображениям и облаку точек и затем несколько раз правит его сам, сравнивая полученную форму с исходной. Это черновик модели: проверяет и подписывает документ инженер.',
    tasks: ['Восстановление параметрической модели по фото и скану детали', 'Пошаговое уточнение черновой CAD-модели', 'Оцифровка деталей без чертежей', 'Подготовка модели к доработке конструктором'],
    where: ['Конструкторские бюро', 'Производство и обратный инжиниринг', 'Ремонт оборудования', 'Исследования'],
    versions: [['CADEvolve RL1', '2026-02'], ['CADReasoner', '2026-02'], ['CADENA (версии SFT и RL)', '2026-08'], ['CADReasoner-PC и CADReasoner-CM', '2026-08']],
    hf: 'https://huggingface.co/kulibinai/cadreasoner',
    github: 'https://github.com/zhemdi/CADReasoner',
    alternatives: ['cad-recode', 'cadrille', 'zero-to-cad'],
    source: 'https://huggingface.co/kulibinai/cadreasoner',
    verified: true,
    en: {
      summary: 'It writes CadQuery code from images and a point cloud, then edits its own output over several rounds, comparing the resulting shape with the original. This is a draft model: an engineer checks and signs off the document.',
      tasks: ['Recovering a parametric model from photos and a scan of a part', 'Step-by-step refinement of a draft CAD model', 'Digitising parts that have no drawings', 'Preparing a model for a design engineer to finish'],
      where: ['Design offices', 'Manufacturing and reverse engineering', 'Equipment repair', 'Research'],
      license: 'Apache 2.0 for the main weights, MIT for the CADENA model',
      developer: 'FusionBrain Lab, Lomonosov Moscow State University and Innopolis University',
      country: 'Russia',
    },
  },
  // ---------- CAD ПО ОПИСАНИЮ И ПО ИЗОБРАЖЕНИЮ ----------
  {
    id: 'zero-to-cad',
    name: 'Zero-to-CAD',
    developer: 'Autodesk Research', country: 'США',
    modality: ['cad', 'vlm', 'code'],
    first: '2026-04', latest: '2026-05',
    sizes: '2B (на основе Qwen3-VL-2B)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['manufacturing', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: ['gguf'],
    summary: 'Модель от исследовательского подразделения Autodesk: по восьми ракурсам детали пишет исполняемую программу CadQuery. Обучена только на синтетических данных. Выдаёт черновик, проверяет и подписывает документ инженер.',
    tasks: ['Получение параметрической модели по набору видов детали', 'Перевод готовой геометрии в редактируемый код', 'Черновик модели для конструкторского бюро', 'Оцифровка простых деталей без исходников'],
    where: ['Конструкторские бюро', 'Производство', 'Проектные организации', 'Исследования'],
    versions: [['Zero-to-CAD Qwen3-VL-2B', '2026-04'], ['Обновление карточки и примеров', '2026-05']],
    hf: 'https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B',
    github: null,
    alternatives: ['cadrille', 'cadreasoner', 'cad-recode'],
    source: 'https://huggingface.co/ADSKAILab/Zero-To-CAD-Qwen3-VL-2B',
    verified: true,
    en: {
      summary: 'A model from Autodesk Research: from eight rendered views of a part it writes an executable CadQuery program. It was trained on synthetic data only. It produces a draft; an engineer checks and signs off the document.',
      tasks: ['Getting a parametric model from a set of views of a part', 'Converting finished geometry into editable code', 'A draft model for a design office', 'Digitising simple parts with no source files'],
      where: ['Design offices', 'Manufacturing', 'Engineering and design firms', 'Research'],
      license: 'Apache 2.0',
      country: 'USA',
      sizes: '2B (based on Qwen3-VL-2B)',
    },
  },
  {
    id: 'text2cad',
    name: 'Text2CAD',
    developer: 'DFKI и Университет Кайзерслаутерна (RPTU)', country: 'Германия',
    modality: ['cad', 'text', '3d'],
    first: '2024-12', latest: '2025-06',
    sizes: 'размер не указан на карточке',
    license: 'CC BY-NC-SA 4.0 — только некоммерческое использование, производные на тех же условиях',
    commercial: 'no',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['manufacturing', 'dev', 'science'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Строит последовательность команд CAD-моделирования прямо по текстовому описанию детали — от фразы новичка до формулировки конструктора. Результат — черновик, проверяет и подписывает документ инженер.',
    tasks: ['Черновик детали по текстовому описанию', 'Быстрый перебор вариантов формы на раннем этапе', 'Наполнение библиотеки типовых деталей', 'Исследования по генерации CAD'],
    where: ['Конструкторские бюро', 'Производство', 'Образование и обучение конструкторов', 'Исследования'],
    versions: [['Text2CAD 1.0 (веса Text2CAD Transformer)', '2024-12'], ['Обновление репозитория с весами', '2025-06']],
    hf: 'https://huggingface.co/datasets/SadilKhan/Text2CAD',
    github: 'https://github.com/SadilKhan/Text2CAD',
    alternatives: ['cadrille', 'zero-to-cad', 'cadreasoner'],
    source: 'https://huggingface.co/datasets/SadilKhan/Text2CAD',
    verified: true,
    en: {
      summary: 'It builds a sequence of CAD modelling commands straight from a text description of a part, from a beginner phrase to a designer-level wording. The output is a draft; an engineer checks and signs off the document.',
      tasks: ['A draft part from a text description', 'Quickly trying out shape options at an early stage', 'Filling a library of standard parts', 'Research on CAD generation'],
      where: ['Design offices', 'Manufacturing', 'Education and training of design engineers', 'Research'],
      license: 'CC BY-NC-SA 4.0 - non-commercial use only, derivatives under the same terms',
      developer: 'DFKI and RPTU Kaiserslautern',
      country: 'Germany',
      sizes: 'size not stated on the model card',
    },
  },
  // ---------- ЧЕРТЕЖИ, ПЛАНЫ И СКАНЫ ПОМЕЩЕНИЙ ----------
  {
    id: 'plankassembly',
    name: 'PlankAssembly',
    developer: 'Manycore Research', country: 'Китай',
    modality: ['cad', '3d', 'vision'],
    first: '2023-09', latest: '2024-12',
    sizes: 'размер не указан на карточке, выложено несколько контрольных точек под разные входы',
    license: 'AGPL-3.0 — производные работы придётся открывать',
    commercial: 'conditional',
    hardware: ['gpu'],
    ru: 'na',
    industries: ['manufacturing', 'docs', 'science'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Собирает трёхмерную модель изделия по трём обычным проекциям чертежа — виду спереди, сверху и сбоку, в том числе когда линии на чертеже неполные. Результат — черновик, проверяет и подписывает документ инженер.',
    tasks: ['Перевод чертежа в трёх проекциях в 3D-модель', 'Оцифровка архива бумажных чертежей мебели и корпусов', 'Проверка соответствия видов друг другу', 'Подготовка модели к доработке конструктором'],
    where: ['Мебельное и корпусное производство', 'Конструкторские бюро', 'Архивы технической документации', 'Исследования'],
    versions: [['PlankAssembly (веса ICCV 2023)', '2023-09'], ['Обновление контрольных точек', '2024-12']],
    hf: 'https://huggingface.co/manycore-research/PlankAssembly',
    github: 'https://github.com/manycore-research/PlankAssembly',
    alternatives: ['cad-recode', 'spatiallm', 'greenmap-blueprint'],
    source: 'https://huggingface.co/manycore-research/PlankAssembly',
    verified: true,
    en: {
      summary: 'It assembles a 3D model of a product from three standard drawing projections - front, top and side - including cases where the lines in the drawing are incomplete. The output is a draft; an engineer checks and signs off the document.',
      tasks: ['Turning a three-view drawing into a 3D model', 'Digitising an archive of paper drawings for furniture and cabinets', 'Checking that the views agree with each other', 'Preparing a model for a design engineer to finish'],
      where: ['Furniture and cabinet manufacturing', 'Design offices', 'Technical documentation archives', 'Research'],
      license: 'AGPL-3.0 - derivative works must be open-sourced',
      country: 'China',
      sizes: 'size not stated on the model card, several checkpoints published for different inputs',
    },
  },
  {
    id: 'spatiallm',
    name: 'SpatialLM',
    developer: 'Manycore Research', country: 'Китай',
    modality: ['cad', '3d', 'text'],
    first: '2025-03', latest: '2025-09',
    sizes: '0.5B – 1B',
    license: 'смешанная: версии на Qwen — CC BY-NC 4.0, версии на Llama 3.2 — Llama 3.2 Community License',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['manufacturing', 'docs', 'dev', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'По облаку точек помещения или по видеообходу строит структурный план: стены, двери, окна и объекты с координатами и размерами. Черновик обмеров, итоговые площади подтверждает специалист.',
    tasks: ['Построение поэтажного плана по 3D-скану помещения', 'Извлечение стен, дверей и окон с размерами', 'Черновые обмеры перед ремонтом или переездом', 'Подготовка данных для BIM и проектных расчётов'],
    where: ['Проектирование и строительство', 'Недвижимость и обмеры помещений', 'Ремонт и дизайн интерьера', 'Робототехника и навигация в помещениях'],
    versions: [['SpatialLM-Llama-1B и SpatialLM-Qwen-0.5B', '2025-03'], ['SpatialLM 1.1', '2025-06'], ['Обновление весов 1.1', '2025-09']],
    hf: 'https://huggingface.co/manycore-research/SpatialLM1.1-Qwen-0.5B',
    github: 'https://github.com/manycore-research/SpatialLM',
    alternatives: ['greenmap-blueprint', 'plankassembly', 'moge'],
    source: 'https://huggingface.co/manycore-research/SpatialLM1.1-Qwen-0.5B',
    verified: true,
    en: {
      summary: 'From a point cloud of a room or a walkthrough video it builds a structured plan: walls, doors, windows and objects with coordinates and sizes. It is a draft survey; final areas are confirmed by a specialist.',
      tasks: ['Building a floor plan from a 3D scan of a space', 'Extracting walls, doors and windows with dimensions', 'Draft measurements before a renovation or a move', 'Preparing data for BIM and design calculations'],
      where: ['Design and construction', 'Real estate and space surveying', 'Renovation and interior design', 'Robotics and indoor navigation'],
      license: 'mixed: Qwen-based versions under CC BY-NC 4.0, Llama 3.2-based versions under the Llama 3.2 Community License',
      country: 'China',
      sizes: '0.5B - 1B',
    },
  },
  {
    id: 'greenmap-blueprint',
    name: 'GreenMap Blueprint',
    developer: 'GreenMap', country: 'не раскрыта',
    modality: ['cad', 'vlm', 'vision'],
    first: '2026-04', latest: '2026-09',
    sizes: '3.5M – 4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['manufacturing', 'docs', 'gov'],
    ollama: false,
    cpu: true,
    quant: ['gguf'],
    summary: 'Набор небольших моделей под русскоязычные строительные чертежи: находит поле чертежа, штамп и легенду, размечает стены и штриховки, вытаскивает данные листа в JSON и ссылки на нормы. Черновик, который проверяет инженер.',
    tasks: ['Поиск штампа, легенды и поля чертежа на листе', 'Разметка стен и штриховок на поэтажном плане', 'Извлечение данных с чертежа в структурированный JSON', 'Подготовка данных для сметы и поиск ссылок на нормативы'],
    where: ['Строительство и проектирование', 'Сметные отделы', 'Технический документооборот', 'Госзаказ и экспертиза проектов'],
    versions: [['Извлечение JSON из русских документов, 2B и 4B', '2026-04'], ['Поиск ссылок на нормативы и сметный модуль', '2026-05'], ['Детекторы поля чертежа, стен и штампа, blueprint-extractor', '2026-06'], ['Детектор легенды', '2026-07'], ['Hatch Finder — поиск штриховок', '2026-09']],
    hf: 'https://huggingface.co/GreenMap',
    github: null,
    alternatives: ['spatiallm', 'docling', 'dots-ocr'],
    source: 'https://huggingface.co/GreenMap',
    verified: true,
    en: {
      summary: 'A set of small models for Russian-language construction drawings: it finds the drawing area, title block and legend, marks up walls and hatching, and pulls sheet data into JSON along with references to standards. A draft that an engineer checks.',
      tasks: ['Finding the title block, legend and drawing area on a sheet', 'Marking up walls and hatching on a floor plan', 'Extracting drawing data into structured JSON', 'Preparing data for cost estimates and finding references to standards'],
      where: ['Construction and design', 'Cost estimating departments', 'Technical document workflows', 'Public procurement and project review'],
      license: 'Apache 2.0',
      country: 'not disclosed',
      sizes: '3.5M - 4B',
    },
  },
  // ---------- ВЕКТОРИЗАЦИЯ РАСТРОВЫХ ЧЕРТЕЖЕЙ И ЗНАКОВ ----------
  {
    id: 'starvector',
    name: 'StarVector',
    developer: 'ServiceNow Research, Mila и ETS Montreal', country: 'Канада',
    modality: ['cad', 'vlm', 'code'],
    first: '2025-01', latest: '2025-03',
    sizes: '1B и 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['media', 'marketing', 'dev', 'manufacturing'],
    ollama: false,
    cpu: false,
    quant: ['gguf'],
    summary: 'Переводит растровую картинку в код SVG: вместо обводки пикселей модель пишет векторные команды, поэтому линии и символы остаются редактируемыми. Сложные чертежи упрощает, результат проверяют глазами.',
    tasks: ['Векторизация схем, знаков и логотипов из растра', 'Перевод сканов простых чертежей в редактируемый вектор', 'Восстановление иконок и пиктограмм из картинок', 'Подготовка графики для печати и резки'],
    where: ['Дизайн и медиапродакшн', 'Маркетинг и брендинг', 'Разработка интерфейсов', 'Подготовка производства и раскроя'],
    versions: [['StarVector 1B im2svg', '2025-01'], ['StarVector 8B im2svg', '2025-01'], ['Обновление весов и кода', '2025-03']],
    hf: 'https://huggingface.co/starvector/starvector-8b-im2svg',
    github: 'https://github.com/joanrod/star-vector',
    alternatives: ['omnisvg', 'greenmap-blueprint', 'florence-2'],
    source: 'https://huggingface.co/starvector/starvector-8b-im2svg',
    verified: true,
    en: {
      summary: 'It turns a raster image into SVG code: instead of tracing pixels the model writes vector commands, so lines and symbols stay editable. It simplifies complex drawings, so the result needs a visual check.',
      tasks: ['Vectorising diagrams, symbols and logos from raster images', 'Turning scans of simple drawings into editable vectors', 'Recovering icons and pictograms from images', 'Preparing graphics for printing and cutting'],
      where: ['Design and media production', 'Marketing and branding', 'Interface development', 'Production and cutting preparation'],
      license: 'Apache 2.0',
      developer: 'ServiceNow Research, Mila and ETS Montreal',
      country: 'Canada',
      sizes: '1B and 8B',
    },
  },
  {
    id: 'omnisvg',
    name: 'OmniSVG',
    developer: 'Университет Фудань и StepFun', country: 'Китай',
    modality: ['cad', 'vlm', 'image'],
    first: '2025-07', latest: '2026-03',
    sizes: '3B – 8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['media', 'marketing', 'dev', 'manufacturing'],
    ollama: false,
    cpu: false,
    quant: ['gguf'],
    summary: 'Семейство моделей, которые делают SVG и по картинке, и по текстовому описанию — от простой иконки до подробной иллюстрации. Для точных чертежей результат надо сверять с оригиналом.',
    tasks: ['Векторизация картинок и знаков в SVG', 'Создание иконок и пиктограмм по текстовому описанию', 'Подготовка векторной графики для сайта и печати', 'Быстрые варианты условных обозначений для схем'],
    where: ['Дизайн и медиапродакшн', 'Маркетинг и брендинг', 'Разработка интерфейсов', 'Подготовка производства и раскроя'],
    versions: [['OmniSVG на Qwen2.5-VL-3B', '2025-07'], ['OmniSVG 1.1 4B и 8B', '2025-12'], ['Обновление весов 1.1', '2026-03']],
    hf: 'https://huggingface.co/OmniSVG/OmniSVG1.1_8B',
    github: 'https://github.com/OmniSVG/OmniSVG',
    alternatives: ['starvector', 'greenmap-blueprint', 'qwen-vl'],
    source: 'https://huggingface.co/OmniSVG/OmniSVG1.1_8B',
    verified: true,
    en: {
      summary: 'A family of models that produce SVG both from an image and from a text description, from a simple icon to a detailed illustration. For precise drawings the result has to be checked against the original.',
      tasks: ['Vectorising images and symbols into SVG', 'Creating icons and pictograms from a text description', 'Preparing vector graphics for web and print', 'Quick options for symbols used on diagrams'],
      where: ['Design and media production', 'Marketing and branding', 'Interface development', 'Production and cutting preparation'],
      license: 'Apache 2.0',
      developer: 'Fudan University and StepFun',
      country: 'China',
    },
  },
  // ---------- СХЕМЫ, БЛОК-СХЕМЫ И ГРАФИКИ ----------
  {
    id: 'qzhou-flowchart',
    name: 'QZhou-Flowchart-VL',
    developer: 'Kingsoft', country: 'Китай',
    modality: ['cad', 'vlm'],
    first: '2025-11', latest: '2025-11',
    sizes: '32B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu', 'multi'],
    ru: 'no',
    industries: ['docs', 'dev', 'manufacturing', 'education'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Читает блок-схему с картинки и сначала выписывает её структуру в JSON — блоки, связи и условия ветвления, а потом уже отвечает на вопрос по схеме. Разбор нужно сверять с оригиналом.',
    tasks: ['Перевод блок-схемы с картинки в структуру JSON', 'Ответы на вопросы по схеме процесса', 'Оцифровка регламентов и схем из презентаций', 'Сверка нарисованного процесса с описанием'],
    where: ['Документооборот и регламенты', 'Разработка и аналитика процессов', 'Производство и технологические карты', 'Обучение персонала'],
    versions: [['QZhou-Flowchart-VL-32B', '2025-11']],
    hf: 'https://huggingface.co/Kingsoft-LLM/QZhou-Flowchart-VL-32B',
    github: null,
    alternatives: ['matcha-deplot', 'qwen-vl', 'internvl'],
    source: 'https://huggingface.co/Kingsoft-LLM/QZhou-Flowchart-VL-32B',
    verified: true,
    en: {
      summary: 'It reads a flowchart from an image and first writes out its structure as JSON - blocks, links and branching conditions - and only then answers a question about the chart. The parse still has to be checked against the original.',
      tasks: ['Converting a flowchart image into a JSON structure', 'Answering questions about a process diagram', 'Digitising procedures and diagrams from presentations', 'Comparing a drawn process against its written description'],
      where: ['Document workflows and internal procedures', 'Development and process analysis', 'Manufacturing and process sheets', 'Staff training'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'matcha-deplot',
    name: 'MatCha и DePlot',
    developer: 'Google Research', country: 'США',
    modality: ['cad', 'vlm', 'ocr'],
    first: '2023-04', latest: '2023-07',
    sizes: '282M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['docs', 'finance', 'media', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Небольшие модели, которые превращают картинку графика или диаграммы в таблицу с числами и отвечают на вопросы по ней. Цифры с картинки восстанавливаются приблизительно, итог надо сверять.',
    tasks: ['Перевод графика из отчёта или PDF в таблицу', 'Вопросы по диаграмме на естественном языке', 'Короткое текстовое описание графика', 'Оцифровка диаграмм из старых документов'],
    where: ['Документооборот и отчётность', 'Финансовая аналитика', 'Медиа и подготовка материалов', 'Исследования'],
    versions: [['MatCha base и MatCha ChartQA', '2023-04'], ['DePlot — график в таблицу', '2023-04'], ['MatCha PlotQA и chart2text', '2023-04'], ['Обновление карточек и весов', '2023-07']],
    hf: 'https://huggingface.co/google/deplot',
    github: null,
    alternatives: ['qzhou-flowchart', 'docling', 'nougat'],
    source: 'https://huggingface.co/google/deplot',
    verified: true,
    en: {
      summary: 'Small models that turn an image of a chart or diagram into a table of numbers and answer questions about it. Values read off an image are approximate, so the result has to be checked.',
      tasks: ['Turning a chart from a report or PDF into a table', 'Natural-language questions about a diagram', 'A short text description of a chart', 'Digitising diagrams from old documents'],
      where: ['Document workflows and reporting', 'Financial analysis', 'Media and content preparation', 'Research'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
];
