// AuK (Tencent), Ternary Bonsai 2 (Prism ML), PII-Tracer (Perplexity). Факты сверены по Hugging Face на 01.10.2026.
module.exports = [
  {
    id: 'auk',
    name: 'AuK',
    developer: 'Tencent Hunyuan', country: 'Китай',
    modality: ['tts', 'voice'],
    first: '2026-09', latest: '2026-09',
    sizes: '1,5B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['media', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Одна открытая модель на все задачи с речью: синтез и клонирование голоса, правка слов и интонации в готовой записи, шумоподавление, отделение вокала. Команды пишутся обычным текстом.',
    tasks: ['озвучка текста и клонирование голоса по образцу', 'правка слов и интонации без перезаписи фразы', 'шумоподавление и очистка записи', 'отделение голоса или вокала от фона'],
    where: ['медиа и видеопродакшн', 'маркетинг и контент', 'обучение и озвучка курсов'],
    versions: [['AuK', '2026-09'], ['AuK-Flash (4 шага вместо 32)', '2026-09']],
    hf: 'https://huggingface.co/tencent/AuK',
    github: 'https://github.com/Tencent-Hunyuan/AuK',
    alternatives: ['f5-tts', 'fish-speech', 'cosyvoice'],
    source: 'https://huggingface.co/tencent/AuK',
    verified: true,
  },
  {
    id: 'bonsai',
    name: 'Ternary Bonsai',
    developer: 'Prism ML', country: 'США',
    modality: ['text', 'vlm'],
    first: '2026-09', latest: '2026-09',
    sizes: '27B (1,72 бита на вес)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'unknown',
    industries: ['dev', 'docs', 'support'],
    ollama: false,
    cpu: false,
    summary: 'Сжатая Qwen3.8-27B: весит 5,9 ГБ вместо 54 ГБ и сохраняет около 98% качества исходной. Контекст 262 тысячи токенов, понимает картинки и вызывает инструменты. Для запуска нужен форк llama.cpp от авторов.',
    tasks: ['агент для работы с кодом на своём компьютере', 'разбор документов без отправки в облако', 'вызов инструментов и автоматизация процессов', 'ответы по длинным документам'],
    where: ['разработка и ИТ', 'документооборот', 'внутренние ассистенты без облака'],
    versions: [['Ternary Bonsai 2 27B (GGUF и MLX)', '2026-09']],
    hf: 'https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf',
    github: null,
    alternatives: ['qwen', 'gemma', 'lfm'],
    source: 'https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf',
    verified: true,
  },
  {
    id: 'pii-tracer',
    name: 'PII-Tracer',
    developer: 'Perplexity', country: 'США',
    modality: ['safety', 'nlp'],
    first: '2026-08', latest: '2026-08',
    sizes: '0,6B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['security', 'legal', 'support'],
    ollama: false,
    cpu: true,
    summary: 'Маленькая открытая модель, которая находит в тексте персональные данные (имена, телефоны, адреса, почту, номера счетов, секреты) и позволяет замаскировать их до отправки в облако. Контекст 4096 токенов.',
    tasks: ['маскирование персональных данных в диалогах', 'проверка текста перед отправкой во внешнюю нейросеть', 'поиск утечек секретов и ключей', 'подготовка данных для обучения без персональных сведений'],
    where: ['информационная безопасность', 'юристы и комплаенс', 'поддержка клиентов'],
    versions: [['PII-Tracer 0.6B (в том числе GGUF, MLX, vLLM)', '2026-08']],
    hf: 'https://huggingface.co/perplexity-ai/PII-Tracer',
    github: null,
    alternatives: ['gliner-pii', 'piiranha'],
    source: 'https://huggingface.co/perplexity-ai/PII-Tracer',
    verified: true,
  },
];
