// Волна 8, группа «Антифрод по операциям и транзакциям»: скоринг операций, поиск связанных схем на графах,
// разбор журналов действий, распознавание мошеннических сообщений и документов по отмыванию.
// Факты сверены по Hugging Face / GitHub на 23.09.2026.
module.exports = [
  // ---------- ГОТОВЫЕ МОДЕЛИ ДЛЯ КОНВЕЙЕРА АНТИФРОДА ----------
  {
    id: 'morpheus',
    name: 'NVIDIA Morpheus (набор моделей)',
    developer: 'NVIDIA', country: 'США',
    modality: ['cyber', 'finance', 'tabular'],
    first: '2022-04', latest: '2025-06',
    sizes: 'от нескольких мегабайт (модели на деревьях) до классификаторов на базе BERT',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['finance', 'security', 'dev'],
    ollama: false,
    cpu: false,
    quant: [],
    summary: 'Открытый набор NVIDIA: граф операций по картам плюс классификатор, профиль обычного поведения пользователя, разбор логов и поиск первопричины. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Подсветка подозрительных операций по карте с учётом связей между участниками', 'Отслеживание отклонений в поведении учётной записи от привычного', 'Разбор журналов и поиск первопричины инцидента', 'Проверка писем на признаки мошеннической рассылки'],
    where: ['Банки и платёжные сервисы', 'Информационная безопасность', 'Крупные ИТ-подразделения'],
    versions: [['Morpheus 22.04, первый публичный выпуск', '2022-04'], ['Morpheus 23.03', '2023-03'], ['Morpheus 24.10', '2024-10'], ['Morpheus 25.02', '2025-02'], ['Morpheus 25.06', '2025-06']],
    hf: null,
    github: 'https://github.com/nv-morpheus/Morpheus',
    alternatives: ['anomalygfm', 'revtrack', 'foundation-sec'],
    source: 'https://github.com/nv-morpheus/Morpheus/tree/branch-25.10/models',
    verified: true,
    en: {
      summary: 'An open NVIDIA bundle: a card-transaction graph plus a classifier, a profile of normal user behaviour, log parsing and root-cause search. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Highlighting suspicious card operations taking participant links into account', 'Tracking deviations of an account from its usual behaviour', 'Parsing logs and finding the root cause of an incident', 'Checking emails for signs of a fraudulent campaign'],
      where: ['Banks and payment services', 'Information security', 'Large IT departments'],
      license: 'Apache 2.0',
      country: 'USA',
      sizes: 'from a few megabytes (tree-based models) up to BERT-based classifiers',
    },
  },
  // ---------- ГРАФЫ: СВЯЗАННЫЕ СХЕМЫ, ДРОПЫ, КОЛЬЦА ----------
  {
    id: 'anomalygfm',
    name: 'AnomalyGFM',
    developer: 'Лаборатория MaLA, Singapore Management University (совместно с University of Technology Sydney)', country: 'Сингапур',
    modality: ['finance', 'tabular'],
    first: '2024-11', latest: '2026-08',
    sizes: 'файл весов около 1,5 МБ',
    license: 'лицензия в репозитории не указана — уточняйте у авторов',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['finance', 'security', 'science'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Предобученная модель для поиска аномальных узлов в графе связей: она размечает подозрительные вершины на новом графе без обучения на нём. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Поиск связанных между собой подозрительных счетов и контрагентов', 'Подсветка нетипичных участников в графе платежей', 'Проверка гипотез о кольцевых схемах и цепочках посредников'],
    where: ['Банки и платёжные сервисы', 'Маркетплейсы и площадки объявлений', 'Служба внутреннего контроля'],
    versions: [['Код и веса на GitHub', '2024-11'], ['Препринт AnomalyGFM', '2025-02'], ['Обновление репозитория', '2026-08']],
    hf: null,
    github: 'https://github.com/mala-lab/AnomalyGFM',
    alternatives: ['revtrack', 'morpheus', 'tabpfn'],
    source: 'https://github.com/mala-lab/AnomalyGFM',
    verified: true,
    en: {
      summary: 'A pretrained model that finds anomalous nodes in a relationship graph and marks suspicious vertices on a new graph without training on it. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Finding suspicious accounts and counterparties linked to each other', 'Highlighting atypical participants in a payment graph', 'Testing hypotheses about ring schemes and chains of intermediaries'],
      where: ['Banks and payment services', 'Marketplaces and classifieds platforms', 'Internal control departments'],
      license: 'no license stated in the repository — check with the authors',
      developer: 'MaLA Lab, Singapore Management University (with University of Technology Sydney)',
      country: 'Singapore',
      sizes: 'weights file about 1.5 MB',
    },
  },
  {
    id: 'revtrack',
    name: 'RevTrack / RevClassify',
    developer: 'MIT и MIT-IBM Watson AI Lab', country: 'США',
    modality: ['finance', 'tabular'],
    first: '2024-10', latest: '2024-10',
    sizes: 'чекпойнты от 0,1 до 45 МБ',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'na',
    industries: ['finance', 'security'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Модели для разметки подозрительных цепочек переводов: смотрят, кто отправил деньги в начале цепочки и кто получил их в конце. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Классификация цепочек переводов как обычных или требующих проверки', 'Поиск новых подозрительных цепочек в большом потоке операций', 'Подготовка материалов для службы комплаенса'],
    where: ['Банки и платёжные сервисы', 'Криптообменники и финтех', 'Комплаенс и внутренний контроль'],
    versions: [['RevTrack, код и чекпойнты (ICAIF 2024)', '2024-10']],
    hf: null,
    github: 'https://github.com/MITIBMxGraph/RevTrack',
    alternatives: ['anomalygfm', 'morpheus', 'kronos'],
    source: 'https://github.com/MITIBMxGraph/RevTrack',
    verified: true,
    en: {
      summary: 'Models that label suspicious chains of transfers by looking at who sent the money at the start of the chain and who received it at the end. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Classifying transfer chains as ordinary or needing review', 'Finding new suspicious chains in a large flow of operations', 'Preparing material for the compliance team'],
      where: ['Banks and payment services', 'Crypto exchanges and fintech', 'Compliance and internal control'],
      license: 'MIT',
      developer: 'MIT and MIT-IBM Watson AI Lab',
      country: 'USA',
      sizes: 'checkpoints from 0.1 to 45 MB',
    },
  },
  // ---------- МОШЕННИЧЕСКИЕ СООБЩЕНИЯ И ЗАЯВКИ ----------
  {
    id: 'flowx-scamguard',
    name: 'FlowX ScamGuard',
    developer: 'FlowX.AI', country: 'США и Румыния',
    modality: ['nlp', 'finance'],
    first: '2026-07', latest: '2026-09',
    sizes: '0.6B – 1.7B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['finance', 'security', 'support'],
    ollama: false,
    cpu: true,
    quant: ['gguf', 'mlx'],
    summary: 'Небольшие модели банковской компании, которые разбирают текст сообщения в SMS, письме или чате и объясняют, какой приём мошенника в нём использован. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Разметка входящих сообщений с признаками обмана', 'Объяснение, по какой фразе сработала подсветка', 'Фильтрация писем и сообщений до передачи оператору'],
    where: ['Банки и платёжные сервисы', 'Поддержка клиентов', 'Информационная безопасность'],
    versions: [['scam-guard-qwen06b и scam-guard-qwen17b', '2026-07'], ['Обновление карточек и сборок', '2026-09']],
    hf: 'https://huggingface.co/flowxai/scam-guard-qwen17b',
    github: null,
    alternatives: ['scamllm', 'phishing-distilbert', 'flowx-openner'],
    source: 'https://huggingface.co/flowxai/scam-guard-qwen17b',
    verified: true,
    en: {
      summary: 'Small models from a banking software company that read the text of an SMS, email or chat message and explain which scam tactic it uses. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Flagging incoming messages that show signs of deception', 'Explaining which phrase triggered the flag', 'Filtering emails and messages before they reach an operator'],
      where: ['Banks and payment services', 'Customer support', 'Information security'],
      license: 'Apache 2.0',
      country: 'USA and Romania',
    },
  },
  {
    id: 'flowx-openner',
    name: 'FlowX OpenNER',
    developer: 'FlowX.AI', country: 'США и Румыния',
    modality: ['nlp', 'finance'],
    first: '2026-07', latest: '2026-09',
    sizes: 'около 150M (на базе ModernBERT-base)',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['finance', 'legal', 'docs'],
    ollama: false,
    cpu: true,
    quant: ['int8'],
    summary: 'Семейство небольших моделей, которые вытаскивают из банковских и страховых текстов суммы, стороны сделки, юрисдикции, счета и упоминания из санкционных проверок. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Извлечение сумм, сторон и юрисдикций из описаний операций', 'Разбор материалов проверки клиента и санкционных списков', 'Разметка номеров счетов и реквизитов в документах', 'Подготовка структурированных карточек по заявкам на выплату'],
    where: ['Банки и платёжные сервисы', 'Страхование', 'Комплаенс и документооборот'],
    versions: [['cee-pii, первая модель семейства', '2026-07'], ['Банковские модели: amlnarrate, sanctionscreen, kycextract, txnclassify, counterpartylink', '2026-07'], ['Обновление карточек', '2026-09']],
    hf: 'https://huggingface.co/flowxai/amlnarrate',
    github: null,
    alternatives: ['gliner', 'nuextract', 'flowx-scamguard'],
    source: 'https://huggingface.co/flowxai/amlnarrate',
    verified: true,
    en: {
      summary: 'A family of small models that pull amounts, deal parties, jurisdictions, accounts and sanctions-screening mentions out of banking and insurance texts. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Extracting amounts, parties and jurisdictions from operation descriptions', 'Parsing customer due diligence material and sanctions lists', 'Marking account numbers and payment details in documents', 'Preparing structured cards for payout claims'],
      where: ['Banks and payment services', 'Insurance', 'Compliance and document workflow'],
      license: 'Apache 2.0',
      country: 'USA and Romania',
      sizes: 'about 150M (based on ModernBERT-base)',
    },
  },
  {
    id: 'scamllm',
    name: 'ScamLLM',
    developer: 'University of Texas at Arlington', country: 'США',
    modality: ['nlp', 'cyber'],
    first: '2023-12', latest: '2025-08',
    sizes: 'около 125M (на базе RoBERTa-base)',
    license: 'на карточке модели указано unknown — лицензия не определена',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'no',
    industries: ['security', 'finance'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Классификатор из исследования IEEE S&P: отделяет обычные запросы к языковой модели от запросов, которыми заказывают текст и страницу для обмана людей. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Разметка запросов к ассистенту, похожих на подготовку обмана', 'Проверка текстов рассылок перед отправкой', 'Наполнение внутренних правил фильтрации примерами'],
    where: ['Информационная безопасность', 'Банки и платёжные сервисы', 'Площадки с пользовательским контентом'],
    versions: [['ScamLLM', '2023-12'], ['Обновление репозитория', '2025-08']],
    hf: 'https://huggingface.co/phishbot/ScamLLM',
    github: null,
    alternatives: ['phishing-distilbert', 'flowx-scamguard', 'aprielguard'],
    source: 'https://huggingface.co/phishbot/ScamLLM',
    verified: true,
    en: {
      summary: 'A classifier from an IEEE S&P study: it separates ordinary requests to a language model from requests that order text and a page meant to deceive people. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Flagging assistant prompts that look like preparation for deception', 'Checking campaign texts before they are sent', 'Filling internal filtering rules with examples'],
      where: ['Information security', 'Banks and payment services', 'Platforms with user-generated content'],
      license: 'the model card states unknown — the license is undefined',
      country: 'USA',
      sizes: 'about 125M (based on RoBERTa-base)',
    },
  },
  // ---------- ЖУРНАЛЫ ОПЕРАЦИЙ И ДЕЙСТВИЙ ПОЛЬЗОВАТЕЛЕЙ ----------
  {
    id: 'biglog',
    name: 'Biglog',
    developer: 'Huawei и Университет науки и технологий Китая (проект LogAIBox)', country: 'Китай',
    modality: ['cyber', 'nlp'],
    first: '2023-04', latest: '2024-09',
    sizes: 'около 110M (архитектура BERT-base)',
    license: 'на карточке модели лицензия не указана — уточняйте у авторов',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['dev', 'security', 'manufacturing'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Модель, предобученная на большом объёме журналов разных систем: превращает строку лога в вектор, поверх которого дообучают поиск сбоев и нетипичных записей. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Поиск нетипичных записей в журналах операций', 'Группировка однотипных сообщений о сбоях', 'Подготовка признаков для собственной модели мониторинга'],
    where: ['ИТ-подразделения и эксплуатация', 'Информационная безопасность', 'Производство и телеком'],
    versions: [['Код Biglog (IWQoS 2023)', '2023-04'], ['Веса на Hugging Face', '2024-09']],
    hf: 'https://huggingface.co/thatbbob/BigLog',
    github: 'https://github.com/LogAIBox/BigLog',
    alternatives: ['logprecis', 'morpheus', 'modernbert'],
    source: 'https://huggingface.co/thatbbob/BigLog',
    verified: true,
    en: {
      summary: 'A model pretrained on a large volume of logs from different systems: it turns a log line into a vector on top of which failure and outlier detection is fine-tuned. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Finding unusual entries in operation logs', 'Grouping similar failure messages', 'Preparing features for an in-house monitoring model'],
      where: ['IT and operations teams', 'Information security', 'Manufacturing and telecom'],
      license: 'no license is stated on the model card — check with the authors',
      developer: 'Huawei and University of Science and Technology of China (LogAIBox project)',
      country: 'China',
      sizes: 'about 110M (BERT-base architecture)',
    },
  },
  {
    id: 'logprecis',
    name: 'LogPrecis / SecureShellBert',
    developer: 'SmartData@PoliTO, Politecnico di Torino', country: 'Италия',
    modality: ['cyber', 'nlp'],
    first: '2023-07', latest: '2024-03',
    sizes: 'около 125M (на базе CodeBERT)',
    license: 'на карточке модели лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['security', 'dev'],
    ollama: false,
    cpu: true,
    quant: [],
    summary: 'Пара моделей итальянского университета: разбирают записанную сессию команд и размечают, какие куски относятся к разведке, закреплению и другим шагам атакующего. Решение по спорной операции принимает человек, автоматическая блокировка без проверки недопустима.',
    tasks: ['Разметка журналов команд по этапам действий', 'Группировка похожих сессий для разбора инцидентов', 'Подготовка признаков для мониторинга серверов'],
    where: ['Информационная безопасность', 'ИТ-подразделения и эксплуатация', 'Исследования и обучение'],
    versions: [['Код LogPrecis на GitHub', '2023-07'], ['SecureShellBert и LogPrecis на Hugging Face', '2024-03']],
    hf: 'https://huggingface.co/SmartDataPolito/logprecis',
    github: 'https://github.com/SmartData-Polito/logprecis',
    alternatives: ['biglog', 'securebert', 'morpheus'],
    source: 'https://huggingface.co/SmartDataPolito/logprecis',
    verified: true,
    en: {
      summary: 'A pair of models from an Italian university: they read a recorded command session and mark which parts belong to reconnaissance, persistence and other attacker steps. A human makes the decision on a disputed operation; automatic blocking without review is not acceptable.',
      tasks: ['Labelling command logs by stage of activity', 'Grouping similar sessions for incident review', 'Preparing features for server monitoring'],
      where: ['Information security', 'IT and operations teams', 'Research and training'],
      license: 'no license is stated on the model card — check with the developer',
      country: 'Italy',
      sizes: 'about 125M (based on CodeBERT)',
    },
  },
];
