// Волна 8, группа «Языки народов России»: распознавание и синтез речи, перевод, языковые модели
// и энкодеры для татарского, башкирского, якутского, бурятского, чувашского, удмуртского, марийского,
// эрзянского, тувинского, калмыцкого, осетинского, ингушского, карельского и других языков.
// Факты сверены по Hugging Face на 23.09.2026.
module.exports = [
  // ---------- БАЗОВЫЕ МНОГОЯЗЫЧНЫЕ МОДЕЛИ, КОТОРЫЕ ЗАКРЫВАЮТ СРАЗУ МНОГО ЯЗЫКОВ ----------
  {
    id: 'mms',
    name: 'MMS (Massively Multilingual Speech)',
    developer: 'Meta AI', country: 'США',
    modality: ['asr', 'tts'],
    first: '2023-05', latest: '2023-09',
    sizes: '300M – 1B',
    license: 'CC-BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['media', 'gov', 'education', 'support'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Речевые модели Meta более чем на тысячу языков. В списке поддержки есть башкирский, татарский, чувашский, якутский, осетинский, чеченский, аварский, удмуртский, марийский, эрзянский, мокшанский, калмыцкий и карельский. Качество по языкам очень разное, проверять надо на своих записях.',
    tasks: ['Расшифровка аудио и видео на редких языках', 'Озвучивание текста на национальном языке', 'Определение, на каком языке звучит запись', 'Основа для дообучения под один конкретный язык'],
    where: ['Медиа, архивы и библиотеки', 'Государственные и муниципальные учреждения', 'Образование и сохранение языков'],
    versions: [['MMS-1B-all, распознавание речи', '2023-05'], ['MMS-LID, определение языка записи', '2023-06'], ['MMS-TTS, отдельные модели синтеза по языкам', '2023-09']],
    hf: 'https://huggingface.co/facebook/mms-1b-all',
    github: 'https://github.com/facebookresearch/fairseq/tree/main/examples/mms',
    alternatives: ['whisper', 'omnilingual-asr', 'seamless'],
    source: 'https://huggingface.co/facebook/mms-1b-all',
    verified: true,
    en: {
      summary: 'Meta speech models covering more than a thousand languages. The supported list includes Bashkir, Tatar, Chuvash, Sakha, Ossetian, Chechen, Avar, Udmurt, Mari, Erzya, Moksha, Kalmyk and Karelian. Quality varies a lot by language, so test it on your own recordings.',
      tasks: ['Transcribing audio and video in rare languages', 'Reading text aloud in a national language', 'Detecting which language a recording is in', 'A base for fine-tuning to one specific language'],
      where: ['Media, archives and libraries', 'Government and municipal bodies', 'Education and language preservation'],
      license: 'CC-BY-NC 4.0 — non-commercial use only',
      country: 'USA',
    },
  },
  {
    id: 'glotlid',
    name: 'GlotLID',
    developer: 'CIS, Университет Людвига-Максимилиана в Мюнхене', country: 'Германия',
    modality: ['nlp'],
    first: '2023-10', latest: '2024-04',
    sizes: 'модель FastText, число параметров на карточке не указано',
    license: 'Apache 2.0 с дополнительными уведомлениями (файл LICENSE в репозитории)',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'media', 'science', 'support'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Определяет, на каком языке написан текст: в третьей версии более двух тысяч меток, включая татарский, башкирский, чувашский, удмуртский, марийский, эрзянский, коми и другие языки народов России.',
    tasks: ['Разбор смешанных архивов текстов по языкам', 'Отсев мусора и чужих языков перед обучением моделей', 'Маршрутизация обращений на нужного оператора или модель', 'Проверка разметки языковых корпусов'],
    where: ['Медиа и издательства', 'Наука и языковые проекты', 'Поддержка клиентов'],
    versions: [['GlotLID v1', '2023-10'], ['GlotLID v3, более двух тысяч меток языков', '2024-04']],
    hf: 'https://huggingface.co/cis-lmu/glotlid',
    github: 'https://github.com/cisnlp/GlotLID',
    alternatives: ['mmbert', 'xlm-roberta', 'bge-m3'],
    source: 'https://huggingface.co/cis-lmu/glotlid',
    verified: true,
    en: {
      summary: 'Detects which language a text is written in: the third version covers more than two thousand labels, including Tatar, Bashkir, Chuvash, Udmurt, Mari, Erzya, Komi and other languages of Russia.',
      tasks: ['Sorting mixed text archives by language', 'Filtering out noise and foreign languages before training', 'Routing requests to the right operator or model', 'Checking the labelling of language corpora'],
      where: ['Media and publishing', 'Research and language projects', 'Customer support'],
      license: 'Apache 2.0 with additional notices (LICENSE file in the repository)',
      developer: 'CIS, LMU Munich',
      country: 'Germany',
      sizes: 'a FastText model; parameter count is not stated on the model card',
    },
  },
  {
    id: 'mmbert',
    name: 'mmBERT',
    developer: 'Университет Джонса Хопкинса (JHU CLSP)', country: 'США',
    modality: ['nlp', 'embed'],
    first: '2025-07', latest: '2025-08',
    sizes: '140M и 307M',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'support', 'science', 'media'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['gguf'],
    summary: 'Многоязычный энкодер, обученный более чем на 1800 языках. В список входят татарский, башкирский, чувашский, удмуртский, бурятский, коми, ингушский и другие языки народов России. Основа для классификаторов и поиска по таким текстам.',
    tasks: ['Классификация обращений и документов на национальных языках', 'Поиск по смыслу в текстах на редких языках', 'Извлечение имён, дат и названий из текста', 'Основа для дообучения под свою задачу'],
    where: ['Документооборот и архивы', 'Поддержка клиентов', 'Наука и языковые проекты'],
    versions: [['mmBERT-base, 307M', '2025-07'], ['mmBERT-small, 140M', '2025-08']],
    hf: 'https://huggingface.co/jhu-clsp/mmBERT-base',
    github: 'https://github.com/jhu-clsp/mmBERT',
    alternatives: ['xlm-roberta', 'modernbert', 'glotlid'],
    source: 'https://huggingface.co/jhu-clsp/mmBERT-base',
    verified: true,
    en: {
      summary: 'A multilingual encoder trained on more than 1800 languages. The list includes Tatar, Bashkir, Chuvash, Udmurt, Buryat, Komi, Ingush and other languages of Russia. A base for classifiers and search over such texts.',
      tasks: ['Classifying requests and documents in national languages', 'Semantic search over texts in rare languages', 'Extracting names, dates and titles from text', 'A base for fine-tuning to your own task'],
      where: ['Document flow and archives', 'Customer support', 'Research and language projects'],
      license: 'MIT',
      developer: 'Johns Hopkins University (JHU CLSP)',
      country: 'USA',
      sizes: '140M and 307M',
    },
  },
  // ---------- РАСПОЗНАВАНИЕ РЕЧИ ----------
  {
    id: 'aigizk-asr',
    name: 'Распознавание речи для башкирского, татарского и марийского (AigizK)',
    developer: 'Айгиз Кунафин (AigizK), участник сообщества SLONE', country: 'Россия',
    modality: ['asr'],
    first: '2022-03', latest: '2026-07',
    sizes: 'от 220M до 1B в разных моделях',
    license: 'разная у моделей: Apache 2.0 и MIT у большинства, у модели для татарского CC-BY-NC 4.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['media', 'gov', 'education', 'support'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['int8'],
    summary: 'Многолетняя работа одного энтузиаста вокруг башкирского Common Voice: дообучения Whisper, wav2vec2, w2v-BERT и GigaAM под башкирский, татарский и марийский языки. Качество у моделей разное, проверять надо на своих записях.',
    tasks: ['Расшифровка звонков и совещаний на башкирском и татарском', 'Субтитры к видео и радиоэфирам', 'Перевод архивных записей в текст', 'Голосовой ввод в приложениях на национальном языке'],
    where: ['Медиа и вещание', 'Государственные и муниципальные учреждения', 'Образование и культура'],
    versions: [['wav2vec2 XLS-R для башкирского (Common Voice 7)', '2022-03'], ['Whisper small для башкирского', '2022-12'], ['MMS-1B для татарского, версия 2', '2024-01'], ['w2v-BERT 2.0 для марийского (Common Voice 17)', '2024-05'], ['GigaAM Bashkir CV25 и сборка ONNX', '2026-07']],
    hf: 'https://huggingface.co/AigizK',
    github: null,
    alternatives: ['whisper', 'gigaam', 'vosk'],
    source: 'https://huggingface.co/AigizK/GigaAM-Bashkir-CV25',
    verified: true,
    en: {
      summary: 'Years of work by one enthusiast around the Bashkir Common Voice project: Whisper, wav2vec2, w2v-BERT and GigaAM fine-tuned for Bashkir, Tatar and Mari. Quality differs between models, so test them on your own recordings.',
      tasks: ['Transcribing calls and meetings in Bashkir and Tatar', 'Subtitles for video and radio broadcasts', 'Turning archive recordings into text', 'Voice input in apps in a national language'],
      where: ['Media and broadcasting', 'Government and municipal bodies', 'Education and culture'],
      license: 'varies by model: mostly Apache 2.0 and MIT, CC-BY-NC 4.0 for the Tatar model',
      developer: 'Aigiz Kunafin (AigizK), member of the SLONE community',
      country: 'Russia',
      sizes: 'from 220M to 1B across the different models',
    },
  },
  {
    id: 'karelian-asr',
    name: 'Распознавание карельской речи (Mihaj)',
    developer: 'Mihaj Dolgushin', country: 'не раскрыта',
    modality: ['asr'],
    first: '2024-02', latest: '2025-11',
    sizes: 'от 300M до 1B в разных моделях',
    license: 'на карточках моделей лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['media', 'education', 'science', 'gov'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Два десятка дообучений Whisper, wav2vec2 и WavLM под карельский язык, в том числе под записи, где человек переходит с карельского на русский. Карточки моделей пустые, качество надо проверять на своих записях.',
    tasks: ['Расшифровка полевых и архивных записей на карельском', 'Субтитры к материалам на карельском языке', 'Работа с записями, где смешаны карельский и русский', 'Основа для дообучения под свой диалект'],
    where: ['Наука и языковые проекты', 'Музеи, архивы и библиотеки', 'Образование и культура'],
    versions: [['wav2vec2 XLS-R для карельского', '2024-02'], ['Whisper medium, финский и карельский', '2024-04'], ['Distil-Whisper large-v2 для карельского', '2024-05'], ['Whisper large-v3-turbo для карельского', '2025-02'], ['wav2vec2-BERT для карельского с русским', '2025-11']],
    hf: 'https://huggingface.co/Mihaj',
    github: null,
    alternatives: ['whisper', 'mms', 'aigizk-asr'],
    source: 'https://huggingface.co/Mihaj/wav2vec2-bert-karelian-cs-w-rus-full-ft',
    verified: true,
    en: {
      summary: 'About two dozen Whisper, wav2vec2 and WavLM fine-tunes for Karelian, including recordings where the speaker switches from Karelian to Russian. The model cards are empty, so quality must be checked on your own recordings.',
      tasks: ['Transcribing field and archive recordings in Karelian', 'Subtitles for Karelian-language material', 'Handling recordings that mix Karelian and Russian', 'A base for fine-tuning to your own dialect'],
      where: ['Research and language projects', 'Museums, archives and libraries', 'Education and culture'],
      license: 'no license is stated on the model cards — check with the developer',
      country: 'not disclosed',
      sizes: 'from 300M to 1B across the different models',
    },
  },
  // ---------- СИНТЕЗ РЕЧИ ----------
  {
    id: 'f5-tts-chuvash',
    name: 'F5-TTS для чувашского языка',
    developer: 'Misha Yakovlev (Misha24-10)', country: 'не раскрыта',
    modality: ['tts', 'voice'],
    first: '2025-06', latest: '2025-06',
    sizes: 'размер в параметрах на карточке не указан',
    license: 'CC-BY-NC 4.0 — только некоммерческое использование',
    commercial: 'no',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['media', 'education', 'marketing'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Синтез чувашской речи: дообучение F5-TTS поверх русской версии на 24 часах записей Common Voice. Умеет повторять голос из примера — использовать только с согласия владельца голоса. Автор называет это экспериментом, качество надо проверять на своих текстах.',
    tasks: ['Озвучивание текстов на чувашском языке', 'Голосовые подсказки и объявления', 'Аудиоверсии материалов для обучения', 'Опыты по переносу синтеза речи на близкий язык'],
    where: ['Медиа и аудиопродакшн', 'Образование и культура', 'Языковые проекты'],
    versions: [['F5-TTS_CHUVASH', '2025-06']],
    hf: 'https://huggingface.co/Misha24-10/F5-TTS_CHUVASH',
    github: null,
    alternatives: ['f5-tts', 'xtts', 'piper'],
    source: 'https://huggingface.co/Misha24-10/F5-TTS_CHUVASH',
    verified: true,
    en: {
      summary: 'Chuvash speech synthesis: an F5-TTS fine-tune on top of the Russian version, trained on 24 hours of Common Voice recordings. It can copy a voice from a sample — only with the voice owner’s consent. The author calls it an experiment, so check quality on your own texts.',
      tasks: ['Reading Chuvash texts aloud', 'Voice prompts and announcements', 'Audio versions of learning material', 'Experiments in moving speech synthesis to a closely related language'],
      where: ['Media and audio production', 'Education and culture', 'Language projects'],
      license: 'CC-BY-NC 4.0 — non-commercial use only',
      country: 'not disclosed',
      sizes: 'parameter count is not stated on the model card',
    },
  },
  // ---------- МАШИННЫЙ ПЕРЕВОД ----------
  {
    id: 'slone-lowres',
    name: 'SLONE: перевод для языков народов России',
    developer: 'SLONE (David Dale, Айгиз Кунафин и другие)', country: 'не раскрыта',
    modality: ['translate', 'embed', 'nlp'],
    first: '2022-09', latest: '2026-07',
    sizes: '42M у компактных энкодеров, 620M – 758M у переводчиков',
    license: 'разная у моделей: CC-BY-NC 4.0 у части переводчиков, CC-BY-SA 4.0 и Apache 2.0 у остальных',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['gov', 'education', 'media', 'docs'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['int8'],
    summary: 'Сообщество, которое достраивает NLLB и mBART под малоресурсные языки. В моделях есть эрзянский, тувинский, башкирский, татарский, чувашский, бурятский, марийский, хакасский и карачаево-балкарский. Качество по языкам разное, проверять надо на своих текстах.',
    tasks: ['Перевод с русского на национальный язык и обратно', 'Подготовка двуязычных материалов и вывесок', 'Поиск соответствий в параллельных текстах', 'Основа для собственного переводчика под один язык'],
    where: ['Государственные и муниципальные учреждения', 'Образование и культура', 'Медиа и издательства'],
    versions: [['mBART-51 для эрзянского', '2022-09'], ['LaBSE для эрзянского, версия 2', '2023-11'], ['NLLB для пары русский — тувинский', '2023-10'], ['NLLB-210, двенадцать языков в одной модели', '2024-03'], ['NLLB с эрзянским, выпуск 2024 года', '2024-08']],
    hf: 'https://huggingface.co/slone',
    github: null,
    alternatives: ['nllb', 'madlad', 'mms'],
    source: 'https://huggingface.co/slone/nllb-210-v1',
    verified: true,
    en: {
      summary: 'A community that extends NLLB and mBART to low-resource languages. Its models cover Erzya, Tuvan, Bashkir, Tatar, Chuvash, Buryat, Mari, Khakas and Karachay-Balkar. Quality differs by language, so test it on your own texts.',
      tasks: ['Translating from Russian into a national language and back', 'Preparing bilingual materials and signage', 'Aligning parallel texts', 'A base for your own translator for a single language'],
      where: ['Government and municipal bodies', 'Education and culture', 'Media and publishing'],
      license: 'varies by model: CC-BY-NC 4.0 for some translators, CC-BY-SA 4.0 and Apache 2.0 for the rest',
      developer: 'SLONE (David Dale, Aigiz Kunafin and others)',
      country: 'not disclosed',
      sizes: '42M for the compact encoders, 620M – 758M for the translators',
    },
  },
  {
    id: 'tuvan-gemma',
    name: 'TuvanGemma',
    developer: 'Mergen Kungaa', country: 'не раскрыта',
    modality: ['translate', 'text'],
    first: '2026-09', latest: '2026-09',
    sizes: '4B и 12B',
    license: 'Gemma Terms of Use — модель производная от Gemma, условия надо прочитать до использования',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['gov', 'education', 'media', 'docs'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['gguf'],
    summary: 'Перевод русский — тувинский, работает на своём компьютере: готовые сборки GGUF, адаптер LoRA и отдельное приложение под Windows. Автор сам предупреждает, что имена, числа и важный текст надо перепроверять у носителя языка.',
    tasks: ['Перевод документов и объявлений на тувинский', 'Перевод тувинских текстов на русский', 'Черновой перевод без отправки данных наружу', 'Подготовка двуязычных материалов'],
    where: ['Государственные и муниципальные учреждения', 'Образование и культура', 'Медиа и издательства'],
    versions: [['TuvanGemma 4B', '2026-09'], ['TuvanGemma 12B и приложение под Windows', '2026-09']],
    hf: 'https://huggingface.co/kungaa/TuvanGemma',
    github: null,
    alternatives: ['nllb', 'slone-lowres', 'gemma'],
    source: 'https://huggingface.co/kungaa/TuvanGemma',
    verified: true,
    en: {
      summary: 'Russian to Tuvan translation that runs on your own machine: ready GGUF builds, a LoRA adapter and a standalone Windows app. The author warns that names, numbers and important text should be double-checked with a native speaker.',
      tasks: ['Translating documents and notices into Tuvan', 'Translating Tuvan texts into Russian', 'Draft translation without sending data outside', 'Preparing bilingual materials'],
      where: ['Government and municipal bodies', 'Education and culture', 'Media and publishing'],
      license: 'Gemma Terms of Use — a Gemma-derived model, read the terms before use',
      developer: 'Mergen Kungaa',
      country: 'not disclosed',
      sizes: '4B and 12B',
    },
  },
  // ---------- ЯЗЫКОВЫЕ МОДЕЛИ И ЦЕЛЫЕ ЯЗЫКОВЫЕ ПРОЕКТЫ ----------
  {
    id: 'lab-ii-sakha',
    name: 'Лаборатория ИИ СВФУ: якутский язык',
    developer: 'Лаборатория искусственного интеллекта Северо-Восточного федерального университета', country: 'Россия',
    modality: ['text', 'translate', 'embed', 'ocr'],
    first: '2025-06', latest: '2026-09',
    sizes: '1.1B – 27B',
    license: 'разная у моделей: Apache 2.0, MIT, CC-BY 4.0, Gemma Terms; у части моделей лицензия не указана',
    commercial: 'conditional',
    hardware: ['min', 'gpu', 'multi'],
    ru: 'yes',
    industries: ['education', 'gov', 'media', 'docs'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Самый полный набор моделей для якутского языка в одном месте: языковые модели разных размеров, перевод с русского и на русский, эмбеддинги и распознавание текста с изображений. Качество у моделей разное, проверять надо на своих данных.',
    tasks: ['Ответы и переписка на якутском языке', 'Перевод документов и материалов', 'Поиск по смыслу в якутских текстах', 'Распознавание якутского текста со сканов и фотографий'],
    where: ['Образование и наука', 'Государственные и муниципальные учреждения', 'Медиа и издательства'],
    versions: [['TinyLlama Sakha Instruct', '2025-06'], ['mT5 для перевода русский — якутский', '2025-06'], ['Aina 14B Instruct', '2025-10'], ['Qwen3 4B и Llama 3.2 для якутского', '2026-01'], ['Qwen3.5 27B для якутского', '2026-03'], ['TranslateGemma 12B для якутского', '2026-06'], ['Эмбеддинги sakha-embed-mmbert и распознавание текста sakha-ocr', '2026-09']],
    hf: 'https://huggingface.co/lab-ii',
    github: null,
    alternatives: ['qwen', 'mmbert', 'nllb'],
    source: 'https://huggingface.co/lab-ii/Qwen3.5-27B-sah',
    verified: true,
    en: {
      summary: 'The most complete set of models for the Sakha (Yakut) language in one place: language models of several sizes, translation to and from Russian, embeddings and text recognition from images. Quality varies, so test it on your own data.',
      tasks: ['Answering and writing in the Sakha language', 'Translating documents and materials', 'Semantic search over Sakha texts', 'Reading Sakha text from scans and photos'],
      where: ['Education and research', 'Government and municipal bodies', 'Media and publishing'],
      license: 'varies by model: Apache 2.0, MIT, CC-BY 4.0, Gemma Terms; some models state no license',
      developer: 'AI Laboratory of the North-Eastern Federal University',
      country: 'Russia',
    },
  },
  {
    id: 'tweety-tatar',
    name: 'Tweety Tatar',
    developer: 'Tweeties (Francois Remy, Гентский университет, и соавторы)', country: 'Бельгия',
    modality: ['text', 'translate'],
    first: '2024-04', latest: '2024-04',
    sizes: '7B',
    license: 'Apache 2.0 у базовой модели; у моделей перевода на основе TowerInstruct — CC-BY-NC 4.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['education', 'media', 'science', 'gov'],
    ollama: false,
    cpu: false,
    langsru: true,
    quant: ['gguf'],
    summary: 'Языковая модель для татарского языка: Mistral 7B, переведённая на татарский токенизатор, плюс версия для перевода между татарским и десятком других языков, включая русский. Качество надо проверять на своих текстах.',
    tasks: ['Генерация и продолжение текстов на татарском', 'Перевод между татарским и русским', 'Основа для дообучения под свою задачу', 'Эксперименты с татарским в чат-сценариях'],
    where: ['Образование и культура', 'Медиа и издательства', 'Наука и языковые проекты'],
    versions: [['Tweety Tatar Base 7B', '2024-04'], ['Tweety Tatar Hydra Base 7B', '2024-04'], ['Tweety Tatar Hydra MT 7B, перевод', '2024-04']],
    hf: 'https://huggingface.co/Tweeties/tweety-7b-tatar-v24a',
    github: null,
    alternatives: ['mistral', 'tower', 'mgpt-langs-ru'],
    source: 'https://huggingface.co/Tweeties/tweety-7b-tatar-v24a',
    verified: true,
    en: {
      summary: 'A language model for Tatar: Mistral 7B converted to a Tatar tokenizer, plus a version for translating between Tatar and a dozen other languages, including Russian. Check quality on your own texts.',
      tasks: ['Generating and continuing Tatar text', 'Translating between Tatar and Russian', 'A base for fine-tuning to your own task', 'Experiments with Tatar in chat scenarios'],
      where: ['Education and culture', 'Media and publishing', 'Research and language projects'],
      license: 'Apache 2.0 for the base model; CC-BY-NC 4.0 for the TowerInstruct-based translation models',
      developer: 'Tweeties (Francois Remy, Ghent University, and co-authors)',
      country: 'Belgium',
    },
  },
  {
    id: 'mgpt-langs-ru',
    name: 'mGPT 1.3B для языков народов России',
    developer: 'SberDevices (ai-forever)', country: 'Россия',
    modality: ['text'],
    first: '2023-08', latest: '2023-08',
    sizes: '1.3B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['education', 'media', 'science', 'gov'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['gguf'],
    summary: 'Отдельные версии mGPT под один язык каждая: башкирский, бурятский, калмыцкий, марийский, осетинский, татарский, тувинский, чувашский и якутский. В карточках у каждой заявлены также русский и английский.',
    tasks: ['Генерация и продолжение текста на национальном языке', 'Основа для дообучения под свою задачу', 'Опыты с редкими языками без обучения с нуля', 'Подготовка учебных и культурных материалов'],
    where: ['Образование и культура', 'Медиа и издательства', 'Наука и языковые проекты'],
    versions: [['mGPT 1.3B для башкирского, татарского, чувашского, якутского, тувинского, калмыцкого, марийского и осетинского', '2023-08'], ['mGPT 1.3B для бурятского', '2023-08']],
    hf: 'https://huggingface.co/ai-forever/mGPT-1.3B-tatar',
    github: 'https://github.com/ai-forever/mgpt',
    alternatives: ['mgpt', 'saiga', 'tweety-tatar'],
    source: 'https://huggingface.co/ai-forever/mGPT-1.3B-tatar',
    verified: true,
    en: {
      summary: 'Separate mGPT versions, one per language: Bashkir, Buryat, Kalmyk, Mari, Ossetian, Tatar, Tuvan, Chuvash and Sakha. Each card also lists Russian and English.',
      tasks: ['Generating and continuing text in a national language', 'A base for fine-tuning to your own task', 'Experiments with rare languages without training from scratch', 'Preparing educational and cultural materials'],
      where: ['Education and culture', 'Media and publishing', 'Research and language projects'],
      license: 'MIT',
      developer: 'SberDevices (ai-forever)',
      country: 'Russia',
    },
  },
  // ---------- ЭНКОДЕРЫ, ЭМБЕДДИНГИ И РАЗБОР ТЕКСТА ----------
  {
    id: 'lingtrain-labse',
    name: 'LaBSE для языков народов России (lingtrain)',
    developer: 'lingtrain', country: 'не раскрыта',
    modality: ['embed'],
    first: '2023-07', latest: '2025-08',
    sizes: 'дообучение LaBSE, размер в параметрах на карточках не указан',
    license: 'на карточках моделей лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'education', 'media', 'science'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Набор дообучений LaBSE, которые переводят предложения в векторы: бурятский, марийский, удмуртский, ингушский, чувашский, якутский и калмыцкий. Обучены на парах с русским, качество по языкам разное.',
    tasks: ['Сопоставление параллельных текстов на русском и национальном языке', 'Поиск по смыслу в двуязычных архивах', 'Сборка обучающих наборов для перевода', 'Группировка похожих текстов'],
    where: ['Образование и культура', 'Медиа и издательства', 'Наука и языковые проекты'],
    versions: [['LaBSE для бурятского', '2023-07'], ['LaBSE для марийского', '2024-01'], ['LaBSE для ингушского', '2024-02'], ['LaBSE для удмуртского', '2024-02'], ['LaBSE для калмыцкого', '2025-05'], ['LaBSE для чувашского, три версии', '2025-08']],
    hf: 'https://huggingface.co/lingtrain',
    github: null,
    alternatives: ['bge-m3', 'e5', 'slone-lowres'],
    source: 'https://huggingface.co/lingtrain/labse-chuvash',
    verified: true,
    en: {
      summary: 'A set of LaBSE fine-tunes that turn sentences into vectors: Buryat, Mari, Udmurt, Ingush, Chuvash, Sakha and Kalmyk. Trained on pairs with Russian; quality differs by language.',
      tasks: ['Aligning parallel texts in Russian and a national language', 'Semantic search across bilingual archives', 'Building training sets for translation', 'Grouping similar texts'],
      where: ['Education and culture', 'Media and publishing', 'Research and language projects'],
      license: 'no license is stated on the model cards — check with the developer',
      country: 'not disclosed',
      sizes: 'LaBSE fine-tunes; parameter count is not stated on the cards',
    },
  },
  {
    id: 'zerpal-udmurt',
    name: 'Zerpal: модели для удмуртского языка',
    developer: 'udmurtNLP', country: 'не раскрыта',
    modality: ['nlp', 'embed'],
    first: '2024-03', latest: '2024-06',
    sizes: '33M – 187M',
    license: 'на карточках моделей лицензия не указана — уточняйте у разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['education', 'docs', 'science', 'media'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Проект вокруг удмуртского языка: энкодеры на базе mBERT, rubert-tiny2 и Glot500, разметчики частей речи, модель исправления опечаток и эмбеддинги удмуртского с английским.',
    tasks: ['Разбор удмуртских текстов по частям речи', 'Исправление опечаток и ошибок распознавания', 'Поиск по смыслу в удмуртских материалах', 'Основа для классификаторов на удмуртском'],
    where: ['Образование и культура', 'Наука и языковые проекты', 'Медиа и издательства'],
    versions: [['Zerpal-mBERT и эмбеддинги удмуртского с английским', '2024-03'], ['Zerpal на rubert-tiny2 и Glot500', '2024-04'], ['Разметчики частей речи и модель исправления опечаток', '2024-06']],
    hf: 'https://huggingface.co/udmurtNLP',
    github: null,
    alternatives: ['rubert-tiny', 'mmbert', 'lingtrain-labse'],
    source: 'https://huggingface.co/udmurtNLP/zerpal-mbert',
    verified: true,
    en: {
      summary: 'A project around the Udmurt language: encoders based on mBERT, rubert-tiny2 and Glot500, part-of-speech taggers, a typo correction model and Udmurt-English embeddings.',
      tasks: ['Parsing Udmurt texts by part of speech', 'Correcting typos and recognition errors', 'Semantic search over Udmurt material', 'A base for classifiers in Udmurt'],
      where: ['Education and culture', 'Research and language projects', 'Media and publishing'],
      license: 'no license is stated on the model cards — check with the developer',
      country: 'not disclosed',
    },
  },
  {
    id: 'tatarnlp-world',
    name: 'Tatar NLP Community',
    developer: 'Tatar NLP Community', country: 'не раскрыта',
    modality: ['nlp', 'text'],
    first: '2026-02', latest: '2026-03',
    sizes: '178M у моделей морфологии, 7B у дообучения Mistral',
    license: 'Apache 2.0 у большинства моделей; у моделей вопросов и ответов по топонимам CC-BY-SA 4.0',
    commercial: 'conditional',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['education', 'science', 'docs', 'media'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: [],
    summary: 'Свежий набор моделей для татарского языка: разбор слов по морфологии на нескольких базах, вопросы и ответы по татарским и русским топонимам, дообучения Mistral и GPT-2 под татарский.',
    tasks: ['Морфологический разбор татарских текстов', 'Поиск ответов по названиям мест', 'Генерация текста на татарском', 'Основа для словарей и учебных сервисов'],
    where: ['Образование и культура', 'Наука и языковые проекты', 'Государственные и муниципальные учреждения'],
    versions: [['Дообучения Mistral 7B и GPT-2 под татарский', '2026-02'], ['Модели вопросов и ответов по топонимам', '2026-03'], ['Разметчики морфологии на нескольких базах', '2026-03']],
    hf: 'https://huggingface.co/TatarNLPWorld',
    github: null,
    alternatives: ['tweety-tatar', 'rubert', 'xlm-roberta'],
    source: 'https://huggingface.co/TatarNLPWorld/rubert-tatar-morph',
    verified: true,
    en: {
      summary: 'A recent set of models for Tatar: morphological analysis on several base models, question answering about Tatar and Russian place names, and Mistral and GPT-2 fine-tunes for Tatar.',
      tasks: ['Morphological analysis of Tatar texts', 'Answering questions about place names', 'Generating text in Tatar', 'A base for dictionaries and learning services'],
      where: ['Education and culture', 'Research and language projects', 'Government and municipal bodies'],
      license: 'Apache 2.0 for most models; CC-BY-SA 4.0 for the place-name question answering models',
      country: 'not disclosed',
      sizes: '178M for the morphology models, 7B for the Mistral fine-tune',
    },
  },
  {
    id: 'bashkir-nlp',
    name: 'BashkirRoBERTa и набор моделей для башкирского',
    developer: 'Tvoy_Tezka (failed09)', country: 'не раскрыта',
    modality: ['nlp', 'embed'],
    first: '2026-09', latest: '2026-09',
    sizes: '50M у BashkirRoBERTa',
    license: 'Apache 2.0 у большинства моделей; у BashkirRoBERTa — собственные условия разработчика',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['docs', 'education', 'media', 'science'],
    ollama: false,
    cpu: true,
    langsru: true,
    quant: ['int8'],
    summary: 'Небольшой набор инструментов для башкирского текста: языковая модель с заполнением пропусков, определитель башкирского языка, эмбеддинги fastText, оценщик пар с русским и восстановление башкирских букв. Всё это выложено осенью 2026 года, качество надо проверять на своих данных.',
    tasks: ['Проверка орфографии и подсказка слов на башкирском', 'Отделение башкирских текстов от чужих', 'Восстановление специфических букв в тексте', 'Подбор соответствий башкирский — русский'],
    where: ['Документооборот и архивы', 'Образование и культура', 'Медиа и издательства'],
    versions: [['BashkirRoBERTa', '2026-09'], ['Определитель башкирского языка', '2026-09'], ['Оценщик пар предложений башкирский — русский', '2026-09'], ['Эмбеддинги fastText', '2026-09'], ['Восстановление башкирских букв', '2026-09']],
    hf: 'https://huggingface.co/failed09',
    github: null,
    alternatives: ['aigizk-asr', 'slone-lowres', 'glotlid'],
    source: 'https://huggingface.co/failed09/bashkir-roberta',
    verified: true,
    en: {
      summary: 'A small toolkit for Bashkir text: a fill-mask language model, a Bashkir language detector, fastText embeddings, a Bashkir-Russian pair scorer and a letter restorer. All published in autumn 2026, so check quality on your own data.',
      tasks: ['Spellchecking and word suggestion in Bashkir', 'Separating Bashkir texts from other languages', 'Restoring language-specific letters in text', 'Matching Bashkir and Russian sentence pairs'],
      where: ['Document flow and archives', 'Education and culture', 'Media and publishing'],
      license: 'Apache 2.0 for most models; custom developer terms for BashkirRoBERTa',
      country: 'not disclosed',
      sizes: '50M for BashkirRoBERTa',
    },
  },
];
