// Волна 4: российские открытые модели (МТС AI, Авито, ai-forever, bond005, deepvk, сообщество). Факты сверены по Hugging Face / GitHub на 22.09.2026.
module.exports = [
  {
    id: 'cotype',
    name: 'Cotype Nano (МТС AI)',
    developer: 'МТС AI (MWS AI)', country: 'Россия',
    modality: ['text'],
    first: '2024-11', latest: '2024-11',
    sizes: '1.5B',
    license: 'Apache 2.0 в тексте МТС AI (файл лицензии в репозитории); в метаданных HF указано other — перед коммерческим запуском прочитать файл',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['support', 'docs', 'marketing'],
    ollama: false,
    cpu: true,
    summary: 'Лёгкая русскоязычная модель от МТС AI для текстов на русском: ответы, пересказ, черновики. Есть готовая версия для процессора без видеокарты. Старшая Cotype Pro открыто не выложена.',
    tasks: ['Черновики писем и описаний на русском', 'Краткий пересказ документов', 'Ответы на типовые вопросы клиентов'],
    where: ['Службы поддержки', 'Офисный документооборот', 'Маркетинг'],
    versions: [['Cotype-Nano', '2024-11'], ['Cotype-Nano-CPU и 4bit, GGUF', '2024-11']],
    hf: 'https://huggingface.co/MTSAIR/Cotype-Nano',
    github: null,
    alternatives: ['gigachat', 't-pro', 'qwen'],
    source: 'https://huggingface.co/MTSAIR/Cotype-Nano',
    verified: true,
    en: {
      summary: 'A lightweight Russian-language model from MTS AI for Russian texts: answers, summaries, drafts. A ready version for CPU without a GPU is available. The larger Cotype Pro is not released openly.',
      tasks: ['Drafts of emails and descriptions in Russian', 'Short document summaries', 'Answers to common customer questions'],
      where: ['Support teams', 'Office document management', 'Marketing'],
      license: 'Apache 2.0 per the MTS AI text (license file in the repository); HF metadata says other, so read the file before commercial launch',
      developer: 'MTS AI (MWS AI)',
      country: 'Russia',
    },
  },
  {
    id: 'kodify',
    name: 'Kodify-Nano (МТС AI)',
    developer: 'МТС AI (MWS AI)', country: 'Россия',
    modality: ['code', 'text'],
    first: '2025-05', latest: '2025-05',
    sizes: '1.5B',
    license: 'Apache 2.0 (текст лицензии МТС AI в репозитории)',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['dev'],
    ollama: false,
    cpu: true,
    summary: 'Маленький помощник программиста от МТС AI, понимает запросы на русском. Работает локально, есть плагины для VS Code и JetBrains.',
    tasks: ['Подсказки и дописывание кода в редакторе', 'Объяснение кода на русском', 'Черновики тестов и документации'],
    where: ['Отделы разработки', 'IT-подразделения с закрытым контуром'],
    versions: [['Kodify-Nano', '2025-05'], ['Kodify-Nano GPTQ и GGUF', '2025-05']],
    hf: 'https://huggingface.co/MTSAIR/Kodify-Nano',
    github: null,
    alternatives: ['qwen-coder', 'mellum', 'deepseek-coder'],
    source: 'https://huggingface.co/MTSAIR/Kodify-Nano',
    verified: true,
    en: {
      summary: 'A small coding assistant from MTS AI that understands requests in Russian. Runs locally, with plugins for VS Code and JetBrains.',
      tasks: ['Code suggestions and completion in the editor', 'Code explanations in Russian', 'Drafts of tests and documentation'],
      where: ['Development teams', 'IT departments with a closed environment'],
      license: 'Apache 2.0 (MTS AI license text in the repository)',
      developer: 'MTS AI (MWS AI)',
      country: 'Russia',
    },
  },
  {
    id: 'a-vibe',
    name: 'A-Vibe (Авито)',
    developer: 'Авито Тех', country: 'Россия',
    modality: ['text'],
    first: '2025-10', latest: '2025-10',
    sizes: '7.9B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['retail', 'support', 'marketing'],
    ollama: false,
    cpu: false,
    summary: 'Модель Авито на базе Qwen3-8B, переученная под русский язык: свой токенизатор, который экономнее кодирует русский текст. Умеет вызывать функции.',
    tasks: ['Описания товаров и объявлений на русском', 'Чат-бот с вызовом внутренних сервисов', 'Разбор и классификация обращений'],
    where: ['Маркетплейсы и интернет-магазины', 'Службы поддержки', 'Маркетинг'],
    versions: [['A-Vibe', '2025-10'], ['A-Vibe Eagle (ускоритель генерации)', '2025-10']],
    hf: 'https://huggingface.co/AvitoTech/avibe',
    github: null,
    alternatives: ['qwen', 't-pro', 'gigachat'],
    source: 'https://huggingface.co/AvitoTech/avibe',
    verified: true,
    en: {
      summary: 'Avito\'s model based on Qwen3-8B, retrained for Russian: its own tokenizer encodes Russian text more efficiently. Supports function calling.',
      tasks: ['Product and listing descriptions in Russian', 'Chatbot that calls internal services', 'Request analysis and classification'],
      where: ['Marketplaces and online stores', 'Support teams', 'Marketing'],
      license: 'Apache 2.0',
      developer: 'Avito Tech',
      country: 'Russia',
    },
  },
  {
    id: 'a-vision',
    name: 'A-Vision (Авито)',
    developer: 'Авито Тех', country: 'Россия',
    modality: ['vlm', 'ocr'],
    first: '2025-10', latest: '2025-10',
    sizes: '7.4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'yes',
    industries: ['retail', 'marketing', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Русскоязычная модель Авито, которая понимает картинки: описывает фото, отвечает на вопросы по изображению, читает надписи. Основа Qwen2.5-VL, на русском быстрее исходной.',
    tasks: ['Описание товара по фото на русском', 'Проверка, что фото совпадает с описанием', 'Чтение брендов и надписей на картинках'],
    where: ['Маркетплейсы и доски объявлений', 'Модерация карточек товаров', 'Каталоги интернет-магазинов'],
    versions: [['A-Vision', '2025-10']],
    hf: 'https://huggingface.co/AvitoTech/avision',
    github: null,
    alternatives: ['qwen-vl', 'internvl', 'minicpm-v'],
    source: 'https://huggingface.co/AvitoTech/avision',
    verified: true,
    en: {
      summary: 'Avito\'s Russian-language model that understands images: describes photos, answers questions about an image, reads text on it. Based on Qwen2.5-VL, faster in Russian than the original.',
      tasks: ['Product descriptions from photos in Russian', 'Checking that a photo matches its description', 'Reading brands and text in images'],
      where: ['Marketplaces and classifieds', 'Product card moderation', 'Online store catalogs'],
      license: 'Apache 2.0',
      developer: 'Avito Tech',
      country: 'Russia',
    },
  },
  {
    id: 'pollux',
    name: 'POLLUX Judge (ai-forever)',
    developer: 'SberDevices (ai-forever)', country: 'Россия',
    modality: ['judge', 'text'],
    first: '2025-06', latest: '2026-04',
    sizes: '4B – 32B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['dev', 'support', 'science'],
    ollama: false,
    cpu: true,
    summary: 'Модели-судьи для оценки ответов других нейросетей на русском языке: ставят балл по заданному критерию и объясняют оценку текстом.',
    tasks: ['Автоматическая проверка качества ответов чат-бота на русском', 'Сравнение нескольких моделей перед выбором', 'Контроль ответов после дообучения'],
    where: ['Команды, внедряющие чат-ботов', 'Службы поддержки', 'Исследования'],
    versions: [['pollux-judge 7B и 32B (с рассуждением и без)', '2025-06'], ['Pollux-4B-Judge', '2026-04']],
    hf: 'https://huggingface.co/ai-forever/Pollux-4B-Judge',
    github: 'https://github.com/ai-forever/POLLUX',
    alternatives: ['gigachat', 't-pro', 'qwen'],
    source: 'https://huggingface.co/ai-forever/Pollux-4B-Judge',
    verified: true,
    en: {
      summary: 'Judge models that evaluate other AI models\' answers in Russian: they score against a given criterion and explain the score in text.',
      tasks: ['Automatic quality checks of Russian chatbot answers', 'Comparing several models before choosing one', 'Checking answers after fine-tuning'],
      where: ['Teams deploying chatbots', 'Support teams', 'Research'],
      license: 'MIT',
      country: 'Russia',
    },
  },
  {
    id: 'meno',
    name: 'Meno (Иван Бондаренко)',
    developer: 'Иван Бондаренко (bond005), НГУ', country: 'Россия',
    modality: ['text', 'nlp'],
    first: '2024-11', latest: '2026-04',
    sizes: '1.5B – 7.6B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'yes',
    industries: ['docs', 'legal', 'finance'],
    ollama: false,
    cpu: true,
    summary: 'Русскоязычные модели для работы с документами, а не для болтовни: ответы по базе знаний, извлечение сущностей и фактов из текста на русском, длинный контекст.',
    tasks: ['Ответы на вопросы по внутренним документам', 'Извлечение имён, дат и сумм из договоров', 'Краткое изложение длинных текстов на русском'],
    where: ['Юридические отделы', 'Документооборот', 'Базы знаний компаний'],
    versions: [['Meno-Tiny-0.1 (1.5B)', '2024-11'], ['Meno-Lite-0.1 (7B)', '2026-01'], ['Meno-Lite-0.1 GGUF', '2026-04']],
    hf: 'https://huggingface.co/bond005/meno-lite-0.1',
    github: null,
    alternatives: ['ruadapt-qwen', 't-pro', 'saiga'],
    source: 'https://huggingface.co/bond005/meno-lite-0.1',
    verified: true,
    en: {
      summary: 'Russian-language models for working with documents rather than chatting: knowledge-base answers, extraction of entities and facts from Russian text, long context.',
      tasks: ['Answers to questions based on internal documents', 'Extracting names, dates and amounts from contracts', 'Short summaries of long Russian texts'],
      where: ['Legal departments', 'Document management', 'Company knowledge bases'],
      license: 'Apache 2.0',
      developer: 'Ivan Bondarenko (bond005), Novosibirsk State University',
      country: 'Russia',
    },
  },
  {
    id: 'ruclip',
    name: 'ruCLIP (ai-forever)',
    developer: 'Сбер AI и SberDevices (ai-forever)', country: 'Россия',
    modality: ['vision', 'embed'],
    first: '2022-01', latest: '2022-01',
    sizes: '150M – 430M',
    license: 'Apache 2.0 (репозиторий на GitHub)',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['retail', 'media'],
    ollama: false,
    cpu: true,
    summary: 'Русская версия CLIP: сопоставляет картинки и подписи на русском. Позволяет искать фото по описанию и раскладывать изображения по категориям без обучения.',
    tasks: ['Поиск товаров по фото и по русскому описанию', 'Сортировка картинок по категориям без разметки', 'Проверка соответствия фото и подписи'],
    where: ['Интернет-магазины', 'Фото- и медиаархивы', 'Модерация контента'],
    versions: [['ruCLIP ViT-B/32, B/16, L/14 (224 и 384 пикселя)', '2022-01'], ['ruCLIP ViT-L/14 336', '2022-01']],
    hf: 'https://huggingface.co/ai-forever/ruclip-vit-base-patch32-384',
    github: 'https://github.com/ai-forever/ru-clip',
    alternatives: ['clip-siglip', 'jina-embeddings'],
    source: 'https://huggingface.co/ai-forever/ruclip-vit-large-patch14-336',
    verified: true,
    en: {
      summary: 'A Russian version of CLIP: matches images with Russian captions. Lets you search photos by description and sort images into categories without training.',
      tasks: ['Product search by photo and by Russian description', 'Sorting images into categories without labeling', 'Checking that a photo matches its caption'],
      where: ['Online stores', 'Photo and media archives', 'Content moderation'],
      license: 'Apache 2.0 (GitHub repository)',
      developer: 'Sber AI and SberDevices (ai-forever)',
      country: 'Russia',
    },
  },
  {
    id: 'kazrush',
    name: 'kazRush (deepvk)',
    developer: 'deepvk (VK)', country: 'Россия',
    modality: ['translate'],
    first: '2024-10', latest: '2024-11',
    sizes: '197M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['gov', 'docs', 'support'],
    ollama: false,
    cpu: true,
    summary: 'Компактные переводчики между казахским и русским от VK. При размере 197M переводят не хуже NLLB на 600M, работают на обычном процессоре.',
    tasks: ['Перевод обращений с казахского на русский', 'Перевод документов и инструкций на казахский', 'Двуязычная поддержка клиентов'],
    where: ['Компании с клиентами в Казахстане', 'Госуслуги', 'Службы поддержки'],
    versions: [['kazRush-kk-ru (казахский в русский)', '2024-10'], ['kazRush-ru-kk (русский в казахский)', '2024-11']],
    hf: 'https://huggingface.co/deepvk/kazRush-kk-ru',
    github: null,
    alternatives: ['nllb', 'madlad', 'opus-mt'],
    source: 'https://huggingface.co/deepvk/kazRush-ru-kk',
    verified: true,
    en: {
      summary: 'Compact Kazakh-Russian translators from VK. At 197M they translate as well as the 600M NLLB and run on a regular CPU.',
      tasks: ['Translating requests from Kazakh to Russian', 'Translating documents and instructions into Kazakh', 'Bilingual customer support'],
      where: ['Companies with customers in Kazakhstan', 'Public services', 'Support teams'],
      license: 'Apache 2.0',
      country: 'Russia',
    },
  },
  {
    id: 'zarya',
    name: 'Zarya (ai-forever)',
    developer: 'SberDevices (ai-forever)', country: 'Россия',
    modality: ['text'],
    first: '2026-09', latest: '2026-09',
    sizes: '0.6B – 4B',
    license: 'MIT',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'yes',
    industries: ['science', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Исследовательский прототип на русском и английском: модель пишет текст не по одному слову, а блоками сразу (диффузия), что ускоряет ответ. Для рабочих систем авторы её не рекомендуют.',
    tasks: ['Эксперименты с ускорением генерации', 'Дообучение небольших моделей под свои задачи', 'Исследования'],
    where: ['R&D-команды', 'Университеты и лаборатории'],
    versions: [['Zarya 0.6B, 1.7B и 4B', '2026-09']],
    hf: 'https://huggingface.co/ai-forever/Zarya-4B',
    github: 'https://github.com/ai-forever/zarya',
    alternatives: ['qwen', 'gigachat', 'rugpt'],
    source: 'https://huggingface.co/ai-forever/Zarya-4B',
    verified: true,
    en: {
      summary: 'A Russian and English research prototype: the model writes text in blocks at once (diffusion) rather than word by word, which speeds up responses. The authors do not recommend it for production systems.',
      tasks: ['Experiments with faster generation', 'Fine-tuning small models for your own tasks', 'Research'],
      where: ['R&D teams', 'Universities and labs'],
      license: 'MIT',
      country: 'Russia',
    },
  },
  {
    id: 'ru-classifiers',
    name: 'Русские классификаторы токсичности и тональности',
    developer: 'Давид Дале (cointegrated) и сообщество', country: 'Россия',
    modality: ['nlp', 'safety'],
    first: '2022-03', latest: '2023-05',
    sizes: '12M – 29M',
    license: 'MIT у токсичности и seara-тональности; у тональности и эмоций от cointegrated лицензия на карточке не указана',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['support', 'security', 'retail', 'marketing'],
    ollama: false,
    cpu: true,
    summary: 'Готовые крошечные модели на rubert-tiny для русского текста: находят грубость и оскорбления, определяют тональность и эмоции. Работают на процессоре за миллисекунды.',
    tasks: ['Фильтр оскорблений в чатах и комментариях на русском', 'Разметка отзывов на позитив, нейтрал и негатив', 'Поиск раздражённых клиентов в обращениях'],
    where: ['Службы поддержки', 'Модерация сообществ', 'Аналитика отзывов'],
    versions: [['rubert-tiny-toxicity, rubert-tiny-sentiment-balanced, rubert-tiny2-cedr-emotion-detection', '2022-03'], ['seara/rubert-tiny2-russian-sentiment', '2023-05']],
    hf: 'https://huggingface.co/cointegrated/rubert-tiny-toxicity',
    github: null,
    alternatives: ['rubert-tiny', 'deepvk-encoders', 'qwen3guard'],
    source: 'https://huggingface.co/seara/rubert-tiny2-russian-sentiment',
    verified: true,
    en: {
      summary: 'Ready-made tiny rubert-tiny models for Russian text: detect rudeness and insults, sentiment and emotions. They run on a CPU in milliseconds.',
      tasks: ['Filtering insults in Russian chats and comments', 'Labeling reviews as positive, neutral or negative', 'Spotting irritated customers in requests'],
      where: ['Support teams', 'Community moderation', 'Review analytics'],
      license: 'MIT for toxicity and seara sentiment; the license for cointegrated sentiment and emotion models is not stated on the model card',
      developer: 'David Dale (cointegrated) and the community',
      country: 'Russia',
    },
  },
  {
    id: 'dusha-emotion',
    name: 'Эмоции в русской речи (модели на датасете Dusha)',
    developer: 'Сообщество (xbgoose и др.), датасет Dusha от SberDevices', country: 'Россия',
    modality: ['voice'],
    first: '2023-05', latest: '2025-07',
    sizes: '21M – 316M',
    license: 'Apache 2.0 у HuBERT-large; у остальных версий лицензия на карточке не указана',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'yes',
    industries: ['support', 'marketing'],
    ollama: false,
    cpu: true,
    summary: 'Модели, определяющие эмоцию по голосу в русской речи: нейтрально, злость, позитив, грусть. Обучены на открытом датасете Dusha от SberDevices.',
    tasks: ['Поиск звонков с раздражённым клиентом', 'Оценка тона разговоров операторов', 'Приоритизация жалоб в колл-центре'],
    where: ['Колл-центры', 'Контроль качества обслуживания'],
    versions: [['HuBERT-large Dusha', '2023-05'], ['HuBERT-base и WavLM Dusha', '2023-06'], ['Whisper-base SER Dusha', '2025-07']],
    hf: 'https://huggingface.co/xbgoose/hubert-large-speech-emotion-recognition-russian-dusha-finetuned',
    github: 'https://github.com/salute-developers/golos/tree/master/dusha',
    alternatives: ['gigaam', 'sensevoice'],
    source: 'https://huggingface.co/waveletdeboshir/whisper-base-ser-dusha',
    verified: true,
    en: {
      summary: 'Models that detect emotion from voice in Russian speech: neutral, anger, positive, sadness. Trained on the open Dusha dataset from SberDevices.',
      tasks: ['Finding calls with irritated customers', 'Assessing the tone of operator conversations', 'Prioritizing complaints in a call center'],
      where: ['Call centers', 'Service quality control'],
      license: 'Apache 2.0 for HuBERT-large; for the other versions the license is not stated on the model card',
      developer: 'Community (xbgoose and others), Dusha dataset from SberDevices',
      country: 'Russia',
    },
  },
];
