// Kolibri, AstaBrief, Xiaomi-TabLDM, JEV и GEV, pplx-decider, Julia, Phonon, Audio8 ASR Infinite. Факты сверены по Hugging Face, GitHub и сайтам разработчиков на 07.10.2026.
module.exports = [
  {
    id: 'kolibri',
    name: 'Kolibri',
    developer: 'Aleph Alpha', country: 'Германия',
    modality: ['text', 'reasoning'],
    first: '2026-10', latest: '2026-10',
    sizes: '78B-A3.5B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['multi'],
    ru: 'no',
    industries: ['gov', 'legal', 'docs', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Европейская открытая модель с рассуждениями на немецком и английском. MoE на 78B параметров, на каждый токен работают 3,5B. Контекст 262 тысячи токенов (проверен до миллиона), вызов инструментов.',
    tasks: ['ответы по длинным документам и RAG', 'агент с вызовом инструментов', 'извлечение данных из документов в структуру', 'помощь с кодом'],
    where: ['госсектор и регулируемые отрасли', 'юридические отделы', 'внутренние ассистенты на своих серверах'],
    versions: [['Kolibri 1 (FP8)', '2026-10'], ['Kolibri 1 BF16', '2026-10']],
    hf: 'https://huggingface.co/Aleph-Alpha/Kolibri-1',
    github: null,
    alternatives: ['gpt-oss', 'mistral', 'qwen'],
    source: 'https://huggingface.co/Aleph-Alpha/Kolibri-1',
    verified: true,
    en: {
      summary: "A European open reasoning model for German and English. A 78B mixture-of-experts with 3.5B active per token, a 262K-token context (tested up to a million) and tool calling.",
      tasks: ['answers over long documents and RAG', 'an agent that calls tools', 'extracting structured data from documents', 'coding help'],
      where: ['public sector and regulated industries', 'legal departments', 'in-house assistants on your own servers'],
      country: 'Germany',
    },
  },
  {
    id: 'astabrief',
    name: 'AstaBrief',
    developer: 'Ai2 (Институт Аллена)', country: 'США',
    modality: ['text'],
    first: '2026-09', latest: '2026-10',
    sizes: '8B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min', 'gpu'],
    ru: 'no',
    industries: ['science', 'education', 'docs'],
    ollama: false,
    cpu: false,
    summary: 'Модель на 8B, которая по вопросу и поданным ей фрагментам научных статей пишет отчёт со ссылками на источники. Сама ничего не ищет: фрагменты нужно подать вместе с вопросом.',
    tasks: ['обзор литературы по вопросу со ссылками на источники', 'сводка по набору собственных PDF', 'черновик аналитической записки с цитатами'],
    where: ['научные группы и вузы', 'R&D-отделы', 'аналитические подразделения'],
    versions: [['AstaBrief 8B SFT', '2026-09'], ['AstaBrief 8B', '2026-10']],
    hf: 'https://huggingface.co/allenai/AstaBrief_8B',
    github: null,
    alternatives: ['olmo', 'qwen', 'tulu'],
    source: 'https://huggingface.co/allenai/AstaBrief_8B',
    verified: true,
    en: {
      summary: "An 8B model that turns a question and the excerpts of scientific papers you give it into a report with citations. It does not search by itself: excerpts must be supplied with the question.",
      tasks: ['literature overview with source citations', 'summary of your own set of PDFs', 'draft analytical note with quotes'],
      where: ['research groups and universities', 'R&D departments', 'analytics teams'],
      developer: 'Ai2 (Allen Institute)',
      country: 'USA',
    },
  },
  {
    id: 'xiaomi-tabldm',
    name: 'Xiaomi-TabLDM',
    developer: 'Xiaomi', country: 'Китай',
    modality: ['tabular'],
    first: '2026-09', latest: '2026-09',
    sizes: 'около 70M',
    license: 'Apache 2.0 по файлу LICENSE на GitHub; в README упомянута некоммерческая лицензия, перед коммерческим использованием уточните у Xiaomi',
    commercial: 'conditional',
    hardware: ['min'],
    ru: 'na',
    industries: ['finance', 'retail', 'manufacturing', 'science'],
    ollama: false,
    cpu: false,
    summary: 'Маленькая модель для таблиц: берёт размеченные строки как контекст и за один проход предсказывает значения для новых строк, отдельно обучать под задачу не нужно. Два чекпоинта: классификация и регрессия.',
    tasks: ['прогноз по таблице клиентов или заказов', 'оценка стоимости или спроса по строкам продаж', 'скоринг заявок без обучения отдельной модели'],
    where: ['финансы и скоринг', 'розница и продажи', 'производство', 'аналитика'],
    versions: [['Xiaomi-TabLDM, классификация и регрессия', '2026-09']],
    hf: 'https://huggingface.co/occams/Xiaomi-TabLDM',
    github: 'https://github.com/xiaomi-research/xiaomi-tabldm',
    alternatives: ['tabpfn', 'tabicl', 'tabfm'],
    source: 'https://github.com/xiaomi-research/xiaomi-tabldm',
    verified: true,
    en: {
      summary: "A small tabular model: it takes labeled rows as context and predicts values for new rows in one pass, with no task-specific training. Two checkpoints: classification and regression.",
      tasks: ['forecasts from a table of customers or orders', 'estimating price or demand from sales rows', 'scoring requests without training a separate model'],
      where: ['finance and scoring', 'retail and sales', 'manufacturing', 'analytics'],
      license: 'Apache 2.0 per the LICENSE file on GitHub; the README mentions a non-commercial license, so confirm with Xiaomi before commercial use',
      sizes: 'about 70M',
      country: 'China',
    },
  },
  {
    id: 'jev-gev',
    name: 'JEV и GEV',
    developer: 'AutoTrust AI', country: 'Сингапур',
    modality: ['nlp', 'vlm', 'agent'],
    first: '2026-09', latest: '2026-10',
    sizes: '9B – 27B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['support', 'docs', 'security', 'dev'],
    ollama: false,
    cpu: false,
    summary: 'Открытые модели решений: на вопросы «да или нет», «выбери вариант», «оцени от 0 до 5» отвечают вероятностями за один проход, а при нужде ещё и рассуждают. Не связаны с закрытой Jev от TypeSafe.',
    tasks: ['сортировка заявок и обращений по отделам', 'проверка действия агента перед выполнением', 'оценка срочности и тональности сообщений', 'выбор инструмента для следующего шага агента'],
    where: ['поддержка клиентов', 'ИИ-агенты и автоматизация процессов', 'документооборот', 'безопасность и модерация'],
    versions: [['JEV-9B', '2026-09'], ['JEV-27B', '2026-09'], ['JEV-27B-VL (понимает картинки)', '2026-09'], ['GEV-26B-Decide (на Gemma 4)', '2026-10']],
    hf: 'https://huggingface.co/autotrust/JEV-27B',
    github: null,
    alternatives: ['clef', 'qwen', 'gemma'],
    source: 'https://huggingface.co/autotrust/JEV-27B',
    verified: true,
    en: {
      summary: "Open decision models: for yes/no, pick-one and rate-0-to-5 questions they answer with probabilities in one pass, and can also reason when needed. Not affiliated with the closed Jev from TypeSafe.",
      tasks: ['routing requests to the right team', 'checking an agent action before it runs', 'rating urgency and tone of messages', 'choosing the tool for an agent next step'],
      where: ['customer support', 'AI agents and process automation', 'document management', 'security and moderation'],
      developer: 'AutoTrust AI',
      country: 'Singapore',
    },
  },
  {
    id: 'pplx-decider',
    name: 'pplx-decider',
    developer: 'Perplexity', country: 'США',
    modality: ['nlp', 'vlm'],
    first: '2026-10', latest: '2026-10',
    sizes: '27B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'unknown',
    industries: ['support', 'docs', 'finance', 'legal'],
    ollama: false,
    cpu: false,
    summary: 'Модель решений на базе Qwen3.8-27B: выбирает вариант, отвечает «да или нет» или ставит оценку и возвращает калиброванные вероятности. Понимает и картинки.',
    tasks: ['маршрутизация обращений по командам', 'проверка ответов ИИ на соответствие источникам', 'оценка тональности и срочности писем', 'классификация документов и договоров'],
    where: ['поддержка клиентов', 'документооборот', 'финансы', 'юридические отделы'],
    versions: [['pplx-decider-v1-27b', '2026-10'], ['pplx-decider-v1.1-27b (Decision Index 61,56 против 56,4)', '2026-10']],
    hf: 'https://huggingface.co/perplexity-ai/pplx-decider-v1.1-27b',
    github: null,
    alternatives: ['clef', 'jev-gev', 'qwen'],
    source: 'https://huggingface.co/perplexity-ai/pplx-decider-v1.1-27b',
    verified: true,
    en: {
      summary: "A decision model built on Qwen3.8-27B: it picks an option, answers yes or no or gives a rating, and returns calibrated probabilities. It also understands images.",
      tasks: ['routing requests to teams', 'checking AI answers against sources', 'rating tone and urgency of emails', 'classifying documents and contracts'],
      where: ['customer support', 'document management', 'finance', 'legal departments'],
      country: 'USA',
    },
  },
  {
    id: 'julia',
    name: 'Julia',
    developer: 'Supersonic Labs', country: 'не указана',
    modality: ['nlp'],
    first: '2026-09', latest: '2026-09',
    sizes: '144M',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'unknown',
    industries: ['support', 'retail', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Совсем маленькая модель решений: по тексту, вопросу и вариантам ответа выбирает один вариант, ставит оценку или отвечает «да или нет». Работает на обычном процессоре и в браузере.',
    tasks: ['маршрутизация обращений по темам', 'определение тональности отзывов', 'быстрая классификация заявок', 'решения «да или нет» по тексту'],
    where: ['поддержка клиентов', 'интернет-магазины', 'встроенные ИИ-агенты'],
    versions: [['Julia 1', '2026-09']],
    hf: 'https://huggingface.co/SupersonicLabs/Julia-1',
    github: null,
    alternatives: ['clef', 'gliner', 'jev-gev'],
    source: 'https://huggingface.co/SupersonicLabs/Julia-1',
    verified: true,
    en: {
      summary: "A very small decision model: from a text, a question and answer options it picks one option, gives a rating or answers yes or no. Runs on an ordinary CPU and in the browser.",
      tasks: ['routing requests by topic', 'detecting the tone of reviews', 'fast classification of requests', 'yes-or-no decisions about a text'],
      where: ['customer support', 'online stores', 'built-in AI agents'],
      country: 'not stated',
    },
  },
  {
    id: 'phonon',
    name: 'Phonon',
    developer: 'Fermion Research', country: 'не указана',
    modality: ['asr'],
    first: '2026-09', latest: '2026-09',
    sizes: '164 МБ (около 2,1 бита на вес)',
    license: 'CC BY 4.0',
    commercial: 'yes',
    hardware: ['min'],
    ru: 'no',
    industries: ['support', 'media', 'docs'],
    ollama: false,
    cpu: true,
    summary: 'Очень компактная модель распознавания английской речи: 164 МБ, по точности близка к своей большой основе Parakeet. Час записи расшифровывает примерно за 20 секунд на ноутбуке.',
    tasks: ['расшифровка встреч и звонков на английском', 'диктовка текста на ноутбуке без интернета', 'субтитры к английским роликам'],
    where: ['колл-центры', 'медиа и подкасты', 'офисная работа'],
    versions: [['Phonon-2 (на базе Parakeet TDT 0.6B v3)', '2026-09']],
    hf: 'https://huggingface.co/FermionResearch/Phonon-2',
    github: null,
    alternatives: ['parakeet', 'whisper', 'moonshine'],
    source: 'https://huggingface.co/FermionResearch/Phonon-2',
    verified: true,
    en: {
      summary: "A very compact English speech recognition model: 164 MB, close in accuracy to its large Parakeet base. Transcribes an hour of audio in about 20 seconds on a laptop.",
      tasks: ['transcribing English meetings and calls', 'dictating text on a laptop offline', 'subtitles for English videos'],
      where: ['call centers', 'media and podcasts', 'office work'],
      license: 'CC BY 4.0',
      sizes: '164 MB (about 2.1 bits per weight)',
      country: 'not stated',
    },
  },
  {
    id: 'audio8-asr',
    name: 'Audio8 ASR Infinite',
    developer: 'Edge0', country: 'не указана',
    modality: ['asr'],
    first: '2026-09', latest: '2026-09',
    sizes: '4B',
    license: 'Apache 2.0',
    commercial: 'yes',
    hardware: ['gpu'],
    ru: 'no',
    industries: ['support', 'media'],
    ollama: false,
    cpu: false,
    summary: 'Потоковое распознавание китайской и английской речи с задержкой 240–560 мс. Может слушать бесконечно долго без роста памяти и сам отличает паузу на раздумье от конца реплики.',
    tasks: ['субтитры для прямых эфиров и созвонов', 'голосовые ассистенты с быстрой реакцией', 'круглосуточная расшифровка потока речи'],
    where: ['колл-центры', 'медиа и стриминг', 'голосовые боты'],
    versions: [['Audio8 ASR Infinite', '2026-09']],
    hf: 'https://huggingface.co/Edge0/Audio8-ASR-Infinite',
    github: 'https://github.com/Edge0-AI/Audio8-ASR-Infinite',
    alternatives: ['voxtral', 'qwen-asr', 'whisper'],
    source: 'https://huggingface.co/Edge0/Audio8-ASR-Infinite',
    verified: true,
    en: {
      summary: "Streaming recognition of Chinese and English speech with a 240-560 ms delay. It can listen indefinitely without memory growth and tells a thinking pause from the end of a turn.",
      tasks: ['subtitles for live streams and calls', 'voice assistants with fast reaction', 'round-the-clock transcription of a speech stream'],
      where: ['call centers', 'media and streaming', 'voice bots'],
      country: 'not stated',
    },
  },
];
