module.exports = [
  {
    slug: 'it-dlya-zoomagazina-gruminga-2027', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ЗООМАГАЗИН', hero: 'IT для зоомагазина',
    tagline: 'Запись, подписка на корм, карточка',
    points: ['Онлайн-запись', 'Подписка на корм', 'Карточка питомца', 'Лояльность и возврат'],
    description: 'Как автоматизировать зоомагазин и груминг-салон — онлайн-запись со слотами, подписка на корм с напоминаниями и карточка питомца с историей. Разбираю программу лояльности, доставку и чек-лист запуска за 30 дней без больших вложений.',
    relatedArticles: ['cifrovizaciya-vetklinik-2026', 'avtomatizaciya-saun-ban-spa-2026', 'biznes-na-arende-i-prokate-2027'],
    relatedOffers: ['zoomagazin-gruming', 'dostavka-bot-povtornye-zakazy', 'programma-loyalnosti'],
  },
  {
    slug: 'it-dlya-yazykovoy-shkoly-repetitorov-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ОБРАЗОВАНИЕ', hero: 'IT для языковой школы',
    tagline: 'Абонементы, уроки, удержание',
    points: ['CRM и база учеников', 'Абонемент со списанием', 'Уроки и прогресс', 'Удержание и кабинет'],
    description: 'IT-стек языковой школы и репетитора — CRM, расписание групп, абонементы со списанием занятий и онлайн-уроки на российских сервисах. Главный фокус на удержании: видимый прогресс, кабинет родителя и борьба с оттоком, с учётом 152-ФЗ по данным детей.',
    relatedArticles: ['avtomatizaciya-onlayn-shkoly-2026', 'avtomatizaciya-sportshkoly-sekciy-2027', 'cifrovizaciya-detskogo-sada-2026'],
    relatedOffers: ['platforma-vebinarov', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'avtomatizaciya-onlayn-shkoly-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ОНЛАЙН-ШКОЛА', hero: 'Автоматизация онлайн-школы',
    tagline: 'LMS, видео, оплаты и рассрочки',
    points: ['Выбор LMS под формат', 'Хостинг видео в РФ', 'Оплаты и рассрочки', 'AI-проверка работ'],
    description: 'Полный стек онлайн-школы и курсов после ухода западных платформ — GetCourse, AntiTreningi, iSpring и связки Tilda с Kinescope. Разбираю хостинг видео, приём оплат с рассрочками, AI-проверку работ на GigaChat и YandexGPT и реальные бюджеты по сегментам.',
    relatedArticles: ['it-dlya-yazykovoy-shkoly-repetitorov-2026', 'avtomatizaciya-sportshkoly-sekciy-2027', 'ai-dlya-logistiki-2026'],
    relatedOffers: ['platforma-vebinarov', 'ai-kontent-zavod', 'integraciya-sistem'],
  },
  {
    slug: 'avtomatizaciya-saun-ban-spa-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'SPA', hero: 'Автоматизация SPA и бань',
    tagline: 'Бронь с депозитом и IoT-парная',
    points: ['Бронь по часам', 'Депозит против no-show', 'IoT-прогрев парной', 'Чек-листы уборки'],
    description: 'Как автоматизировать сауну, баню и SPA-комплекс — почасовая бронь с депозитом, график парных и видеонаблюдение вместо тетрадки. Разбираю системы записи, IoT-управление парной и контроль уборки, с реальными бюджетами для мини-саун и сетей.',
    relatedArticles: ['it-dlya-zoomagazina-gruminga-2027', 'biznes-na-arende-i-prokate-2027', 'dostavka-vody-produktov-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'programma-loyalnosti', 'integraciya-sistem'],
  },
  {
    slug: 'avtomatizaciya-sportshkoly-sekciy-2027', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'СПОРТ', hero: 'Автоматизация спортшколы',
    tagline: 'Расписание, абонементы, кабинет родителя',
    points: ['Расписание и залы', 'Абонемент с заморозкой', 'Кабинет родителя', 'Посещаемость и оплата'],
    description: 'Как навести порядок в спортшколе и детских секциях — онлайн-расписание групп и залов, абонементы с заморозкой и кабинет родителя вместо хаоса в тетради. Разбираю отметку посещаемости, расчёт зарплат тренеров, напоминания об оплате и хранение данных детей по 152-ФЗ.',
    relatedArticles: ['it-dlya-yazykovoy-shkoly-repetitorov-2026', 'avtomatizaciya-onlayn-shkoly-2026', 'cifrovizaciya-detskogo-sada-2026'],
    relatedOffers: ['sportshkola-sekcii', 'programma-loyalnosti', 'bot-dlya-biznesa'],
  },
  {
    slug: 'biznes-na-arende-i-prokate-2027', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'АРЕНДА', hero: 'Аренда и прокат',
    tagline: 'Оборачиваемость вместо учёта',
    points: ['Каталог парка', 'Календарь доступности', 'Договор и залог онлайн', 'Контроль возврата'],
    description: 'Арендный и прокатный бизнес зарабатывает на оборачиваемости актива, а теряет на ручном учёте — двойных бронях, потерянных залогах и пропавшем инвентаре. Разбираю минимальный контур автоматизации, бюджетные вилки и хранение данных арендаторов по 152-ФЗ.',
    relatedArticles: ['avtomatizaciya-saun-ban-spa-2026', 'it-dlya-zoomagazina-gruminga-2027', 'dostavka-vody-produktov-2026'],
    relatedOffers: ['arenda-spectehniki', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'dostavka-vody-produktov-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ДОСТАВКА', hero: 'Доставка воды и продуктов',
    tagline: 'Повторы, маршруты, оборотная тара',
    points: ['CRM повторных заказов', 'Автоповторы и подписка', 'Маршруты курьеров', 'Учёт оборотной тары'],
    description: 'Доставка воды и продуктов держится на повторных заказах и LTV, а не на первом чеке — с летним пиком спроса в 1,5–2,5 раза. Разбираю CRM с автоповторами, маршрутизацию курьеров, учёт оборотной тары и маркировку «Честный знак» для воды.',
    relatedArticles: ['ai-dlya-logistiki-2026', 'avtomatizaciya-saun-ban-spa-2026', 'it-dlya-zoomagazina-gruminga-2027'],
    relatedOffers: ['dostavka-bot-povtornye-zakazy', 'tms-marshrutizaciya', 'programma-loyalnosti'],
  },
  {
    slug: 'ai-buhgalter-avtomatizaciya-rutiny-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · УЧЁТ', hero: 'AI-бухгалтер',
    tagline: 'OCR первички, авторазнесение, сверки',
    points: ['OCR счетов и УПД', 'Авторазнесение в 1С', 'Сверки расходов', 'Локальный или РФ-LLM'],
    description: 'Как AI забирает рутину бухгалтера — связка OCR и LLM распознаёт первичку и проводит её в 1С почти без участия человека. Разбираю сверки с банком и контрагентами, проверку должной осмотрительности и требования к данным: GigaChat, YandexGPT или локальная модель.',
    relatedArticles: ['ai-dlya-yurista-dokumenty-2026', 'ai-dlya-logistiki-2026', 'ai-dlya-sellerov-wb-ozon-2026'],
    relatedOffers: ['ai-konsultant', 'integraciya-sistem', 'audit-i-uskorenie-sayta'],
  },
  {
    slug: 'ai-dlya-yurista-dokumenty-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · ПРАВО', hero: 'AI для юриста',
    tagline: 'Драфты, проверка рисков, RAG',
    points: ['Генерация по шаблонам', 'Вычитка на риски', 'RAG по НПА и практике', 'Российский стек LLM'],
    description: 'Как AI ускоряет работу юриста с документами — первый драфт договора по шаблону, вычитка на риски, сравнение редакций и OCR сканов. Разбираю российский стек, RAG по КонсультантПлюс и судебной практике и почему проверка человеком обязательна на каждом документе.',
    relatedArticles: ['ai-buhgalter-avtomatizaciya-rutiny-2026', 'ai-dlya-logistiki-2026', 'ai-dlya-sellerov-wb-ozon-2026'],
    relatedOffers: ['it-yuridicheskaya-firma', 'ai-konsultant', 'integraciya-sistem'],
  },
  {
    slug: 'ai-dlya-logistiki-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · ЛОГИСТИКА', hero: 'AI для логистики',
    tagline: 'Маршруты, прогноз спроса, OCR накладных',
    points: ['ML-маршруты VRP', 'Прогноз спроса', 'OCR накладных', 'Динамические цены'],
    description: 'Логистика — одна из самых готовых к AI отраслей: ML-маршрутизация экономит 15–30 процентов топлива, а прогноз спроса снижает overstock. Разбираю задачу VRP, складскую автоматизацию, российский стек YandexGPT и GigaChat и риски 152-ФЗ при работе с данными получателей.',
    relatedArticles: ['ai-buhgalter-avtomatizaciya-rutiny-2026', 'ai-dlya-yurista-dokumenty-2026', 'dostavka-vody-produktov-2026'],
    relatedOffers: ['tms-marshrutizaciya', 'ai-konsultant', 'integraciya-sistem'],
  },
];
