module.exports = [
  {
    slug: 'yunit-ekonomika-osnovatelya-2026', kind: 'article',
    label: 'СТАРТАП И ПРОДУКТ', pill: 'ЮНИТ-ЭКОНОМИКА', hero: 'Юнит-экономика',
    tagline: 'Зарабатывает ли бизнес на клиенте',
    points: ['CAC и LTV', 'Правило LTV/CAC ≥ 3', 'Окупаемость CAC', 'Когорты и churn'],
    description: 'Разбор юнит-экономики для основателя — CAC, LTV, contribution margin, окупаемость привлечения и когортный анализ. Поможет понять, приносит ли каждый клиент прибыль и где точка безубыточности.',
    relatedArticles: ['saas-pricing-2026', 'biznes-plan-2026-shablon', 'voronka-prodazh-b2b-2026'],
    relatedOffers: ['skvoznaya-analitika-koltreking', 'prototip-poc-investor', 'cto-as-a-service'],
  },
  {
    slug: 'biznes-plan-2026-shablon', kind: 'article',
    label: 'СТАРТАП И ПРОДУКТ', pill: 'БИЗНЕС-ПЛАН', hero: 'Бизнес-план: шаблон',
    tagline: 'Структура плана, который читают',
    points: ['Типы и структура', 'Lean Canvas', 'Финансовая модель', 'Что читает инвестор'],
    description: 'Готовый шаблон бизнес-плана на 2026 год — структура, Lean Canvas, финмодель и требования разных получателей. Показывает на примере IT-стартапа, что инвесторы читают на самом деле и какие ошибки топят документ.',
    relatedArticles: ['yunit-ekonomika-osnovatelya-2026', 'kak-prevratit-ideyu-v-produkt-2027', 'saas-pricing-2026'],
    relatedOffers: ['prototip-poc-investor', 'cto-as-a-service', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'saas-pricing-2026', kind: 'article',
    label: 'СТАРТАП И ПРОДУКТ', pill: 'SAAS', hero: 'SaaS-ценообразование',
    tagline: 'Как назначить цену на подписку',
    points: ['7 моделей pricing', 'Тарифные планы', 'Юнит-экономика', 'A/B-тест цен'],
    description: 'Семь моделей ценообразования для SaaS, психология цен и три способа посчитать тариф с нуля. Разбирает деление на планы, особенности AI-продуктов и российского рынка, а также корректное A/B-тестирование.',
    relatedArticles: ['yunit-ekonomika-osnovatelya-2026', 'biznes-plan-2026-shablon', 'mvp-to-production-3-mesyatsa-2026'],
    relatedOffers: ['prototip-poc-investor', 'priem-platezhey-sbp', 'cto-as-a-service'],
  },
  {
    slug: 'it-dlya-stomatologiy-medcentrov-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'МЕДИЦИНА', hero: 'IT для стоматологии',
    tagline: 'Цифровизация частной клиники',
    points: ['МИС и расписание', 'Электронная медкарта', 'Снимки и PACS', 'CRM и удержание'],
    description: 'Обзор IT для стоматологий и медцентров — МИС, онлайн-запись, электронная медкарта, PACS и AI-диагностика. Затрагивает CRM удержания пациентов, телемедицину, работу со страховыми и требования к данным по 152-ФЗ.',
    relatedArticles: ['cifrovizaciya-fitnes-kluba-2026', 'it-dlya-pekarni-konditerskoy-2026', 'it-dlya-turizma-otelei-2026'],
    relatedOffers: ['zapis-salon-krasoty', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'cifrovizaciya-fitnes-kluba-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ФИТНЕС', hero: 'IT для фитнес-клуба',
    tagline: 'Учёт, доступ и удержание клиентов',
    points: ['CRM и абонементы', 'Контроль доступа', 'Расписание и бронь', 'Борьба с оттоком'],
    description: 'Разбор цифровизации фитнес-клуба — CRM, абонементы и заморозки, контроль доступа, онлайн-запись и мобильное приложение. Показывает, как удерживать участников, бороться с оттоком и считать зарплату тренеров.',
    relatedArticles: ['it-dlya-stomatologiy-medcentrov-2026', 'it-dlya-pekarni-konditerskoy-2026', 'it-dlya-turizma-otelei-2026'],
    relatedOffers: ['zapis-salon-krasoty', 'programma-loyalnosti', 'bot-dlya-biznesa'],
  },
  {
    slug: 'it-dlya-pekarni-konditerskoy-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ПЕКАРНЯ', hero: 'IT для пекарни',
    tagline: 'Учёт, производство и списания',
    points: ['Касса и заказы', 'План выпечки', 'Себестоимость по ТТК', 'Списания и FIFO'],
    description: 'Гид по IT для пекарни и кондитерской — касса, учёт заказов, план выпечки и калькуляция себестоимости по ТТК. Решает боль скоропорта: управление списаниями, переоценку к вечеру и контроль остатков сырья по FIFO.',
    relatedArticles: ['cifrovizaciya-fitnes-kluba-2026', 'it-dlya-stomatologiy-medcentrov-2026', 'svoy-magazin-vs-wildberries-ozon-2026'],
    relatedOffers: ['programma-loyalnosti', 'integraciya-sistem', 'bot-dlya-biznesa'],
  },
  {
    slug: 'it-dlya-turizma-otelei-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'ТУРИЗМ', hero: 'IT для туризма и отелей',
    tagline: 'PMS, каналы и прямые брони',
    points: ['PMS отеля', 'Channel Manager', 'Прямое бронирование', 'Динамические цены'],
    description: 'Обзор IT для туризма и отелей — PMS, Channel Manager, свой сайт с прямым бронированием и динамическое ценообразование. Затрагивает AI, управление гостями, финансовую аналитику и эквайринг для отрасли.',
    relatedArticles: ['cifrovizaciya-fitnes-kluba-2026', 'it-dlya-stomatologiy-medcentrov-2026', 'finteh-i-platezhi-dlya-biznesa-2027'],
    relatedOffers: ['bronirovanie-otel-glamping', 'priem-platezhey-sbp', 'integraciya-sistem'],
  },
  {
    slug: 'svoy-magazin-vs-wildberries-ozon-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'E-COMMERCE', hero: 'Свой магазин vs WB/Ozon',
    tagline: 'Где выгоднее продавать товар',
    points: ['Реальная комиссия', 'Плюсы и минусы', 'Математика выгоды', 'Гибридная стратегия'],
    description: 'Сравнение продаж на маркетплейсах и в собственном интернет-магазине — реальная структура комиссии WB и Ozon, плюсы и минусы каждого канала. Считает на трёх сценариях, когда выгоднее свой магазин, и разбирает гибридную стратегию и техстек.',
    relatedArticles: ['seo-internet-magazina-yandex-30-hakov-2026', 'live-commerce-rf-2026', 'it-dlya-pekarni-konditerskoy-2026'],
    relatedOffers: ['repraiser-wb-ozon', 'fulfilment-internet-magazina', 'sayt-distributora'],
  },
  {
    slug: 'finteh-i-platezhi-dlya-biznesa-2027', kind: 'article',
    label: 'ФИНТЕХ И ПЛАТЕЖИ', pill: 'ФИНТЕХ', hero: 'Финтех и платежи',
    tagline: 'Приём денег и финучёт без штрафов',
    points: ['Эквайринг и СБП', 'Касса и 54-ФЗ', 'Рассрочка и BNPL', 'Рекуррент и финмодель'],
    description: 'Разбор приёма платежей и финучёта для бизнеса — эквайринг, СБП, онлайн-касса по 54-ФЗ, рассрочка и регулярные платежи. Показывает управленческий учёт, антифрод по 152-ФЗ и пять типичных ошибок с деньгами.',
    relatedArticles: ['cfa-dlya-biznesa-2026', 'svoy-magazin-vs-wildberries-ozon-2026', 'saas-pricing-2026'],
    relatedOffers: ['priem-platezhey-sbp', 'skvoznaya-analitika-koltreking', 'integraciya-sistem'],
  },
  {
    slug: 'cfa-dlya-biznesa-2026', kind: 'article',
    label: 'ФИНТЕХ И ПЛАТЕЖИ', pill: 'ЦФА', hero: 'ЦФА для бизнеса',
    tagline: 'Цифровые активы по 259-ФЗ',
    points: ['ЦФА простыми словами', 'Закон 259-ФЗ', 'Кому подходит', 'Выпуск и налоги'],
    description: 'Объяснение цифровых финансовых активов для бизнеса — что такое ЦФА, как их регулирует 259-ФЗ и чем они отличаются от крипты и ценных бумаг. Разбирает кейсы, пошаговый выпуск, налоги и риски привлечения денег через ЦФА.',
    relatedArticles: ['finteh-i-platezhi-dlya-biznesa-2027', 'biznes-plan-2026-shablon', 'yunit-ekonomika-osnovatelya-2026'],
    relatedOffers: ['priem-platezhey-sbp', 'cto-as-a-service', 'integraciya-sistem'],
  },
];
