module.exports = [
  {
    slug: 'ai-dlya-sellerov-wb-ozon-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · WB/OZON', hero: 'AI для селлеров',
    tagline: 'Нейросети на маркетплейсах WB и Ozon',
    points: ['Карточки и SEO', 'Отзывы и вопросы', 'Аналитика и цены', 'Чат-боты поддержки'],
    description: 'Где AI реально помогает продавцу на Wildberries и Ozon — генерация карточек, работа с отзывами, аналитика и ценообразование. Разбор инструментов, российского стека и типовых ошибок без обещаний волшебных продаж.',
    relatedArticles: ['ai-v-povsednevnoy-zhizni-25-sposobov-2026', 'ai-buhgalter-avtomatizaciya-rutiny-2026', 'ai-dlya-logistiki-2026'],
    relatedOffers: ['repraiser-wb-ozon', 'ai-konsultant', 'upravlenie-postavkami-fbo-fbs'],
  },
  {
    slug: 'ai-avatary-cifrovye-dvoyniki-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · АВАТАРЫ', hero: 'AI-аватары и двойники',
    tagline: 'Видео без съёмок и цифровой двойник',
    points: ['Виды аватаров', 'Голосовые клоны', 'Локализация и липсинк', 'Биометрия и закон'],
    description: 'Как бизнесу применять AI-аватары и цифровых двойников — говорящие головы, автопрезентеры, голосовые клоны и локализация видео. Отдельно про биометрию, согласие и риски дипфейков с опорой на 152-ФЗ.',
    relatedArticles: ['ai-v-povsednevnoy-zhizni-25-sposobov-2026', 'svoya-strim-studiya-2026', 'mlm-kontent-zavod-ai-2026'],
    relatedOffers: ['ai-dvoynik-eksperta', 'ai-kontent-zavod', 'ai-konsultant'],
  },
  {
    slug: 'ai-v-povsednevnoy-zhizni-25-sposobov-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · ЖИЗНЬ', hero: 'AI в жизни: 25 способов',
    tagline: '25 сценариев AI для быта и работы',
    points: ['Здоровье и быт', 'Финансы и покупки', 'Карьера и работа', 'Творчество и семья'],
    description: 'Двадцать пять практических способов применять AI в повседневной жизни — здоровье, финансы, карьера, творчество и дом. Сравнительная таблица сервисов, доступных в России, и пять частых ошибок новичков.',
    relatedArticles: ['ai-dlya-sellerov-wb-ozon-2026', 'ai-avatary-cifrovye-dvoyniki-2026', 'ai-bot-v-max-gigachat-yandexgpt-2026'],
    relatedOffers: ['ai-konsultant', 'ai-kontent-zavod', 'ai-bot-kak-biznes'],
  },
  {
    slug: 'max-bot-restoran-kafe-2026', kind: 'article',
    label: 'МЕССЕНДЖЕРЫ И БОТЫ', pill: 'MAX · КАФЕ', hero: 'MAX-бот для кафе',
    tagline: 'Заказы, доставка и лояльность в MAX',
    points: ['Меню в Mini App', 'Доставка и бронь', 'Программа лояльности', 'Связка с iiko'],
    description: 'Зачем кафе и ресторану свой бот в MAX — меню, доставка, бронирование столика и программа лояльности. Разбор архитектуры, интеграции с iiko и r_keeper, экранов кухни и юридических нюансов HoReCa.',
    relatedArticles: ['max-bot-rieltor-2026', 'max-mini-apps-2026', 'chatbot-telegram-max-vk-2026'],
    relatedOffers: ['kofeynya', 'dostavka-bot-povtornye-zakazy', 'bot-dlya-biznesa'],
  },
  {
    slug: 'max-bot-rieltor-2026', kind: 'article',
    label: 'МЕССЕНДЖЕРЫ И БОТЫ', pill: 'MAX · РИЕЛТОР', hero: 'MAX-бот для риелтора',
    tagline: 'Подбор объектов и сделки в MAX',
    points: ['Парсинг базы', 'AI-подбор под клиента', 'AI-оценка квартиры', 'Запись на показ'],
    description: 'Как риелтору собрать бота в MAX — парсинг базы объявлений, AI-подбор под клиента, оценка стоимости квартиры и запись на показ. Воронка клиента, документы по сделке, cross-sell и юридические нюансы 2026 года.',
    relatedArticles: ['max-bot-restoran-kafe-2026', 'max-mini-apps-2026', 'chatbot-telegram-max-vk-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'ai-konsultant', 'max-mini-app-magazin'],
  },
  {
    slug: 'max-mini-apps-2026', kind: 'article',
    label: 'МЕССЕНДЖЕРЫ И БОТЫ', pill: 'MAX MINI APP', hero: 'MAX Mini Apps',
    tagline: 'Приложение внутри мессенджера MAX',
    points: ['MAX SDK основы', 'Дизайн под мобильный', 'Платежи в MAX', 'Монетизация'],
    description: 'Что такое MAX Mini Apps и чем они отличаются от Telegram и VK — SDK, дизайн под мобильное приложение, платежи и монетизация. Пошаговая разработка за две недели, стоимость и пять типичных ошибок.',
    relatedArticles: ['vk-mini-app-dlya-biznesa-2026', 'chatbot-telegram-max-vk-2026', 'max-bot-restoran-kafe-2026'],
    relatedOffers: ['max-mini-app-magazin', 'geymifikaciya-kanala-max', 'bot-dlya-biznesa'],
  },
  {
    slug: 'chatbot-telegram-max-vk-2026', kind: 'article',
    label: 'МЕССЕНДЖЕРЫ И БОТЫ', pill: 'БОТЫ', hero: 'Чат-бот TG, MAX, VK',
    tagline: 'Выбор платформы под задачу бизнеса',
    points: ['Где аудитория', 'Сравнение платформ', 'Приём оплат', 'No-code или код'],
    description: 'Зачем бизнесу чат-бот и как выбрать между Telegram, MAX и VK — где аудитория, сравнение платформ, приём оплат и интеграция с CRM. Разбор no-code конструкторов против кастомной разработки, стоимости и юридических нюансов.',
    relatedArticles: ['max-mini-apps-2026', 'vk-mini-app-dlya-biznesa-2026', 'ai-bot-v-max-gigachat-yandexgpt-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'ai-bot-kak-biznes', 'ai-konsultant'],
  },
  {
    slug: 'vk-mini-app-dlya-biznesa-2026', kind: 'article',
    label: 'МЕССЕНДЖЕРЫ И БОТЫ', pill: 'VK MINI APP', hero: 'VK Mini App',
    tagline: 'Приложение для бизнеса внутри VK',
    points: ['VK Bridge API', 'VKUI или свой дизайн', 'VK Pay платежи', 'Продвижение в каталоге'],
    description: 'Как сделать VK Mini App для бизнеса — технический стек, регистрация в Mini Apps Studio, VK Bridge и платежи через VK Pay. Сравнение с Telegram и MAX, продвижение в каталоге, B2B-сценарии и безопасность.',
    relatedArticles: ['max-mini-apps-2026', 'chatbot-telegram-max-vk-2026', 'svoy-sayt-vs-socseti-2026'],
    relatedOffers: ['max-mini-app-magazin', 'bot-dlya-biznesa', 'ai-konsultant'],
  },
  {
    slug: 'svoya-strim-studiya-2026', kind: 'article',
    label: 'МЕДИА И КОНТЕНТ', pill: 'СТРИМ', hero: 'Своя стрим-студия',
    tagline: 'Студия для стримов под свой бюджет',
    points: ['Три уровня студии', 'Микрофоны и камеры', 'Настройка OBS', 'Свет и звук'],
    description: 'Как собрать свою стрим-студию в 2026 году — три уровня по бюджету, выбор микрофонов, камер и аудио-интерфейсов. Пошаговая настройка OBS, мультикамерная схема, освещение и стоимость владения за год.',
    relatedArticles: ['podcast-s-gostyami-monetizaciya-2026', 'ai-avatary-cifrovye-dvoyniki-2026', 'mlm-kontent-zavod-ai-2026'],
    relatedOffers: ['podkast-studiya-distribuciya', 'platforma-vebinarov', 'ai-kontent-zavod'],
  },
  {
    slug: 'podcast-s-gostyami-monetizaciya-2026', kind: 'article',
    label: 'МЕДИА И КОНТЕНТ', pill: 'ПОДКАСТ', hero: 'Подкаст с гостями',
    tagline: 'Подкаст с гостями и его монетизация',
    points: ['Форматы с гостями', 'Технический стек', 'Repurposing контента', '7 моделей дохода'],
    description: 'Почему подкаст с гостями — сильная контент-стратегия и как его монетизировать — форматы, технический стек, поиск гостей и подготовка эпизода. Стратегия repurposing в пять форматов, семь моделей дохода и AI-инструменты подкастера.',
    relatedArticles: ['svoya-strim-studiya-2026', 'mlm-kontent-zavod-ai-2026', 'ai-avatary-cifrovye-dvoyniki-2026'],
    relatedOffers: ['podkast-studiya-distribuciya', 'ai-kontent-zavod', 'platforma-vebinarov'],
  },
];
