module.exports = [
  {
    slug: 'kibergigiena-sotrudnikov-2026', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'БЕЗОПАСНОСТЬ', hero: 'Кибергигиена команды',
    tagline: 'Человек — главная уязвимость',
    points: ['Фишинг и вишинг', 'Пароли и 2FA', 'Принцип минимума', 'Симуляции атак'],
    description: 'Более 80% инцидентов начинаются не со взлома, а с действия сотрудника: клик по ссылке, слабый пароль, разговор с «банком». Разбираем фишинг, двухфакторную защиту, управление доступами и обучение команды без наказания за честность.',
    relatedArticles: ['chek-list-bezopasnosti-sayta-47-punktov', 'utechki-pd-24-chasa-2026', 'oborotnye-shtrafy-utechki-pd-2026'],
    relatedOffers: ['152-fz-pod-klyuch', 'integraciya-sistem'],
  },
  {
    slug: 'oborotnye-shtrafy-utechki-pd-2026', kind: 'article',
    label: 'ПРАВО · 152-ФЗ', pill: '152-ФЗ', hero: 'Оборотные штрафы',
    tagline: 'Утечка — до 3% выручки',
    points: ['Штраф до 15 млн', 'Оборотные 1–3%', 'Уведомить за 24 ч', 'Аудит до проверки'],
    description: 'С 30 мая 2025 года по ФЗ-420 штрафы за утечку персональных данных выросли радикально: фиксированный за первую и оборотный 1–3% выручки за повторную. Разбираем суммы, уголовную статью, сроки уведомления РКН и смягчающие обстоятельства.',
    relatedArticles: ['audit-152-fz-2026', 'utechki-pd-24-chasa-2026', 'kibergigiena-sotrudnikov-2026'],
    relatedOffers: ['152-fz-pod-klyuch', 'audit-i-uskorenie-sayta'],
  },
  {
    slug: 'konkurs-priglasheniy-max-virusnyy-rost-2027', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'MAX · РОСТ', hero: 'Конкурс приглашений в MAX',
    tagline: 'Клиенты приводят клиентов',
    points: ['Реферальные ссылки', 'Живой рейтинг', 'Защита от накрутки', 'Запуск за 2 недели'],
    description: 'Вирусный рост — это когда аудиторию приводят сами клиенты, а не реклама. Главная механика для мессенджеров: конкурс приглашений с личными ссылками, живым рейтингом и призами топу — плюс защита от накрутки и аналитика вовлечения.',
    relatedArticles: ['sistemy-loyalnosti-2027', 'marketing-i-trafik-2027', 'kak-kreatoru-postavit-kontent-na-potok-2027'],
    relatedOffers: ['geymifikaciya-kanala-max', 'programma-loyalnosti'],
  },
  {
    slug: 'geo-chek-list-30-punktov-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'GEO', hero: 'GEO-чек-лист',
    tagline: 'Попасть в ответы ИИ',
    points: ['Техническая база', 'Контент и структура', 'Авторитетность', '30 пунктов аудита'],
    description: 'GEO-аудит проверяет сайт на готовность попадать в ответы ChatGPT, Perplexity и Алисы, а не в синие ссылки. 30 пунктов разбиты на пять блоков: техника, контент, авторитетность, присутствие на источниках и измерение результата.',
    relatedArticles: ['geomarketing-yandex-karty-2026', 'marketing-i-trafik-2027', 'rag-sistemy-dlya-biznesa-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'ai-kontent-zavod'],
  },
  {
    slug: 'geomarketing-yandex-karty-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'ГЕО · ЛОКАЛЬНО', hero: 'Геомаркетинг',
    tagline: 'Карты — витрина локалки',
    points: ['Яндекс.Бизнес и 2ГИС', 'Заполнить карточку', 'Отзывы легально', 'Рост рейтинга'],
    description: 'Для кафе, салона, СТО и клиники карты — основная витрина: клиент выбирает точку за десять секунд по рейтингу, отзывам и фото. Разбираем карточку в Яндекс.Бизнесе и 2ГИС, факторы ранжирования, сбор отзывов и платное продвижение.',
    relatedArticles: ['geo-chek-list-30-punktov-2026', 'marketing-i-trafik-2027', 'sistemy-loyalnosti-2027'],
    relatedOffers: ['ai-upravlenie-reputaciey', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'marketing-i-trafik-2027', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'АНАЛИТИКА', hero: 'Сквозная аналитика',
    tagline: 'Без измерения — слив бюджета',
    points: ['Сквозная аналитика', 'Лид-магниты и квизы', 'Возврат клиентов', 'Репутация и отзывы'],
    description: 'Маркетинг без измерения — это оплата догадок, а не результата. Фундамент системы — сквозная аналитика и коллтрекинг, которые связывают рекламный рубль с выручкой; дальше идут лид-магниты, удержание, AI-контент и работа с отзывами.',
    relatedArticles: ['sistemy-loyalnosti-2027', 'geomarketing-yandex-karty-2026', 'kak-kreatoru-postavit-kontent-na-potok-2027'],
    relatedOffers: ['skvoznaya-analitika-koltreking', 'ai-upravlenie-reputaciey'],
  },
  {
    slug: 'kak-kreatoru-postavit-kontent-na-potok-2027', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'КОНТЕНТ · AI', hero: 'Контент на поток',
    tagline: 'Система, а не вдохновение',
    points: ['Контент-завод', 'Нарезка на клипы', 'AI снимает рутину', 'Авто-дистрибуция'],
    description: 'Стабильный контент — это система: один источник смысла превращается в десяток единиц по регламенту. Принцип контент-завода, нарезка эфиров на клипы, AI для расшифровки и обложек, авто-постинг по площадкам и монетизация аудитории.',
    relatedArticles: ['marketing-i-trafik-2027', 'konkurs-priglasheniy-max-virusnyy-rost-2027', 'rossiyskiy-ai-stack-2026'],
    relatedOffers: ['ai-kontent-zavod', 'geymifikaciya-kanala-max'],
  },
  {
    slug: 'sistemy-loyalnosti-2027', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'ЛОЯЛЬНОСТЬ', hero: 'Системы лояльности',
    tagline: 'Удержание дешевле привлечения',
    points: ['Баллы и кешбэк', 'Подписка — тренд', 'Механика под нишу', 'LTV и retention'],
    description: 'Лояльность — это не «карта со скидкой», а система возврата клиента и роста повторных покупок. Разбираем баллы, кешбэк и платную подписку, выбор механики под нишу, внедрение через CRM и бот, экономику удержания и 152-ФЗ.',
    relatedArticles: ['marketing-i-trafik-2027', 'konkurs-priglasheniy-max-virusnyy-rost-2027', 'geomarketing-yandex-karty-2026'],
    relatedOffers: ['programma-loyalnosti', 'geymifikaciya-kanala-max'],
  },
  {
    slug: 'skolko-stoit-sayt-2026', kind: 'article',
    label: 'РАЗРАБОТКА', pill: 'РАЗРАБОТКА', hero: 'Сколько стоит сайт',
    tagline: 'Цены выросли на 30–50%',
    points: ['Пять категорий', 'Реальные вилки цен', 'Скрытые расходы', 'Где сэкономить'],
    description: 'Цены на разработку в РФ выросли на 30–50% за три года из-за роста зарплат и оттока специалистов. Разбираем пять категорий проектов с реальными вилками, пять факторов цены, скрытые расходы и способы сэкономить без потери качества.',
    relatedArticles: ['importozameshchenie-po-2026', 'marketing-i-trafik-2027', 'geo-chek-list-30-punktov-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'importozameshchenie-po-2026', kind: 'article',
    label: 'РАЗРАБОТКА', pill: 'ИМПОРТОЗАМЕЩЕНИЕ', hero: 'Импортозамещение ПО',
    tagline: 'Операционная необходимость',
    points: ['Реестр и преференции', 'CRM и офис', 'Облака в РФ', 'Self-hosted'],
    description: 'Импортозамещение в 2026 — не лозунг, а реальность: вендоры ушли, лицензии не продлеваются, для госсектора это требование закона. Разбираем реестр российского ПО, зрелые и незрелые ниши и стратегию self-hosted на своём сервере.',
    relatedArticles: ['skolko-stoit-sayt-2026', 'rossiyskiy-ai-stack-2026', 'lokalnyy-llm-na-noutbuke-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'importozameshchenie-ofisa'],
  },
];
