module.exports = [
  {
    slug: 'uskorenie-1c-postgresql', kind: 'article',
    label: 'РАЗРАБОТКА', pill: '1С · POSTGRESQL', hero: 'Ускорение 1С',
    tagline: 'Тюнинг PostgreSQL для 1С под нагрузку',
    points: ['Тюнинг ядра Linux', 'Тесты FIO и диска', 'Разбор postgresql.conf', 'Борьба с bloat'],
    description: 'Как разогнать связку 1С и PostgreSQL без замены железа — от тюнинга ядра Linux до тонкой настройки postgresql.conf. Стресс-тесты дисков через FIO, регламент autovacuum и pg_repack против раздувания базы.',
    relatedArticles: ['svoy-vps-dlya-razrabotchika-2026', 'importozameshchenie-po-2026', 'skolko-stoit-sayt-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'importozameshchenie-infrastruktura', 'integraciya-sistem'],
  },
  {
    slug: 'svoy-vps-dlya-razrabotchika-2026', kind: 'article',
    label: 'РАЗРАБОТКА', pill: 'ИНФРАСТРУКТУРА', hero: 'Свой VPS',
    tagline: 'Свой сервер на РФ-провайдере за 30 минут',
    points: ['РФ-провайдеры', 'Выбор по задачам', 'Настройка с нуля', 'Безопасность сервера'],
    description: 'Зачем разработчику свой VPS в 2026 и как выбрать между Selectel, RuVDS, Timeweb и Yandex Cloud. Пошаговая настройка сервера с нуля за полчаса с базовой защитой.',
    relatedArticles: ['uskorenie-1c-postgresql', 'importozameshchenie-po-2026', 'pwa-iz-sayta-za-vyhodnye-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'pwa-iz-sayta-za-vyhodnye-2026', kind: 'article',
    label: 'РАЗРАБОТКА', pill: 'PWA', hero: 'PWA из сайта',
    tagline: 'Приложение из сайта без магазинов',
    points: ['Файл manifest', 'Service Worker', 'Кнопка установки', 'Push и оффлайн'],
    description: 'Как превратить обычный сайт в устанавливаемое PWA-приложение за выходные. Манифест, Service Worker, оффлайн-режим, push-уведомления и кнопка установки без публикации в магазинах.',
    relatedArticles: ['svoy-vps-dlya-razrabotchika-2026', 'skolko-stoit-sayt-2026', 'marketing-i-trafik-2027'],
    relatedOffers: ['integraciya-sistem', 'audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'it-dlya-salonov-krasoty-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'КРАСОТА', hero: 'IT для салона красоты',
    tagline: 'Онлайн-запись и CRM против простоев',
    points: ['Онлайн-запись', 'CRM салона', 'Меньше неявок', 'Программа лояльности'],
    description: 'Полный IT-стек салона красоты на 2026 год: онлайн-запись, CRM и пять механик против неявок клиентов. Лояльность, соцсети-витрина, AI и аналитика финансов для бьюти-индустрии.',
    relatedArticles: ['avtomatizaciya-roznica-14-dney', 'sistemy-loyalnosti-2027', 'priem-platezhey-sbp-sayt'],
    relatedOffers: ['zapis-salon-krasoty', 'programma-loyalnosti', 'priem-platezhey-sbp'],
  },
  {
    slug: 'avtomatizaciya-roznica-14-dney', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'РОЗНИЦА', hero: 'Розница за 14 дней',
    tagline: 'Товароучёт и касса под 54-ФЗ за 14 дней',
    points: ['МойСклад или 1С', 'Аудит склада', 'Касса и маркировка', 'Запуск за 14 дней'],
    description: 'Пошаговый план автоматизации розничного магазина за две недели: выбор между МойСклад и 1С:Розница, аудит склада, кассовое оборудование и маркировка. Запуск кассовой зоны по 54-ФЗ и работа с саботажем персонала.',
    relatedArticles: ['it-dlya-salonov-krasoty-2026', 'sistemy-loyalnosti-2027', 'priem-platezhey-sbp-sayt'],
    relatedOffers: ['chestnyy-znak-markirovka', 'wms-ai-prognoz', 'programma-loyalnosti'],
  },
  {
    slug: 'it-dlya-horeca-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'HORECA', hero: 'IT для общепита',
    tagline: 'POS, доставка и лояльность для кафе',
    points: ['POS-система', 'Складской учёт', 'Свой бот доставки', 'Лояльность гостей'],
    description: 'IT-набор для общепита на 2026 год: POS-системы, складской учёт и закупки, свой сайт с ботом доставки против комиссий агрегаторов. Лояльность, бронь столиков, AI-помощник и аналитика финансов.',
    relatedArticles: ['avtomatizaciya-roznica-14-dney', 'sistemy-loyalnosti-2027', 'priem-platezhey-sbp-sayt'],
    relatedOffers: ['kofeynya', 'dostavka-bot-povtornye-zakazy', 'chestnyy-znak-markirovka'],
  },
  {
    slug: 'it-dlya-avtoservisa-2026', kind: 'article',
    label: 'ОТРАСЛИ', pill: 'АВТО', hero: 'IT для автосервиса',
    tagline: 'CRM, заказ-наряд и подбор запчастей',
    points: ['CRM для СТО', 'Онлайн-запись на ТО', 'Электронный наряд', 'Подбор запчастей'],
    description: 'IT-стек автосервиса на 2026 год: CRM, онлайн-запись на ТО, электронный заказ-наряд и подбор запчастей по API. Диагностика с AI, отзывы, лояльность и расчёт зарплат механиков.',
    relatedArticles: ['avtomatizaciya-roznica-14-dney', 'sistemy-loyalnosti-2027', 'priem-platezhey-sbp-sayt'],
    relatedOffers: ['avtoservis', 'avtomoyka-deteyling', 'programma-loyalnosti'],
  },
  {
    slug: 'priem-platezhey-sbp-sayt', kind: 'article',
    label: 'ФИНТЕХ И ПЛАТЕЖИ', pill: 'СБП', hero: 'Приём по СБП',
    tagline: 'Комиссия 0,4–0,7% вместо эквайринга',
    points: ['Комиссия от 0,4%', 'BNPL и рассрочка', 'API на сайте', 'Удобный checkout'],
    description: 'Как принимать оплату по СБП с комиссией 0,4–0,7% вместо 1,5–3,5% классического эквайринга. Подключение BNPL и рассрочки для роста чека, API-интеграция на сайт и проектирование удобной страницы оплаты.',
    relatedArticles: ['cifrovoy-rubl-dlya-biznesa-2026', 'biznes-na-marketpleysah-2027', 'skolko-stoit-sayt-2026'],
    relatedOffers: ['priem-platezhey-sbp', 'integraciya-sistem', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'cifrovoy-rubl-dlya-biznesa-2026', kind: 'article',
    label: 'ФИНТЕХ И ПЛАТЕЖИ', pill: 'ФИНТЕХ', hero: 'Цифровой рубль',
    tagline: 'Третья форма денег и низкие комиссии',
    points: ['Третья форма денег', 'Платформа ЦБ', 'Смарт-контракты', 'Низкие комиссии'],
    description: 'Что такое цифровой рубль как третья форма денег и чем он отличается от безнала и криптовалюты. Платформа ЦБ, сроки внедрения, программируемые платежи и приём цифрового рубля на кассе бизнеса.',
    relatedArticles: ['priem-platezhey-sbp-sayt', 'biznes-na-marketpleysah-2027', 'importozameshchenie-po-2026'],
    relatedOffers: ['priem-platezhey-sbp', 'integraciya-sistem', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'biznes-na-marketpleysah-2027', kind: 'article',
    label: 'ФИНТЕХ И ПЛАТЕЖИ', pill: 'МАРКЕТПЛЕЙСЫ', hero: 'Юнит-экономика селлера',
    tagline: 'Маржа на WB и Ozon через автоматизацию',
    points: ['Карточки и SEO', 'Репрайсер цен', 'Прогноз поставок', 'Юнит-экономика SKU'],
    description: 'Как селлеру выйти в плюс на WB и Ozon в 2027 за счёт автоматизации, а не ручного труда. Карточки и ключевые слова, репрайсер под маржу, прогноз поставок FBO/FBS и юнит-экономика по каждому SKU.',
    relatedArticles: ['priem-platezhey-sbp-sayt', 'cifrovoy-rubl-dlya-biznesa-2026', 'marketing-i-trafik-2027'],
    relatedOffers: ['repraiser-wb-ozon', 'wms-ai-prognoz', 'skvoznaya-analitika-koltreking'],
  },
];
