module.exports = [
  {
    slug: 'it-dlya-fermerov-zabaykalya-buryatii-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'АПК',
    hero: 'IT для фермеров',
    tagline: 'Цифра бережёт время фермера',
    points: [
      'Учёт стада и полей',
      'Маркировка и ветучёт',
      'Сбыт и продажи онлайн',
      'Гранты и господдержка',
    ],
    description: 'Фермеру в регионе IT нужно не ради ERP, а ради контроля: где скотина, что с молоком и какие документы горят. Простые инструменты учёта, маркировки и онлайн-сбыта закрывают рутину без раздутого софта.',
    relatedArticles: ['cifrovizaciya-agrosektora-2026', 'it-torgovlya-s-kitaem-zabaykalsk-2026'],
    relatedOffers: ['agro-tochnoe-zemledelie', 'syrovarnya-ferma', 'paseka-pchelovodstvo'],
  },
  {
    slug: 'cifrovizaciya-agrosektora-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'АГРО',
    hero: 'Цифровизация агросектора',
    tagline: 'Точное земледелие — больше с гектара',
    points: [
      'Поля и севооборот',
      'Датчики и дроны в поле',
      '«Меркурий», маркировка',
      'Прямые продажи фермера',
    ],
    description: 'Цифровизация поднимает урожайность и срезает издержки за счёт учёта полей, датчиков, дронов и точного земледелия. Российские платформы и господдержка делают переход подъёмным даже для среднего хозяйства.',
    relatedArticles: ['it-dlya-fermerov-zabaykalya-buryatii-2026', 'cifrovizaciya-snt-tszh-2026'],
    relatedOffers: ['agro-tochnoe-zemledelie', 'teplicy-gidroponika', 'integraciya-sistem'],
  },
  {
    slug: 'cifrovizaciya-snt-tszh-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'СНТ · ТСЖ',
    hero: 'IT для СНТ и ТСЖ',
    tagline: 'Взносы и собрания — под контролем',
    points: [
      'Учёт взносов и долгов',
      'Собрания и голосование',
      'Шлагбаум и видеонадзор',
      'ГИС ЖКХ и безнал',
    ],
    description: 'Председателю IT снимает хаос с взносами, собраниями и должниками и закрывает обязанности по ГИС ЖКХ. Учёт, онлайн-голосования и безналичные платежи делают товарищество прозрачным для жильцов.',
    relatedArticles: ['cifrovizaciya-agrosektora-2026', 'lokalnoe-prodvizhenie-chita-ulan-ude-2026'],
    relatedOffers: ['integraciya-sistem', 'bot-dlya-biznesa', 'programma-loyalnosti'],
  },
  {
    slug: 'it-dlya-letnih-verand-obshchepita-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'ОБЩЕПИТ',
    hero: 'IT для летних веранд',
    tagline: 'Запуск IT к сезону — за неделю',
    points: [
      'QR-меню, заказ стола',
      'Касса в аренду, 54-ФЗ',
      'СБП, QR и чаевые',
      'Акции и доставка',
    ],
    description: 'У сезонной точки нет времени на долгое внедрение — IT поднимают за неделю на аренде оборудования. QR-меню, заказ со стола и быстрые оплаты разгружают персонал, который не успевает обучиться.',
    relatedArticles: ['it-dlya-svadebnyh-event-agentstv-2026', 'glamping-bazy-otdyha-2026'],
    relatedOffers: ['dostavka-bot-povtornye-zakazy', 'programma-loyalnosti', 'bot-dlya-biznesa'],
  },
  {
    slug: 'it-dlya-svadebnyh-event-agentstv-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'EVENT',
    hero: 'IT для event-агентств',
    tagline: 'От заявки до тайминга — в одной системе',
    points: [
      'Воронка мероприятия',
      'Сметы и подрядчики',
      'Тайминг дня события',
      'Личный кабинет клиента',
    ],
    description: 'Event-агентству IT собирает в одну систему заявки, сметы, подрядчиков и тайминг мероприятия. CRM-воронка и кабинет клиента убирают хаос из переписок и таблиц в разгар сезона.',
    relatedArticles: ['it-dlya-letnih-verand-obshchepita-2026', 'lokalnoe-prodvizhenie-chita-ulan-ude-2026'],
    relatedOffers: ['it-event-agentstvo', 'crm-turagentstvo', 'programma-loyalnosti'],
  },
  {
    slug: 'it-torgovlya-s-kitaem-zabaykalsk-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'КИТАЙ',
    hero: 'Торговля с Китаем',
    tagline: 'Забайкальск — ворота в Китай',
    points: [
      'Старт ВЭД и документы',
      'Сайт под аудиторию КНР',
      'Расчёты и платежи',
      'Логистика и таможня',
    ],
    description: 'Забайкальск даёт прямой выход на китайский рынок, но старт ВЭД требует документов, расчётов и логистики. Сайт под китайскую аудиторию и налаженные платежи снижают риски и ускоряют сделки.',
    relatedArticles: ['it-dlya-fermerov-zabaykalya-buryatii-2026', 'lokalnoe-prodvizhenie-chita-ulan-ude-2026'],
    relatedOffers: ['sayt-distributora', 'b2b-portal-opt', 'integraciya-sistem'],
  },
  {
    slug: 'sanatorii-medtourizm-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'МЕДТУРИЗМ',
    hero: 'Санатории и медтуризм',
    tagline: 'МИС — сердце санатория',
    points: [
      'МИС и мед.карта гостя',
      'Бронирование путёвок',
      'Расписание процедур',
      'ОМС, ДМС и соцпутёвки',
    ],
    description: 'Санаторий держится на МИС, которая связывает бронь путёвок, мед.карту гостя и расписание процедур. Учёт ОМС, ДМС и соцпутёвок плюс бот гостя повышают загрузку и долю повторных заездов.',
    relatedArticles: ['glamping-bazy-otdyha-2026', 'it-dlya-letnih-verand-obshchepita-2026'],
    relatedOffers: ['sanatorii-medturizm', 'bronirovanie-otel-glamping', 'programma-loyalnosti'],
  },
  {
    slug: 'glamping-bazy-otdyha-2026',
    kind: 'article',
    label: 'ОТРАСЛИ',
    pill: 'ТУРИЗМ',
    hero: 'Глэмпинг и базы отдыха',
    tagline: 'Прямая бронь вместо комиссий агрегаторов',
    points: [
      'Шахматка домиков',
      'Свой сайт без комиссий',
      'Динамические цены',
      'Заселение по коду',
    ],
    description: 'Глэмпингу прямое бронирование с сайта и шахматка домиков возвращают маржу, уходящую агрегаторам. Динамические цены, бот-консьерж и бесконтактное заселение поднимают загрузку и средний чек.',
    relatedArticles: ['sanatorii-medtourizm-2026', 'setevoy-biznes-v-turizme-2026'],
    relatedOffers: ['bronirovanie-otel-glamping', 'apart-otel-posutochnaya', 'programma-loyalnosti'],
  },
];
