module.exports = [
  {
    slug: 'rossiyskiy-ai-stack-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · 152-ФЗ', hero: 'Российский AI-стек',
    tagline: 'Чем заменить зарубежный AI',
    points: ['YandexGPT 5', 'GigaChat 3', 'Данные в РФ', 'Под каждую задачу'],
    description: 'Разбор российских языковых моделей и сервисов генерации — YandexGPT, GigaChat, T-Bank AI, Cotype, Kandinsky. Поможет выбрать легальную замену OpenAI и Gemini с хранением данных в РФ.',
    relatedArticles: ['rag-sistemy-dlya-biznesa-2026', 'lokalnyy-llm-na-noutbuke-2026', 'ai-agenty-vs-chatboty-2027'],
    relatedOffers: ['ai-konsultant', 'importozameshchenie-infrastruktura', 'bot-dlya-biznesa'],
  },
  {
    slug: 'rag-sistemy-dlya-biznesa-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI', hero: 'RAG для бизнеса',
    tagline: 'AI отвечает по вашим данным',
    points: ['Векторная база', 'Чанкинг и поиск', 'Запрет галлюцинаций', 'Ответ по документам'],
    description: 'Объясняет, как собрать RAG-систему: векторные базы, эмбеддинги, чанкинг, reranking и промпты против галлюцинаций. Полезно тем, кому нужен AI, отвечающий строго по корпоративным документам.',
    relatedArticles: ['rossiyskiy-ai-stack-2026', 'ai-chatbot-prodazhi-2027', 'ai-agenty-vs-chatboty-2027'],
    relatedOffers: ['ai-konsultant', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'ai-agenty-vs-chatboty-2027', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI', hero: 'AI-агенты vs боты',
    tagline: 'Когда нужен агент, а когда бот',
    points: ['Бот по сценарию', 'Агент с действиями', 'Риски и контроль', 'Цена и этапы'],
    description: 'Сравнивает кнопочные боты, LLM-боты и автономных AI-агентов: где какой подход оправдан, какие риски и сколько стоит. Поможет не переплатить за агента там, где хватит простого бота.',
    relatedArticles: ['rag-sistemy-dlya-biznesa-2026', 'ai-chatbot-prodazhi-2027', 'vnedrenie-ai-dorozhnaya-karta-90-dney-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'ai-konsultant', 'integraciya-sistem'],
  },
  {
    slug: 'lokalnyy-llm-na-noutbuke-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · ПРИВАТНО', hero: 'Локальный LLM',
    tagline: 'Приватный AI без облака',
    points: ['Ollama и LM Studio', 'Данные не уходят', 'Требования к железу', 'Локальный RAG'],
    description: 'Практический гид по запуску LLM на своём ноутбуке через Ollama, LM Studio и vLLM — с требованиями к памяти и бенчмарками. Подойдёт тем, кому важна приватность и работа без облака.',
    relatedArticles: ['rossiyskiy-ai-stack-2026', 'rag-sistemy-dlya-biznesa-2026', 'ai-agenty-vs-chatboty-2027'],
    relatedOffers: ['ai-konsultant', 'importozameshchenie-infrastruktura', 'cto-as-a-service'],
  },
  {
    slug: 'vnedrenie-ai-dorozhnaya-karta-90-dney-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI', hero: 'Внедрение AI за 90 дней',
    tagline: 'Дорожная карта на три месяца',
    points: ['Месяц 1: задачи', 'Месяц 2: пилот', 'Месяц 3: масштаб', 'Честный расчёт ROI'],
    description: 'Пошаговый план внедрения AI за 90 дней: выбор первой задачи, пилот, измерение и масштабирование без слитого бюджета. Полезно руководителям, которые хотят первый результат, а не эксперименты.',
    relatedArticles: ['ai-agenty-vs-chatboty-2027', 'rag-sistemy-dlya-biznesa-2026', 'ai-chatbot-prodazhi-2027'],
    relatedOffers: ['ai-konsultant', 'cto-as-a-service', 'integraciya-sistem'],
  },
  {
    slug: 'ai-chatbot-prodazhi-2027', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · ПРОДАЖИ', hero: 'AI-ассистент продаж',
    tagline: 'AI квалифицирует лиды и закрывает',
    points: ['Связка с CRM', 'Квалификация лидов', 'Telegram и VK', 'Контроль токенов'],
    description: 'Как собрать AI-ассистента продаж на RAG с интеграцией в amoCRM, Битрикс24, Telegram и VK. Поможет автоматизировать квалификацию лидов, FAQ и статусы заказов с контролем расходов на токены.',
    relatedArticles: ['rag-sistemy-dlya-biznesa-2026', 'ai-agenty-vs-chatboty-2027', 'vnedrenie-ai-dorozhnaya-karta-90-dney-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'ai-konsultant', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'chek-list-bezopasnosti-sayta-47-punktov', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'БЕЗОПАСНОСТЬ', hero: 'Безопасность сайта',
    tagline: '47 пунктов самопроверки',
    points: ['HTTPS и сертификаты', 'OWASP-уязвимости', 'Сессии и доступ', 'Утечки и сервер'],
    description: 'Чек-лист из 47 пунктов для самостоятельной проверки безопасности сайта: HTTPS, OWASP, аутентификация, утечки данных и инфраструктура. Поможет закрыть очевидные дыры до того, как их найдут злоумышленники.',
    relatedArticles: ['zashchita-sayta-ot-botov-parsinga-2027', 'audit-152-fz-2026', 'utechki-pd-24-chasa-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', '152-fz-pod-klyuch', 'cto-as-a-service'],
  },
  {
    slug: 'audit-152-fz-2026', kind: 'article',
    label: 'ПРАВО · 152-ФЗ', pill: '152-ФЗ', hero: 'Аудит 152-ФЗ',
    tagline: 'Проверка перед оборотным штрафом',
    points: ['Кому нужно', 'Что проверяют', 'Штрафы 2026', 'Правильное согласие'],
    description: 'Разбор аудита по 152-ФЗ: кому он обязателен, что проверяют, какие штрафы действуют в 2026 году и как оформить согласие на обработку ПД. Полезно бизнесу, который собирает персональные данные клиентов.',
    relatedArticles: ['utechki-pd-24-chasa-2026', 'oborotnye-shtrafy-utechki-pd-2026', 'chek-list-bezopasnosti-sayta-47-punktov'],
    relatedOffers: ['152-fz-pod-klyuch', 'audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'utechki-pd-24-chasa-2026', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: '152-ФЗ', hero: 'Утечка ПД: 24 часа',
    tagline: 'Уведомить РКН за 24 часа',
    points: ['Первые 60 минут', 'Факты за 4 часа', 'РКН за 24 часа', 'Субъекты за 72 часа'],
    description: 'Пошаговый план действий при утечке персональных данных: что делать в первый час, как собрать факты и уложиться в сроки уведомления РКН и субъектов. Поможет избежать оборотных штрафов при инциденте.',
    relatedArticles: ['audit-152-fz-2026', 'oborotnye-shtrafy-utechki-pd-2026', 'chek-list-bezopasnosti-sayta-47-punktov'],
    relatedOffers: ['152-fz-pod-klyuch', 'audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'zashchita-sayta-ot-botov-parsinga-2027', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'БЕЗОПАСНОСТЬ', hero: 'Защита от парсинга',
    tagline: 'Стоп парсингу и накруткам',
    points: ['Защита цен', 'Стоп накруткам', 'Rate limiting и WAF', 'Без вреда SEO'],
    description: 'Как защитить сайт от парсинга цен, накруток заявок и вредных ботов через rate limiting, поведенческий анализ, капчу и WAF. Поможет отсечь ботов, не закрыв при этом YandexBot и Googlebot.',
    relatedArticles: ['chek-list-bezopasnosti-sayta-47-punktov', 'audit-152-fz-2026', 'utechki-pd-24-chasa-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'cto-as-a-service', 'integraciya-sistem'],
  },
];
