module.exports = [
  {
    slug: 'svoy-sayt-vs-socseti-2026',
    kind: 'article',
    label: 'МЕДИА И КОНТЕНТ',
    pill: 'КОНТЕНТ',
    hero: 'Свой сайт vs соцсети',
    tagline: 'Соцсети — аренда, сайт — ваш актив',
    points: [
      'В соцсети вы арендатор',
      'Сайт-хаб, соцсети-окна',
      'Аудиторию ведём к себе',
      'Свой стек по бюджету',
    ],
    description: 'В соцсетях вы не владеете ни аудиторией, ни охватом — алгоритм решает за вас. Свой сайт становится хабом, а соцсети превращаются в спицы для распределения трафика.',
    relatedArticles: ['mlm-svoy-sayt-distributora-2026', 'tilda-vs-kastomnaya-razrabotka-2026', 'podcast-s-gostyami-monetizaciya-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'sayt-distributora'],
  },
  {
    slug: 'mlm-cifrovaya-duplikaciya-2026',
    kind: 'article',
    label: 'СЕТЕВОЙ БИЗНЕС',
    pill: 'MLM',
    hero: 'Цифровая дупликация',
    tagline: 'Один лидер обучает тысячи без выгорания',
    points: [
      'Ручной онбординг — стоп',
      'Новичок готов за 72 ч',
      'Бот-наставник и LMS',
      'CRM учёт активности',
    ],
    description: 'Лидер становится узким горлышком, когда обучает каждого новичка вручную. Цифровая дупликация переносит онбординг, обучение и контроль на автоматику — структура растёт без выгорания.',
    relatedArticles: ['mlm-svoy-sayt-distributora-2026', 'mlm-kontent-zavod-ai-2026', 'chatbot-telegram-max-vk-2026'],
    relatedOffers: ['sayt-distributora', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'mlm-industrii-gde-rabotaet-2026',
    kind: 'article',
    label: 'СЕТЕВОЙ БИЗНЕС',
    pill: 'MLM',
    hero: 'Где работает MLM',
    tagline: 'Старые ниши сдуваются, новые растут',
    points: [
      'БАДы и косметика сыты',
      'Инфобизнес без доверия',
      'Крипто-хайпы опасны',
      'Travel и подписки — рост',
    ],
    description: 'Классические ниши вроде БАДов, косметики и инфобизнеса перенасыщены и теряют доверие рынка. Жизнеспособность сегодня показывают travel-клубы и подписочные модели с реальной ценностью.',
    relatedArticles: ['mlm-cifrovaya-duplikaciya-2026', 'mlm-svoy-sayt-distributora-2026', 'mlm-kontent-zavod-ai-2026'],
    relatedOffers: ['sayt-distributora', 'ai-konsultant'],
  },
  {
    slug: 'mlm-svoy-sayt-distributora-2026',
    kind: 'article',
    label: 'СЕТЕВОЙ БИЗНЕС',
    pill: 'MLM',
    hero: 'Сайт дистрибьютора',
    tagline: 'Реплика делает вас как все',
    points: [
      'Реплика — лиды чужие',
      'Свой сайт — личный бренд',
      'Лид-магнит ловит базу',
      'Сайт — бот — CRM',
    ],
    description: 'На реплике компании вы неотличимы от тысяч других, а лиды уходят не вам. Свой сайт строит личный бренд и собирает контакты в собственную базу через понятную воронку.',
    relatedArticles: ['mlm-cifrovaya-duplikaciya-2026', 'mlm-kontent-zavod-ai-2026', 'svoy-sayt-vs-socseti-2026'],
    relatedOffers: ['sayt-distributora', 'bot-dlya-biznesa', 'integraciya-sistem'],
  },
  {
    slug: 'mlm-kontent-zavod-ai-2026',
    kind: 'article',
    label: 'СЕТЕВОЙ БИЗНЕС',
    pill: 'MLM · AI',
    hero: 'AI-контент для сетевика',
    tagline: 'Контент-план на месяц за один час',
    points: [
      'AI снимает выгорание',
      'Контент-план за час',
      'Готовые промпты',
      'Бренд, а не реклама',
    ],
    description: 'Сетевик выгорает, придумывая посты каждый день вручную. AI собирает контент-план на месяц за час и помогает звучать живо, продвигая личный бренд, а не рекламу компании.',
    relatedArticles: ['mlm-svoy-sayt-distributora-2026', 'mlm-cifrovaya-duplikaciya-2026', 'ai-avatary-cifrovye-dvoyniki-2026'],
    relatedOffers: ['ai-kontent-zavod', 'sayt-distributora', 'ai-konsultant'],
  },
  {
    slug: 'svoy-oblachnyy-disk-2026',
    kind: 'article',
    label: 'РАЗРАБОТКА',
    pill: 'ОБЛАКО',
    hero: 'Свой облачный диск',
    tagline: 'Nextcloud — файлы на вашем сервере',
    points: [
      'Свой диск без подписок',
      'Nextcloud — лидер',
      'Разворот на Docker',
      'Бэкапы по схеме 3-2-1',
    ],
    description: 'Аренда чужого облака — это вечная подписка и чужой контроль над вашими файлами. Nextcloud на собственном сервере даёт хранилище, синхронизацию и редактирование под полным контролем.',
    relatedArticles: ['tilda-vs-kastomnaya-razrabotka-2026', 'razrabotka-dlya-meditsiny-2026', 'dostupnost-sayta-a11y-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'cto-as-a-service', 'integraciya-sistem'],
  },
  {
    slug: 'tilda-vs-kastomnaya-razrabotka-2026',
    kind: 'article',
    label: 'РАЗРАБОТКА',
    pill: 'TILDA',
    hero: 'Tilda vs кастом',
    tagline: 'Выбор по задачам, а не по моде',
    points: [
      'Tilda — для старта',
      'Кастом — для логики',
      'Скорость и SEO решают',
      'Гибрид Tilda и кастом',
    ],
    description: 'Tilda отлично подходит для быстрого старта, но упирается в потолок на сложной логике и нагрузке. Кастомная разработка выигрывает по скорости, безопасности и контролю, а гибрид объединяет оба подхода.',
    relatedArticles: ['svoy-sayt-vs-socseti-2026', 'dostupnost-sayta-a11y-2026', 'mlm-svoy-sayt-distributora-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'dostupnost-sayta-a11y-2026',
    kind: 'article',
    label: 'РАЗРАБОТКА',
    pill: 'A11Y',
    hero: 'Доступность сайта',
    tagline: 'Доступность — это охват, SEO и закон',
    points: [
      'Стандарт WCAG 2.2',
      'Виджет не решает',
      'Доступность даёт SEO',
      'Проверка за 5 минут',
    ],
    description: 'Доступность открывает сайт людям с ограничениями и одновременно улучшает позиции в поиске. Накладные виджеты проблему не решают — нужны правки в коде по стандарту WCAG 2.2.',
    relatedArticles: ['tilda-vs-kastomnaya-razrabotka-2026', 'razrabotka-dlya-meditsiny-2026', 'svoy-sayt-vs-socseti-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'cto-as-a-service'],
  },
  {
    slug: 'razrabotka-dlya-meditsiny-2026',
    kind: 'article',
    label: 'РАЗРАБОТКА',
    pill: 'МЕДИЦИНА',
    hero: 'Разработка для медицины',
    tagline: 'Закон идёт впереди кода',
    points: [
      'Жёсткое регулирование',
      'Особый режим 152-ФЗ',
      'Регистрация в РЗН',
      'Безопасность глубже',
    ],
    description: 'Медицинский IT работает в самой зарегулированной отрасли, где закон важнее кода. Особый режим 152-ФЗ, регистрация ПО и усиленная безопасность — обязательная база, а не опция.',
    relatedArticles: ['svoy-oblachnyy-disk-2026', 'dostupnost-sayta-a11y-2026', 'tilda-vs-kastomnaya-razrabotka-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'cto-as-a-service', 'integraciya-sistem'],
  },
  {
    slug: 'ai-bot-v-max-gigachat-yandexgpt-2026',
    kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ',
    pill: 'AI · MAX',
    hero: 'AI-бот в MAX',
    tagline: 'Российский AI-бот в мессенджере MAX',
    points: [
      'AI-бот живёт в MAX',
      'GigaChat или YandexGPT',
      'Подключение по шагам',
      'Сценарии под бизнес',
    ],
    description: 'AI-бот в мессенджере MAX отвечает клиентам на российских моделях GigaChat или YandexGPT. Архитектура понятна, подключение идёт по шагам, а сценарии настраиваются под задачи бизнеса.',
    relatedArticles: ['chatbot-telegram-max-vk-2026', 'max-mini-apps-2026', 'mlm-kontent-zavod-ai-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'ai-konsultant', 'ai-bot-kak-biznes'],
  },
];
