module.exports = [
  {
    slug: 'ai-agenty-v-biznese-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · АГЕНТЫ', hero: 'AI-агенты в бизнесе',
    tagline: 'Где агенты работают, а где это хайп',
    points: ['7 рабочих сценариев', 'Фреймворки и код', 'Стоимость в проде', 'Юр-нюансы по РФ'],
    description: 'Разбор, что такое AI-агент и где он реально работает, а где это маркетинговая ловушка 2026 года. Семь рабочих сценариев, фреймворки, стоимость в проде, юридические нюансы по РФ и топ ошибок внедрения.',
    relatedArticles: ['mcp-model-context-protocol-2026', 'ai-chatbot-na-sayt-bez-programmirovaniya-2026', 'ai-v-marketinge-2026'],
    relatedOffers: ['ai-konsultant', 'ai-obrabotka-tiketov', 'bot-dlya-biznesa'],
  },
  {
    slug: 'mcp-model-context-protocol-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · MCP', hero: 'MCP для AI',
    tagline: 'Протокол, что связывает AI с данными',
    points: ['Архитектура MCP', 'Готовые серверы', 'Свой MCP-сервер', 'Безопасность'],
    description: 'Что такое протокол MCP простыми словами и какую проблему он решает в связке AI с внешними данными. Архитектура, готовые серверы, запуск своего сервера, сравнение с function calling и безопасность.',
    relatedArticles: ['ai-agenty-v-biznese-2026', 'ai-chatbot-na-sayt-bez-programmirovaniya-2026', 'self-hosted-infrastruktura-2026'],
    relatedOffers: ['ai-konsultant', 'cto-as-a-service', 'ai-obrabotka-tiketov'],
  },
  {
    slug: 'ai-transkripciya-soveshchaniy-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI', hero: 'AI-транскрипция',
    tagline: 'Текст и саммари встреч за выходные',
    points: ['Whisper за 5 минут', 'Локально или облако', 'Диаризация спикеров', 'Саммари встречи'],
    description: 'Как собрать AI-ассистента для встреч на Whisper — от установки за пять минут до саммари совещания. Локальная транскрипция против облачной, диаризация спикеров, интеграции и юр-нюансы по РФ.',
    relatedArticles: ['ai-v-marketinge-2026', 'self-hosted-infrastruktura-2026', 'ai-agenty-v-biznese-2026'],
    relatedOffers: ['ai-obrabotka-tiketov', 'ai-konsultant', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'ai-v-marketinge-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · МАРКЕТИНГ', hero: 'AI в маркетинге',
    tagline: 'Где AI побеждает маркетолога, а где нет',
    points: ['Контент на потоке', 'SEO в 2026', 'Промпты для задач', 'Реклама и соцсети'],
    description: 'Что реально изменил AI в маркетинге и где он сильнее маркетолога, а где всё ещё слабее. Контент-маркетинг, SEO, рабочие промпты, реклама в Яндекс.Директ и VK Ads, кейс и стоимость внедрения.',
    relatedArticles: ['kontent-kotoryy-citiruyut-ii-2026', 'geo-optimizaciya-chto-eto-2026', 'ai-agenty-v-biznese-2026'],
    relatedOffers: ['ai-kontent-zavod', 'ai-upravlenie-reputaciey', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'self-hosted-infrastruktura-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'ИНФРА', hero: 'Self-hosted инфраструктура',
    tagline: 'Свои сервисы вместо облаков SaaS',
    points: ['Docker как основа', 'Nextcloud и Gitea', 'Бэкапы и защита', 'Когда не нужно'],
    description: 'Зачем поднимать свою инфраструктуру в 2026 и когда self-hosted дешевле SaaS. Выбор VPS, Docker, Nextcloud, Gitea, n8n, аналитика, бэкапы, безопасность и честный разбор, когда это не нужно.',
    relatedArticles: ['mcp-model-context-protocol-2026', 'reestr-rossiyskogo-po-2026', 'ai-transkripciya-soveshchaniy-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'cto-as-a-service', 'audit-i-uskorenie-sayta'],
  },
  {
    slug: 'ai-chatbot-na-sayt-bez-programmirovaniya-2026', kind: 'article',
    label: 'AI И ТЕХНОЛОГИИ', pill: 'AI · NO-CODE', hero: 'Чат-бот без кода',
    tagline: 'AI-бот на сайт за выходные без кода',
    points: ['n8n за 30 минут', 'Правильный промпт', 'Подключение виджета', 'Связка с CRM'],
    description: 'Как собрать AI-чат-бота на сайт за выходные без программирования на связке n8n и виджета. Правильный промпт, лид-квалификация, интеграция с CRM и честное сравнение no-code с кастомной разработкой.',
    relatedArticles: ['ai-agenty-v-biznese-2026', 'mcp-model-context-protocol-2026', 'voronka-prodazh-b2b-2026'],
    relatedOffers: ['bot-dlya-biznesa', 'kviz-bot-podbor-zayavki', 'ai-konsultant'],
  },
  {
    slug: 'dipfeyki-moshennichestvo-zashchita-2026', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'БЕЗОПАСНОСТЬ', hero: 'Дипфейки и защита',
    tagline: 'Как не отдать деньги фейк-директору',
    points: ['Схемы атак', 'Суммы потерь', 'Как распознать', 'Регламенты защиты'],
    description: 'Что такое дипфейки и почему это прямая угроза деньгам бизнеса. Типичные схемы атак, реальные суммы потерь, признаки подделки и регламенты с обучением сотрудников для защиты компании.',
    relatedArticles: ['kak-obnaruzhit-fishing-2026', 'zashchita-ot-shifrovalshchikov-2026', 'biometria-ebs-2026'],
    relatedOffers: ['it-yuridicheskaya-firma', 'ai-upravlenie-reputaciey', 'cto-as-a-service'],
  },
  {
    slug: 'zashchita-ot-shifrovalshchikov-2026', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'БЕЗОПАСНОСТЬ', hero: 'Защита от шифровальщиков',
    tagline: 'Бэкапы и регламент против выкупа',
    points: ['Правило 3-2-1', 'Сегментация прав', 'План реагирования', 'Почему не платить'],
    description: 'Как защитить компанию от программ-вымогателей до того, как файлы окажутся зашифрованы. Бэкапы по правилу 3-2-1, сегментация и минимальные права, план реагирования и почему нельзя платить выкуп.',
    relatedArticles: ['kak-obnaruzhit-fishing-2026', 'dipfeyki-moshennichestvo-zashchita-2026', 'self-hosted-infrastruktura-2026'],
    relatedOffers: ['importozameshchenie-infrastruktura', 'cto-as-a-service', 'it-yuridicheskaya-firma'],
  },
  {
    slug: 'kak-obnaruzhit-fishing-2026', kind: 'article',
    label: 'БЕЗОПАСНОСТЬ', pill: 'ФИШИНГ', hero: 'Как распознать фишинг',
    tagline: 'Признаки фишинга в почте и мессенджерах',
    points: ['Чек-лист за 10 секунд', 'Признаки в почте', 'Фишинг в мессенджерах', 'Если уже попался'],
    description: 'Как за десять секунд отличить фишинг от настоящего сообщения в почте, SMS и мессенджерах. Признаки поддельных писем и сайтов, новые схемы 2026 с AI, защита бизнеса и план для родителей.',
    relatedArticles: ['dipfeyki-moshennichestvo-zashchita-2026', 'zashchita-ot-shifrovalshchikov-2026', 'biometria-ebs-2026'],
    relatedOffers: ['it-yuridicheskaya-firma', 'cto-as-a-service', 'ai-upravlenie-reputaciey'],
  },
  {
    slug: 'uvedomlenie-rkn-2026', kind: 'article',
    label: 'ПРАВО И ДОКУМЕНТЫ', pill: '152-ФЗ', hero: 'Уведомление РКН',
    tagline: 'Подать уведомление оператора ПД верно',
    points: ['Кому обязательно', 'Подготовка данных', 'Подача через РКН', 'Топ ошибок'],
    description: 'Кому обязательно подавать уведомление оператора персональных данных и что грозит без него. Пошаговая подача через портал РКН, формулировка целей обработки, обновления и топ частых ошибок.',
    relatedArticles: ['soglasie-na-obrabotku-pd-2026', 'lokalizaciya-pd-2026', 'cookie-banner-zakon'],
    relatedOffers: ['152-fz-pod-klyuch', 'it-yuridicheskaya-firma', 'edo-elektronnaya-podpis'],
  },
];
