module.exports = [
  {
    slug: 'kak-izmerit-geo-2026', kind: 'article',
    label: 'GEO И AI-ПОИСК', pill: 'GEO', hero: 'Как измерить GEO',
    tagline: 'Считаем видимость в ответах ИИ',
    points: ['Выдача нестабильна', '20–40 промптов-проб', 'Метрики и таблица', 'Регулярный мониторинг'],
    description: 'Объясняет, почему классические SEO-инструменты не работают для GEO и какие метрики отслеживать вручную. Показывает, как собрать набор контрольных вопросов и прогонять их через ChatGPT, Perplexity, Алису и Яндекс Нейро.',
    relatedArticles: ['geo-optimizaciya-chto-eto-2026', 'kontent-kotoryy-citiruyut-ii-2026', 'llms-txt-standart-2026'],
    relatedOffers: ['ai-kontent-zavod', 'ai-konsultant', 'audit-i-uskorenie-sayta'],
  },
  {
    slug: 'llms-txt-standart-2026', kind: 'article',
    label: 'GEO И AI-ПОИСК', pill: 'LLMS.TXT', hero: 'llms.txt — стандарт',
    tagline: 'Файл-навигатор для нейросетей',
    points: ['Markdown в корне сайта', 'Не robots и не sitemap', 'Структура и синтаксис', 'Внедрение и проверка'],
    description: 'Разбирает, что такое llms.txt, чем он отличается от robots.txt и sitemap.xml и кто его читает. Даёт готовый пример файла, структуру разделов и частые ошибки при внедрении.',
    relatedArticles: ['geo-optimizaciya-chto-eto-2026', 'kak-izmerit-geo-2026', 'kontent-kotoryy-citiruyut-ii-2026'],
    relatedOffers: ['ai-kontent-zavod', 'audit-i-uskorenie-sayta', 'ai-konsultant'],
  },
  {
    slug: 'yandex-neyro-alisa-istochniki-2026', kind: 'article',
    label: 'GEO И AI-ПОИСК', pill: 'НЕЙРО', hero: 'Попасть в Яндекс Нейро',
    tagline: 'Источники для ответов Нейро и Алисы',
    points: ['Ответ над выдачей', 'Источники из индекса', 'Роль Вебмастера', 'Отличия от ChatGPT'],
    description: 'Показывает, как устроена выдача с ИИ-ответом Яндекса и что влияет на выбор источников. Объясняет практические шаги, чтобы попасть в ответы Нейро и Алисы, и чем это отличается от ChatGPT и Perplexity.',
    relatedArticles: ['geo-optimizaciya-chto-eto-2026', 'kak-izmerit-geo-2026', 'kontent-kotoryy-citiruyut-ii-2026'],
    relatedOffers: ['ai-kontent-zavod', 'ai-konsultant', 'audit-i-uskorenie-sayta'],
  },
  {
    slug: 'voronka-prodazh-b2b-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'B2B', hero: 'Воронка продаж B2B',
    tagline: 'Длинный цикл и несколько ЛПР',
    points: ['Цикл от месяца до года', 'Этапы и метрики', 'CRM и лид-скоринг', 'AI в продажах'],
    description: 'Разбирает отличия B2B-воронки от B2C: длинный цикл сделки, множество лиц принятия решения и ROI-обоснование. Показывает этапы, источники лидов, выбор CRM, лид-скоринг и применение AI в продажах.',
    relatedArticles: ['yunit-ekonomika-osnovatelya-2026', 'reputaciya-otzyvy-yandex-2gis-2026', 'ai-v-marketinge-2026'],
    relatedOffers: ['b2b-portal-opt', 'skvoznaya-analitika-koltreking', 'integraciya-sistem'],
  },
  {
    slug: 'seo-internet-magazina-yandex-30-hakov-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'SEO', hero: 'SEO магазина: 30 хаков',
    tagline: '30 приёмов под требования Яндекса',
    points: ['Технический SEO', 'Карточки и категории', 'Контент и аналитика', 'План внедрения'],
    description: 'Даёт 30 конкретных хаков по SEO интернет-магазина под Яндекс: техническая база, карточки товара, категории, контент и аналитика. Сравнивает свой магазин с продажами на WB и Ozon и предлагает план внедрения.',
    relatedArticles: ['svoy-magazin-vs-wildberries-ozon-2026', 'reputaciya-otzyvy-yandex-2gis-2026', 'email-push-rassylki-rf-2026'],
    relatedOffers: ['audit-i-uskorenie-sayta', 'fulfilment-internet-magazina', 'skvoznaya-analitika-koltreking'],
  },
  {
    slug: 'email-push-rassylki-rf-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'РАССЫЛКИ', hero: 'Email и push в РФ',
    tagline: 'Замена ушедшим сервисам рассылок',
    points: ['Российские сервисы', 'SPF, DKIM, DMARC', 'Web и mobile push', 'Закон и согласие'],
    description: 'Обзор российских сервисов email-рассылок и своего SMTP после ухода зарубежных платформ. Разбирает доставляемость, прогрев домена, web и mobile push, сегментацию и требования закона.',
    relatedArticles: ['seo-internet-magazina-yandex-30-hakov-2026', 'reputaciya-otzyvy-yandex-2gis-2026', 'ai-v-marketinge-2026'],
    relatedOffers: ['skvoznaya-analitika-koltreking', 'integraciya-sistem', 'ai-kontent-zavod'],
  },
  {
    slug: 'reputaciya-otzyvy-yandex-2gis-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'ОТЗЫВЫ', hero: 'Репутация и отзывы',
    tagline: 'Отзывы читают люди и нейросети',
    points: ['Карты, 2ГИС, отзовики', 'Законный сбор отзывов', 'Работа с негативом', 'Процесс мониторинга'],
    description: 'Показывает, как отзывы на Яндекс Картах, 2ГИС и отзовиках влияют на выбор клиентов и ИИ-ассистентов. Разбирает законный сбор отзывов, работу с негативом, запреты на накрутку и инструменты мониторинга.',
    relatedArticles: ['voronka-prodazh-b2b-2026', 'seo-internet-magazina-yandex-30-hakov-2026', 'ai-v-marketinge-2026'],
    relatedOffers: ['ai-upravlenie-reputaciey', 'skvoznaya-analitika-koltreking', 'ai-konsultant'],
  },
  {
    slug: 'live-commerce-rf-2026', kind: 'article',
    label: 'МАРКЕТИНГ И РОСТ', pill: 'LIVE', hero: 'Live-commerce в РФ',
    tagline: 'Продажи через прямые эфиры',
    points: ['Конверсия в 5–10 раз', 'Платформы РФ 2026', 'Форматы и стек', 'Метрики и стоимость'],
    description: 'Объясняет, почему Live Commerce даёт конверсию выше обычного e-commerce и какие платформы доступны в РФ. Разбирает форматы, технический стек, привлечение зрителей, юридические нюансы и метрики.',
    relatedArticles: ['svoy-magazin-vs-wildberries-ozon-2026', 'seo-internet-magazina-yandex-30-hakov-2026', 'reputaciya-otzyvy-yandex-2gis-2026'],
    relatedOffers: ['fulfilment-internet-magazina', 'skvoznaya-analitika-koltreking', 'repraiser-wb-ozon'],
  },
  {
    slug: 'kak-prevratit-ideyu-v-produkt-2027', kind: 'article',
    label: 'СТАРТАП И ПРОДУКТ', pill: 'СТАРТАП', hero: 'Идея в продукт',
    tagline: 'От идеи до пользователей за три шага',
    points: ['Сначала проверь спрос', 'Прототип и proof', 'MVP с пользой', 'AI и железо'],
    description: 'Показывает путь от идеи до продукта через три шага: валидация спроса, прототип и MVP. Разбирает выбор формата, AI-продукты, работу с подрядчиком, права на код и частые ошибки основателя.',
    relatedArticles: ['mvp-to-production-3-mesyatsa-2026', 'yunit-ekonomika-osnovatelya-2026', 'biznes-plan-2026-shablon'],
    relatedOffers: ['prototip-poc-investor', 'ai-konsultant', 'integraciya-sistem'],
  },
  {
    slug: 'mvp-to-production-3-mesyatsa-2026', kind: 'article',
    label: 'СТАРТАП И ПРОДУКТ', pill: 'MVP', hero: 'MVP за 3 месяца',
    tagline: 'План по неделям до релиза',
    points: ['MVP — не прототип', 'Discovery до кода', 'Каркас и запуск', 'Метрики с первого дня'],
    description: 'Конкретный план запуска MVP по неделям: Discovery, каркас и инфраструктура, наполнение и production. Опирается на 15+ доведённых до релиза проектов, стек инструментов автора и реальный кейс RAG-системы.',
    relatedArticles: ['kak-prevratit-ideyu-v-produkt-2027', 'yunit-ekonomika-osnovatelya-2026', 'saas-pricing-2026'],
    relatedOffers: ['prototip-poc-investor', 'ai-konsultant', 'integraciya-sistem'],
  },
];
