// Энциклопедия открытых ИИ-моделей: данные для /ii-modeli/.
// Одна запись = одно семейство моделей. Факты — только по карточке модели
// на Hugging Face / GitHub; непроверенное не публикуем.
// hardware: min — ноутбук или до 8 ГБ видеопамяти; gpu — одна видеокарта 16–80 ГБ;
// multi — несколько видеокарт. commercial: yes / conditional / no.
const BASE = [
  {
    id: 'qwen', name: 'Qwen', developer: 'Alibaba', country: 'Китай',
    modality: ['text', 'vlm'], first: '2023-08', latest: '2026-08', sizes: '0,6B – 2,4T-A95B',
    license: 'Apache 2.0 (большинство версий); у старших Qwen3.8 — своя лицензия', commercial: 'conditional', hardware: ['min', 'gpu', 'multi'], ru: 'yes', industries: ['support', 'retail', 'docs', 'dev'], ollama: true, cpu: true,
    summary: 'Семейство языковых моделей с сильным русским языком: от маленьких версий для ноутбука до флагмана уровня коммерческих API.',
    tasks: ['Чат-бот и ассистент по базе знаний', 'Ответы на письма и обращения', 'Разбор и классификация документов', 'Генерация описаний товаров'],
    where: ['Поддержка клиентов', 'E-commerce', 'Юристы и бухгалтерия', 'Внутренние базы знаний'],
    versions: [['Qwen', '2023-08'], ['Qwen1.5', '2024-02'], ['Qwen2', '2024-06'], ['Qwen2.5', '2024-09'], ['Qwen3', '2025-04'], ['Qwen3.5', '2026-02'], ['Qwen3.6', '2026-04'], ['Qwen3.8 (27B – 2.4T-A95B)', '2026-08']],
    hf: 'https://huggingface.co/Qwen', github: 'https://github.com/QwenLM',
    alternatives: ['llama', 'gemma', 'mistral'],
    en: {
      summary: 'A family of language models with strong Russian language support, from small versions for a laptop to a flagship on par with commercial APIs.',
      tasks: ['Chatbot and knowledge-base assistant', 'Replies to emails and customer requests', 'Document parsing and classification', 'Product description generation'],
      where: ['Customer support', 'E-commerce', 'Legal and accounting', 'Internal knowledge bases'],
      license: 'Apache 2.0 (most versions); the larger Qwen3.8 models have their own license',
      country: 'China',
    },
  },
  {
    id: 'llama', name: 'Llama', developer: 'Meta', country: 'США',
    modality: ['text', 'vlm'], first: '2023-02', latest: '2025-04', sizes: '1B – 405B',
    license: 'Llama Community License', commercial: 'conditional', hardware: ['min', 'gpu', 'multi'], ru: 'no', industries: ['support', 'education', 'dev'], ollama: true, cpu: true,
    summary: 'Модели, с которых начался массовый open source в ИИ. Огромная экосистема дообученных версий и инструментов.',
    tasks: ['Ассистент для сотрудников', 'Суммаризация встреч и документов', 'Основа для дообучения под отрасль', 'Распознавание картинок (версии Vision)'],
    where: ['Корпоративные ассистенты', 'Образование', 'Разработка продуктов на ИИ'],
    versions: [['LLaMA', '2023-02'], ['Llama 2', '2023-07'], ['Llama 3', '2024-04'], ['Llama 3.1', '2024-07'], ['Llama 3.2', '2024-09'], ['Llama 3.3', '2024-12'], ['Llama 4', '2025-04']],
    hf: 'https://huggingface.co/meta-llama', github: 'https://github.com/meta-llama',
    alternatives: ['qwen', 'gemma', 'mistral'],
    en: {
      summary: 'The models that started mass open source in AI. A huge ecosystem of fine-tuned versions and tools.',
      tasks: ['Assistant for employees', 'Summaries of meetings and documents', 'Base for industry-specific fine-tuning', 'Image understanding (Vision versions)'],
      where: ['Corporate assistants', 'Education', 'AI product development'],
      license: 'Llama Community License',
      country: 'USA',
    },
  },
  {
    id: 'deepseek-r1', name: 'DeepSeek-R1', developer: 'DeepSeek', country: 'Китай',
    modality: ['text'], first: '2025-01', latest: '2025-05', sizes: '1,5B – 671B',
    license: 'MIT', commercial: 'yes', hardware: ['min', 'gpu', 'multi'], ru: 'unknown', industries: ['finance', 'legal', 'dev', 'science'], ollama: true, cpu: true,
    summary: 'Рассуждающая модель: думает по шагам перед ответом. Сильна в расчётах, логике и коде; есть компактные дистиллированные версии.',
    tasks: ['Сложные расчёты и проверка логики', 'Анализ договоров и регламентов', 'Помощь программистам', 'Разбор спорных случаев по шагам'],
    where: ['Финансы и аналитика', 'Юридические отделы', 'Разработка'],
    versions: [['DeepSeek-R1', '2025-01'], ['R1-Distill', '2025-01'], ['R1-0528', '2025-05']],
    hf: 'https://huggingface.co/deepseek-ai', github: 'https://github.com/deepseek-ai',
    alternatives: ['qwen', 'gpt-oss'],
    en: {
      summary: 'A reasoning model that thinks step by step before answering. Strong at calculations, logic and code; compact distilled versions are available.',
      tasks: ['Complex calculations and logic checks', 'Analysis of contracts and internal policies', 'Help for developers', 'Step-by-step review of disputed cases'],
      where: ['Finance and analytics', 'Legal departments', 'Software development'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'gpt-oss', name: 'gpt-oss', developer: 'OpenAI', country: 'США',
    modality: ['text'], first: '2025-08', latest: '2025-08', sizes: '20B, 120B',
    license: 'Apache 2.0', commercial: 'yes', hardware: ['gpu'], ru: 'unknown', industries: ['dev', 'support', 'docs'], ollama: true, cpu: false,
    summary: 'Первые открытые модели OpenAI со времён GPT-2. Рассуждения, вызов инструментов, младшая версия помещается на одну видеокарту.',
    tasks: ['ИИ-агент с вызовом внутренних систем', 'Ответы по регламентам', 'Черновики писем и отчётов'],
    where: ['Корпоративные агенты', 'Закрытый контур без облака'],
    versions: [['gpt-oss-20b', '2025-08'], ['gpt-oss-120b', '2025-08']],
    hf: 'https://huggingface.co/openai', github: 'https://github.com/openai/gpt-oss',
    alternatives: ['qwen', 'deepseek-r1'],
    en: {
      summary: 'OpenAI\'s first open models since GPT-2. Reasoning and tool calling; the smaller version fits on a single GPU.',
      tasks: ['AI agent that calls internal systems', 'Answers based on internal policies', 'Drafts of emails and reports'],
      where: ['Corporate agents', 'Closed, cloud-free environments'],
      license: 'Apache 2.0',
      country: 'USA',
    },
  },
  {
    id: 'gemma', name: 'Gemma', developer: 'Google', country: 'США',
    modality: ['text', 'vlm', 'code'], first: '2024-02', latest: '2026-06', sizes: '270M – 31B',
    license: 'Gemma 4 и DiffusionGemma — Apache 2.0; ранние версии, CodeGemma и FunctionGemma — Gemma Terms of Use', commercial: 'yes', hardware: ['min', 'gpu'], ru: 'unknown', industries: ['support', 'docs', 'retail'], ollama: true, cpu: true,
    summary: 'Компактные модели Google: хорошо работают на одном компьютере, старшие версии понимают картинки. Есть CodeGemma для кода, FunctionGemma 270M для вызова функций и быстрая DiffusionGemma.',
    tasks: ['Ассистент на ноутбуке без интернета', 'Разбор фото документов и чеков', 'Классификация обращений'],
    where: ['Малый бизнес', 'Работа на слабом железе', 'Мобильные устройства'],
    versions: [['Gemma', '2024-02'], ['CodeGemma', '2024-04'], ['Gemma 2', '2024-06'], ['Gemma 3', '2025-03'], ['Gemma 3n', '2025-06'], ['FunctionGemma 270M', '2025-12'], ['Gemma 4', '2026-04'], ['DiffusionGemma 26B-A4B', '2026-06']],
    hf: 'https://huggingface.co/google', github: 'https://github.com/google-deepmind/gemma',
    alternatives: ['qwen', 'llama'],
    en: {
      summary: 'Compact Google models that run well on a single computer; larger versions understand images. Includes CodeGemma for code, FunctionGemma 270M for function calling and the fast DiffusionGemma.',
      tasks: ['Offline assistant on a laptop', 'Reading photos of documents and receipts', 'Customer request classification'],
      where: ['Small business', 'Low-end hardware', 'Mobile devices'],
      license: 'Gemma 4 and DiffusionGemma: Apache 2.0; earlier versions, CodeGemma and FunctionGemma: Gemma Terms of Use',
      country: 'USA',
    },
  },
  {
    id: 'mistral', name: 'Mistral', developer: 'Mistral AI', country: 'Франция',
    modality: ['text', 'vlm', 'code', 'safety'], first: '2023-09', latest: '2026-07', sizes: '3B – 675B',
    license: 'Apache 2.0 (большинство версий, включая Ministral 3, Pixtral 12B, Leanstral и Shieldstral); Mistral Medium 3.5 — модифицированная MIT: компаниям с крупной выручкой нужен платный доступ', commercial: 'conditional', hardware: ['min', 'gpu', 'multi'], ru: 'yes', industries: ['support', 'docs', 'dev'], ollama: true, cpu: true,
    summary: 'Европейские модели с упором на скорость. Mixtral — одна из первых открытых моделей на архитектуре «смесь экспертов»; есть версии с картинками (Pixtral, Medium 3.5), для доказательств в Lean и модерации (Shieldstral).',
    tasks: ['Быстрые ответы в чате', 'Извлечение данных из текста', 'Перевод и работа с несколькими языками'],
    where: ['Поддержка клиентов', 'Обработка заявок', 'Европейские проекты'],
    versions: [['Mistral 7B', '2023-09'], ['Mixtral 8x7B', '2023-12'], ['Mistral NeMo / Mathstral 7B', '2024-07'], ['Pixtral 12B', '2024-09'], ['Mistral Small 3', '2025-01'], ['Magistral Small', '2025-06'], ['Mistral Large 3 / Ministral 3 (3B, 8B, 14B)', '2025-12'], ['Mistral Small 4 / Leanstral', '2026-03'], ['Mistral Medium 3.5 128B', '2026-04'], ['Leanstral 1.5 119B-A6B / Shieldstral-1.0-3B', '2026-07']],
    hf: 'https://huggingface.co/mistralai', github: 'https://github.com/mistralai',
    alternatives: ['qwen', 'llama'],
    en: {
      summary: 'European models focused on speed. Mixtral was one of the first open mixture-of-experts models; there are versions for images (Pixtral, Medium 3.5), Lean proofs and moderation (Shieldstral).',
      tasks: ['Fast chat responses', 'Data extraction from text', 'Translation and multilingual work'],
      where: ['Customer support', 'Request processing', 'European projects'],
      license: 'Apache 2.0 (most versions, including Ministral 3, Pixtral 12B, Leanstral and Shieldstral); Mistral Medium 3.5: modified MIT, companies with large revenue need paid access',
      country: 'France',
    },
  },
  {
    id: 'whisper', name: 'Whisper', developer: 'OpenAI', country: 'США',
    modality: ['asr'], first: '2022-09', latest: '2025-03', sizes: '39M – 1,5B',
    license: 'MIT', commercial: 'yes', hardware: ['min', 'gpu'], ru: 'yes', industries: ['support', 'media', 'legal'], ollama: false, cpu: true,
    summary: 'Распознавание речи на 99 языках, включая русский. Стандарт де-факто для расшифровки звонков и встреч. Ускоренные Distil-Whisper от Hugging Face — только для английского.',
    tasks: ['Расшифровка звонков и созвонов', 'Субтитры к видео', 'Голосовые сообщения в текст', 'Протоколы совещаний'],
    where: ['Отделы продаж', 'Колл-центры', 'Медиа и блогеры', 'Юристы'],
    versions: [['Whisper', '2022-09'], ['large-v2', '2022-12'], ['Distil-Whisper (Hugging Face)', '2023-11'], ['large-v3', '2023-11'], ['large-v3-turbo', '2024-10'], ['distil-large-v3.5', '2025-03']],
    hf: 'https://huggingface.co/openai/whisper-large-v3', github: 'https://github.com/openai/whisper',
    alternatives: [],
    en: {
      summary: 'Speech recognition in 99 languages, including Russian. The de facto standard for transcribing calls and meetings. Hugging Face\'s faster Distil-Whisper is English only.',
      tasks: ['Transcription of calls and video meetings', 'Video subtitles', 'Voice messages to text', 'Meeting minutes'],
      where: ['Sales teams', 'Call centers', 'Media and bloggers', 'Lawyers'],
      license: 'MIT',
      country: 'USA',
    },
  },
  {
    id: 'flux', name: 'FLUX', developer: 'Black Forest Labs', country: 'Германия',
    modality: ['image'], first: '2024-08', latest: '2026-01', sizes: '4B – 32B',
    license: 'FLUX.1 [schnell] и FLUX.2 [klein] 4B — Apache 2.0; версии [dev] — некоммерческие', commercial: 'conditional', hardware: ['gpu'], ru: 'na', industries: ['marketing', 'media', 'retail'], ollama: false, cpu: false,
    summary: 'Генерация картинок от авторов Stable Diffusion. Хорошо рисует текст на изображении и держит композицию.',
    tasks: ['Картинки для карточек товаров', 'Баннеры и обложки', 'Редактирование фото по описанию (Kontext)'],
    where: ['Маркетплейсы', 'Маркетинг и SMM', 'Дизайн-студии'],
    versions: [['FLUX.1 [schnell] / [dev]', '2024-08'], ['FLUX.1 Tools', '2024-11'], ['FLUX.1 Kontext [dev]', '2025-06'], ['FLUX.2 [dev]', '2025-11'], ['FLUX.2 [klein]', '2026-01']],
    hf: 'https://huggingface.co/black-forest-labs', github: 'https://github.com/black-forest-labs/flux',
    alternatives: ['qwen-image'],
    en: {
      summary: 'Image generation from the creators of Stable Diffusion. Renders text in images well and keeps the composition.',
      tasks: ['Images for product cards', 'Banners and covers', 'Photo editing by description (Kontext)'],
      where: ['Marketplaces', 'Marketing and social media', 'Design studios'],
      license: 'FLUX.1 [schnell] and FLUX.2 [klein] 4B: Apache 2.0; [dev] versions: non-commercial',
      country: 'Germany',
    },
  },
  {
    id: 'qwen-image', name: 'Qwen-Image', developer: 'Alibaba', country: 'Китай',
    modality: ['image'], first: '2025-08', latest: '2026-09', sizes: '7B – 20B',
    license: 'До Qwen-Image-2512 — Apache 2.0; Qwen-Image-2.1 — исследовательская, некоммерческая', commercial: 'conditional', hardware: ['gpu'], ru: 'na', industries: ['retail', 'marketing', 'media'], ollama: false, cpu: false,
    summary: 'Генерация и редактирование картинок, в том числе с текстом на изображении. Ранние версии можно в коммерцию, свежая 2.1 — только некоммерческая.',
    tasks: ['Инфографика для карточек товаров', 'Правка фото по текстовой команде', 'Рекламные креативы'],
    where: ['Маркетплейсы', 'Интернет-магазины', 'Реклама'],
    versions: [['Qwen-Image', '2025-08'], ['Qwen-Image-Edit', '2025-08'], ['Qwen-Image-2512', '2025-12'], ['Qwen-Image-2.1', '2026-09']],
    hf: 'https://huggingface.co/Qwen/Qwen-Image', github: 'https://github.com/QwenLM/Qwen-Image',
    alternatives: ['flux'],
    en: {
      summary: 'Image generation and editing, including text in images. Earlier versions allow commercial use; the latest 2.1 is non-commercial only.',
      tasks: ['Infographics for product cards', 'Photo editing by text command', 'Ad creatives'],
      where: ['Marketplaces', 'Online stores', 'Advertising'],
      license: 'Up to Qwen-Image-2512: Apache 2.0; Qwen-Image-2.1: research, non-commercial',
      country: 'China',
    },
  },
  {
    id: 'wan', name: 'Wan', developer: 'Alibaba', country: 'Китай',
    modality: ['video', 'avatar'], first: '2025-02', latest: '2026-07', sizes: '1,3B – 14B',
    license: 'Apache 2.0', commercial: 'yes', hardware: ['gpu', 'multi'], ru: 'na', industries: ['marketing', 'media', 'retail'], ollama: false, cpu: false,
    summary: 'Генерация видео по тексту и по картинке. Младшая версия запускается на игровой видеокарте. После 2.2 базовые модели открыто не выходят, только прикладные: монтаж (VACE), говорящие персонажи по звуку (S2V), танцы под музыку (Dancer).',
    tasks: ['Короткие рекламные ролики', 'Оживление фото товара', 'Видео для соцсетей'],
    where: ['SMM и реклама', 'E-commerce', 'Продакшн'],
    versions: [['Wan 2.1', '2025-02'], ['Wan2.1-VACE', '2025-05'], ['Wan 2.2', '2025-07'], ['Wan2.2-S2V-14B', '2025-08'], ['Wan-Dancer-14B', '2026-07'], ['Wan2.2-Animate-2', '2026-07']],
    hf: 'https://huggingface.co/Wan-AI', github: 'https://github.com/Wan-Video',
    alternatives: [],
    en: {
      summary: 'Text-to-video and image-to-video; the small version runs on a gaming GPU. After 2.2 only applied models are open: editing (VACE), audio-driven talking characters (S2V), dancing to music (Dancer).',
      tasks: ['Short promo videos', 'Animating product photos', 'Videos for social media'],
      where: ['Social media and advertising', 'E-commerce', 'Video production'],
      license: 'Apache 2.0',
      country: 'China',
    },
  },
  {
    id: 'bge-m3', name: 'BGE-M3', developer: 'BAAI', country: 'Китай',
    modality: ['embed'], first: '2024-01', latest: '2024-01', sizes: '568M',
    license: 'MIT', commercial: 'yes', hardware: ['min'], ru: 'yes', industries: ['support', 'docs', 'legal'], ollama: true, cpu: true,
    summary: 'Модель для поиска по смыслу на сотне языков. Основа RAG: бот находит нужный кусок документа перед ответом.',
    tasks: ['Поиск по базе документов', 'RAG для чат-бота', 'Поиск похожих обращений и дублей'],
    where: ['Базы знаний', 'Юридические архивы', 'Поддержка клиентов'],
    versions: [['BGE-M3', '2024-01']],
    hf: 'https://huggingface.co/BAAI/bge-m3', github: 'https://github.com/FlagOpen/FlagEmbedding',
    alternatives: [],
    en: {
      summary: 'A model for meaning-based search in about a hundred languages. The core of RAG: the bot finds the right part of a document before answering.',
      tasks: ['Search across a document base', 'RAG for a chatbot', 'Finding similar requests and duplicates'],
      where: ['Knowledge bases', 'Legal archives', 'Customer support'],
      license: 'MIT',
      country: 'China',
    },
  },
  {
    id: 'sam', name: 'Segment Anything (SAM)', developer: 'Meta', country: 'США',
    modality: ['vision'], first: '2023-04', latest: '2026-03', sizes: '91M – ~0,85B',
    license: 'SAM и SAM 2 — Apache 2.0; SAM 3 — SAM License (коммерция разрешена)', commercial: 'conditional', hardware: ['min', 'gpu'], ru: 'na', industries: ['retail', 'manufacturing', 'media'], ollama: false, cpu: true,
    summary: 'Выделяет любой объект на фото и видео по клику или рамке. Основа для удаления фона и подсчёта объектов.',
    tasks: ['Удаление фона с фото товара', 'Подсчёт объектов на фото', 'Разметка данных для обучения'],
    where: ['E-commerce', 'Производство и контроль качества', 'Агро'],
    versions: [['SAM', '2023-04'], ['SAM 2', '2024-07'], ['SAM 3', '2025-11'], ['SAM 3.1', '2026-03']],
    hf: 'https://huggingface.co/facebook', github: 'https://github.com/facebookresearch/sam2',
    alternatives: [],
    en: {
      summary: 'Selects any object in photos and videos with a click or a box. The basis for background removal and object counting.',
      tasks: ['Background removal from product photos', 'Counting objects in photos', 'Data labeling for training'],
      where: ['E-commerce', 'Manufacturing and quality control', 'Agriculture'],
      license: 'SAM and SAM 2: Apache 2.0; SAM 3: SAM License (commercial use allowed)',
      country: 'USA',
    },
  },
];

// Остальные семейства лежат по направлениям в tools/models/*.js (каждый файл — массив).
// При совпадении id запись из файла направления заменяет базовую.
const fs = require('fs');
const path = require('path');
const byId = new Map(BASE.map((m) => [m.id, m]));
const dir = path.join(__dirname, 'models');
for (const f of fs.existsSync(dir) ? fs.readdirSync(dir).filter((x) => x.endsWith('.js') && !x.startsWith('_')).sort() : []) {
  for (const m of require(path.join(dir, f))) {
    if (m.verified === false) continue; // непроверенное не публикуем
    byId.set(m.id, m);
  }
}
module.exports = [...byId.values()];
