// Коммерческие предложения (пакеты под ниши). Источник правды для build-offers.js.
// У всех предложений тело — bodyHtml (развёрнутый КП). Цены не указываем:
// priceFrom = «Бесплатная консультация» (точная смета — после разговора).
// segment — группа для фильтра на хабе.

const kofeynyaBody = require('./offer-content-kofeynya.js');
const cvetochnyyBody = require('./offer-content-cvetochnyy.js');
const avtoservisBody = require('./offer-content-avtoservis.js');
const obshchepitBody = require('./offer-content-obshchepit.js');
const botBody = require('./offer-content-bot.js');
const konkursBody = require('./offer-content-konkurs.js');
const rozygryshiBody = require('./offer-content-rozygryshi.js');
const salonBody = require('./offer-content-salon.js');
const stomatologiyaBody = require('./offer-content-stomatologiya.js');
const aiKonsultantBody = require('./offer-content-ai-konsultant.js');
const lichnyyKabinetBody = require('./offer-content-lichnyy-kabinet.js');
const loyalnostBody = require('./offer-content-loyalnost.js');
const bystryyStartBody = require('./offer-content-bystryy-start.js');
const fitnesBody = require('./offer-content-fitnes.js');
const onlaynShkolaBody = require('./offer-content-onlayn-shkola.js');
const fz152Body = require('./offer-content-152fz.js');
const integraciyaBody = require('./offer-content-integraciya.js');
const otelBody = require('./offer-content-otel.js');
const botMagazinBody = require('./offer-content-bot-magazin.js');
const nedvizhimostBody = require('./offer-content-nedvizhimost.js');
const avtoshkolaBody = require('./offer-content-avtoshkola.js');
const sellerBody = require('./offer-content-seller.js');
const kliningBody = require('./offer-content-klining.js');
const b2bBody = require('./offer-content-b2b.js');
const dostavkaBody = require('./offer-content-dostavka.js');
const stroykaBody = require('./offer-content-stroyka.js');
const aiYurbuhBody = require('./offer-content-ai-yurbuh.js');
const vetklinikaBody = require('./offer-content-vetklinika.js');
const kovorkingBody = require('./offer-content-kovorking.js');
const tipografiyaBody = require('./offer-content-tipografiya.js');
const himchistkaBody = require('./offer-content-himchistka.js');
const golosovoyBody = require('./offer-content-golosovoy.js');
const bazaZnaniyBody = require('./offer-content-baza-znaniy.js');
const hrBody = require('./offer-content-hr.js');
const praktikaBody = require('./offer-content-praktika.js');
const turagentstvoBody = require('./offer-content-turagentstvo.js');
const dashboardBody = require('./offer-content-dashboard.js');
const cifrovizaciyaVseBody = require('./offer-content-cifrovizaciya-vse.js');
const platformaLoyalnostiBody = require('./offer-content-platforma-loyalnosti.js');
const saasBody = require('./offer-content-saas.js');
const marketplaceBody = require('./offer-content-marketplace.js');
const aiOtdelBody = require('./offer-content-ai-otdel.js');
const lmsBody = require('./offer-content-lms.js');
const franshizaBody = require('./offer-content-franshiza.js');
const portalBody = require('./offer-content-portal.js');
const importozamBody = require('./offer-content-importozam.js');
const ctoBody = require('./offer-content-cto.js');

// Порядок на хабе: свежие партии выше, старые ниже.
const _ALL_OFFERS = [
  ...require('./offers-batch-12.js'),
  ...require('./offers-batch-11.js'),
  ...require('./offers-batch-10.js'),
  ...require('./offers-batch-9.js'),
  ...require('./offers-batch-8.js'),
  ...require('./offers-batch-7.js'),
  ...require('./offers-batch-6.js'),
  ...require('./offers-batch-5.js'),
  ...require('./offers-batch-4.js'),
  ...require('./offers-batch-3.js'),
  ...require('./offers-batch-2.js'),
  {
    slug: 'kofeynya',
    published: true,
    segment: 'Автоматизация',
    niche: 'Кофейня',
    icon: 'ph-coffee',
    title: 'Digital-платформа для кофейни под ключ',
    tagline: 'PWA + программа лояльности, аналитика поведения клиентов и мессенджер-каналы (MAX, Telegram) — привлечение, удержание и рост среднего чека.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'MVP за 2–3 недели',
    bodyHtml: kofeynyaBody,
    relatedServices: [
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
    ],
    relatedBlog: [
      { url: '/blog/it-dlya-horeca-2026/', label: 'IT для HoReCa' },
      { url: '/blog/pwa-iz-sayta-za-vyhodnye-2026/', label: 'Что такое PWA' },
      { url: '/blog/max-bot-restoran-kafe-2026/', label: 'МАКС-бот для кафе' },
    ],
    faq: [
      { q: 'Чем PWA лучше обычного приложения?', a: 'PWA работает у всех без установки из App Store и Google Play, обновляется мгновенно и не платит комиссий магазинам. Для клиента почти неотличимо от нативного приложения, для бизнеса — в разы дешевле.' },
      { q: 'Можно подключать модули постепенно?', a: 'Да, решение модульное. Начинаем с базы (лояльность, регистрация, админка), а остальное подключаем по мере роста — вы не платите за то, чем не пользуетесь.' },
      { q: 'Данные клиентов в безопасности?', a: 'Да. Размещаем на российских серверах с соблюдением 152-ФЗ — никаких рисков с регулятором.' },
    ],
    metaTitle: 'Digital-платформа для кофейни под ключ | Чимитдоржи Дарижапов',
    metaDescription: 'Кастомная платформа для кофейни: PWA, программа лояльности, аналитика поведения клиентов, каналы MAX и Telegram. Российский стек, 152-ФЗ. Привлечение, удержание и рост среднего чека.',
  },
  {
    slug: 'cvetochnyy-magazin',
    published: true,
    segment: 'Боты и AI',
    niche: 'Цветочный магазин',
    icon: 'ph-flower-lotus',
    title: 'Программа лояльности для цветочного магазина (бот MAX)',
    tagline: 'Бот в MAX: накопительные баллы, автонапоминания к праздникам и важным датам, реферальная программа — клиенты возвращаются сами.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'от 2 недель',
    bodyHtml: cvetochnyyBody,
    relatedServices: [
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
    ],
    relatedBlog: [
      { url: '/blog/cifrovizaciya-cvetochnogo-magazina-2026/', label: 'Цифровизация цветочного магазина' },
      { url: '/blog/max-kanaly-rassylki-marketing-2026/', label: 'Каналы и рассылки в МАКС' },
      { url: '/blog/max-bot-zapis-na-uslugi-2026/', label: 'МАКС-бот для записи' },
    ],
    faq: [
      { q: 'Почему именно MAX?', a: 'Российский мессенджер — данные клиентов хранятся в России (152-ФЗ), а аудитория MAX это взрослые платёжеспособные люди, которые и покупают цветы на праздники.' },
      { q: 'Баллы — это законно?', a: 'Да. Баллы начисляются с фактических покупок и являются скидкой на товар, без вступительных взносов и вывода средств — это соответствует требованиям к партнёрским программам.' },
      { q: 'Бот правда напоминает сам?', a: 'Да. Один раз заносим даты клиента, дальше планировщик раз в сутки сканирует все даты и сам отправляет напоминания о праздниках, днях рождения близких и сгорающих баллах.' },
    ],
    metaTitle: 'Программа лояльности для цветочного магазина — бот MAX | Чимитдоржи Дарижапов',
    metaDescription: 'Бот лояльности для цветочного магазина в MAX: накопительные баллы, автонапоминания к праздникам и важным датам, реферальная программа «приведи друга». Данные в РФ, 152-ФЗ.',
  },
  {
    slug: 'avtoservis',
    published: true,
    segment: 'Автоматизация',
    niche: 'Автосервис и СТО',
    icon: 'ph-wrench',
    title: 'Цифровизация автосервиса под ключ',
    tagline: 'Онлайн-запись, CRM, напоминания клиентам и учёт работ — чтобы сервис не терял заявки и время механиков.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'от 2 недель',
    bodyHtml: avtoservisBody,
    relatedServices: [
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
    ],
    relatedBlog: [
      { url: '/blog/it-dlya-avtoservisa-2026/', label: 'IT для автосервиса' },
      { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' },
    ],
    faq: [
      { q: 'Сколько времени занимает внедрение?', a: 'Базовый запуск — около двух недель. Сроки зависят от количества интеграций и готовности ваших данных.' },
      { q: 'Нужно ли менять текущую программу учёта?', a: 'Не обязательно. Чаще всего мы добавляем недостающие модули и при необходимости интегрируемся с тем, что уже работает, включая 1С.' },
      { q: 'На какой платформе делается бот записи?', a: 'Под вашу аудиторию: Telegram, МАКС или виджет на сайте. Можно несколько каналов сразу.' },
    ],
    metaTitle: 'Цифровизация автосервиса под ключ | Чимитдоржи Дарижапов',
    metaDescription: 'Готовое решение для автосервиса и СТО: онлайн-запись, CRM, напоминания и учёт работ. Российский стек, 152-ФЗ. Внедрение от 2 недель, бесплатная консультация.',
  },
  {
    slug: 'obshchepit',
    published: true,
    segment: 'Автоматизация',
    niche: 'Кафе и общепит',
    icon: 'ph-fork-knife',
    title: 'IT-решение для кафе и общепита',
    tagline: 'Бот для заказов и брони, программа лояльности и автоматизация рутины — больше повторных гостей и меньше ручной работы.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'от 10 дней',
    bodyHtml: obshchepitBody,
    relatedServices: [
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
    ],
    relatedBlog: [
      { url: '/blog/it-dlya-horeca-2026/', label: 'IT для HoReCa' },
      { url: '/blog/max-bot-restoran-kafe-2026/', label: 'МАКС-бот для кафе' },
    ],
    faq: [
      { q: 'Подойдёт ли для маленькой кофейни или бара?', a: 'Да. Можно начать с малого — бот заказов и брони окупается даже при скромном потоке, а дальше добавлять модули.' },
      { q: 'Можно ли подключить онлайн-оплату?', a: 'Да, подключаем приём оплаты и при необходимости интеграцию с кассой.' },
      { q: 'Рассылки — это законно?', a: 'Да, если есть согласие гостя и соблюдены требования закона о рекламе (ст. 18 ФЗ-38) и 152-ФЗ. Настраиваю так, чтобы не было штрафов.' },
    ],
    metaTitle: 'IT-решение для кафе и общепита | Чимитдоржи Дарижапов',
    metaDescription: 'Готовое IT-решение для кафе и общепита: бот заказов и брони, программа лояльности, сбор отзывов, онлайн-оплата. Российский стек, 152-ФЗ. Бесплатная консультация.',
  },
  {
    slug: 'bot-dlya-biznesa',
    published: true,
    segment: 'Боты и AI',
    niche: 'Любой бизнес',
    icon: 'ph-robot',
    title: 'Чат-бот для бизнеса: Telegram, МАКС, VK',
    tagline: 'Бот, который принимает заявки, отвечает на вопросы и работает 24/7 — с подключением нейросети по желанию.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'от 1 недели',
    bodyHtml: botBody,
    relatedServices: [
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
      { url: '/services/ai-agents/', label: 'AI-агенты' },
    ],
    relatedBlog: [
      { url: '/blog/chatbot-telegram-max-vk-2026/', label: 'Боты: Telegram, MAX, VK' },
      { url: '/blog/ai-bot-v-max-gigachat-yandexgpt-2026/', label: 'AI-бот на российских нейросетях' },
    ],
    faq: [
      { q: 'Чем умный AI-бот отличается от обычного?', a: 'Обычный работает по сценарию и кнопкам. AI-бот понимает живые вопросы и отвечает по вашей базе знаний на нейросети GigaChat или YandexGPT.' },
      { q: 'Бот будет работать в МАКС?', a: 'Да. Делаю ботов под Telegram, МАКС и VK — можно запустить сразу на нескольких платформах.' },
      { q: 'Данные клиентов в безопасности?', a: 'Да. Использую российские нейросети с размещением данных в РФ и настраиваю обработку по 152-ФЗ.' },
    ],
    metaTitle: 'Чат-бот для бизнеса: Telegram, МАКС, VK | Чимитдоржи Дарижапов',
    metaDescription: 'Разработка чат-бота для бизнеса в Telegram, МАКС и VK: приём заявок, автоответы, интеграция с CRM, AI-режим на GigaChat/YandexGPT. Бесплатная консультация.',
  },
  {
    slug: 'geymifikaciya-kanala-max',
    published: true,
    segment: 'Геймификация',
    niche: 'Каналы и сообщества',
    icon: 'ph-trophy',
    title: 'Геймификация канала в МАКС: бот «Конкурс приглашений»',
    tagline: 'Рост подписчиков силами самих участников: реферальный конкурс с баллами, живым рейтингом и защитой от накруток — платите за реальных людей, а не за рекламу.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'готовая система, запуск за дни',
    bodyHtml: konkursBody,
    relatedServices: [
      { url: '/services/telegram-bots/', label: 'Чат-боты' },
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
    ],
    relatedBlog: [
      { url: '/blog/max-kanaly-rassylki-marketing-2026/', label: 'Каналы и рассылки в МАКС' },
      { url: '/blog/geymifikaciya-saas-2026/', label: 'Геймификация в бизнесе' },
      { url: '/blog/chatbot-telegram-max-vk-2026/', label: 'Боты: Telegram, MAX, VK' },
    ],
    faq: [
      { q: 'За что именно начисляется балл?', a: 'Только за нового подписчика, который перешёл по личной ссылке участника и остался в канале несколько дней. Это защита от «зашёл-вышел» и накруток.' },
      { q: 'Как защищаетесь от накрутчиков?', a: 'Система подсвечивает подозрительную активность, есть выдержка перед начислением и ручной контроль — накрутчика можно заблокировать или удалить, баллы скорректировать.' },
      { q: 'Что нужно от меня для запуска?', a: 'Канал в МАКС и добавить бота администратором (один раз). Перед конкурсом задаёте сроки, баллы за приглашение и призы. Призы победителям вручаете сами — система обеспечивает честный подсчёт.' },
    ],
    metaTitle: 'Геймификация канала в МАКС — бот «Конкурс приглашений» | Чимитдоржи Дарижапов',
    metaDescription: 'Бот «Конкурс приглашений» в МАКС: рост канала силами участников через реферальные ссылки, баллы и рейтинг, защита от накруток, админ-панель и статистика. Платите за реальных подписчиков.',
  },
  {
    slug: 'chestnye-rozygryshi',
    published: true,
    segment: 'Геймификация',
    niche: 'Розыгрыши и акции',
    icon: 'ph-ticket',
    title: 'Честные онлайн-розыгрыши для бизнеса',
    tagline: 'Гости покупают номерки, система проверяемо честно выбирает победителя (commit-reveal). Вовлечение, вирусный охват и дополнительная выручка — с защитой репутации.',
    priceFrom: 'Бесплатная консультация',
    timeline: 'обсуждается под формат',
    bodyHtml: rozygryshiBody,
    relatedServices: [
      { url: '/services/web-development/', label: 'Разработка веб-приложений' },
      { url: '/services/business-automation/', label: 'Автоматизация бизнеса' },
    ],
    relatedBlog: [
      { url: '/blog/geymifikaciya-saas-2026/', label: 'Геймификация в бизнесе' },
      { url: '/blog/it-dlya-horeca-2026/', label: 'IT для HoReCa' },
      { url: '/blog/svoy-magazin-vs-wildberries-ozon-2026/', label: 'Свой сервис vs маркетплейсы' },
    ],
    faq: [
      { q: 'Как гарантируется честность розыгрыша?', a: 'Используется механика commit-reveal: до старта продаж публикуется зашифрованный «отпечаток» секретного кода, после розыгрыша код раскрывается, и любой может пересчитать результат и убедиться, что победитель выбран честно, без подкрутки.' },
      { q: 'Как принимается оплата?', a: 'Онлайн-эквайринг (Т-Касса). Суммы считаются на сервере, оплата подтверждается вебхуком, один номерок невозможно продать дважды.' },
      { q: 'Это законно?', a: 'Платные розыгрыши в РФ регулируются (ФЗ-138 «О лотереях», стимулирующие акции имеют свои правила). Конкретный юридический формат подбираем и согласуем под ваш бизнес — а commit-reveal обеспечивает доказуемую честность.' },
    ],
    metaTitle: 'Честные онлайн-розыгрыши для бизнеса (commit-reveal) | Чимитдоржи Дарижапов',
    metaDescription: 'Веб-сервис розыгрышей для кафе и ретейла: гости покупают номерки и оплачивают онлайн, победитель выбирается проверяемо честно (commit-reveal). Вовлечение, охват и доп. выручка.',
  },
  {
    slug: 'zapis-salon-krasoty', published: true, segment: 'Автоматизация',
    niche: 'Салон красоты и барбершоп', icon: 'ph-scissors',
    title: 'Онлайн-запись для салонов красоты и барбершопов',
    tagline: 'Бот записи, расписание мастеров, напоминания и лояльность — меньше неявок и звонков, мастера загружены.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 10 дней', bodyHtml: salonBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/it-dlya-salonov-krasoty-2026/', label: 'IT для салона красоты' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Через что клиенты записываются?', a: 'Через бот в Telegram или МАКС, либо виджет записи на сайте. Можно несколько каналов сразу.' },
      { q: 'Уменьшит ли это неявки?', a: 'Да. Автонапоминания и подтверждение записи заметно снижают «забыл и не пришёл».' },
      { q: 'Подойдёт для одного мастера?', a: 'Да, решение масштабируется от частного мастера до сети салонов.' },
    ],
    metaTitle: 'Онлайн-запись для салонов красоты и барбершопов | Чимитдоржи Дарижапов',
    metaDescription: 'Готовое решение для салона красоты и барбершопа: онлайн-запись через бот, расписание мастеров, напоминания, лояльность. Меньше неявок, российский стек, 152-ФЗ.',
  },
  {
    slug: 'it-stomatologiya', published: true, segment: 'Медицина и MedTech',
    niche: 'Стоматология и медцентр', icon: 'ph-tooth',
    title: 'IT для стоматологии и медцентра',
    tagline: 'Онлайн-запись, карта пациента, напоминания о приёме и согласия по 152-ФЗ — порядок в записи и защита данных пациентов.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: stomatologiyaBody,
    relatedServices: [{ url: '/services/clinics-digitalization/', label: 'Цифровизация клиник' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/it-dlya-stomatologiy-medcentrov-2026/', label: 'IT для стоматологий и медцентров' }, { url: '/blog/soglasie-na-obrabotku-pd-2026/', label: 'Согласие на обработку ПД' }],
    faq: [
      { q: 'Как защищены данные пациентов?', a: 'Медданные — особая категория ПД. Настраиваю согласия, минимизацию данных и хранение в РФ строго по 152-ФЗ.' },
      { q: 'Можно интегрировать с нашей МИС?', a: 'Чаще всего да, через API. Если интеграция невозможна, добавляем недостающие модули рядом.' },
      { q: 'Что с напоминаниями о контрольных осмотрах?', a: 'Система сама напоминает пациентам о приёме и о плановых осмотрах — это возвращает пациентов.' },
    ],
    metaTitle: 'IT для стоматологии и медцентра: запись, карта пациента, 152-ФЗ | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для стоматологии и медцентра: онлайн-запись, карта пациента, напоминания о приёме, согласия и данные пациентов строго по 152-ФЗ. Российский стек.',
  },
  {
    slug: 'ai-konsultant', published: true, segment: 'Боты и AI',
    niche: 'Любой бизнес', icon: 'ph-headset',
    title: 'AI-консультант 24/7 для сайта и мессенджеров',
    tagline: 'Отвечает на вопросы по вашей базе знаний (RAG) на GigaChat/YandexGPT, принимает заявки и работает круглосуточно — без нагрузки на менеджеров.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: aiKonsultantBody,
    relatedServices: [{ url: '/services/ai-agents/', label: 'AI-агенты' }, { url: '/services/rag-systems/', label: 'RAG-системы' }],
    relatedBlog: [{ url: '/blog/ai-chatbot-na-sayt-bez-programmirovaniya-2026/', label: 'AI-чатбот на сайт' }, { url: '/blog/rag-sistemy-dlya-biznesa-2026/', label: 'RAG-системы для бизнеса' }],
    faq: [
      { q: 'Откуда AI берёт ответы?', a: 'Только из вашей базы знаний (товары, услуги, цены, FAQ) через RAG. Он не выдумывает — отвечает по вашим данным.' },
      { q: 'Где он работает?', a: 'Виджет на сайте и/или боты в Telegram, МАКС, VK — можно везде сразу.' },
      { q: 'А если AI не знает ответ?', a: 'Передаёт диалог живому оператору и собирает заявку — клиент не остаётся без ответа.' },
    ],
    metaTitle: 'AI-консультант 24/7 для сайта и мессенджеров (RAG) | Чимитдоржи Дарижапов',
    metaDescription: 'AI-консультант для бизнеса: отвечает по вашей базе знаний (RAG) на GigaChat/YandexGPT, принимает заявки 24/7 на сайте и в Telegram/МАКС/VK. Данные в РФ, 152-ФЗ.',
  },
  {
    slug: 'lichnyy-kabinet-klienta', published: true, segment: 'Автоматизация',
    niche: 'Услуги и B2B', icon: 'ph-identification-card',
    title: 'Личный кабинет клиента (портал самообслуживания)',
    tagline: 'Заявки, статусы, документы, оплаты и история в одном кабинете — клиенты решают вопросы сами, меньше звонков менеджерам.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: lichnyyKabinetBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }, { url: '/blog/svoy-sayt-vs-socseti-2026/', label: 'Свой сайт vs соцсети' }],
    faq: [
      { q: 'Кому это нужно?', a: 'Бизнесу, где клиенты часто спрашивают статусы, документы и историю: b2b-поставки, сервис, онлайн-школы, агентства, ЖКХ.' },
      { q: 'Интегрируется с CRM/1С?', a: 'Да, кабинет связывается с вашими системами, чтобы данные были актуальными.' },
      { q: 'Это безопасно?', a: 'Авторизация, разграничение доступа, обработка ПД по 152-ФЗ, данные в РФ.' },
    ],
    metaTitle: 'Личный кабинет клиента — портал самообслуживания | Чимитдоржи Дарижапов',
    metaDescription: 'Личный кабинет клиента для бизнеса: заявки и статусы, документы, оплаты, история и поддержка. Меньше рутинных звонков, интеграция с CRM/1С, 152-ФЗ.',
  },
  {
    slug: 'programma-loyalnosti', published: true, segment: 'Геймификация',
    niche: 'Ритейл и услуги', icon: 'ph-medal',
    title: 'Программа лояльности для бизнеса (баллы и кэшбэк в боте)',
    tagline: 'Цифровая карта, баллы и кэшбэк, уровни и реферальная программа в боте — клиенты возвращаются чаще и приводят друзей.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: loyalnostBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/geymifikaciya-saas-2026/', label: 'Геймификация в бизнесе' }, { url: '/blog/email-push-rassylki-rf-2026/', label: 'Рассылки в РФ' }],
    faq: [
      { q: 'Нужны ли пластиковые карты?', a: 'Нет. Карта лояльности живёт в боте и привязана к телефону — ничего печатать не нужно.' },
      { q: 'Подойдёт любому бизнесу?', a: 'Да: магазины, кафе, услуги, сети. Механику (баллы, кэшбэк, уровни) настраиваем под вас.' },
      { q: 'Рассылки законны?', a: 'Да, при согласии клиента и соблюдении закона о рекламе и 152-ФЗ — настраиваю так, чтобы не было штрафов.' },
    ],
    metaTitle: 'Программа лояльности для бизнеса — баллы и кэшбэк в боте | Чимитдоржи Дарижапов',
    metaDescription: 'Универсальная программа лояльности: цифровая карта, баллы и кэшбэк, уровни клиента и реферальная программа в боте. Для ритейла и услуг. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'bystryy-start-sayt', published: true, segment: 'Автоматизация',
    niche: 'Малый бизнес', icon: 'ph-rocket-launch',
    title: 'Быстрый старт: сайт + Яндекс Карты + квиз за неделю',
    tagline: 'Лендинг с квизом, карточки в Яндекс Картах и 2ГИС, мессенджеры и локальное SEO — присутствие в онлайне и первые заявки за неделю.',
    priceFrom: 'Бесплатная консультация', timeline: 'около недели', bodyHtml: bystryyStartBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка сайтов' }, { url: '/services/digital-marketing/', label: 'Маркетинг' }],
    relatedBlog: [{ url: '/blog/skolko-stoit-sayt-2026/', label: 'Сколько стоит сайт' }, { url: '/blog/lokalnoe-prodvizhenie-chita-ulan-ude-2026/', label: 'Локальное продвижение' }],
    faq: [
      { q: 'Правда за неделю?', a: 'Да, за счёт готовых проверенных блоков. От вас — тексты, фото и доступы; остальное беру на себя.' },
      { q: 'Что входит, кроме сайта?', a: 'Квиз для заявок, карточки в Яндекс Картах и 2ГИС, подключение мессенджеров, базовое локальное SEO и аналитика.' },
      { q: 'А если нужен магазин с каталогом?', a: 'Это уже отдельное решение — обсудим. «Быстрый старт» рассчитан на услуги и локальный бизнес.' },
    ],
    metaTitle: 'Быстрый старт в онлайн: сайт, Яндекс Карты, квиз за неделю | Чимитдоржи Дарижапов',
    metaDescription: 'Пакет «Быстрый старт» для малого бизнеса: лендинг с квизом, карточки в Яндекс Картах и 2ГИС, мессенджеры, локальное SEO. Присутствие в онлайне и заявки за неделю.',
  },
  {
    slug: 'avtomatizaciya-fitnesa', published: true, segment: 'Автоматизация',
    niche: 'Фитнес-клуб и студия', icon: 'ph-barbell',
    title: 'Автоматизация фитнес-клуба и студии',
    tagline: 'Абонементы со списанием занятий и заморозкой, запись на тренировки, расписание и напоминания — порядок в учёте и меньше оттока.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: fitnesBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/cifrovizaciya-fitnes-kluba-2026/', label: 'Цифровизация фитнес-клуба' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Как работают абонементы?', a: 'Система сама списывает занятия, поддерживает заморозку и напоминает об окончании абонемента — без тетрадей и Excel.' },
      { q: 'Подойдёт студии йоги или единоборств?', a: 'Да: фитнес-клубы, йога, танцы, единоборства, бассейны, секции.' },
      { q: 'Видно ли отток клиентов?', a: 'Да, аналитика показывает посещаемость и тех, кто перестал ходить, — можно вовремя вернуть.' },
    ],
    metaTitle: 'Автоматизация фитнес-клуба и студии: абонементы, расписание | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для фитнес-клуба и студии: запись на тренировки, абонементы со списанием и заморозкой, расписание тренеров, напоминания, аналитика оттока. Российский стек.',
  },
  {
    slug: 'onlayn-shkola-platforma', published: true, segment: 'Образование и EdTech',
    niche: 'Онлайн-школы и эксперты', icon: 'ph-graduation-cap',
    title: 'Платформа для онлайн-школы и курсов',
    tagline: 'Продажа курса, доступ к урокам, домашки, прогресс и напоминания через бот — продаёте и ведёте учеников в одной системе.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: onlaynShkolaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/web-development/', label: 'Разработка веб-приложений' }],
    relatedBlog: [{ url: '/blog/avtomatizaciya-onlayn-shkoly-2026/', label: 'Автоматизация онлайн-школы' }, { url: '/blog/it-dlya-yazykovoy-shkoly-repetitorov-2026/', label: 'IT для языковой школы' }],
    faq: [
      { q: 'Где хранятся уроки?', a: 'В личном кабинете ученика с доступом по расписанию и защитой контента. Видео и методология — ваши.' },
      { q: 'Можно принимать оплату?', a: 'Да, подключаем приём оплаты за курс. Договор эквайринга оформляете вы.' },
      { q: 'Как удерживаете учеников?', a: 'Бот напоминает об уроках и дедлайнах, показывает прогресс и выдаёт сертификаты — меньше «отвалившихся».' },
    ],
    metaTitle: 'Платформа для онлайн-школы и курсов под ключ | Чимитдоржи Дарижапов',
    metaDescription: 'Платформа для онлайн-школы: продающая страница и оплата, личный кабинет ученика, доступ к урокам, домашки, прогресс, напоминания через бот. Российский стек, 152-ФЗ.',
  },
  {
    slug: '152-fz-pod-klyuch', published: true, segment: 'Право',
    niche: 'Любой сайт с формой', icon: 'ph-shield-check',
    title: '«152-ФЗ под ключ»: защита от штрафов за персональные данные',
    tagline: 'Аудит, политика, согласия, уведомление в РКН и cookie-баннер — приводим сайт и бизнес в соответствие закону и снижаем риск штрафов.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 1–3 дней', bodyHtml: fz152Body,
    relatedServices: [{ url: 'https://audit.chimitdorzhi.tech/', label: 'Аудит 152-ФЗ' }, { url: '/services/rkn-audit/', label: 'Аудит РКН' }],
    relatedBlog: [{ url: '/blog/audit-152-fz-2026/', label: 'Аудит сайта по 152-ФЗ' }, { url: '/blog/uvedomlenie-rkn-2026/', label: 'Уведомление в РКН' }, { url: '/blog/oborotnye-shtrafy-utechki-pd-2026/', label: 'Оборотные штрафы за утечки' }],
    faq: [
      { q: 'Под закон попадает мой сайт?', a: 'Почти наверняка да — если есть хотя бы форма заявки, обратной связи или подписки, вы обрабатываете персональные данные.' },
      { q: 'Какие штрафы грозят?', a: 'С 2025 года повторные нарушения — до 500 000 ₽ для юрлиц, а оборотные штрафы за утечки — до 500 млн ₽. Пакет снижает эти риски.' },
      { q: 'Что я получу на руки?', a: 'Готовую политику и согласия, поданное уведомление в РКН, настроенный cookie-баннер и рекомендации по защите данных.' },
    ],
    metaTitle: '«152-ФЗ под ключ»: политика, согласия, уведомление РКН | Чимитдоржи Дарижапов',
    metaDescription: 'Приведение сайта и бизнеса в соответствие 152-ФЗ под ключ: аудит, политика обработки ПД, согласия, уведомление в Роскомнадзор, cookie-баннер. Снижение риска штрафов.',
  },
  {
    slug: 'integraciya-sistem', published: true, segment: 'Автоматизация',
    niche: 'Бизнес с несколькими системами', icon: 'ph-plugs-connected',
    title: 'Связка систем: сайт + CRM + 1С + мессенджеры',
    tagline: 'Заявки, клиенты, товары и переписка перестают жить порознь — настраиваю интеграции, чтобы данные ходили автоматически и заявки не терялись.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: integraciyaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/it-infrastructure/', label: 'IT-инфраструктура' }],
    relatedBlog: [{ url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }, { url: '/blog/importozameshchenie-po-2026/', label: 'Импортозамещение ПО' }],
    faq: [
      { q: 'С чем умеете интегрировать?', a: 'Сайт и квизы, популярные CRM, 1С, мессенджеры Telegram/МАКС/VK, платежи — через API и вебхуки, при необходимости через n8n.' },
      { q: 'Зачем это бизнесу?', a: 'Чтобы заявка с сайта сразу попадала в CRM, заказ — в 1С, а сообщение в мессенджере привязывалось к клиенту. Меньше ручного переноса и потерь.' },
      { q: 'Нужно ли менять текущие системы?', a: 'Нет, чаще связываем то, что уже работает. Покупку лицензий CRM/1С вы оформляете сами.' },
    ],
    metaTitle: 'Интеграция сайта, CRM, 1С и мессенджеров в единый поток | Чимитдоржи Дарижапов',
    metaDescription: 'Связка систем для бизнеса: интеграция сайта, CRM, 1С и мессенджеров через API и вебхуки. Заявки не теряются, данные ходят автоматически. Российский стек.',
  },
  {
    slug: 'bronirovanie-otel-glamping', published: true, segment: 'Автоматизация',
    niche: 'Отель и глэмпинг', icon: 'ph-bed',
    title: 'Онлайн-бронирование для отеля, гостевого дома и глэмпинга',
    tagline: 'Модуль брони с календарём занятости, онлайн-оплата и бот — прямые брони без комиссий агрегаторов и без двойных бронирований.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: otelBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/web-development/', label: 'Разработка веб-приложений' }],
    relatedBlog: [{ url: '/blog/it-dlya-turizma-otelei-2026/', label: 'IT для туризма и отелей' }, { url: '/blog/glamping-bazy-otdyha-2026/', label: 'IT для глэмпинга и баз отдыха' }],
    faq: [
      { q: 'Это снизит зависимость от агрегаторов?', a: 'Да. Прямые брони через ваш сайт и бот идут без комиссий Booking/Островка — вы платите только за разработку, а не процент с каждой брони.' },
      { q: 'Защита от двойных броней есть?', a: 'Да, календарь занятости обновляется атомарно — один номер/домик нельзя забронировать дважды.' },
      { q: 'Подойдёт для нескольких объектов?', a: 'Да: отели, гостевые дома, базы отдыха, глэмпинг, апартаменты — с любым числом номеров и категорий.' },
    ],
    metaTitle: 'Онлайн-бронирование для отеля, гостевого дома и глэмпинга | Чимитдоржи Дарижапов',
    metaDescription: 'Модуль бронирования для отеля и глэмпинга: календарь занятости, онлайн-оплата, бот в Telegram/МАКС, защита от двойных броней. Прямые брони без комиссий агрегаторов.',
  },
  {
    slug: 'bot-magazin-zakazy', published: true, segment: 'Боты и AI',
    niche: 'Магазин и торговля', icon: 'ph-shopping-bag',
    title: 'Бот-магазин: заказы и оплата в мессенджере',
    tagline: 'Витрина с каталогом, корзиной и онлайн-оплатой прямо в Telegram/МАКС/VK — продажи без отдельного сайта.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 10 дней', bodyHtml: botMagazinBody,
    relatedServices: [{ url: '/services/telegram-bots/', label: 'Чат-боты' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/magazin-bot-max-2026/', label: 'Магазин-бот в МАКС' }, { url: '/blog/svoy-magazin-vs-wildberries-ozon-2026/', label: 'Свой магазин vs маркетплейсы' }],
    faq: [
      { q: 'Нужен ли отдельный сайт?', a: 'Нет. Каталог, корзина и оплата работают прямо в мессенджере. Если позже понадобится полноценный сайт-магазин — это отдельное решение.' },
      { q: 'Как принимается оплата?', a: 'Онлайн-оплата картой внутри оформления заказа, статусы и уведомления приходят клиенту автоматически.' },
      { q: 'На какой платформе?', a: 'Telegram, МАКС или VK — можно на нескольких сразу, с единой админкой товаров и заказов.' },
    ],
    metaTitle: 'Бот-магазин: заказы и оплата в Telegram, МАКС, VK | Чимитдоржи Дарижапов',
    metaDescription: 'Магазин в мессенджере: каталог, корзина, онлайн-оплата, промокоды и админка заказов в Telegram/МАКС/VK. Продажи без сайта для малого ритейла. Российский стек.',
  },
  {
    slug: 'crm-agentstvo-nedvizhimosti', published: true, segment: 'Автоматизация',
    niche: 'Агентство недвижимости', icon: 'ph-house-line',
    title: 'CRM и бот для агентства недвижимости',
    tagline: 'База объектов с подбором под клиента, бот-подбор, CRM сделок и напоминания о показах — заявки не теряются, подбор за секунды.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: nedvizhimostBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/max-bot-rieltor-2026/', label: 'МАКС-бот для риелтора' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Как работает подбор?', a: 'Клиент задаёт параметры боту, и тот мгновенно подбирает подходящие объекты из вашей базы — без ручного перебора менеджером.' },
      { q: 'А показы и звонки не забудутся?', a: 'CRM напоминает о показах, звонках и задачах по каждой сделке — ничего не теряется.' },
      { q: 'Подойдёт частному риелтору?', a: 'Да, от частного риелтора до агентства и застройщика — масштабируется.' },
    ],
    metaTitle: 'CRM и бот для агентства недвижимости и риелтора | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для агентства недвижимости: база объектов, бот подбора под клиента, CRM сделок, напоминания о показах, рассылки подборок. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'it-dlya-avtoshkoly', published: true, segment: 'Образование и EdTech',
    niche: 'Автошкола', icon: 'ph-steering-wheel',
    title: 'IT для автошколы: запись, теория, оплата',
    tagline: 'Запись на занятия и экзамены, расписание инструкторов и машин, бот-тренажёр ПДД и оплата с рассрочкой — порядок в потоке учеников.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: avtoshkolaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/cifrovizaciya-avtoshkol-2026/', label: 'Цифровизация автошколы' }, { url: '/blog/avtomatizaciya-onlayn-shkoly-2026/', label: 'Автоматизация онлайн-школы' }],
    faq: [
      { q: 'Решает ли путаницу с расписанием?', a: 'Да. Запись на теорию, вождение и экзамены ведётся в единой системе — нет накладок по инструкторам и машинам.' },
      { q: 'Что за бот-тренажёр?', a: 'Бот в Telegram/МАКС с вопросами ПДД для повторения теории и напоминаниями о занятиях — ученики лучше готовятся.' },
      { q: 'Можно отслеживать оплату по частям?', a: 'Да, система учитывает рассрочку и напоминает об оплате.' },
    ],
    metaTitle: 'IT для автошколы: запись, бот-тренажёр ПДД, оплата | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для автошколы: запись на занятия и экзамены, расписание инструкторов и автомобилей, бот-тренажёр ПДД, оплата с рассрочкой, личный кабинет ученика. Российский стек.',
  },
  {
    slug: 'avtomatizaciya-sellera-wb-ozon', published: true, segment: 'Боты и AI',
    niche: 'Селлеры WB и Ozon', icon: 'ph-storefront',
    title: 'Автоматизация селлера на Wildberries и Ozon',
    tagline: 'AI-карточки и SEO-описания, авто-ответы на отзывы, аналитика и репрайсинг — экономия десятков часов в неделю.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: sellerBody,
    relatedServices: [{ url: '/services/ai-agents/', label: 'AI-агенты' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/ai-dlya-sellerov-wb-ozon-2026/', label: 'AI для селлеров WB и Ozon' }, { url: '/blog/seo-internet-magazina-yandex-30-hakov-2026/', label: 'SEO интернет-магазина' }],
    faq: [
      { q: 'AI сам напишет карточки?', a: 'AI готовит SEO-описания и заголовки под внутренний поиск площадок, а вы проверяете и утверждаете — человек всегда контролирует факты.' },
      { q: 'Отвечает ли на отзывы?', a: 'Да, авто-ответы в тоне бренда на типовые отзывы, спорные — на ручную модерацию.' },
      { q: 'Что с ценами?', a: 'Репрайсер отслеживает рынок и помогает держать цену конкурентной по вашим правилам.' },
    ],
    metaTitle: 'Автоматизация селлера на Wildberries и Ozon (AI) | Чимитдоржи Дарижапов',
    metaDescription: 'Автоматизация для селлера WB и Ozon: AI-генерация карточек и SEO-описаний, авто-ответы на отзывы, аналитика продаж и репрайсинг на российских нейросетях. Экономия времени.',
  },
  {
    slug: 'zayavki-klining-uslugi', published: true, segment: 'Автоматизация',
    niche: 'Клининг и выездные услуги', icon: 'ph-broom',
    title: 'Заявки и расписание для клининга и выездных услуг',
    tagline: 'Приём заказов через бот/сайт, распределение по бригадам, маршруты и напоминания — ни одна заявка не теряется, бригады загружены ровно.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: kliningBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/it-dlya-kliningovoy-kompanii-2026/', label: 'IT для клининговой компании' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Как распределяются заявки?', a: 'Заявка с сайта или бота попадает в систему, вы назначаете бригаду — ей приходит уведомление с адресом, временем и составом работ.' },
      { q: 'Поддерживает регулярные заказы?', a: 'Да, повторные и регулярные уборки настраиваются с автонапоминаниями клиенту.' },
      { q: 'Для каких услуг подходит?', a: 'Клининг, мойка окон, дезинфекция, муж на час, выездной сервис, доставка-монтаж.' },
    ],
    metaTitle: 'Заявки и расписание для клининга и выездных услуг | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для клининга и выездных услуг: приём заявок через бот/сайт, распределение по бригадам, маршруты, напоминания, повторные заказы, оплата. Российский стек.',
  },
  {
    slug: 'b2b-portal-opt', published: true, segment: 'Автоматизация',
    niche: 'Опт и дистрибуция', icon: 'ph-warehouse',
    title: 'B2B-портал заказов для опта и дистрибьютора',
    tagline: 'Личный кабинет оптового клиента с индивидуальными прайсами, остатками и повторными заказами 24/7 — меньше ручной работы менеджеров.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: b2bBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/web-development/', label: 'Разработка веб-приложений' }],
    relatedBlog: [{ url: '/blog/cifrovizaciya-optovoy-bazy-distributora-2026/', label: 'Цифровизация оптовой базы' }, { url: '/blog/voronka-prodazh-b2b-2026/', label: 'Воронка продаж B2B' }],
    faq: [
      { q: 'Клиенты увидят свои цены?', a: 'Да, у каждого оптового клиента свои прайсы и скидки — портал показывает индивидуальные условия.' },
      { q: 'Остатки актуальные?', a: 'Да, через интеграцию с 1С остатки и цены подтягиваются в реальном времени.' },
      { q: 'Это снизит нагрузку на менеджеров?', a: 'Заметно: клиенты делают повторные заказы сами 24/7, менеджеры перестают вручную собирать заявки и прайсы.' },
    ],
    metaTitle: 'B2B-портал заказов для опта и дистрибьютора | Чимитдоржи Дарижапов',
    metaDescription: 'B2B-портал для опта: личный кабинет клиента, индивидуальные прайсы, остатки в реальном времени, повторные заказы 24/7, интеграция с 1С. Меньше ручной работы.',
  },
  {
    slug: 'dostavka-bot-povtornye-zakazy', published: true, segment: 'Автоматизация',
    niche: 'Доставка воды и продуктов', icon: 'ph-truck',
    title: 'Доставка воды и продуктов: бот повторных заказов',
    tagline: 'Заказ в один тап, подписка и автоповтор, напоминания «пора заказать» и маршрут курьера — регулярность и удержание клиентов.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 10 дней', bodyHtml: dostavkaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/dostavka-vody-produktov-2026/', label: 'IT для доставки воды и продуктов' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Чем полезен автоповтор?', a: 'Клиент один раз настраивает состав и график — дальше бот сам напоминает и оформляет повторный заказ. Это держит регулярную выручку.' },
      { q: 'Поможет курьерам?', a: 'Да, заказы собираются в маршрут, статусы видны клиенту и курьеру.' },
      { q: 'Для каких товаров?', a: 'Доставка воды, продуктовые лавки, фермерские наборы, готовая еда, зоотовары.' },
    ],
    metaTitle: 'Доставка воды и продуктов: бот повторных заказов | Чимитдоржи Дарижапов',
    metaDescription: 'Бот для доставки воды и продуктов: заказ в один тап, подписка и автоповтор, напоминания, онлайн-оплата, маршрут курьера. Регулярная выручка и удержание клиентов.',
  },
  {
    slug: 'crm-stroitelnaya-kompaniya', published: true, segment: 'Автоматизация',
    niche: 'Строительство и ремонт', icon: 'ph-hammer',
    title: 'CRM для строительной и ремонтной компании',
    tagline: 'Заявки, сметы, объекты и этапы в одной системе, статус для клиента — порядок в проектах и прозрачные оплаты.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: stroykaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/it-infrastructure/', label: 'IT-инфраструктура' }],
    relatedBlog: [{ url: '/blog/it-dlya-stroitelnyh-kompaniy-2026/', label: 'IT для строительных компаний' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Клиент увидит статус работ?', a: 'Да, по каждому объекту — этапы, фото и статус. Это снимает поток вопросов «что там у вас по моему ремонту».' },
      { q: 'Сметы тоже в системе?', a: 'Да, сметы и расчёты привязаны к объекту, оплаты учитываются по этапам.' },
      { q: 'Для кого?', a: 'Строительные и ремонтные компании, отделка, монтаж, ландшафт, мебель на заказ.' },
    ],
    metaTitle: 'CRM для строительной и ремонтной компании | Чимитдоржи Дарижапов',
    metaDescription: 'CRM для стройки и ремонта: заявки и сделки, карточки объектов с этапами и фото, сметы, график подрядчиков, статус и оплаты по этапам. Порядок в проектах. Российский стек.',
  },
  {
    slug: 'ai-pomoshchnik-yurist-buhgalter', published: true, segment: 'Боты и AI',
    niche: 'Юристы и бухгалтеры', icon: 'ph-scales',
    title: 'AI-помощник для юриста и бухгалтера',
    tagline: 'Готовит черновики типовых документов и отвечает по вашей базе знаний (RAG) на российских нейросетях — экономит часы на рутине.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: aiYurbuhBody,
    relatedServices: [{ url: '/services/ai-agents/', label: 'AI-агенты' }, { url: '/services/rag-systems/', label: 'RAG-системы' }],
    relatedBlog: [{ url: '/blog/ai-dlya-yurista-dokumenty-2026/', label: 'AI для юриста: документы' }, { url: '/blog/ai-pomoshchnik-buhgaltera-2026/', label: 'AI-помощник бухгалтера' }],
    faq: [
      { q: 'AI заменит специалиста?', a: 'Нет. Он готовит черновик и подсказывает по вашей базе, а итог проверяет и утверждает юрист или бухгалтер. Ответственность остаётся за специалистом.' },
      { q: 'Откуда берёт ответы?', a: 'Из ваших документов, шаблонов и регламентов через RAG — отвечает по вашим материалам, а не из «общих знаний».' },
      { q: 'Данные конфиденциальны?', a: 'Да, используем российские нейросети с размещением данных в РФ и соблюдением 152-ФЗ.' },
    ],
    metaTitle: 'AI-помощник для юриста и бухгалтера (документы, RAG) | Чимитдоржи Дарижапов',
    metaDescription: 'AI-помощник для юриста и бухгалтера: черновики типовых документов, ответы по вашей базе знаний (RAG) на GigaChat/YandexGPT. Данные в РФ, 152-ФЗ. Человек утверждает итог.',
  },
  {
    slug: 'it-vetklinika', published: true, segment: 'Медицина и MedTech',
    niche: 'Ветеринарная клиника', icon: 'ph-paw-print',
    title: 'IT для ветеринарной клиники',
    tagline: 'Онлайн-запись, карта питомца и автонапоминания о вакцинации и приёме — меньше неявок, клиенты возвращаются вовремя.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: vetklinikaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/cifrovizaciya-vetklinik-2026/', label: 'Цифровизация ветклиники' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Напоминания о прививках работают сами?', a: 'Да. Система хранит даты вакцинаций и обработок по каждому питомцу и сама напоминает владельцу — это возвращает клиентов вовремя.' },
      { q: 'Где ведётся история питомца?', a: 'В карте питомца: приёмы, назначения, прививки. Всё в одном месте, доступно врачу на приёме.' },
      { q: 'Подойдёт грумингу и передержке?', a: 'Да: ветклиники, ветаптеки, груминг, передержки — запись и напоминания нужны всем.' },
    ],
    metaTitle: 'IT для ветеринарной клиники: запись, карта питомца, прививки | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для ветклиники: онлайн-запись, карта питомца с историей, автонапоминания о вакцинации и приёме, база клиентов. Меньше неявок. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'bronirovanie-kovorking', published: true, segment: 'Автоматизация',
    niche: 'Коворкинг и площадки', icon: 'ph-armchair',
    title: 'Бронирование коворкинга, залов и площадок',
    tagline: 'Онлайн-бронирование по слотам с календарём занятости и оплатой — почасовая аренда без двойных броней и простоев.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: kovorkingBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/it-dlya-turizma-otelei-2026/', label: 'IT для туризма' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Защита от двойных броней есть?', a: 'Да, календарь занятости обновляется атомарно — один слот нельзя забронировать дважды.' },
      { q: 'Можно брать предоплату?', a: 'Да, онлайн-оплата и предоплата защищают от пустых броней.' },
      { q: 'Для каких помещений подходит?', a: 'Коворкинги, переговорные, фотостудии, спортзалы и корты, банкетные и event-залы, антикафе.' },
    ],
    metaTitle: 'Бронирование коворкинга, залов и площадок онлайн | Чимитдоржи Дарижапов',
    metaDescription: 'Онлайн-бронирование для коворкинга, переговорных, студий и залов: календарь занятости, почасовая аренда, оплата, бот, учёт загрузки. Без двойных броней. Российский стек.',
  },
  {
    slug: 'zakazy-tipografiya', published: true, segment: 'Автоматизация',
    niche: 'Типография и полиграфия', icon: 'ph-printer',
    title: 'Приём заказов для типографии и полиграфии',
    tagline: 'Форма заказа с расчётом стоимости, загрузкой макетов и статусами — заявки не теряются, повторный заказ в один клик.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: tipografiyaBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }, { url: '/blog/skolko-stoit-sayt-2026/', label: 'Сколько стоит сайт' }],
    faq: [
      { q: 'Клиент сам рассчитает заказ?', a: 'Да, форма с параметрами считает примерную стоимость и принимает макет — менеджер не тратит время на типовые расчёты.' },
      { q: 'Повторные заказы удобны?', a: 'Да, повторить прошлый заказ можно в один клик — это удобно для постоянных корпоративных клиентов.' },
      { q: 'Кому подходит?', a: 'Типографии, полиграфия, рекламно-производственные компании, фотопечать, сувенирная продукция.' },
    ],
    metaTitle: 'Приём заказов для типографии и полиграфии онлайн | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для типографии: онлайн-форма заказа с расчётом, загрузка макетов, статусы заказа, повторный заказ в один клик, оплата. Заявки не теряются. Российский стек.',
  },
  {
    slug: 'himchistka-prachechnaya', published: true, segment: 'Автоматизация',
    niche: 'Химчистка и прачечная', icon: 'ph-t-shirt',
    title: 'Химчистка и прачечная: заказы и статусы',
    tagline: 'Приём заказов, статус по номеру квитанции, уведомления «готово» и вызов доставки — без звонков «готово ли?» и потерянных клиентов.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 2 недель', bodyHtml: himchistkaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/it-dlya-kliningovoy-kompanii-2026/', label: 'IT для клининга' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Как клиент узнаёт, что готово?', a: 'Статус виден по номеру квитанции, а при готовности приходит уведомление «готово к выдаче» — звонки «готово ли?» исчезают.' },
      { q: 'Есть доставка?', a: 'Да, клиент может вызвать курьера на забор и доставку прямо из бота/на сайте.' },
      { q: 'Кому подходит?', a: 'Химчистки, прачечные, прачечные самообслуживания с доставкой, ремонт одежды и обуви.' },
    ],
    metaTitle: 'Химчистка и прачечная: приём заказов и статусы онлайн | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для химчистки и прачечной: приём заказов через бот/сайт, статус по квитанции, уведомления о готовности, вызов доставки, лояльность. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'golosovoy-ai-bot', published: true, segment: 'Боты и AI',
    niche: 'Телефония', icon: 'ph-phone-call',
    title: 'Голосовой AI-бот для телефонии',
    tagline: 'Принимает звонки, отвечает на типовое голосом, записывает клиентов и фиксирует заявки 24/7 — ни один звонок не теряется.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: golosovoyBody,
    relatedServices: [{ url: '/services/voice-ai/', label: 'Голосовой AI' }, { url: '/services/ai-agents/', label: 'AI-агенты' }],
    relatedBlog: [{ url: '/blog/chatbot-telegram-max-vk-2026/', label: 'Чат-боты для бизнеса' }, { url: '/blog/rossiyskiy-ai-stack-2026/', label: 'Российский AI-стек' }],
    faq: [
      { q: 'Бот заменит операторов?', a: 'Нет, он закрывает первую линию: типовые вопросы, запись и заявки. Сложные и эмоциональные звонки переводит на живого оператора.' },
      { q: 'Говорит по-русски естественно?', a: 'Да, используем российские технологии синтеза и распознавания речи.' },
      { q: 'Нужен ли отдельный номер?', a: 'Подключаемся к вашей телефонии или провайдеру — номер менять не обязательно.' },
    ],
    metaTitle: 'Голосовой AI-бот для телефонии: приём звонков и заявок 24/7 | Чимитдоржи Дарижапов',
    metaDescription: 'Голосовой AI-бот: принимает звонки, отвечает голосом на типовое, записывает клиентов и фиксирует заявки в CRM круглосуточно. Российские технологии речи, данные в РФ.',
  },
  {
    slug: 'baza-znaniy-ai', published: true, segment: 'Боты и AI',
    niche: 'Корпоративная база знаний', icon: 'ph-books',
    title: 'Корпоративная база знаний с AI-поиском',
    tagline: 'Сотрудники мгновенно находят ответы по вашим регламентам через AI (RAG) — быстрый онбординг и меньше отвлечений на коллег.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: bazaZnaniyBody,
    relatedServices: [{ url: '/services/rag-systems/', label: 'RAG-системы' }, { url: '/services/ai-agents/', label: 'AI-агенты' }],
    relatedBlog: [{ url: '/blog/rag-sistemy-dlya-biznesa-2026/', label: 'RAG-системы для бизнеса' }, { url: '/blog/rossiyskiy-ai-stack-2026/', label: 'Российский AI-стек' }],
    faq: [
      { q: 'Откуда AI берёт ответы?', a: 'Только из ваших документов и регламентов через RAG — отвечает по вашим материалам и даёт ссылку на источник.' },
      { q: 'Где сотрудники задают вопросы?', a: 'В веб-интерфейсе или в боте Telegram/МАКС — как удобнее команде.' },
      { q: 'Данные не утекут?', a: 'Российские нейросети, данные в РФ, разграничение доступа и соблюдение 152-ФЗ.' },
    ],
    metaTitle: 'Корпоративная база знаний с AI-поиском для сотрудников | Чимитдоржи Дарижапов',
    metaDescription: 'База знаний с AI-ассистентом (RAG): сотрудники мгновенно находят ответы по регламентам, быстрый онбординг, меньше отвлечений. GigaChat/YandexGPT, данные в РФ, 152-ФЗ.',
  },
  {
    slug: 'hr-bot-podbor', published: true, segment: 'Боты и AI',
    niche: 'HR и рекрутинг', icon: 'ph-users-three',
    title: 'HR-бот: подбор и скрининг кандидатов',
    tagline: 'Собирает отклики, задаёт первичные вопросы и ведёт воронку найма — быстрее обрабатываете поток кандидатов, особенно при массовом найме.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: hrBody,
    relatedServices: [{ url: '/services/hr-team-management/', label: 'HR и управление командой' }, { url: '/services/ai-agents/', label: 'AI-агенты' }],
    relatedBlog: [{ url: '/blog/ai-v-hr-naym-2026/', label: 'AI в HR и найме' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Бот сам решает, кого нанять?', a: 'Нет. Он собирает отклики, проводит первичный скрининг по вашим критериям и готовит воронку — финальное решение за вами.' },
      { q: 'Где кандидаты отвечают?', a: 'Через бот по ссылке из вакансии — отклик и анкета собираются автоматически, рекрутер видит готовую воронку.' },
      { q: 'Что с данными кандидатов?', a: 'ПД соискателей обрабатываются с согласия и хранятся в РФ по 152-ФЗ.' },
    ],
    metaTitle: 'HR-бот для подбора и скрининга кандидатов | Чимитдоржи Дарижапов',
    metaDescription: 'HR-бот: приём откликов, первичный скрининг по критериям, анкеты, назначение интервью, воронка найма. Для массового найма и кадровых агентств. Данные в РФ, 152-ФЗ.',
  },
  {
    slug: 'zapis-chastnaya-praktika', published: true, segment: 'Медицина и MedTech',
    niche: 'Частная практика', icon: 'ph-user-focus',
    title: 'Запись и кабинет для частной практики',
    tagline: 'Онлайн-запись на сессии, оплата и пакеты, личный кабинет клиента — больше времени на работу, а не на администрирование.',
    priceFrom: 'Бесплатная консультация', timeline: 'от 10 дней', bodyHtml: praktikaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/web-development/', label: 'Разработка веб-приложений' }],
    relatedBlog: [{ url: '/blog/it-dlya-yazykovoy-shkoly-repetitorov-2026/', label: 'IT для репетиторов' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Снизит ли неявки и переносы?', a: 'Да, подтверждение записи и напоминания заметно уменьшают неявки и хаотичные переносы.' },
      { q: 'Можно продавать пакеты сессий?', a: 'Да, поддерживаются абонементы и пакеты с оплатой онлайн.' },
      { q: 'Данные клиентов конфиденциальны?', a: 'Да: это чувствительные данные, обрабатываются с согласия и хранятся в РФ по 152-ФЗ.' },
    ],
    metaTitle: 'Запись и личный кабинет для частной практики | Чимитдоржи Дарижапов',
    metaDescription: 'Решение для психологов, коучей, репетиторов и нутрициологов: онлайн-запись на сессии, оплата и пакеты, личный кабинет клиента, напоминания. Конфиденциально, 152-ФЗ.',
  },
  {
    slug: 'crm-turagentstvo', published: true, segment: 'Автоматизация',
    niche: 'Турагентство', icon: 'ph-airplane-tilt',
    title: 'CRM для турагентства',
    tagline: 'Заявки в одном месте, подбор и карточки туристов, напоминания о доплатах, документах и вылетах — клиенты возвращаются за повторными турами.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: turagentstvoBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/it-dlya-turizma-otelei-2026/', label: 'IT для туризма и отелей' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Заявки из разных каналов соберутся?', a: 'Да, заявки с сайта и из мессенджеров попадают в единую CRM — ничего не теряется.' },
      { q: 'Поможет не забывать про доплаты и вылеты?', a: 'Да, система напоминает о доплатах, документах, вылете и возвращении по каждому туристу.' },
      { q: 'Что с паспортными данными?', a: 'Это особо чувствительные данные: обрабатываются с согласия и хранятся в РФ по 152-ФЗ.' },
    ],
    metaTitle: 'CRM для турагентства: заявки, подбор туров, напоминания | Чимитдоржи Дарижапов',
    metaDescription: 'CRM для турагентства: заявки из всех каналов, карточки туристов и история, бот подбора, напоминания о доплатах, документах и вылетах, рассылки горящих туров. 152-ФЗ.',
  },
  {
    slug: 'dashboard-rukovoditelya', published: true, segment: 'Автоматизация',
    niche: 'Аналитика и BI', icon: 'ph-chart-donut',
    title: 'Дашборд и отчёты для руководителя (BI под ключ)',
    tagline: 'Выручка, заявки, конверсия и загрузка из всех систем на одном экране — решения на цифрах, а не на ощущениях.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: dashboardBody,
    relatedServices: [{ url: '/services/business-analytics-unit-economics/', label: 'Бизнес-аналитика' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/yunit-ekonomika-osnovatelya-2026/', label: 'Юнит-экономика основателя' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для малого бизнеса' }],
    faq: [
      { q: 'Откуда берутся данные?', a: 'Собираем из ваших источников — CRM, 1С, сайт и аналитика, рекламные кабинеты, эквайринг, таблицы — в единый дашборд.' },
      { q: 'Где смотреть отчёты?', a: 'В веб-дашборде и в виде сводок в боте по расписанию — цифры всегда под рукой, в том числе на телефоне.' },
      { q: 'А если данные в бардаке?', a: 'Сначала наводим порядок в источниках — корректная аналитика возможна только на чистых данных.' },
    ],
    metaTitle: 'Дашборд и отчёты для руководителя (BI под ключ) | Чимитдоржи Дарижапов',
    metaDescription: 'BI-дашборд для руководителя: выручка, заявки, конверсия, средний чек, загрузка и ROI из CRM, 1С, сайта и рекламы на одном экране. Отчёты в боте. Российский стек.',
  },
  {
    slug: 'cifrovizaciya-pod-klyuch', published: true, segment: 'Флагманы',
    niche: 'Комплексный проект', icon: 'ph-stack',
    title: 'Цифровизация бизнеса под ключ («всё включено»)',
    tagline: 'Сайт, CRM, боты, интеграции, аналитика и обучение команды — полный переход бизнеса в цифру одним проектом, без зоопарка систем.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается под объём', bodyHtml: cifrovizaciyaVseBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/cto-as-a-service/', label: 'CTO-as-a-service' }],
    relatedBlog: [{ url: '/blog/cifrovizaciya-biznesa-buryatiya-zabaykalye-2026/', label: 'Цифровизация бизнеса в регионе' }, { url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для бизнеса' }],
    faq: [
      { q: 'Чем это лучше, чем собирать по кускам?', a: 'Единые данные и один ответственный за результат. Собирать у разных подрядчиков дольше и дороже, а системы потом не дружат между собой.' },
      { q: 'Можно поэтапно?', a: 'Да. Начинаем с аудита и MVP, дальше подключаем модули по приоритету — но по единой архитектуре.' },
      { q: 'Сколько это стоит?', a: 'Зависит от объёма и числа модулей. Называю смету после аудита — начните с бесплатной консультации.' },
    ],
    metaTitle: 'Цифровизация бизнеса под ключ: сайт, CRM, боты, аналитика | Чимитдоржи Дарижапов',
    metaDescription: 'Комплексная цифровизация бизнеса под ключ: сайт, CRM, чат-боты, интеграции с 1С, аналитика и обучение команды. Единая экосистема вместо разрозненных инструментов. Российский стек.',
  },
  {
    slug: 'platforma-loyalnosti-uderzhaniya', published: true, segment: 'Флагманы',
    niche: 'Платформа удержания', icon: 'ph-crown',
    title: 'Омниканальная платформа лояльности и удержания',
    tagline: 'PWA-карта, боты, кэшбэк и уровни, аналитика поведения и омниканальные рассылки — превращает разовых клиентов в постоянных.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: platformaLoyalnostiBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/telegram-bots/', label: 'Чат-боты' }],
    relatedBlog: [{ url: '/blog/geymifikaciya-saas-2026/', label: 'Геймификация в бизнесе' }, { url: '/blog/email-push-rassylki-rf-2026/', label: 'Рассылки в РФ' }],
    faq: [
      { q: 'Чем отличается от обычной карты лояльности?', a: 'Это платформа удержания: не только баллы, но и аналитика поведения (частота, LTV, отток) и омниканальные коммуникации, которые сами возвращают клиента.' },
      { q: 'Какие каналы поддерживаются?', a: 'PWA-карта, боты Telegram/МАКС, push и SMS — клиенту удобно, бизнесу единая база.' },
      { q: 'Рассылки законны?', a: 'Да, с согласием клиента и по закону о рекламе и 152-ФЗ.' },
    ],
    metaTitle: 'Омниканальная платформа лояльности и удержания клиентов | Чимитдоржи Дарижапов',
    metaDescription: 'Платформа удержания: PWA-карта, боты, кэшбэк и уровни, реферальная программа, аналитика поведения и омниканальные рассылки. Возвращает клиентов. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'zapusk-saas-produkta', published: true, segment: 'Флагманы',
    niche: 'SaaS-продукт', icon: 'ph-cloud-arrow-up',
    title: 'Запуск SaaS-продукта под ключ',
    tagline: 'Свой онлайн-сервис с подписками, кабинетами и оплатами — от идеи до работающего продукта с регулярной выручкой.',
    priceFrom: 'Бесплатная консультация', timeline: 'MVP за несколько недель', bodyHtml: saasBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/cto-as-a-service/', label: 'CTO-as-a-service' }],
    relatedBlog: [{ url: '/blog/mvp-to-production-3-mesyatsa-2026/', label: 'MVP за 3 месяца' }, { url: '/blog/saas-pricing-2026/', label: 'Ценообразование SaaS' }],
    faq: [
      { q: 'Это сайт или продукт?', a: 'Продукт-бизнес: мультитенантность, тарифы и подписки, кабинеты, биллинг и аналитика — то, что приносит регулярную выручку.' },
      { q: 'С чего начинаем?', a: 'С валидации идеи и MVP, чтобы проверить спрос с минимальными затратами, а затем масштабируем.' },
      { q: 'Гарантируете успех на рынке?', a: 'Нет, рыночный успех зависит от спроса и маркетинга. Я отвечаю за качественную реализацию и помогаю считать юнит-экономику.' },
    ],
    metaTitle: 'Запуск SaaS-продукта под ключ: подписки, кабинеты, биллинг | Чимитдоржи Дарижапов',
    metaDescription: 'Запуск SaaS под ключ: архитектура и MVP, мультитенантность, биллинг и подписки, личные кабинеты, API и аналитика. От идеи до продукта с регулярной выручкой. Российский стек.',
  },
  {
    slug: 'marketplace-pod-nishu', published: true, segment: 'Флагманы',
    niche: 'Маркетплейс и агрегатор', icon: 'ph-share-network',
    title: 'Маркетплейс / агрегатор под нишу или город',
    tagline: 'Двусторонняя платформа «исполнители ↔ клиенты» с монетизацией — свой агрегатор услуг под отрасль или регион.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: marketplaceBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/cto-as-a-service/', label: 'CTO-as-a-service' }],
    relatedBlog: [{ url: '/blog/svoy-magazin-vs-wildberries-ozon-2026/', label: 'Свой сервис vs маркетплейсы' }, { url: '/blog/mvp-to-production-3-mesyatsa-2026/', label: 'MVP за 3 месяца' }],
    faq: [
      { q: 'Как маркетплейс зарабатывает?', a: 'Комиссия со сделок, платное размещение, подписка исполнителей или продвижение в топе — модель подбираем под вашу нишу.' },
      { q: 'С чего начать, чтобы не провалиться?', a: 'С узкой ниши или одного города и MVP — сначала набираем одну сторону платформы, решая «проблему курицы и яйца».' },
      { q: 'Кому подходит?', a: 'Предпринимателям, отраслевым лидерам, ассоциациям и медиа с аудиторией.' },
    ],
    metaTitle: 'Маркетплейс и агрегатор под нишу или город под ключ | Чимитдоржи Дарижапов',
    metaDescription: 'Разработка маркетплейса/агрегатора: кабинеты исполнителей и клиентов, поиск и отзывы, модерация, монетизация (комиссия, подписка, продвижение). Двусторонняя платформа. Российский стек.',
  },
  {
    slug: 'ai-otdel-prodazh-podderzhki', published: true, segment: 'Флагманы',
    niche: 'AI для продаж и поддержки', icon: 'ph-brain',
    title: 'AI-отдел продаж и поддержки под ключ',
    tagline: 'Омниканальный AI (сайт, мессенджеры, телефон) + база знаний + CRM + передача операторам — заявки и вопросы закрываются 24/7.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: aiOtdelBody,
    relatedServices: [{ url: '/services/ai-agents/', label: 'AI-агенты' }, { url: '/services/rag-systems/', label: 'RAG-системы' }],
    relatedBlog: [{ url: '/blog/ai-agenty-v-biznese-2026/', label: 'AI-агенты в бизнесе' }, { url: '/blog/rag-sistemy-dlya-biznesa-2026/', label: 'RAG-системы' }],
    faq: [
      { q: 'Это один бот?', a: 'Нет, это единый AI-слой: виджет на сайте, боты в Telegram/МАКС/VK и голосовой AI на телефоне — с общей базой знаний и CRM.' },
      { q: 'А люди ещё нужны?', a: 'Да. AI закрывает типовое и первую линию, сложное и крупные сделки передаёт операторам. Человек контролирует.' },
      { q: 'Данные клиентов в безопасности?', a: 'AI отвечает только по вашей базе (RAG), данные в РФ, по 152-ФЗ.' },
    ],
    metaTitle: 'AI-отдел продаж и поддержки под ключ (омниканальный) | Чимитдоржи Дарижапов',
    metaDescription: 'AI-отдел продаж и поддержки: омниканальный AI на сайте, в мессенджерах и на телефоне, база знаний RAG, CRM, маршрутизация и передача операторам, аналитика. Обработка 24/7.',
  },
  {
    slug: 'obrazovatelnaya-platforma-lms', published: true, segment: 'Образование и EdTech',
    niche: 'Образовательная платформа', icon: 'ph-chalkboard-teacher',
    title: 'Образовательная платформа (LMS) под ключ',
    tagline: 'Своя онлайн-школа на много курсов и потоков: продажи, кабинеты, домашки, прогресс и аналитика — без процентов с оборота.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: lmsBody,
    relatedServices: [{ url: '/services/web-development/', label: 'Разработка веб-приложений' }, { url: '/services/business-automation/', label: 'Автоматизация бизнеса' }],
    relatedBlog: [{ url: '/blog/avtomatizaciya-onlayn-shkoly-2026/', label: 'Автоматизация онлайн-школы' }, { url: '/blog/it-dlya-yazykovoy-shkoly-repetitorov-2026/', label: 'IT для языковой школы' }],
    faq: [
      { q: 'Чем лучше Геткурса и конструкторов?', a: 'Своя платформа — без процентов с оборота, с кастомизацией под ваши процессы и полным контролем над данными. Окупается на масштабе.' },
      { q: 'Это для одного курса?', a: 'Нет, это платформа на много курсов, потоков и преподавателей — для растущей онлайн-школы или учебного центра. Для одного курса есть отдельное решение.' },
      { q: 'Данные учеников защищены?', a: 'Да, данные в РФ и обработка по 152-ФЗ.' },
    ],
    metaTitle: 'Образовательная платформа (LMS) под ключ для онлайн-школы | Чимитдоржи Дарижапов',
    metaDescription: 'LMS под ключ: каталог курсов и потоки, продажи и оплаты, кабинеты учеников и преподавателей, домашки, прогресс, сертификаты, аналитика. Без процентов с оборота. Российский стек.',
  },
  {
    slug: 'platforma-set-franshiza', published: true, segment: 'Флагманы',
    niche: 'Сеть и франшиза', icon: 'ph-buildings',
    title: 'Цифровая платформа для сети филиалов и франшизы',
    tagline: 'Единая система для всех точек: запись, лояльность, аналитика, обучение и контроль стандартов — масштабируйтесь без хаоса.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: franshizaBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/cto-as-a-service/', label: 'CTO-as-a-service' }],
    relatedBlog: [{ url: '/blog/crm-dlya-malogo-biznesa-2026/', label: 'CRM для бизнеса' }, { url: '/blog/cifrovizaciya-biznesa-buryatiya-zabaykalye-2026/', label: 'Цифровизация бизнеса' }],
    faq: [
      { q: 'Зачем единая платформа сети?', a: 'Чтобы все точки работали по одним стандартам, данные были сводными, а владелец видел картину по сети и по каждой точке.' },
      { q: 'Помогает запускать франшизу?', a: 'Да: новая точка/франчайзи стартует по готовому шаблону с обучением и контролем качества — единый бренд в цифре.' },
      { q: 'А операционное управление?', a: 'Платформа даёт инструменты и контроль; операционкой точек управляете вы и ваши управляющие.' },
    ],
    metaTitle: 'Цифровая платформа для сети филиалов и франшизы | Чимитдоржи Дарижапов',
    metaDescription: 'Платформа для сети и франшизы: единая запись/лояльность/аналитика по всем точкам, база знаний и обучение, контроль стандартов, ролевой доступ. Масштабирование без хаоса.',
  },
  {
    slug: 'korporativnyy-portal', published: true, segment: 'Флагманы',
    niche: 'Интранет и процессы', icon: 'ph-tree-structure',
    title: 'Корпоративный портал и автоматизация процессов',
    tagline: 'Интранет: база знаний, заявки и согласования, задачи, онбординг — внутренняя «нервная система» компании.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: portalBody,
    relatedServices: [{ url: '/services/business-automation/', label: 'Автоматизация бизнеса' }, { url: '/services/it-infrastructure/', label: 'IT-инфраструктура' }],
    relatedBlog: [{ url: '/blog/rag-sistemy-dlya-biznesa-2026/', label: 'RAG-системы' }, { url: '/blog/importozameshchenie-po-2026/', label: 'Импортозамещение ПО' }],
    faq: [
      { q: 'Что это даёт компании?', a: 'Сотрудники быстрее находят информацию и оформляют заявки/согласования, новички быстрее адаптируются, знания не теряются с людьми.' },
      { q: 'Это замена ERP или бухгалтерии?', a: 'Нет. Портал закрывает внутренние коммуникации, знания и процессы согласований, а не учёт и зарплату.' },
      { q: 'Безопасность?', a: 'Ролевой доступ, данные в РФ, по 152-ФЗ.' },
    ],
    metaTitle: 'Корпоративный портал и автоматизация процессов (интранет) | Чимитдоржи Дарижапов',
    metaDescription: 'Корпоративный портал под ключ: база знаний с поиском, заявки и согласования (отпуска, закупки, доступы), задачи, онбординг, справочник. Российский стек, 152-ФЗ.',
  },
  {
    slug: 'importozameshchenie-infrastruktura', published: true, segment: 'Флагманы',
    niche: 'IT-инфраструктура', icon: 'ph-hard-drives',
    title: 'Импортозамещение и переезд IT-инфраструктуры в РФ',
    tagline: 'Серверы, почта, облако, диск, софт и данные — на российский контур под ключ, без простоя и с соблюдением 152-ФЗ.',
    priceFrom: 'Бесплатная консультация', timeline: 'обсуждается', bodyHtml: importozamBody,
    relatedServices: [{ url: '/services/it-infrastructure/', label: 'IT-инфраструктура' }, { url: '/services/russian-stack-migration/', label: 'Миграция на российский стек' }],
    relatedBlog: [{ url: '/blog/importozameshchenie-po-2026/', label: 'Импортозамещение ПО' }, { url: '/blog/self-hosted-infrastruktura-2026/', label: 'Self-hosted инфраструктура' }],
    faq: [
      { q: 'Будет ли простой при переезде?', a: 'Нет, переносим поэтапно с резервными копиями и проверкой — бизнес продолжает работать.' },
      { q: 'Зачем это нужно?', a: 'Зарубежные сервисы отключают и не принимают оплату, а хранение данных за рубежом нарушает 152-ФЗ. Российский контур снимает эти риски.' },
      { q: 'Лицензии вы покупаете?', a: 'Лицензии оформляете вы; я подбираю аналоги, переношу данные и настраиваю.' },
    ],
    metaTitle: 'Импортозамещение и переезд IT-инфраструктуры в РФ под ключ | Чимитдоржи Дарижапов',
    metaDescription: 'Перевод IT-контура на российские решения: серверы, почта, облако, диск, мессенджеры, софт и данные — под ключ, без простоя, по 152-ФЗ. Снижение санкционных рисков.',
  },
  {
    slug: 'cto-as-a-service', published: true, segment: 'Флагманы',
    niche: 'IT-директор на аутсорсе', icon: 'ph-compass',
    title: 'CTO-as-a-service: IT-директор на аутсорсе',
    tagline: 'Стратегия, архитектура, управление подрядчиками и развитие IT по подписке — для растущего бизнеса без своего IT-директора.',
    priceFrom: 'Бесплатная консультация', timeline: 'подписка / разовый аудит', bodyHtml: ctoBody,
    relatedServices: [{ url: '/services/cto-as-a-service/', label: 'CTO-as-a-service' }, { url: '/services/it-mentoring/', label: 'IT-менторство' }],
    relatedBlog: [{ url: '/blog/mvp-to-production-3-mesyatsa-2026/', label: 'MVP за 3 месяца' }, { url: '/blog/skolko-stoit-sayt-2026/', label: 'Сколько стоит сайт' }],
    faq: [
      { q: 'Чем это отличается от разработки?', a: 'Это управленческая подписка: стратегия, архитектура, выбор технологий и контроль подрядчиков — а не написание кода по задаче.' },
      { q: 'Зачем, если можно нанять CTO?', a: 'Штатный IT-директор дорог и часто преждевременен. Аутсорс даёт ту же экспертизу дешевле и без привязки к одному вендору.' },
      { q: 'В каком формате работаем?', a: 'От разового аудита и консультаций до плотного ежемесячного сопровождения — под ваш этап.' },
    ],
    metaTitle: 'CTO-as-a-service: IT-директор на аутсорсе по подписке | Чимитдоржи Дарижапов',
    metaDescription: 'CTO-as-a-service: IT-стратегия и архитектура, выбор технологий, управление подрядчиками, бюджет IT, безопасность и 152-ФЗ, оценка разработчиков. Дешевле штатного IT-директора.',
  },
];

// Обогащение: экспертные структурированные блоки (pains/beforeAfter/deliverables/
// process/result/objections/whyMe). При наличии — заменяют «сухой» bodyHtml.
const _RICH = Object.assign({},
  require('./offers-rich-1.js'), require('./offers-rich-2.js'), require('./offers-rich-3.js'),
  require('./offers-rich-4.js'), require('./offers-rich-5.js'), require('./offers-rich-6.js'),
  require('./offers-rich-7a.js'), require('./offers-rich-7b.js'),
  require('./offers-rich-8a.js'), require('./offers-rich-8b.js'),
  require('./offers-rich-9a.js'), require('./offers-rich-9b.js'),
  require('./offers-rich-10a.js'), require('./offers-rich-10b.js'),
  require('./offers-rich-11a.js'), require('./offers-rich-11b.js'), require('./offers-rich-11c.js'),
  require('./offers-rich-12a.js'), require('./offers-rich-12b.js'), require('./offers-rich-12c.js'), require('./offers-rich-12d.js'),
  require('./offers-rich-13a.js'), require('./offers-rich-13b.js'),
  require('./offers-rich-14a.js'), require('./offers-rich-14b.js'),
  require('./offers-rich-15a.js'), require('./offers-rich-15b.js'), require('./offers-rich-15c.js'));
for (const o of _ALL_OFFERS) {
  const r = _RICH[o.slug];
  if (r) { Object.assign(o, r); delete o.bodyHtml; }
}

// --- Перегруппировка по понятным заказчику рубрикам ---------------------
// Разбиваем разросшиеся «Автоматизация» (39) и «Флагманы» (19) на отраслевые
// и тематические рубрики. Один источник правды — менять только здесь.
const SEG_REMAP = {
  // Отрасли
  'kofeynya': 'HoReCa и общепит',
  'obshchepit': 'HoReCa и общепит',
  'dostavka-dlya-seti': 'HoReCa и общепит',
  'ai-prognoz-zakupok-horeca': 'HoReCa и общепит',
  'kontrol-franshizy-horeca': 'HoReCa и общепит',
  'upravlenie-setyu-restoranov': 'HoReCa и общепит',

  'lichnyy-kabinet-dolshchika': 'Недвижимость',
  'vr-tury-nedvizhimost': 'Недвижимость',
  'ai-ocenka-nedvizhimosti': 'Недвижимость',
  'crm-agentstvo-nedvizhimosti': 'Недвижимость',
  'platforma-prodazh-novostroek': 'Недвижимость',

  'tms-marshrutizaciya': 'Логистика и склад',
  'wms-ai-prognoz': 'Логистика и склад',
  'treking-gruzov': 'Логистика и склад',
  'upravlenie-avtoparkom': 'Логистика и склад',
  'b2b-portal-opt': 'Логистика и склад',

  'ai-uderzhanie-fitnes': 'Спорт и фитнес',
  'biometriya-dostup-fitnes': 'Спорт и фитнес',
  'prilozhenie-kluba-ai-trener': 'Спорт и фитнес',
  'avtomatizaciya-fitnesa': 'Спорт и фитнес',
  'upravlenie-setyu-fitnes': 'Спорт и фитнес',

  'cifrovizaciya-proizvodstva': 'Производство и стройка',
  'importozameshchenie-asu-tp': 'Производство и стройка',
  'crm-stroitelnaya-kompaniya': 'Производство и стройка',

  'zapis-salon-krasoty': 'Малый бизнес и услуги',
  'bystryy-start-sayt': 'Малый бизнес и услуги',
  'zayavki-klining-uslugi': 'Малый бизнес и услуги',
  'himchistka-prachechnaya': 'Малый бизнес и услуги',
  'zakazy-tipografiya': 'Малый бизнес и услуги',
  'avtoservis': 'Малый бизнес и услуги',
  'it-yuridicheskaya-firma': 'Малый бизнес и услуги',
  'it-fotograf-videograf': 'Малый бизнес и услуги',
  'it-event-agentstvo': 'Малый бизнес и услуги',
  'bronirovanie-arendy': 'Малый бизнес и услуги',
  'bronirovanie-kovorking': 'Малый бизнес и услуги',
  'bronirovanie-otel-glamping': 'Малый бизнес и услуги',
  'crm-turagentstvo': 'Малый бизнес и услуги',
  'dostavka-bot-povtornye-zakazy': 'Малый бизнес и услуги',
  'lichnyy-kabinet-klienta': 'Малый бизнес и услуги',
  'chestnyy-znak-markirovka': 'Малый бизнес и услуги',

  // AI и технологии (из «Флагманов» в профильную рубрику)
  'ai-vnedrenie-90-dney': 'Корпоративный AI',
  'korporativnoe-obuchenie-ai': 'Корпоративный AI',
  'ai-otdel-prodazh-podderzhki': 'Корпоративный AI',

  // Комплексные платформы — кросс-отраслевые крупные проекты
  'cifrovizaciya-pod-klyuch': 'Комплексные платформы',
  'korporativnyy-portal': 'Комплексные платформы',
  'dashboard-rukovoditelya': 'Комплексные платформы',
  'zapusk-saas-produkta': 'Комплексные платформы',
  'marketplace-pod-nishu': 'Комплексные платформы',
  'platforma-set-franshiza': 'Комплексные платформы',
  'importozameshchenie-infrastruktura': 'Комплексные платформы',
  'cto-as-a-service': 'Комплексные платформы',
  'tech-cofounder-zapusk': 'Комплексные платформы',
  'mobilnoe-prilozhenie-pwa': 'Комплексные платформы',
  'integraciya-sistem': 'Комплексные платформы',
  'platforma-loyalnosti-uderzhaniya': 'Комплексные платформы',
  'it-granty-gospodderzhka': 'Комплексные платформы',
  'audit-i-uskorenie-sayta': 'Комплексные платформы',
  'edo-elektronnaya-podpis': 'Комплексные платформы',
};
for (const o of _ALL_OFFERS) {
  if (SEG_REMAP[o.slug]) o.segment = SEG_REMAP[o.slug];
}

module.exports = _ALL_OFFERS;
