server {
    listen 80;
    server_name 8d4a125849ec.vps.myjino.ru;

    root /var/www/universe_buryat;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /images/ {
        alias /var/www/universe_buryat/images/;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location /posts.json {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache";
    }
}
